### ISSUE TITLE
Collection empty when changing route

### ISSUE THREAD

**Issue by blntylmn** [Urigo/angular-meteor#1002]
I am following the angular 1 tutorial with meteor-angular 1.3.1. In Step 9 when I change the route from parties list to party detail Parties collection (i mean client side) is empty if I not subscribe again in the party details controller. I think this should not the normal behaivour. Am I doing some thing wrong or is this a bug ?
Edit: I also downloaded your step 10 zip file and commented out "this.subscribe('parties');" line in the party details controller same thing happened.

**Comment by mgrivera** [comment]
Hi @blntylmn, 

I absolutely think you should control if subscription stops or no (when changing routes). This doesn't seem so in the new api. 

In the previous angular-meteor api: 

1. **$meteor.subscribe**: won't stop the subscription if you change routes 
2. **$scope.$meteorSubscribe**: will stop the subscription always, when $scope is destroyed

I've not used the new api yet, but according to what I've read, the subscription is stopped always, when $scope is destroyed. As per (new api) documentation: 

this.subscribe(...) 

> The subscription will stop automatically when it's context ($scope) is destroyed.

I think you should have control as when to stop or leave the collections alive (in client) when changing routes. 

Am I wrong in the previous reasoning? Thanks and bye ...

**Comment by mgrivera** [comment]
Maybe for a client collection to persist when changing routes, we should just use *meteor* subscription: 

Meteor.subscribe(...) 

Any thoughts? Thanks and bye ...

**Comment by ThomsC** [comment]
you can do the subscription in an abstract route, then your two routes are sub route to the abstract one in this case the subscription will persist.

**Comment by Urigo** [comment]
question - closing
