### ISSUE TITLE
http://www.angular-meteor.com/api/1.3.1/ is not working

### ISSUE THREAD

**Issue by pacozaa** [Urigo/angular-meteor#1003]
http://www.angular-meteor.com/api/1.3.1/ is not working 

I think you didn't redirect this link to http://www.angular-meteor.com/api/1.3.1/helpers

![image](https://cloud.githubusercontent.com/assets/3154089/11996709/841cf50a-aa9b-11e5-8010-d6cba69e0ad0.png)

**Comment by dotansimha** [comment]
Thanks @pacozaa , 
Fixed it in https://github.com/Urigo/angular-meteor/pull/1006 , waiting for @Urigo  to merge.

**Comment by Urigo** [comment]
Merged and deployed.
