### ISSUE TITLE
v1.3.1 RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by veeramarni** [Urigo/angular-meteor#1008]
I'm getting below error when i use collections from helpers functions. If i just pull without adding reactivity it works fine. 

![130f74a8-ab24-11e5-8494-31c411781abe](https://cloud.githubusercontent.com/assets/3382355/12004596/113f2280-ab34-11e5-9cc1-80b99738e63b.png)

```
function displayCtrl($scope, $reactive....){
  $reactive(this).attach($scope);
 
 this.helpers({
    images() {
      return Images.find();
   }
})

// getAllimages() fails when i navigate to this view
getAllImages();

  function getAllImages(){
    return function(){
      imagesUrl = [];
      _.each(this.images, function(val, no){
        imagesUrl.push(val.url());
      })
      return imagesUrl;
    }
  }
```
But if i replace this.images with Images.find().fetch() , i don't have this issue. 
```
 function getAllImages(){
    return function(){
      var images =  Images.find().fetch();
      imagesUrl = [];
      _.each(images, function(val, no){
        imagesUrl.push(val.url());
      })
      return imagesUrl;
    }
  }
```

**Comment by dotansimha** [comment]
@veeramarni can you provide the actual code in a git repo so I can test and debug it in my localhost?

**Comment by dotansimha** [comment]
@veeramarni 
It was a bug caused by an unnecessary watcher that created. 
Fixed, and will be deployed soon in 1.3.2!

**Comment by Urigo** [comment]
Deployed

**Comment by veeramarni** [comment]
Thanks, i will test it.
