### ISSUE TITLE
$reactive not available when used with meteor-client-side 

### ISSUE THREAD

**Issue by elmor34** [Urigo/angular-meteor#1011]
I'm using 

ionicframework 1.2.2
angular-meteor  1.3.1
meteor-client-side 0.2.3

when I use $reactive in controller, I get =>
*Error: [$injector:unpr] Unknown provider: $reactiveProvider <- $reactive <- HomeCtrl*

Regards
Gokhan

**Comment by dotansimha** [comment]
Hi @elmor34 , it's a duplication of #985
