### ISSUE TITLE
1.3.2: best practice for subscribe and helper

### ISSUE THREAD

**Issue by leizard** [Urigo/angular-meteor#1021]
Hi, I now updated successfully to 1.3.2 from Bower (Thank you very much for your work) . But during the migration, I'm a little confuse about new subscribe and helper support. 
In the example, you use subscribe and helper like this : 

```
        $reactive(this).attach($scope);

        this.age = 10;

        this.subscribe('users', function() {
            return [this.age];
        });

        this.helpers({
            users: function () {
                return Users.find({});
            }
        });
```

But it seems not working (for me), because the helper users could not get enough data when the subscribe('users') is not done. So I have to do something like this:

```
        $reactive(this).attach($scope);

        this.age = 10;

        this.subscribe('users', function() {
            return [this.age];
        }, {
            onReady: function() {
                $scope.helpers({
                    users: function () {
                        return Users.find({});
                    }
                });
            }
        });
```

I have to put the helpers definition inside onReady event of the subscription. It works, but make the code uglier: In the onReady event, I have to use $scope.helpers because this.helpers would make it undefined method. 
Did I do anything wrong ? Or I should use it the "ugly" way ?

**Comment by Deadly0** [comment]
@leizard How do you use helper `users`? What the reason to use `onReady` to define helpers? Helpers will automatically update template and trigger autorun function when data arrives.

**Comment by leizard** [comment]
Yeah indeed. Thanks to your confirmation, I looked again and It s just my subscribe issue. I fixed it and now use helpers and subscribe the old way. Everything now works like a charm and even performance is better. 
Thank you very much
