### ISSUE TITLE
Tutorial step 12 - Pagination sort order

### ISSUE THREAD

**Issue by blackpr** [Urigo/angular-meteor#1023]
At step 12.14 I think we need to use getReactively for the sort order to work
old
```javascript
this.updateSort = () => {
	this.sort = {
	  name: parseInt(this.orderProperty)
	}
};
```
new
```javascript
this.updateSort = () => {
	this.sort = {
	  name: parseInt(this.getReactively('orderProperty'))
	}
};
```

**Comment by DAB0mB** [comment]
Normally your'e right, but for angular-meteor 1.3 this is a valid syntax.
In angular-meteor 1.4 it will be deprecated and the use for 'getReactively' will be necessary.

**Comment by Urigo** [comment]
@DAB0mB he is right, the update sort won't refresh with this syntax, we should update the tutorial

**Comment by DAB0mB** [comment]
https://github.com/Urigo/meteor-angular-socially/pull/96

**Comment by Urigo** [comment]
fixed in the new version of the tutorial
