### ISSUE TITLE
1.3.2 reactive helpers with Meteor.call

### ISSUE THREAD

**Issue by ThomsC** [Urigo/angular-meteor#1025]
Hi,

When I do something like this : 

```javascript
reactiveContext.helpers({
            start_period: moment().subtract(1, 'months').format('L'),
            end_period: moment().add(1, 'months').format('L'),
            thePeriod: () => {
                Meteor.call('periodeOperations', this.getReactively('start_period'), this.getReactively('this.end_period'), function (err, data) {
                    console.log(data);
                    return data;
                });
            }
});
```

thePeriode is being execute each time reactives values change but the view does not update at all. It's like `thePeriod` was empty.

Is there a good practice to do this king of thing ?

**Comment by DAB0mB** [comment]
The `data` returned by `Meteor.call` is not saved anywhere and therefore will not be presented in the view. You should do something like the following instead:

```js
this.period = {
  start: moment().subtract(1, 'months').format('L');
  end: moment().add(1, 'months').format('L');
};

this.autorun(() => {
  Meteor.call('calculate', this.getReactively('period', true), function (err, data) {
      if (err) return console.error(err);
      this.data = data;
  });
});
```

As you can see there is no need for helpers, `getReactively` and `autorun` does everything you need, once `period` property is changed the calculation method will be called all over again.

**Comment by ThomsC** [comment]
your solution is pretty simple thanks !

Is there a way to call the autorun function again without changing `period` as I click on a button for instance ?

**Comment by Urigo** [comment]
@ThomsC you can place the whole logic inside a separate function and place that function inside the autorun and when clicking a button call that function directly
