### ISSUE TITLE
Code in Zipfile at the beginning of Tutorial Step 11 does not compile

### ISSUE THREAD

**Issue by Sauermann** [Urigo/angular-meteor#1027]
The zipfile https://github.com/Urigo/meteor-angular2.0-socially/archive/step_09.zip
available at the top of http://www.angular-meteor.com/tutorials/socially/angular2/running-your-app-on-android-or-ios-with-phoneGap
does not compile.
Error message:

    client/parties-form/parties-form.ts (4, 31): Cannot find module 'angular2/angular2'.

**Comment by Urigo** [comment]
@Sauermann I've deployed a new version, can you check if that's still the case?

**Comment by Sauermann** [comment]
Looks good. Thanks for the update!
