### ISSUE TITLE
Extension of type declaration missing in tutorial step 9

### ISSUE THREAD

**Issue by Sauermann** [Urigo/angular-meteor#1028]
In Step 9 (http://www.angular-meteor.com/tutorials/socially/angular2/privacy-and-publish-subscribe-functions) of the tutorial it should be mentioned that the Party type declaration in "typings/party.d.ts" needs to be extended by

    public: boolean

**Comment by Urigo** [comment]
@Sauermann can you check if that is still the case after the new tutorial version deployed today?

**Comment by Sauermann** [comment]
Thanks for your answer.
But the changes did not yet appear on the mentioned page. (To be sure I cleared my browser cache and cookies)

**Comment by Urigo** [comment]
@Sauermann it is now (just before step 9.4)
Please let me know if you are still not able to see it.

**Comment by Sauermann** [comment]
Looks good. Thanks!
