### ISSUE TITLE
Update to 1.3.2 cause "error: connect ECONNREFUSED"

### ISSUE THREAD

**Issue by michaelszt** [Urigo/angular-meteor#1031]
When I update my app to 1.3.2, I get error message:

While downloading angular@1.3.2...:
error: connect ECONNREFUSED

While downloading angular-meteor-data@0.0.9...:
error: connect ECONNREFUSED

While downloading angular-with-blaze@1.3.2...:
error: connect ECONNREFUSED

I tried many times.

**Comment by ThomsC** [comment]
I did it and everything worked great...
