### ISSUE TITLE
How can i do logout callback

### ISSUE THREAD

**Issue by yobre** [Urigo/angular-meteor#1032]
Hi Urigo..
I'm trying to catch the event LOGOUT to perform a redirect on the homepage, nothing exceptional.
For authentication I'm using `<blaze-template name = "loginButtons"> </ blaze-template>`

For now the only thing I could do is to fill in the file that contains the basic routes, the following code:

``` javascript
.run ($ rootScope, $ state) ->

   Meteor.logout (() ->
     console.log "Meteor.logout ()"
     $ state.go ("main")
   )
```

But that is read and executed only to refresh later and not immediately.

My question is: what method I can use to get an immediate redirect to the homepage?

**Comment by ThomsC** [comment]
Can't you do that ?

```javascript

Meteor.logout();
$state.go ("main");
```

**Comment by Urigo** [comment]
@yobre you can $watch the current user and change route according to that
