### ISSUE TITLE
Digest not running after Accounts.createUser

### ISSUE THREAD

**Issue by kamilkisiela** [Urigo/angular-meteor#1034]
I think this is a bug but correct me if I'm wrong.
If so then I can fix it and submit PR.

---

Let's say I have some variable with `false` as initial value and I use `getReactively()` on it.

I'm changing value:
```javascript
this.foo = true; // this.propertiesTrackerDeps[k].changed() triggers
```

Then I want to 
```javascript
this.foo = 1; // ... triggers
```

Next, it goes back to initial value
```javascript
this.foo = false; // ... does not trigger
```

And yes, I could use `undefined` as initial value to avoid this, but it's just a workaround.

It's all about this line and `newValue !== initialValue`:
https://github.com/Urigo/angular-meteor/blob/master/packages/angular-meteor-data/modules/angular-meteor-reactive-context.js#L132

---

### Edit

Value changes properly. It's not working because of `Accounts.createUser()`.

When I change `this.foo` to anything in callback (with arrow function) it won't work.

Example:

```javascript
sampleMethod() {
    this.foo = true;
    Accounts.createUser({ ... }, () => {
        this.foo = false;
    });
}
```

It's weird because here it works:

```javascript
sampleMethod() {
    this.foo = true;
    this.$timeout(() => {
        this.foo = false;
    }, 500);
}
```

**Comment by Urigo** [comment]
I think the reason might be that the callback in running outside of Angular's scope...
In the older implementation we wrapped that callback with a $q promise so it was inside Angular context.

Try to run $digest manually to see if that's the problem.

If so, I wonder what will be the best way to solve that and still stay close to the original Meteor API

**Comment by kamilkisiela** [comment]
I forgot to update this issue :)

Few days ago I wrote the service called `UsePromise`.

Usage:

```javascript
UsePromise.on(Accounts.createUser, { ... })
    .then(() => {
        this.foo = false;
    });
```

So yes, @Urigo you're right. `$q` is very helpful.

**Comment by Urigo** [comment]
this is interesting, can you share the code?

**Comment by kamilkisiela** [comment]
`AssignInjectables` is a class to assign injectables to the object scope.

**UsePromise**: 

```javascript
const { SetModule, Service, Inject } = angular2now;

SetModule('lib');
@Service({
  name: 'UsePromise'
})
@Inject(['$q'])
class UsePromise extends AssignInjectables {

  constructor() {
    super(arguments);
  }

  on(func, ...args) {
    const deferred = this.$q.defer();

    args.push(function resolver(err, data) {
      if (err) {
        deferred.reject(err);
      } else {
        deferred.resolve(data);
      }
    });

    func.apply(undefined, args); // is there a need for using another context?

    return deferred.promise;
  }
}
```

**AssignInjectables**:

```javascript
class AssignInjectables {
    constructor(args) {
      if (args && args.callee) {
        const injected = args.callee.$inject;

        if (injected && injected.length) {
          for (let i = 0; i < injected.length; i++) {
            this[injected[i]] = args[i];
          }
        }
      }
    }
  }
```

**Comment by ozsay** [comment]
We chose an API that is closer to the Meteor API for meteor methods.

In 1.3.6 to call a meteor method you will do: 
```js
this.call('add', 1, 2, (err, result) => {
  if (!err)
    $scope.result = result;
});
```
This will call the `add` meteor method and set `$scope.result` in a digestion cycle.

I think it would be best to fix this issue similarly:
```js
this.call(Accounts.createUser, { ... }, (err, result) => {
  if (!err)
    this.foo = false;
});
```

This should update `this.foo` properly.

**Comment by Urigo** [comment]
Maybe we should still continue to have something like this - https://github.com/Urigo/angular-meteor/blob/master/packages/angular-meteor-data/modules/angular-meteor-user.js#L70-L84
but with callbacks instead of promises so it will be with a digest cycle but more similar to Meteor's accounts API.
We could use the same solution as we use in `this.call`

**Comment by Urigo** [comment]
The problem with this is that every time there is a new Accounts solution (for instance - Accounts phone number), we have to update it here, would love to hear nice ways of making that part easier

**Comment by ozsay** [comment]
Another possible API:

```js
Accounts.createUser({...}, this.digested((err, result) => {
  if (!err)
    $scope.result = result;
}));
```

> we can make a better name than "digested"

**Comment by ozsay** [comment]
We chose the last comment as the implemented API. already been done to 1.3.6

**Comment by kamilkisiela** [comment]
@ozsay Great :+1:

**Comment by Urigo** [comment]
`angular@1.3.6-beta.1` was released.
Please check and let me know if that fixed the issue.

**Comment by Urigo** [comment]
`angular@1.3.6` is out.
