### ISSUE TITLE
Wrong archives linked in tutorial

### ISSUE THREAD

**Issue by ChrisLasar** [Urigo/angular-meteor#1037]
Thanks for your great work on angular-2.0 and meteor.

I tried run the tutorial by downloading the archive zips linked at http://ng-meteor.meteor.com/tutorials/angular2/adding-removing-objects-and-angular-event-handling.

As a newbie I run into a couple of small problems. Reasons for these problems are all fixed in the repository (https://github.com/Urigo/meteor-angular2.0-socially). However the tutorial still links the wrong archives, e.g. release "step_03", which still imports 'angular2/angular2', instead of "step_3" which already fixes these issues.

I apologize if this is not the right place to report this issue, but the "improve this doc" link in the tutorial does not work to fix it myself. However it links to this repository.

BTW: After I first discovered how to fix the issues mentioned above myself, I had to delete my browses cache manually to make sure "app.html" gets reloaded. I just discovered by chance that it always comes from the cache. Is this behaviour is expected?

**Comment by Urigo** [comment]
@ChrisLasar is that still the case with the new deployed version?

**Comment by ChrisLasar** [comment]
Dear @Urigo ,
thanks it seems to be fixed now.
