### ISSUE TITLE
Login problem still goes on in 1.3.2  in spite of 

### ISSUE THREAD

**Issue by gaykan** [Urigo/angular-meteor#1039]
I can create a user using $meteor.createUser, but cannot login with $meteor.loginWithPassword.
It was told by @idanwe that it was fixed in 1.3.2.

( By the way I 'm using Ionic and meteor-client-side ) 

Problem is detailed as 

I upgraded, but it is still the same, but I get two different messages for login.

**For a previously created I get**

>*Error: Match failed [400]
column: 26050
details: undefined
error: 400
errorType: "Meteor.Error"
line: 1
message: "Match failed [400]"
reason: "Match failed"

**For a create and in success code  loginWithPassword I get ( no problem on createUser )**

>*Error: string.charCodeAt is not a function. (In 'string.charCodeAt(n)', 'string.charCodeAt' is undefined)
Utf8Encode@http://localhost:8100/lib/accounts-password-client-side.bundle.min.js:1:2442
SHA256@http://localhost:8100/lib/accounts-password-client-side.bundle.min.js:1:2985
_hashPassword@http://localhost:8100/lib/accounts-password-client-side.bundle.min.js:1:27418
loginWithPassword@http://localhost:8100/lib/accounts-password-client-side.bundle.min.js:1:27073
http://localhost:8100/lib/angular-meteor-1.3.2/dist/angular-meteor.bundle.js:10912:24*

**Comment by davidbonachera** [comment]
Yup i have the error on the 1.3.1.
```Exception while invoking method 'login' Error: Match error: Match error: Failed Match.Where validation in field username in field user.username```

**Comment by ThomsC** [comment]
you can use this : `Meteor.loginWithPassword(vm.user.email, vm.user.password, function (err) { ... }`

http://docs.meteor.com/#/full/meteor_loginwithpassword

**Comment by gaykan** [comment]
I already use create with no problem. 
But when I try to login with following code which is the same as your advice, I get error 

`var email = "serdaronal@letsearn.net";
    var password = "123456";
    $meteor.loginWithPassword(
      email,
      password
    ).then(function() {
        console.log('Login SERDAR success');
      }, function(err) {
        console.log('Login SERDAR error - ', err);
      });`

**Comment by ThomsC** [comment]
No it is not the same. You use `$meteor`which is deprecated and `.then()` in the link to the official documentation  of meteor I gave you doesn't exist.

Try this :

```javascript
var email = "serdaronal@letsearn.net"; 
var password = "123456"; 
Meteor.loginWithPassword( email, password, function(err) {
 	if(err){
 	console.log('Login SERDAR error - ', err);
 	}
 	else{
 	console.log('Login SERDAR success');
 	}
});

```

**Comment by gaykan** [comment]
No difference at all

'Error: Match failed [400]
column: 26050
details: undefined
error: 400
errorType: "Meteor.Error"
line: 1
message: "Match failed [400]"
reason: "Match failed"
sourceURL: "http://localhost:8100/lib/meteor-client-side.bundle.min.js"
stack: "errorClass@http://localhost:8100/lib/meteor-client-side.bundle.min.js:1:26050↵_livedata_result@http://localhost:8100/lib/meteor-client-side.bundle.min.js:7:27263↵onMessage@http://localhost:8100/lib/meteor-client-side.bundle.min.js:7:9487↵http://localhost:8100/lib/meteor-client-side.bundle.min.js:6:29311↵forEach@[native code]↵forEach@http://localhost:8100/lib/meteor-client-side.bundle.min.js:1:1472↵onmessage@http://localhost:8100/lib/meteor-client-side.bundle.min.js:6:29255↵dispatchEvent@http://localhost:8100/lib/meteor-client-side.bundle.min.js:5:17343↵_dispatchMessage@http://localhost:8100/lib/meteor-client-side.bundle.min.js:6:3602↵_didMessage@http://localhost:8100/lib/meteor-client-side.bundle.min.js:6:4789↵onmessage@http://localhost:8100/lib/meteor-client-side.bundle.min.js:6:7663"'

**Comment by gaykan** [comment]
I think there is missing point in sever side that mismatches the client code !

**Comment by gaykan** [comment]
I have 
controlle     ==>  $rootScope 
index.html   ==> angular-meteor-1.3.2/dist/angular-meteor-auth.bundle.min.js
                           angular-meteor-1.3.2/dist/angular-meteor.bundle.min.js

app.js         ==>  'angular-meteor', 'angular-meteor.auth',
on server side 
.packages           angular-meteor-auth
                            angularui:angular-ui-router
                            dotansimha:accounts-ui-angular
any ide. Everthing seems ok!

**Comment by gaykan** [comment]
Problem comes from **okland:accounts-phone** package

**Comment by Urigo** [comment]
@gaykan so can you close that issue and reference the issue you opened?
also it's better if you will provide a reproduction
thanks

**Comment by gaykan** [comment]
When I forked Ionic-whatsappyo  try to add a loginWithPassword and create user method, 1.3.4 issued and it got inspirational. I created new issue for that. After solving 1.3.4 problem, I will create the case on forked version.
regards

**Comment by Lenin7** [comment]
Hey gaykan, are you using meteor 1.3 by any chance?
