### ISSUE TITLE
Unexpected Routing

### ISSUE THREAD

**Issue by jordangarside** [Urigo/angular-meteor#104]
**Problem:**
Angular-meteor is doing some kind of routing on my URLs without me specifying anything.
Even if I try to set html5Mode: false, it still tries to do something to my routes/URLs.

**Description:**
If I'm on the home page / and attempt to navigate to /trending with a simple href it will trigger the URL /trending on iron-router, then redirect back to the original URL /.
It's hard to explain so I made a [demo](https://github.com/jordangarside/angularMeteorDemo).
The links are in the Side Menu. The "trending" link is done through a normal href and the "about" link is done through an href on an ion-item. Neither link works and switching to ng-href doesn't help. There are lots of console.logs in the demo to understand what is happening.

**Why it Matters:**
It makes it impossible to use iron-router at the moment which is killing me.
I want to use angular for cordova development, but I don't want to have to re-do all my routing in angular. :(

**Comment by Urigo** [comment]
@dotansimha can you try to look into it?
I think you solved it on our project

**Comment by Urigo** [comment]
@jordangarside do you think that maybe you can provide a MeteorPad showing the problem?

**Comment by jordangarside** [comment]
@urigo Wow awesome, didn't even know it existed. I should be able to get it to work on there, I'll let you know soon.

**Comment by jordangarside** [comment]
@Urigo Here's the [MeteorPad](http://meteorpad.com/pad/znkD2GQd7KB5ze9vn/Angular-Meteor%20Routing%20Demo) of the problem.

**Comment by Urigo** [comment]
Ohh,
if you want to use angular only for cordova you can do something like this:

    if (Meteor.isCordova) {
      window.angularDemoModule = angular.module('angularDemo', ['angular-meteor', 'ui.router'])
    }

**Comment by jordangarside** [comment]
I ended up figuring out just about everything there is for this issue.

You really can't use Angular and Iron-Router. Iron-Router will cause Angular to think there is a state change because the URL has changed. When Angular thinks the state has changed it will recall all inline controllers and also re-execute angular directives, so things get messy very fast (you end up with multiply nested elements because Angular re-executed). There doesn't seem to be any simple way to prevent Angular's Router from watching the URL, at most you can suspend it (which isn't helpful if you want to use Iron-Router exclusively).

It is difficult to even navigate to Iron-Router routes as href's are watched by Angular. I found a way to navigated directly to Iron-Router links by doing a directive and using `Router.go("route")`, which will successfully skip over Angular's routing. The problem is that Angular still refreshes the page every time the URL changes, which isn't good because my layout doesn't change so Iron-Router keeps all the DOM elements in place for the layout. So every angular element on my layout was getting called every time the route changed.

In the end I just decided to make an angular route encompassing "/cordova/*" with a base template that has `<ion-nav-view>` so that Iron-Router doesn't update anything in that namespace.

**I think the docs should be changed so that they no longer suggest Iron-Router and Angular are compatible** *(unless someone can show me a demo where both are successfully used)*

**Comment by Urigo** [comment]
@jordangarside can you show me where to change the docs? or maybe pull request them?
