### ISSUE TITLE
Chapter 4 is totally wrong

### ISSUE THREAD

**Issue by bagusflyer** [Urigo/angular-meteor#1048]
It shows the code for chapter 3.

**Comment by blackpr** [comment]
Do you mean the step 4 at Angular-Meteor & ionic?
Maybe the same? 
https://github.com/Urigo/angular-meteor/issues/1047

**Comment by Urigo** [comment]
Can test with the new 1.3.3 version?

**Comment by Urigo** [comment]
@bagusflyer Chapter 4 where?

**Comment by Urigo** [comment]
@bagusflyer can you test it now?
