### ISSUE TITLE
Multiple layouts

### ISSUE THREAD

**Issue by shirk3y** [Urigo/angular-meteor#106]
Hi,
Is there any way to implement mutliple layouts that use distinct set of base DOM elements and stylesheets? I've found solution to do it in Iron Router, but I don't want to mix ui-router with it.
And wider question: Are there plans to totally separate from Blaze in the future?

**Comment by Urigo** [comment]
Hi @shirk3y , I'm sorry but I wasn't able to understand your question fully.

can you provide an example (in iron:router if that working for you)?

About separating from Blaze, the [new version](https://github.com/Urigo/angular-meteor/releases/tag/0.6.0-alpha) let's you use the .tpl file extension to make a file compile only with AngularJS and without Blaze.
You can have a look in the new tutorial:
http://angularjs.meteor.com/tutorial/step_00

**Comment by shirk3y** [comment]
@Urigo I mean something like http://www.manuel-schoebel.com/blog/iron-router-tutorial (See section "Specify a layout")

About new `.tpl` extension: Does it support alternative languages like `jade`?

**Comment by Urigo** [comment]
@shirk3y yes of course you can do few different layouts, this is a basic feature and the our tutorial is also specifying how to do that.

For more information, the best source will be [ui-router](https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views)

About .jade, Meteor gives each file extension only one build process so right now no jade in .tpl
You can watch and help in the discussion here:
https://github.com/MeteorCommunity/discussions/issues/51

**Comment by pbastowski** [comment]
Jade templates are now available through this angular-meteor package: https://github.com/civilframe/meteor-angular-jade/

**Comment by shirk3y** [comment]
@pbastowski Thanks a lot!

**Comment by Urigo** [comment]
@pbastowski nice job!
If you want, you can pull request the readme file and add your package to the bottom

**Comment by pbastowski** [comment]
Guys
This is not my package. I just found it myself yesterday and thought I'd share :)
Paul



On 12 Mar 2015, at 00:12, Uri Goldshtein <notifications@github.com> wrote:

@pbastowski nice job!
If you want, you can pull request the readme file and add your package to the bottom

**Comment by Urigo** [comment]
@pbastowski it doesn't mean you can't add it to the readme...   :)

**Comment by pbastowski** [comment]
Good point, Uri :)



On 12 Mar 2015, at 09:58, Uri Goldshtein <notifications@github.com> wrote:

@pbastowski it doesn't mean you can't add it to the readme... :)
