### ISSUE TITLE
Tutorial's login and sign up pages are broken

### ISSUE THREAD

**Issue by wsjwong** [Urigo/angular-meteor#1060]
I planned to start doing the tutorial but I found that the login and sign up pages are broken in the demo.
[Login](http://socially-step22.meteor.com/login)
[Sign up](http://socially-step22.meteor.com/register)

EDIT: I only find the pages broken in Safari (on both OS X and iOS).

**Comment by ShMcK** [comment]
I'm not having any issue on my computer/phone.

Could you try it again, or provide more system details?
