### ISSUE TITLE
Angular 2 Tutorial (Socially) Missing Parts 17 Onwards

### ISSUE THREAD

**Issue by sirockin** [Urigo/angular-meteor#1065]

**Comment by Urigo** [comment]
We are working on it :)
would love help in writing them

**Comment by sirockin** [comment]
Yes I appreciate that. They're very clear and well-written so I can see they take some time to produce. As a complete newbie to both Meteor and Angular I can't help with the writing. I'd be very happy to proof-read and test though.

**Comment by Urigo** [comment]
we got till 18 now.
soon will finish it all
