### ISSUE TITLE
Angular 2 Tutorial (Socially) Step 8 Zipped Code does not show parties

### ISSUE THREAD

**Issue by sirockin** [Urigo/angular-meteor#1067]
The link to the Step 8 zip file at the top of Step 9 works, but when run, no parties are displayed.

I wonder if this is due to 'meteor remove autopublish' (see top of Step 9) having been run before zipping.

**Comment by barbatus** [comment]
I downloaded 9th step and verified that search works as expected: I added one test party, tried to find it - it was found, then I searched by Palo Alto - it found correctly two parties.
What version of the package are you using?
I recommend to update to the latest and try it out once more.

**Comment by barbatus** [comment]
right, autopublish got wrongly into the Step 8. I just rebuilt the archive.
@Urigo I think we can close it.

**Comment by Urigo** [comment]
cool
