### ISSUE TITLE
Stuck on 9.12 - search not working

### ISSUE THREAD

**Issue by skl** [Urigo/angular-meteor#1069]
I've followed the tutorial as best I can and I've double-checked my work, however I'm struggling with the search feature - the client-side collection is not being filtered by location when I search. I know the (click) event is firing and PartiesList::search() is executing, I even checked the value parameter is coming through correctly.

It's just that `this.parties = Parties.find({ location: value });` seems to have no affect? Here's my code:
https://github.com/skl/learn-angular2-meteor/commit/23df1948692e780c9b3e697eec9977d7a55713d0

**Comment by barbatus** [comment]
I downloaded 9th step and verified that search works as expected: I added one test party, tried to find it - it was found, then I searched by Palo Alto - it found correctly two parties.
What version of the package are you using?
I recommend to update to the latest and try it out once more.

**Comment by barbatus** [comment]
Ok, I tested you repo as well. It works as expected for the test I described above too.
What's the exact case where it doesn't work for you?

**Comment by skl** [comment]
@barbatus thanks for testing :) Sorry, seems I was confused on a couple of points:

- I didn't realise you had to log in to search
- I didn't realise it had to be an exact match when searching
- I get weird behaviours/duplicate results if I don't delete the parties from the initial `loadParties()` - see http://i.imgur.com/Oa98ATG.gifv

But - following your test and I can confirm the search was working as you describe, thanks for taking the time to test my repo :)
