### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by scenaristeur** [Urigo/angular-meteor#1073]
at the bottom of the angular2 tuto : http://www.angular-meteor.com/tutorials/socially/angular2/dynamic-template
the link "step 3 "in the line "So, let's go to step 3 to learn how to bind our application to the great power of Meteor."
throw to angular1 tuto : http://www.angular-meteor.com/tutorials/socially/angular1/3-way-data-binding
instead of angular2 tuto

--> I was a little bit confused when I saw "Binding to Angular 1" thinking I was in Angular2 tuto.
 --> perharps a cool backgroundcolor or border of page to always know  if we are in tuto1 or tuto2 

+ § Declare a collection, after 3.1 , it is written : "The TypeScript compiler coverts .ts files to ES5, "
 didn't you mean "coNverts" ?

**Comment by ShMcK** [comment]
You're right, all of the tutorial links are linking to Angular 1. 

I'll put together a quick fix now.

**Comment by ShMcK** [comment]
[This commit](https://github.com/ShMcK/angular-meteor/commit/19dcfe60e60aa3e0ce91466968df9757190ddb07) should fix the issue of links pointing to the wrong tutorial.

**Comment by Urigo** [comment]
Thanks again @ShMcK !
