### ISSUE TITLE
something wrong with encode in "Initializing Data on Server Side" / 3.7  Load initial parties on server side

### ISSUE THREAD

**Issue by scenaristeur** [Urigo/angular-meteor#1074]
I'm french and in french, there are 'simple quote' and 'éàèù' :

1. in the loadParties() : i wanted to put "l'avion" but there is a problem with the simple quote --> I use double quote instead of simple quote and it's ok --> Does simple & double have the same fonctions, or do i have to escape with backslash ?
2. it seems that the accentued characters (éàèù) work bad with the "loadparties" function, although it worked fine with the console methode : accentued characters appear as question mark like '�' .
The problem is not in my browser : wrong characters are stored in the db (tested with db.parties.find({})

--> how could i send accentued characters to mongo / use utf-8 encoding ?

thanks Dav'

**Comment by ThomsC** [comment]
Quel problème as tu exactement avec les accents?

De mon côté tout fonctionne très bien je n'ai pas fait d'encodage spécial.

**Comment by Urigo** [comment]
were you able to solve this?

**Comment by Urigo** [comment]
closed because inactive
