### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined...at null.loginWithGoogle

### ISSUE THREAD

**Issue by HariharanIT** [Urigo/angular-meteor#1079]
Hi..i am using angular-meteor with my ionic app..
$meteor object having method name like loginWithGoogle,LoginWithFacebook..etc
but Meteor object does have this method...it only have loginWithPassword and token method for login.
Meteor.loginWithPassword working fine...The social login method undefined..in the Meteor object..

While trying $meteor.loginWithGoogle will cause the TypeError: Cannot read property 'apply' of undefined...at null.loginWithGoogle

And Meteor.loginWithGoogle will cause the loginWithGoogle method not defined..

i think i added all the required library in ionic client and meteor server..

**Comment by skl** [comment]
Did you `meteor add accounts-facebook`?

**Comment by HariharanIT** [comment]
Yeah.. I added that needed package..

**Comment by ozsay** [comment]
Hi, sorry for the late comment..

Can you provide a repository with a reproduction ?

**Comment by HariharanIT** [comment]
Hi,

https://github.com/HariharanIT/angular-meteor-socialLogin 
I am trying social login with angular-meteor in ionic CLI

In latest angular meteor version they..we don't need any wrapper(ie $meteor) to call meteor methods...but even though calling Meteor object directly didn't get any result..i am getting the error which i already mention in this issue.....

**Comment by Urigo** [comment]
closing as an old issue.
please check that it works with the latest tutorial (https://angular-meteor.com/tutorials/whatsapp2/ionic/setup) and if not, reopen
