### ISSUE TITLE
Angular 2.0 Tutorial Step 12 Incomplete Instructions for Anti:Fake

### ISSUE THREAD

**Issue by sirockin** [Urigo/angular-meteor#1080]
Step 12 provides a code snippet for generating 27 parties from Anti:Fake but does not give instructions for:
1/ Where to put the snippet (presumably server/load_parties.ts)
2/ How to install the anti:fake package: 'meteor add anti:fake'
3/ How to import the 'Fake' class

There is also no evidence of anti:fake in the zip download for Step 12.

**Comment by skl** [comment]
This is what I ended up doing to get it working:

Install package, as you say: `meteor add anti:fake`

*new file* `typings/fake.d.ts`:
```
declare var Fake: any;
```

*modify file* `server/load_parties.ts`:
```
/// <reference path="../typings/fake.d.ts" />

import {Parties} from 'collections/parties';

export function loadParties() {
    if (Parties.find().count() !== 0) {
        return;
    }

    for (var i = 0; i < 27; i++) {
        Parties.insert({
            name: Fake.sentence(50),
            location: Fake.sentence(10),
            description: Fake.sentence(100),
            public: true
        });
    }
};
```

Then `meteor reset` and `meteor` to clear all data and restart the app.

N.B. From what I've read this appears to be a TypeScript specific approach to working with this package, by default with Meteor you can just install the package and `Fake` is magically available globally without any additional setup. This is touched on further on in this tutorial.

**Comment by ShMcK** [comment]
I've proposed the following [changes](https://github.com/ShMcK/angular-meteor/commit/9ceb9b894b7e612b54b4bcd98789d525dec0f8f9) for the tutorial here:

```md
### Generating Mock Data

Thankfully, we have a helpful package called [_anti:fake_](https://atmospherejs.com/anti/fake), which will help us out with the generation of names, locations and other properties of new fake parties.

    meteor add anti:fake

So, with the following lines of code we are going to have 30 parties in total
(given that we already have three):

__`server/load_parties.ts`__:

    ...

    for (var i = 0; i < 27; i++) {
      Parties.insert({
        name: Fake.sentence(50),
        location: Fake.sentence(10),
        description: Fake.sentence(100),
        public: true
      });
    }


Fake is loaded in Meteor as a global, you may want to declare it for TypeScript.

__`typings/party.d.ts`__:

    declare var Fake: {
        sentence(words: number): string;
    }

Now reset the database (`meteor reset`) and run the app. You should see a list of 10 parties shown initially and 3 pages links just at the bottom.

Play around with the pagination: click on page links to go back and forth,
then try to delete parties to check if the current page updates properly.
```

**Comment by ShMcK** [comment]
However, once Meteor 1.3 hits I think it would be better to load [Faker.js](https://github.com/marak/Faker.js/) from NPM. That way data can look more realistic (for example, real location names).

**Comment by Urigo** [comment]
Thanks @ShMcK
