### ISSUE TITLE
Getting a single object from DB

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/angular-meteor#1081]
Hi all, 

I may be totally getting everything wrong, but I have to ask this simple question. 
I have a page that is supposed to display user profile information for any username given in url like this:
`mysite.com/someuser` 
This should open a page with controller that will load user data for particular user like this: 

```javascript
angular.module('myapp').controller('PubProfileCtrl', function($scope, $reactive, $stateParams){
	
	var vm = this;	
	
    $reactive(this).attach($scope);
	
	this.helpers({
		thisUser: () => Meteor.users.findOne({username: $stateParams.username})
	});			
	
	
	console.log(this.thisUser);
});
```
But instead, the console is printing undefined for user data.

Is there something else I should do to have this simple feature? I need this to be reactive for reasons of checking whether the user is online or not (using `konecty:user-presence` package).

Should I publish something on server side? Should I subscribe to something in controller? I don't think so. 

Thanks.

**Comment by gaykan** [comment]
By default, AngularJS will route URLs with a hashtag For Example:
```
http://www.example.com
http://www.example.com/#/about
```

So if you want to remove hashtag 

1. use     **$locationProvider.html5Mode(true)**  in routings part in config as .

```
app.config(function($routeProvider,$locationProvider) {
    $routeProvider.when('/home', {
        templateUrl:'/html/home.html'
    });
    $locationProvider.html5Mode(true);
})
```
2.  In html head add base tag
```
<html>
<head>
    <meta charset="utf-8">    
    <base href="/">
</head>
```
Hope, it is sufficient...

**Comment by MilosStanic** [comment]
Thanks @gaykan, but the point is not at all in parsing the $stateParams. 
It works perfectly fine. 
The point is getting a single object from database. It returns undefined.

**Comment by gaykan** [comment]
Ok.
What you do is ok.
But you need to publish the collections, you are using on server side, so that you may use on client side, 
with something like 

>  Meteor.publish('users', function ( search string or none ) {
    return Meteor.users.find( {  search string or none ) }, {fields: {profile: 1, emails:1, username:1}});
  });

for replicating your user data to your local database.

regards

**Comment by MilosStanic** [comment]
Thanks, it also seems I need to subscribe as well.
