### ISSUE TITLE
Problem at Angular 2 Tutorial Step 4.9

### ISSUE THREAD

**Issue by keithn** [Urigo/angular-meteor#1083]
I've got to this step, creating the form, it displays ok, I click Add and nothing happens.

It doesn't seem to be triggering the event handler... I've copied your code for the party form ts and html, doesn't seem to work either.  

No errors in either browser or meteor terminal

If I put a break point on the submit handler for the form, it ends up in an angular event handler, but doesn't seem to make it to addParty.

tried it by replacing it with all the code with the zip of the next page... Add definitely doesn't seem to work with that code either.

Not really knowing too much about angular, I'm not sure how to debug this.  I'm wondering if there's a recent update / packages  that might be causing an issue?

Keiths-MacBook-Pro:socially keithnicholas$ meteor list

package in the project :- 

autopublish            1.0.4  (For prototyping only) Publish the entire datab...

es5-shim               4.1.14  Shims and polyfills to improve ECMAScript 5 su...

insecure               1.0.4  (For prototyping only) Allow all database write...

jquery                 1.11.4  Manipulate the DOM using CSS selectors

meteor-base            1.0.1  Packages that every Meteor app needs

mobile-experience      1.0.1  Packages for a great mobile user experience

mongo                  1.1.3  Adaptor for using MongoDB and Minimongo over DDP

session                1.1.1  Session variable

standard-minifiers     1.0.2  Standard minifiers used with Meteor apps by def...

tracker                1.0.9  Dependency tracker to allow reactive callbacks

urigo:angular2-meteor  0.3.6_4  Angular2 and Meteor integration

**Comment by skl** [comment]
@keithn when this happened to me I had to move `addParty()` to `PartiesForm`, see https://github.com/skl/learn-angular2-meteor/commit/50a718c98df122e94a085d5c6bb0d24bdf952565

**Comment by futbotism** [comment]
+1

**Comment by MichalKrasowski** [comment]
In my case clearing browser caches helped.

**Comment by Urigo** [comment]
@kaihaase can you please try the new version of the tutorial and let me know if it still happens?

**Comment by Urigo** [comment]
fixed with the new version of the tutorial.
please reopen if that's not the case
