### ISSUE TITLE
Using angular-meteor with kendo ui grid

### ISSUE THREAD

**Issue by longxuanho** [Urigo/angular-meteor#1086]
Does anybody have an idea how I can using Kendo UI Grid with angular-meteor? It drives me crazy when trying to find out what the dataSource for kendo grid is.

**Comment by michaelszt** [comment]
I am using ui-grid,(http://ui-grid.info ), it works good for me.

**Comment by mgrivera** [comment]
You can also use *mquandalle:bower* to download and install ui-grid via bower ...
