### ISSUE TITLE
Support $watchCollection in getReactively

### ISSUE THREAD

**Issue by canac** [Urigo/angular-meteor#1088]
In my application it would be helpful if I could tell getReactively to use $watchCollection under the hood. Passing `objectEquality=true` to getReactively works, but it is far too slow for my application. I would be happy to try to put together a pull request if you are willing to include this feature.

**Comment by canac** [comment]
@Urigo I patched angular-meteor to add getCollectionReactively for my application, but it seems like that is something that other users could benefit from. Is that a feature that you would be interested in including in angular-meteor? If so, I would be happy to submit a pull request for it.

**Comment by Deadly0** [comment]
Useful function, +1

**Comment by Urigo** [comment]
@canac want to create a pull request to add that function?
