### ISSUE TITLE
Move tutorials into submodules

### ISSUE THREAD

**Issue by ShMcK** [Urigo/angular-meteor#1091]
Moving the Angular 1 & 2 tutorials into [submodules](http://git-scm.com/book/en/v2/Git-Tools-Submodules) would make it much easier to make future edits.

It would also focus issues & pull requests away from angular-meteor itself.

**Comment by Urigo** [comment]
done, I've just moved it into a separate repo with `git split`, I don't think we need to submodule it...
https://github.com/urigo/angular-meteor-docs
