### ISSUE TITLE
Act on subscription update

### ISSUE THREAD

**Issue by sebakerckhof** [Urigo/angular-meteor#1092]
let's say I have a chat message component (directive) which takes a message id, so something like `<chat-message message-id="vm.messageId"></chat-message>`

The controller subscribes to the message data:
```js
this.subscribe('chat.messageDetails',()=>[this.getReactively('messageId')]);
```

Now I'd like to have a variable that indicates whether the data is loading, how could I do this?

I can use the `onReady` function to know when the subscription returned and set `this.loading` to false. But how do I know when the subscription is being called, is there an equivalent `onStart`/`onCalled` or something?

**Comment by sebakerckhof** [comment]
Yeah, that's using the onReady function I mentioned, but I need something when the subscription is being called (to set `this.animation` to true)

**Comment by mgrivera** [comment]
Hi @sebakerckhof, 

I have never used *traker.autorun* but ... isn't it just to do something when a *reactive source* changes state? 

This is from angular-meteor's doc: 
```javascript
myModule.controller('MyCtrl', ['$scope', '$reactive', function($scope, $reactive) {
  $reactive(this).attach($scope);

  this.myVar = 10;

  this.autorun(() => {
    console.log('Autorun!!', this.getReactively('myVar'));
  });

  this.myVar = 50; // This will cause the autorun function method to run again
}]);
```

*this.autorun* is just a wrapper of metor's *traker.autorun*. 
 
This is from meteor's doc: 
```javascript
Tracker.autorun(function (c) {
  if (! Session.equals("shouldAlert", true))
    return;

  c.stop();
  alert("Oh no!");
});
```

Could you just check and see if this helps you? ...

**Comment by Deadly0** [comment]
@sebakerckhof i use this way to display loadbar
```
var deferred = $q.defer();
$scope.subscribe('collection',
	() => {
		deferred = $q.defer();
		$scope.dataLoading = deferred.promise; // Loading initialized
		return []
	}, () => {
		deferred.resolve(); // Loading finished
	}
);
```

**Comment by Urigo** [comment]
@sebakerckhof why not setting loading to true one line before the subscription is called?

**Comment by sebakerckhof** [comment]
@Urigo Because the subscription is reactive, and I want a loading indicator everytime it re-runs.
Of course I could do an autorun on the reactive subscription parameters, but I need to do this quite often, so it becomes cumbersome.

**Comment by kamilkisiela** [comment]
@sebakerckhof Maybe this is enough for you? [example](https://github.com/kamilkisiela/angular-meteor-1092/blob/master/imports/ui/app.js#L19-L29).

@Urigo I could make a PR that brings `onStart` callback to `subscribe` method.

**Comment by mgrivera** [comment]
@kamilkisiela That'd be great ... This is very needed because, that way you can control when a subscription starts ...

**Comment by sebakerckhof** [comment]
@kamilkisiela why didn't I think of that :p! very simple and good solution.

**Comment by kamilkisiela** [comment]
@sebakerckhof Do you also think that `onStart` it would be a good idea?

Putting stuff in function that returns arguments is quite weird :)

I've already have a working solution for this.

**Comment by sebakerckhof** [comment]
Yeah, I'd like onStart. Especially since I like to keep my subscription arguments one-liners ( `() => [this.getReactively(...)]`).
I guess you could just wrap that function in the angular-meteor library if an onStart-callback is defined, which is probably what you had planned.

**Comment by kamilkisiela** [comment]
Exactly :)

**Comment by Urigo** [comment]
@kamilkisiela would love to see a PR on that!

**Comment by kamilkisiela** [comment]
Done #1347

**Comment by Tallyb** [comment]
Now we just need the subscription equivalent of $http.pendingRequests.length...
