### ISSUE TITLE
Support Angular 2 Dependency Injection API

### ISSUE THREAD

**Issue by sirockin** [Urigo/angular-meteor#1093]
The MeteorComponent implementation closely couples the angular component with the server implementation, making it difficult to implement unit testing.

Would it be possible to incorporate the Angular 2 dependency injection API into the Angular Meteor architecture?

See also my post here:
https://forums.meteor.com/t/angular-2-meteor-dependency-injection/16216

**Comment by sirockin** [comment]
I realise I posed this as a question. Nonetheless, it does appear to be a necessary feature since without it a key facet of the Angular 2 framework is broken.

**Comment by Hongbo-Miao** [comment]
Hi @sirockin, dependency Injection is working perfect, just use it directly like in normal Angular 2 apps.

**Comment by sirockin** [comment]
Thanks @Hongbo-Miao. Would it be possible for you to post an example of how you would use a Service to wrap the back Meteor back end instead of using the MeteorComponent implementation. @Urigo perhaps you could integrate such an example into the tutorial?

**Comment by Hongbo-Miao** [comment]
@sirockin Oh, `MeteorComponent` does not affect Service.

```
import { Injectable } from '@angular/core';

@Injectable()
export class FooService {
  foo: string;

  Bar(){}
}
```

If you need use Angular2-Meteor API, just extends `MeteorComponent`.
```
import { Injectable } from '@angular/core';

@Injectable()
export class FooService extends MeteorComponent {
  constructor() {
    super();
  }

  foo: string;

  Bar(){
    // this.call
    // this.subscribe
    // this.autorun
  }
}
```

Also, have a check for [Subscribe data in Service using RxJS 5](https://forums.meteor.com/t/subscribe-data-in-service-using-rxjs-5/23258).

The new tutorial will have Service example for sure!

**Comment by sirockin** [comment]
Thanks @Hongbo-Miao
