### ISSUE TITLE
Guide line

### ISSUE THREAD

**Issue by ThomsC** [Urigo/angular-meteor#1097]
What is the best solution to do this king of thing :

```javascript

this.subscribe('userInfo', () => {
            vm.userInfo = $scope.$meteorObject(UsersInfos, {owner_id:Meteor.userId()});
        });
```

Obviously I don't want to use $meteorObject but helpers don't modify the database when I change the object in the view. Or am I missing something ?

**Comment by Deadly0** [comment]
@ThomsC, autobind is deprecated and will be removed in 1.4. Now you should update data in collection by yourself.

Also the second argument of `this.subscribe` not an onReady callback. This function should return array of arguments for subscription. Check the docs http://www.angular-meteor.com/api/1.3.2/subscribe

**Comment by ThomsC** [comment]
somehow it is working, should I do this instead:

```javascript

this.subscribe('userInfo', [], () => { ... });

```
?

Could you give me an example on how it should be update now please?

**Comment by Deadly0** [comment]
@ThomsC, yes, it's correct. But be ready for `$scope.$meteorObject` will be removed in 1.4

**Comment by ThomsC** [comment]
I understood but how do we do now?

**Comment by Deadly0** [comment]
@ThomsC I guess you have to read this article http://info.meteor.com/blog/angular-meteor-1.3 . It explains how to migrate from old API to new API with a lot of examples.

To replace autobind you should catch when your doc hav been changed and call MyCollection.update function (meteor native API)

**Comment by ThomsC** [comment]
ok thanks

**Comment by ThomsC** [comment]
ok like this : 

```javascript
this.helpers({
          party: () => {
            return Parties.findOne({_id: $stateParams.partyId});
          }
        });
 
        this.save = () => {
          Parties.update({_id: $stateParams.partyId}, {
            $set: {
              name: this.party.name,
              description: this.party.description
            }
          });
        };
```

but if I don't want a save button, do I need to $watch every field of my form, how  can I reproduce the behavior of autobind ?

**Comment by Deadly0** [comment]
@ThomsC, you can use deep watch to watch entire document or use ng-change on inputs if it's possible.

**Comment by ThomsC** [comment]
which one is better?

**Comment by ThomsC** [comment]
cause i did it with ng-change for now

**Comment by Deadly0** [comment]
@ThomsC i guess ng-change is better because deep watch may consume a lot of resources. Also you can look at $watchCollection but ng-change is more clear way.

**Comment by ThomsC** [comment]
ok thank you so much
