### ISSUE TITLE
$meteorCollection single element

### ISSUE THREAD

**Issue by hyperborea** [Urigo/angular-meteor#110]
With $collection.bindOne getting deprecated soon, are there any plans to introduce something similar for $meteorCollection? It's a very common use case to only work with a single item, so it would be neat not needing to access the first element of the collection, but to directly bind the element to the scope. Not sure how that should be done with the new API though.

The docs are still referencing to $collection.bindOne btw.

**Comment by Urigo** [comment]
I'm glad you asked :)

http://angularjs.meteor.com/api/meteorObject
http://angularjs.meteor.com/tutorial/step_06

**Comment by hyperborea** [comment]
Amazing, thanks a lot! I really like the new API too :)
