### ISSUE TITLE
Angular-meteor & i18n

### ISSUE THREAD

**Issue by yobre** [Urigo/angular-meteor#1102]
What is the correct method to handle i18n?

I tried using tap:i18n but not working.
With angular-translate can translate correctly.

However what is the best package to manage the internationalization?

Thanks

**Comment by ThomsC** [comment]
+1

**Comment by dapids** [comment]
Hi @yobre,

I personally use angular-translate for quite a long time and I'm very satisfied with it. ;)

Cheers,
David

**Comment by yobre** [comment]
Thanks David!

**Comment by kamilkisiela** [comment]
Same here, `angular-translate` works really well for me.

**Comment by yobre** [comment]
Thanks to all guys!
