### ISSUE TITLE
getReactively returns undefined

### ISSUE THREAD

**Issue by sean-stanley** [Urigo/angular-meteor#1103]
Hi, I think getReactively is returning undefined for an object containing keys that all evaluate to undefined.

here is my quick example

```
// ... inside helper
let params = this.getReactively($stateParams, true); // $stateParams = {category:undefined, favourites: undefined, search: undefined}

if (params.category) query.category = params.category // throws TypeError: Cannot read property 'category' of undefined
```
I would expect `params.category` to evaluate to undefined instead of throwing an error.

**Comment by Deadly0** [comment]
@sean-stanley first argument for `getReactively` a variable name in current scope, not an object.

**Comment by mgrivera** [comment]
Hi, this is the angular-meteor doc for *getReactively*: 
```javascript
myModule.controller('MyCtrl', ['$scope', '$reactive', function($scope, $reactive) {
  $reactive(this).attach($scope);

  this.myUser: {
    id: 10
  };

  this.helpers({
    myData: () => {
      return Data.find({_id: this.getReactively('myUser.id')});
    }
  });

  this.myUser.id = 29; // This will cause the helper to run again and update the view
}]);
```

**Comment by Urigo** [comment]
thanks for the help guys

**Comment by sean-stanley** [comment]
Right my bad. For clarity: I need to use the variable name as a string, and it is possible to deep watch a variable that is an object according to the docs but I forgot to list the object name as a string in `getReactively`'s arguments.
