### ISSUE TITLE
Chapter 5 Challenge and Chapter 6 "Party Details" Form View Not Working

### ISSUE THREAD

**Issue by barrymoo** [Urigo/angular-meteor#1104]
@Urigo Thanks for the nice tutorial.

My "Party Details" page (in the browser)  will not change from the original `<header>...</header>` style in Chapter 4/5.  I tried:
-  `meteor reset` - Resetting my MongoDB shouldn't do anything, but I tried it anyway.
- `rm -r typings` - I suppose this deletes the compiled ES5 javascript

My current [code base](https://github.com/barrymoo/angular2-meteor-socially). Any help, from anyone would be greatly appreciated. I am sure I am doing something silly, but I don't see anything obvious from your zipped up Chapter 6 code.

**Comment by cesargalindo** [comment]
@Urigo Thanks for the nice tutorial and updating it to Meteor 1.3.  

I'm running through the tutorial and am unable to get app step 05 working.  I have a copy of the steop 05 code for meteor 1.2 and that work fine.

Socially Step 05 works with Meteor 1.2.1
https://github.com/cesargalindo/zip_files/blob/master/meteor-angular2.0-socially-step_05_1.2.zip?raw=true

Socially Step 05 does not work with Meteor 1.3.1 
https://github.com/cesargalindo/zip_files/blob/master/meteor1_3_angular2_sociallly_05.zip?raw=true

The module.js file is throwing the following exception:
EXCEPTION: The selector "app" did not match any elements

I'm know things are still a work in progress but any feedback would be appreciated.

**Comment by cesargalindo** [comment]
Please ignore my issue.  I added the index.html file and it started working.   This file wasn't required in Meteor 1.2.1 but is for Meteor 1.3.1.

**Comment by Urigo** [comment]
fixed in the new tutorials
