### ISSUE TITLE
getReactively doesn't work properly with directive scope

### ISSUE THREAD

**Issue by Deadly0** [Urigo/angular-meteor#1105]
In `subscribe` `getReactively` will be called only once with initial value. When `filter` changed nothing happened with subscription.

If use getReactively without deep watch it will throw error when `filter` changed.
![2016-01-15_232531](https://cloud.githubusercontent.com/assets/4887213/12364402/6595d322-bbdf-11e5-8752-f8816d8f4a0b.png)

```
angular.module('app').directive('myDirective', function() {
  return {
    restrict: 'E',
    templateUrl: 'template.html',
    replace: true,
    scope: {
      filter: '='
    },
    link: function($scope) {
      $scope.subscribe('oddsPortalPicks', function() {
        return [$scope.getReactively('filter', true)]; // Will be called only once
      });
      return $scope.autorun(function() {
        console.log($scope.getReactively('filter')); // Will throw error "TypeError: Cannot read property 'changed' of undefined"
      });
    }
  };
});
```

Is directive scope not a reactive context or this is a bug?

Also after updating from 1.3.4 to 1.3.5 got a lot of errors "TypeError: Cannot read property 'change' of undefined" in code which worked well in 1.3.4.

**Comment by Deadly0** [comment]
Nobody faced the same problem? Maybe someone can correct my code? Can't update to 1.3.5

**Comment by ozsay** [comment]
Hi, we are currently working on 1.3.6 which is a whole refactor to the code.

Can you test your project with the version from https://github.com/ozsay/angular-meteor/tree/1.3.6?

```bash
git clone -b 1.3.6 https://github.com/ozsay/angular-meteor.git
```

and follow the [instructions](https://github.com/Urigo/angular-meteor/blob/master/CONTRIBUTING.md#run-local-angular-meteor-in-your-project) for loading the local copy of `angular-meteor`.

**Comment by Deadly0** [comment]
@ozsay got error ```Error: [$injector:unpr] Unknown provider: $meteorProvider```

**Comment by ozsay** [comment]
Can you share your repository ?

If not please show the `versions` files located in `.meteor` folder

**Comment by Deadly0** [comment]
After cloning angular 1.3.6 repo my dependencies were updated from ```angular@1.3.4``` to ```angular@1.3.5``` but not 1.3.6. Maybe i did something wrong?

```
accounts-base@1.2.2
accounts-password@1.1.4
alanning:roles@1.2.14
aldeed:collection2@2.8.0
aldeed:collection2-core@1.0.0
aldeed:schema-deny@1.0.1
aldeed:schema-index@1.0.1
aldeed:simple-schema@1.5.3
andruschka:tinycon@0.0.1
angular@1.3.5
angular-meteor-data@0.1.0
angular-templates@0.0.3
angular:angular@1.4.8
angular:angular-animate@1.4.8
angular:angular-aria@1.4.8
angular:angular-material@1.0.4
angularui:angular-ui-router@0.2.15
autoupdate@1.2.4
babel-compiler@5.8.24_1
babel-runtime@0.1.4
base64@1.0.4
benjamine:jsondiffpatch@0.1.38_1
binary-heap@1.0.4
blaze@2.1.3
blaze-tools@1.0.4
boilerplate-generator@1.0.4
brentjanderson:buzz@1.1.10
caching-compiler@1.0.0
caching-html-compiler@1.0.2
callback-hook@1.0.4
cfs:access-point@0.1.49
cfs:base-package@0.0.30
cfs:collection@0.5.5
cfs:collection-filters@0.2.4
cfs:data-man@0.0.6
cfs:file@0.1.17
cfs:gridfs@0.0.33
cfs:http-methods@0.0.30
cfs:http-publish@0.0.13
cfs:power-queue@0.9.11
cfs:reactive-list@0.0.9
cfs:reactive-property@0.0.4
cfs:standard-packages@0.5.9
cfs:storage-adapter@0.2.3
cfs:tempstore@0.1.5
cfs:upload-http@0.0.20
cfs:worker@0.1.4
check@1.1.0
cryptoquick:stylus-multi@1.2.1
danialfarid:ng-file-upload@5.0.9
dburles:mongo-collection-instances@0.3.4
ddp@1.2.2
ddp-client@1.2.1
ddp-common@1.2.2
ddp-rate-limiter@1.0.0
ddp-server@1.2.2
deps@1.0.9
diff-sequence@1.0.1
ecmascript@0.1.6
ecmascript-runtime@0.2.6
ejson@1.0.7
email@1.0.8
geojson-utils@1.0.4
hot-code-push@1.0.0
html-tools@1.0.5
htmljs@1.0.5
http@1.1.1
id-map@1.0.4
infinitedg:winston@0.7.3
infinitedg:winston-loggly@1.0.1
jhuenges:highstock@0.0.9
jquery@1.11.4
lai:collection-extensions@0.1.4
livedata@1.0.15
localstorage@1.0.5
logging@1.0.8
mdg:validation-error@0.2.0
meteor@1.1.10
meteor-base@1.0.1
meteorhacks:async@1.0.0
meteorhacks:npm@1.5.0
minifiers@1.1.7
minimongo@1.0.10
momentjs:moment@2.11.1
mongo@1.1.3
mongo-id@1.0.1
mongo-livedata@1.0.9
mrt:cheerio@0.3.2
mrt:later@1.6.1
ndxbxrme:ng-coffeescript@1.2.2
npm-bcrypt@0.7.8_2
npm-container@1.2.0
npm-mongo@1.4.39_1
observe-sequence@1.0.7
ordered-dict@1.0.4
pbastowski:angular-babel@1.0.9
peerlibrary:blocking@0.5.2
peerlibrary:xml2js@0.4.8_1
percolate:migrations@0.9.8
promise@0.5.1
raix:eventemitter@0.1.3
random@1.0.5
rate-limit@1.0.0
reactive-dict@1.1.3
reactive-var@1.0.6
reload@1.1.4
retry@1.0.4
reywood:publish-composite@1.4.2
routepolicy@1.0.6
rzymek:moment-locale-ru@2.9.0
service-configuration@1.0.5
session@1.1.1
sha@1.0.4
spacebars@1.0.7
spacebars-compiler@1.0.7
srp@1.0.4
standard-minifiers@1.0.2
stevezhu:lodash@3.10.1
templating-tools@1.0.0
tracker@1.0.9
ui@1.0.8
underscore@1.0.4
url@1.0.5
veekungx:angular-material-data-table@0.9.4
webapp@1.2.3
webapp-hashing@1.0.5
```

**Comment by ozsay** [comment]
we haven't updated the versions in the repo yet, but I see the problem now. `$meteor` was deprecated since 1.3.0. In 1.3.6 we removed it accidentally. I will talk with @Urigo about that.

**Comment by Deadly0** [comment]
@ozsay ok, i have replaced ```$meteor``` with ```Meteor``` and now it works.

Now this example hangs up the browser
```
angular.module('app').directive('myDirective', function() {
  return {
    restrict: 'E',
    templateUrl: 'template.html',
    replace: true,
    scope: {
      filter: '='
    },
    link: function($scope) {
        $scope.subscribe('collection', function () {
            return [$scope.getReactively('filter')];
         });

        $scope.helpers({
            data: function() {
                Collection.find($scope.getReactively('filter'));
            }
        });
    });
}});
```

Interesting that if use deep watch it just not works. ```getCollectionReactively``` hangs up the browser too.

**Comment by Deadly0** [comment]
@ozsay please, let me know if you can/can't reproduce the bug.

**Comment by ozsay** [comment]
@Deadly0 sorry for the wait. I will be able to test this maybe only in a few hours.

It would be best if you share the repository / create a new project that will produce the bug.

**Comment by Urigo** [comment]
@Deadly0 can you please share a repo with a reproduction?
It looks like that there is a good possibility that it relates to other parts of the code and it would be easier to find and fix it with a full app

**Comment by Deadly0** [comment]
@ozsay @Urigo 

Demo with bug is here: http://angular-meteor-bug-1.meteor.com/ Change date to reproduce the bug.
Repo: https://github.com/Deadly0/angular-meteor-bug-1

**Comment by ozsay** [comment]
Hi, I found out what seems to be the issue here. Since `filter` is an `object` you need to specify that we do a deep watch like this:

```js
	link: ($scope) ->
		$scope.helpers
			cols: () -> Collection.find($scope.getReactively('filter', true))
```

Hopefully this solve your main issue

**Comment by Deadly0** [comment]
@ozsay looks like the fix for 1.3.6 branch. But not work with 1.3.5. Behaviour without deep watch looks strange, trust you will fix it. Will wait for 1.3.6 release to update in my app.

**Comment by Urigo** [comment]
@Deadly0 `angular@1.3.6-beta.1` was released.
Please check and let me know if that fixed the issue.

**Comment by Deadly0** [comment]
@Urigo @ozsay i have tested new beta release with my bug repo and my 2 apps. New release works fine with my bug repo but still not works in my apps.

I have found another bug: reactivity not working if i change object field which name starts with "$" sign. For example this code: 
```
{date: {
	$gte: currentDateForFind
	$lt: nextDate
}}
```

I use it as mongo db query.

I have updated my repo with new bug and use case. https://github.com/Deadly0/angular-meteor-bug-1 Every time you change date you should see ```date changed``` ```subscribe``` ```helper``` in console, but ```getReactively``` do not see changes.

**Comment by ozsay** [comment]
well I looked into it and it seems like an angular issue.

Check this codepen: http://codepen.io/anon/pen/WrmNrV

unfortunately, angular ignores properties with `$` in properties name:
https://github.com/angular/angular.js/issues?q=is%3Aissue+watch+dollar+is%3Aclosed

**Comment by Deadly0** [comment]
@ozsay, thank you, didn't know about it. Any ideas how to deal with it?

**Comment by ozsay** [comment]
You can search for a magic solution... Or you can implement some kind of transformation function:
```js
link: ($scope) ->
        $scope.helpers
            cols: () -> Collection.find(transform($scope.getReactively('filter', true)))

transform = (filter) ->
  { c:
    $gte: filter.c.gte
    $lt: filter.c.lt }

```

**Comment by Deadly0** [comment]
@ozsay, yes I use roles to secure the data. Move selectors to a publish function sounds like a good idea, thank you very much!
