### ISSUE TITLE
WebStorm

### ISSUE THREAD

**Issue by TWKDreamState** [Urigo/angular-meteor#1106]
Hi,

This is not an issue particularly with angular-meteor (I'm liking the changes that have been made).

Just out of interest, in my version of WebStorm, all of the new code I am using is causing errors in WebStorm and perhaps someone else can help to advise on this as it makes the code quite hard to work with! Feel free to close if not the place to discuss (fairly new to GitHub).

As an example....

```javascript
'use strict';

angular.module('meteorbluespyApp')
    .controller('HomeCtrl', function ($scope, $state, $window, $reactive) {

        $reactive(this).attach($scope);

        this.helpers({
            isLoggedIn() {                  <-----THIS CAUSES WEBSTORM TO SHOW AN ERROR - THE CODE STILL WORKS
            if (!!Meteor.user()){
                $state.go('dashboard');
            }
        }
    });

$scope.admin.bodyWide = true;

$scope.currWindowScroll = 0;

angular.element($window).bind('scroll', function () {
    $scope.currWindowScroll = $window.scrollY;
    $scope.$apply();
});

})
.
value('duScrollDuration', 1500);
```

WebStorm is expecting 'isLoggedIn' to have a ':' after it and therefore the formatting is out for the rest of the code. Is there anyway to get round this? Whilst the above is a simple example, some of app will be more complex. It's hard to show my view in this thread, but the auto-formatting doesn't work and the code is shown to have errors. I'm planning to upgrade my whole app to the new helpers syntax which will make it hard to debug.

Many thanks.

**Comment by TWKDreamState** [comment]
<img width="490" alt="capture" src="https://cloud.githubusercontent.com/assets/8638987/12364970/bd35ed76-bbc9-11e5-8889-fe386b7db954.PNG">

Screen shot might help highlight the issue.

**Comment by Deadly0** [comment]
@TWKDreamState you can enable ES6 support in settings:
![2016-01-16_001825](https://cloud.githubusercontent.com/assets/4887213/12365594/d4f98fd6-bbe6-11e5-8fe7-a992756539a0.png)

**Comment by Urigo** [comment]
Thanks @Deadly0

**Comment by TWKDreamState** [comment]
Thank you :) Appreciate it.

**Comment by kelvinaero** [comment]
This solved the issue
