### ISSUE TITLE
Please limit deprecation warnings

### ISSUE THREAD

**Issue by cranesandcaff** [Urigo/angular-meteor#1109]
I appreciate the first warning but after that my console can quickly fill up with an excessive amount of warnings. The latest update puts a deprecation warning on every helper method, even when I'm using the `getReactively` method. It makes it really difficult to identify my own console logs.

**Comment by DerekFong1004** [comment]
+ 1 The warnings are quite annoying and make debugging really difficult.

**Comment by atoftegaard** [comment]
Please provide a way to suppress these annoying warnings, something like: `$provide.decorator('$angularMeteorSuppressWarning', function () { return true; });`

**Comment by Urigo** [comment]
good idea, will be added in the next version

**Comment by ozsay** [comment]
@Urigo In 1.3.5 there was a mistake with the warnings as @dotansimha explained [here](https://github.com/Urigo/angular-meteor/issues/1110#issuecomment-178502477).

In 1.3.6 the deprecation warnings are only on 1.2.x API. Is is sufficient or we still need to limit the warnings ?

**Comment by Urigo** [comment]
I think it's still good to have the ability to remove those message if you really want to.

**Comment by ozsay** [comment]
Hi everybody,

here is the commit with the changes: https://github.com/ozsay/angular-meteor/commit/120b7064488d46f0ecec60300e59c91e93cabe4f

The API for suppressing warnings is as follows:
```js
myModule.config(function($angularMeteorSettings) {
  $angularMeteorSettings.suppressWarnings = true;
})
```

**Comment by atoftegaard** [comment]
Maybe warnings about overriding helpers should not be suppressable. Those warnings mean something should be fixed in the current version. Deprecation warnings are relevant for future warnings.

**Comment by ozsay** [comment]
I agree, but It looks like there are plenty of these warnings on socially. I think it's good for the beta until we investigate these overrides.

**Comment by Urigo** [comment]
still, when you remove the warnings it means that you are being explicit and aware of what you are doing, so I think it should remove all warnings.

**Comment by Urigo** [comment]
`angular@1.3.6-beta.1` was released with that feature like @ozsay described.
Please check and let me know if that worked for you.

**Comment by Urigo** [comment]
`1.3.6` was released with that option: http://www.angular-meteor.com/api/1.3.6/settings
