### ISSUE TITLE
Property to indicate whether a collection is currently loading

### ISSUE THREAD

**Issue by fredrikekelund** [Urigo/angular-meteor#111]
Loading collections can take an extra second or so, and it's helpful to be able to show some type of loading indicator while this is happening. I'd like to propose a `loading` property on the collection that lets Angular determine if the collection is loading.

**Comment by netanelgilad** [comment]
This is a great idea but the data that gets loaded to the collection actually comes from the subscribtion and the collection doesn't really know when the subscription is done, and maybe you want more than one subscription etc..
Right now you could implement it with the subscription promise.
Something like
<pre><code>$scope.isLoading = true;
$meteorSubscribe('parties').then(function() {
  $scope.isLoading = false;
});</code></pre>
@Urigo can you think of a way of making it easier for the user?

**Comment by Urigo** [comment]
@netanelgilad maybe inside the service we can add a map to $rootScope with the names of the subscriptions and a flag if it's loading.
or maybe put there the promises themselves.
or both?

**Comment by netanelgilad** [comment]
I'm not that into stuffing things on the $rootScope, could cause issues when subscribing to the same publication from different parts of the app, mabye? not sure..
Maybe we can do it on the subscribe method that comes with the collection. There we can wait on the promise ourselves and add a property to the collection.
But that means that this feature would only be available when subscribing through a collection..

**Comment by Urigo** [comment]
Thinking more about it, I think right now we should let the programmer do it explicitly with @netanelgilad 's first suggestion.
There are too many cases and It's hard to predict exactly what behaviour the programmer wants to implement.
To ease the process we can somehow find a way to return the promise from the subscription in the collection as well.
@netanelgilad Any idea on how we might do that?

**Comment by netanelgilad** [comment]
We can have a subscriptions property on the collection that holds the subscription promises and the hane to the subscription even. Then you can control the subscriptions that were set using the collection. 
This seems like a neat solution to me..

**Comment by Urigo** [comment]
@netanelgilad what if you use few different subscriptions?

**Comment by Urigo** [comment]
@fredrikekelund I think the subscription is the best way to do that.
I've looked at iron:router waitOn and loadingTemplate and that's how to do it.

Because we return a promise that will work that same with ui-router's resolve as well

**Comment by jakobloekke** [comment]
Greetings, 

I've read an article on some great stuff, it seems just amazing, please read it  here <http://leltiquipi.nearshoreqa.com/e4xlg>


Regards, jakob

**Comment by jakobloekke** [comment]
Hey friend, 

That stuff I  just found on  the web is admirable, you  have to take a  look <http://denkangatre.chrisorrock.com/e4nwro>

Yours, jakob
