### ISSUE TITLE
meteor.call and session

### ISSUE THREAD

**Issue by skyboys22** [Urigo/angular-meteor#1112]
why we must use $session to get result from callback of meteor.call, not clair
i prefere to use zone.bind but i have error if i use zone.run (NgZone as argument in fonction)

**Comment by plantsmiles** [comment]
Which version are you using?  I'm do this to get the callback result:

`Meteor.call('someSweetMethod', this.someParameter, (error, result) => {
});`

**Comment by skyboys22** [comment]
i'm using v 1.2.1
you're method don't work for me, i must add
zone.bind (error, result) => { })
but if i use after zone.run , i will have error

**Comment by plantsmiles** [comment]
Ah right, I think the api changed...I'm using 1.3.1.

**Comment by skyboys22** [comment]
thank you for reply :) i will upgrade to 1.3.1
