### ISSUE TITLE
Error: argument 2 must be a function when using the new subscribe syntax on 1.3.5

### ISSUE THREAD

**Issue by iain17** [Urigo/angular-meteor#1113]
Just updated to version 1.3.5 and tried to adjust to the new subscribe syntax. However even just the example on: http://www.angular-meteor.com/api/1.3.1/subscribe doesn't work. It expects a function on argument 2, when clearly the example also states that you can send arguments along when you subscribe.

The old methode $scope.$meteorSubscribe works perfectly fine.

**Comment by MilosStanic** [comment]
Works without second argument with 1.3.4

**Comment by Urigo** [comment]
@kamilkisiela fixed that in the docs, the example should work now
