### ISSUE TITLE
Meteor call not running digest

### ISSUE THREAD

**Issue by sebakerckhof** [Urigo/angular-meteor#1116]
If I modify something in the callback of a Meteor.call function, these changes often do not appear if I don't manually start a digest cycle.

This wasn't a problem with the old $meteor service before.

**Comment by TWKDreamState** [comment]
This looks similar to my issue - hopefully it will help you.

https://github.com/Urigo/angular-meteor/issues/1130

**Comment by sebakerckhof** [comment]
Yes, it is, but I believe it may be filed as a bug.

**Comment by ozsay** [comment]
With the new api that was introduced in the latest releases of `angular-meteor` which is closer to the regular `meteor` api, `angular-meteor` doesn't wrap Meteor calls anymore. So when you write `Meteor.call`, the actual `meteor` function is called without any wrap. And the callback function is not called in the angular scope, so you must call $digest yourself. Another solution is to do what @TWKDreamState did in his issue. Or you can wrap the callback code with `$timeout`:

```js
Meteor.call('method', function() {
  $timeout(function() {
    // change scope here
  });
});
```

@Urigo Do we want to revert this behaviour?

**Comment by sebakerckhof** [comment]
yeah, I get why this happens, but I'd argue that a library that wants to integrate angular with meteor should provide this. Especially since it's not a large chunk of code to maintain.

**Comment by Urigo** [comment]
will be fixed in the next version

**Comment by Urigo** [comment]
We will add a `this.call` which has the same API as `Meteor.call` but it will run a digest cycle after the callback has fired

**Comment by sebakerckhof** [comment]
Sounds good

**Comment by ozsay** [comment]
This feature has been added in 1.3.6.

**Comment by Urigo** [comment]
`angular@1.3.6-beta.1` was released.
Please check the new `this.call` to see if that works for you.

**Comment by erperejildo** [comment]
I'm using angular-meteor 1.3.11 and I facing the same issue. I've got this call:
```
Meteor.call('getFoodInfo', function(error, result){
      console.log(result);
      that.foodTypesArray = result.types;
      that.dishTypesArray = result.whens;
      that.timesArray = result.times;
    });
```
Sometimes those variables on my template are not updated, but always available as I can see on the console. If I add `$timeout(function() {});` I always get the data. Shall I update something else in my modules?

**Comment by TWKDreamState** [comment]
Hi @erperejildo.

Have you tried using 'this.call' instead  of 'Meteor.call'?

**Comment by erperejildo** [comment]
Oh, I see. I don't know why but I understood the change was that --> this, not Meteor --> this.
My fault! working now

Should I change all my Meteor.calls?

**Comment by TWKDreamState** [comment]
From personal experience, I think you will have less issues if you change them all :)
