### ISSUE TITLE
yo angular-meteor: directive myDirective (GENERATOR HAS ALREADY BEEN RUN)

### ISSUE THREAD

**Issue by agnelnieves** [Urigo/angular-meteor#1122]
Greetings,

I'm trying to use the yo directive generator to make a new directive but it says: 
```
generator has already been run
```
Here's what I typed:
```
yo angular-meteor: directive myDirective
```
I tried closing and re-openning the cmd, also tried to Install generator-angular-meteor (update), computer restart, and still has the same error. 

What could be happening and how can I fix it?

Thanks in advace

**Comment by kamilkisiela** [comment]
I think you should post an issue [here](https://github.com/ndxbxrme/generator-angular-meteor/issues)

**Comment by agnelnieves** [comment]
@kamilkisiela Will do! Thanks man!
