### ISSUE TITLE
   While building package app-core:    error: No plugin known to handle file 'client/index.html'. 

### ISSUE THREAD

**Issue by sferoze** [Urigo/angular-meteor#1123]
I am getting this error in the console each time I try and run my app

I am starting with a blank meteor app and am trying to bootstrap an angular app within a package. 

`While building package app-core:
   error: No plugin known to handle file 'client/index.html'. If you want this
   file to be a static asset, use addAssets instead of addFiles; eg,
   api.addAssets('client/index.html', 'client').`

package.js
```
Package.describe({
  summary: "Connected-Car-Core",
  version: "1.0.0",
  name: "app-core"
});

Package.onUse(function(api) {
  
  api.versionsFrom('1.2.1');

  api.use([
    'jquery',
    'angular',
    'angularui:angular-ui-router',
    'driftyco:ionic',
    'momentjs:moment',
    'd3js:d3',
    'agnito:raphael',
    'netanelgilad:angular-file-upload@1.1.5',
    'danialf:ng-file-upload',
    'francocatena:compass',
    'fourseven:scss',
    'check'
  ],['client']);

  api.addFiles('client/index.html', 'client');
  api.addFiles('lib/app.js', 'client');


});
```

index.html
```
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <base href="/">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>

  <p> hello </p>

</body>
```

app.js
```
angular.module('ConnectedCar', ['angular-meteor', 'ionic'])

function onReady() {
  angular.bootstrap(document, ['ConnectedCar']);
}

if(Meteor.isCordova) {
  angular.element(document).on('deviceready', onReady);
} else {
  angular.element(document).ready(onReady);
  console.log('hello');
}
```

**Comment by Philip-Nunoo** [comment]
@sferoze try adding the "templating" package as part of your dependency packages. :)

**Comment by sferoze** [comment]
@Philip-Nunoo thanks but actually angular should be handling the templating. The code I pasted works now. I think there was some error in the build process before. I think the old package.js was not updating. Anyways it is working now without any change.
