### ISSUE TITLE
How to find out when subscriptions are ready?

### ISSUE THREAD

**Issue by jessonjoy** [Urigo/angular-meteor#1124]
Hello,

Looking to find out how to find out if subscriptions are ready similar to Template.subscriptionsReady?

Thanks

Jesson

**Comment by ThomsC** [comment]
```javascript
this.subscribe('name', ()=>[parameters], () => { 
//when ready
});
````
http://www.angular-meteor.com/api/1.3.2/subscribe

**Comment by MilosStanic** [comment]
@ThomsC not correct, the third argument to `subscribe` is an object with `onReady` and `onStop` methods.

```javascript
var subscriptionHandle = this.subscribe('parties', [this.numberOfParties], {
    onReady: function () {
      console.log("onReady And the Items actually Arrive", arguments);
      subscriptionHandle.stop();  // Stopping the subscription, will cause onStop to fire
    },
    onStop: function (error) {
      if (error) {
        console.log('An error happened - ', error);
      } else {
        console.log('The subscription stopped');
      }
    }
  });
```
from the same page.

**Comment by kamilkisiela** [comment]
@MilosStanic 

https://github.com/Urigo/angular-meteor/blob/master/packages/angular-meteor-data/modules/angular-meteor-reactive-scope.js#L40

So it can be `object` (`{ onReady() {}, onStop() {} }`) and `function` (only onReady callback)

**Comment by MilosStanic** [comment]
Ah, okay, I didn't know that, I apologize @ThomsC @kamilkisiela

**Comment by Urigo** [comment]
thanks everyone :)

**Comment by jessonjoy** [comment]
thanks folks!
