### ISSUE TITLE
Server Side Rendering and SEO

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/angular-meteor#1127]
The age old question with Angular apps, and also, from what I see, with Meteor apps. 

So, is it possible to use the [meteorhacks:ssr](https://github.com/meteorhacks/meteor-ssr), and how to do it? Any recipe?

**Comment by mxab** [comment]
Hi,
we use prerender.io for it. you can also run prerender on your own if you like

**Comment by MilosStanic** [comment]
@mxab 
Thanks for answering. 
I will consider that option. 

What I actually want to do is the following: 
I have an index.html for my angular app like this: 

```html
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <base href="/">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
  <title>Chat App</title>
</head>
<body>
  <ui-view ng-cloak></ui-view>
  <section id="my-section"></section>
</body>
```

I want to be able to populate the section tag inner HTML with content from DB on the server. It would be static content in the sense there will be no variables to parse.
Is that possible?
In the outcome, the server will serve prerendered index.html, and then leave it to Angular to populate the `<ui-view>`.

**Comment by mxab** [comment]
I used this once
https://github.com/meteorhacks/meteor-inject-initial

```
WebApp.connectHandlers.use(function (req, res, next) {

    if (Inject.appUrl(req.url)) {
        Inject.rawModHtml('insertLangs', function (html) {
            return html.replace(
                /<\/body>/,
                '<section id="my-section"></section></body>');
        });
    }
    next();
}
```

**Comment by MilosStanic** [comment]
Thanks a lot @mxab 
I will investigate.
