### ISSUE TITLE
angular-meteor ui router cannot set controller 

### ISSUE THREAD

**Issue by xiulunlin** [Urigo/angular-meteor#113]
I just follow the demo in https://github.com/Urigo/meteor-angular-socially/compare/step_04...step_05
The demo works fine but I found some problems in my app and I don't know what's going on.

First,I cannot use the file named *.tpl as templateUrl , I have to rename it to *.html and add 
\<template name=""\>
 something
\</template\>
inside it while the demo just uses a .tpl file directly without template tag

Second,I can not bind my controller with template although I use the some way to define controller as what demos do .
Below are my project in github .
https://github.com/xiulunlin/allenshow

Thanks for help!

**Comment by netanelgilad** [comment]
@xiulunlin the repository is empty =[
upload it and we'll have a look.

**Comment by xiulunlin** [comment]
thanks for your quick answer @netanelgilad , the project is uploading

**Comment by xiulunlin** [comment]
The repository is ready , please have a look  @netanelgilad  The controller seem to work again although I don't know why , and the first problem still confuse me .

**Comment by netanelgilad** [comment]
When using .tpl files in the templateUrl you need to supply the full path to the .tpl file.
For example: `'client/parites/views/devil.tpl'`.
Give it a try. should work.. Then use that for the other html files and you won't need the <template> tag any more..

**Comment by xiulunlin** [comment]
I have tried 'client/parites/views/devil.tpl' but it doesn't work @netanelgilad

**Comment by Urigo** [comment]
@xiulunlin I think the reason might be that you are not using angular-meteor's updated version.

Because it's an alpha version, Meteor doesn't automatically update it and you need to explicitly specify the version:
    meteor add urigo:angular@0.6.0-alpha

**Comment by xiulunlin** [comment]
I think you are right . @Urigo 

Still my project doesn't work when using 
meteor add urigo:angular@0.6.0-alpha
But I tried  "meteor reset" and then restart again to reinstall angular , in this way it helps!

**Comment by Urigo** [comment]
Just released the official 0.6.0 version.

Should work now.

Please run

    meteor update

in the command line

**Comment by Urigo** [comment]
Closing for now.

Please re-open if it's not working after the update

**Comment by jakobloekke** [comment]
Greetings, 


Look what I've  just found  on the web!  It's so  amazing,  check it out <http://zyndefongi.pin-3.com/e4fnbo>

Sent from my iPhone, jakob

**Comment by jakobloekke** [comment]
Yo! 
I've just heard  from a friend about that amazing stuff,  I'm so excited, you've got to take a look <http://fronteprala.lapointeonline.com/e4uqc>
All the best, jakob
