### ISSUE TITLE
New Project Angular & Ionic getting WARNING: Tried to load angular more than once

### ISSUE THREAD

**Issue by sferoze** [Urigo/angular-meteor#1137]
I am getting the warning in console `WARNING: Tried to load angular more than once`

The app still works just fine, but I do want to solve this issue. 

I am developing this angular app inside a meteor package. 

Here is how I am bootstrapping. I have an index.html 

Then I bootstrap angular in app.js with code

```
function onReady() {
  angular.bootstrap(document, ['ConnectedCar']);
}

if(Meteor.isCordova) {
  angular.element(document).on('deviceready', onReady);
} else {
  angular.element(document).ready(onReady);
}
```

If I comment out the bootstrapping code above the angular app does not work and shows up blank BUT the warning `WARNING: Tried to load angular more than once` still appears. 

I have double checked and all my template paths seem to be correct. I have also checked my html and it is all well formed. 

Any idea how to solve this?

**Comment by ThomsC** [comment]
`WARNING: Tried to load angular more than once` it's a route problem. Sometimes the cache doesn't clean well so it is a nightmare to debug.
Try to isolate the route which is wrong one by one ...

**Comment by ozsay** [comment]
I came across this warning when I had dependencies issues (not on an angular-meteor project though).

it happens when the angular script (`angular.js`) loads more than once.

example:

```html
<html>
  <body>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js"></script>
  </body>
</html>
```

In meteor though, it manages the insertions of the scripts tags for you.
Can you check on the developer tools if the DOM contains more than one reference of the angular script?
Also, if you can share your repository so we can investigate it.

Oz

**Comment by Splaktar** [comment]
This can also happen if your routing gets messed up. I had this issue recently and fixed it by adding `.html` to the end of all of my templateUrl definitions.

**Comment by Urigo** [comment]
@sferoze did any of the suggestions worked for you

**Comment by Urigo** [comment]
Closing as there is no response
