### ISSUE TITLE
How to call less.modifyVars() from angular controller?

### ISSUE THREAD

**Issue by yobre** [Urigo/angular-meteor#1140]
I'm using angular-meteor and [flemay:less-autoprefixer](https://atmospherejs.com/flemay/less-autoprefixer) for compile my less file.
I would implement color picker for change dinamically the bootstrap color of my template but the 'less' global variable is not exposed in my app.
How can call less.modifyVars() method?

Thanks

**Comment by Urigo** [comment]
@yobre can you please provide a reproduction of an example project where you are trying to that and not successful?

**Comment by Urigo** [comment]
closing as there is no reproduction..
