### ISSUE TITLE
ng-repeat weird behavior

### ISSUE THREAD

**Issue by SimoneGatti** [Urigo/angular-meteor#1142]
Hi all!
I created my first meteor app and I chose to use angular package.
I have 2 simple page: the first that lists items and allows to add and remove one of them, the second that shows item details. When the first page is loaded I see all items correctly. After I visited the details page, then ng-repeat show only one item duplicated many time. How you can see below (name - id).

<img width="1143" alt="before" src="https://cloud.githubusercontent.com/assets/16915705/12609781/34d9255a-c4e4-11e5-996a-1db54c91327b.png">
<img width="1141" alt="after" src="https://cloud.githubusercontent.com/assets/16915705/12609787/3d83c836-c4e4-11e5-99e1-0c265e86909a.png">

I logged the mongo cursor returned by helpers function (still the same):
<pre>
ret>0>wfwefwe
ret>1>eeeee
ret>2>geggggggg
ret>3>wwwww
</pre>

Did you find the same behavior before now? What to you think about that?
(When I used angular-with-blaze package, I was having the same behavior simply adding new item)

I can provide some snippet of code:
<ul>
<li><b>template</b><pre>
&lt;div class="reports-list container"&gt;
    &lt;div class="panel panel-primary"&gt;
        &lt;div class="panel-heading"&gt;
            &lt;h3 class="panel-title"&gt;
                &lt;i class="fa fa-tasks"&gt;&lt;/i&gt; {{ "REPORTS" | translate | capitalize }}
                &lt;i class="fa fa-plus-circle yo-right yo-link" ng-click="addReport()" uib-tooltip='{{ "ADD_REPORT" | translate | capitalize }}'&gt;&lt;/i&gt;
            &lt;/h3&gt;
        &lt;/div&gt;
        &lt;div class="panel-body"&gt;
            &lt;ul class="nav nav-tabs nav-stacked col-md-12 col-sm-12"&gt;
                &lt;li ng-repeat="report in reports"&gt;
                    &lt;p&gt;
                        &lt;a ui-sref="reports.detail({ reportId: report._id })"&gt;{{ report.name }}&lt;/a&gt;
                        &lt;i class="yo-right" ng-class="report.chiuso == true ? 'fa fa-check-circle yo-true' : 'fa fa-close yo-false'"&gt;&lt;/i&gt;
                        &lt;button class="btn btn-sm btn-danger" ng-click="remove(report._id)"&gt;{{ "BUTTON_REMOVE" | translate | capitalize }}&lt;/button&gt;
                    &lt;/p&gt;
                &lt;/li&gt;
            &lt;/ul&gt;
        &lt;/div&gt;
    &lt;/div&gt;
    &lt;p&gt;{{ "TOTAL_NUMBER_OF_REPORTS" | translate | capitalize }}: {{reports.length}}&lt;/p&gt;
&lt;/div&gt;
</pre></li>
<li><b>ui-router</b><pre>
.config ($stateProvider) ->
  $stateProvider
  .state 'reports',
    url: '/reports'
    abstract: true
    template: '<ui-view/>'
  .state 'reports.list',
    url: '/list'
    templateUrl: 'client/reports/reports-list.view.ng.html'
    controller: 'ReportsListCtrl'
  .state 'reports.detail',
    url: '/detail/:reportId'
    templateUrl: 'client/reports/report-detail.view.ng.html'
    controller: 'ReportDetailCtrl'
</pre></li>
<li><b>model (client and server)</b><pre>
@Reports = new Mongo.Collection('reports')
Meteor.methods
  'reports.remove': (reportId) ->
    Reports.remove reportId
</pre></li>
<li><b>client</b><pre>
.controller 'ReportsListCtrl', ($scope) ->
  $scope.subscribe('reports')

  $scope.helpers({
    reports: () ->
      Reports.find({'user._id': Meteor.userId()})
  })
    
  $scope.remove = (reportId) ->
    Meteor.call('reports.remove', reportId)

  $scope.addReport = () ->
    tName = moment().format("MMMM") + " " + moment().format("YYYY")
    Meteor.call('reports.insert', Meteor.user(), tName, (error, result) ->
      if error
        console.log error
      else
        console.log result
        if !result
          console.log result'REPORT_ALREADY_EXISTS'
    )
</pre></li>
<li><b>server</b><pre>
Meteor.publish('reports', () ->
  Reports.find()
)
Reports.allow
  insert: (userId, report) ->
    userId
  update: (userId, report, fields, modifier) ->
    userId
  remove: (userId, report) ->
    userId

Meteor.methods
  'reports.myReportExists': (userId, tName) ->
    Reports.find({'user._id': userId, name: tName}).count() > 0

  'reports.insert': (user, tName) ->
    exists = Meteor.call('reports.myReportExists', user._id, tName)
    if exists
      return false
    else
      currentDate = moment()
      days = []
      _.times(currentDate.daysInMonth(), (d) ->
        isFestivity = false
        dataActual = moment().date(d+1).toDate()
        tzoffset = (new Date()).getTimezoneOffset() * 60000;
        dataActual.setHours(0)
        dataActual.setMinutes(0)
        dataActual.setSeconds(0)
        dataActual.setMilliseconds(0)

        dataActual = new Date(dataActual - tzoffset)

        days.push {
            datetime: moment().date(d+1).toDate()
            dayOfWeek: moment().date(d+1).format("d")
            festivo: false
            ore: ""
            ore_straordinario: ""
            ore_viaggio: ""
            trasferta: ""
            km: ""
            parcheggi: ""
            pedaggi: ""
            trasporti: ""
            ristorazione: ""
            pernottamento: ""
            note: ""
          }
      )
      Reports.insert {
          name: tName
          user: user
          chiuso: false
          table: days
        }
      return true
</pre></li>
</ul>

**Comment by yobre** [comment]
Hi Simone, i've the same problem.
Any ideas?

**Comment by ozsay** [comment]
Can you provide the full app as a repository? (include all views and controllers)

**Comment by SimoneGatti** [comment]
@ozsay @yobre Feel free to contribute <a href="https://github.com/SimoneGatti/track">here</a>.
The GitHub repo url is: https://github.com/SimoneGatti/track.git

**Comment by ozsay** [comment]
I upgraded angular-meteor version to the latest (1.3.5) and everything worked fine.

try to change to `angular@1.3.5` in the packages file

**Comment by SimoneGatti** [comment]
@ozsay It works also for me. Thank you!
Follow up some questions:
Why command "meteor add angular" download 1.3.4*, but <a href="https://atmospherejs.com/meteor/angular">here</a> show that last release is 1.3.5? Isn't 1.3.5 a stable version yet?

**Comment by SimoneGatti** [comment]
OK, finally I got it! 
Use angular 1.3.5 instead of 1.3.4* doesn't matter. The most important thing is upgrade to angular-meteor-data@0.1.0, so you can use also angular-with-blaze 1.3.4 with urigo:angular-blaze-template 0.3.0.
Cool!!

**Comment by Urigo** [comment]
Thanks @ozsay

**Comment by robmarian** [comment]
Unfortunately, I have the same problem. 
I'm using `angular@1.3.6` and `angular-meteor-data@0.2.0`, so the solutions proposed here don't apply to my situation.
I've setted up a [repo](https://github.com/robmarian/ng-repeat-issue) with steps to reproduce the issue. Make sure to hack around it.
