### ISSUE TITLE
ng-repeat and dburles:collection-helpers

### ISSUE THREAD

**Issue by bartvanremortele** [Urigo/angular-meteor#1143]
I have an issue with collection-helpers inside an ng-repeat. It works fine when working with a single object e.g.: book.author() but the same does not work inside of an ng-repeat. This behaviour is already described here: https://forums.meteor.com/t/does-dburles-collection-helpers-work-with-angular-meteor/12800/5 but as far as I can tell there is no solution for this yet.

**Comment by yobre** [comment]
the same problem in this issue: [#1142](https://github.com/Urigo/angular-meteor/issues/1142)

**Comment by ozsay** [comment]
@bartvanremortele Can you check if [this](https://github.com/Urigo/angular-meteor/issues/1142#issuecomment-175688417) helps

**Comment by bartvanremortele** [comment]
after upgrading to 1.3.5 `meteor add angular@1.3.5` this issue seems to be resolved. Thank you.
