### ISSUE TITLE
From Meteor reactivity to view through method callback

### ISSUE THREAD

**Issue by SimoneGatti** [Urigo/angular-meteor#1147]
Hi all!

I need to show/use in view some data resulting from the execution of a Meteor method (async), the latter fired by a change in mongo collection. (If a document change, then I can see evidence in another browser tab). 

First I used simple scope variable
<pre>
angular.module 'trackerApp'
.controller 'UsersCtrl', ($scope) ->

  $scope.usersClosed = []

  $scope.getClosed = () ->
    Meteor.call('reports.getClosed', (error, result) ->
      if !error
        $scope.usersClosed = result
    )
</pre>
but assignment in callback function doesn't render again the view.
So I decided to use helper variable
<pre>
  $scope.helpers({
    usersClosed: []
  })
</pre>
It works fine, but in client console appear some warnings like:
<b>defining 'usersClosed' value helper, note that this feature will be deprecated in 1.4 in favor of using 'getReactively' - http://www.angular-meteor.com/api/1.3.1/get-reactively</b>
After that I moved to a helper function
<pre>
  $scope.helpers({
    usersClosed: () ->
      $scope.getReactively('xyz')
  })
</pre>
It never works.
Why it doesn't? Isn't $scope made reactive by default?
(You can find more explanation in #1110; I tried also to use $reactive(this).attach($scope) )

Let's look handling of collection changes. I tried two way:
<ul>
<li>
<b>observer</b>
<pre>
  $scope.getClosed = () ->
    Meteor.call('reports.getClosed', (error, result) ->
      if !error
        $scope.usersClosed = result
    )
  $scope.getClosed()
  Reports.find().observeChanges(
    added: (id, fields) ->
      $scope.getClosed()
    changed: (id, fields) ->
      $scope.getClosed()
    removed: (id) ->
      $scope.getClosed()
  )
</pre>
</li>
<li>
<b>autorun</b>
<pre>
  $scope.autorun (computation) ->
    Reports.find()
    Meteor.call('reports.getClosed', (error, result) ->
      if !error
        $scope.usersClosed = result
    )
</pre>
</li>
</ul>
Only the first one works, but it's quite annoying.

Why autorun doesn't react to collection changes? Isn't autorun a reactive context and collection a reactive source?

The full example code is <a href="https://github.com/SimoneGatti/track" >here</a>. (Remember to keep open all the three pages to verify reactivity)

<i>
PS: An alternative to first part could be use Session
<pre>
$scope.helpers({
    usersClosed: () ->
         Session.get('xyz')
  })

$scope.getClosed = () ->
    Meteor.call('reports.getClosed', (error, result) ->
      if !error
        Session.set('xyz', result)
    )
</pre>
, even if it seems to be concerning session of user (I don't feel confident to use it).
</i>

**Comment by ozsay** [comment]
The reason the callback doesn't rerender the view is because `$scope.$digest` is not running after the callback. Read my comment [here](https://github.com/Urigo/angular-meteor/issues/1116#issuecomment-175592538).

I'm not sure what you tried to do next, so I hope this solves your problem.

**Comment by SimoneGatti** [comment]
@ozsay Thank you for your answer!

About <a href="http://www.angular-meteor.com/api/1.3.2/autorun">autorun</a>: 
Can it be used like <a href="http://docs.meteor.com/#/full/tracker_autorun">tracker autorun</a>? <i>- ...you can monitor a cursor (which is a reactive data source).. -</i>
Because code below doesn't work
<pre>
$scope.autorun (computation) ->
    Reports.find()
    Meteor.call('reports.getClosed', (error, result) ->
      if !error
        $scope.usersClosed = result
    )
</pre>

**Comment by ozsay** [comment]
No unfortunately it can't, since a result of a meteor method is not a reactive data source.

In 1.3.6 There will be an api for making this:

for example:
```js
myModule.controller('MyCtrl', ['$scope', '$reactive', function($scope, $reactive) {
  $reactive(this).attach($scope);

  this.call('reports.getClosed', (error, result) => {
      if !error
        $scope.usersClosed = result
    });
}]);
```

I'm closing since the API has been added.

**Comment by mattiLeBlanc** [comment]
Can't wait to use the new api. I am running in some reference issue with executing a Meteor.call.
In my callback success, the `this` doesn't reference back to the this before the Meteor call.
So I can't stop a spinner from spinning for example. The new Api would hopefully fix this?

**Comment by nunof07** [comment]
@mattiLeBlanc just use a variable for that, example:

```js
var ctrl = this;

// something here...

Meteor.call('somemethod', (err, res) => {
	ctrl.spinner = false;
});
```

**Comment by mattiLeBlanc** [comment]
You would think so. However it lost its reactivity. So update of variable doesn't work it's way back up
So I need to kick the baby somewhere.

**Comment by nunof07** [comment]
Can't say without seeing your code, but I use this all the time for spinners and similar without issue.

Are you using scope directly or attaching the scope to this?

**Comment by mattiLeBlanc** [comment]
```
class xCtrl {
  private process: boolean = false;

  constructor( private $scope: any ) {
    $reactive(this).attach($scope);
  }

  aFunction() {
      var that = this;
      this.processing = true;


      Meteor.call( 'invoice.credit', function( error, result ) {
        console.log(that);
        if ( error ) {
          that.$log.error( error );
        }
        that.processing  = false;
        that.success     = true;
        that.$scope.$apply();
      } );
  }
}
```

This is not my full class of course. But the point is that in the callback I need to execute apply to make it update.
Running Angular Meteor 1.3.5 on TypeScript compiler

**Comment by nunof07** [comment]
Hmm, I don't usually work with TypeScript, but maybe it could be related with how the code is translated to JavaScript.

What does it log for "that"?

If I was to write that in JS I would do it like this, which is what I usually use and usually works for me:

```js
function ($scope, $reactive) {
	const that = this;

	$reactive(this).attach($scope);
	
	this.processing = false;
	this.success = false;
	
	this.aFunction = () => {
		this.processing = true;

		Meteor.call('invoice.credit', (error, result) => {
			console.log(that);
			
			if (error) {
				that.success = false;
			} else {
				that.success = true;
			}
			that.processing = false;
		} );
	};
}
```

**Comment by mattiLeBlanc** [comment]
That would be the this object. So setting the var works as a workaround for now. Maybe it is the compiler (pbastowski:typescript). Maybe not.

**Comment by nunof07** [comment]
I hadn't noticed before that you mentioned that calling the $scope.$apply() made it work for you.

I still think it's a bit strange you need to call $apply() for it to work, but at least you got it working.

**Comment by mattiLeBlanc** [comment]
Yes, it strange. It think it is somehow cut of from angulars 2 way binding? Or just running after the digest maybe. Cause it is an async call.

**Comment by mattiLeBlanc** [comment]
Seriously...it stopped working and I tried $digest which no works....I am a bit scared of this behaviour.

**Comment by Urigo** [comment]
`angular@1.3.6-beta.1` was released.
Please check the new `this.call` to see if that works for you.

**Comment by mattiLeBlanc** [comment]
Yep, it seems to have been resolved. Thank you!

**Comment by erperejildo** [comment]
facing same issue:
https://github.com/Urigo/angular-meteor/issues/1116#issuecomment-175592538
