### ISSUE TITLE
subscription is not working after using $state.go()

### ISSUE THREAD

**Issue by pacozaa** [Urigo/angular-meteor#1148]
I have two pages
first it is login page
second it is customer data page

then after login success
I use 
$state.go('customer');
to redirect to customer page but the collection in helper in customer page is not return anything
but 
if I press refresh or type in url direct in the browser 
the collection in helper in customer page will return everything I expected.

1. Everything in helper is works fine except collection which need subscription.
2. So I guess that $state.go('customer'); not make my subscription meteor subscribe the collection

How do I fix this problem?

**Comment by kamilkisiela** [comment]
I think it's related to #1108
