### ISSUE TITLE
namspace angular-meteor '$' services and blaze

### ISSUE THREAD

**Issue by ndevr** [Urigo/angular-meteor#115]
#20 Great but...

I think this project is an wrapper around meteor and it would be more easier for everyone (especially for new users which coming from meteor to angular) when it only exists one service-handler "$meteor" for all other services. It is very strict and you will save a lot of time. The learning curve would be very high if you're using exactly the same func names/struct:

$meteor.collection = Meteor.Collections
$meteor.subscripe = Meteor.Subscibe 
$meteor.method Meteor.Method
$meteor.user =  (Meteor.currentUser and more??? = collect?)
$meteor.autorun = Meteor.autorun
$meteor.dept = Meteor.dept
$meteor.collectionFS = Meteor.CollectionFS

I also don't like to work with the Globals (Collections etc.) somewhere. I think every 3rd Party Lib (Meteor) should be completely wrapped. Globals should be injected in that project only - not later in controllers or somewhere because thats the wrapper. It makes testing much more easier and the code remains clean and nobody is confused why I'am using a angular collection wrapper and in a callback the global collection (example see docs).

Another think which we can talk about is that we should not hack the blaze/handlbar templating from meteor anymore. I think we should discus that with meteor to make blaze optional and we can use the native stuff from angular. That will make Meteor + Angular more closely.

What you think guys?

**Comment by yagoferrer** [comment]
+1 for this. Having a general $meteor service with the same API structure sounds like a good idea. Under the hood can keep the same service names.

**Comment by Urigo** [comment]
@ndevr good idea about the $meteor, let me think about it for a few days.

Also about the globals I agree and we disscusted this issue a bit in our team.  any thoughts about how to implement that?

And about making Blaze optional:
https://github.com/meteor/meteor/issues/3400
https://github.com/meteor/meteor/issues/2765

**Comment by ndevr** [comment]
@Urigo still thinking about it ;) ???

**Comment by Urigo** [comment]
@ndevr yes sorry for the delay, done a few stuff for the new version.
I think this a good idea and I agree!
I hope to get to that soon but it looks like a simple change, do you might want to pull request it?

**Comment by Urigo** [comment]
Fixed.
Will be released in 0.7
