### ISSUE TITLE
$scope.getReactively always returns undefined

### ISSUE THREAD

**Issue by leizard** [Urigo/angular-meteor#1154]
Hi,
I use angular-meteor package on Bower.
In my app, I use $scope.getReactively like this:

```
angular.module('myapp.controllers')
	.controller('TaskListCtrl', taskListCtrl);

function taskListCtrl($scope, $rootScope) {
	$scope.startPoint = 0;
	$scope.subscribe('tasks', function() {
		return [
			$rootScope.getReactively('companyId'),
			{
				limit: 20,
				skip: $scope.getReactively('startPoint'),
				sort: {
					updateddate: -1
				}
			}
		];
	}, {
		onReady: function () {
		}
	});
}

```

The subscribe always fail because $scope.getReactively always return undefined. However,  `$rootScope.getReactively('companyId')` still working. I tried some ways like

```
	$scope.startPoint = 0;
	console.log($scope.getReactively('startPoint'));
	$scope.subscribe('tasks', function() {
		return [
			$rootScope.getReactively('companyId'),
			{
				limit: 20,
				skip: $scope.getReactively('startPoint'),
				sort: {
					updateddate: -1
				}
			}
		];
	}, {
		onReady: function () {
		}
	});

	$scope.startPoint = 10;

```

But `$scope.getReactively('startPoint')` always return undefined. Do I get it wrong somewhere ?

**Comment by leizard** [comment]
I update angular-meteor to 1.3.5 and it work again. don't know why but i'm happy it work, took me 1 days :(.

**Comment by jsantana90** [comment]
that was weird, I was having the same problem and updated angular to 1.3.5 and it fixed it. Thanks!

**Comment by leizard** [comment]
glad it helped you :smile: . I'm curious about the use case you use angular-meteor through bower ? Are you developing a meteor mobile client ?

**Comment by erperejildo** [comment]
I'm struggling to share a rootScope variable between 2 components using angular-meteor. I don't know if you would know how to deal with this @leizard, 
I've got 1 component inside another one and I'd like to change and show this variable in any of these components.
I'm using Angular 1 but with typeScript
