### ISSUE TITLE
subscribe onReady is called before Client-side collection is updated

### ISSUE THREAD

**Issue by DmitryEfimenko** [Urigo/angular-meteor#1161]
It appears I'm running into the the exact behavior that is described in the new Meteor Guide's section [Publication behavior when arguments change](http://guide.meteor.com/data-loading.html#publication-behavior-with-arguments), and I'm wondering if this could be improved for angular developers. Here is my simplified code (TypeScript):
**Server**
```typescript
Meteor.publish('parties', function(fnName: string, terms: any) {
    let params = queryConstructor(fnName, terms);
    return Models.find(params.selector, params.options);
});
```

**Client Controller**
```typescript
class PartiesController extends ReactiveComponent {
    static $inject = ['$scope', '$reactive', '$timeout'];
    parties: any[];
    terms = { 
        page: 1,
        pageSize: 10
    };

    constructor($scope: angular.meteor.IScope, $reactive, $timeout) {
        super();
        $reactive(this).attach($scope);
        
        this.subscribe('parties', ()=> ['parties.paged', this.getReactively('terms', true)], ()=> {
            // below is code that demonstrates issue
            // this callback function is called kind of too fast: The subscription is ready,
            // but local collection of 'Parties' still has old records
            let allClientParties = Parties.find().fetch();
            // for the first run the log below will be 10 (the size of terms.pageSize).
            // The second run (when I clicked on page 2) this will be 20.
            console.log(allClientParties.length);
            $timeout(()=> {
                console.log(allClientParties.length); // will return 10 for the first and second run.
            }, 500);
            
            
            // the code that I'd like to "just work", but currently I have to wrap it in a timeout and wait for
            // some time for local collection to get rid of old records.
            let params = queryConstructor('parties.paged', this.terms);
            this.parties = Parties.find(params.selector, params.options).fetch();
        });
    }
}
```
Please see the comments in the code above.
I'm not sure that changing the behavior of `onReady` callback would be appropriate.
Perhaps having some other callback like `onClientReady` would be a better solution.

**Comment by Urigo** [comment]
@DmitryEfimenko thank you for your question.
With Angular-Meteor 1.3 we are trying to stay as close to the rest of the community as possible.
That means the we want the `onReady` to fire exactly when Meteor's fire `onReady`.
and that means that Angular-Meteor best practice will be exactly like Meteor's best practices which means you should count on the data to be there.
So you should initialize `this.parties` as a helper and not as a regular param that initializes only once.

About another callback, I think that it's a nice idea that should go as a separate package that helps both Angular-Meteor developers as well as React and Blaze Meteor developers.

Let me know if that's making sense for you

**Comment by DmitryEfimenko** [comment]
This issue popped up is due to the confusion about proper way of using `.helpers`: Issue #1110. Since I was getting warnings all over, I thought not using `.helpers` is the way to go. Thanks to your comments on both this issue and issue #1110 I now understand, that using `.helpers` is the right way.
I am only now uncertain about some use cases when using `.helpers`, which, as you pointed out in #1110, should be clarified shortly.

I'm going to close this issue (since the code in it does not follow best practices at all) and wait for clarifications for #1110.

Thanks for great work!

**Comment by Urigo** [comment]
`angular@1.3.6-beta.1` was released.
Please check if that works for you.

**Comment by erperejildo** [comment]
@Urigo I'm using latest Angular and angular-meteor and still facing this issue
