### ISSUE TITLE
Update videos for tutorial chapters

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#1169]
Request for help from the community to screencast yourself explaining and performing the updated Angular1-Meteor-Socially chapters.
It can be even one chapter for each contributor.

So that we won't have outdated videos very soon you should use the [Angular1-Meteor 1.4.0-beta release with Npm support](https://github.com/Urigo/angular-meteor/milestones/1.4.0-beta.1).

List of chapters to keep track:
- [ ] Chapter 0
- [ ] Chapter 1
- [ ] Chapter 2
- [ ] Chapter 3
- [ ] Chapter 4
- [ ] Chapter 5
- [ ] Chapter 6
- [ ] Chapter 7
- [ ] Chapter 8
- [ ] Chapter 9
- [ ] Chapter 10
- [ ] Chapter 11
- [ ] Chapter 12
- [ ] Chapter 13
- [ ] Chapter 14
- [ ] Chapter 15
- [ ] Chapter 16
- [ ] Chapter 17
- [ ] Chapter 18
- [ ] Chapter 19
- [ ] Chapter 20
- [ ] Chapter 21
- [ ] Chapter 22

**Comment by Urigo** [comment]
codemill$1500

**Comment by Urigo** [comment]
@DragonK-Olbius has been assigned to this task.

**Comment by Urigo** [comment]
@DragonK-Olbius has been unassigned from this task.

**Comment by Urigo** [comment]
@selfrefactor has been assigned to this task.

**Comment by LoveIsGrief** [comment]
Are the tutorials still for Meteor 1.3 still out? Meteor 1.4 is up and I noticed the current tutorials still use the old folder structure - /lib folder as opposed to the /import folder.

**Comment by Urigo** [comment]
will be part of the next major version of the tutorial
