### ISSUE TITLE
can not use this.$emit?

### ISSUE THREAD

**Issue by pacozaa** [Urigo/angular-meteor#1170]
I've try to used this.$emit  in the some.component.js
`this.$emit('myCustomEvent', 'Data to send');`
but the browser show the error that
`$emit is not a function`
then I end up using
`$scope.$emit('myCustomEvent', 'Data to send');`

**Comment by kamilkisiela** [comment]
Reactive component has only meteor-mongo related things. Why it should also contain `$emit`, `$broadcast` and `$on`?

It works in different direction, `Scope` is extended by `ReactiveScope`, not the other way.

**Comment by pacozaa** [comment]
@kamilkisiela Thank you. I'm trying to send data from $mdDialog(angular material) to their parents.
Do you know how to do it?

**Comment by Deadly0** [comment]
@pacozaa look at the example https://material.angularjs.org/latest/demo/dialog
To send data back you can use ```$mdDialog.hide(answer)``` . ```answer``` is your data.

```
$scope.answer = function(answer) {
    $mdDialog.hide(answer);
  };
```

**Comment by pacozaa** [comment]
@Deadly0  Thank you :)
