### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by TWKDreamState** [Urigo/angular-meteor#1173]
Can I just check? After many hours bug hunting...

The only way I can get a production (ie. minified version) following the tutorial advice (but in my own app) and trying to use best practice with controllerAs and Components is to inject into the directives....

    selectSurveyController.$inject = ['$scope', '$reactive'];

...is this correct?

**Comment by Urigo** [comment]
I'm not sure what is your question..

**Comment by TWKDreamState** [comment]
@Urigo Hi, sorry for not explaining. I've been writing the app previously with out DI manual declaration (as per step 2.3 in the tutorial) and not had any issues. Recently, I've been trying to change to controllerAs and Components and noticed it wouldn't work in production mode without DI although step 3.8 in tutorial doesn't declare them either so I'm a bit confused if I've missed something somewhere.

**Comment by TWKDreamState** [comment]
Ok, I think it's related to ng-annotate

Seems similar to this https://github.com/olov/ng-annotate/issues/54

I am separating my directive into a function so that might be interfering with the automatic DI.

ie.

```
.directive('selectSurvey', selectSurvey);

function selectSurvey ... etc
```

so I need to write in the DI.

**Comment by Urigo** [comment]
thanks for updating
