### ISSUE TITLE
any update to use angular material 2 ?

### ISSUE THREAD

**Issue by skyboys22** [Urigo/angular-meteor#1174]
hello,

is there possibility to use angular material 2 with angular2-meteor ?

version of angular2 used is not complete, someone can guide me to fixe it !

thank you

**Comment by Urigo** [comment]
yes we have it working on the next version on Socially 2.0 with Meteor 1.3.
Will be updated in the tutorial when Meteor 1.3 will be out

**Comment by Urigo** [comment]
Enjoy :)
http://www.angular-meteor.com/tutorials/socially/angular2/angular-material-and-custom-angular-auth-forms
