### ISSUE TITLE
How to distinguish between logout by other client and and logout by myself?

### ISSUE THREAD

**Issue by fancyer** [Urigo/angular-meteor#1175]
I need to alert current client when logged out by other client.
I know that watch $rootScope.currentUser or use autorun can catch a logout, but how do I know it is from other client or "myself"?

Is there "event:logoutByOtherClients" or something can catch?

**Comment by ozsay** [comment]
by "other clients" you mean the same user logs in from 2 different devices?

**Comment by fancyer** [comment]
yes, and the new client will logout old

**Comment by ozsay** [comment]
Well I don't think that there is an official implementation (not in `angular-meteor`nor `meteor`) since it's looks to me like a specific need. Maybe there is a package for it in `atmosphere`.

**Comment by fancyer** [comment]
thanks for your comment.
unfortunately I haven't find package for this yet. I will try client-side solution again.

**Comment by ozsay** [comment]
In the users collection meteor keeps all the login tokens under `user.services.resume.loginTokens` (each logged in client has a login hash). You can publish that data to the clients and then observe the changes in this array to detect user logouts in different clients.

**Comment by jacobdr** [comment]
That sounds like security vulnerability city to me. 




@fancyer, in the future please provide a much more detailed question and also walk through the user story. It is much easier for the community to help when they are provided context. 



One alternative (maybe) is that you could use the user-agent provided by the browser to try to implement this feature. While the user is logged in you could send a periodic poll and make sure they are still on the same device. Then, when a user clicks the "log out" button, you can compre the state of the world against what you thought it was. 




Such polling would probably best be done using DDP hooks, but you could also tie it to certain user events like loading pages/ clicking buttons /etc. 












—

**Comment by fancyer** [comment]
@jacobdr Thanks for your advice, I will do better next time.

It seems there is no simple client-side way for this, I will try your suggestion.

Thanks for you all.

**Comment by ozsay** [comment]
@jacobdr All these tokens are available to the client without this publication. meteor saves them in the `localStorage` and uses them to perform auto-login when you refresh the page\ reopen the app (in a later time).

**Comment by jacobdr** [comment]
@Oz you're solution was clever, and you are right about availability of the
tokens.

However, but I wouldn't call the Meteor security situation impressive by
any means. The fact that passwords are sent unencrypted (hashed, but
unencrypted) over the wire by default is really not ideal. These tokens
also seem like a ripe attack vector.

**Comment by Urigo** [comment]
@fancyer I'm not sure about your use case, does `[Meteor.Meteor.logoutOtherClients](http://docs.meteor.com/#/full/meteor_logoutotherclients)` answers your use case?

**Comment by fancyer** [comment]
@Urigo Let's make a "user story".

I have one iPhone, so do my girlfriend, both of them installed "WhateverApp". 

I have logged in on my phone. My girl knows the password. One day she login with my account on her phone, and my "whateverApp" logged out by her login.

What I want is the App should ALERT me when I'm logged out by her, not just delete my login state silently. 

So the technical problem is : how do I cacth logoutOtherClients event as a "other client"?

**Comment by Urigo** [comment]
sounds like a nice feature that not only the Angular Meteor community will benefit from but the whole Meteor community.
I would create a package for that and post it on the Meteor forums to get feedback.
Closing as it's not related to Angular Meteor in my mind, but please feel free to re-open and correct me if I'm wrong

**Comment by fancyer** [comment]
Guys I resolved this problem with only client side code.

Angular-meteor stores Meteor.loginToken in local storage, and removes it when logout.
When I login, add a key to local storage, when I log out, remove it.

```javascript
// set & remove login status
login callBack: window.localStorage.setItem('loginStatus', '1');
logout callBack: window.localStorage.removeItem('loginStatus');

$meteor.autorun($rootScope, function(){
  var currentUser = $rootScope.getReactively('currentUser');
  
  // exit app or logged out
  if(!currentUser){
    // logged out, by self or server
    if(!window.localStorage.getItem('Meteor.loginToken'){
      $state.go('login');

      // log out by server
      if(window.localStorage.getItem('loginStatus')){
        alert('YOU ARE DOOMED!');
      } 
    }
  }  
})
```
