### ISSUE TITLE
Can not subscribe CollectionFS

### ISSUE THREAD

**Issue by pacozaa** [Urigo/angular-meteor#1177]
I have try to subscribe CollectionFS but still not working. I will show what I've try to do so far.

First in my model folder

```javascript
Prints = new FS.Collection('prints', {
  stores: [
    new FS.Store.GridFS('original')
  ],
  filter: {
    allow: {
      contentTypes: ['image/*']
    }
  }
});
Prints.allow({
  insert: function (userId) {
    return true;
  },
  remove: function (userId) {
    return true;
  },
  download: function (userId) {
    return true;
  },
  update: function (userId) {
    return true;
  }
});

```
Second in my server folder
```javascript
Meteor.publish('prints', function () {
  return Prints.find({});
});

```

Third in my component

```javascript
this.helpers({
        oldImage: () => {
          return Prints.find({}).count();
        }
      });

this.subscribe('prints');
  this.autorun(() => {
        console.log('Autorun!!', this.getReactively('oldImage'));
      });
```
I use code above to to print exist row which should print (there is a file in the collection)
`Autorun!! 1` but I still got `Autorun!! 0`
So you may wondering why I sure that there is a file in the collection because I have check with Robotmongo and use
` Prints.find({}).count() `
in the Chrome Developers tools and it returned 1 in the console.

So I wonder why I can not get the any Prints(CollectionFS) in the directive and How to solve this problem.

Any further question would be appreciate.

Thank you.

**Comment by Deadly0** [comment]
@pacozaa, try to return mongo cursor instead of number in helper.

```
this.helpers({
        oldImage: () => {
          return Prints.find({});
        }
      });
```

By the way, there are a lot of bugs with reactivity and helpers in 1.3.5. Wait for 1.3.6, i guess, it will be fixed soon.

**Comment by ozsay** [comment]
Can you try to upgrade to `angular-meteor` 1.3.6-beta.1?

Also, setting a number (`Prints.find({}).count()`) as helper is deprecated. You should use `autorun` instead:

```js
this.subscribe('prints');
this.autorun(() => {
    this.count = Prints.find({}).count();
});
```

**Comment by pacozaa** [comment]
@ozsay Thank you.
I will try it the day after tomorrow and give info back to you.

**Comment by pacozaa** [comment]
@ozsay Hey, I test `angular-meteor@1.3.6-beta.1` with this issue what it came out is 

1. @Deadly0 suggestion works.
`
this.helpers({
     PrintImages: () => {
          return Prints.find({});
        }
});
`
and then in html file I just call {{controllerName.PrintImages[0].url()}}
2. @ozsay your suggestion above doesn't work.
3. I have tried 
`
this.helpers({
     PrintImages: () => {
          return Prints.findOne();
        }
});
`
it doesn't work.
4. I have tried 
`
this.helpers({
     PrintImages: () => {
          return Prints.find({}).fetch()[0];
        }
});
`
it doesn't work.
5. I have tried 
`
this.helpers({
     PrintImages: () => {
          return Prints.find({})[0];
        }
});
`
it doesn't work.

Seem likes one it has to return array to make it subscribe to collectionFS

**Comment by Urigo** [comment]
@pacozaa just released `1.3.6`.
It seems like you found a solution but please also try the following:

```
this.autorun(() => {
  this.PrintImages = Prints.findOne();
});
```

**Comment by pacozaa** [comment]
@Urigo You suggestion is not work with `1.3.6 or 1.3.5` (I've tried this with 1.3.5 before)as my opinion above I don't think it subscribe or reactive with single value neither findOne() nor count()

**Comment by Urigo** [comment]
@pacozaa so I guess this is another problem.
if you can share a reproduction in a repo I can have a look

**Comment by pacozaa** [comment]
@Urigo How to reproduction in a repo?
If I run meteor on my laptop which directory in project I have to edit or modify. Is it `.meteor/build` ?
I would like to help you make angular-meteor better, so any advice to help or solve this issue is appreciate.
