### ISSUE TITLE
Release Angular1Meteor through Npm

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#1178]
- [ ] expose Angular1Meteor through Npm as default.
- [ ] use it in an Atmosphere package to be compatible with Meteor versions before 1.3.
- [ ] expose old legacy code to Npm as well as older version 1.2

**Comment by kamilkisiela** [comment]
Only things that could be exposed in npm are: `angular-meteor-data` and `angular-meteor-auth`.
Compilers stays in atmosphere.

Names in npm:
`angular-meteor-data` as `angular-meteor`
`angular-meteor-auth` stays the same

What you all think about using webpack?

I prepared an example how it would be look like.
https://github.com/kamilkisiela/angular-meteor/tree/v1.4.x-npm/packages/angular-meteor-data

---

About name of the main package. 
At the moment angular-meteor has two dependencies:

`angular-meteor-data`
`angular-templates`

But `angular-templates` is a compiler so it cannot be published as npm package.

That's the reason of my proposal of keeping `angular-meteor-data` as `angular-meteor` in npm.

It allows to include possible `angular-templates` in main `angular-meteor` package in the future.

**Comment by Urigo** [comment]
@kamilkisiela sounds great.
It's also aligned with Angular2-Meteor where the process will be:

```
npm install angular2
npm install angular2-meteor
meteor add angular2-compilers
```
so in Angular1-Meteor it might look like:
```
npm install angular
npm install angular-meteor
meteor add angular-compilers // which will consist of `angular-html-templates` (now called angular-templates) and `pbastowski:angular-babel` (until we will get everything inside the official `ecmascript`)
```

we also are using Webpack there so Webpack sounds great.

**Comment by kamilkisiela** [comment]
@Urigo May I do something in that direction so we can already work on it in `v1.4`?

`v1.4.x` branch is rapidly updated so should I still wait? Or may I prepare PR so everybody could switch into angular1-meteor with build process (`webpack`)?

**Comment by kamilkisiela** [comment]
@Urigo And I think we should use some code standards to keep code clean also to prevent silly mistakes like using not defined variables etc. My proposal is to use `eslint` with `airbnb`'s rules with few changes.

We're using eslint in `angular2-now` and it works great :)

**Comment by Urigo** [comment]
@kamilkisiela I think that this weekend we will close a beta for 1.3.6 and then use your change in 1.3.7.
So let's wait for Sunday for the Npm branch.
About the code cleanup I think that's a great suggestion.
Can you open it as a separate issue to track?
also, do you think we could connect it to Bithound?

**Comment by kamilkisiela** [comment]
Ok

**Comment by kamilkisiela** [comment]
Bithound supports ESLint do yeah, it is possible

**Comment by kamilkisiela** [comment]
I'm impatient so I pulled down `1.3.6` branch and added build process (webpack) with linting utility (eslint).

You can see it here:
https://github.com/kamilkisiela/angular-meteor/tree/v1.3.7/packages/angular-meteor-data

---

**Testing**

To run tests in watch mode so velocity can receive changes and wepack can rebuild output file:

```
npm run watch
npm run test:local
```

To run tests in **CI mode**:

```
npm test
```

---

**Building**

Outputs not minified bundle:

```
npm run build:dist
```

Outputs minified bundle:

```
npm run build:prod
```

Both at once:

```
npm run build
```

---

I came up with idea.

Names of modules and services are being used as a `string` so to avoid silly mistakes like typo etc ,we can use something like this:

```javascript
import { Mixer, module as mixerModule } from './modules/mixer';

export const module = 'angular-meteor.reactive';
export const Reactive = '$$Reactive';

angular.module(module, [ 
    mixerModule
]);

service(Reactive, [
Mixer
function($$Mixer) { /* ... */ }
])
```

**Comment by Urigo** [comment]
done.
Thank you @kamilkisiela for the huge help and great work!
