### ISSUE TITLE
Issue when starting an application

### ISSUE THREAD

**Issue by TyrionGraphiste** [Urigo/angular-meteor#1179]
Hi, I'm new with angular-meteor and just get an issue that I don't understand.
I'm trying to run meteor after linked angular 2 to my app, but when I meteorize I get this issue :

> C:\Users\my_user\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
>                                                      ^
> Error: Path reservation conflict: app/client/app.js

So I added Angular 2 with **meteor add urigo:angular2-meteor**, I removed **Blaze** and **ecmascript**, but it's not working as wanted.

I'm following exactly the given example but there is no mention of this, could someone help me to solve it?
This isn't a good idea to use angular 2 right now ?

**Comment by Urigo** [comment]
@TyrionGraphiste can you please share a repo with your problem?

**Comment by TyrionGraphiste** [comment]
Hi, I stopped to use this repository.
