### ISSUE TITLE
How to integrate Ground db in angular-meteor app

### ISSUE THREAD

**Issue by niketaB** [Urigo/angular-meteor#1180]
I need some guidelines to integrate ground DB with Angular-ionic type of application.
What exactly, i am doing is, 
1. I have ionic-angular application
2. I am using angular-meteor package in to Ionic application, to get meteor packages and functionality.
Now I want to use GroundDB, which is meteor package in to my App.
Is the ground db package available with angular-meteor package ?
Please let us know how to integrate this and use it.

**Comment by LucNaterop** [comment]
+ 1

**Comment by Urigo** [comment]
for specific question please post your repo and then I can provide answers..
Closing but please re-open if you haven't found a solution and if you did, please post that solution here for others to enjoy
