### ISSUE TITLE
Hmm.. the website angular-meteor.com is down

### ISSUE THREAD

**Issue by Hongbo-Miao** [Urigo/angular-meteor#1181]
I am not sure whether this is place to report. But the website [angular-meteor.com](http://www.angular-meteor.com/) has been down a while.

**Comment by Deadly0** [comment]
Can't open website too.

**Comment by BradleyFaught** [comment]
Website is still down, just so you guys know. Great Tutorial btw.

**Comment by berkaey** [comment]
yeap same here

**Comment by rafaelb** [comment]
@Urigo angular-meteor.com is down

**Comment by davidmoret** [comment]
Indeed..
Is there another place to see the lastest api doc ?

**Comment by Urigo** [comment]
Fixed.
I'm keeping it open because there is something I need to do to make it more permanent..

**Comment by davidmoret** [comment]
Thanks !

**Comment by ThomsC** [comment]
looks like it is down again..
