### ISSUE TITLE
Run socially on 1.3.6 branch and make sure it works properly

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#1183]

**Comment by riongull** [comment]
New to development here, so pardon me if I'm wrong, but I think the socially tutorial may still have outdated syntax on step 3.2. 

Should this block of code work with the 1.3.6 API?  It looks like the new usage requires $reactive.

  angular.module('socially', ['angular-meteor']);
 
  angular.module('socially').controller('PartiesListCtrl', function ($scope) {
    $scope.helpers({
      parties: () => {
        return Parties.find({});
      }
    });
  });
}

When I ran that code in
