### ISSUE TITLE
Double check docs for 1.3.6

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#1186]
Make sure no breaking change from 1.3.5 and that all the needed info is there (by issues opened as questions)

**Comment by ozsay** [comment]
@Urigo I added the api for Meteor methods: `this.call` and `this.apply`. Should we add 1.3.6 to the API list?

**Comment by Urigo** [comment]
yes

**Comment by ozsay** [comment]
Docs have been updated. After the merge to master I need to update the links in them
