### ISSUE TITLE
Linting utility for Angular1Meteor

### ISSUE THREAD

**Issue by kamilkisiela** [Urigo/angular-meteor#1187]
I suggest to use [`ESLint`](http://eslint.org/) because of its simplicity and it is much more human-friendly than `jsHint`. ESLint supports meteor environment so it's a additional cons :)

with

[`eslint-config-airbnb/base`](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/base.js) - has ES6 support

As part of build process #1178

**Comment by kamilkisiela** [comment]
@Urigo Issue created, as you said :)

**Comment by Urigo** [comment]
also add it to Bithound checks - https://github.com/Urigo/angular-meteor/issues/1185

**Comment by kamilkisiela** [comment]
It might look similar to this
https://github.com/Urigo/angular-meteor/compare/v1.4.x...kamilkisiela:v1.4.x

Based off of [Airbnb's Style Guide](https://github.com/airbnb/javascript/blob/master/README.md)

Basically, angular-meteor's code on `1.4.x` branch looks great and matches these airbnb's rules in most cases.

**Comment by Urigo** [comment]
thank you @kamilkisiela !

**Comment by kamilkisiela** [comment]
@Urigo :+1:
