### ISSUE TITLE
removing jquery package, angular has jqLite

### ISSUE THREAD

**Issue by mattiLeBlanc** [Urigo/angular-meteor#1189]
Hi,

Not an issue unless I remove the jquery package.
Because I am using template cache, Meteor tries to bootstrap the body with $ which is not available after removal.
However, Angular normally reverts to JQLite if I am correct.
Anyway way we can ditch jQuery when using Angular + Meteor?

( i did notice jquery was still loaded as a dependency by another package...not really sure which one, but it didn't claim the $).

**Comment by Urigo** [comment]
great question :)
https://github.com/meteor/meteor/pull/6105

**Comment by mattiLeBlanc** [comment]
Thanks buddy.
