### ISSUE TITLE
Silence warnings on pre-1.3.0 releases

### ISSUE THREAD

**Issue by lscordilis** [Urigo/angular-meteor#1193]
I understand both Angular and Angular-meteor are evolving quickly, and you want people to get the best use out of the frameworks by keeping updated. However, your changes between 1.2 and 1.3 are very drastic and updating to 1.3+ involves a huge amount of work on large projects in production. Any serious developer would be aware of new releases and changes going on in the open source frameworks they rely on. I don't think there's a need to flood the console with warnings and reminders to update. 

Thank you for your consideration

**Comment by ozsay** [comment]
Are you referring [those](https://github.com/Urigo/angular-meteor/blob/b32a9d59ce4fa26d7ccf3d84b9924f84709f7ddb/packages/angular-meteor-data/modules/angular-meteor-camera.js#L9) warnings ?

**Comment by ozsay** [comment]
I'm closing since it's a duplicate and already been fixed in 1.3.6 https://github.com/Urigo/angular-meteor/issues/1109#issuecomment-180741235

**Comment by Urigo** [comment]
@ozsay add a note about how to silent warnings in the warnings themselves

**Comment by Urigo** [comment]
`angular@1.3.6-beta.1` was released.
Here is the API on how the silence warnings - http://www.angular-meteor.com/api/1.3.6/settings
