### ISSUE TITLE
Using ReactiveComponent with Angular1.4

### ISSUE THREAD

**Issue by mattiLeBlanc** [Urigo/angular-meteor#1194]
https://github.com/dotansimha/angular-reactive-component/issues/3

I was able to make ReactiveComponent work without using angular2-now and reaping small benefit of not having to bind this to reactiveContext.

**Comment by mattiLeBlanc** [comment]
Well, I just noticed that if I do not use ReactiveComponent but run `$reactive( this ).attach( $scope );` in the constructor it works the same and I don't need a reactiveContext.

What is the proper way right now, there seems to be multiple ways to do the same thing.

**Comment by ozsay** [comment]
if you extend ReactiveComponent, you don't need to attach the scope to the reactive context. It does it for you.

Both ways do the same.

**Comment by mattiLeBlanc** [comment]
Yes, I realised that.
