### ISSUE TITLE
defining 'invoices' value helper, note that this feature will be deprecated in 1.4 in favor of using 'getReactively'

### ISSUE THREAD

**Issue by mattiLeBlanc** [Urigo/angular-meteor#1195]
Hi,

I am not really sure what you mean with this warning:
defining 'invoices' value helper, note that this feature will be deprecated in 1.4 in favor of using 'getReactively' - http://www.angular-meteor.com/api/1.3.1/get-reactively

I am only setting up a helper in my controllers's constructor
```
{
    super( arguments );
    this.subscribe( 'invoices', () => [ this.invoiceFilter 
    ] );
    
    this.helpers( {
      invoices: () => Invoices.find( {} )
    } );
}
```

What will be deprecated about this.helpers? Reading the 1.32 docs It seems to be the valid way to do it, right?
(by the way I am extending my class with ReactiveComponent)

**Comment by ozsay** [comment]
There is an issue with this specific deprecation warning. It will be removed in the next version.

You can read [this](https://github.com/Urigo/angular-meteor/issues/1110#issuecomment-178502477) comment of @dotansimha in another issue.

I'm closing since it's a duplicate.

**Comment by mattiLeBlanc** [comment]
okay, no worries.
