### ISSUE TITLE
Subscription stoppped after state change in success login promise handler

### ISSUE THREAD

**Issue by mattiLeBlanc** [Urigo/angular-meteor#1198]
okay...that subject was a mouthful....

Anyway, the core issue is that my subscription is created and immediately stopped on state render.
But only when it is followed after a login process.

So I am using Angular-Meteor 1.35 and angular-ui-router 0.2.15. I code in TypeScript.

Test case 1:

```
doLogin() {
    this.$scope.$broadcast('show-errors-check-validity');

    if ( this.$scope.frmLogin.$invalid) { return; }


    this.authService.login( this.user )

      .then( ( result: any ) => {

          this.$state.go( 'private.dashboard.open' ); // <----- this state changes to dashboard triggers a subscription create and close

      } )

      .catch( ( error: any ) => {

        this.$scope.frmLogin.password.$setValidity( 'incorrect', false );

        // reBroadcast to show all current errors
        //
        this.$scope.$broadcast('show-errors-check-validity');

      } );

  }
```

So when I login, and the promise has been resolved and I call $state.go to my dashboard I end up with a empty listing and in my console I see:
```
onReady And the Items actually Arrive []          dashboard.controller.ts:28
The subscription stopped          dashboard.controller.ts:28
```

When I do a similar $stage.go from any other state while being logged in then the subscription always stays alive.

FIX1:
So, I figured out that the list-item directive I use in the dashboard list with invoices has its own scope. When I comment this listitem directive in my dashboard.open state, and login....Voila we have an active subscription and now stopping.
Weird....and not helpful cause I need the directive. 

Fix2: 
This one seems to fix a lot of angular things....using a timeout to get something behind in the digest process.
```
  doLogin() {
    this.$scope.$broadcast('show-errors-check-validity');

    if ( this.$scope.frmLogin.$invalid) { return; }


    this.authService.login( this.user )

      .then( ( result: any ) => {
         window.setTimeout( () => {
          this.$state.go( 'private.dashboard.open' );
        }, 0 );
        // this.$state.go( 'private.dashboard.open' );
      } )

      .catch( ( error: any ) => {

        this.$scope.frmLogin.password.$setValidity( 'incorrect', false );

        // reBroadcast to show all current errors
        //
        this.$scope.$broadcast('show-errors-check-validity');

      } );

  }
```

With the timeout (yes I should use $timeout) it works fine with the directive enabled in the dashboard,open state. So I reckon, during the resolve of the login promise, and the state change the controller is created and destroyed.

I must say that I have set the controller on an abstract state and its shared with its state siblings:
```
 .state('private.dashboard',
    {
      url: '/dashboard'
    , abstract: true
    , views:
      {
        'container@private':
        {
            templateUrl: 'client/views/dashboard/dashboard.html'
          , controller:   'DashboardController'
          , controllerAs: 'vm'
        }
        , 'header@private':
        {
          templateUrl: 'client/views/layout/header.html'
        }
        , 'footer@private':
        {
          templateUrl: 'client/views/layout/footer.html'
        }
      }
    } )
    .state('private.dashboard.open',
    {
      url: '/open'
      , views:
      {
        'headerContent@private.dashboard':
        {
          templateUrl: 'client/views/dashboard/header.content.html'
        }
      , 'content@private.dashboard':
        {
          templateUrl: 'client/views/dashboard/open/open.html'
          // , controller:   'GetStartedController'
          // , controllerAs: 'vm'
        }
      }
    })
    .state('private.dashboard.activated',
    {
      url: '/activated'
      , views:
      {
        'content@private.dashboard':
        {
          templateUrl: 'client/views/dashboard/activated/activated.html'
        }
      }
    })
```
This seems to work pretty nicely because both siblings inherit the controller. 
There are no issue navigating in the app back and fort to the dashboard. Only when I login.

Finally the auth service I made:
```
public login( user: any ) {

    var deferred = this.$q.defer();


    Meteor.loginWithPassword( user.email, user.password, ( error ) => {

      var message;

      if ( error ) {

        console.log(error);

        if (error.reason === 'Incorrect password') {

          message = 'Email and password combination is incorrect';
        }
        if (error.reason === 'User not found') {
          message = 'No account found with this email address';
        }

        deferred.resolve( {

          status:   'ERROR'
        , message:  message
        } );

      }
      else {

        deferred.resolve( {

          status:   'OK'
        , message:  'User loggedin'
        } );
      }
    });
    return deferred.promise;
  }
```
Again, nothing fancy, just a Q promise.

Am I looking at a strange UI-Routing bug here?

**Comment by ozsay** [comment]
Hi,

I believe that this issue is related to another one. Please read my comment [there](https://github.com/Urigo/angular-meteor/issues/1108#issuecomment-179232141).

I would appreciate if you test your code with 1.3.6 (which isn't released yet). In the comment I explained how to do this.

Thanks

**Comment by mattiLeBlanc** [comment]
Yes, it looks to be another duplicate. Sorry for that. I though mine was pretty specific and unique. It is not. :)

**Comment by ozsay** [comment]
Hi,
we released 1.3.6-beta.1 to atmosphere. Can you test your app with it?

Thanks

**Comment by Urigo** [comment]
`1.3.6` was released and was supposed to fix this issue.
Please re-open and tag me with a reproduction project if it doesn't work for you.

**Comment by mattiLeBlanc** [comment]
Yep, it seemed to have resolved this issue. Thanks
