### ISSUE TITLE
Replace absolute URLs with template declarations

### ISSUE THREAD

**Issue by cubitworx** [Urigo/angular-meteor#1199]
This is a feature request to allow templates to be referenced by their declarations instead of file names.

One thing I was surprised about is that angular-meteor uses absolute path references instead of referencing templates by there declared name; if you consider that meteor is built around the idea of finding templates regardless of which files they are in or where those files are located.

I reference the example in the [Meteor-Angular Socially App Tutorial - step 21.13](http://www.angular-meteor.com/tutorials/socially/angular1/mobile-support-and-packages-isolation). This example shows the absolute path of `templateUrl` to be `'/packages/socially-browser/client/auth/login/login.html'`.

Imagine you could instead define templates for use within angular-meteor with the following syntax:

blaze template syntax:

    <template name="auth/login.html">
    </template>

And/Or angular template syntax :

    <script type="text/ng-template" id="/auth/login.html">
    </script>

The consumer of the package could then reference the template, not by the absolute path to the file location in the package but simply with the package name followed by the template name as follows:

If those templates where declared in the `socially-browser` package;

    templateUrl: 'socially-browser/auth/login.html'

If those templates where declared directly in the app:

    templateUrl: '/auth/login.html'

The benefits of changing angular-meteor to allow templates to be accessed by definition instead of absolute path are:
- Templates would no longer be dependant on where they are located
- It would allow package authors to move files around in their package without breaking backwards compatibility
- It would help with the confusion of including package names & prefixes as discussed in #958
- Templates can be grouped by function into a single file, if needed. Great for small or related templates
- It starts to feel and act a lot more like a meteor package should, where you don't need to worry about where your files are located (within reason of course)

Many thanks for the great work on this package!

**Comment by trajano** [comment]
https://github.com/Urigo/angular-meteor/pull/1313 actually addresses the issue.

Once it is implemented your module (in this example a UI-router state)

<pre>
import './main.html'

angular.module(module.name)
  .config(($stateProvider) => {
    $stateProvider.state('sign-in', {
      controller: SignInStateController,
      controllerAs: 'signInStateCtrl',
      parent: 'unauthenticated',
      templateUrl: 'imports/ui/states/sign-in/main.html',
      url: '/sign-in'
    })
  })
</pre>
Could be replaced as
<pre>
import myTemplateUrl from './main.html'

angular.module(module.name)
  .config(($stateProvider) => {
    $stateProvider.state('sign-in', {
      controller: SignInStateController,
      controllerAs: 'signInStateCtrl',
      parent: 'unauthenticated',
      templateUrl: myTemplateUrl
      url: '/sign-in'
    })
  })
</pre>
The one thing I kind of wish it could do, but am not sure where in the code it would be is to NOT load it up immediately as an option.  So it would return a promise rather than a URL.
