### ISSUE TITLE
$meteorObject

### ISSUE THREAD

**Issue by nspangler** [Urigo/angular-meteor#120]
I am following the tutorial, but when I try to add the $meteorObject using:

    angular.module("socially").controller("PartyDetailsCtrl", ['$scope', '$stateParams', '$meteorObject',
         function($scope, $stateParams, $meteorObject){
       $scope.party = $meteorObject(Parties, $stateParams.partyId);
    }]);

I get the following error:

![screen shot 2015-01-10 at 4 09 23 pm](https://cloud.githubusercontent.com/assets/5549886/5693646/5483f20a-98e3-11e4-96f2-6947c3711d3c.png)

**Comment by CharlSparksNZ** [comment]
Same here. Definitely have the 0.6.0-alpha package installed. $meteorCollection works fine but $meteorObject throws the above error. A quick search for the service shows the service doesn't exist.

**Comment by Urigo** [comment]
Just released 0.6.0.
Please try doing 

    meteor update

in the command line and re-run
