### ISSUE TITLE
Move `angular-meteor-auth` into a seperate repo

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#1201]

**Comment by Urigo** [comment]
Moved here - https://github.com/Urigo/angular-meteor-auth

**Comment by sean-stanley** [comment]
The atmosphere link for angular-meteor-auth still goes to [https://github.com/Urigo/angular-meteor](https://github.com/Urigo/angular-meteor) maybe package.js needs updating with new repo url?

**Comment by Urigo** [comment]
@sean-stanley you are right.  fixed and will be done with next deploy (hopefully tomorrow)

**Comment by Urigo** [comment]
deployed.
