### ISSUE TITLE
Make sure Whatsapp clone tutorial with Ionic bundle works with 1.3.6

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#1205]
- [ ] https://forums.meteor.com/t/build-a-whatsapp-clone-with-meteor-and-ionic-meteor-platform-version/12139/31
- [ ] https://forums.meteor.com/t/build-a-whatsapp-clone-with-meteor-and-ionic-meteor-platform-version/12139/35
- [ ] https://forums.meteor.com/t/meteor-agular-ionic-ddp-problem/14441

**Comment by sabativi** [comment]
True, i think we need some infos on how to include angular-meteor-auth within an ionic app, what it the package, i can find the repo to use the url as dependencies for now [auth](https://github.com/ozsay/angular-meteor-auth) does not work
Thanks

**Comment by Urigo** [comment]
should work now with the new version of the Whatsapp tutorial
