### ISSUE TITLE
Auto-changelog generator

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#1210]
Create an auto-changelog generator like the Angular repo

**Comment by kamilkisiela** [comment]
My proposal is to use [`commitizen`](https://www.npmjs.com/package/commitizen) with `cz-conventional-changelog` (same as angular's convention) to make commit process a lot easier for contributors.

And [`conventional-changelog`](https://github.com/stevemao/conventional-changelog-cli) as the auto-changelog generator. Which is used by angular team.

I can work on it beside build process.

**Comment by Urigo** [comment]
Cool!  so does that means that the `commitizen` badge will test each PR?

**Comment by kamilkisiela** [comment]
My point of view on it:

> 1. User is trying to add his changes.
> 2. But he doesn't the commit message convention.

We can help him on the very first stage by providing `commitizen`.
He can use `npm run commit` command which opens sort of interactive commiting process with guidelines as you can see [here](https://github.com/commitizen/cz-cli/raw/master/meta/screenshots/add-commit.png). 

> 3. But let's say he doesn't even know that angular-meteor has some convention.

We can use here [`ghooks`](https://github.com/gtramontina/ghooks) with [`validate-commit-msg`](https://github.com/kentcdodds/validate-commit-msg). First one is to set git hooks (automatically) and second one is our hook with format checking. 
When user tries to commit changes with invalid message that git hook will throw error. So it will prevent adding wrong commits.

> 4. He's now able to properly commit changes. And he posted a PR.

> 5. Github shows `contributing guidelines` in posting PR's form only if `CONTRIBUTING.md` file exists.

We could put there few important notes.

> 6. Let's say it's a freakishly good PR with few unit tests and long description and it's sweet and eye-candy in general.

Travis says OK, bithound says it too. Let's merge it!

> 7. Now you want to release new angular-meteor version.

> 8. You're changing package's version.

> 9. And... here comes changelog!

You can use `npm run changelog` command (as a shortcut for `conventional-changelog -p angular -i CHANGELOG.md -s`) to append new changes. `changelog.md ` file will be updated.

> 10. Commit changes

> 11. As a bonus you can use [`conventional-github-releaser`](https://github.com/stevemao/conventional-github-releaser)

To release new verion on github.

---

Whole publishing process could be simplified to one command `npm run publish` which would detect if it's a patch, minor or major release (Semantic Versioning) but I don't recommend it.

`npm run bump:(patch|minor|major)` would be awesome, to bump new version
with:
`npm publish` for publishing

But it could be more automated. I would set travis to publish new version to npm when commit has version tag (again Semantic Versioning).

How it would work? 

Let's say you bumped new version with updated changelog and pushed it to repository. 
Now you can go to github's Releases section and publish new one. 
GH automatically adds tag with version number to commit you selected. 
It triggers travis and if everything still works then `npm publish` command is being executed.

---

Essay per day :heavy_check_mark:
