### ISSUE TITLE
How to repackage Angular2 packages on Atmosphere

### ISSUE THREAD

**Issue by Hongbo-Miao** [Urigo/angular-meteor#1211]
Hi, @Urigo and everyone, can you give us, especially the author of [ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap), [ng2-charts](https://github.com/valor-software/ng2-charts), [ng2-file-upload](https://github.com/valor-software/ng2-file-upload) @valorkin some directions for repackaging these Angular2 style packages on [Atmosphere](https://atmospherejs.com/) to let them be reused in the future angular2-meteor project?

@valorkin's packages are really high-quality style packages for angular2. All their packages can be found [here](https://github.com/valor-software).

https://github.com/valor-software/ng2-file-upload/issues/49

**Comment by Urigo** [comment]
@Hongbo-Miao please read this chapter of the tutorial and let me know if that worked for you - http://www.angular-meteor.com/tutorials/socially/angular1/3rd-party-libraries

**Comment by valorkin** [comment]
@Urigo thx for link, I will read it
but you suggestion about consuming 3rd party
what about automatic packaging 3rd party libraries?
if I want to publish my ng2 libraries in atmosphere

**Comment by valorkin** [comment]
my bad seems solution #1 is what we need

**Comment by Hongbo-Miao** [comment]
@Urigo Sorry, I failed after some tries... I think it needs put some d.ts files in typings automatically after downloading the package, but I don't know how to create those files. How about creating a tutorial Step `3rdParty Libraries` for angular 2 [here](http://www.angular-meteor.com/tutorials/socially/angular2/3rd-party-libraries) first using  [ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap) or [ng2-file-upload](https://github.com/valor-software/ng2-file-upload) as examples... :P

**Comment by MilosStanic** [comment]
Hi, I also tried to package angular2-materialize package for Meteor, but failed. Main problem so far is packing any .ts files for Meteor, as well as packing npm dependencies of the original package that don't already exist on Atmosphere.
I will keep trying. If I succeed, I'll suggest a chapter for Angular2-Meteor tutorial.

**Comment by MilosStanic** [comment]
@Hongbo-Miao I kinda succeeded to transpile TS and package it for meteor using the package.js like in https://github.com/barbatus/ng2-meteor-accounts/blob/master/package.js
Please try and let me know. 
It seems that I also need to package other npm dependencies that don't exist on atmosphere and use them in my package.js

**Comment by Hongbo-Miao** [comment]
@valorkin @MilosStanic  I got help from (zrbfly)[https://atmospherejs.com/zrbfly/ng2-bootstrap], who first succeed packaging ng2-bootstrap, I will let you know details of how to package it once I am clear those steps.

**Comment by Urigo** [comment]
with the new Meteor version you can just use npm and import styles from it

**Comment by Hongbo-Miao** [comment]
Oh, yeah, it is working well now using NPM.
