### ISSUE TITLE
Current user Resolve not always resolving. Displaying inconsistent behaviour

### ISSUE THREAD

**Issue by mattiLeBlanc** [Urigo/angular-meteor#1212]
Hi,
I might have a related issue that my controller's constructor is not consistent in resolving the currentUser.
Some reloads I get a current user, and some it is undefined. It must be a timing issue of the Users subscription but I am using several approaches like promise, Reactive variable and a resolve( that's currentUser dep) on the router. All display the same behaviour.

I am running UI-Router. 

See console output:
```
globalController currentuser undefined
profile.information.controller.ts:25 $auth -> undefined
profile.information.controller.ts:36 > currentUser undefined
profile.information.controller.ts:29 $auth wait undefined
```

My constructor:

```
 constructor( private $log: angular.ILogService, private $state: angular.ui.IStateService, private $scope: any, private currentUser: any, private toastr: Toastr, $reactive: any, private $auth: any  ) {

    $reactive(this).attach($scope);
    var user: any;
    console.log( '$auth ->', $auth.currentUser);

    $auth.waitForUser().then(() => {
        let currentUser = $auth.currentUser;
        console.log( '$auth wait', currentUser );
      });
    this.autorun( () => {

      user = this.getReactively( 'currentUser' );
    });
    // var user = currentUser;
    console.log('> currentUser', user );
    if ( user ) {
      this.information = user.profile;
      this.information.companyAbn = '123 456 734';
    }
  }
```
(I am trying multiple things in the code so that's why its messy.)

Just another reload of the page and check console output:
```
globalController currentuser Object {_id: "bATDodgxdCFn6tsBN", emails: Array[1], profile: Object}
profile.information.controller.ts:25 $auth -> undefined
profile.information.controller.ts:36 > currentUser Object {_id: "bATDodgxdCFn6tsBN", emails: Array[1], profile: Object}
profile.information.controller.ts:29 $auth wait undefined
```
Any idea's?
Do I need to apply a window.setTimout 0 to make it work (as a hack)?

**Comment by ozsay** [comment]
can you share your repository so we can reproduce this?

**Comment by mattiLeBlanc** [comment]
Uhm, well its a company project, in development, so I probably have to make an extraction see if it that displays the same behaviour. I hope to have time for this before I go on leave this week,

**Comment by Urigo** [comment]
`angular@1.3.6-beta.1` was released.
Please check if that works for you.

**Comment by Urigo** [comment]
Angular Meteor `1.3.6` was released.
Closing as we didn't get feedback for the past 5 days.
Please re-open if your problem wasn't solved and you can provide a reproduction.

**Comment by mattiLeBlanc** [comment]
Yep, it seems to have been resolved. Thank you!
