### ISSUE TITLE
Find a better solution for Socially upload photos chapter

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#1213]
CollectionFS is not maintained anymore so we should refactor the chapter

**Comment by MilosStanic** [comment]
Really? How do you know it is not being maintained anymore? I see last commit 12 days ago, but last release in March 2015. :/
The only fresh and relatively popular package I could find on Atmosphere is [vsivsi:file-collection](https://github.com/vsivsi/meteor-file-collection/).

**Comment by MilosStanic** [comment]
Here's a topic about deprecating CollectionFS on Meteor Forums: 
https://forums.meteor.com/t/deprecating-collectionfs/16921/2

**Comment by MilosStanic** [comment]
This alternative looks viable judging from docs. 

https://github.com/jalik/jalik-ufs

Didn't test it though.

**Comment by Urigo** [comment]
@MilosStanic thanks for the ideas!
updated in the new version of the tutorial: http://www.angular-meteor.com/tutorials/socially/angular1/handling-files-with-collectionfs
I guess we should update the new of the chapter :)
