### ISSUE TITLE
Add angular2now step to Socially

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#1214]

**Comment by trajano** [comment]
Not quite the same but https://github.com/Urigo/meteor-angular-socially/pull/110/commits/5dff66934de5608f0a87c55dbb7194d3c1d84bd3 uses the Angular 2.0 Upgrade Adapter

**Comment by Urigo** [comment]
@trajano that's amazing!
have you done it according to [this](https://github.com/Urigo/meteor-angular-socially/blob/master/EDIT_THIS_TUTORIAL.md)?
email me and let's chat about adding your contribution to the tutorial

**Comment by Urigo** [comment]
Done and even with video! - http://www.angular-meteor.com/tutorials/socially/angular1/migration-to-angular2
Thanks @kamilkisiela and @trajano
