### ISSUE TITLE
Showing warnings in browser console for auth and helper

### ISSUE THREAD

**Issue by mitiaptest** [Urigo/angular-meteor#1218]
Hello Guys,

Updated angular package giving warnings in browser console?

Deployed server Name: http://angularmeteordemo.meteor.com/
Code pushed on : https://github.com/mitiaptest/angular-meteor-demo-code.git

**Warnings are:
[angular-meteor.$rootScope.currentUser/loggingIn] Please note that this functionality has migrated to a separate package and will be deprecated in 1.4.0.  For more info: http://www.angular-meteor.com/api/1.3.2/auth
eb5541b8bc368d07b71271b0e83de6ceca7f91cd.js:108 defining 'parties' value helper, note that this feature will be deprecated in 1.4 in favor of using 'getReactively' - http://www.angular-meteor.com/api/1.3.1/get-reactively**

**Comment by ozsay** [comment]
Hi,

In 1.3.6 you will be able to suppress those warnings as explained here https://github.com/Urigo/angular-meteor/issues/1109

I'm closing since it's a duplicate

**Comment by Urigo** [comment]
`angular@1.3.6-beta.1` was released.
@mitiaptest Please check if that works for you.

**Comment by mitiaptest** [comment]
Ok @Urigo I will check and let you know.

**Comment by mitiaptest** [comment]
@Urigo Is there any setting for suppressWarnings ?

**Comment by mitiaptest** [comment]
@Urigo I have checked with 1.3.6-beta.1 and it is not showing any warning in my console.Is that means my code is correct (No need to change)????

**Comment by Urigo** [comment]
If your settings makes warnings on, then yes - http://www.angular-meteor.com/api/1.3.6/settings
