### ISSUE TITLE
subscription stopping sometimes on pages reload

### ISSUE THREAD

**Issue by mattiLeBlanc** [Urigo/angular-meteor#1220]
Hi,

I am having an issue where my subscription sometimes stops after a page reload during development in Meteor.
Sometimes it does load, sometimes it doesn't.
I use Typescript.

My subscription setup is standard as in docs:
```
private invoiceFilter = {

    'AmountDue': { $gt: 0 }
  };

constructor( private $log: angular.ILogService, private $state: angular.ui.IStateService, private authService: any, private $modal: any, private $scope: any, $reactive: any ) {

    $reactive( this ).attach( $scope );

    this.subscribe( 'invoices', () => [ this.invoiceFilter ],  {

      onReady: function () {
        console.log("onReady And the Items actually Arrive", arguments);
        // subscriptionHandle.stop();  // Stopping the subscription, will cause onStop to fire
      },
      onStop: function (error) {
        if (error) {
          console.log('An error happened - ', error);
        } else {
          console.log('The subscription stopped');
        }
      }
    });
    this.helpers( {
      invoices: () => Invoices.find( {}, { limit :10} )
    } );
  }
```

In my server console I see the subscription always loaded with a userId
```
=> Client modified -- refreshing
I20160210-12:51:11.059(11)? invoice subscription loaded { AmountDue: { '$gt': 0 }, userId: 'Lkqe4W5LR9TLQfegr' }
I20160210-12:51:15.001(11)? invoice subscription loaded { AmountDue: { '$gt': 0 }, userId: 'Lkqe4W5LR9TLQfegr' }
I20160210-12:51:54.171(11)? invoice subscription loaded { AmountDue: { '$gt': 0 }, userId: 'Lkqe4W5LR9TLQfegr' }
```

My subscription looks like
```
// IMPORTANT NOT TO USE FAT ARROW DUE TO LOSS OF THIS SCOPE. this.userId will become undefined
//
Meteor.publish( 'invoices', function ( filter: any ) {

  filter         = filter || {};
  filter.userId  = this.userId;

  console.log( 'invoice subscription loaded', filter );

  return Invoices.find( filter, {
    fields: {
      'Total':          1
    , 'DueDate':        1
    , 'Date':           1
    , 'InvoiceNumber':  1
    , 'LineItems.Description' : 1
    , 'Contact.Name':   1
    }
  } );
} );
```

I am not seeing any error. I my Chrome console I just see `The subscription stopped`. When I change state and go back to overview than most of the time the subscription doesn't stop.
When it did stop and I just refresh browser it stops immediately.

Using Angular Meteor 1.3.5.

Is this issue on my side or so timing issue with the subscription and the user Id?

**Comment by arvidkastel** [comment]
+1

**Comment by ozsay** [comment]
Hi,

It might be related to #1108. Can you test you project with the current 1.3.6 ? I explained how to do that here https://github.com/Urigo/angular-meteor/issues/1105#issuecomment-179228637

Thanks

**Comment by Urigo** [comment]
`angular@1.3.6-beta.1` was released.
@mattiLeBlanc Please check if that works for you.

**Comment by mattiLeBlanc** [comment]
I can check next week when I am back from my holiday.
Cheers

**Comment by Urigo** [comment]
I've released `1.3.6`.
It should be solved now as I saw that scenario and saw it was solved.
But if I mistaken please re-open that issue and tag me.

**Comment by mattiLeBlanc** [comment]
Looks like it is resolved. Thanks.

**Comment by minhtri9111199** [comment]
Hi guys, I had a same issue like that. Please help to solve it.
I use Angular-Meteor version 1.3.6, Meteor version 1.3 with Angular UI Router.
My issue is that: 
- When Ctrl + left mouse OR refresh the page, the page reloaded but sometimes it didn't subscribe data from server.
- Then I clicked on other URL (url had been config in router.js), it subsribe data again. All thing was normal.
-----------
So please let me know any solution to solve this. thanks.

**Comment by Urigo** [comment]
@minhtri9111199 it looks like you are not waiting for the data to arrive from the server to refresh the Angular view, if you still have an issue, please create a new one with a reproduction
