### ISSUE TITLE
getReactively executes on every collection change

### ISSUE THREAD

**Issue by gooor** [Urigo/angular-meteor#1221]
Hi,

I have one specific problem with getReactively. Having this code:
```
  this.someField = '12121';
  this.helpers({
    someCollection: () => {
      console.log('test');
      return SomeCollection.find({ someField: this.getReactively('someField') })
    }
  });
```
And it's ok - someCollection is filled, if anything added to it it updates, and `test` appears only once.

Bad things happen when `this.someField` changes or when I make:
```
  $timeout(() => { this.someField = '12121' }, 100);
  this.helpers({
    someCollection: () => {
      console.log('test');
      return SomeCollection.find({ someField: this.getReactively('someField') })
    }
  });
```
First of all `test` prints on every change to SomeCollection (even if query does not match!). What is even worse - adding another helper:
```
  $timeout(() => { this.someField = '12121' }, 100);
  this.helpers({
    someCollection: () => {
      console.log('test');
      return SomeCollection.find({ someField: this.getReactively('someField') })
    },
    otherCollection: () => {
      return OtherCollection.find();
    }
  });
```
will print `test` on every change to SomeCollection and to OtherCollection. This is causing big performance issues.

**Comment by ozsay** [comment]
I believe that this issue is related to #1108. We are going to release the new version tomorrow with a fix. Hopefully, it will help you.

**Comment by Urigo** [comment]
@ozsay I'm not sure if that's the case or that it is just a question about how Helpers work.

@gooor the helper will re-run on every change of the Collection and also on every change of reactive vars inside it, like any parameter using `getReactively`. that how helpers work and how reactivity work in Meteor.
If you don't want the helper to change when `this.someField` changes, you should use it directly without using `getReactively`.
But maybe I missunderstood your question so please elaborate.
Thanks

**Comment by sebakerckhof** [comment]
@Urigo I think there are 2 things here:
1. The find on someCollection is re-executed when an element of the someCollection changes. E.g. each time an object is added to the collection, the whole query is re-run (and since minimongo doesn't have indexes, this can be very expensive on larger collections). However, I think that's indeed just how Meteor works, but it could be done much, much more efficient.

2. I think in his last example someCollection shouldn't be re-run if nothing changes to it. @gooor sees the find on someCollection being re-run, if only things change to OtherCollection. That shouldn't happen I believe.

**Comment by Urigo** [comment]
@gooor , is what @sebakerckhof suggests true?  I would like to see a reproduction with the new `angular@1.3.6-beta.1` to examine it.
The helper re-runs, but inside we do smart nested diff that changes only the things that had really changed - https://github.com/Urigo/angular-meteor/blob/master/packages/angular-meteor-data/modules/reactive.js#L148-L167

**Comment by sebakerckhof** [comment]
I'm throwing together a repro, since I've also been seeing some similar stuff.

**Comment by Urigo** [comment]
awesome!

**Comment by sebakerckhof** [comment]
@Urigo Here's a quick and dirty repro that tests some stuff:
https://github.com/sebakerckhof/angular-meteor-data-repro

The bad news is: the problems described by @gooor are true
The good news is: the problems seem to be solved in `1.3.6-beta.1` (the version in the repo uses that, you can switch back to 1.3.5 to see what @gooor describes).

There is however one thing left that bothers me even with `1.3.6-beta.1`. 
As you can see I set the `selected` property on an element when I select it. Selecting the element will open it in the `details` view which subscribes to new data. While the only new data is a `description` field, the entire object gets replaced. You can see it by the quick red flash when selecting an element.
Of course it's up for discussion what the correct behavior should be.

**Comment by Urigo** [comment]
that's great @sebakerckhof ! I will have a look in a few hours

**Comment by ozsay** [comment]
@sebakerckhof 

Your current setup is deprecated. Our best practice setting `foo` as a reactive variable is with `autorun` (not with `helpers`. The right way to set `foo` as a reactive variable is:

```js
...
    controller:['$scope','$reactive',function($scope,$reactive){
          $reactive(this).attach($scope);

          this.$onInit = function() {
            this.subscribe('foo',()=>[this.getReactively('fooId')]);
          };

          this.autorun(() => {
              console.log('calling foo');
              this.foo  = Foos.findOne({ _id: this.getReactively('fooId') });
          });
...
```

This basically will do the same, and it will replace `foo` whenever the `autorun` will run.

You can do this differently in order to avoid the replacement:

```js
...
    controller:['$scope','$reactive',function($scope,$reactive){
          $reactive(this).attach($scope);
         
          this.foo = {};

          this.$onInit = function() {
            this.subscribe('foo',()=>[this.getReactively('fooId')]);
          };

          this.autorun(() => {
              console.log('calling foo');
              var tempFoo  = Foos.findOne({ _id: this.getReactively('fooId') });

              angular.extend(this.foo, tempFoo);
          });
...
```

**Comment by gooor** [comment]
@Urigo `1.3.6-beta.1` fixed the problem of re-executing the helper on every change in any collection :) 
There's one thing that bothers me. As @ozsay wrote, best practice is to use autorun not helper, and if I do replace 
```
  this.helpers({
    foos: () => {
      console.log('calling');
      return Foos.find({field: this.getReacively('field')});
    }
  });
```
(which now works fine on 1.3.6) with
```
    this.autorun(() => {
      console.log('calling');
      this.foos = Foos.find({field: this.getReacively('field')});
    });
```
It again executes on every change to Foos, while `this.field` remains unchanged o_O

**Comment by Urigo** [comment]
@gooor the best practice is to use `helpers` only for Meteor Cursors.
Your last example use a Meteor Cursor so you should use a helper

**Comment by gooor** [comment]
@Urigo thanks for explanation :) - but there's still a problem as `autorun` is called even if `this.field` is unchanged

**Comment by Urigo** [comment]
@gooor this is how Meteor's `autorun` works.  it executes on every change on any reactive thing inside it and a Meteor cursor is a reactive object.
If you want to re-run something only when `field` is changing you can use Angular's `$watch`:

```
$scope.$watch('field', function(){
  console.log('calling');
  this.foos = Foos.find({field: this.field});
});
```

**Comment by gooor** [comment]
@Urigo ok now I understand (I think) :)

**Comment by Urigo** [comment]
1.3.6 was released.
