### ISSUE TITLE
Blaze Templates

### ISSUE THREAD

**Issue by lorenzogm** [Urigo/angular-meteor#1227]
I'm trying to add Blaze Templates in my angular-meteor app and I get this error:

`meteorTemplate: There is no template with the name 'home'`

home.html
```
<blaze-template name="home"></blaze-template>
<blaze-template name="loginButtons"></blaze-template>
```

The "loginButtons" template works perfectly, but the "home" (which is defined as below) is not included in the available template.

templates/home.html
`<template name="home">test</template>`

Those are my packages:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.

check
email

# Angular
angular
angularui:angular-ui-router
angularutils:pagination
tmeasday:publish-counts

# Blaze Templates
urigo:angular-blaze-template

# Database
aldeed:collection2

# Auth
accounts-password
dotansimha:accounts-ui-angular

# Design
less
angular:angular-material
planettraining:material-design-icons
```

I am not sure which is the right config so I have tried replacing 'angular' package by 'angular-with-blaze' and 'blaze-html-templates'. However I got more errors because I need to change the extension to '.ng.html' and I stuffs related with 'strictDi' as well.

I have read a lot about the right config in the last few days. Could anyone sum up which is the right config to use angular-meteor with blaze templates? Regarding 'packages', 'file names for html and js' etc.

I think a new chapter in 'Socially' about this would be sooo good.

Regards!

**Comment by Urigo** [comment]
In order to use them both, you have to give one type of file extension to each type of file.
Meaning - `.ng.html` for Angular and `html` for Blaze.
Then you should use `angular-with-blaze` instead of `angular`.
That's it.  you have to do that because of how Meteor compilers works.
I would love if you could tell me how to improve the docs to make it more clear for developers.
Thank you

**Comment by lorenzogm** [comment]
Thank you @Urigo !
