### ISSUE TITLE
Unnecessary Meteor.isServer if condition in meteor methods tutorial ?

### ISSUE THREAD

**Issue by vinaynb** [Urigo/angular-meteor#1229]
Hello,
I found this while going through the docs. In [this](http://www.angular-meteor.com/tutorials/socially/angular1/meteor-methods) link for Meteor Methods tutorial we put the code sending a mail in an if block while checking for Meteor.isServer.

Now as this whole file is under /server directory why do we need that condition checking Meteor.isServer while sending a mail ? Won't this whole code run only at server itself ?

**Comment by Urigo** [comment]
@vinaynb because this file is not sitting in the server folder but in the `model` folder which means it's being loaded both on the client and the server

**Comment by vinaynb** [comment]
@Urigo oh okay. I missed that.
