### ISSUE TITLE
Angular-Meteor weirdly loading every master template

### ISSUE THREAD

**Issue by maximsko** [Urigo/angular-meteor#1231]
Please have a short look at the following ui-router definition:

```javascript
$stateProvider
  .state('master', {
    abstract: true,
    views: {
      'nav': {
        templateUrl: 'client/global/views/nav.ng.html',
        controller: 'AuthCtrl'
      },
      'main': {
        template: '<div ui-view="main" />'
      },
      'main-left': {
        template: '<div ui-view="main-left" />'
      },
      'sidebar': {
        template: '<div ui-view="sidebar" />'
      }
    },
    templateUrl: 'client/layouts/application.ng.html'
  })
  .state('centered', {
    abstract: true,
    views: {
      'nav': {
        templateUrl: 'client/global/views/nav.ng.html',
        controller: 'AuthCtrl'
      },
      'main': {
        template: '<div ui-view="main" />'
      },
    },
    templateUrl: 'client/layouts/application-centered.ng.html'
  })
  .state('master.interiors_index', {
    url: '/',
    views: {
      "main-left": {
        templateUrl: 'client/interiors/views/index.ng.html',
        controller: 'InteriorsIndexCtrl'
      }
    }
  })
  .state('centered.interiors_create', {
    url: '/interiors/new',
    views: {
      'main': {
        templateUrl: 'client/interiors/views/create.ng.html',
        controller: 'InteriorsCreateCtrl',
      }
    }
  })
```

Now, the weird thing is that if I enter master.interiors_index or centered.interiors_create I will have two (!!!) nav views in my compiled website, actually resulting in two navs. If I look at the html code I can see that for some weird reason the master templates (client/layouts/application.ng.html and client/layouts/application-centered.ng.html) are simply thrown together. There is the markup of both. Deleting one of these layout files fixes everything, but I kinda need two different layouts for my app.

**Comment by ozsay** [comment]
Can you test if it's happening with `angular-meteor` 1.3.6-beta.1 ?

If it does, can you share your repository for reproduction ?

Thanks

**Comment by Urigo** [comment]
@maximsko also, does it happen in a regular Angular app or only in an Angular Meteor app?

**Comment by maximsko** [comment]
Duh, please excuse me. I just dug deeper on this and came to the conclusion, that I had misunderstood the concept of layouts in angular. In a regular Angular app this wouldn't happen, because there is one initial index.html (or however you want to call it) and Meteor seems to just load everything by default which caused the navigation do be loaded twice, so that wasn't my routes configs fault.
Anyway, I achieved what I wanted after reading through https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views#view-names---relative-vs-absolute-names, sorry for the trouble!
