### ISSUE TITLE
use external js function 

### ISSUE THREAD

**Issue by skyboys22** [Urigo/angular-meteor#1233]
Hello,

i'm using angular2-meteor -v1.3.5 with Materialize, and my probleme is how to call external function javascript or Jquery from ts file?
i found declare function xxx(); but it's not resolve my probleme :/

my need is to initialise function, i tried to do that inside html file but no success.

any idea?

thank you

**Comment by harrysbaraini** [comment]
If I understand you, you have to import the file into where it will be used.

**Comment by Urigo** [comment]
@skyboys22 can you please provide an example app for that scenario? I'm sure I understand exactly what you are trying to accomplish

**Comment by skyboys22** [comment]
hello @Urigo i'm using Materialize with angular2-meteor, with css it's perfect but to initialise function js i found probleme to do it. with meteor we can use template.nameTemplate.event, but i dont find this in angular2-meteor :/

**Comment by skyboys22** [comment]
event that i need is when the template is rendred

**Comment by Urigo** [comment]
@skyboys22 please provide an example project

**Comment by skyboys22** [comment]
i have this in TS file
```
@Component({
    selector: 'companies-edit'
})
@View({
    templateUrl: 'client/dashboard/companies/edit/edit.html',
    directives: [RouterLink, NgModel]
})
//declare var collapsible:any;
export class Edit extends MeteorComponent{
    companyForm: ControlGroup;
    data: Array<Object>;
    id = 0;
    constructor(public router : Router,  private _routeParams:RouteParams, zone: NgZone)
    {
        super();
        document.getElementsByClassName("collapsible").collapsible({accordion : false});
...
```
collapsible is function in materialize.
and this in html
```
<ul class="collapsible" data-collapsible="accordion" >
        <li>
            <div class="collapsible-header" >First<span class="badge">1</span></div>
            <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
        </li>
</ul>
```
what i'm doing know:
`    <a class="btn" onclick="$('.collapsible').collapsible({accordion : false})">Activer</a>
`

**Comment by donedgardo** [comment]
+1
If I understood correctly is how to use jquery and an external js library(materialize) in your component.js file using import.

I have the same question.

**Comment by skyboys22** [comment]
not in js file @donedgardo, but in ts file
i got solution from there: https://github.com/skyboys22/DefinitelyTyped/tree/master/materialize-css
include file d.ts and call after from your ts file, functions to initialise

**Comment by Urigo** [comment]
@skyboys22 can we close this issue?

**Comment by skyboys22** [comment]
yes @Urigo i forget it ^^ sorry
