### ISSUE TITLE
meteor-publish-composite

### ISSUE THREAD

**Issue by TWKDreamState** [Urigo/angular-meteor#1235]
This is not intended as a bug report unless you feel it as a bug with angular-meteor and not meteor-publish-composite! I'm posting as guidance to anyone else facing this issue.

I use meteor-publish-composite throughout my app and had an issue with the reactive searching and ordering, based on a $stateParam that I supplied.

Essentially, using a normal meteor.publish worked fine. When I used the same code with meteor-publish-composite I had an issue which took a while to track down.

Code like this ...

```
this.subscribe('groups', () => {
        return [
            {
                limit: parseInt(this.perPage),
                skip: parseInt((this.getReactively('page') - 1) * this.perPage),
                sort: this.getReactively('sort')
            },
            this.getReactively('searchText')
        ]
    });
```

..worked perfectly with a normal Meteor.publish. searchText was sent in as 'searchText'.

With meteor-publish-composite, searchText was sent literally just as searchText (without the '' around it). Not sure why.

e.g. a result from what meteor-publish-composite recieves is below. Noticed, the ID and searchText are not surrounded by ''.

`iPyN22NBKCjEsosp7 { limit: 10, skip: 0, sort: { surname: 1 } } w`

The only way I have managed to get around this is the following...

```
this.subscribe('groupinformation', () => {
        return [
            {id: $stateParams.mygroupId},    <--------specifying the $stateParams as id
            {
                limit: parseInt(this.perPage),
                skip: parseInt((this.getReactively('page') - 1) * this.perPage),
                sort: this.getReactively('sort')
            },
            {search: this.getReactively('searchText')}    <--------specifying the this.getReactively('searchText') as search
        ]
    });
```

...and then updating my Meteor.publishComposite as required.

Hopefully might help someone with the same issue as me.

**Comment by Urigo** [comment]
thanks you very much for this @TWKDreamState
