### ISSUE TITLE
Controversial use of $reactive(this).attach($scope)

### ISSUE THREAD

**Issue by SimoneGatti** [Urigo/angular-meteor#1237]
In tutorial and in API reference you can find many example using famous command <b>$reactive(this).attach($scope)</b> without contextualized its use.

I would like to change subscribe according to a $scope var. Moreover I would like to see in view the collection subscribed.

My current code:
I'm using angular 1.3.5. I'm using a simple angular controller (<b>not controllerAs, not directive, not other stuff..</b>).
<pre>
.controller 'CarsCtrl', ($scope, $reactive) ->
  $reactive(this).attach($scope)

  $scope.searchText = ""
  $scope.carsPerPage = 10
  $scope.actualPage = 1;
  $scope.sort = {
    _id: 1
  }

  this.autorun () ->
    console.log 'changed>'+$scope.getReactively('searchText')

  this.subscribe('cars', ->
    console.log 'subscribe'
    [
      {
        limit: parseInt($scope.carsPerPage),
        skip: parseInt(($scope.getReactively('actualPage') - 1) * $scope.carsPerPage),
        sort: $scope.getReactively('sort')
      }
      $scope.getReactively('searchText')
    ]
  )

  this.helpers({
    cars: () ->
      Cars.find({}, { sort : $scope.getReactively('sort') })
  })
</pre>
<pre>
Meteor.publish('cars', (options, searchString) ->
  console.log ":"+options.limit+":"+options.skip+":"+options.sort._id+":"
  console.log ":"+searchString
  if (!searchString || searchString == null)
    searchString = ''

  selector = {
    "_id": { '$regex' : '.*' + searchString || '' + '.*', '$options' : 'i' }
  }

  Cars.find(selector, options)
)
</pre>

<ol>
<li>
This code (and only this) allow me to change the value of $scope variables from view and re-subscribe correctly.
View eg.: 
<pre>
&lt;input type="search" ng-model="searchText"&gt;
</pre>
</li>
<li>
I can't figure out how to view the helper collection in a simple ng-repeat.
<b>The following code doesn't work:</b> 
<pre>
&lt;div ng-repeat="car in cars track by $index"&gt;
  &lt;div&gt;
    {{car._id}}
  &lt;/div&gt;
&lt;/div&gt;
</pre>
</li>
</ol>

Do you have any idea?

**Comment by TWKDreamState** [comment]
Hi, I'm fairly new to all this (learning every day!) but I think you need to return the Cars.find(selector, options) in your Meteor.publish.

Try ...

`return Cars.find(selector, options)`

**Comment by TWKDreamState** [comment]
You also have a mixture of this and $scope. I'd suggest just sticking to 'this' as you use $reactive(this).attach($scope)?

**Comment by TWKDreamState** [comment]
`.controller 'CarsCtrl', ($scope, $reactive) ->
  $reactive(this).attach($scope)

  this.searchText = ""
  this.carsPerPage = 10
  this.actualPage = 1;
  this.sort = {
    _id: 1
  }

  this.autorun () ->
    console.log 'changed>'+this.getReactively('searchText')

  this.subscribe('cars', ->
    console.log 'subscribe'
    [
      {
        limit: parseInt(this.carsPerPage),
        skip: parseInt((this.getReactively('actualPage') - 1) * this.carsPerPage),
        sort: this.getReactively('sort')
      }
      this.getReactively('searchText')
    ]
  )

  this.helpers({
    cars: () ->
      Cars.find({}, { sort : this.getReactively('sort') })
  })`

**Comment by SimoneGatti** [comment]
Hi @TWKDreamState, my publish actually return Cars.find(selector, options): it's coffeescript.
Moreover the mixture of this and $scope is mandatory, because I need to change searchText, carsPerPage, actualPage and sort in the view.
I can yet resubscribe each time I change the value of that variables. The problem is how to view cars in a ng-repeat.

**Comment by TWKDreamState** [comment]
My bad - they say a little knowledge is dangerous! Hopefully someone else might be able to suggest what is happening.

**Comment by SimoneGatti** [comment]
@TWKDreamState Thank you anyway! Do you never display a collection or a variable using this?

**Comment by ozsay** [comment]
`$reactive(this).attach($scope)`

This command does 2 main things:
1. It makes the context that you send to `$reactive` function a reactive context. All of the helpers will be available on this context.
2. It attaches the reactive context to a scope. Because angular watchers are available only on scope (and not on controllers) we must attach to a scope in order to track changes (for `getReactively` etc.).

If you are not using the `controllerAs` syntax, you can set your scope as the reactive context and all of the helpers will be available on it:

`$reactive($scope).attach($scope)`

And then change all of the `this.helpers`, `this.autorun` to `$scope.helpers`, `$scope.autorun`

**Comment by SimoneGatti** [comment]
Thank you @ozsay! I try your solution but the browser console logs this error
<img width="1908" alt="schermata 2016-02-18 alle 10 57 52" src="https://cloud.githubusercontent.com/assets/16915705/13139816/a79557ca-d62e-11e5-832e-60babd8de8a3.png">

**Comment by ozsay** [comment]
can you try to upgrade `angular-meteor` to the latest version (1.3.6)?

**Comment by SimoneGatti** [comment]
Sure, but is it available on atmospherejs?

**Comment by ozsay** [comment]
yes

**Comment by SimoneGatti** [comment]
Cool! I will try it..

**Comment by SimoneGatti** [comment]
Ok, it works fine! (without use of $reactive(this).attach($scope))
@ozsay @Urigo: May I suggest to deprecate version 1.3.4 and 1.3.5?

**Comment by Urigo** [comment]
@SimoneGatti it's that what 1.3.6 is doing?
