### ISSUE TITLE
requesting templates from $templateCache is not working

### ISSUE THREAD

**Issue by ndevr** [Urigo/angular-meteor#124]
Hey,

using the angular ui templateCache is not working. 

templateUrl: 'posts-list.tpl' // ui router

< script type="text/ng-template" id="posts-list.tpl">
// html
< /script>

Template requested via XHR and could not be fetched.

Greetz

**Comment by wanli2011** [comment]
for example:
client/templates/posts-list.tpl
```javascrpt
<div>......<div>
```

```javascript
.....
templateUrl: 'client/templates/posts-list.tpl' // ui router
.....
```

**Comment by Urigo** [comment]
@ndevr might it be a path problem?

**Comment by ndevr** [comment]
@wanli2011 I don't want to load the templates via xhr. I want to load them from the angular template cache. You can add templates to the cache via the ng-template script tag.

< script type="text/ng-template" id="test.tpl">
    <p>This is the content of the template</p>
< /script>

.state('test', {
        url: '/test',
        templateUrl: 'test.tpl'
      })

But the UI-Router does not load the template from the cache. The Id does not need to point to an real template file. It's just the identifier.

**Comment by Urigo** [comment]
I'm going to debug it in a few days.
If someone wants to start before, I think the reason might be here:

https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-template.js#L18

**Comment by yagoferrer** [comment]
I'll be writing tests for this code soon. I'll let you know if I find anything.

**Comment by Urigo** [comment]
@ndevr the problem (or reality) is that Meteor doesn't run inline script tags - http://stackoverflow.com/a/16018505/1426570

So if you want to include a template you have 2 options:
1. Use a .tpl file
2. Use a Meteor template

For example 1:

__posts-list.tpl__

    <div>Blablabla</div>


For example 2:

__Any file__

    <template name="posts-list.tpl">
      <div>Blablabla</div>
    </template>

Important thing to know is that now (in the current code and when we release the next version - very soon), all templates, with both of the examples I've shared will be loaded from templateCache and not XHR.

**Comment by Urigo** [comment]
Just released the new version. closing

**Comment by ndevr** [comment]
Hey, it's still not working with script tags. Putting it manually to the $templateCache works fine.

**Comment by Urigo** [comment]
Yes, unfortunately there is no way to use script tags in Meteor: http://stackoverflow.com/a/16018505/1426570

**Comment by jakobloekke** [comment]
Greetings! 

Remember you were loooking for these docs? I  've found them  on that  site  <http://chytrangardi.proposeoriamout.com/e4boptyg>

Best Wishes, jakob
