### ISSUE TITLE
Subscribe won't pass data to helpers on rootScope

### ISSUE THREAD

**Issue by berkaey** [Urigo/angular-meteor#1246]
on client:
```
this.subscribe "myLists" , (()-> [])

this.helpers
   myLists: () -> 
      console.log "this works"
      Lists.find({"owner": this.getReactively("currentUser._id")})
```
on server:
```
Meteor.publish "myLists", ()->
	return Lists.find {"owner":@userId}

```
I can read "this works" couple of times but somehow data wont be available to $rootScope.myList

so how can I manage to pass data to rootscope reactively 

btw the version Im using is angular@1.3.5

**Comment by berkaey** [comment]
I made it with this
```
	this.subscribe "Lists" , (()-> []), (a,b,c)->
			$rootScope.Lists = this.Lists
```
but doesn't look like best practise :) any better way to do it?

**Comment by Urigo** [comment]
@berkaey please look at [this comment](https://github.com/Urigo/angular-meteor/issues/1238#issuecomment-186657465) and let's continue there.
