### ISSUE TITLE
subscribe without helpers?

### ISSUE THREAD

**Issue by berkaey** [Urigo/angular-meteor#1252]
Hey I'm trying this.

```
	$reactive(this).attach($scope)
	$scope.query = $state.params.query
	$scope.subscribe "searchResults" , (()-> [this.getReactively("query")]), (a,b,c)->
		console.log $scope.searchResults,"search"
```
publish log says found 1 item but nothing on $scope or in "this".

i know it will work if I add this
```
this.helpers
		searchResults: () -> 
           x.find {"deleted":null, $text: $search: query },
			fields: score: $meta: 'textScore'
			sort: score: $meta: 'textScore'
```
but it isnt DRY I have to write the same thing here and also in publish functions.

any idea to keep things DRY?

**Comment by berkaey** [comment]
turns out we cant use it like this
```
this.helpers
        searchResults: () -> 
           x.find {"deleted":null, $text: $search: query },
            fields: score: $meta: 'textScore'
            sort: score: $meta: 'textScore'
```
mini mongo doesnt support "$text" keyword yet

I use it like this but it also returns other items already subscribed. 
```
x.find({}, { sort: [["score", "desc"]] })
```
so this is like hell now :) there should be some way to get returning docs.

I can use angular to filter things out but it will be just wrong I guess.

**Comment by Tallyb** [comment]
if you have multiple subscriptions on the same collection concurrently - you should use a find function in your helpers. you cannot avoid it (and it is not DRY as the query may differ). 
I did not try $text on minimongo, but if that does not work, it is probably correct to have angular for the rescue.

**Comment by berkaey** [comment]
yeap after some test I noticed that if I only use one subscribe to one collection everything worked like expected with just
```
x.find({})
```
thanks for reply btw ;) @Tallyb 

and also I assume there is no way to correct set of objects if I use multiple subscribe beside then just use different "find" right?

**Comment by kamilkisiela** [comment]
@berkaey yes

**Comment by Urigo** [comment]
@berkaey yes that's how subscriptions and collections work in Meteor.
There are a few interesting articles about that subject that might make things clearer:
One is @Tallyb - https://medium.com/angular-meteor/coll-pub-sub-with-angular-meteor-cb13fe48f570#.v5m86xihp
Another one - http://www.meteorpedia.com/read/Understanding_Meteor_Publish_and_Subscribe
and another one - https://www.discovermeteor.com/blog/pagination-problems-meteor/
