### ISSUE TITLE
How to render page after subscription ready

### ISSUE THREAD

**Issue by jessonjoy** [Urigo/angular-meteor#1255]
Hello,

I have a collection with thousands of documents that I subscribe to from the meteor app. I have a dashboard page that shows this count. When the app starts, the count continues to increment itself and takes upto 15- 20 seconds for this counter to stop. How do I check to render the page only after all the data has loaded so that the count shows up once instead of incrementing?

Here's how I do my subscription:
```
               subHande = Meteor.subscribe('PublishCollection1', function () {
                      console.log('subHande 1');
                });

                if(subHande.ready()){
                    console.log('subHande.ready', subHande.ready());
                }

```

The subscription ready() is returning as false.

Here's how I bind to the UI:

`
reactiveContext.helpers({
        list1: function() {
            return Collection1.find({});
        }
`

Thanks for the help!

Jesson

**Comment by Deadly0** [comment]
@jessonjoy if you want display the count, no need to send all collection data to the client. You can count your docs on server and publish only the count. This package can help you https://atmospherejs.com/tmeasday/publish-counts

If you need to publish all data, look at 3rd argument of subscribe function http://www.angular-meteor.com/api/1.3.6/subscribe

**Comment by Urigo** [comment]
@jessonjoy looks like this is solved.
please reopen is it's not.
