### ISSUE TITLE
Meteor.status() is not a reactive data source.

### ISSUE THREAD

**Issue by notbogdan** [Urigo/angular-meteor#1259]
We're trying to do the following to show a connection status on our app: 

```
this.helpers({
	userBlock: () => {
        //...
		return {
			name: name,
			connectionStatus: Meteor.status().connected
		}
	}
});
```

However the helper doesn't re run after the server is disconnected. Outputting Meteor.status().connected variable directly into the template, both via $scope and controller reference doesn't see its value updating either.

**Comment by elHoudini9** [comment]
You are returning an object in your helper function, I believe that it is meant for collections.

From the angular-meteor documentation:

**helpers**

Use this method to define Meteor collections that will be reactive throughout the entire reactive context life.

The parameter of this method is an object whose keys will be added to the reactive context as arrays, representing the reactive collections. Each value of the object must be a function that returns a Mongo.Cursor.

**Comment by canac** [comment]
Doing something like this has worked for me to solve similar problems:

```js
this.autorun(() => {
  this.userBlock = {
    name: name,
    connectionStatus: Meteor.status().connected
  };
});
```

The function passed to `autorun` will be rerun every time `Meteor.status()` changes, which will in turn update the `userBlock` property.

**Comment by ThomsC** [comment]
for me this is working perfectly

```javascript
$reactive(this).attach($scope);
        
        let vm = this;

        vm.helpers({
            connected: () => {
                return Meteor.status().connected;
            }
        });
```

**Comment by Urigo** [comment]
thanks for the answers
