### ISSUE TITLE
Bower update to 1.3.7

### ISSUE THREAD

**Issue by leizard** [Urigo/angular-meteor#1260]
Hi, is angular-meteor updated to 1.3.7 on Bower ? I run `bower update angular-meteor` but it stays in the version 1.3.5. Is it because the dependencies to meteor-client-side package, which mine is 1.2.1 now.

**Comment by leizard** [comment]
I downgrade `meteor-client-side` package to 0.2.0 and successfully updated angular-meteor to 1.3.7. Now all the warnings about the helpers are gone :beers:

**Comment by Urigo** [comment]
@idanwe

**Comment by trajano** [comment]
There's a 1.3.9_1 perhaps it should be changed to that version.

**Comment by Urigo** [comment]
done.
