### ISSUE TITLE
Autorun is not trigger with getReactively when the value is updated in the view

### ISSUE THREAD

**Issue by ThomsCass** [Urigo/angular-meteor#1262]
Here is the documentation : http://www.angular-meteor.com/api/1.3.6/autorun

```javascript
myModule.controller('MyCtrl', ['$scope', '$reactive', function($scope, $reactive) {
  $reactive(this).attach($scope);

  this.myVar = 10;

  this.autorun(() => {
    console.log('Autorun!!', this.getReactively('myVar'));
  });

  this.myVar = 50; // This will cause the autorun function method to run again => YES IT WORKED
}]);

```

But if `myVar`is updated in the view for example with an input field the autorun is not trigger.

Is this a normal behavior ? Cause for now I used `ng-change()`

**Comment by ozsay** [comment]
I just verified with 1.3.7 that it's working.

Can you provide your code to see what the issue is?

**Comment by mattiLeBlanc** [comment]
Hi, I have something similar.

My controller (in TS):
```
class DashboardController {

  static $inject = [ '$log', '$state', 'authService', '$modal', '$scope' , '$reactive' ];

  private sortColumns: any = {
    'test':123
  }
  constructor( private $log: angular.ILogService, private $state: angular.ui.IStateService, private authService: any, private $modal: any, private $scope: any, $reactive: any ) {

    $reactive( this ).attach( $scope );
    this.autorun( () => {
      console.log( 'autorun Sort', this.getReactively( 'sortColumns.test' ) );
    });
  }

  updateSort( sortValue: any ): void {
    console.log( "updating sort", sortValue );
    // this.sortColumns.test = sortValue;
    this.sortColumns.test = 444;
  }
}
this.DashboardController = DashboardController;
```

Then I have a simple direct put on the sort column in the template
```

class ColumnSortDirective implements angular.IDirective {

  public restrict = 'A';
  // public scope         = {
  //   model:         '='
  // };
  public scope = false;

  constructor() {}

  public link = (
    scope:       angular.IScope,
    element:     angular.IAugmentedJQuery,
    attr:        any,
    ctrlArr:     any,
    transclude:  angular.ITranscludeFunction ) => {

      console.log( scope );
      console.log( attr );

      element.on( 'click', () => {
        console.log( 'click column');
        scope.$parent.vm.updateSort(  555 );
      });
    };
}

function columnSortFactory() : angular.IDirectiveFactory {
  var directive = () => new ColumnSortDirective();
  return directive;
}
this.columnSortFactory = columnSortFactory;
```

So what happens: I print the SortColumns.test value in my template (value 123).
Then when I click the sortcolumn, it should update to 555.
In my Chrome console, I can see that the scope value sortColum.test was modified to 555, but the autorun never runs again.
Right now in the directive I call a function of the parent to (make sure) have access to the correct scope. 
I have also tried using isolated scope and passing the object to the markup using & and = operators.
In my Chrome console, it works, but Autorun never runs again.

What is going wrong here?

**Comment by Urigo** [comment]
@ThomsC @mattiLeBlanc can you please create a repo with a reproduction?

**Comment by mattiLeBlanc** [comment]
I am on it. Will get back to you asap. Thanks.

**Comment by mattiLeBlanc** [comment]
@Urigo 
I have removed everything that is not relevant and the result you can get from here:
https://github.com/mattiLeBlanc/invoiceList

So, I am not seeing the publication stop issue right now. The reason could be that I removed the user and the ui-router resolve of currentUser.
I will add that in now into a different branch so that I can test if I can get this issue to be reproduced too.

I have added the issues in the readme file in the repo.
Hope you can have a look and find the same results.

**Comment by Urigo** [comment]
@mattiLeBlanc I will keep track on this issue here: https://github.com/Urigo/angular-meteor/issues/1264
