### ISSUE TITLE
1.3.6: Reactivity not working properly and more

### ISSUE THREAD

**Issue by mattiLeBlanc** [Urigo/angular-meteor#1264]
Hi,

I am using Angular Meteor quite extensively in the current building of a prototype for a financial company.

During development I ran into a couple of issues, which have been addressed quickly by Urigo ( many thanks for that).

But still I think some things of the new API are not working 100% and I am running into issue which cost me a lot of time to track down or work around.

Just for the sake of reporting, I am going to list them down here. Please feel free to respond or give constructive feedback on how to better do it, if it is not a bug.

edit: Actually it is one big story holding probably multiple issues but mainly it is related to reactivity.

** 1) Reactivity with an object: not autorunning after setting of new value**

I have a simple sort scenario where I have a list of invoices and I have a header with columns. Clicking on the columns need to trigger a sort. For this I created a directive that will capture the click on a specific column and update the scope value of `sortColumns` in the main dashboardController (which holds the invoice list subscription).
This scope value is the one that should be watched.
```
  updateSort( sortValue: any ): void {

    console.log( "updating sort", sortValue);
    this.sortColumns.__currentColumn  = sortValue;
    this.sortColumns[ sortValue ]     = 1;
    this.$scope.$digest();
  }

```

In BLAZE, I would create a ReactiveVar and that would be it. But unfortunately in Angular I need to watch this variable change somewhere.
Because I want to filter on my subscription, a template Helper would make sense to me.
I create a helper `invoices`, which will just return a Find() on the invoices subscription. 
In the helper I add 
```
trigger = this.getReactively( 'sortColumns'.__currentColumn );
sort =  angular.copy( this.sortColumns );
delete sort.__currentColumn;
return Invoices.find( {}, { sort: sort } );
```

The `updateSort` function is the one I call from the directive because directly accessing the `sortColumns` object and updating did not result in a reactive update in Autorun OR the helper.

However, just updating the object with new key/values did not work either, because watching `sortColumns` alone did not result in a reactive update.
Only looking specifically looking at `sortColumns.__currentColumn` and updating this property only to trigger the update seems to work.
So I have to remove the property in my `sort` object so that I can pass the sort object directly to the Mongo Find().

With the $digest call, I wouldn't get the update of my sortColumns. Why is this necessary?

Expected behaviour: 
_If I update the object, with whatever content and I am watching the object and not a specific property, I expect a reactive Update, right?_

**2) Updating controller variable directly from directive not triggering reactive update** 
So I used the `updateSort` function in the first reported issue, but at first I wanted to directly update that value from the directive. I gave the directive an isolated scope but I assume the value in the directive is always a copy of the value from the controller. So Autorun or ReactiveContext would never watch that copy. So I called a function that updates the value IN the controller. 
This does make sense, so maybe not a bug but I want to validate if this is the best way.

**3) Running in a $digest error**
When I try to set the initial sorting from my column directive I do it like this: By giving on column a attribute `direction="desc"` and while looping through my columns I look at the one that has a direction attribute and then call the `updateSort` function with the correct column in my dashboardController.

On first page run, I get a $digest is already running error. I intentionally call the $digest function in my `updateSort` to make sure during runtime, when a user clicks on the column, a reactive update takes place.
I guess this issue is related to the above mentioned reactive issues and I could remove $digest in the future.

**4) Subscription stopped issue**
I still run into the subscription stopped issue once in a while. Especially during my issues with the sorting directive, on application auto reload by Meteor I see an empty invoice list. Then reloading by clicking in the address bar and hitting enter a several times work. Or go to another view and go back always seem to work. Not sure what triggers this issue. 

**5) Helper reactive reRun returns empty collection for a instant and then normal collection**
I have a helper in my DashboardController that returns all invoices. As mentioned above, I have a reactive Sort object. When I do sort, the helper does a return of `Invoices.find( selector, { sort: sort } );`
This would renew the invoices in my template which it does.
However, there is an instant where the results flicker from an empty collection to a full collection. When I console.log the invoices with sort and filter
```
        console.log( "length", Invoices.find( selector, { sort: sort } ).fetch().length);
        return Invoices.find( selector, { sort: sort } );
```
it always shows 27, when I sort like a madman.
However when I print the same collection length in my template, the result goes from [] to 27 in an instant.This triggers a flickering effect of my 'There are no invoices in your account' to the list of invoices.
Is this something that can be prevented? Only return the helper collection to the template when it's done and not empty?
Of course it doesn't always do it. When I click on 3 columns to sort, it might happen at the third one...

Summary: It took me most of the day to figure out how to get this working and in the end it still feels like a hack. And some fixes trigger errors in other situations, like described in issue 3. 

I think it would be nice to make a bigger list of examples for all kind of scenario's with ReactiveContext, Helpers etc.. That way people can safe time and we are sure noone is hacking the system.

**Comment by sean-stanley** [comment]
I had similar issues in a fairly large project with angular-meteor. I eventually had to give up or take some quite hacky routes to get things to work and I'm still not sure why my eventual solution worked. I'd be keen to see or work on some meteor pen's that can accurately reproduce these bugs.

**Comment by plraphael** [comment]
I'm running into a similar problem as described in 4) Subscription stopped issue.

Basically, in the page immediately after login, my collection that should have one item after the subscription has none. If I refresh the page, everything goes back to normal.

**Comment by ThomsC** [comment]
I'm with 1.3.7 and got the same problem as described in 4

**Comment by mattiLeBlanc** [comment]
@plraphael No, your comment is not irrelevant. I reckon version 1.3.6 and version 1.3.7 shared much code and it is important to know if an issue is still relevant for an even newer version.

**Comment by Urigo** [comment]
thank you for those reports.
It will be great if you could reproduce a separate isolated repo with the problem.
It can help me solve it and help you isolate and understand it

**Comment by Urigo** [comment]
also, just to make sure, please check your code while doing deep watch in getReactively instead of regular by providing `true` to the `objectEquality` parameter - http://www.angular-meteor.com/api/1.3.6/get-reactively#arguments

**Comment by mattiLeBlanc** [comment]
Mate,

I am just testing with 1.3.7 on my girlfriends macbook (I didn't want to upgrade on my production macbook just yet).

I checked all items that I posted above and how they work at this version.

** 1) Reactivity with an object: not autorunning after setting of new value**
This still seems to be an issue, unless I am not using it correctly.

The code below has the `updateSort` function triggered by a directive and provides a value like `{ column: 'Total', direction: 'desc' }`.
This is set in the private variable `sortColumns` which is being watched (the whole variable).

```
 this.helpers( {

  invoices: () => {
    var sort;

    // this is purely to make sortColumns reactive
    //
    sort = this.getReactively( 'sortColumns' );
    return Invoices.find( {}}, { sort: sort } );
  }
} );

updateSort( sort: any ): void {

   this.sortColumns[ sort.column ]  = sort.direction === 'desc' ? -1 : 1;
  this.$scope.$digest(); // still necessary to make the reactive update work
 }
```
Updating the object with another key doesn't trigger the watch on the object itself. Maybe this is because that is not how the watch should work. However with Meteor Blaze ReactiveVar (if I am remembering correctly) it DOES work.

I only get the situation working if I add ` this.sortColyms = {}` to the updateSort function and reset the object on each column order. That works but feels like a hack if the reactivity should work on an object.

The $DIGEST is still necessary. Other wise the Helper will not reRun.

**Comment by Urigo** [comment]
@mattiLeBlanc it looks like you haven't read my comment.

1. Please check your code while doing deep watch in getReactively instead of regular by providing true to the objectEquality parameter - http://www.angular-meteor.com/api/1.3.6/get-reactively#arguments

2. Please provide a separate repo with a reproduction

* If you haven't found the time to share a reproduction it will be hard for me to find the time to solve the problem

**Comment by mattiLeBlanc** [comment]
@Urigo Yes, I did but I was just in the process of writing a report :). I have updated my findings in the above post and I have emailed you about access to the repo.

**Comment by Urigo** [comment]
@mattiLeBlanc I'm happy the `deep watch` parameter solved one of your issues.
@sean-stanley @plraphael @ThomsC did it solve yours as well?

About the second problem - private repo won't help me.   If you haven't found the time to go into your code and isolate the problem, it's not a good idea that I will go into your private code, try to isolate your business logic with the problem and share a reproduction.

Please go into your code and isolate the problem.

I hope you understand my logic and it makes sense.  I want to help you solve the problem.

About the digest thing, something I would start with if I had a reproduction is if it's an Angular or Angular-Meteor problem.
I would put a regular Angular `$watch` on `sortColumns` and see if it fires

**Comment by mattiLeBlanc** [comment]
@Urigo 
What if the problem is that it doesn't happen in an isolated situation? Maybe something breaks, timing issues etc because it starts to grow? I am happy to try to isolate it, just thought it would be easier if I give you access to the full app and tell you where to look.
I will try your watch, however if the updateRow function is executed (which it is, I consoled logged it and it does update the this.sortColumn object, the Helper doesn't fire unless I call a $digest, wouldn't it the issue be the combination of Angular and Meteor?

**Comment by Urigo** [comment]
not for sure because $digest just call the Angular's digest loop so the question is why Angular doesn't fire it by itself when you change a scope variable

**Comment by sean-stanley** [comment]
@Urigo, rather than using a deep watch I watched the individual parameters e.g. `getReactively('object.property')` and that implementation works well and I like.

My problem couldn't be well isolated as it only happened when I was logging in, then changing routes in Meteor.call's callback. The auth service would then from `ng-if` call the link function of a custom directive that had a subscribe call. If I remove the subscribe call in the directive everything worked fine and my subscriptions in the new route weren't stopped. I fixed that particular issue by wrapping my route change in a 10ms `$timeout`. hacky but no noticable UI problems at least.

That said if you really want I can try to reproduce it in an as isolated event as possible.

I am using angular 1.5 component syntax for parts of my app if that matters at all.

**Comment by Urigo** [comment]
@sean-stanley I might know your problem, have you tried `this.call`? http://www.angular-meteor.com/api/1.3.6/call
this will wrap the callback in a digestion cycle.

Then also, if it's something else from Meteor that is outside of Angular's scope, you can use $bindToContext - http://www.angular-meteor.com/api/1.3.6/reactive-context#dbindtocontext
(scroll down for an example)

**Comment by Urigo** [comment]
also, make sure you are using the `angular-meteor-auth` package as a separate package and in the latest version `0.2.1`

**Comment by sean-stanley** [comment]
@urigo thanks for the tip about `this.call` it seems like that would be part of the issue you're right. I guess I missed that part of the docs I'll make that change now.

I do use $auth as a seperate package. That was a good decision breaking it up I think and I've had no problems switching from the old to new api for that except sometimes it's unclear in a controller when to use `$auth.currentUser` or just plain ole `Meteor.user()` but that's probably a discussion for another place and another time.

**Comment by mattiLeBlanc** [comment]
@Urigo 
I have removed everything that is not relevant and the result you can get from here:
https://github.com/mattiLeBlanc/invoiceList

So, I am not seeing the publication stop issue right now. The reason could be that I removed the user and the ui-router resolve of currentUser.
I will add that in now into a different branch so that I can test if I can get this issue to be reproduced too.

I have added the issues in the readme file in the repo.
Hope you can have a look and find the same results.

**Comment by ThomsC** [comment]
For me the publication stop issue seems to be resolve when I use :

```javascript
resolve: {
                    currentUser: ($q) => {
                        if (Meteor.userId() == null)
                            return $q.reject('AUTH_REQUIRED');
                        if (Roles.userIsInRole(Meteor.userId(), ['user', 'sub-user']))
                            return $q.resolve();
                        else {
                            return $q.reject('AUTH_REQUIRED');
                        }
                    }
                }
```

Instead of 

```javascript
$auth.requireUser()
```

**Comment by plraphael** [comment]
Let me explain what is happening in my case.

After a successful login, the user is redirected to a page with a subscription. A normal subscription, that does not have any parameters (hence, does not use getReactively). What I'm getting on my logs is that the subscription gets "ready" and after some time, gets "stopped". If I refresh the page, the subscription does not get stopped, and everything is fine.

I tried what @ThomsCass suggested, but got the same result.

**Comment by ThomsCass** [comment]
can we see your resolve function and the part of the controller where you do the subscription with the helpers?

**Comment by arvidkastel** [comment]
Just a hint on issue 4 with subscriptions stopping. I noticed that this happened to me when Meteor.user() return undefined for some short time before (I assume) the Meteor.users collection is populated. By installing the fastrender package the logged in users is always available which seemed to solve the problem. Not sure why, but it also made the routing with the ui router stop functioning.

**Comment by kamilkisiela** [comment]
@mattiLeBlanc Can we catch up on hangouts or something? I'm currently working on these issues.

**Comment by mattiLeBlanc** [comment]
@kamilkisiela I have send you an email (the the email address in your git account).
I have also added a 6th helper reactivity issue about a helper not updating after mongo document change.

**Comment by Urigo** [comment]
@mattiLeBlanc could you please update about the current situation of the issues you specified?
thanks

**Comment by mattiLeBlanc** [comment]
These issue have all been resolved.

**Comment by der-ede** [comment]
Hi there,

are there still people using angular-meteor?
I started a project and ran into the same issues as you guys.
Thank you @mattiLeBlanc for posting the github repo invoiceList, but in the readme also questions arose.
Anyone on this right now?
(I am utilizing angular-meteor 1.3.11)

**Comment by mattiLeBlanc** [comment]
Hi,

This thread was created 6 months ago or so and i must say that most issue
where resolved. Some were related to architecture and some were bugs.

Which issues are you running into right now?

**Comment by der-ede** [comment]
Hi @Matti LeBlanc,

thank you for responding.
The issue of the reactivity not functioning properly almost subsided in the meantime when I played around with the resolve a bit.
But sometimes it still just does not get the changes in $scope.helpers({}), although no „deep“ reactivity.

But also in general I was wondering whether the whole angular-meteor project is obsolete and gone.

Explanation:

Over the past 1 1/2 years or so I accompanied some projects with meteor and the question of the ui-framework was just costly since it changed a lot, from fame.us to meteoric-ionic to angular-meteor and now everyone seems to be wanting react.

So angular-meteor is still maintained and will be in the future?


Regards
Thorsten


> Am 20.01.2017 um 14:25 schrieb Matti LeBlanc <notifications@github.com>:
> 
> Hi,
> 
> This thread was created 6 months ago or so and i must say that most issue
> where resolved. Some were related to architecture and some were bugs.
> 
> Which issues are you running into right now?
>

**Comment by mattiLeBlanc** [comment]
Well looping at the code base it is still actively being maintained.
There must be a lot of people considering angular 2 , react or Vue over
angular 1.5 so I guess eventually it will become stale.
Not saying you can't keep using it as long as you freeze your code base at
work.

For now I think it is still fine and allows for rapid development
especially with angulars 1.5 components.

**Comment by der-ede** [comment]
Ok thank you, in js 2 years has become one whole generation...



> Am 21.01.2017 um 00:41 schrieb Matti LeBlanc <notifications@github.com>:
> 
> Well looping at the code base it is still actively being maintained.
> There must be a lot of people considering angular 2 , react or Vue over
> angular 1.5 so I guess eventually it will become stale.
> Not saying you can't keep using it as long as you freeze your code base at
> work.
> 
> For now I think it is still fine and allows for rapid development
> especially with angulars 1.5 components.
>

**Comment by der-ede** [comment]
So, just to make sure:

In the helpers, I have to use find() instead of findOne(), since only find() will be treated reactively, right?

And in terms of getreactively: any variable can be made reactive, also variables from services for example?

Regards


> Am 21.01.2017 um 00:41 schrieb Matti LeBlanc <notifications@github.com>:
> 
> Well looping at the code base it is still actively being maintained.
> There must be a lot of people considering angular 2 , react or Vue over
> angular 1.5 so I guess eventually it will become stale.
> Not saying you can't keep using it as long as you freeze your code base at
> work.
> 
> For now I think it is still fine and allows for rapid development
> especially with angulars 1.5 components.
>

**Comment by der-ede** [comment]
Ok, got it, getReactively just takes the place of the Session variables in Blaze.

thx
> Am 26.01.2017 um 14:25 schrieb Thorsten Seckert <seckert.t@googlemail.com>:
> 
> So, just to make sure:
> 
> In the helpers, I have to use find() instead of findOne(), since only find() will be treated reactively, right?
> 
> And in terms of getreactively: any variable can be made reactive, also variables from services for example?
> 
> Regards
> 
> 
>> Am 21.01.2017 um 00:41 schrieb Matti LeBlanc <notifications@github.com <mailto:notifications@github.com>>:
>> 
>> Well looping at the code base it is still actively being maintained.
>> There must be a lot of people considering angular 2 , react or Vue over
>> angular 1.5 so I guess eventually it will become stale.
>> Not saying you can't keep using it as long as you freeze your code base at
>> work.
>> 
>> For now I think it is still fine and allows for rapid development
>> especially with angulars 1.5 components.
>>

**Comment by mattiLeBlanc** [comment]
I think FindOne() and Find().fetch() both give the same reactivity. FindOne just returns one and Find() returns a cursor.

**Comment by der-ede** [comment]
ok, then it was about the getReactively() why it didn’t work. thx.
