### ISSUE TITLE
Cannot read property 'splice' of undefined

### ISSUE THREAD

**Issue by ThomsCass** [Urigo/angular-meteor#1265]
Hey guys!

I'm `using angular-meteor 1.3.7`

I don't know what is happening but I've been struggling with this error for two days. 

It happens when I add a document to a collection and listen to it with a helper and a subscription. This error occurs only with one Collection in my project. The workflow is absolutely the same as my other collections and the tutorial angular meteor so I didn't manage to isolate the problem.

```javascript
Error: Cannot read property 'splice' of undefined
TypeError: Cannot read property 'splice' of undefined
    at Object.addedAt (angular-meteor.js:2148)
    at observeChangesCallbacks.addedBefore (observe.js:96)
    at Object.self.applyChange.addedBefore (observe.js:33)
    at minimongo.js:371
    at _.extend.runTask (fiber_stubs_client.js:42)
    at _.extend.flush (fiber_stubs_client.js:70)
    at _.extend.drain (fiber_stubs_client.js:78)
    at LocalCollection.insert (minimongo.js:579)
```

Have someone an idea on what could be the problem ? Is an angular-meteor bug ?

Cheers

**Comment by jonmc12** [comment]
@ThomsC I've run across this error a few times.  I can't say I understand it, but as you suggest, it seems to happen when there is a collection in a helper.  I'll try to explain how I repro'd the error, and the work-around I found is at the end.

I first noticed this when I created a parent / child relationship between the directives (notice the error occurs on `$reactive(this).attach($scope)` in Child 1):

```javascript
angular.module('app.test').config(['$urlRouterProvider', '$stateProvider',
  function($urlRouterProvider, $stateProvider) {

    $urlRouterProvider.otherwise("/project/start");

    $stateProvider
      .state('project', {
        url : '/project',
        template: '<project></project>'
      })
      .state('project.start', {
        url: '/start',
        template: '<project-start></project-start>'
      })   
      .state('project.settings', {
        url: '/settings',
        template: '<project-settings></project-settings>'
      })
    }
]);

// Parent
angular.module('app.test').directive('project', function () {
  return {
    restrict: 'E',
    templateUrl: '/packages/test:project/client/views/project.ng.html',
    controllerAs: 'project',
    controller: function ($scope, $state, $reactive) {
      $reactive(this).attach($scope);

      // Hide / show child directive templates dynamically
      this.$state = $state;

      // Share active project to child components
      Session.setDefault('activeProjectId', "");

      this.subscribe('members', () => {
        return [ Session.get('activeProjectId') ];
      });
      
      this.helpers({
        members: () => {
          return Members.find();
        }
      });

    }
  }
});

// Child 1
angular.module('app.test').directive('projectStart', function () {
  return {
    restrict: 'E',
    templateUrl: '/packages/test:project/client/views/project.start.ng.html',
    controllerAs: 'projectStart',
    controller: function ($scope, $reactive, $state) {
      // This will cause ERROR:
      $reactive(this).attach($scope);

    }
  }
});

// Child 2
angular.module('app.test').directive('projectSettings', function () {
  return {
    restrict: 'E',
    templateUrl: '/packages/test:project/client/views/project.settings.ng.html',
    controllerAs: 'projectSettings',
    controller: function ($scope, $reactive) {
      $reactive(this).attach($scope);

    }
  }
});
```

So, I moved the helper out of the parent and into Child 1, now the error will occur when `$reactive(this).attach($scope)` is called on Child 2:

```javascript
// Parent
angular.module('app.test').directive('project', function () {
  return {
    restrict: 'E',
    templateUrl: '/packages/test:project/client/views/project.ng.html',
    controllerAs: 'project',
    controller: function ($scope, $state, $reactive) {
      $reactive(this).attach($scope);

      // Hide / show child directive templates dynamically
      this.$state = $state;

      // Share active project to child components
      Session.setDefault('activeProjectId', "");

      this.subscribe('members', () => {
        return [ Session.get('activeProjectId') ];
      });

    }
  }
});

// Child 1
angular.module('app.test').directive('projectStart', function () {
  return {
    restrict: 'E',
    templateUrl: '/packages/test:project/client/views/project.start.ng.html',
    controllerAs: 'projectStart',
    controller: function ($scope, $reactive, $state) {
      $reactive(this).attach($scope);
      
      this.helpers({
        members: () => {
          return Members.find();
        }
      });

    }
  }
});

// Child 2
angular.module('app.test').directive('projectSettings', function () {
  return {
    restrict: 'E',
    templateUrl: '/packages/test:project/client/views/project.settings.ng.html',
    controllerAs: 'projectSettings',
    controller: function ($scope, $reactive) {
      // Now, this will cause ERROR:
      $reactive(this).attach($scope);

    }
  }
});
```

Why?  I'm not sure root cause, but it seems like `$reactive(this).attach($scope)` is attaching the controller to `$scope` as each directive is instantiated.  This means that younger siblings will inherit `$scope` attached with each of the older siblings attached (I'd assume this is not intended, probably a bug).  You might be able to demonstrate this in your own code by placing `console.log("$scope <name>:", Object.keys($scope))` below each instance of `$reactive(this).attach($scope)` and seeing that the scope attachments are perhaps different in each of your controllers.

The error you describe above occurs if the older sibling happens to have a helper with a collection defined.

In my case, I was able to work-around this by changing the order of instantiation.  ie, this throws error:

```html
<!-- /packages/test:project/client/views/project.ng.html -->
<project-start ng-show="welcome.$state.current.name === 'project.start'"></project-start>

<project-settings ng-show="welcome.$state.current.name === 'project.settings'"></project-settings>
```

however, this does not throw error:
```html
<!-- /packages/test:project/client/views/project.ng.html -->
<project-settings ng-show="welcome.$state.current.name === 'project.settings'"></project-settings>

<project-start ng-show="welcome.$state.current.name === 'project.start'"></project-start>
```

However, I think this will only work if you only have one sibling that uses a collection in a helper.

Also referencing #1263 which suggest some examples and documentations that consider reactivity with Angular inheritance patterns.

**Comment by ThomsC** [comment]
@jonmc12 Thank you Thank you Thank you.

the line causing the error is absolutely `$reactive(this).attach($scope);`

Here is how the error occur for me :

To add an document in a collection I use an $mdDialog.
In this $mdDialog I need to make a subscription for some items.

So in the controller of the Dialog I had :
```javascript
$reactive(this).attach($scope);
vm.helpers({
             ...
             });
```

To get rid of the error I now do the subscription in the parent get my items there and pass it to the Dialog.

So the two lines you see above are now in my parent.

**Comment by ThomsC** [comment]
Ok so after testing everything this is a bug in 1.3.7 because this problem didn't appear in 1.3.4 ...

**Comment by cubitworx** [comment]
@ThomsCass What is the reason you closed this? I'm having the same problem when using reactive collections, however mine only seems to occur when I navigate away from a layout using:
```
$reactive(this).attach($scope);
this.helpers({
   collection: () => thisCollection.find() // where thisCollection is a Mongo.collection
});
```
What I find interesting is that it only started happening when I updated from `1.3-cordova-beta.5` to `Meteor 1.3-beta.11`. I am not 100% sure it was only the upgrade that caused the error to appear - I would have to revert to the cordova beta to confirm but I don't remember changing anything before or during the update so don't think it is anything other than the update.

Thanks

**Comment by ThomsCass** [comment]
Hi,

I open an other ticket here #1269 and a solution was found.
