### ISSUE TITLE
Meteor Up Angular Initialization Errors and unresponsive reactivity

### ISSUE THREAD

**Issue by sean-stanley** [Urigo/angular-meteor#1266]
I just wanted to make people aware that if you attempt to deploy a Meteor app with angular-meteor using Meteor Up, you will likely have problems.

Even when running the latest version of mup and a new enough version of npm to have the latest versions of mup's dependencies, my deployed project (which I'd like to say is production ready but sadly isn't) continues to have glitches compared to an app deployed with meteor deploy.

Until I updated Meteor Up to the latest version I had angular js failing to find controllers and even though the newest version of mup didn't have that problem, some of my reactivity wasn't working. Not all of it, just frustratingly some of it.

The site behaves exactly as I'd like when deployed with meteor deploy and if you'd like a quick example of this go to [foodcoop.meteor.com](http://foodcoop.meteor.com), create an account and add an item to your cart, you'll see in the toolbar that the count and total in your cart reactively changes as it watches the Cart.Items collection with a helper.

However if you go to a url I've hosted it with Meteor Up like [here](https://kaicoop.nz), the cart total fails to update though works fine when actually editing from the cart page.

I am using the latest 1.3.7 version of angular-meteor and all dependencies are at their highest available versions. I'll add a complete .versions file for the project though the code is on github [here](https://github.com/redhead-web/meteor-foodcoop)

If anyone has any suggestions for making Meteor Up work better with angular js I am happy to hear it and I will keep the group updated on my experiments for deploying angular-meteor apps.

I have not tried mupx yet. That will be my next step.

**Comment by ThomsC** [comment]
I have an angular-meteor app in production, deploy with mup which is working perfectly.

The trick is you have to downgrade to 1.3.4 ...

**Comment by mattiLeBlanc** [comment]
I have no issues using 1.3.6. I have deployed multiple times (mupx) and my app is working the same online as it does locally.
Are you sure you don't have issues related to DI? Annotation working fine?

**Comment by sean-stanley** [comment]
Well locally I use strict-di="" to test for that and get no issues locally.

If 1.3.7 is the problem it might be more related to the new angular-templates package not compiling right with mup.

It's too bad if that is the case I suspect using angular-templates cache  would result in big performance boosts for the app.

I am going to try just running a local `meteor build` and see if that works.

**Comment by mattiLeBlanc** [comment]
I just deployed me project on my girlfriend's macbook with 1.3.7 (using mupx) and it is working fine on my server. No dependency issues at all.
I am using Typescript, which shouldn't make a difference.

You know you can run Meteor locally in production mode, so it will do the minimize etc and you could possibly trigger the same issue.

**Comment by sean-stanley** [comment]
Today I deployed again with mup and the issue is resolved and I did not have to downgrade.I first ran mup setup again after trying mupx. I decided not to use mupx because I prefer mup's current implementation of mongodb.

So for now I am going to close this issue. Thank you for sharing your responses.
