### ISSUE TITLE
ES6 Arrow function in directive's controller definition

### ISSUE THREAD

**Issue by majorgilles** [Urigo/angular-meteor#1268]
Hello, I was following your tutorial online, but was using es6 syntax for lambdas.

I was noticing one of my functions in a directive was not being called reactively.

```
angular.module('socially')
    .directive('partiesList', () => {

        return {
            restrict: 'E',
            templateUrl: 'client/parties-list.html',
            controllerAs: 'partiesList',
            controller: ($scope, $reactive) => {
                $reactive(this).attach($scope);
                this.helpers({
                    parties:() => {
                        return Parties.find({});
                    }
                });
            }
        };
    });
```

replacing ($scope, $reactive) => { ... } by   function($scope, $reactive) { .... }   did the trick but I have absolutely no idea why.

**Comment by Urigo** [comment]
@majorgilles the thing about ES6 arrow functions is that they keep the context of `this` outside of the function.
Angular's controller needs this to be the current new context so arrow functions are not a good replacement for defining the controller of the directive..
