### ISSUE TITLE
Problem of inheritance with 1.3.7

### ISSUE THREAD

**Issue by ThomsCass** [Urigo/angular-meteor#1269]
Hi,

Related to this post #1265 and this one #1263

I think there is something broken when we use `$reactive(this).attach($scope)` in a child view like a mdDialog.

This error will be thrown :

```javascript
Error: Cannot read property 'splice' of undefined
TypeError: Cannot read property 'splice' of undefined
    at Object.addedAt (angular-meteor.js:2148)
    at observeChangesCallbacks.addedBefore (observe.js:96)
    at Object.self.applyChange.addedBefore (observe.js:33)
    at minimongo.js:371
    at _.extend.runTask (fiber_stubs_client.js:42)
    at _.extend.flush (fiber_stubs_client.js:70)
    at _.extend.drain (fiber_stubs_client.js:78)
    at LocalCollection.insert (minimongo.js:579)
```

@Urigo Here is the repo that reproduce the error, simply add a item and you will see the error appear in the console https://github.com/ThomsCass/angular-meteor-inheritance.git

Hope it helps

Thanks

**Comment by ThomsCass** [comment]
Any news with this bug ?

**Comment by kamilkisiela** [comment]
You're attaching accueilController's `$scope` to the reactive context of dialogController 

[Lines 37-39 of accueilController.js](https://github.com/ThomsCass/angular-meteor-inheritance/blob/master/client/accueil/accueilController.js#L37-L39)

```javascript
function DialogController($mdDialog) {

    $reactive(this).attach($scope); // <-- $scope of accueilController
```

change to:

```javascript
function DialogController($mdDialog, $scope) {

    $reactive(this).attach($scope); // <-- now it is a $scope of DialogController
```

**Comment by kamilkisiela** [comment]
@ThomsCass It fixes the reproduction so tell me if app is working too.

**Comment by ThomsCass** [comment]
@kamilkisiela Yep it's working now thanks a lot. 

I didn't need to do that before how comes we need to do that now ? 
(even if I understand the logic of the solution)

**Comment by kamilkisiela** [comment]
API is still the same but there is a new background for reactivity, called viewModel. You can check it at src/modules/view-model.js.

I can tell you more, but atm I'm little busy

**Comment by ThomsCass** [comment]
Would love to hear more when you have time :)
