### ISSUE TITLE
 $compileProvider.debugInfoEnabled(false) not working for Andriod and iOS

### ISSUE THREAD

**Issue by mitiaptest** [Urigo/angular-meteor#1271]
Hello Guys,

To improve App performance we have tried to add $compileProvider.debugInfoEnabled(false) into config but it causing issue that for app first time install its not working but if i killed my app and start again then works.

Anyone having idea why its not working with meteor application.

Thanks,

**Comment by mitiaptest** [comment]
Any update?

**Comment by Urigo** [comment]
@mitiaptest does it happens also when you are using a simulator?

**Comment by kamilkisiela** [comment]
Couldn't reproduce this issue. It's working on my Nexus 5.

I tried:
```javascript
angular.module('app', [
  'angular-meteor'
]).config(['$compileProvider', ($compileProvider) => {
  $compileProvider.debugInfoEnabled(false);
}]).run([() => {
  console.log('ready');
}]);
```

**Comment by kamilkisiela** [comment]
Sharing repo:
https://github.com/kamilkisiela/angular-meteor-1271

**Comment by mitiaptest** [comment]
@Urigo I haven’t checked this thing of simulator.I am facing this issue on mobile device.

**Comment by mitiaptest** [comment]
@kamilkisiela will push sample code on shared repo.

**Comment by kamilkisiela** [comment]
@mitiaptest Great! You can add me as a collaborator :muscle:

**Comment by Urigo** [comment]
@mitiaptest any news?

**Comment by mitiaptest** [comment]
@Urigo We have resolved this issue by injecting module.

Thanks,
Mit

**Comment by mitiaptest** [comment]
Thanks @kamilkisiela
