### ISSUE TITLE
$scope.getReactively returns undefined inside autorun in 1.3.7

### ISSUE THREAD

**Issue by seanjb** [Urigo/angular-meteor#1272]
Hi, just upgraded to 1.3.7 and am running into an issue with getReactively. It appears to only be returning undefined when used with $scope.
It still triggers the autorun correctly but has no return value.

This does not appear to happen with this.getReactively just $scope.getReactively

Sample code for problem below

```
controller: function ($scope, $element, $reactive, sioObjectHelpers, sioNavHelpers) {
            $reactive(this).attach($scope);

            $scope.testVar = 'sample';
            this.autorun(() => {
                console.log('Reactive:' + $scope.getReactively('testVar'));
                console.log('Actual:' + $scope.testVar);
            });
            $scope.testVar = 'Reactive test';
```

This code generated the following console output

Reactive:undefined
Actual:sample

Reactive:undefined
Actual:Reactive test

**Comment by kamilkisiela** [comment]
You should use just  `$scope` or `this` enhanced by `$reactive(this).attach($scope)`, not both.

```javascript
$reactive(this).attach($scope);
this.testVar = 'sample';
this.autorun(() => {
    console.log('Reactive:', this.getReactively('testVar'));
    console.log('Actual:', this.testVar);
});
this.testVar = 'Reactive test';
```

or

```javascript
$scope.testVar = 'sample';
$scope.autorun(() => {
    console.log('Reactive:', $scope.getReactively('testVar'));
    console.log('Actual:', $scope.testVar);
});
$scope.testVar = 'Reactive test';
```

**Comment by seanjb** [comment]
Given that scenario, when using a directive with an isolated scope, I still want to access the scope variables reactively and also make my controller reactive. 

This is a valid use case and a common one. It did work up until this release so is there a new design pattern I should use to access the isolated scope variables reactively?

**Comment by kamilkisiela** [comment]
@seanjb Could you give me an example to help me understand it? I'm currently working on it.

At the moment, with the current solution it is impossible to make controller's context reactive and still use `$scope.getReactively`.

With your example I could make a solution.

If I understand you correctly, wouldn't it be easier to bind variables to the controller using [`bindToController`](https://docs.angularjs.org/api/ng/service/$compile#-bindtocontroller-)?

**Comment by seanjb** [comment]
Good tip on bindToController. Tested a use case using that and your previous comment (avoiding $scope all together) and it works. This does mean a significant re-write however unless we can fix this issue where scope and controller cannot be reactive together.

Some sample code to reproduce

```
angular.module("myModule").directive('testReactiveDirective', function () {
    return {
        restrict: 'E',
        template: 'Test Reactive Directive is loaded. {{testReactiveDirectiveCtrl.sortOrder}}',
        controllerAs: 'testReactiveDirectiveCtrl',
        scope: {sortDirection: '='},
        controller: function ($scope, $element, $reactive) {
            $reactive(this).attach($scope);
            this.sortOrder = 'Not Set Yet';

            this.autorun(() => {
                console.log('Reactive:' + $scope.getReactively('sortDirection'));
                console.log('Actual:' + $scope.sortDirection);
                this.sortOrder = $scope.sortDirection;
            });
        }
    };
});

angular.module("myModule").directive('testCtrl', function () {
    return {
        restrict: 'E',
        template: '<span ng-click="testCtrl.toggleSortOrder()">Change Sort</span> - <test-reactive-directive sort-direction="testCtrl.sortOrder"></test-reactive-directive>',
        controllerAs: 'testCtrl',
        scope: {},
        controller: function ($scope, $element, $reactive) {
            $reactive(this).attach($scope);
            this.sortOrder = 'ASC';

            this.toggleSortOrder = ()=>{
                if(this.sortOrder === 'ASC'){
                    this.sortOrder = 'DESC';
                } else {
                    this.sortOrder = 'ASC';
                }
            };
        }
    };
});
```

and the html
```
<test-ctrl></test-ctrl>
```

**Comment by kamilkisiela** [comment]
@seanjb As far as I know, the best practice in your case would be something like that:

```javascript
angular.module("myModule").directive('testReactiveDirective', function () {
    return {
        restrict: 'E',
        template: 'Test Reactive Directive is loaded. {{testReactiveDirectiveCtrl.sortOrder}}',
        controllerAs: 'testReactiveDirectiveCtrl',
        scope: {sortDirection: '='},
        controller: function ($scope) {
            this.sortOrder = 'Not Set Yet';

            $scope.autorun(() => {
                console.log('Reactive:' + $scope.getReactively('sortDirection'));
                console.log('Actual:' + $scope.sortDirection);
                this.sortOrder = $scope.sortDirection;
            });
        }
    };
});

angular.module("myModule").directive('testCtrl', function () {
    return {
        restrict: 'E',
        template: '<span ng-click="testCtrl.toggleSortOrder()">Change Sort</span> - <test-reactive-directive sort-direction="testCtrl.sortOrder"></test-reactive-directive>',
        controllerAs: 'testCtrl',
        scope: {},
        controller: function () {
            this.sortOrder = 'ASC';

            this.toggleSortOrder = ()=>{
                if(this.sortOrder === 'ASC'){
                    this.sortOrder = 'DESC';
                } else {
                    this.sortOrder = 'ASC';
                }
            };
        }
    };
});
```

**Comment by seanjb** [comment]
Thanks for quick reply!
This is a simple example to replicate the problem. My directives have functionality that requires both the scope and the controller to be reactive. For instances collection helpers etc. moving back to a full $Scope pattern moves me away from the benefits of ConrollerAs

'BindToController: true' will solve these problems but does require a significant refactor. 

This is a bit of breaking change in my view.

**Comment by Urigo** [comment]
@seanjb hi, so I agree that we should support it so it won't be a breaking change.
So we will work on a solution for the next version, will update on the solution as soon as possible.

But, I also agree that this is not a best practice anymore.
For best practices today I follow the Angular 1 to 2 guide, specially this section: https://angular.io/docs/ts/latest/guide/upgrade.html#!#using-component-directives

I hope we can get solution for your scenario soon.

**Comment by seanjb** [comment]
Thanks for that @Urigo yes I agree the bindToController method is the better appraoch to use here, and will start a process of re-factoring around this. The fix however will ease the immediate pain so thank you!

Is it worth calling out on the getRactively api docs that controller re-activity should be used in place of $scope where at all possible?

**Comment by kamilkisiela** [comment]
#1282 should fix that

**Comment by kamilkisiela** [comment]
#1278 should fix that

**Comment by Urigo** [comment]
@seanjb should be fixed now.
Please reopen if that isn't the case.
Thanks @kamilkisiela !
