### ISSUE TITLE
angular-templates templateCache.get delegate fails for certain 3rd libraries

### ISSUE THREAD

**Issue by blongstreth** [Urigo/angular-meteor#1274]
Some libraries call $templateCache.get method as part of a check to see if the cache entry exists.  If not, the 3rd party library will call $templateCache.set to add the entry.  Thus, angular-templates templateCache.get delegate will always fail making it impossible to use 3rd party libraries using the mentioned pattern.  As a result, can you please consider not throwing an error exception:
```
$delegate.get = function(templatePath) {
        var originalResult = originalGet(templatePath);

        if (angular.isUndefined(originalResult)) {
          var fileExtension = ((templatePath.split('.') || []).pop() || '').toLowerCase();

// PLEASE DON"T CHECK OR FIGURE A WAY TO BE SMARTER
          if (templatesFileExtension.indexOf(fileExtension) > -1) {
            throw new Error('[angular-meteor][err][404] ' + templatePath + ' - HTML template does not exists!');
          }
        }

        return originalResult;
      };
```

Link to code:
https://github.com/Urigo/angular-meteor/blob/master/packages/angular-templates/templates-handler.js

Link to 3rd part library code:
https://github.com/JanStevens/angular-growl-2/blob/master/src/growlDirective.js

Thanks,

Bradley

**Comment by Urigo** [comment]
@blongstreth very interesting scenario.

The reason we added this code was that we load all templates to templates cache and we want to notify the user when a path is wrong in a better way then just "Angular is loaded more than once".

I still want to notify the user about that, but maybe console.log instead of an Error would be sufficient, what do you think?
and @dotansimha what are your thoughts about that solution?

**Comment by blongstreth** [comment]
Thanks for quick response!  For the time being, I worked around this issue by decorating your decorator and trapping the exception and returning (void) 0 after catching :-)

Question:  Is it safe to say that angular-meteor assumes that $templateCache.get method is only called after the cache is set/loaded?  If so, too bad there is not a way to track while configuring and postpone the analysis.

**Comment by Urigo** [comment]
@blongstreth now you can set the settings to remove those warnings for your case
