### ISSUE TITLE
where is ReactiveContext.stop() in (1.3.7)

### ISSUE THREAD

**Issue by mixersoft** [Urigo/angular-meteor#1280]
I'm using this code with `angular-meteor#1.3.7`

```
ReactiveContext = $reactive(this).attach($scope)
```

and according to the 1.3.6 docs I'm supposed to call `stop()` manually. but I cannot find it in `1.3.7`

> stop
> This method takes care of stopping every subscribe, autorun and helpers registration you created.
> 
> Note that this method is called automatically when using $scope with your reactive context, which means you need to call this method manually when you do not use $scope.

**Comment by mixersoft** [comment]
I did find a `stop()` method on the subscription handle. is it enough just to call that?

```coffeescript

    $scope.$on '$ionicView.enter', (e)->
      subHandle = ReactiveContext.subscribe 'collection'

    $scope.$on '$ionicView.leave', (e) ->
      subHandle.stop()



```

**Comment by kamilkisiela** [comment]
```js
const context = $reactive(this).attach($scope)
context.stop()
// or
this.stop()
```

It's working on the latest release :)
