### ISSUE TITLE
JSONDiffPatch dependency in angular-meteor NPM module.

### ISSUE THREAD

**Issue by danimbrogno** [Urigo/angular-meteor#1281]
Hi, I just encountered a small bug when using angular-meteor installed via NPM. I haven't seen any docs on using it this way, so apologies if this is not a supported use case. 

I'm using angular 1.5.2 and angular-meteor 1.3.7 with Meteor 1.3 rc.3.

I have a helper which returns a cursor from a subscription:

```
this.helpers({
		invitations: () => companyInvitationCollection.getCompanyInvitationsById(this.getReactively('state.getActiveCompanyId()'))
});
```

When state.getActiveCompanyId() changes, my subscription re-runs triggering the invitations helper to update. At this point I get this warning in my console:

```
Exception from Tracker recompute function:
meteor.js?hash=b079ca6…:923 ReferenceError: jsondiffpatch is not defined
    at Scope.$$Reactive.$$handleCursor (modules.js?hash=732466d…:37519)
    at modules.js?hash=732466d…:37466
    at modules.js?hash=732466d…:37472
    at Object.Tracker.nonreactive (tracker.js?hash=6f5d0f5…:617)
    at Company.<anonymous> (modules.js?hash=732466d…:37462)
    at modules.js?hash=732466d…:36942
    at Tracker.Computation._compute (tracker.js?hash=6f5d0f5…:351)
    at Tracker.Computation._recompute (tracker.js?hash=6f5d0f5…:370)
    at Object.Tracker._runFlush (tracker.js?hash=6f5d0f5…:509)
    at onGlobalMessage (meteor.js?hash=b079ca6…:401)
```

It seems the package depends on benjamine/jsondiffpatch but this isn't specified in the packages dependencies.

As a workaround I installed jsondiffpatch manually: `npm install jsondiffpatch --save` and made it a global with:

```
import jsondiffpatch from 'jsondiffpatch';
window.jsondiffpatch = jsondiffpatch;
```

If there is a cleaner workaround let me know. Just thought I'd bring this to your attention, as I'm not sure if this slipped through the cracks, or whether installing via npm isn't yet supported.

Thanks for your great work!

**Comment by Urigo** [comment]
thanks @danimbrogno for the workaround, we are working now on the solution!
