### ISSUE TITLE
design Q: promises, angular-meteor 'reactivity', & Meteor.methods()

### ISSUE THREAD

**Issue by mixersoft** [Urigo/angular-meteor#1292]
I got used to building my `ionic+angular`apps with `promises`, but now that I've switched to `Meteor` + `angular-meteor#1.3.7` I'm discovering it's a lot of work to convert `reactivity` to `promises`.

With `promises`, I got used to knowing exactly when a change has completed -- and I can do the next thing. But with `angular-meteor` 'reactivity', the timing of backend changes don't seem to be so 'exact'. I can't help but think that I'm doing this wrong. Is it possible that what I used to do with `promises` should now be done inside `autorun()`? Am I supposed to let the `$digest` loop do more work?

```coffeescript

# ./posts/post.controller.coffee
PostCtrl = ($scope, $q)->
  ReactiveContext = $reactive(this).attach($scope)
  vm = this

  # from ng-click=".onComment($event, $post, $comment)"
  $scope.onComment = ($ev, post, comment)->
    return vm.postComment(post, {message:comment})
    .then (comment)->
        console.log(["success",comment])
    , (err)->
         console.log(["error",err])       
       
  # call Meteor.method with promises
  vm.postComment = (post, options)->
      comment = options.message
      from = Meteor.user()

      dfd = $q.defer()
      ReactiveContext.call 'Post.postComment', post, comment, from, (err, result)->
        if err
          return dfd.reject(err)
        dfd.resolve( Comments.findOne(result) )
        console.log ['Meteor::Post.postComment OK']
      return dfd.promise
  return vm

PostCtrl.$inject = ['$scope', '$q']
```

```coffeescript
# ./server/comments.model.coffee
Comments = new Mongo.Collection('comments')

# Post hasMany Comments
Meteor.methods({
  'Post.postComment': (post, comment, from)->
    comment = {
      type: "Comment"
      ownerId: from._id
      postId: post._id
      createdAt: new Date()
      comment: comment
    }
    Comments.insert( comment )
})
```

Is this a "better" pattern for angular-meteor?

```coffeescript
# ./posts/post.controller.coffee
  
  [...]
  vm.postId = $stateParams.id
  ReactiveContext.helpers {
    'comments': Comments.find({ postId: ReactiveContext.getReactively('vm.postId') })
  }
  ReactiveContext.autorun (tracker)->
    # using deep watch here
    comments = ReactiveContext.getReactively('comments', true)
   # do "promise-y" things here
```

**Comment by kamilkisiela** [comment]
@mixersoft 

Instead of this:

```coffee
ReactiveContext.helpers {
    'comments': Comments.find({ postId: ReactiveContext.getReactively('vm.postId') })
  }
  ReactiveContext.autorun (tracker)->
    # using deep watch here
    comments = ReactiveContext.getReactively('comments', true)
   # do "promise-y" things here
```

You can use this:

```js
// js because I'm not familiar with coffeescript

vm.postId = $stateParams.id;

vm.helpers({
  comments: () => Comments.find({ postId: vm.postId })
});
```

And now under `vm.comments` you have fetched data.

---

`ReactiveContext` is just a reference to `vm` so it's basically the same and you don't have to use it like this: 

```js
ReactiveContext = $reactive(this).attach($scope);
// just
$reactive(this).attach($scope);
```

**Comment by Urigo** [comment]
@mixersoft please reopen if that haven't solved your problem

**Comment by mixersoft** [comment]
@kamilkisiela  I understand your comment, but it doesn't really address my question - which is about using `promises` to tell `angular` when something was changed by the `angular-meteor` binding instead of just discovering the change while in the `$digest` loop. 

In the example above, I know how to get Comments for a Post.Id. But, I want to know **when** a `Comment` has been added from somewhere else, and then grab the commenter's `username` and face `pic`. or some other attribute from a FK lookup.

I think my use case is related to data de-nomalization in Meteor. For example, I want to save a Meteor userId as a FK in a Meteor doc, and grab the `username` and face `pic` from `Meteor.users`  when I display the doc. I can do it once when the doc is retrieved (and the code is a little cleaner), or I can do it every time in the `$digest` cycle. Is this an `un-Meteor` way to do things?

Q: Should I just assume that it costs me nothing to do a FK lookup to get a data attribute from `mini-mongo`?

However, I did discover that you can use plain `Meteor.call()` with angular `$q` promises to get changes from Meteor into the `angular` world, i.e. 3 way-binding.

**Comment by Tallyb** [comment]
@mixersoft  probably best to move the issue to the meteor forum with an angular tag. It will be great to have that discussion there regarding recommended patterns with angular and so. Ping here when you opened the topic.
