### ISSUE TITLE
meteor method not return array of string

### ISSUE THREAD

**Issue by navin10sharma** [Urigo/angular-meteor#1293]
```
Meteor.methods({
     checked: function(){
         var settingArray = setting.findOne({});
         if(settingArray){
             var Contactfields = {
                 "Contactfieldsname":[ "firstname","lastname", "phone","email"]
             };
             var contactFieldsArray = Contactfields.Contactfieldsname;
             console.log('array value' + contactFieldsArray );
             return contactFieldsArray ;
         }else{
             console.log('setting array Empty');
         }
    }
});
```

My console  O/P and return value :  arrayvalue : firstname,lastname,phone,email    
But i need output as array : [ "firstname","lastname", "phone","email"] 

can you guys please help me out why this happening..

Thanks

**Comment by ThomsCass** [comment]
this post is not related to angular-meteor ...

It is absolutely normal because you call the toString method of your array with the concatenation ...

```javascript
console.log('array value' + contactFieldsArray ); // => firstname,lastname,phone,email

console.log(contactFieldsArray ); // =>  [ "firstname","lastname", "phone","email"]
```

**Comment by Urigo** [comment]
@ThomsCass thanks for the answer.
@navin10sharma it seems like a question not related to angular-meteor.
I would suggest opening those in StackOverflow.
Let me know if that fine, closing for now.
