### ISSUE TITLE
Upgrade path for urigo:angular to angular (Meteor 1.1.0 to 1.2.1) / templating and angular-templates conflict

### ISSUE THREAD

**Issue by tehXor** [Urigo/angular-meteor#1297]
We were upgrading a Meteor 1.1.0 app to 1.2.1. The old version had `urigo:angular 0.8.4`. After the upgrade this package was marked as depreciated with the note that instead the official `angular` package should be used.

In a first try we did `meteor remove urigo:angular` and `meteor add angular` (as well as `meteor remove blaze-html-templates ecmascript` but those were not there in the first place).

However this leads to the problem that the app isn't starting anymore:
```
Errors prevented startup:
While determining active plugins:
error: conflict: two packages included in the app (templating and angular-templates) are both trying to handle *.html
```

I'm somewhat guessing `angular-templates` is a new dependency of `angular` while `templating` a leftover from the old meteor version? Unfortunately `meteor remove templating` is not working and the error stays the same after explicitly adding `templating` with `meteor add templating` and removing it again with `meteor remove templating`. I again can only guess it's maybe some dependency and cannot be removed from the project. 

If we should get that working we still have the *.ng.html scheme. From reading some issues it seems this is depreciated as well and I wonder what else might come next. We were considering urigo:angular as somewhat "stable" but for that these changes seem pretty heavy. Is there somewhere a clean documented upgrade path we missed so far? If not some advice would be great!

**Comment by Urigo** [comment]
@tehXor welcome to the new version!
so, with the old version the angular template compiler compiled `.ng.html` files and now it compiles `.html` files instead of Blaze.
If you want to update gradually, I would first replace `angular` with `angular-with-blaze` package that uses a compiler similar to the old one where `.ng.html` is for angular templates and `.html` is for Blaze.

I think there are a few issues about it but writing something more complete is a good idea.
Would love to help you with the update step by step and then have you write a small guide like that from your perspective.

**Comment by tehXor** [comment]
Thanks @Urigo for the feedback!

We managed to upgrade now. What we did was to create a clean and new meteor project with `meteor create` and then we manually added and removed all required packages with `meteor remove` and `meteor add` so that we basically had the same package state judging from the `packages` file of the old project. Then we copied the old projects source code over to the new project. This worked well and the app started without the conflicting error.
So I can recommend this approach for updates from older versions with similar problems.

It's funny that we still have `templating` in our project; it get's removed when your remove `blaze-html-templates` which we don't need. But we use `arsnebula:appupdate` and `templating` is a dependancy of that so at the point of adding `arsnebula:appupdate` `templating` gets installed again as well. Still now as mentioned before without the error.

Our templates with the `.ng.html` still work and we didn't need to change anything here. We got a lot of depreciation regarding the `$meteor` and `$meteorCollection` APIs. We refactored all that to the new `helpers` API which seems to work so far but that was a little more fuss.

Well and yes, it would be great to have a documentation section for updates were every update has a little section with all required adaptions in detail. I know this will probably not happen soon or ever as it would be a lot of work but still it would be nice ;-)
We run the app in question since 2014 and were two times at the point were an update required quite a lot of work. And the process of update currently is to just upgrade and see what errors hit you. If you are lucky these are depreciation warnings and you find some documentation about it (also it's often not enough when you have more specific implementations of the old APIs). And then there are still a lot of cases where you have actual errors which you need to figure out on your own or with the help of Google/GitHub/Stackoverflow.
This is especially true if you don't update on very regular basis but once every few month when it really gets necessary which is quite often the case in the real world :P 

That being said this is still a great project and we are still very happy with our choice using this over Meteor's native templating and use it in new projects as well. So :+1: !
