### ISSUE TITLE
Module 'angular-meteor' is not available error after upgrading to Meteor 1.3

### ISSUE THREAD

**Issue by franciskim** [Urigo/angular-meteor#1302]
I have a very simple prototype that I wrote on 1.2 - when I heard the news a few hours ago I immediately upgraded my Meteor to 1.3 and now I'm stuck with the error:

`Error: [$injector:nomod] Module 'angular-meteor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

Anyone have any ideas?

My modules are as follows:

```
angular                        1.3.9  
autopublish                    1.0.5  
es5-shim                       4.5.8  
http                           1.1.3  
insecure                       1.0.5  
jquery                         1.11.6 
meteor-base                    1.0.2  
mobile-experience              1.0.2  
mongo                          1.1.5  
oauth2                         1.1.7  
session                        1.1.3  
spectrum:material-design-lite  0.0.4  
standard-minifier-css          1.0.4  
standard-minifier-js           1.0.4  
tracker                        1.0.11 
```

**Comment by capanemaggfc** [comment]
that's the same for me :/

**Comment by capanemaggfc** [comment]
same error here :/

**Comment by admeister** [comment]
+1

**Comment by mxab** [comment]
can you try if this works for you
in you app.js
```
import angular from 'angular';
import 'angular-meteor';

angular.module('yourApp', ['angular-meteor']);
```

**Comment by franciskim** [comment]
@mxab thanks for that - I've already tried with no luck. My current set up seems to complain about the reserved keyword `import`

**Comment by admeister** [comment]
I'm just using regular old JavaScript not won't work me for.

**Comment by mxab** [comment]
@franciskim your current setup in IDE terms or is some meteor processing/compiling step complaining?

@admeister "regular old JavaScript" means?

**Comment by admeister** [comment]
I'm not using TypeScript

**Comment by admeister** [comment]
Or ECMAScript 6

**Comment by franciskim** [comment]
@mxab during the Meteor compiling/processing stage

**Comment by mxab** [comment]
@franciskim can you add pbastowski:angular-babel@1.3.1 to your `packages`

**Comment by Urigo** [comment]
@franciskim can you share your repo so I could have a look?

**Comment by jmwierzbicki** [comment]
@Urigo I have totally same issue with my application - updating to 1.3 makes it crash at loading angular-meteor, Im not sure but i think it worked before i typed (as meteor suggested me)  

> meteor npm install --save angular underscore jsondiffpatch

**Comment by Urigo** [comment]
I know the solution, working on a new release right now.
would love more reproductions so I can make sure I'm solving it

**Comment by franciskim** [comment]
@Urigo the repo is at work so it'll take me at least 12 hours before I can come back to you.

**Comment by jmwierzbicki** [comment]
@urigo - application is working now, thanks for fix :+1: 

by the way, there is still issue with text visible before application fully loads

**Comment by Urigo** [comment]
Please try `1.3.9_1` and let me know if that works for you

**Comment by capanemaggfc** [comment]
works fine here, thanks @Urigo !

**Comment by luncasu** [comment]
Works for me too.

**Comment by ahmedbouhmid** [comment]
me not working

2016-03-29 15:27 GMT+01:00 luncasu <notifications@github.com>:

**Comment by Urigo** [comment]
@ahmedbouhmid can you provide a reproduction?

**Comment by franciskim** [comment]
fixed it for me, thanks!
