### ISSUE TITLE
angular-meteor-auth may be preventing the upgrade to 1.3.9_1

### ISSUE THREAD

**Issue by trajano** [Urigo/angular-meteor#1303]
When doing a `meteor update` the `angular` package appears to get prevented from being updated by `angular-meteor-auth`

<pre>
The following top-level dependencies were not updated to the very latest version available:
 * angular 1.3.7 (1.3.9_1 is available)
 * angular-meteor-auth 0.2.2 (1.0.0 is available)
</pre>

By doing
<pre>
meteor remove angular-meteor-auth
meteor update
meteor add angular-meteor-auth
</pre>

We get things updated.  Is there a way of fixing the packaging so that this the above manual steps can be removed?

**Comment by Deadly0** [comment]
@trajano I saw similar complaints at meteor bug tracker but with others packages. Looks like it is not an angular-meteor specific problem.

**Comment by Urigo** [comment]
@trajano the reason for that is that Meteor wants you to be aware before updating to a new major version. it's for safety.
I've updated angular-meteor-auth to 1.0.0 because I think it's ready.

Closing, please reopen if it's not clear..

**Comment by trajano** [comment]
Thanks just want to make sure that the behaviour is intentional.
