### ISSUE TITLE
Update tutorial to use AngularJS 1.5.x component syntax

### ISSUE THREAD

**Issue by sean-stanley** [Urigo/angular-meteor#1307]
It would be a good idea to upgrade the tutorial to angularJS 1.5.x component syntax.

I would personally love to learn if there are any special advantages that can be gained for meteor from the new version. A blog post on best practices with 1.5.x would be neat too as the new component guide from the angular js team is introducing quite a few new concepts to app structuring.

Also, if necessary I can be available to help upgrade the tutorial.

**Comment by Urigo** [comment]
in the works!

**Comment by Urigo** [comment]
done - http://www.angular-meteor.com/tutorials/socially/angular1/3-way-data-binding#upgradingtocomponentssyntax
