### ISSUE TITLE
Application broken after updating to Meteor 1.3

### ISSUE THREAD

**Issue by longxuanho** [Urigo/angular-meteor#1308]
After I update meteor from version 1.2 to 1.3, everything has broken. The error message is: 
`Error: [$injector:nomod] Module 'angular-meteor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

**Comment by muninn9** [comment]
Mine also broke only I received this error, "angular@^1.2.27 not installed".

**Comment by kamilkisiela** [comment]
Try to use the latest version which is `1.3.9_2`.

**Comment by crstn210** [comment]
same here, i have two apps, I've upgraded both to 1.3 and one has broken with the same error, i'm trying  to see the difference

**Comment by crstn210** [comment]
Problem solved, some dependencies where preventing angular meteor upgrade successfully, you have to update the versions manually, look at the log when you update meteor

**Comment by Urigo** [comment]
awesome.
closing, please let me know if needs to reopen
