### ISSUE TITLE
angular-templates default export with path

### ISSUE THREAD

**Issue by trajano** [Urigo/angular-meteor#1311]
The current default export in angular-templates just returns an empty object.  Can we add the path name for the template as part of the object so we can refer to it symbolically rather than a string?

<pre>
import editTemplate from './todo-edit.tpl.html'
import listTemplate from './todos.tpl.html'
...
     views: {
          'content@app': {
            templateUrl: listTemplate.url,
...
     views: {
          'content@app': {
            templateUrl: editTemplate.url,
...
</pre>

FYI, I didn't see an `angular-templates` repository, is there one?  I don't use angular-meteor as per the example in the updated angular todos app.

I'm using ui-router as a dependency.

### When reporting a bug, please be sure to include the following:
- [x] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `angular-meteor` you're using, and the platform(s) you're running it on
- [X] What packages or other dependencies you're using
- [X] The behavior you expect to see, and the actual behavior

**Comment by trajano** [comment]
I think the following line gets generated ... 

    angular.module('angular-templates').run(['$templateCache', function ($templateCache) {
    $templateCache.put('client/foo/tab-default.html',
    ...

can be changed to

    var templateUrl = 'client/foo/tab-default.html';
    angular.module('angular-templates').run(['$templateCache', function ($templateCache) {
    $templateCache.put(templateUrl,

    exports.default = templateUrl

Though I haven't found the pertinent code that does the generation yet.

**Comment by trajano** [comment]
I think I have found it in `compileNGTemplate_plugin.js` but I can't find the source anywhere at least Google search for it with quotes yields no results.

The part that needs to change should be 
<pre>
function wrapAngularTemplate(id, contents) {                                                                        // 111
  return "angular.module('angular-templates').run(['$templateCache', function($templateCache) { $templateCache.put('" + id + "'," + JSON.stringify(contents) + ");}]);";
}                                                                                                                   //
</pre>

to 
<pre>
function wrapAngularTemplate(id, contents) {                                                                        // 111
  return 
    "var templateUrl = '" + id + "';" +
    "angular.module('angular-templates').run(['$templateCache', function($templateCache) { $templateCache.put(templateUrl," + JSON.stringify(contents) + ");}]);" +
    "exports.default = templateUrl;";
}                                                                                                                   //
</pre>

**Comment by Urigo** [comment]
Reviewing

**Comment by Tallyb** [comment]
components with inline html rules! (one woman's opinion, but I found it very convenient)
If the file gets too big, you should probably further componentize it...

**Comment by trajano** [comment]
I kind of wish I can do a "lazy load" with my PR, but I am not sure how yet.  Only thing I did was extract and export the template ID.

**Comment by kamilkisiela** [comment]
@Urigo #1354 closes it

**Comment by Urigo** [comment]
you can find the docs here: http://www.angular-meteor.com/api/1.3.11/templates
@kamilkisiela thanks!
