### ISSUE TITLE
(Angular-Meteor Tutorial) Retrieve the lastest document inserted to MongoDB

### ISSUE THREAD

**Issue by longxuanho** [Urigo/angular-meteor#1312]
In helper, how can I get the lastest document inserted to MongoDB? I have tried:

`
this.helpers({
    newestParty: () => Parties.find({}, {sort: {_id: -1}, limit: 1})
});
`

but it does not work.

**Comment by longxuanho** [comment]
Finally I found that we cannot query for the lastest document based on neither _id or $natural key. It should be:
`
this.helpers({ newestParty: () => Parties.find({}, {sort: {createdAt: -1}, limit: 1}) }); 
`

**Comment by Urigo** [comment]
thanks for updating!

**Comment by ThomsCass** [comment]
have you try this : `Parties.findOne({},{sort:{$natural:-1}});`

**Comment by longxuanho** [comment]
Sorry. It doesn't work. The error is:

`
angular.js:12520 Error: unsupported sort key: $natural
`

It's seems like Meteor MongoDB is quite different to the original one although they said it just a wrap around Mongo cursor. You also cannot chain methods like this:

`
Parties.find().limit().sort() // You cannot do this too
`

**Comment by ThomsCass** [comment]
It works for me on server side. I don't know client side
