### ISSUE TITLE
Iron router splash screen when using angular meteor

### ISSUE THREAD

**Issue by ThomsCass** [Urigo/angular-meteor#1314]
Hi guys,

I'm using angular-meteor but for my REST API I use iron router. Everything works great the only problem is that because I suppose I don't use iron-router on client side I get this awful splash screen :

```javascript
iron:router
Organize your Meteor application.

Router.route('/', function () {
  this.render('Home', {
    data: function () { return Items.findOne({_id: this.params._id}); }
  });
});
````
How can I remove it cause I get it on every single page of my app ...

Thanks a lot

**Comment by Urigo** [comment]
I think you will find the solution here: http://stackoverflow.com/questions/31035196/iron-router-conflict-with-angular-ui-router
If not, please feel free to re-open

**Comment by ThomsCass** [comment]
@Urigo Thanks for the link but it doesn't help.

In my case I use Iron router only on server side so I don't have any routes on my client and don't want any. It's a problem with iron router if you don't use any routes on the client but then it's not compatible with ui-router and so angular meteor.

this issue is also related https://github.com/iron-meteor/iron-router/issues/976

What I do for a work around is this :

somewhere in js client file :

```javascript
Router.configure({
        notFoundTemplate: 'pageNotFound'
    });
```
With that iron-router is going to create a disgusting message but in only one div with the word 'pageNotFound' in it in all your views.

Then in all my controller I call this :
```javascript
ResetIron = function(){
    $( document ).ready(function() {
        setTimeout(function(){
            $('div:contains("pageNotFound")').remove();
        }, 500);
        setTimeout(function(){
            $('div:contains("pageNotFound")').remove();
        }, 3000); // ==> for IE
    });
}
```

which is a pretty disgusting solution. I would be lovely if you could re-open this issue until something clean is provide :)

Thanks

**Comment by ThomsCass** [comment]
Beside it slows down the app on mobile as the iron-router logic is run too.

**Comment by MilosStanic** [comment]
Just experienced this myself with Meteor 1.3 and Angular2-Meteor. 
Using iron:router to load image files from server (because there's hundreds of them and placing them in /public makes node go wild on RAM). So I get this ugly splashscreen. 
I saw your workaround @ThomsCass with jquery, but for some reason it doesn't work for me. And you're right, it's ugly.

**Comment by ThomsCass** [comment]
@MilosStanic it's strange.

But yeah it's ugly so what I think of was to make a reimplementation of the iron-router with no splash screen to work with meteor angular.

But as I'm not an expert in rewriting for now here is what I try :

- I cloned the repo of iron router on github
- find the code of the splashscreen and remove it
- modify the package.js and publish it to atmopshere

and voila : `https://atmospherejs.com/thoms/iron-router-no-splash`

But it's not working! I probably missed something but I don't know what, if someone is interested to help so we can have a proper solution it would be great!

Thanks

**Comment by MilosStanic** [comment]
@ThomsCass maybe you should submit a pull request to iron-router with a fix. They may accept it, as there are many people complaining.
My attempt at your first workaround with jquery failed because I'm using Angular2-Meteor, and I had trouble importing `$` .

**Comment by paolo-g** [comment]
Thanks for the solution @ThomsCass but this definitely needs to get resolved here https://github.com/iron-meteor/iron-router/issues/976
