### ISSUE TITLE
angular-meteor-auth

### ISSUE THREAD

**Issue by eorengo** [Urigo/angular-meteor#1317]
Hi there,

I'm following the tutorial (whatsapp with ionic and meteor) but I'm can't moved next of the point 4.24, we had to add lib/angular-meteor/dist/angular-meteor-auth.bundle.js but we've never added that library. My current angular-meteor version is 1.3.9 but I tried many others. I also tried downloading angular-meteor-auth as a different package ("bower install angular-meteor-auth") and I try to fix the path to lib/angular-meteor-auth-auth/dist/angular-meteor-auth.bundle.js to find the js but it didn't work either. Any ideas? Thanks!!
BTW, I'm also downloaded the latest full project and I get all the npm's and bower's libs and I still seeing the path wrong  :-(

**Comment by Urigo** [comment]
Are you using Ionic CLI or Meteor CLI one?
http://www.angular-meteor.com/tutorials/whatsapp/

**Comment by eorengo** [comment]
I tried both. Meteor works but I wanted to test it in Ionic. Thanks




-------- Mensaje original --------
De: "EXTERNAL:Uri Goldshtein"
Fecha:10/04/2016 06:46 PM (GMT-05:00)
A: Urigo/angular-meteor
CC: ORENGO Emiliano Roy TENARIS
Asunto: Re: [Urigo/angular-meteor] angular-meteor-auth (#1317)


Are you using Ionic CLI or Meteor CLI one?
http://www.angular-meteor.com/tutorials/whatsapp/

**Comment by ShaharLahav** [comment]
same problem here

**Comment by numerized** [comment]
Same problem here.
Please URGENT. :))))

**Comment by sean-stanley** [comment]
angular meteor auth is not a necessary package as functionality can be easily duplicated either with the $root.currentUser variable in templates or simply use Meteor.userId() in controllers. One caveat is that Meteor.userId() will most likely return undefined on initial page load as it won't be watched reactively. Fix this with this.autorun() wrapper.

**Comment by DAB0mB** [comment]
@eorengo I fixed this problem not a long ago, the use of bower is deprecated so we make a full use of npm instead. Can you please tell me if the issue is fixed?

**Comment by Urigo** [comment]
please open a new one if the new package do not work for you
