### ISSUE TITLE
Load angular template files tegother in production

### ISSUE THREAD

**Issue by wanli2011** [Urigo/angular-meteor#132]
In production, put all angular template in one file, and load once

**Comment by netanelgilad** [comment]
I think this could be done for development as well, since it's just templates and not code. @wanli2011  @Urigo what do you think?

**Comment by wanli2011** [comment]
If templates is modified, it can not be refreshed immediately in some browsers. Need to clear the cache.

**Comment by Urigo** [comment]
New version with this fix has just been released
