### ISSUE TITLE
Tutorial problems (does not run by following exact steps and missing chapters)

### ISSUE THREAD

**Issue by kokokenada** [Urigo/angular-meteor#1324]
* I had to deviate from the tutorial instructions and put main.js in the client folder (tutorial said root folder) in order to avoid a build error (ReferenceError: window is not defined)

* Furthermore, as I flip through the chapters 17, 18, 20, 21, 22 the text from the last displayed chapters are displayed. (I was hoping to see if anything has changes to packaging and ionic that are required in Meteor 1.3)

**Comment by benco1967** [comment]
+1 chapters 17 18 20 21 22 are not displayed

**Comment by Urigo** [comment]
those chapters are not updated yet in the Angular 1.x tutorial.  I hope to get them updated this weekend.
the Angular 2.0 chapters are updated until 18

**Comment by kamilkisiela** [comment]
@kokokenada @benco1967 

Steps (each PR):
- [17-18]
- [19]
- [20-21]
- [22]

are now available! :)

[17-18]: https://github.com/Urigo/angular-meteor-docs/pull/43
[19]: https://github.com/Urigo/angular-meteor-docs/pull/44
[20-21]: https://github.com/Urigo/angular-meteor-docs/pull/61
[22]: https://github.com/Urigo/angular-meteor-docs/pull/69

**Comment by Urigo** [comment]
thank you @kamilkisiela !

**Comment by benco1967** [comment]
Hi,

I try to rebuild my application with the new version it works well, just
fine.

I just need to improve Roles like I did with the previous version.

Your work is awesome.
At work I use to work with Play! and ng 1.3, but I like Meteor and ng 1.5
Explain with your tutorial it's a piece of cake

best

Benoît
