### ISSUE TITLE
autorun not autorunning

### ISSUE THREAD

**Issue by fpaboim** [Urigo/angular-meteor#1328]
I'm using autorun with the controllerAs syntax. When I use somthing like this in my controller:

```
      this.autorun(() => {
        let trips = Trips.find({})
        console.log('Updated trips')
      });
```

Autorun is not running when I update the Trips collection. If I use this hack and add '.fetch()'

```
      this.autorun(() => {
        let trips = Trips.find({}).fetch()
        console.log('Updated trips')
      });
```

Then autorun reruns as expected, so I have a bunch of these hacks sprinkled on my controller. Is something in my app broken, is this by design or is it a bug? Thanks!

**Comment by jacobdr** [comment]
Based on my reading of the docs for collection.find --docs.meteor.com/#/full/find(http://docs.meteor.com/#/full/find)-- the reactivity for a cursor does not begin until you have attempted to retrieve any documents via the fetch map or forEach methods.

You can ignore the return value from such a call if you want -- but it's not the typical case that you'd want just a cursor without some need for its document (the observe and observe changes methods being the only exception I can think of ATM).


JR

**Comment by fpaboim** [comment]
Ok, thanks for clarifying!
