### ISSUE TITLE
$meteor.forgotPassword other way

### ISSUE THREAD

**Issue by ThomsCass** [Urigo/angular-meteor#1329]
Hi,

Is there an other way to implement this method with the new API :

```javascript

$meteor.forgotPassword({email:vm.user.email}).then(
                function () {
                    $mdDialog.show(
                        $mdDialog.alert()
                            .parent(angular.element(document.body))
                            .clickOutsideToClose(true)
                            .title('Réinitialisation du mot de passe.')
                            .content('Un email a été envoyé à votre adresse de messagerie.')
                            .ariaLabel('Réinitialisation')
                            .ok('Ok')
                    );
                    $state.go(blockSettings.pageLogin);
                },
                function (err) {
                    toastr.error('Veuillez vérifier votre email.');
                }
            );
````

In fact this one is really slow because we have to wait the email to be send.

**Comment by kamilkisiela** [comment]
You can use [`Accounts.forgotPassword`](http://docs.meteor.com/#/full/accounts_forgotpassword)

```js
import { Accounts } from 'meteor/accounts-base';

// ... somewhere inside a controller

Accounts.forgotPassword(data, (error) => {
    if (error) { 
        toastr.error
    } else {
         $mdDialog.alert
    }
});
```

Or with [`$bindToContext`](http://www.angular-meteor.com/api/1.3.6/reactive-context) if you need to keep it inside the digest cycle.

As you could see in the example above, `$meteor.forgotPassword` works the same way as `Accounts.forgotPassword` but it has that callback transformed into `Promise`.

---

About:

> In fact this one is really slow because we have to wait the email to be send.

You can create your own method to send emails with password with usage of [`this.unblock()`](http://docs.meteor.com/#/full/method_unblock).
