### ISSUE TITLE
How to disable reactivity?

### ISSUE THREAD

**Issue by ryuken** [Urigo/angular-meteor#1332]
I have a question, I'm using angular 1 with meteor.
I'm trying to fetch some data non-reactive, but it's not working it only returns undefined.
I use it like this Orders.findOne({ _id: $stateParams.id }, { reactive : false })
In reactive mode it first returns undefined and then the correct data

**Comment by trajano** [comment]
It's best to ask this kind of question on the http://forums.meteor.com or stackoverflow

**Comment by ryuken** [comment]
yeah true thanks I'll close the issue =P
