### ISSUE TITLE
issues with step 00 of the tutorial

### ISSUE THREAD

**Issue by pauldhawk** [Urigo/angular-meteor#1333]
tutorial questions:

1. created files is not correct tutorial says
    - socially.css    (delete)
    - socially.html   (delete)
    - socially.js     (delete)
    I get the folder stuructor :
            ├── client
        │   ├── main.css
        │   ├── main.html
        │   └── main.js
        ├── package.json
        └── server
            └── main.js
2. should we  delete the following files? :
    ├── client
    │   ├── main.css (delete)
    │   ├── main.html (delete)
    │   └── main.js (delete)
    ├── package.json
    └── server
    └── main.js (keep?)

3. assuming we still create index.html?

4. on npm init
    should entry point: (index.js) be index.html?
    should be use the git repo   "url": "git+https://github.com/dotansimha/meteor-angular2.0-socially.git"?
5.  on
        meteor npm install --save angular2-meteor
    do we need the meteor? doesn't this work:
        npm install --save angular2-meteor

6. on .08 can you explain why we import do we need it in each file or just the main app:
    import 'reflect-metadata';
    import 'zone.js/dist/zone';
7. on .09's title is Add the main component HTML file
    should the word main be changed to app
8.  under code .10- what imports are best for meteor.start? the app.ts or html file? can you add a link to the Meteor.start docs
9.  TypeScript Typings section -
     - shouldn't there be a
        typings -init to create the typings.config file
        and the instals have a -- save on them
        ie
            typings -init
            typings install es6-promise --save
            typings install es6-shim --ambient --save
    - should we make the meteor def file a command to install
        putting it in the correct folders:
            typings install Meteor=https://gist.githubusercontent.com/tomitrescak/8366ce98f1857e202ea8/raw/4c8850ad8174de2662f92c87328280838e0ab5fd/meteor.d.ts --ambient --save
        just downloading it
            typings install Meteor=https://gist.githubusercontent.com/tomitrescak/8366ce98f1857e202ea8/raw/4c8850ad8174de2662f92c87328280838e0ab5fd/meteor.d.ts

    shouldn't the d.ts files be in the correct space
    ├── main
│   │   ├── ambient
│   │   │   ├── Meteor
│   │   │   │   └── index.d.ts

10 shouldn't the tsconfig.json have a excludes section to stop duplicate regs:
    {
      "compilerOptions": {
        ......
      },
      "exclude": [
        "node_modules",
        "typings/browser",
        "typings/browser.d.ts",
      ]
    }
10. the start of the next chapert has code from the last step. this code does not compile. 
I have setup a repo for the steps. you are welcome to use it:
https://github.com/pauldhawk/socially-tutorial.git 

pps is this good? I can do the rest of the steps....

**Comment by Urigo** [comment]
should be fixed now
