### ISSUE TITLE
issues with step 00 and 03 of the tutorial

### ISSUE THREAD

**Issue by pauldhawk** [Urigo/angular-meteor#1334]
tutorial questions:

1. created files is not correct tutorial says
    - socially.css    (delete)
    - socially.html   (delete)
    - socially.js     (delete)
    I get the folder stuructor :
            ├── client
        │   ├── main.css
        │   ├── main.html
        │   └── main.js
        ├── package.json
        └── server
            └── main.js
2. should we  delete the following files? :
    ├── client
    │   ├── main.css (delete)
    │   ├── main.html (delete)
    │   └── main.js (delete)
    ├── package.json
    └── server
    └── main.js (keep?)

3. assuming we still create index.html?

4. on npm init
    should entry point: (index.js) be index.html?
    should be use the git repo   "url": "git+https://github.com/dotansimha/meteor-angular2.0-socially.git"?
5.  on
        meteor npm install --save angular2-meteor
    do we need the meteor? doesn't this work:
        npm install --save angular2-meteor

6. on .08 can you explain why we import do we need it in each file or just the main app:
    import 'reflect-metadata';
    import 'zone.js/dist/zone';
7. on .09's title is Add the main component HTML file
    should the word main be changed to app
8.  under code .10- what imports are best for meteor.start? the app.ts or html file? can you add a link to the Meteor.start docs
9.  TypeScript Typings section -
     - shouldn't there be a
        typings -init to create the typings.config file
        and the instals have a -- save on them
        ie
            typings -init
            typings install es6-promise --save
            typings install es6-shim --ambient --save
    - should we make the meteor def file a command to install
        putting it in the correct folders:
            typings install Meteor=https://gist.githubusercontent.com/tomitrescak/8366ce98f1857e202ea8/raw/4c8850ad8174de2662f92c87328280838e0ab5fd/meteor.d.ts --ambient --save
        just downloading it
            typings install Meteor=https://gist.githubusercontent.com/tomitrescak/8366ce98f1857e202ea8/raw/4c8850ad8174de2662f92c87328280838e0ab5fd/meteor.d.ts

    shouldn't the d.ts files be in the correct space
    ├── main
│   │   ├── ambient
│   │   │   ├── Meteor
│   │   │   │   └── index.d.ts

10 shouldn't the tsconfig.json have a excludes section to stop duplicate regs:
    {
      "compilerOptions": {
        ......
      },
      "exclude": [
        "node_modules",
        "typings/browser",
        "typings/browser.d.ts",
      ]
    }
10. the start of the next chapert has code from the last step. this code does not compile. 
I have setup a repo for the steps. you are welcome to use it:
https://github.com/pauldhawk/socially-tutorial.git 

--------------- step 3
1. code in 3.4 missing NgZone
    import {Component, NgZone} from 'angular2/core';
2. code in the section below 3.4 missing tracker
    import {Tracker} from 'meteor/tracker';
3. 3.7 missing Mongo import
    import {Mongo} from 'meteor/mongo';

-------------- step 4
1. component Component Architecture party
    in paragraph says to put the new file in ("client/parties-form").
    in the code block (4.1) client/imports/parties-form/parties-form.ts
    -- which is correct ??

---- step 5
1. in 5.2 missing mongo imoport
    import {Mongo} from 'meteor/mongo';
2. above config rts there is a list of folder structor
client
  \- parties-list
  \- parties-form
  \- party-details

in almost all other sections it goes client\imports\....

3. 5.13 import wrong does not need .ts :
    import {Parties} from '../../../collections/parties'

-------------- setup 4
1. component Component Architecture party
    in paragraph says to put the new file in ("client/parties-form").
    in the code block (4.1) client/imports/parties-form/parties-form.ts
    -- which is correct

---- step 5
1. in 5.2 missing mongo imoport
    import {Mongo} from 'meteor/mongo';
2. above config rts there is a list of folder structor
client
  \- parties-list
  \- parties-form
  \- party-details

3. 5.13 import wrong does not need .ts :
    import {Parties} from '../../../collections/parties'

**Comment by dotansimha** [comment]
Step 0:
1. fixed.
2. fixed.
3. Described in step 0.1.
4. Fixed.
5. It's the same - we recommend to use "meteor npm install" so if you do not have "node" installed at all - it will still work.
6. It's the dependencis of Angular 2 - it's no longer needed to be imported in each file - it's there because of some issue with Meteor that already fixed. 
7. It's app, but it's still the main endpoint of the app - it's that same actually...
8. Old comment - removed.
9. 
install commands - Fixed.
meteor 1.3 typings - It's in a repo now - fixed.
excludes - relevant only from Meteor 1.3.2 and up, so updated it now.
10. Fixed.

step 3:
1. fixed.
2. fixed.
3. fixed.

step 4:
1. fixed.

step 5:
1. fixed.
2. fixed.
3. fixed.

All of the changes are in https://github.com/Urigo/angular-meteor-docs/pull/86

@Urigo

**Comment by Urigo** [comment]
deployed
