### ISSUE TITLE
is there an ETA for the 1.4 version?

### ISSUE THREAD

**Issue by dohomi** [Urigo/angular-meteor#1335]
Hi @Urigo 

is there any ETA for the `1.4` version? As there are many code changes it would be great help to know when its a good time starting with the restructure.

Cheers,
Dominic

**Comment by Urigo** [comment]
so, I've removed the default deprecation messages from the code in 1.3 as I see that version as long term support for all APIs to date.
About 1.4, I think it will take a while as I'm thinking of a new API that will be more generic and similar between Angular 1.x Meteor, Angular 2.0 Meteor and Angular Apollo.
also, because it will be a breaking change when it comes, I will publish it as 2.0 and not 1.4 to avoid making people update unintentionaly.

**Comment by mxab** [comment]
> About 1.4, I think it will take a while as I'm thinking of a new API that will be more generic and similar 
> ...because it will be a breaking change when it comes
... we spent more or less to nearly 2 weeks day and night lifting our code base from 1.2 to 1.3... our hands are bleeding and our heads are ringing... please don't tell me the the 1.3 to 1.4 will again be such a huge change in the api ...ok we switched also a lot of stuff to components, es6 classes and modules and reviewing some code felt good... but still

**Comment by Urigo** [comment]
no no, 1.3 is here to stay for a very very long while, I will support it for as long as needed.

When I'm talking about 2.0 (not 1.4) I'm talking about something really really far away into the future, no point about thinking or preparing for it now and in recent months.
I know the 1.3 transition as hard, I won't do that again for you.

**Comment by mxab** [comment]
ok :)

**Comment by dohomi** [comment]
@Urigo this means that the actual rewrite away from the `$scope.$meteor<service>` services was actually not really necessary? I thought they will be removed sometimes soon as part of `1.4`? I think the current documentation could lead to some confusion.. as I'm confused right now :)

**Comment by Urigo** [comment]
I do not recommend the old API.
The new API is better and I recommend you to use it.
If you don't want to update, you can always continue to use the old version, nobody "deletes" 1.2 or 1.3, you can always just keep using old versions, like any other library.

**Comment by dohomi** [comment]
ok thanks! Keep up the good work!
