### ISSUE TITLE
$parent not working in controller

### ISSUE THREAD

**Issue by navin10sharma** [Urigo/angular-meteor#1336]
I have the following code in form $parent.checkOut is working fine. But once i try to access this Data in conoller {this.$parent.checkOut} but it showing undefiend. Can you please help me how i can access these model Data into my controller.

`  <div class="input-group date">
                                        <input type="datetime" class="form-control" date-time
                                               ng-model="$parent.checkOut" view="date"
                                               min-view="date" format="YYYY-MM-DD" auto-close="true">
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    </div>`

can i know $parent is currently supported or not in angular-meteor.

**Comment by kamilkisiela** [comment]
@navin10sharma It's related to `angular` not `angular-meteor` but I don't think it's works this way.

Here's [an explanation](http://stackoverflow.com/questions/21453697/angularjs-access-parent-scope-from-child-controller).
