### ISSUE TITLE
Can't use functions inside {{ }} template delimiters

### ISSUE THREAD

**Issue by fredrikekelund** [Urigo/angular-meteor#134]
I just upgraded to 0.6.0 and tried migrating to Angular's standard `{{...}}` template delimiters, but it seems I can't make function calls inside those template delimiters. Here's my error output:

	=> Your application has errors. Waiting for file change.
	=> Modified -- restarting.                    
	=> Errors prevented startup:                  
	   
	   While building the application:
	   client/views/data-listener.html:142: Expected identifier, number, string, boolean, or
	   null
	   ...ner is <em>{{Listener().status}}</em></sp...
	   ^

**Comment by ndevr** [comment]
@fredrikekelund  change the filetype to *.tpl otherwise use angular ng-bind direct

**Comment by fredrikekelund** [comment]
Ah, my bad. Thanks for the help!
