### ISSUE TITLE
Error: "r" when logging in or resetting password

### ISSUE THREAD

**Issue by danielflippance** [Urigo/angular-meteor#1340]
Some of my end users are having problems logging in and resetting their password. When I try to do the same using their username and password, the Meteor call returns an error "r". The two methods I'm calling are:

- $meteor.loginWithPassword
- Accounts.resetPassword

Is "r" a code that I can lookup to find the meaning?
I'm running Meteor 1.2.1. My Angular Meteor versions are:

accounts-base@1.2.2
accounts-password@1.1.4
accounts-ui@1.1.6
accounts-ui-unstyled@1.1.8
angular@1.3.1
angular-meteor-data@0.0.8
angular-templates@0.0.3
angular:angular@1.4.8
angular:angular-animate@1.4.8
angular:angular-sanitize@1.4.8
angularui:angular-ui-router@0.2.15

**Comment by Tallyb** [comment]
This function is probably a minified version of the code. you will need to run in development / debug mode.

**Comment by kamilkisiela** [comment]
@danielflippance Any more details? :)

**Comment by danielflippance** [comment]
Turns out the user in question thought they had created an account but they had not. The "r" error message in this case meant: "You do not have an account"

**Comment by kamilkisiela** [comment]
@Urigo OK, so we can close this issue now
