### ISSUE TITLE
Blaze 2 Angular 2 Docs

### ISSUE THREAD

**Issue by lorensr** [Urigo/angular-meteor#1342]
I didn't see an issue tracking this section of the docs, just a non-functioning "Angular 2" button on this page:

http://www.angular-meteor.com/migration/angular1/intro

I have a Blaze/IR mobile app, and I'd like to put it in an Ionic 2 shell, with a tab bar and iOS swipe-to-go-back navigation. Once there are some basic docs for it, I'd be happy to try them out and do edits/additions. I'd like to change as little as possible, so I'm particularly wondering whether there's a way to keep IR, and whether I have to use TypeScript? Thanks!

**Comment by Urigo** [comment]
codemill$1000

**Comment by Urigo** [comment]
@lorensr has been assigned to this task.

**Comment by Urigo** [comment]
thanks to @dotansimha we now have a full tutorial about this - http://www.angular-meteor.com/migration/angular2/intro

**Comment by lorensr** [comment]
Oh awesome, thanks @dotansimha – looks great 😊 Sorry I didn't get to this earlier
