### ISSUE TITLE
Socially - Step 20: graphicsmagick create 0 byte thumbnail

### ISSUE THREAD

**Issue by phucnv206** [Urigo/angular-meteor#1343]
Same problem when I clone and run latest version.

It works when transform without **gm**

`
transformWrite(readStream, writeStream, fileId, file) {
readStream.pipe(writeStream);
}
`

**Comment by kamilkisiela** [comment]
Do you have installed graphicsmagick or imagemagick? It won't work without it

**Comment by phucnv206** [comment]
Oops! I didn't read gm installation. Thank you @kamilkisiela 

Hope Angular-Meteor team will improve tutorial about this.
