### ISSUE TITLE
Inconsistent usage of helpers in tutorial

### ISSUE THREAD

**Issue by Ben305** [Urigo/angular-meteor#1344]
The API Reference for `helpers` contains the following sentence:
> Each value of the object must be a function that returns a Mongo.Cursor.

With this in mind, I was wondering when I was reading step 6 from the tutorial called "Bind one object". In that chapter, a single object called `party` that returns the result from a call to `Parties.findOne` is added to the helpers.

What's right and what's wrong now? Can we use helpers to return results from calls to `Collection.findOne` or should this happen in autorun?

**Comment by Urigo** [comment]
updated in the new version of the tutorial

**Comment by malaire** [comment]
This doesn't seem to be fixed. Page [1] is still using findOne in helpers.

[1] https://www.angular-meteor.com/tutorials/socially/angular1/bind-one-object
