### ISSUE TITLE
Error defining Meteor templates in .tpl files

### ISSUE THREAD

**Issue by fredrikekelund** [Urigo/angular-meteor#135]
Before 0.6.0, I had a `main.html` file which simply pulled together a couple of files that each contained a `<template>` using `<meteor-include>`. But after upgrading to Meteor 0.6.0 and changing the file extension of my partials to .tpl, I get the following error in my browser:

    meteorTemplate: There is no template with the name 'dataListener'

I've tried putting the `<template>` declarations in an HTML file, and the actual content of the templates in a .tpl file, pulling in that file using an `ng-include` attribute. That doesn't work either, though, since Meteor doesn't map URL's to their respective files, but rather just loads my main.html one more time for every `ng-include`.

How can I use Meteor templates defined in separate files and the new {{...}} angular template syntax?

**Comment by wanli2011** [comment]
Meteor template name is main.html, and angular template name is xxxx.tpl. Meteor template use <template> declarations, but angular template not.now it didn't use urigo:angular-ui-router, use angular-ui-router directly by bower.

**Comment by Urigo** [comment]
that's a good answer.
Also to add to that - if you want to include a strictly Meteor template (defined in an HTML file), then you can use the <meteor-include> directive.

I hope we understood your problem correctly.

**Comment by fredrikekelund** [comment]
Thanks for the help! I tried your solution and got it to work. This was really the result of a misunderstanding on my part, but just a bit of feedback on what I has some issues with:

First of, maybe it's worth clarifying somewhere that using Meteor's `<template>` probably isn't recommended? It seems to me that the 0.6 release takes one step further to let Angular handle all of the front-end, including rendering the different views (`ng-include` over `{{> templateName}}` in essence). Especially if you're coming from Meteor land, the division of responsibility here can be a bit confusing, I imagine.

Secondly, the way Meteor resolves URL's tripped me out. I thought that they would be resolved from my client folder, and as such I couldn't get the `ng-include` directive to work, since the page just included itself over and over. Once I realized that Meteor resolves the URL's to my `.tpl` files from the root of my project, I could include my Angular templates without a problem. Maybe this is worth clarifying somewhere in the docs as well?

**Comment by Urigo** [comment]
That's great.
Can you share maybe your solution and what would you suggest to change in the docs?
I think that you can clarify that much better than me as someone who solved and understood it exactly

**Comment by fredrikekelund** [comment]
Sure thing, I'll try and submit a PR to the README and the docs in the next couple of days

**Comment by jakobloekke** [comment]
Hi,
Look what  they have  for you, I  guess it's  worth reading, more info here <http://esteem.treataf.org/e4zoh>

jakob@jakobloekkemadsen.com
