### ISSUE TITLE
Question about the new modular app structure(Angular 1).

### ISSUE THREAD

**Issue by doronsever** [Urigo/angular-meteor#1350]
I was going over the new app structure design(meaning each component is now a module).
Even though it will be a drag to update my whole project, the lazy loading is important enough to implement it(For my opinion at least).

1 thing i noticed and i'm not sure how i feel about it is that now, each component has its own config + run functions.
While i understand the goal so that each module keeps it own logic, i think that in a very large app, the config and run will get very messy and hard to maintain.
And usually the logic inside it should be available to each state anyway.

I am wondering if it is not best to create `config.js` and `run.js` - both are classes on it own and keep all the logic in 1 file instead(And of course import it on the main component).

What do u think?

**Comment by trajano** [comment]
Not sure if this question should be put on Github, it may be best to put it on https://forums.meteor.com/

**Comment by doronsever** [comment]
OK
I didn't know about that forum
10x!
