### ISSUE TITLE
button or nav links not clickable on IOS 9.3

### ISSUE THREAD

**Issue by tomitbe** [Urigo/angular-meteor#1351]
Hi,
Started the tutorial of angular-meteor with version 1.3. As soon as we add ionic, none of the buttons are tappable on IOS 9.3 device: Once we double click (tap), the ng-click action is triggered... On android and in browser it still works fine. I guess it is a ionic related

**Comment by martinothamar** [comment]
Sort of duplicate from #1341 I guess, but I've experienced this problem as well. Can be temporarily avoided with Ionic's `on-release` instead of `ng-click`.

**Comment by tomitbe** [comment]
@martinothamar thank you for your quick reaction. I will try to replace all ng-click by on-releases; keep you posted on that.

**Comment by tomitbe** [comment]
@martinothamar the solution with on-release is perfect! thx

**Comment by tyrelltle** [comment]
hi on-release dosent work for me, my link is still not clickable on IOS device (have to double click). could you give example how to use on-release?

**Comment by tomitbe** [comment]
Hi Tian,

In view

<div class="tabs">
    <a class="tab-item" on-release="$ctrl.logCode()">
        Scan
    </a>

In controller

logCode() {
    var elem = this;
    BarcodeScanner
        .scan()
        .then(function(barcodeData) {
            // Success! Barcode data is here
            // alert(barcodeData.text);
            elem.addTask(barcodeData.text);
        }, function(error) {
            //var loc = new TodosListCtrl();
            elem.addTask('web');
            // An error occurred
        });
}

Van: Tian Shao <notifications@github.com<mailto:notifications@github.com>>
Beantwoorden - Aan: Urigo/angular-meteor <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: maandag 9 mei 2016 07:55
Aan: Urigo/angular-meteor <angular-meteor@noreply.github.com<mailto:angular-meteor@noreply.github.com>>
CC: Tom Van den Broek <contact@tom-it.be<mailto:contact@tom-it.be>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Onderwerp: Re: [Urigo/angular-meteor] button or nav links not clickable on IOS 9.3 (#1351)


hi on-release dosent work for me, my link is still not clickable on IOS device (have to double click). could you give example how to use on-release?

-

**Comment by tyrelltle** [comment]
@tomitbe Thanks! 
What about all the tabs? currently my tabs look like 
<ion-tabs class="bar-dark tabs-stable tabs-icon-top" ng-cloak>
  <ion-tab title="xxx" icon-on="ion-ios-star" icon-off="ion-ios-star-outline" href="#/tab/business">
    <ion-nav-view name="tab-business"></ion-nav-view>
  </ion-tab>
  <ion-tab title="xxx" icon-on="ion-ios-person" icon-off="ion-ios-person-outline" href="#/tab/setting">
    <ion-nav-view name="tab-setting"></ion-nav-view>
  </ion-tab>
</ion-tabs>

ng-click is not used here, and the tabs have the same problem (single click not working). how would you use on-release to fix that? should i replace href='xxx' with  on-release ?

Thanks!

**Comment by tomitbe** [comment]
Yes indeed, you need to use on-release instead of href as well.


@tomitbe<https://github.com/tomitbe> Thanks!
What about all the tabs? currently my tabs look like








ng-click is not used here, and the tabs have the same problem (single click not working). how would you use on-release to fix that? should i replace href='xxx' with on-release ?

Thanks!

-

**Comment by martinothamar** [comment]
Got a little bit of an update, got ng-click to work as usual.

I basically uninstalled `ionic-scripts` installed the official ionic-package for meteor instead.

```sh
meteor npm uninstall --save ionic-scripts
meteor add driftyco:ionic
```

![Console output](http://i.imgur.com/isXhCVA.png "Output")

After that you'll have to remove som lines from app.js to ensure you have no duplicates. 

My app.js looks like this: 

```js
// Libs
import { Meteor } from 'meteor/meteor';
import 'angular-meteor';
import 'angular-meteor-auth';
import '../../lib/ionic-calendar/js/calendar-tpls.min';
import '../../lib/ion-datetime-picker.min';

// Modules
import Definer from '../definer';
import { RoutesConfig, RoutesRunner } from '../routes';
import LoginCtrl from '../controllers/login.controller';
import MeetingsCtrl from '../controllers/meetings.controller';
import NewMeetingCtrl from '../controllers/newmeeting.controller';
import SlideDown from '../directives/slide-down';
import CalendarAlign from '../directives/calendar-align';
import HideInitially from '../directives/hide-initially';

// App
const App = angular.module('Flowit', [
  'angular-meteor',
  'ionic',
  'ngAnimate',
  'ui.rCalendar',
  'ion-datetime-picker',
  'angular-meteor.auth'
])
```

Tested this on iOS 9.3 simulator. Feedback appreciated.

**Comment by Furqankhanzada** [comment]
@martinothamar after lot of struggling i adopted your solution. working perfect but with this we can't use npm packages.

**Comment by dungthan** [comment]
`import angular from 'angular';
import angularMeteor from 'angular-meteor';
import uiRouter from 'angular-ui-router';
import ngSanitize from 'angular-sanitize';
import ngAnimate from 'angular-animate';
import 'ionic-sdk/release/js/ionic';
import 'ionic-sdk/release/js/ionic-angular';
import 'ionic-sdk/release/css/ionic.css';

import './carekid.html';
import { name as Login } from '../login/login';
import { name as Register } from '../register/register';
import { name as ForgetPassword } from '../forgetPassword/forgetPassword';
import { name as RequirementList } from '../requirementList/requirementList';

class Carekid {}

const name = 'carekid';

export default angular.module(name, [
	angularMeteor,
	uiRouter,
	ngAnimate,
	ngSanitize,
	Login,
	Register,
	ForgetPassword,
	RequirementList,
	'ionic'
]).component(name, {
	templateUrl: `imports/ui/components/${name}/${name}.html`,
	controllerAs: name,
	controller: Carekid
}).config(config);

function config($locationProvider, $urlRouterProvider) {
	'ngInject';

	$locationProvider.html5Mode(true);

	$urlRouterProvider.otherwise('/login');
}
`

I sample issue
angular-meteor tutorial 
using ionic-sdk 
please help me!

**Comment by abcd-ca** [comment]
Fixed the `<select>` `ng-change` bug. Added they keyboard plugin and did this, which gives us the 'done' button above the spinner.

```
.run([
	() => {
		if (window.cordova){
			console.log('** unhiding accessory bar');
			cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false);
		}
	}
]);
```

**Comment by der-ede** [comment]
Hi there,

just stumbled across this post. What fixed it for me was to
    meteor remove mobile-experience

since it includes `fastclick.js` which seems to get in the way of Ionic.

Regards

**Comment by DriesVandermeulen** [comment]
@der-ede Your my f***ing Hero! Big thank you!

The mobile-experience package includes 3 packages:
- fastclick: avoid the 300ms touch delay
- mobile-status-bar: avoid the status bar information covering up your app content
- launch-screen: cover the app with a launch image so that people don’t have to see things loading

After removing ```mobile-experience``` I have re-added the ```mobile-status-bar``` and ```launch-screen``.

**Comment by der-ede** [comment]
Ok, you're welcome.

Am Dienstag, 20. September 2016 schrieb Dries Vandermeulen :

**Comment by Urigo** [comment]
Fixed and deployed.
Please open a new issue if the new explanation on the tutorial is not working for you.
thank you so much @DriesVandermeulen

**Comment by der-ede** [comment]
And thx again @Urigo for the angular-meteor package.
