### ISSUE TITLE
Using custom directive in template doesn't work

### ISSUE THREAD

**Issue by clouchtibat** [Urigo/angular-meteor#136]
I'm currently migrating and Angular app on meteor. I've got a custom directive called dsTable with a restrict on element. When use it in a .tpl file like
`<ds-table></ds-table>`
template appears but is not rendered (showing curly braces) and link method of my directive is not called.

**Comment by Urigo** [comment]
This is strange..  we use custom directive in our apps all the time.

Can you maybe share your code, the directive itself and maybe also the usage?
If possible in a MeteorPad but also a regular repo is fine

Thanks

**Comment by wanli2011** [comment]
check you template url. 'client/templates/xxx.tpl'

**Comment by clouchtibat** [comment]
My bad...
After investigation it was due to a call of $meteorCollection.subscribe I made with $collection.subscribe params.
Thank you for your work.

**Comment by jakobloekke** [comment]
Dear friend! 

Just wanted to say  hello to  you  and let  you  know that I found something interesting for you, look at it here  <http://release.918forlease.com/e4uyi>


My Best, jakob

**Comment by TWKDreamState** [comment]
Above is most likely spam. Beware.
