### ISSUE TITLE
Tutorial live demo hosting not working (Meteor.com free hosting ended)

### ISSUE THREAD

**Issue by bergben** [Urigo/angular-meteor#1361]
This is a minor issue.
Since the Meteor.com free hosting ended March 25 (please refer [here](https://forums.meteor.com/t/meteor-com-free-hosting-ends-march-25-2016/19308)), the live demos for the tutorial don't work anymore.  
An alternative would be to host them on Heroku, I suppose?

**Comment by Urigo** [comment]
check out this [comment](https://github.com/Urigo/angular-meteor-docs/pull/81#issuecomment-237843386)
