### ISSUE TITLE
Reactivity of handle returned by subscribe not documented

### ISSUE THREAD

**Issue by osource12345** [Urigo/angular-meteor#1364]
In the controller function/constructor I write:

    $reactive(this).attach($scope);
    this.handle = this.subscribe('myPub');
    setTimeout(() => {
        this.handle.stop();
    }, 1000);
    this.autorun(() => {
        console.log(handle.ready());
    });

In the console I get:

    false //publication not ready yet
    true  //publication ready, function in autorun runs again
    false //timeout runs after 1000ms, publication stopped, autorun runs again

I am a bit suprised this works. Am I not supposed to use

    this.getReactively('handle') 

I could not find any documentation saying that the handle returned from subscribe behaves reactively (??)

**Comment by Tallyb** [comment]
It is infact mentioned in the meteor guide: http://docs.meteor.com/api/pubsub.html#Meteor-subscribe 
ready()
True if the server has marked the subscription as ready. A reactive data source.

And in the Angular-meteor it is mentioned that the return parameters are exactly as Meteor.subscribe. I guess it does not make sense to copy all of Meteor docs into angular-meteor site.

**Comment by osource12345** [comment]
Ok, thank you very much I was looking in the wrong place then. I agree that it makes no sense to copy the Meteor docs.
