### ISSUE TITLE
Socially - 3.3 3-Way data binding

### ISSUE THREAD

**Issue by Betrin13** [Urigo/angular-meteor#1365]
"3.3  Add some data to the parties collection"
I believe you have made a mistake in html? instead of "=>" you have "= & g t ;" (I have added a space inside of each because html tag actually produces results that are expected in the tutorial "=&gt;")
I am using windows 10, latest version of Google Chrome, however in my opinion that is totally unrelated because i have tried using Mozilla and Microsoft Edge. Also my friend tried opening page on a Mac and it had same results. This issue have caused quite a headache for me, because it break the code and causes babel error.
![image](https://cloud.githubusercontent.com/assets/10996124/15539811/7373877e-227c-11e6-833e-f6b4201ec64e.png)

http://www.angular-meteor.com/tutorials/socially/angular1/3-way-data-binding

**Comment by Tallyb** [comment]
https://github.com/Urigo/angular-meteor-docs/issues/123

**Comment by androniks** [comment]
Thanks, I didn't see it. Great

**Comment by Betrin13** [comment]
Thanks, great

**Comment by Tallyb** [comment]
@Betrin13  since there is an open issue in the docs repo, you may close this issue. Do you agree?
