### ISSUE TITLE
Help with "No provider for PlatformRef!"

### ISSUE THREAD

**Issue by slyerrr** [Urigo/angular-meteor#1367]
Im trying to add Mongo to angular2meteor application, after adding dependencies i have error in my chrome browser : 
reflective_injector.js:776Uncaught No provider for PlatformRef!

ReflectiveInjector_._throwOrNull	@	reflective_injector.js:776
ReflectiveInjector_._getByKeyDefault	@	reflective_injector.js:804
ReflectiveInjector_._getByKey	@	reflective_injector.js:767
ReflectiveInjector_.get	@	reflective_injector.js:576
createPlatform	@	application_ref.js:41
MeteorApp.bootstrap	@	meteor_app.js:22
bootstrap	@	bootstrap.js:9
meteorInstall.client.app.js	@	app.ts:45
fileEvaluate	@	install.js:141
require	@	install.js:75
(anonymous function)	@	parties.ts:4

What can be causing this ? 
some problems within typings folder ?

**Comment by mitjade** [comment]
I had a similar problem when trying to start a new angular2meteor application. I think it has something to do with angular2-meteor-auto-bootstrap. When I followed first 3 steps of the Angular 2.0 Meteor tutorial exactly, I did not get the error, but if I tried to run all "meteor npm install ..." dependencies in one line I got the same error.

**Comment by Urigo** [comment]
Should be fixed with latest versions.
If not please create a new issue on the angular2-meteor repo
