### ISSUE TITLE
cannot run two angular2 apps in parallel

### ISSUE THREAD

**Issue by mxab** [Urigo/angular-meteor#1368]
Hi,
just was working on an angular2 app, which I wanted to run on a different port then my other app. Unfortunately the app crashes
You can reproduce it when you checkout https://github.com/Urigo/meteor-angular2.0-socially two times and try to run it

```
git clone https://github.com/Urigo/meteor-angular2.0-socially socially1
git clone https://github.com/Urigo/meteor-angular2.0-socially socially2
cd socially1 && meteor npm i && cd ..
cd socially2 && meteor npm i && cd ..
```

Then start them both on different ports:
```
cd socially1 && meteor
cd socially2 && meteor --port 5000
```
```
/Users/bruchmann/.meteor/packages/barbatus_typescript/.0.2.11.1287iqp++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: UNKNOWN, readdir '/Users/bruchmann/temp/socially2/node_modules/rxjs/src/testing'
```

the path (here `.../node_modules/rxsj/...`) of the error seems random

In my real use case it is actually an meteor angular 1.3 and a meteor angular2 but this was the easiest way to reproduce it

**Comment by Tallyb** [comment]
I received a similar issue on angular1 as well. We did not intentionally run 2 apps, but a reboot resolved it, so I am assuming it was similar reason

**Comment by mxab** [comment]
hmm yes, looks like a restart solved this.
