### ISSUE TITLE
Things to fix/improve in Angular 1 tutorial

### ISSUE THREAD

**Issue by erperejildo** [Urigo/angular-meteor#1369]
Hi there! Thanks for this tutorials, there are really useful to learn Meteor  :)

I just finished the Angular 1 tutorial and there are a few parts to fix or improve. These is a list which I've created while I've been doing the tutorial so sorry if some parts are fixed (like > symbol), I started a few days ago:
- Explain at beginning of tutorial mobile development is not ready yet (it'd be in 11.1) because I thought I had a problem.
- 3.16: I couldn't work with urigo:static-templates, the view always was white (but with no problems), even downloading the next step zip.
- 6.1: We have to remove all parties which we added from console when we start to add parties from the app if not we got an undefined issue (sorry but I don't remember when or where).
- 8.7: We've got a problem if we added a party not being logged. This block of code would be better with this:

```
if (this.party.owner) {    
      this.party.owner = Meteor.user()._id;
}
```
- 9.4: This step was really confused to me. I had to download next zip. Could be better clarify this a little bit or separate it in more steps.
- 14.8: Mandrill package is not longer free: https://www.mandrill.com/pricing/
- 18: Error messages in login show them up with the full response. The mobile css is broken with Angular Material and you can't see the party detail properly (and further steps!).
- 18.11: At the end of code block we lose `</ui-gmap-google-map></div>`
- 18.20: Social icons not founds issue.
- 19: You said for Meteor 1.3: 

> if it possible you should always use packages from NPM instead of Atmosphere

but in [Meteor's guide](http://guide.meteor.com/atmosphere-vs-npm.html) we've got:

> Atmosphere packages are packages written specifically for Meteor and have several advantages over npm when used with Meteor
- 20 Image upload: This plugin doesn't work on mobile (at least on mine). I tried before [this library](https://github.com/Foliotek/Croppie) and works perfectly.
- 21 SMS: Maybe this fix the issue with okland:accounts-phone and Meteor 1.3 (couldn't try it because mobile css issue): https://github.com/okland/accounts-phone/issues/22
- Something related with Cordova plugins (at least a simple one) would be great.

Well and that's it. Hope this works  ;)

Thanks for the tutorial!

**Comment by Jabark** [comment]
Another one I found:
- 13.4: `return Meteor.users.findOne(owner) || 'nobody';` always returned 'nobody'. I had to add `this.subscribe('users');` to line 24

**Comment by DAB0mB** [comment]
@erperejildo Here's the status:

##### 3.16
    I couldn't work with `urigo:static-templates`, the view always was white (but with no problems), even downloading the next step zip.

  The view is white since there is no data to present unless you add some new data. Simply insert a new party document to the Parties collection.

##### 6.1
    We have to remove all parties which we added from console when we start to add parties from the app if not we got  an undefined issue (sorry but I don't remember when or where).

Had no issues with it what-so-ever.

##### 8.7
    We've got a problem if we added a party not being logged.

Fixed and deployed

##### 9.4
    This step was really confused to me. I had to download next zip. Could be better clarify this a little bit or separate it in more steps.

Refactored and deployed. Hopefully it satisfies you now.

##### 14.8
    Mandrill package is not longer free: https://www.mandrill.com/pricing/

Replaced with [EmailJS](emailjs.com). Hopefully will be depoloyed today.

##### 18
    Error messages in login show them up with the full response. The mobile css is broken with Angular Material and you can't see the party detail properly (and further steps!).

The mobile layout is broken indeed and needs to be fixed.

##### 18.11
    At the end of code block we lose </ui-gmap-google-map></div>

Issue doesn't exist.

##### 18.20
    Social icons not founds issue.

Already fixed.

##### 19
    You said for Meteor 1.3

    > if it possible you should always use packages from NPM instead of Atmosphere

    but in Meteor's guide we've got

    > Atmosphere packages are packages written specifically for Meteor and have several advantages over npm when used with Meteor

Refactored and deployed.

##### 20
    This plugin doesn't work on mobile (at least on mine). I tried before this library and works perfectly.

Havn't tested it on mobile yet.

##### 21
    Maybe this fix the issue with okland:accounts-phone and Meteor 1.3 (couldn't try it because mobile css issue): okland/accounts-phone#22

Already fixed.

**Comment by DAB0mB** [comment]
@Jabark The issue is already fixed.

**Comment by Urigo** [comment]
thank you for the great feedback @erperejildo and @Jabark !
