### ISSUE TITLE
Using Kendo UI with angular-meteor

### ISSUE THREAD

**Issue by longxuanho** [Urigo/angular-meteor#1370]
The Kendo UI library requires to include jquery and angular library first in the HTML header as:

```
<head>
    <title></title>
    <link rel="stylesheet" href="styles/kendo.common.min.css" />
    <link rel="stylesheet" href="styles/kendo.default.min.css" />
    <script src="js/jquery.min.js"></script>
    <script src="js/angular.min.js"></script>
    <script src="js/kendo.all.min.js"></script>
</head>
```

The question is, how can I use kendo UI with angular - meteor framework? Thanks.

**Comment by Urigo** [comment]
I know it's easy but can you document your solution for others?  thanks

**Comment by longxuanho** [comment]
I found the solution here:
http://guide.meteor.com/writing-atmosphere-packages.html

All I need is create an atmosphere package  and put the source code in. Then import using:

```
import 'your-username:your-package'

export default angular.module(name, [
   ...
    'kendo.directives',
   ...
]).component(name, {
    template,
    controllerAs: name,
    controller: Pandora
})
```

**Comment by Urigo** [comment]
why not just import from npm?

**Comment by longxuanho** [comment]
Kendo UI library requires a lot of CSS, images, and fonts that I can put in a single Meteor packages using: 
```
Package.onUse(function(api) {
   api.mainModule('my-package.js');
   api.addFiles('my-package.css', 'client');
   api.addAssets([
    'my-package-images.png',
    'my-package-webfont.svg',
    'my-package-webfont.ttf',
    'my-package-webfont.woff',
  ], 'client');
});
```

I don't know how to do it with npm. It would be nice if you could update the tutorial at http://www.angular-meteor.com/tutorials/socially/angular1/3rd-party-libraries

**Comment by Urigo** [comment]
makes sense because of the fonts, but know that you can import CSS from node modules with the latest Meteor
