### ISSUE TITLE
trying to follow the upgrade path advised by angular.io to use typescript with angular 1 then adding angular 2

### ISSUE THREAD

**Issue by anymos** [Urigo/angular-meteor#1374]
Following the advice in this page :https://angular.io/docs/ts/latest/guide/upgrade.html

I was trying to add type script to angular-meteor 1.x by using the some typescript compiler without success.

What would be the best course of action to do so, and eventually been able to use angular 1 and angular 2 inside the same meteor app client side at least ?

**Comment by kamilkisiela** [comment]
@anymos 

You can read ["Migration to Angular2"](http://www.angular-meteor.com/tutorials/socially/angular1/migration-to-angular2) chapter of Angular-Meteor tutorial.

I also made a video about it. You can check it [here](https://www.youtube.com/watch?v=3mtgDq4sB8Y).

Basically, if you want to switch from using raw JavaScript to use TypeScript and some of your controllers and services still use `ng-annotate` (which is included by default in `pbastowski:angular-babel`) you can use [`mys:typescript-ng-annotate`](https://atmospherejs.com/mys/typescript-ng-annotate). This is sort of a migration package that includes typescript compiler and ng-annotate so if you'll be fully ready to get rid of ng-annotate you could remove that package and just use `barbatus:typescript`.

Feel free to ask any question! :)

**Comment by anymos** [comment]
Good morning,

thank you very much for your answer, I did the tutorial so long ago that I didn t know that a part was already there for me regarding this :-) it s a reminder for me of  RTFM ... every month... ahhahaha

anyway, I have a little issue that puzzle me :

W20160610-08:16:38.178(7)? (STDERR) import { Meteor } from 'meteor/meteor';
W20160610-08:16:38.178(7)? (STDERR) ^^^^^^    
W20160610-08:16:38.180(7)? (STDERR) SyntaxError: Unexpected reserved word

I did not rename the file to ts, but doing it I am having the same error.

**Comment by anymos** [comment]
@kamilkisiela, Good morning, I have investiguated the issue a bit more and it sounds like the problem I am having is when .js and .ts are mixed together.

We have a huge code base, and my plan was to migration to ts some of the part incrementally, keeping other part in js. Which  I imagine would be the way everybody is going to try to do.

The problem is that if you mix js and ts I ve got some issue.

It might not be related to angular meteor so feel free to tell be if this is the case I will then close the issue.

You can reproduce the issue by using this repo : https://github.com/anymos/meteorAngularTypeScript
