### ISSUE TITLE
(offer of help in) Documentation Updates

### ISSUE THREAD

**Issue by bhk4** [Urigo/angular-meteor#1375]
First, let me say that, having run through the tutorial, the current information is exceptionally well laid out, and the technical work is amazing.

Beyond that, and without any pejorative meaning or any criticism of the existing content, I would like to offer my assistance in updating the documentation to clarify several grammatically confusing aspects as well as some instructional items that seem, to my mind, to be missing (specifically around areas where changes are being shown but should are not actually being made to the code) and simply need a bit more delineation as showcases rather than parts of the tutorial itself.

**Comment by bhk4** [comment]
PS - I know stackoverflow was a place for questions but this seemed the more appropriate location to me

**Comment by bhk4** [comment]
moving to meteor docs and submitting via forked pull request

**Comment by Urigo** [comment]
do you mean the angular-meteor.com website?
You can create PRs and issues for it here: https://github.com/urigo/angular-meteor-docs
