### ISSUE TITLE
Angular rc2 breaks dependencies

### ISSUE THREAD

**Issue by mitjade** [Urigo/angular-meteor#1376]
When trying to follow Angular 2.0 Meteor Tutorial I get an error when executing:
meteor npm install --save angular2-meteor @angular/platform-browser-dynamic

...
npm ERR! peerinvalid The package @angular/core@2.0.0-rc.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/common@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
npm ERR! peerinvalid Peer @angular/compiler@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
npm ERR! peerinvalid Peer angular2-meteor@0.5.5 wants @angular/core@2.0.0-rc.1

**Comment by nanomoffet** [comment]
I'm getting the same issue trying to install any new packages like the router.

npm install --save gives me missing dependency warnings for both platform-browser-dynamic and router, and meteor npm install errors out completely.

**Comment by mitjade** [comment]
Ups I realised I added this issue on wrong repository. It is relevant to Urigo/angular2-meteor.
Will post issue there.

**Comment by mitjade** [comment]
https://github.com/Urigo/angular2-meteor/issues/300
