### ISSUE TITLE
this command did not finish successfully on Win, meteor version 1.3.3.1 $ meteor npm install --save angular2-meteor @angular/platform-browser-dynamic

### ISSUE THREAD

**Issue by nickprusov** [Urigo/angular-meteor#1380]
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\nick\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.3_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe" "C:\\Users\\nick\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.3_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "angular2-meteor" "@angular/platform-browser-dynamic"
npm ERR! node v0.10.45
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/core@2.0.0-rc.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/common@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
npm ERR! peerinvalid Peer @angular/compiler@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
npm ERR! peerinvalid Peer angular2-meteor@0.5.5 wants @angular/core@2.0.0-rc.1

npm ERR! Please include the following file with any support request:
npm ERR!     c:\projects\leapfrog\socially\npm-debug.log

**Comment by NOaMTL** [comment]
check [this](https://github.com/Urigo/angular2-meteor/issues/301)

**Comment by Urigo** [comment]
should be fixed with the latest versions
