### ISSUE TITLE
Lifecycle hooks not called in navigation.

### ISSUE THREAD

**Issue by ittechsathish** [Urigo/angular-meteor#1382]
The issue clearly logged by many at https://github.com/angular/angular/issues/4809.

I'm also having this issue in my meteor project. It seems we need to change the order of loading the polyfill files, but I don't know how to fix this in meteor app.

Please help me.

**Comment by kamilkisiela** [comment]
This should be submitted on [Urigo/angular2-meteor](http://github.com/Urigo/angular2-meteor/issues/new). 

You can change the loading order by changing the order of `import` statements or `require` or whatever you're using.
You can also use [`angular2-meteor-polyfills`](http://npmjs.com/package/angular2-meteor-polyfills).
