### ISSUE TITLE
How to use angular-meteor-auth from NPM?

### ISSUE THREAD

**Issue by sebakerckhof** [Urigo/angular-meteor#1383]
I gradually want to upgrade our current meteor (1.2) app to ES6 modules and I hope to use as much from NPM instead of atmosphere as possible.
I'm testing out some strategies, but I can't seem to make angular-meteor-auth from NPM working.

Here's a little test repo:
https://github.com/sebakerckhof/ngmeteor13test

If I install angular-meteor-auth from npm and import it like https://github.com/sebakerckhof/ngmeteor13test/blob/master/imports/ui/app/app.component.js#L4

I get an error from the angular-meteor-auth code about `this.autorun` not being defined.

**Comment by sebakerckhof** [comment]
@Urigo Any idea?

**Comment by mxab** [comment]
@sebakerckhof do you have a stacktrace to the this.autorun not define message?

**Comment by sebakerckhof** [comment]
@mxab For some reason the developer tools doesn't give me a stack trace. However, the error originates from this line: https://github.com/Urigo/angular-meteor-auth/blob/master/dist/angular-meteor-auth.js#L90

Anyway, you don't need to do anything special to trigger it. If you just clone & run the repo mentioned above, you should see it directly when you navigate to the running app.

**Comment by sebakerckhof** [comment]
Actually, if I manually set a breakpoint I can get a stacktrace:
```
$$Auth (angular-meteor-auth.js:90)
(anonymous function) (angular-meteor.js:1756)
meteorInstall.node_modules.angular-meteor.dist.angular-meteor.js.angular.module.service._construct (angular-meteor.js:1755)
(anonymous function) (angular-meteor.js:1738)
meteorInstall.node_modules.angular-meteor.dist.angular-meteor.js.angular.module.service.mixin (angular-meteor.js:1737)
(anonymous function) (angular-meteor-auth.js:204)
invoke (modules.js?hash…1ba96295c:5415)
(anonymous function) (modules.js?hash…1ba96295c:5223)
forEach (modules.js?hash…1ba96295c:1018)
createInjector (modules.js?hash…1ba96295c:5223)
doBootstrap (modules.js?hash…1ba96295c:2455)
bootstrap (modules.js?hash…1ba96295c:2476)
onReady (main.js:7)
fire (jquery.js:3143)
fireWith (jquery.js:3255)
ready (jquery.js:3467)
completed (jquery.js:3498)
```

**Comment by Urigo** [comment]
@sebakerckhof looks like we are using it here: http://www.angular-meteor.com/tutorials/whatsapp/ionic/authentication
does it happen there as well?

**Comment by Urigo** [comment]
like, the bundle from `bower` works for you?

**Comment by sebakerckhof** [comment]
@Urigo Well that's bower in a webpack project... I'm talking about a Meteor project where I'm trying to move away from atmosphere packages as much as possible towards npm packages...

Please see the example repo: https://github.com/sebakerckhof/ngmeteor13test

**Comment by DAB0mB** [comment]
Over here https://github.com/sebakerckhof/ngmeteor13test/blob/master/imports/ui/app/app.component.js#L31 you need to load `angular-meteor` before loading `angular-meteor-auth` since `angular-meteor-auth` is dependent on some `angular-meteor` internals.

**Comment by sebakerckhof** [comment]
@DAB0mB Thanks, that indeed seems to solve the issue. However, shouldn't the module dependencies be so that the order in which I put them doesn't matter? I mean if `angular-meteor-auth` specifies all the dependencies it needs.

**Comment by DAB0mB** [comment]
@sebakerckhof It actually makes sense because there are some run blocks which should be invoked in the right order. Like, you can't load angular modules without loading angular first, am I right? Same thing for `angular-meteor` and `angular-meteor-auth`, an extension can't be applied without the core library being loaded first. Anyways if that's the issue, I don't find it critical, but whatever @Urigo decides.

**Comment by sebakerckhof** [comment]
Okay. I thought angular invoked the run blocks bottum up acvording to the dependency graph, but apparently not. Closing as it's a user error.
