### ISSUE TITLE
angular-ui-router issue.

### ISSUE THREAD

**Issue by ArnaudRib** [Urigo/angular-meteor#1384]
Hey guys,

I've tried everything, but still, i'm stuck during the Whatsapp application tutorial : 

I had some UNMET PEER DEPENDENCY, which i fixed with sudo meteor npm i [every packages that are imported in app.js].

It worked fine for angular, angular-animate, angular-ecmascript, angular-sanitize.

However, for angular-ui-router, the terminal reads :
 
$ sudo meteor npm i angular-ui-router

"
whatsapp@ /path/whatsapp
├── angular@1.5.7 
├── angular-animate@1.5.7  extraneous
├── angular-ecmascript@0.0.3  extraneous
├── angular-sanitize@1.5.7  extraneous
└── UNMET PEER DEPENDENCY angular-ui-router@0.3.1
npm WARN ionic-scripts@0.0.1 requires a peer of angular-ui-router@^0.2.13 but none was installed.
"

I tried to uninstall ionic-scripts, installing angular-ui-router, and installing back ionic-scripts, but it shows the same issue.

Could anyone help me to fix this? 

Thanks.

**Comment by acolpitts** [comment]
+1

**Comment by ArnaudRib** [comment]
Hey man!

That's what I did yesterday!
And it seemed to have worked indeed. It is weird because it now reads "Invalid", but still it's working.

Thanks again :).

**Comment by DAB0mB** [comment]
@ArnaudRib A peer dependency is a dependency that is required by another package to be installed directly in your project. If a peer dependency is not installed your your application will still start, but it is not guaranteed to run properly. The peer dependency your'e currently looking at is required by `ionic-scripts` which means that it haven't been updated for quiet a while.

**Comment by DAB0mB** [comment]
@ArnaudRib I just released a new version of `ionic-scripts` and the problem should be fixed. @Urigo this issue can be closed.

**Comment by Urigo** [comment]
great.
please open another issue if the problem persist
