### ISSUE TITLE
use of templatesUrl results in 404

### ISSUE THREAD

**Issue by jeroensmeets** [Urigo/angular-meteor#1391]
After updating angular-templates to 1.0.5, every template is 404-ing in my working application. Going back to version 1.0.3 the errors are gone and the application loads correctly.

My templates are grouped by function, e.g.:

```
subscription/controllers
subscription/views
```

Part of my config:

```
angular.module("app").config( function ( $urlRouterProvider, $stateProvider, $locationProvider ) {

	$locationProvider.html5Mode(true);

	$stateProvider
		.state('home', {
			url: '/home',
			templateUrl: 'client/static/views/home.ng.html',
			controller: 'HomeCtrl'
		})
		.state('subscribe', {
			url: '/abonnement',
			templateUrl: 'client/subscription/views/subscribe.ng.html',
			controller: 'SubscribeCtrl'
		})
```

**Comment by Ben305** [comment]
Seems to be the same problem like #1390 

cc @kamilkisiela @Urigo

**Comment by jeroensmeets** [comment]
@Ben305 yes, I know, thx for adding the reference. Your remark is specific for packages and didn't want to take over with a related observation.

**Comment by Urigo** [comment]
we are on it, in the meantime please pin the previous version

**Comment by kamilkisiela** [comment]
@jeroensmeets Should be fixed by #1393

**Comment by otporsad** [comment]
There seams to be a problem with atmosphere package:
```
$ meteor add angular-templates    

 => Errors while adding packages:

While checking for angular-templates@1.0.6:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

```

**Comment by jeroensmeets** [comment]
@kamilkisiela @Urigo thanks so much!

**Comment by Urigo** [comment]
the newest version is `1.0.6_1`
https://atmospherejs.com/meteor/angular-templates
