### ISSUE TITLE
Docs: "Improve this doc" button doesn't work

### ISSUE THREAD

**Issue by lorensr** [Urigo/angular-meteor#1395]
cc @dotansimha 

http://www.angular-meteor.com/migration/angular2/intro

![image](https://cloud.githubusercontent.com/assets/251288/17035873/c6c21172-4f57-11e6-8fe1-a71ad95c5eca.png)

**Comment by Urigo** [comment]
fixed and deployed

**Comment by Urigo** [comment]
thanks for the heads up @lorensr
