### ISSUE TITLE
ng-include not working

### ISSUE THREAD

**Issue by Ben305** [Urigo/angular-meteor#1398]
This is for @kamilkisiela (as follow up to our discussion yesterday in https://github.com/Urigo/angular-meteor/pull/1397)

It seems that ng-include doesn't work correctly any longer. I have updated my sample at https://github.com/Ben305/AngularTemplatesSample

**Comment by kamilkisiela** [comment]
@Ben305 Try to add `/` before `imports/.../...` in ngInclude.

I'm not sure if this requirement of forward slash inside ngInclude is a bug or it suppose to be that way. Correct me if I'm wrong.

**Comment by Ben305** [comment]
@kamilkisiela There seems to be a breaking change between version `1.0.3` and `1.0.7`

With `1.0.3` ng-include only works without a leading `/` before file name
With `1.0.7` ng-include only works with a leading `/` before the filename

**Comment by feketegy** [comment]
Also, I'm running 1.0.7. and still need to manually import the html templates one by one with `import ../imports/components/test.html` ... 

Without the static imports the `ng-include` directive doesn't work

**Comment by kamilkisiela** [comment]
@feketegy It's in `/imports`, it's lazy loaded by Meteor.

**Comment by feketegy** [comment]
@kamilkisiela I missed that, thanks!
