### ISSUE TITLE
Uncaught TypeError: data is not an Blob or File in Meteor 1.4

### ISSUE THREAD

**Issue by isibz** [Urigo/angular-meteor#1406]
I'm working with the step 20 of the tutorial angular 1. When i updated the meteor version to 1.4 the functionality to upload an image throws an error:

> ufs-uploader.js:44 Uncaught TypeError: data is not an Blob or FileUploadFS.Uploader @ ufs-uploader.js:44(anonymous function) @ methods.js:23reader.onload @ helpers.js:44

I don't know if its a problem of the package UploadFS or something inside the tutorial code

thanks,

**Comment by isibz** [comment]
Sorry

UploadFS.readAsArrayBuffer() is DEPRECATED -- I close the Issue

**Comment by GbalsaC** [comment]
If anyone comes here with same issue, follow:
https://github.com/jalik/jalik-ufs#breaking-changes

**Comment by Urigo** [comment]
should we update the tutorial or it's already updated?

**Comment by jocelyn19** [comment]
Hi, not yet corrected, just doing the tutorial, got the same error while trying to upload a file.
Can someone fix it?

Thanks

**Comment by fidelsam1992** [comment]
Hello,
The tutorial is not updated yet.
I have tried to make it work, but the size of the uploaded images inside the collections appear to be 0.

Please support this issue.
