### ISSUE TITLE
Cannot get FileReader events working with angular-meteor and cordova-plugin-file

### ISSUE THREAD

**Issue by tlambeir** [Urigo/angular-meteor#1407]
I'm trying to get a base64 encoded string from an image on my android phone using this code

```
resolveLocalFileSystemURL(pathToFile, function(fileEntry) {
            fileEntry.file(function(file) {
                var reader = new FileReader();
                reader.onloadend = function(event) {
                    // this event does not fire
                    console.log(event.target.result);
                };
                reader.readAsDataURL(file);
            },function(error) {
                console.log(error);
            });
        },function(error) {
            console.log(error);
        });
```

However the reader.onloadend call is not firing, also none of the other filereader events are bing triggerd.

I've set up my project using the angular2 meteor tuturial step 1: http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping

After that I added the plugin cordova-plugin-file@4.2.0

Could it be that one of the packages in angular-meteor is overwriting the FileReader events somehow?

**Comment by Urigo** [comment]
Please try the `bindToContext` function - https://www.angular-meteor.com/api/1.3.11/reactive-context

Please re-open the issue and tag me if it didn't solve it for you
