### ISSUE TITLE
Socially Example Unavailable

### ISSUE THREAD

**Issue by Icey88** [Urigo/angular-meteor#1408]
Unable to view the Socially example link given in the tutorial located here:
http://www.angular-meteor.com/tutorials/socially

URL in question:
http://socially-step22.meteor.com/

Error:
This site can’t be reached

socially-step22.meteor.com’s server DNS address could not be found.

**Comment by GustavoSaudade** [comment]
I have same problem. 
I need to start the tutorial, but whithout a example is more difficult.

**Comment by Urigo** [comment]
check out this [comment](https://github.com/Urigo/angular-meteor-docs/pull/81#issuecomment-237843386)
