### ISSUE TITLE
Unable to get Socially app working on iOS and Android simulators - stuck on Loading... 

### ISSUE THREAD

**Issue by cesargalindo** [Urigo/angular-meteor#1409]
I downloaded the following Socially tutorials on August 4th, 2016.

meteor-angular2.0-socially-step_18
meteor-angular2.0-socially-step_21
meteor-angular2.0-socially-step_22

All the web views work fine when launching with
> meteor

However when launching the iOS or Android simulators, it appears to get stuck on the "Loading ..." screen. See attached screen shots.
![meteor-android](https://cloud.githubusercontent.com/assets/1699810/17411239/639b7b58-5a2c-11e6-88a0-26eee656d591.png)
![meteor-ios](https://cloud.githubusercontent.com/assets/1699810/17411240/639c0514-5a2c-11e6-928b-2622370262e3.png)

> meteor run ios
> meteor run android

I'm running this locally on my Mac.  I've cleared out all my simulation data, rebooted my machine etc., updated all components to latest versions, etc.., but nothing seems to work.

**Comment by Urigo** [comment]
the tutorial was updated and deployed.
Please open another issue if it doesn't work for you
