### ISSUE TITLE
update failed: MongoError: '$unset' is empty.

### ISSUE THREAD

**Issue by catsoft** [Urigo/angular-meteor#141]
I'm getting this error with $meteorObject on mongodb v.2.6.5
<code>update failed: MongoError: '$unset' is empty. You must specify a field like so: {$mod: {<field>: ...}}</code>
btw in my developer machine everythings works fine.
Am I doing something wrong or is this an issue ?

**Comment by Urigo** [comment]
I think Meteor officially support only mongodb 2.4 as of today.
But maybe I'm wrong?

**Comment by catsoft** [comment]
I found the problem.I was using the "zimme:collection-softremovable" package.I removed it and problem solved. But somehow angular-meteor and softremovable conflicts. I did not dig the issue because I can do with other ways what softremovable does. angular-meteor works perfectly with  mongodb v.2.6.5 and above. You can close this issue.

**Comment by Urigo** [comment]
How did you use Mongo 2.6.5?
Do you use the search option it has?

**Comment by catsoft** [comment]
Not yet bu I thinking about it.Just trying to figure out that  really need to use it on my project.I am using it for oplog tailing actually.

**Comment by catsoft** [comment]
I have another problem after your last release. I think it comes with .tpl extension. The browser caches views and I have to clear browser cache manually after every change of my html code. Do you know how can I solve this ?

**Comment by Urigo** [comment]
Closing
