### ISSUE TITLE
templateUrl in directives/components using the old style syntax.

### ISSUE THREAD

**Issue by TWKDreamState** [Urigo/angular-meteor#1410]
I have an existing app that I have been working on but I'm coming up with a 404 error on templates. I will eventually upgrade to the modular type environment, but right now I would prefer to continue with my app 'as is' due to time constraints.

Error: [angular-meteor][err][404] client/home/home.view.html - HTML template does not exists! You can disable this error by following this guide http://www.angular-meteor.com/api/1.3.11/templates

I'm on the latest version of everything AFAIK.

I am still learning Angular, Meteor, etc, so I may have made an elementary mistake somewhere. Indeed, any hints on better coding will be welcome.

I've (hopefully) uploaded an example of the error here...

https://github.com/TWKDreamState/templateUrl

If it's missing anything, please let me know.

For me, no matter what I change templateUrl to, it simply produces this error, whereas previously I did not have any issues. This has been referenced in a few other places but the latest angular-templates does not fix this for me.

https://github.com/Urigo/angular-meteor/pull/1397

https://github.com/Urigo/angular-meteor/issues/1391

Any help/thoughts would be appreciated.

**Comment by kamilkisiela** [comment]
#1412 Should fix it

**Comment by TWKDreamState** [comment]
Brill. Thank you for this. I'll wait for the merge.

I started to move towards 'modularising' my app but this will help a great deal during the changeover.
