### ISSUE TITLE
Whatsapp Clone with angular-meteor and Ionic step 2.4 helpers

### ISSUE THREAD

**Issue by EdineraWeb** [Urigo/angular-meteor#1413]
I have been following this tutorial step by step, and after bypassing the issue with angular-templates, yet I run into another issue. When declaring collections for chats and messages, first of all, Meteor does not load startup function, therefore does not load messages and chats into respective collections. 

Yet another issue I have is when trying to bind helper to `this`, I get the error `Unresolved method or function helpers()`. 

I'm using Meteor 1.4.0.1

here are the packages: 

`
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
reactive-var            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

autopublish             # Publish all data to the clients (for prototyping)
insecure                # Allow all DB writes from clients (for prototyping)
angular-templates
dab0mb:ionic-assets
fourseven:scss`

Issue is here: 

`import { Controller } from 'angular-ecmascript/module-helpers';
import { Chats } from '../../../lib/collections';

export default class ChatsCtrl extends Controller {
    constructor() {
        super(...arguments);

```
    this.helpers({
        data() {
            return Chats.find();
        }
    });
}


remove(chat) {
    this.data.remove(chat);
}
```

}`

**Comment by DAB0mB** [comment]
@EdineraWeb Make sure you import `angular-meteor` and that you load it using `angular`'s module system, then make sure you use the `$reactive` service which will provide you with the `helpers()` function. It should look like so:

```js
import angular from 'angular';
import 'angular-meteor';
import 'angular-ui-router';

angular.module('myApp', ['angular-meteor', 'ui.router'])
  .config(function ($stateProvider, $locationProvider) {
    $locationProvider.html5Mode(true);

    // logic
  });

function StateController($reactive, $scope) {
  $reactive(this).attach($scope);

  // logic
}
```

About Meteor not being loaded, please share your code by uploading it into a repo so I can help you.

**Comment by Urigo** [comment]
@EdineraWeb I'm closing for now, please open a new issue if the updated tutorial is not working for you
