### ISSUE TITLE
Support Angular 2 RC 5 Bootstrap (NgModule)

### ISSUE THREAD

**Issue by aaronroberson** [Urigo/angular-meteor#1417]
Angular 2 Release Candidate 5 contains a breaking change on how the app is bootstrapped. They've introduced `NgModule`. Several of the `ApplicationRef` methods have been deprecated (see https://github.com/angular/angular/blob/master/CHANGELOG.md#bootstrap-changes).

Please update `angular2-meteor-auto-bootstrap` to play well with NG2RC5 and `NgModule`.

**Comment by Hongbo-Miao** [comment]
@aaronroberson 
I think it is updated to RC5. Check the [readme file](https://github.com/Urigo/angular2-meteor).

Next time, please go to [angular2-meteor](https://github.com/Urigo/angular2-meteor) to report if you met any issue. Thanks

**Comment by Urigo** [comment]
We've just published new versions that support the latest stable Angular 2.0 and updated the Socially 2.0 tutorial.
Please try it out and open a new issue if you find any
