### ISSUE TITLE
Proper way to use 2 helpers eachother

### ISSUE THREAD

**Issue by erperejildo** [Urigo/angular-meteor#1418]
I've got one helper which has data from my collection `Food`:
```
// helper
food() {
        return Food.find({}, {
          sort : this.getReactively('sort')
        });
      }
```
And I've got a `ng-repeat` in my view to show this data. One of the fields is `owner` which is the user's id.
I've got another function to get the user avatar with the id (but I'm not sure if the correct way would be a function or another helper):
```
// function
getAvatar(id) {
    console.log(id);
    var query = Meteor.users.findOne(id, {fields: {avatar: 1} });
    return query.avatar;
  }
```
In `ng-repeat:`
```
<div class="plate-name">{{plate.name}}</div>
<div class="user-avatar">{{foodList.getAvatar(plate.owner)}}</div>
```

Is this the correct way? The result is ok but the `console.log` is called more than **100 times!** with 6 images. So, I understand something is not ok despite of all (I've removed the sort and is not that).

**Comment by DAB0mB** [comment]
@erperejildo can you please upload an example repo? Something simple that will reproduce the issue

**Comment by DAB0mB** [comment]
I opened a repo which reproduces this problem https://github.com/DAB0mB/ng-meteor-food-issue. Anyone who's willing to take on this issue your'e more than welcome.

**Comment by DAB0mB** [comment]
Ok after running the same scenario without using `angular-meteor` it resulted with the same result. I internet is full of issues like these and apparently it's normal, it's just how `angular` works. Any time a digestion loop runs it forces the watchers to update their states, so it depends how many models are bounded to your view, how long your list is, you can read the following article https://daveceddia.com/controller-function-executed-multiple-times/. You can call the function during the controller initialization which will reduce the amount of invocations dramatically, instead of using it inside the view. Use the following code instead:

```js
import angular from 'angular';
import 'angular-meteor';
import 'angular-ui-router';
import {Meteor} from 'meteor/meteor';
import {Food} from '../imports/collections';

angular.module('myApp', ['angular-meteor', 'ui.router'])
  .config(function ($stateProvider, $locationProvider) {
    $locationProvider.html5Mode(true);

    $stateProvider.state('food', {
      url: 'food',
      template: `
        <h2>List</h2>
        <div ng-repeat="plate in foodList.food">
          <div class="plate-name">name: {{plate.name}}</div>
          <div class="user-avatar">avatar: {{plate.avatar}}</div>
        </div>
      `,
      controller: StateController,
      controllerAs: 'foodList'
    });
  });

function StateController($reactive, $scope) {
  $reactive(this).attach($scope);

  this.helpers({
    food() {
      return Food.find({}, {
        transform: (plate) => {
          const user = Meteor.users.findOne(plate.owner, {
            fields: {'profile.avatar': 1}
          });

          plate.avatar = user.profile.avatar;

          return plate;
        }
      });
    }
  });
}
```

Please tell me if that answered you question :-)

**Comment by erperejildo** [comment]
@DAB0mB thanks for your huge answer and explanation!
The url was this one: http://foodapp-88007.onmodulus.net/food (the deploy was another complicated step to figure out).

At the end I understood (or assumed) that I cannot use functions in any loop at all because it doesn't work as expected.

In my case what I tried to use was more related with this:
https://forums.meteor.com/t/proper-way-to-use-2-helpers-eachother/28311

Thanks again!
