### ISSUE TITLE
Should I need $scope.$apply() ?

### ISSUE THREAD

**Issue by mackbrowne** [Urigo/angular-meteor#1420]
I'm using a plugin (edgee:slingshot) and to upload files it has a client side method that uses a callback.  I'm familiar with how in vanilla angular, you'd have to call `$scope.$apply()` for the dom to update.  Using `$scope.$apply()` was the only way i could get the dom to refresh `this.question` on the screen.  Otherwise the change will not display in the dom and my ng-show and ng-hide tags in the html won't trigger.

`
    uploader.send(image, (error, downloadUrl) => {
      if (error) {
        // Log service detailed response.
        console.error('Error uploading', uploader.xhr.response);
        alert(error);
      } else {
        console.log('uploaded image to s3')
        this.question.image = downloadUrl;
        this.$scope.$apply();
      }
    });
`

Is this the best way to do things?  Am I missing a autorun method or something else possibly?

**Comment by santiq** [comment]
Yes you could do that, but there is a better way.

When you perform async operations, you can bind the context of the callback function with $reactiveContext.

For example

```javascript
Accounts.forgotPassword({ email: this.email }, this.$bindToContext(err => {
    //  ... Here your callback logic ...
}));
```

In your case 

```javascript
 $reactive(this).attach($scope);
```

```javascript
 uploader.send(image, this.$bindToContext( (error, downloadUrl) => { 
 	if (error) {
	 // Log service detailed response.
	  console.error('Error uploading', uploader.xhr.response);
	  alert(error);
	 } else {
	  console.log('uploaded image to s3')
	   this.question.image = downloadUrl;

	   // You can delete this
	   // this.$scope.$apply(); 
	} 
}));
```

You can read the docs here

http://www.angular-meteor.com/api/1.3.6/reactive-context

**Comment by Urigo** [comment]
thanks for the great answer @santiq
