### ISSUE TITLE
stuck at Extracting angular-templates@1.0.9 after updating Meteor to 1.4.1.1

### ISSUE THREAD

**Issue by tlambeir** [Urigo/angular-meteor#1421]
When trying to add the angular templates to my meteor project it gets stuk and just keeps spinning at:

**Extracting angular-templates@1.0.9...** 

I don't seem to be getting an error.

**Comment by stefanholzapfel** [comment]
Look at my comment at
https://github.com/meteor/meteor/issues/7688

**Comment by kamilkisiela** [comment]
@tlambeir Have you tried @stefanholzapfel 's solution?

**Comment by Urigo** [comment]
Looks like it's solved inside and linked issue.
@tlambeir if I'm wrong, please open a new issue, thanks
