### ISSUE TITLE
This project has been canceled?

### ISSUE THREAD

**Issue by lednhatkhanh** [Urigo/angular-meteor#1422]
- Doesn't work with Meteor 1.4
- Doesn't work with Angular 2 RC5
- The last commit was more than 15 days ago.

**Comment by Tallyb** [comment]
August syndrome...

**Comment by mackbrowne** [comment]
Working for me...

I've had my growing pains, but this issues section has been ultra-helpful.

Meteor 1.4.1.1 and angular1 here.

I tried the angular2 version a few weeks ago, seemed to work fine.

**Comment by Hongbo-Miao** [comment]
@lednhatkhanh

This is Angular1-Meteor place.
If you met any issue, please report at [angular2-meteor](https://github.com/Urigo/angular2-meteor)

**Comment by lednhatkhanh** [comment]
Oh, sorry, gonna close this now.
