### ISSUE TITLE
Mongo.Collection.get is not a function (Meteor 1.4+, angular-meteor 1.3.11)

### ISSUE THREAD

**Issue by leosco** [Urigo/angular-meteor#1423]
I recently upgraded one of my angular-meteor apps to Meteor 1.4.1.1 and angular-meteor 1.3.11, which is the latest release. Most of my code runs on the angular-meteor 1.2.x API, which is stated in your docs at http://www.angular-meteor.com/api/1.2.0/meteorCollection as "deprecated since 1.3 and will be removed at 1.4". Has the legacy API already been removed before the 1.4 release? If not, does Meteor 1.4+ not support angular-meteor at this time? Should I downgrade to 1.3?

I've attached the error logs for your review. 

[localhost-1473207657712.txt](https://github.com/Urigo/angular-meteor/files/458041/localhost-1473207657712.txt)

I've also attached a small snapshot of the source code it's from. 

[amSnap.txt](https://github.com/Urigo/angular-meteor/files/458053/amSnap.txt)

Thanks in advance for any advice/help :)

**Comment by Urigo** [comment]
the old API should work, we decided not to deprecate it even though it's not the recommended way.
So probably your errors are not related to that.
Can you maybe share a reproduction?

**Comment by leosco** [comment]
Haha thanks for responding :)
I ended up migrating to the new API. It does work much better. Great job!

**Comment by Urigo** [comment]
ok great, closing for now, if someone get the same error please open a new issue
