### ISSUE TITLE
Meteor 1.4.1.1 thrown error when add angular templates

### ISSUE THREAD

**Issue by wandyatmono** [Urigo/angular-meteor#1424]
/home/xxx/.meteor/packages/meteor-tool/.1.4.1_1.1l5666a++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-14c7sa8/os.json'
    at Error (native)

**Comment by shakealot** [comment]
I can't even start the Angular2 Socially tutorial. Isn't it compatible with meteor 1.4 ?

**Comment by kamilkisiela** [comment]
Could you create a repository with reproduction?

I tried to reproduce this issue but no luck.

**Comment by Urigo** [comment]
We've updated yesterday the Socially 2.0 tutorial to the latest Angular 2.0 stable.
Please try it again with the latest package versions and Meteor versions and if it does not work please open a new issue.
Sorry it took a while.
