### ISSUE TITLE
https://github.com/bsliran/angular2-meteor-base not work for me. 

### ISSUE THREAD

**Issue by inromualdo** [Urigo/angular-meteor#1428]
Can i use meteor angular 2 from scrash. meteor create, install dependencies and so one...

When i clone the repo, meteor npm install end metro, it throws this error: /Users/mac/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/var/folders/v0/bzh15d2n24vfzqzp9fzrnr700000gn/T/mt-qi6wj/os.json'
    at Error (native)

**Comment by Tallyb** [comment]
you should open angular 2 meteor issues here: https://github.com/Urigo/angular2-meteor

**Comment by mxab** [comment]
@Tallyb actually it looks like the angular2-meteor is merged in this repo

**Comment by Tallyb** [comment]
@mxab  - apparently yes, that was the lerna fix...

**Comment by Urigo** [comment]
We've just published new versions that support the latest stable Angular 2.0 and updated the Socially 2.0 tutorial.
Please try it out and open a new issue if you find any
