### ISSUE TITLE
Start to Full App tutorial doesn't work at step 0.

### ISSUE THREAD

**Issue by eliehamouche** [Urigo/angular-meteor#1437]
Hello

I've been trying to do the first meteor-angular tutorial.
Followed all the steps but I can't finish step 0.
On the browser it's stuck at ...Loading
and I get a console error: 

decorators.js:173Uncaught reflect-metadata shim is required when using class decorators

I saw a similar issue that was closed due to an update but this doesn't. 
Please help. I really want to learn this but I can't get past step 0.

Meteor packages:
```
meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.12                   # The database Meteor supports right now
reactive-var@1.0.10            # Reactive variable for tracker
jquery@1.11.9                  # Helpful client-side library
tracker@1.1.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.2.0   # CSS minifier run for production mode
standard-minifier-js@1.2.0    # JS minifier run for production mode
es5-shim@4.6.14                # ECMAScript 5 compatibility for older browsers.

autopublish@1.0.7             # Publish all data to the clients (for prototyping)
insecure@1.0.7                # Allow all DB writes from clients (for prototyping)
angular2-compilers@0.6.1
practicalmeteor:mocha
xolvio:cleaner
hwillson:stub-collections
dispatch:mocha-phantomjs
shell-server
```

tsconfig.json: 
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "isolatedModules": false,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "removeComments": false,
    "noImplicitAny": false,
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false
}
```

**Comment by slippyC** [comment]
Something is wrong with bootstrap.

Here is code from where I posted over at angular2-meteor branch.  Just use this instead in your /client/main.ts file instead for now...

Also you will need to do meteor add barbatus:angular2-polyfills.

`
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

//This points to your first component. Tutorial would be './app.component'
import {AppComponent} from './imports/app/app'; //<========

const platform = platformBrowserDynamic();

@NgModule({
imports: [
BrowserModule
],
declarations: [
AppComponent
],
bootstrap: [
AppComponent
]
})
export class AppModule {}

platform.bootstrapModule(AppModule);
`

**Comment by Urigo** [comment]
Hi everyone and sorry for the late response.
We were hard at work for updating to the latest Angular 2.0 stable.
Please try the new `angular2-meteor@0.7.0`, `angular2-compilers@0.6.2_1` and the latest Angular 2.0.

We've update the Socially 2.0 tutorial and the Blaze to Angular 2 migration tutorial for reference - http://www.angular-meteor.com/migration/angular2/intro (Whatsapp clone is on the way)

Sorry for the long wait, it was very hard to keep up with Angular 2 releases in latest months.

If you find issues, please open new ones on the Github repo.

**Comment by henrique-rotava** [comment]
Same problem here, using `meteor add barbatus:angular2-polyfills` solved the issue.
This package should be added to the angular2-boilerplate repo or it should be mentioned on the tutorial if it is required.

**Comment by Urigo** [comment]
@henrique-rotava do you mean that if you follow step 0 of the tutorial from scratch, it doesn't work?
If so, can you PR the chapter to make sure it has everything that is needed?
also maybe PR the `angular2-boilerplate`?

**Comment by dotansimha** [comment]
@henrique-rotava I just fixes some issues in the base boilerplate, it should work now.
