### ISSUE TITLE
Coveralls

### ISSUE THREAD

**Issue by yagoferrer** [Urigo/angular-meteor#144]
Hey Uri,
It would be nice to activate Coveralls so that people can see the code coverage report.
To activate go to http://coveralls.io using your github account, then turn on the angular-meteor project.  Save the `repo_token` then go to Travis-CI and add the `repo_token` as environmental variable in the Travis-CI angular-meteor project.

**Comment by yagoferrer** [comment]
It will look similar to this: https://github.com/yagoferrer/angular-meteor 
Checkout the badge in the docs.

**Comment by Urigo** [comment]
Great, will do it first thing after landing

**Comment by Urigo** [comment]
thank you so much!
