### ISSUE TITLE
Errors prevented startup:  Package version not in catalog: blaze 2.1.9

### ISSUE THREAD

**Issue by kenp77** [Urigo/angular-meteor#1440]
Hi,

I'm following the Angular 2.0 Meteor Socially app tutorial to create my first meteor application but i get this error message when i run the application : 

```
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While selecting package versions:
   error: Package version not in catalog: blaze 2.1.9

   While refreshing package catalog to resolve previous errors:
   error: Network error: wss://packages.meteor.com/websocket:
   0:error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too
   small:openssl\ssl\s3_clnt.c:3617:
```

I set my proxy in npm and i'm able to install all the package with the meteor npm install.
I just dont understand why i'm still getting this error and how to resolve it.

Thanks

**Comment by dirklammers** [comment]
Hello everybody, similar problem to me.

```
=> Started proxy.                             
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Package version not in catalog: blaze 2.1.9
   
   While refreshing package catalog to resolve previous errors:
   error: Network error: wss://packages.meteor.com/websocket:
   140060338001792:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown
   protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
   
   
=> Your application has errors. Waiting for file change.
=> Started MongoDB. 

```
I am behind a proxy where the websocket protocol is not allowed. Tried to disable websocket for meteor with the DISABLE_WEBSOCKETS=1 environment variable in my .bashrc. Should this work and is this the correct place for the variable ?

Regards
