### ISSUE TITLE
I always get this and not that I can do. I work on Windows 10 64bit

### ISSUE THREAD

**Issue by ernestomr87** [Urigo/angular-meteor#1446]
E:\Projects\LearnMeteor\socially>meteor
[[[[[ ~\E\Projects\LearnMeteor\socially ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

While checking for angular2-compilers@0.6.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it
for your platform.

=> Your application has errors. Waiting for file change.

**Comment by ArthurMauricioDelgadillo** [comment]
Hi, you should use angular2-compilers@0.6.2_1.
Do this: 
`
meteor remove angular2-compilers
meteor rebuild
meteor add angular2-compilers@=0.6.2_1
`

You can read more in https://github.com/Urigo/angular2-meteor/issues/410

**Comment by Urigo** [comment]
@ernestomr87 is that solved your problem?

**Comment by Urigo** [comment]
@ernestomr87 please re-open and tag me if it's not solved for you with the latest versions
