### ISSUE TITLE
Add example using Apollo

### ISSUE THREAD

**Issue by mischkl** [Urigo/angular-meteor#1448]
Hi,
was just wondering if folks are keeping an eye on GraphQL/Apollo and if someone who knows what they're doing might be willing to create a demo with Angular 2 similar to https://github.com/apollostack/meteor-starter-kit . There is already a nice Angular 2 Apollo integration package and an example of using it here: https://github.com/apollostack/githunt-angular2, but no demos yet of the complete combination Meteor + Angular 2 + Apollo so far.
Cheers!

**Comment by Urigo** [comment]
@mischkl definitely want to add an example and maybe a chapter to Socially...
Would love some help with that, if someone wants to give it a try, you can contact me directly and I'll help you with everything you need

**Comment by Eraldo** [comment]
+1
I too would love to have some kind of full fledged sample application.
(ideally also adding more of the useful stuff like 'astronomy' etc)

**Comment by darkbasic** [comment]
+1

**Comment by adrianolsk** [comment]
+1
I have seen a lot of cool stuffs on Meteor, Apollo and Angular 2. 
But is  really confusing to implement, and there is no tutorial explaining how to implement this 3 together.

Some examples that I have seen uses angular2 for client with Angular CLI with webpack and Meteor for the server side. But it don´t explain how to put that in production, would I need 2 different deploys or one?

I found a example with meteor and apollo and another with apollo and angular.
Apollo now supports pub/sub and I didn't see a example using angular.

What I would like to see is a example using:
Meteor
Angular2 with webpack
Apollo server and client integration with  pub/sub for realtime.

With Meteor everything just works, but when I try put all those new cool stuffs together everything falls apart and explode.

**Comment by cosmin-dumitrache** [comment]
+1

**Comment by jrosseel** [comment]
+1

**Comment by rodrilink** [comment]
+1

**Comment by asemoon** [comment]
+1
This is really needed! The angular meteor concept is amazing. I love the idea of having a continuously connected app and at the same time, I want to open the potential of exposing data using graphQL to other clients. For either adding more platforms or Sass purposes.

**Comment by plmercereau** [comment]
+1

**Comment by MohmadAyman** [comment]
+1

**Comment by darkbasic** [comment]
I have a working example here: https://github.com/darkbasic/angularcli-graphql
The client doesn't use Meteor at all, but the backend uses Meteor's oplog tailing to achieve @live queries: https://github.com/Urigo/WhatsApp-Server-GraphQL-Live-RxJS-Meteor

Right now I'm working on the next tutorial, which will use Apollo and GraphQL so stay tuned.

**Comment by ardatan** [comment]
Closed by https://github.com/Urigo/angular-meteor/commit/4a64d340c6e36e96941782a575f02c642304dc0d
