### ISSUE TITLE
angular-templates 1.0.9 does not install>

### ISSUE THREAD

**Issue by maiardm** [Urigo/angular-meteor#1450]
Hi! I'm trying to install Meteor w/angular flavor, excluding blaze-templates was OK, but when i try to install angular templates, processing 'stalls' in loop like:

**### H:\Radar>meteor add angular-templates
   Extracting angular-templates@1.0.9...     /**  (for ever).

System / Environment  documentation:

OpSys:  Win10 / 64 bits

H:\Radar>node -v
v6.7.0

H:\Radar>npm -v
3.10.8

H:\Radar>meteor -v
[[[[[ ~\H\Radar ]]]]]

=> Started proxy.
=> Started MongoDB.
Local package version is up-to-date: allow-deny@1.0.5
Local package version is up-to-date: autopublish@1.0.7
Local package version is up-to-date: autoupdate@1.2.11
Local package version is up-to-date: babel-compiler@6.9.1_1
Local package version is up-to-date: babel-runtime@0.1.11_1
Local package version is up-to-date: base64@1.0.9
Local package version is up-to-date: binary-heap@1.0.9
Local package version is up-to-date: blaze@2.1.9
Local package version is up-to-date: blaze-tools@1.0.10
Local package version is up-to-date: boilerplate-generator@1.0.10
Local package version is up-to-date: callback-hook@1.0.9
Local package version is up-to-date: check@1.2.3
Local package version is up-to-date: ddp@1.2.5
Local package version is up-to-date: ddp-client@1.2.9
Local package version is up-to-date: ddp-common@1.2.6
Local package version is up-to-date: ddp-server@1.2.10
Local package version is up-to-date: deps@1.0.12
Local package version is up-to-date: diff-sequence@1.0.6
Local package version is up-to-date: ecmascript@0.5.8_1
Local package version is up-to-date: ecmascript-runtime@0.3.14_1
Local package version is up-to-date: ejson@1.0.12
Local package version is up-to-date: es5-shim@4.6.14_1
Local package version is up-to-date: fastclick@1.0.12
Local package version is up-to-date: geojson-utils@1.0.9
Local package version is up-to-date: hot-code-push@1.0.4
Local package version is up-to-date: html-tools@1.0.11
Local package version is up-to-date: htmljs@1.0.11
Local package version is up-to-date: http@1.1.8
Local package version is up-to-date: id-map@1.0.8
Local package version is up-to-date: insecure@1.0.7
Local package version is up-to-date: jquery@1.11.9
Local package version is up-to-date: launch-screen@1.0.12
Local package version is up-to-date: livedata@1.0.18
Local package version is up-to-date: logging@1.1.15_1
Local package version is up-to-date: meteor@1.2.17_1
Local package version is up-to-date: meteor-base@1.0.4
Local package version is up-to-date: minifier-css@1.2.14_1
Local package version is up-to-date: minifier-js@1.2.14_1
Local package version is up-to-date: minimongo@1.0.17
Local package version is up-to-date: mobile-experience@1.0.4
Local package version is up-to-date: mobile-status-bar@1.0.12
Local package version is up-to-date: modules@0.7.6_1
Local package version is up-to-date: modules-runtime@0.7.6_1
Local package version is up-to-date: mongo@1.1.12_1
Local package version is up-to-date: mongo-id@1.0.5
Local package version is up-to-date: npm-mongo@1.5.50
Local package version is up-to-date: observe-sequence@1.0.12
Local package version is up-to-date: ordered-dict@1.0.8
Local package version is up-to-date: promise@0.8.7
Local package version is up-to-date: random@1.0.10
Local package version is up-to-date: reactive-var@1.0.10
Local package version is up-to-date: reload@1.1.10
Local package version is up-to-date: retry@1.0.8
Local package version is up-to-date: routepolicy@1.0.11
Local package version is up-to-date: shell-server@0.2.1
Local package version is up-to-date: spacebars@1.0.13
Local package version is up-to-date: spacebars-compiler@1.0.13
Local package version is up-to-date: standard-minifier-css@1.2.1
Local package version is up-to-date: standard-minifier-js@1.2.0_1
Local package version is up-to-date: tracker@1.1.0
Local package version is up-to-date: ui@1.0.12
Local package version is up-to-date: underscore@1.0.9
Local package version is up-to-date: url@1.0.10
Local package version is up-to-date: webapp@1.3.11_1
Local package version is up-to-date: webapp-hashing@1.0.9
Doing HTTP request:  POST
https://www.meteor.com/oauth2/authorize?...
Doing HTTP request:  GET
https://activity.meteor.com/_oauth/meteor-developer?...
=> Started your app.

=> App running at: ...
   Type Control-C twice to stop.

**Comment by maiardm** [comment]
I tried as Normal User and also as Administrator.

Tried too, to install version 1.0.7 from angular-templates with same result.

The problem seems to be in meteor add function (perhaps in update too).

**Comment by maiardm** [comment]
Hi! I did a new try:

I uninstalled and reinstalled Meteor (obviously running as Administrator).

Then, again following Meteor Tutorial steps for simple-todos app (but changing the app name to "radar", and home-drive to H:), this time i got a different error:

after submitting the steps:

----------
H:
meteor create radar

cd radar
meteor npm install
meteor

meteor remove blaze-html-templates

meteor add angular-templates

----------
This time i got:

## _**H:\radar>meteor add angular-templates**_

_**events.js:141
 throw er; // Unhandled 'error' event**_
 ^

_**Error: write EOF
 at exports.errnoException (util.js:907:11)
 at WriteWrap.afterWrite (net.js:785:14)**_

**Comment by Urigo** [comment]
@maiardm why did you close this? did it work for you?

**Comment by maiardm** [comment]
Hi Mr Urigo !

Sorry! I didn´t wanted to close it. 
I don´t even know how to close an item.
Perhaps i've done  something wrong, but it wasn't intentional.
Can you reopen it ? Or must i open a new (equal) one?
Again sorry by my newbie mistake.
An thanks for your care.

**Comment by maiardm** [comment]
Now I know what i've done (I hit "Close and comment")
But i wanted only to close my comment (not the topic).
It will not happen again.

**Comment by maiardm** [comment]
By the way ...
Is there something i can do to help on debugging / solving this problem ? If so, i'm at your service.
Thank You.

**Comment by DAB0mB** [comment]
@maiardm What happens if you try to run an older version of Meteor? Does it work?

**Comment by maiardm** [comment]
@
Tried too, to install version 1.0.7 from angular-templates with same result.

The problem seems to be in meteor add function (perhaps in update too).

**Comment by maiardm** [comment]
@DAB0mB 

Tried too, to install version 1.0.7 from angular-templates with same result.

The problem seems to be in meteor add function (perhaps in update too).

**Comment by DAB0mB** [comment]
@maiardm I can't seem to reproduce this problem I will try to help you anyway and tell me which method worked for you. It seems like you have problems extracting the package. Try to follow the solution in the following issue:

https://github.com/meteor/meteor/issues/7689

Meteor uses tar.exe to extract its packages and this guy had a very old version of it. Try to uninstall it or install a newer version of it.

**Comment by maiardm** [comment]
@DAB0mB You are correct ! I have/had an old version of tar.exe on my path:


```
 Pasta de C:\msys\bin

21/04/2010  00:44           308.736 tar.exe     (this one was on the active path)
               1 arquivo(s)        308.736 bytes

 Pasta de C:\Tesseract

31/08/2016  10:31           352.256 tar.exe    (this was not in use, but available in another directory)
               1 arquivo(s)        352.256 bytes
```

I "replaced" the first one by second an tried again (all over).

This time it was (if i could say) worse, in the sense that the install processing stalled at a point BEFORE the preceding ones:

```
C:\>meteor create teste
   Extracting templating-compiler@1.2.15...  -   (endless loop here).
```

Since i'm now using a much newer version of "tar.exe" this was a big surprise for me.

Is there some way of start a processing trace or something like that, to register / list some information an flow of processing steps ? 

Something like that that could be very useful to help debug this problem.

**Comment by maiardm** [comment]
Well, i searched a bit more and found an old gzip.exe too, replacing it solved this last problem and send me back to stalling on:
```
C:\test5>meteor add angular-templates
Extracting angular-templates@1.0.9... / (for ever).
```
So, we are back at the first step.

**Comment by maiardm** [comment]
Hi! report from my last try: 

1) Reinstalled W10 

2) Installed last version of MSys / MinGW found af Source Forge:  
**mingw-msys-core-6.1.0-x86**

3) Tried again with same results.

I´m sure that now the last versions of each program from MSys / MinGW is at use, but the problem still occurs.

Does somebody has some idea for any new test ?

**Comment by maiardm** [comment]
Hi Friends,

is there some other way to add angular-templates to meteor environment?

if so, please, where can i find some documentation about that ?

i'm needing to start a small web project, and want(ed) to develop it under meteor/angular/... stack.

but this simple (an very basic) problem, is getting away my best hopes on these packages.

**Comment by Urigo** [comment]
just to make sure, is there anyone else who experiences this issue?

**Comment by maiardm** [comment]
@Urigo  This one seems to me same problem:

[(https://forums.meteor.com/t/unable-to-add-angular-tempates/30142)]

I registered my case there first and only after some time registered here too.

**Comment by maiardm** [comment]
New adventures on installing meteor:

i tried to install meteor on two other cpus (with exactly the same results).

One of them (a desktop), is running W10-Home/32Bits

The other is a notebook, running W10-Home/64Bits

Nothing changed, the install process stalls at the same point, at 

```
C:\test5>meteor add angular-templates
Extracting angular-templates@1.0.9... / (for ever).
```
So, i'm now absolutely sure that meteor install function(s) have a problem.

**Comment by maiardm** [comment]
Hi!

The install loop of node/meteor install process occurs on the first instance of tar.exe (PID 8456): node´s direct child.

During loop, i ended manually, first gzip.exe (PID 2624) and then the second instance of tar.exe (PID 8576), but the message "Extracting...." still remained showing (blinking).

Only when I killed the first instance of tar.exe (PID 8456) the exibition of loop messages stopped. Then occured an exception (as expected), on node processing.

![node-meteor](https://cloud.githubusercontent.com/assets/564179/19484886/fc486ad2-9537-11e6-9efa-1f6c456784b6.png)

**Comment by maiardm** [comment]
Hi! good news ! ... (?)

i tried to install older versions from angular-templates package, in a backward search, and finally, at 1.0.3 it worked !!!

```
C:\test1>meteor add angular-templates@=1.0.3

Changes to your project's package version selections:

angular-templates          added, version 1.0.3
angular-templates-runtime  added, version 0.0.1

angular-templates: Compile angular templates into the template cache
```
So the problem (for me), started at 1.0.5 and exists until now.

But i'm now very glad because i got to confirm without any questions: the problem is outside, not in my cpus / oses / envs and so.

Well, lets start to work with 1.0.3 and wait for this problem's solution.

**Comment by maiardm** [comment]
It doesn't works !

Running angular-templates@1.0.3 with tutorial code adjusted to 1.0.9 doesn't works.

All i get is a nice blank page on browser.

No errors, no warning messages on either side, just a blank page on browser.

**Comment by DAB0mB** [comment]
@maiardm Unfortunately I can't seem to reproduce the issue, you can contact me in the email address listed in my Github account and we can do a video chat where you can show me the issue. Hopefully it'll help :-)

**Comment by maiardm** [comment]
@DAB0mB Perhaps i got a light at the end of this dark tunnel !

I removed / reinstalled node (7.0.0 now), and meteor.

By chance i tried to install meteor without admin privileges. Then the meteor install process tried to create/install modules on a directory with my OLD userid (i reinstalled windows a few days ago), not under the actual userid.

My old userid WAS "Ricardo Maia" (with a space between names), and my present userid IS "RicardoMaia" (without space).

Well, since i didn't copy anything from my previous system (W10 was installed on the same HD ant it was formatted wit full format option), and also didn't create any other user, only "RicardoMaia", FROM WHERE my old user name is coming? Does Node / Meteor download sites stores this information anywhere?

Well, i runned Meteor install steps again (now with Admin privileges), and a this time "new" dir: "Ricardo Maia" was created (???), under C:\Users (only a work dir, not a real user).

I copied then (by hand) the AppData subdir created under "Ricardo Maia" to "RicardoMaia" overlapping any existent files.

This time, when i tried to install angular-templates, IT WORKED !!


```
C:\test>meteor add angular-templates

Changes to your project's package version selections:

angular-templates           added, version 1.0.9
caching-compiler            added, version 1.0.6
urigo:static-html-compiler  added, version 0.1.8


angular-templates: Compile angular templates into the template cache

```

Now i got some new questions:

1) FROM WHERE my old userid is coming?

2) I had angular-templates installation problems BEFORE reinstalling W10. So the userid change may not be this problem originator. What is/was the real origin of my problem? 

3) Did Node 7.0.0 corrected the install problem ?

4) How / where can i correct the wrong userid? What must i do ?

**Comment by maiardm** [comment]
Let me tell one more thing:

When I was "Ricardo Maia" at my former W1 installation, i remember that i saw a "paralel" directory under C:\Users

It was "Ricardo%Maia". At that time i didn't understand what it was and where did it came from. Then i didn't care about that. But now it is very clear: something (Node/Meteor install process) has created it (instead of using "Ricardo Maia").

This now explains (to me) why i got problems since my first installation tries: The target directory (and subs), for update modules download / expanded was not the real one, it should be "Ricardo Maia" at the first case but Node/Meteor install process was creating and "updating": "Ricardo%Maia". And after my win reinstall the target was "Ricardo Maia" instead of "RicardoMaia".

So it seems that Node/Meteor installation process is not handling acurately userids with space character(s) inside, (this is perhaps the same with other special characters too), probably due to html special chars handling.

**Comment by Urigo** [comment]
I hope you end up solving your problem...

**Comment by GrandNewbien** [comment]
Would you mind explaining how you solved your problem more in depth? I've been having this same problem for quite some time now, and feel it's the same issue.
