### ISSUE TITLE
Issue where subscription doesn't become ready due to ui-router preventdefault of route

### ISSUE THREAD

**Issue by mattiLeBlanc** [Urigo/angular-meteor#1452]
Hi,

Context: Angular 1.5 with Meteor.

I have created a 'traffic cop' that handles which states are allowed and which not in UI-router.
On ui-router's `$stateChangeStart`  I do a `preventDefault()` to stop the route transition and then do some checking of the route is allowed. If so, I do another $state.go to the original toState and of it goes.
This works fine, however, I have an issue with a subscription in a Dashboard state that doesn't get ready because of 'traffic cops' intervention.
I already have a solution (hack), by adding a $timeout of 0 around the subscription declaration in my controller which allows it to run at the end of the $digest cycle. (i think)
However this looks like a symptom fix.

So this `Dashboard` state has a controller that subscribes in the constructor. 
```
    .state( 'private.dashboard',
    {
      url: '/dashboard'
    , abstract: true
    , views:
      {
        'container@private':
        {
            templateUrl: 'client/views/dashboard/dashboard.html'
          , controller:   'DashboardController'
          , controllerAs: 'vm'
        }
      }
    } )
    .state( 'private.dashboard.open',
    {
        url: '/open?utm_campaign&utm_content&utm_medium&utm_source&utm_term'
      , views:
      {
        'content@private.dashboard':
        {
          templateUrl: 'client/views/dashboard/open/open.html'
        }
      }
    , params: {
        accessCode: 'dashboardOpen'
      , allowed: null
      }
    } )
    .state( 'private.dashboard.activated',
    {
      url: '/activated'
    , views:
      {
        'content@private.dashboard':
        {
          templateUrl: 'client/views/dashboard/activated/activated.html'
        }
      }
    , params: {
        accessCode: 'dashboardActive'
       , allowed: null
      }
    } )
```

Both Open and Activated Dashboards use the same controller, the Dashboard controller.

When I prevent the transition to the OPEN dashboard, check if allowed and resume transition, I see that the subscription is started
```
      this.subscribe( 'activatedInvoices', () => [] );
      this.subscribe( 'invoices', () => [], {
        onStart: function () {
          console.log("New subscribtion has been started");
        },
        onReady: () => {
          console.log("onReady And the Items actually Arrive", arguments);
          this.loading = false;
        }
      , onStop: function (error) {
          if (error) {
            console.log('An error happened - ', error);
          } else {
            console.log('The subscription stopped');
          }
        }
      });
```
However, the ready never fires.

When I cancel out my Traffic cop by putting a return at the top of the function, the subscription loads fine.
So it might have something to do with the preventDefault and then $state.go to the same state.
I do seem to notice that some of the ui-view components flicker as if they are reRendered. 
When I disable the traffic cop I do not see that flicker.

However, the $timeout around the subscription resolves the issue for now. But I am still puzzled.

**Comment by mxab** [comment]
@mattiLeBlanc this may be the same issue as I'm having #1443

**Comment by mattiLeBlanc** [comment]
I actually noticed that the flickering is only visible in the SVG icons on the page.
In my header, I see the logo flickering, but I put some text behind it and that doesn't flicker.
However, the text might be rendered quicker then the SVG :-/ ?

**Comment by mattiLeBlanc** [comment]
@mxab yes, could be related since I my controller is set in the abstract (parent) state which called again on child state chnage

**Comment by mattiLeBlanc** [comment]
Okay, I have been able to fix the issue by changing my approach a bit. The issue was related to ui-router and angular-meteor and not really angular-meteor's fault I think.

The gist of the fix was that on $changeStart I did a preventDefault (if stateparam `verified` eq false) and then check the the permission for this state, if then allowed I did a $state.go to the state with a stateParam `verified:true` so that in the next $stateChange event the `preventDefault` would not fire again.

This works perfectly, but for the fact that all the ui-views seemed to reload.
I then didged the stateParam flag for a variable set in the localStorage, and not the flickering is gone and I everything works smooth.

My traffic cop engine:
```
     let verified = angular.fromJson( localStorage.getItem( 'routeVerified' ) );

      if ( !verified ) {
        event.preventDefault();

        console.log("TEST RIGHT TO BE HERE");
        let qContinue = this.isStateAllowed.call( this, toState.name, accessCode, event );
        // not all state require further acces rule checking
        //
        qContinue.then( doContinue => {
          console.log( 'Do Continue', doContinue);
          localStorage.setItem( 'routeVerified', true );
          $timeout( () => {

            $state.go( doContinue.toState, toParams, { location: 'replace', inherit: false } );
          }, 0 );
        } );
      } else {
        console.log('[ALLOWED]');
        // set verified to false for the next route change
        //
        localStorage.setItem( 'routeVerified', null );
      }
    } );
```
The timeout was purely for testing, when set to 1000 ms it would prevent non stoppable browser redirect loop.

So, in hindsight I think it was a ui-router related issue because I prevented the state and then transitioned to the same state which caused the subscription issue as collateral
