### ISSUE TITLE
How to get count of MongoObservable.Collection?

### ISSUE THREAD

**Issue by zh-wowtv** [Urigo/angular-meteor#1455]
I'm wondering how to get count of the MongoObservable.Collection? My collection:

   `export const Parties = new MongoObservable.Collection<Party>('parties');`

I think:

   `Parties.find().count();` 

will return a Observable not a number. Am I right? So my code is something like:

   ```
   Parties.find().count().subscribe(
      val => {
         console.log(val);
      }
   ```

But it seems console.log is never been called. What did I do wrong? Any idea? Thanks.

**Comment by vacarsu** [comment]
```Parties.cursor.count()```

**Comment by jalalat** [comment]
I use Counts within my Pub: 

Meteor.publish('commentCountPub', function(userId: string) {
    Counts.publish(this, 'commentCount', Comments.find(buildQuery.call(this, userId)).Cursor());
});

**Comment by dotansimha** [comment]
You can either use:
```js
Parties.cursor.count()
```
As @vacarsu suggested.

If you think it should be part of the ObservableCursor API, please open an issue in https://github.com/Urigo/meteor-rxjs/
