### ISSUE TITLE
Getting "clientAddress" of "onConnection"

### ISSUE THREAD

**Issue by hakikihacioglu** [Urigo/angular-meteor#1456]
Hi,

I am a newbie with Angular 2 and meteor, and trying to get the IP address of the client. In the docs of Meteor there is a section

https://docs.meteor.com/api/connections.html#Meteor-onConnection

which explains how to retrieve the client IP with a callback. 
I have no idea where and how to call the callback function with Angular 2.

Thank you

**Comment by dotansimha** [comment]
First, make sure you aware that `Meteor.onConnection` can run only on the server side of your Meteor application. 

You need to register a callback in any of your loaded server files, for example:
// server/main.ts
```js
Meteor.onConnection((connection) => {
   const clientIp = connection.clientAddress;
});
```
