### ISSUE TITLE
Stuck when trying to switch an angular-meteor project from Atmosphere to npm

### ISSUE THREAD

**Issue by knigal** [Urigo/angular-meteor#1457]
Hi
The repo of our Metoer 1.3 app (an `angular-meteor` one) is [here](https://github.com/mapmelabs/mapme-story-editor) 
As a part of upgrading it to Meteor 1.4, we're setting it to pull `angular-meteor` from npm (among other, separate changes). 

For unclear reason the changes get the client to throw the following error:

```
angular_angular.js?hash=08f63d2…:83Uncaught Error: [$injector:modulerr] Failed to instantiate module mapmeStoryEditor due to:
Error: [$injector:unpr] Unknown provider: $stateProvider
```
At first glance the error origin seems to be a missing injection of the `angular-ui-router` module, however this module is installed (via npm), imported and specified as a dependency of the app. As such this 'smells funny' and I suspect that the error origin might be elsewhere, perhaps a result of a missing `angular-meteor` migration step? 

Notes:
- `master` branch is the `before` state: where angular-meteor is pulled from atmosphere and "everything just works"
- branch `EDITOR-602-pull-angular-from-npm` is an intereme branch: most angular-related packages have been switched to npm (along with angular and angular-meteor from npm) and everything still works (thou, angular is loaded twice)
- branch `EDITOR-602-Pull_angular-meteor_from_npm` (pointed by PR [347](https://github.com/mapmelabs/mapme-story-editor/pull/347) is the one with additional changes which get the error in question to appear
- A few environment variables are required for the server to start. When those are missing the server errors and exits. For debugging this issue, it'll be sufficient to use dummy mock values for those, as in:

```
S3_PATH=a \
MAPBOX_ACCESS_TOKEN=b \
STRIPE_PUBLISHABLE_KEY=c \
ACCOUNT_DOCK_KEY=e \
AWS_ACCESS_KEY_ID=f \
AWS_ACCESS_KEY_SECRET=g \
STRIPE_SECRET_KEY=h \
meteor
```
- As the app isn't an open source project, access requires permissions (pls msg for those)

**Comment by Urigo** [comment]
I can't see the code.
Have you placed all the files needed to be imported on the `import` folder?

**Comment by knigal** [comment]
@Urigo what do you mean by  'the import folder'? Where would you expect this folder to exist?
afaik all I needed to do is to provide you with access to clone the repo. According to github, the invitation I sent you is still pending. Check for an invite from `mapmelabs`

**Comment by Urigo** [comment]
@knigal please read this whole article - https://guide.meteor.com/1.3-migration.html step by step first.

**Comment by knigal** [comment]
@Urigo 
Seems I'm not quite following the problem. Just so I know where we stand - were you able to clone the repo?

Note that I've read the migration instructions you reference. But let me clarify first: you wrote `import folder` - did you mean `imports`?  

If so, take into account that we've knowingly haven't switched the file structure yet to the one required by 1.4 because it's a nontrivial task (we do have a different task for that, which we'll start soon). 

Would switching to the new file structure be a pre-requirement for using angular from npm? If so, I can't see why...

**Comment by Urigo** [comment]
if you read the doc you would see that the reason is because that the `imports` folder works exactly like the `npm_modules` folder in terms of load order.
If you want to bring something from npm and the import it and that it will be loaded before another code you import, you have to import the other code as well which means putting in the the `imports` folder.
otherwise, how could Meteor know which file to load first?

**Comment by knigal** [comment]
ok I understand where you're getting at. 

We've structured the app in such a way that it's a bit of hybrid of the two file loading approaches. Thanks to backward compatibility with the `/client` and `/server` folders, this works. 
As such, according to Meteor's legacy file-loading order spec (which should still work - right?) the `/client/scipts/lib/lib/app.js` should be loading first, and that file contains all the necessary `import` statements

Is this not a valid assumption?
As a side note, I agree that the file structure should change. All we need is for the current file structure to hold until the fs change gets done a weeks from now

Note: please git pull the branch before rechecking, I added one commit

**Comment by DAB0mB** [comment]
@knigal I haven't seen your project but I suggest that you put a debugger right before you load `angular-ui-router`'s ng1 module into your app's ng1 module to see if it is defined. This way you can be sure if the importations were done correctly or not.

**Comment by knigal** [comment]
I'm closing this issue because it seems like it's going down an unsupported/uninteresting trajectory. I've ended up switching to npm/angular-meteor by:

1. Changing the app structure according to https://guide.meteor.com/structure.html 
2. Replacing atmosphere meteor packages with their npm equiv (or downloaded them into the `compatibility` folder) 

After mudfighting the repo for a few hours everything got done and it works. Yay!
