### ISSUE TITLE
issues with client/init.test.ts - has no exported member TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS and TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS 

### ISSUE THREAD

**Issue by parthleo10** [Urigo/angular-meteor#1459]
I am using angular2-meteor@0.7.0.
meteor@1.3.
When I run "yarn", I get these following errors : (FYI: npm install == yarn)
client/init.test.ts(6,3): error TS2305 : Module "node_modules/@angular/platform-browser-dynamic/testing/index" has no exported member **TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS**
client/init.test.ts(6,3): error TS2305 : Module "node_modules/@angular/platform-browser-dynamic/testing/index" has no exported member **TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS**
client/init.test.ts(6,3): error TS2305 : Module "node_modules/@angular/core/testing/testing/index" has no exported member '**setBaseTestProviders**'

Below is as it shows me :

![capture](https://cloud.githubusercontent.com/assets/14926925/19515887/06f24f22-9617-11e6-90bc-7262e17d579a.PNG)

If you want more info, plz let me know...
I am totally confused...
Kindly suggest me a solution to it
Thanks

**Comment by DAB0mB** [comment]
Hello @parthleo10 thank you for submitting this issue. Can you upload your project to [github](github.com) and provide a link to it? To begin with you can post your `package.json` configuration and upload your project later on. Also, I suggest your'e using windows OS right? Make sure that all `angular2-meteor` peer dependencies are installed. Try to update your Meteor version to 1.4.0, it might seem unrelated but it's probably something with the versions of your packages or frameworks that your'e using.

**Comment by dotansimha** [comment]
@parthleo10 
Do you use the angular 2 boilerplate ? because the tests did not work there and we fixed it few days ago. can you try the latest version?

**Comment by dotansimha** [comment]
@parthleo10 just verified it again and it looks like it works.
Please re-open if you still having issues.
