### ISSUE TITLE
Issue running with Angular Meteor 

### ISSUE THREAD

**Issue by jeffchiu605** [Urigo/angular-meteor#1461]
Hi. Hi! I'm trying to install Meteor w/angular flavor, but when i try to install angular project, processing 'stalls' in loop like:

Unable to resolve some modules:

>   "@angular/core" in /Users/jchiu/Downloads/meteor-angular-socially-master/imports/ui/filters/uninvitedPipe.js (web.browser)
>   "@angular/platform-browser" in /Users/jchiu/Downloads/meteor-angular-socially-master/client/main.js (web.browser)
>   "@angular/forms" in /Users/jchiu/Downloads/meteor-angular-socially-master/client/main.js (web.browser)
>   "@angular/upgrade" in /Users/jchiu/Downloads/meteor-angular-socially-master/client/main.js (web.browser)
>   "@angular/material" in /Users/jchiu/Downloads/meteor-angular-socially-master/client/main.js (web.browser)
>   "ng-img-crop/compile/minified/ng-img-crop" in /Users/jchiu/Downloads/meteor-angular-socially-master/imports/ui/components/partyUpload/partyUpload.js (web.browser)
>   "ng-img-crop/compile/minified/ng-img-crop.css" in /Users/jchiu/Downloads/meteor-angular-socially-master/imports/ui/components/partyUpload/partyUpload.js (web.browser)
>   "stream" in /Users/jchiu/Downloads/meteor-angular-socially-master/node_modules/gm/lib/command.js (web.browser)
>   "events" in /Users/jchiu/Downloads/meteor-angular-socially-master/node_modules/gm/index.js (web.browser)
>   "util" in /Users/jchiu/Downloads/meteor-angular-socially-master/node_modules/lru-cache/lib/lru-cache.js (web.browser)
>   "fs" in /Users/jchiu/Downloads/meteor-angular-socially-master/node_modules/which/which.js (web.browser)
>   "child_process" in /Users/jchiu/Downloads/meteor-angular-socially-master/node_modules/cross-spawn/index.js (web.browser)
>   "path" in /Users/jchiu/Downloads/meteor-angular-socially-master/node_modules/which/which.js (web.browser)
>   "spawn-sync" in /Users/jchiu/Downloads/meteor-angular-socially-master/node_modules/cross-spawn/index.js (web.browser)
>   "angular2-meteor" in /Users/jchiu/Downloads/meteor-angular-socially-master/imports/ui/components/partyUninvited/partyUninvited.js (web.browser)
>   "angular-material" in /Users/jchiu/Downloads/meteor-angular-socially-master/imports/ui/components/socially/socially.js (web.browser)
>   "angular-sanitize" in /Users/jchiu/Downloads/meteor-angular-socially-master/imports/ui/components/socially/socially.js (web.browser)
>   "ionic-sdk/release/js/ionic" in /Users/jchiu/Downloads/meteor-angular-socially-master/imports/ui/components/socially/socially.js (web.browser)
>   "ionic-sdk/release/js/ionic-angular" in /Users/jchiu/Downloads/meteor-angular-socially-master/imports/ui/components/socially/socially.js (web.browser)
>   "ionic-sdk/release/css/ionic.css" in /Users/jchiu/Downloads/meteor-angular-socially-master/imports/ui/components/socially/socially.js (web.browser)

If you notice problems related to these missing modules, consider running:

>   meteor npm install --save @angular ng-img-crop meteor-node-stubs spawn-sync angular2-meteor angular-material angular-sanitize ionic-sdk

npm ERR! addLocal Could not install /Users/jchiu/Downloads/meteor-angular-socially-master/@angular
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/jchiu/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/jchiu/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install" "--save" "@angular" "ng-img-crop" "meteor-node-stubs" "spawn-sync" "angular2-meteor" "angular-material" "angular-sanitize" "ionic-sdk"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! path /Users/jchiu/Downloads/meteor-angular-socially-master/@angular
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/jchiu/Downloads/meteor-angular-socially-master/@angular'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/jchiu/Downloads/meteor-angular-socially-master/@angular'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

W20161027-11:35:50.089(-7)? (STDERR) ufs: permissions are not defined for store "thumbs"
W20161027-11:35:50.259(-7)? (STDERR) ufs: permissions are not defined for store "images"
=> Started your app.
### When reporting a bug, please be sure to include the following:
- [ ] I'm running  Meteor 1.4.1.3. version of `angular-meteor` 
  mongo      upgraded from 1.1.12_5 to 1.1.13
  npm-mongo  upgraded from 2.2.10_1 to 2.2.11_1
  meteor-angular-socially-master: updated to Meteor 1.4.1.3.
- [ ] What packages or other dependencies I'm using
- [ ] The behavior you expect to see, and the actual behavior

I expected angular-meteor to run, and it shows localhost:3000 but it does not show me anything after that.
I have troubled running angular-meteor at my environment.
I git clone the project.

**Comment by Urigo** [comment]
what are the steps that you are following?
can you share your repo?

**Comment by jeffchiu605** [comment]
Here's my Github repro and the issue: https://github.com/jeffchiu605/meteor-angular-socially-master/issues/1

**Comment by DAB0mB** [comment]
@jeffchiu605 Look what I replied here https://github.com/Urigo/meteor-angular-socially/issues/142

**Comment by Urigo** [comment]
fixed [here](https://github.com/Urigo/meteor-angular-socially/issues/142)
