### ISSUE TITLE
Calling global JS functions from meteor template functions

### ISSUE THREAD

**Issue by jollysean** [Urigo/angular-meteor#1465]
Is there a possibility to call global javascript variable/functions from inside template function?
I am planning to transform an existing app in meteor, where  a Layout.init() is called upon ```
`
..
import template from './header.html';

class HeaderControllera {
	  'ngInject';
   constructor($scope,$reactive) {
$scope.$on('$includeContentLoaded', function() {
   Layout.init();
}
})
.
.
`
`

**Comment by Urigo** [comment]
@jollysean can you provide that example in a repo?

**Comment by jollysean** [comment]
Here is a test repo. [https://github.com/jollysean/testmetang/blob/master/imports/components/tpl/header.js](https://github.com/jollysean/testmetang)

Line:12 imports/components/tpl/header.js 
$window.Layout.initHeader(); 

$window is unable to access global variable Layout. Is there a way in Meteor to access global vars from template controllers?

**Comment by mxab** [comment]
@jollysean meteor wraps files in function
```
var Layout
```
will only be visible in that file, either make 

```
window.Layout = ...
Layout = ...
```
but do you use Layout outside of the angular world at all? Otherwise just go for the angular DI approach
```
angular.module("...").value('Layout', Layout)
....
function MyController(Layout){
 Layout.initHeaders()

}
```

**Comment by DAB0mB** [comment]
@jollysean I just don't understand your dilemma since you can just turn Layout into a module and import it:

```js
import { init } from '../../layout';

init();
``` 

Shouldn't that work for you?

**Comment by jollysean** [comment]
Uh, so simple. Reactive thinking is so amazing
