### ISSUE TITLE
css-compilers fails when there is an empty scss file

### ISSUE THREAD

**Issue by dotansimha** [Urigo/angular-meteor#1466]
Related to:
https://github.com/Urigo/angular2-meteor/issues/430 
https://github.com/Urigo/angular2-meteor/issues/427

If there is an empty `.scss` file, or a file with empty definitions (which probably removed in the SASS compiler) - the compilers fails and throws an error.

In order to reproduce again the bug - must `meteor reset` and run again. 

@barbatus

**Comment by ayazhussein** [comment]
I'm getting this error even without any scss/css files. i tried meteor deploy and meteor --production

**Comment by sdarnell** [comment]
Note that for me the offending file was actually in node_modules, and an important file for using angular2 with meteor: `node_modules/meteor-rxjs/examples/angular2/client/imports/app/app.component.scss`

**Comment by dotansimha** [comment]
Thanks @sdarnell . I released a new version of `meteor-rxjs` (0.4.4, a clean publish without any examples or other unnecessary files) and updated the boilerplate to use the new version.

**Comment by sdarnell** [comment]
Thanks Dotan for the fast turn-around! Just tested it and it solves the problem.

**Comment by barbatus** [comment]
Please try now. Run meteor update in order to update css-compilers

**Comment by dotansimha** [comment]
I am using the latest boilerplate version, with Meteor 1.4.2.1. Updated all packages:
```
Changes to your project's package version selections from updating package
versions:

babel-runtime*         upgraded from 0.1.13 to 1.0.0
barbatus:css-compiler  upgraded from 0.3.4 to 0.3.5
caching-compiler       upgraded from 1.1.8 to 1.1.9
coffeescript           upgraded from 1.11.1_2 to 1.11.1_3
ddp-common             upgraded from 1.2.7 to 1.2.8
ddp-server             upgraded from 1.3.11 to 1.3.12
ecmascript             upgraded from 0.5.9 to 0.6.0
```

Then tried to run `meteor run --production` and got the same error:
```
Dotans-MacBook-Pro:angular2-meteor-base dotansimha$ meteor run --production
Warning: The --production flag should only be used to simulate production
bundling for testing purposes. Use meteor build to create a bundle for
production deployment. See: https://guide.meteor.com/deployment.html
[[[[[ ~/Dev/angular2-meteor-base ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While processing files with angular2-compilers (for target web.browser):
   /tools/isobuild/compiler-plugin.js:717:15: 'data' option to addAsset must be
   a Buffer or String.
   at ResourceSlot.addAsset (/tools/isobuild/compiler-plugin.js:717:15)
   at InputFile.addAsset (/tools/isobuild/compiler-plugin.js:482:24)
   at SassCompilerExtended.addCompileResult
   (packages/barbatus:css-compiler/compilers/basic_compiler.js:32:15)
   at packages/caching-compiler/multi-file-caching-compiler.js:144:14
   at packages/caching-compiler/multi-file-caching-compiler.js:97:11
   at
   /Users/dotansimha/.meteor/packages/angular2-compilers/.0.6.5.1t7l1hu++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish
   (/Users/dotansimha/.meteor/packages/angular2-compilers/.0.6.5.1t7l1hu++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
   at
   /Users/dotansimha/.meteor/packages/angular2-compilers/.0.6.5.1t7l1hu++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (/Users/dotansimha/.meteor/packages/angular2-compilers/.0.6.5.1t7l1hu++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:221:35)
   at SassCompilerExtended.processFilesForTarget
   (packages/caching-compiler/multi-file-caching-compiler.js:95:11)
   at _loop
   (packages/barbatus:css-compiler/compilers/style_compiler.js:20:26)
   at StyleCompiler.processFilesForTarget
   (packages/barbatus:css-compiler/compilers/style_compiler.js:18:36)


=> Your application has errors. Waiting for file change.
```

Tried `meteor reset` - got the same.

@barbatus

**Comment by barbatus** [comment]
Ok, it was css minifier to blame. It removes empty classes and returns null.
@dotansimha  `angular2-meteor-base` has `app.component.scss` with just `.app {}`, dunno why. Try pls meteor update one more.

**Comment by ayazhussein** [comment]
<img width="1920" alt="screen shot 2016-11-09 at 11 43 05 pm" src="https://cloud.githubusercontent.com/assets/16168367/20155828/5610421a-a6d6-11e6-9581-10dbb56dda6c.png">

updated to 0.3.5_1, meteor reset, deleted all the css/scss, even html , I don't even have style in Components.

**Comment by sdarnell** [comment]
I tried barbatus:css-compiler 0.3.5_1 with meteor 1.4.2 and it still has the issue (when empty styles present).

**Comment by barbatus** [comment]
seems new version is picked up again (there was similar issue before) since I tested locally and it works. @Urigo can we try to publish angular2-compiler with new version of css-compiler (everything is in the PR already)?

**Comment by ayazhussein** [comment]
<img width="1920" alt="screen shot 2016-11-10 at 12 13 11 am" src="https://cloud.githubusercontent.com/assets/16168367/20156783/86ef7e24-a6da-11e6-9bfe-db1477eb6257.png">

**Comment by Urigo** [comment]
I've published `angular2-compilers@0.6.6` with @barbatus latest changes.
@ayazhussein @sdarnell can you please try it out?

**Comment by dotansimha** [comment]
Now it's working great! Tested with the latest boilerplate.

**Comment by ayazhussein** [comment]
Working..thanks @barbatus @urigo

**Comment by sdarnell** [comment]
Yup, fixes the issue for me.

**Comment by vinhhungle** [comment]
Beautiful! working for me too after running 'meteor update'

Thanks all for your help!

**Comment by waynem59** [comment]
Yesterday I left my desktop with strange error messages though I removed every single (s)css file and when I returned just now I was surprised by this bug fix. What should I say: it works! What a nice start of the day ;-)
