### ISSUE TITLE
Can't @import a .scss file in a .sass file

### ISSUE THREAD

**Issue by apatryda** [Urigo/angular-meteor#1471]
When having a client/main.sass file it is impossible to import .scss files from it.

For instance:
`@import '{}/node_modules/bootstrap-sass/assets/stylesheets/bootstrap'`

fails with the following error:
> While processing files with angular2-compilers (for target web.browser):
/client/main.sass: Scss compiler error: File to import:
{}/node_modules/bootstrap-sass/assets/stylesheets/bootstrap not found in file:
.../{}/client/main.sass`

Adding .scss to the path or prefixing a filename with an underscore doesn't help.

The same goes for importing files from /client directory.

**Comment by sdarnell** [comment]
As a work-around, you could use relative pathnames:
```
@import '../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap';
```
I use that approach because my editor doesn't understand the magic '{}' syntax.

**Comment by dotansimha** [comment]
@sdarnell is right, use relative path :)
