### ISSUE TITLE
Roadmap for integrating Angular CLI and Progressive Web Apps features with Meteor

### ISSUE THREAD

**Issue by dotansimha** [Urigo/angular-meteor#1475]
_From @Urigo on May 25, 2016 13:31_

_Copied from original issue: Urigo/angular2-meteor#280_

**Comment by dotansimha** [comment]
_From @daslicht on October 23, 2016 11:15_

So integration of angular cli is planned ?

**Comment by dotansimha** [comment]
_From @barbatus on October 27, 2016 22:5_

@daslicht yes, I am working on it currently.

**Comment by dotansimha** [comment]
_From @daslicht on October 28, 2016 9:53_

awesome news! Its getting better and better !

**Comment by barbatus** [comment]
I expect it to be out soon, see https://github.com/barbatus/angular2-compiler.
It took some time due to issues with Angular2 CLI API.

**Comment by SyedAman** [comment]
Any update on this? Can I use Angular CLI for a MeteorJS project?

**Comment by cyberbeast** [comment]
BUMP. Any updates on this?

**Comment by ludapops** [comment]
Bump. Lets hear the good news!

**Comment by barbatus** [comment]
Here is progress tracking issue https://github.com/barbatus/angular2-compiler/issues/2

**Comment by evilboss** [comment]
bump, This is very interesting

**Comment by michaelb-01** [comment]
bump

**Comment by Urigo** [comment]
yes, we are still working on this.
But now, we are focusing on making it work with the upcoming Meteor 1.5 which supports dynamic imports.
If anyone wants to help, please let me know.
Another import thing is, you can use Angular CLI today, but that means making Angular CLI your front end and Meteor just for your backend.
If you want to do that, check out our tutorial on Ionic CLI, we are doing the same work there, just replace the CLI and Angular CLI and you suppose to be good to go.

**Comment by ArnoldM-webdev** [comment]
I'm trying to use your tutorial on ionic CLI to make it work with Angular CLI but I'm stuck with the webpack configuration that should able to import Meteor packages... Angular CLI don't let us override this configuration.
How can I solve this?
Thank's a lot for all your great work!

**Comment by Zeioth** [comment]
Bump! We are not able to run Meteor + Angular 2 + Lazyload
Thank you for working on this!

**Comment by nicolaspanel** [comment]
@Urigo, you said:
> Another import thing is, you can use Angular CLI today, but that means making Angular CLI your front end and Meteor just for your backend.
> If you want to do that, check out our tutorial on Ionic CLI, we are doing the same work there, just replace the CLI and Angular CLI and you suppose to be good to go.

Updating angular-cli's webpack config seems risky / discouraged (see https://github.com/angular/angular-cli/issues/1656).
It would be great if meteor could "just" serve angular`s statics (I mean from `dist` directory). Is there a way to do this?

@ArnoldM-webdev: you can access angular-cli's webpack config using `ng eject`

**Comment by michaelb-01** [comment]
Is this still being developed?

**Comment by Urigo** [comment]
Now you can use all features from the Angular CLI:

- Lazy loading and dynamic imports
- AOT compilation
- SSR Angular Universal
- Latest Angular 5, Meteor 1.6 and Node 8.8

both with the Angular CLI and Meteor Client bundler or with the Meteor CLI itself!

thanks to the great work of @darkbasic and @ardatan .

Check out all the new examples in the examples folder here: https://github.com/Urigo/angular-meteor/tree/master/examples
