### ISSUE TITLE
Assets include lots of files that shouldn't be there

### ISSUE THREAD

**Issue by sdarnell** [Urigo/angular-meteor#1479]
I've hit the same problem as https://github.com/Urigo/angular-meteor/issues/1466 and I was trying to establish which file was causing the problem... and was very surprised by the result.

I added the following statement to ResourceSlot.addAsset() in the meteor tools/isobuild/compiler-plugin.js file roughly around line 717.

    console.warn('addAsset: '+options.path);

Although our app has lots (lots!) of files and packages that show up here, the following is the output from the bare boiler-plate app generated from angular2-boilerplate: https://github.com/bsliran/angular2-meteor-base

Here is the list of files that seem to be added as assets:
```
=> Started proxy.                             
=> Started MongoDB.                           
addAsset: node_modules/meteor-rxjs/examples/angular2/client/imports/app/app.component.html.d.ts
addAsset: node_modules/angular2-meteor/examples/todos-meteor-1.3/client/components/task-list.component.html.d.ts
addAsset: node_modules/angular2-meteor/examples/todos-meteor-1.3/imports/components/task.component.html.d.ts
addAsset: node_modules/angular2-meteor/examples/todos-meteor-1.3/client/app.component.html.d.ts
addAsset: node_modules/angular2-meteor/examples/todos-meteor-1.3/client/index.html.d.ts
addAsset: node_modules/meteor-rxjs/examples/angular2/client/index.html.d.ts
addAsset: client/imports/app/demo/demo.component.html.d.ts
addAsset: node_modules/chai-spies/test/browser/index.html.d.ts
addAsset: client/imports/app/app.component.html.d.ts
addAsset: node_modules/reflect-metadata/spec/index-out.html.d.ts
addAsset: node_modules/reflect-metadata/spec/index.html.d.ts
addAsset: node_modules/reflect-metadata/spec/typescript-out.html.d.ts
addAsset: node_modules/reflect-metadata/spec/typescript.html.d.ts
addAsset: node_modules/angular2-meteor/examples/todos-meteor-1.3/imports/components/task.component.less
addAsset: node_modules/meteor-rxjs/examples/angular2/client/imports/app/app.component.scss
addAsset: client/imports/app/demo/demo.component.scss
addAsset: client/imports/app/app.component.scss
addAsset: node_modules/angular2-meteor/examples/todos-meteor-1.3/imports/components/task.component.html.d.ts
addAsset: node_modules/chai-spies/test/browser/index.html.d.ts
addAsset: node_modules/reflect-metadata/spec/index-out.html.d.ts
addAsset: node_modules/reflect-metadata/spec/index.html.d.ts
addAsset: node_modules/reflect-metadata/spec/typescript-out.html.d.ts
addAsset: node_modules/reflect-metadata/spec/typescript.html.d.ts
addAsset: node_modules/angular2-meteor/examples/todos-meteor-1.3/imports/components/task.component.less
=> Started your app.                          
```

The most obvious question is why the compiler is picking up stuff from node_modules including test junk.

I guess the client/imports/...scss files are acceptable, but in our app we NEVER use these files via URLs. They're always just imported and passed to the `@Component({ styles })` array.

So my concerns are that all of this stuff is bloating and slowing down our app or the build process.
This stuff also seems to be exposed and served to clients (if they actually tried to access them) - for obvious reasons we'd like to keep our app's surface area as small as possible.

So how can we limit what is being processed?
Is there anyway to prevent these assets from being processed or added, and still be able to use non-inline templates?

The final point to note is that final file: `node_modules/meteor-rxjs/examples/angular2/client/imports/app/app.component.scss` seems to be the one that breaks the use of `--production` causing https://github.com/Urigo/angular-meteor/issues/1466
This file contains just "app { }" which presumably is optimised away resulting in an empty file.

We're using meteor 1.4.2, angular 2 2.1.2, angular2-compilers 0.6.5, angular2-meteor 0.7.0

**Comment by sdarnell** [comment]
For the html files at least, the change that seems to start considering files in node_modules was: https://github.com/Urigo/meteor-static-html-compiler/commit/062b6c190013ddd0a9ec3c8a829e589547801b9b

**Comment by dotansimha** [comment]
I cleaned and released a new version of `meteor-rxjs` (0.4.4) without the examples, and applied https://github.com/Urigo/angular-meteor/commit/44508318fe133b9524c3a989ac5523dde91a3f61 here in order to get clean package when publishing.

@Urigo We need to publish a new version of `angular2-meteor`

**Comment by Urigo** [comment]
published `angular2-meteor@0.7.1`, please check if there problem persists

**Comment by dotansimha** [comment]
`angular2-meteor@0.7.1` installed as clean dependency, without any assets :)

**Comment by sdarnell** [comment]
I appreciate the fixes to the css compiler and the sleek new meteor-rxjs, but this issue was more about the general inclusion of all css and html files regardless of whether they are needed, hence bloating the deployed apps, presumably slowing down builds, and exposing content to the outside world that probably shouldn't be.

My understanding is that the current compilers take any css/scss/less/html file and add them as assets. It would be better if there was some way of only doing this for files which are actually referenced from import statements. More specifically I think only the ones that are referenced with the '!url' suffix need to be added as assets.

If this is too tricky to do in the meteor build process (I don't know how the ordering works), a compromise would be to have some mechanism where we could disable the call to addAsset().
Maybe also have some way of excluding certain directories (like node_modules).

**Comment by dotansimha** [comment]
Meteor added official support for NPM &  `node_modules` in Meteor 1.3, and since then - the whole `node_modules` are going through the compiler. 
I don't think there is an efficient way to tell which files from `node_modules` you actually use (using import / require) in your app so it's might be a little tricky to try and detect which files should go through the compiler and which files to exclude.

@barbatus what do you think?

**Comment by barbatus** [comment]
@sdarnell i think files from node_modules definitely not needed as assets, that piece was just missed. I'll fix and let you know. Also, In the near future we'll get rid of using URL for assets (in new combined compiler), there is not much sense in them.

**Comment by sdarnell** [comment]
Great thanks. For what is worth, we don't use the URL form anyway :)
