### ISSUE TITLE
Can't import any Css/Sass/SCSS file in another CSS/Sass/SCSS file.

### ISSUE THREAD

**Issue by ayazhussein** [Urigo/angular-meteor#1482]
Whenever I try to import in client/main.scss or any other .scss/sass or .css file, I get this error

```
 App running at: http://localhost:8080/
=> Client modified -- refreshing (x6)
=> Errors prevented startup:
   
   While building for web.browser:
   /client/imports/app/shared/header.component.sass: Scss compiler error: File to import: {}/client/imports/app/shared/sass/material-kit not found in file: /Users/ayaz/Documents/Projects/clientWebRemote/{}/client/imports/app/shared/header.component.sass
   
   
=> Your application has errors. Waiting for file change.
```

I tried moving the files around, putting them in imports folder, outside imports folder.

angular2-compilers 0.6.6

**Comment by sdarnell** [comment]
Do relative path names work?

**Comment by ayazhussein** [comment]
nope, using sass
```sass
@import "../../../stylesheets/bootstrap/bootstrap.min.css"
```
```
 /client/imports/app/shared/header.component.sass: Scss compiler error: File to import: {}/client/stylesheets/bootstrap/bootstrap.min.css not found in file: /Users/ayaz/Documents/Projects/clientWebRemote/{}/client/imports/app/shared/header.component.sass
```

**Comment by sdarnell** [comment]
Seems to be a common issue that others have encountered even though it should have been fixed quite a while ago: http://stackoverflow.com/questions/7111610/import-regular-css-file-in-scss-file

A solution that works is to rename bootstrap.min.css to _bootstrap.min.scss.  The underscore apparently prevents it being output to a separate file, and as new SASS files are a superset of css making the extension scss should do no harm.

BTW as meteor will automatically do the minimisation for production builds, you shouldn't need to use the min version of bootstrap.

**Comment by ayazhussein** [comment]
```
While building for web.browser:
   /client/imports/app/shared/header.component.scss: Scss compiler error: File to import: {}/client/stylesheets/bootstrap/_material-kit.css not found in file: /Users/ayaz/Documents/Projects/clientWebRemote/{}/client/imports/app/shared/header.component.scss
```

I changed the file to .scss and added underscore.. same error

**Comment by nebiljabari** [comment]
@ayazhussein Have you try to put your .scss in client root folder then styleUrls ? [example](https://github.com/Urigo/angular-meteor/issues/1486)

**Comment by kamilkisiela** [comment]
[Works for me](https://github.com/kamilkisiela/angular2-meteor-base/blob/issue/1482/client/imports/app/demo/demo.component.scss)

@mention me if this is still a case

**Comment by ayazhussein** [comment]
<img width="1920" alt="screen shot 2016-11-16 at 3 42 36 pm" src="https://cloud.githubusercontent.com/assets/16168367/20349484/585ccd9e-ac13-11e6-9678-369501da6085.png">

seems that it works when there is only $green, but when i add another variable, it gives me this error.

**Comment by kamilkisiela** [comment]
@ayazhussein add semicolons

```sass
$green: #2BD95A;
$greenhover: #24c750
```

**Comment by ayazhussein** [comment]
Seems to work, but it's weird to add semicolon in .sass files :D
@kamilkisiela

**Comment by kamilkisiela** [comment]
I checked it and it works:

`*.scss`

```scss
$green: #2BD95A;
$greenhover: #24c750;
```

`*.sass`

```sass
$green: #2BD95A;
$greenhover: #24c750
```

**Comment by ayazhussein** [comment]
It works, just saying that it's weird to add semicolon in *.sass since it's supposed to be without any semicolons.
closing the issue

**Comment by kamilkisiela** [comment]
@ayazhussein no no, I mean that it works without semicolons in `.sass`. Do you have the latest version?

**Comment by kamilkisiela** [comment]
Or could you prepare some simple reproduction? Really really basic.

**Comment by ayazhussein** [comment]
just tested, it's working, 
``` sass
$green: #2BD95A;
$greenhover: #24c750
```
works if you add semicolon to all but last $var when it should work like this:

``` sass
$green: #2BD95A
$greenhover: #24c750
```

but it throws the same error, I was just referring that *.sass syntax has no semicolons.

**Comment by kamilkisiela** [comment]
I don't think we're on the same page. I mean that 

```sass
$green: #2BD95A
$greenhover: #24c750
```

should work in `.sass` files. Without any semicolons. Could you provide just a basic reproduction?

**Comment by ayazhussein** [comment]
<img width="1920" alt="screen shot 2016-11-18 at 3 09 11 pm" src="https://cloud.githubusercontent.com/assets/16168367/20431143/23638d6e-ada1-11e6-9f87-9af1465525d2.png">
<img width="1920" alt="screen shot 2016-11-18 at 3 09 29 pm" src="https://cloud.githubusercontent.com/assets/16168367/20431142/23636f5a-ada1-11e6-8824-3f56425577aa.png">


angular2-compilers 0.6.6

**Comment by ayazhussein** [comment]
<img width="1920" alt="screen shot 2016-11-18 at 3 11 17 pm" src="https://cloud.githubusercontent.com/assets/16168367/20431170/4b66e5fe-ada1-11e6-9419-54da8e1bbfc7.png">

and this way works...

**Comment by DAB0mB** [comment]
@ayazhussein @Urigo I think this can be closed?!

**Comment by Urigo** [comment]
everyone please try to new and updated [angular-compilers  package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers).
It supports:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

Please open a new issue if you encountered one.
