### ISSUE TITLE
Style compiling issue

### ISSUE THREAD

**Issue by ayazhussein** [Urigo/angular-meteor#1485]
<img width="1920" alt="screen shot 2016-11-11 at 10 07 26 pm" src="https://cloud.githubusercontent.com/assets/16168367/20228728/59ccef12-a85b-11e6-9596-ac64d6ad25c3.png">

both of the images have the same sass styles, same html template, component used in routing so it appears under router-outlet,
the left one is built with angular-2-meteor and the right side is built with angular2 project created with angular cli.
Spent almost the whole day trying to fix the damn resizing when I knew that it should be working,
I can upload the sass,html and ts file for testing.

@Urigo @barbatus

**Comment by dotansimha** [comment]
Hi @ayazhussei, can you share a repository with your code? 
Note that there are differences in files loading between Angular 2 project and Angular2-Meteor project, because we are using Meteor build process.

**Comment by ayazhussein** [comment]
invitation sent.
@dotansimha

**Comment by ayazhussein** [comment]
@dotansimha 
I noticed something wrong with the width of the body, it doesn't get below 980px and the height is just going crazy..  if that helps..

**Comment by kamilkisiela** [comment]
@ayazhussein Could you add me also?

**Comment by kamilkisiela** [comment]
@ayazhussein I've created a PR, check it and tell me if it fixed the problem.

**Comment by ayazhussein** [comment]
seems that it was fixed. rookie mistake. sorry
