### ISSUE TITLE
styles:  [ style ] Error

### ISSUE THREAD

**Issue by nebiljabari** [Urigo/angular-meteor#1486]
If I respect the syntax `styles: [style]`, for a .css file, present in [step 18.12](https://github.com/Urigo/meteor-angular2.0-socially/commit/34165256925a33f73f0a4956cea613270117f9ed) of the tuto
I get : `Error: Expected 'styles' to be an array of strings.`

To get my page styled I have to put `styles: style` (or just `style` work too) with 
`import style from './style.css'` but TypeScript don't like it:

> Argument of type '{ selector: string; template: string; styles: string; }' is not assignable to parameter of type 'Component'.
>   Types of property 'styles' are incompatible.
>     Type 'string' is not assignable to type 'string[]'.

`styleUrls` work if the css file is in the client folder : `client/imports/app/foo.compo.ts`
```
@Component({
  selector: 'foo-selector',
  template,
  styleUrls: ['../../style.css']
})
```
Angular : 2.1.2 - Angular2-meteor : 0.7.0 - Angular2-compilers : 0.6.5 - Meteor : 1.4.2.1

**Comment by dotansimha** [comment]
@nebiljabari 

1. Which IDE do you use?
2. Can you share you `tsconfig.json`? maybe some typings is missing. we recently added [this file](https://github.com/Urigo/angular2-meteor-base/blob/master/typings.d.ts#L7-L30) to the boilerplate in order to solve those import issues.

**Comment by nebiljabari** [comment]
@dotansimha 

1. No IDE, I use Atom
2. The `typings.d.ts` is the same (I cloned the repo 3/4 days ago)

`tsconfig.json`
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "es6",
      "dom"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ],
  "files": [
    "typings.d.ts"
  ],
  "compileOnSave": false,
  "angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit": true
  }
}

```

**Comment by kamilkisiela** [comment]
Does

> Argument of type '{ selector: string; template: string; styles: string; }' is not assignable to parameter of type 'Component'.
Types of property 'styles' are incompatible.
Type 'string' is not assignable to type 'string[]'.

apply to:

```ts
import style from './style.css'

@Component({
  selector: 'foo-selector',
  template,
  styles: [ style ]
}) class FooComponent{}
```

?

And why you have `styles: string` instead of `styles: any[]`? It's not specific to `angular-meteor`. It's all about your environment. 

Your IDE thinks that `Component` decorator contains `styles` that is a string and not an array of strings. This type definition comes from `@angular/core` ([here](https://github.com/angular/angular/blob/master/modules/%40angular/core/src/metadata/directives.ts#L581)) so you have to have something that overwrites it or something.

**Comment by nebiljabari** [comment]
Yes @kamilkisiela with the standard pattern and I don't know why `styles: string`
Path: `client/imports/app/foo.compo.ts`
```
import style from './style.css'

@Component({
  selector: 'foo-selector',
  template,
  styles: [ style ]
}) 
export class FooCompo{}
```
I ran several test and the best I get is : 
```
import style from '../../style/style.css'
styles : style
```
It failed to load if the .css is in the `client/imports` folder

I let to your appreciation to close or not this issue

**Comment by DAB0mB** [comment]
@nebiljabari Unfortunately, adding custom loaders is not available in Meteor's build system. However, if you use Webpack, you can use the following loader: https://github.com/jtangelder/sass-loader. You can use whatever loader you desire, as long as it fulfills what you wish for, and you use it right, then that's the way to go. We have a tutorial in our websites which guides you through building an application using Webpack and Meteor and it's available here: https://angular-meteor.com/tutorials/whatsapp2/ionic/setup. Take your time to investigate about Webpack and its bundling system, and see how you can combine it with Meteor in a way that is right for YOUR application, it might take you some time. Please give me your feedback so I can know if my answer was helpful.

**Comment by Urigo** [comment]
everyone please try to new and updated [angular-compilers  package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers).
It supports:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

Please open a new issue if you encountered one.
