### ISSUE TITLE
[docs] Integrate 3rd party : external global script and external global stylesheet 

### ISSUE THREAD

**Issue by florent1933** [Urigo/angular-meteor#1491]
When reading the docs, we don't know how to install an external global script or stylesheets which are in node_modules.

In angular-cli.json (with webpack) we can do:
```
      "styles": [
        "../node_modules/fullcalendar/dist/fullcalendar.min.css",
        "../node_modules/fullcalendar-scheduler/dist/scheduler.min.css",
        "styles.css",
        "grids.css"
      ],
      "scripts": [
        "../node_modules/webcomponentsjs/full.js",
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/moment/moment.js",
        "../node_modules/fullcalendar/dist/fullcalendar.min.js",
        "../node_modules/fullcalendar-scheduler/dist/scheduler.min.js",
      ],
``` 

How can we achieve something similar with angular-meteor?

**Comment by kamilkisiela** [comment]
You can import those like this
https://github.com/Urigo/meteor-angular2.0-socially/blob/master/client/main.scss#L1

**Comment by florent1933** [comment]
@kamilkisiela 👍

Thanks for your answer.

**Comment by DAB0mB** [comment]
@florent1933 @Urigo Should this issue be closed?!

**Comment by Urigo** [comment]
everyone please try to new and updated [angular-compilers  package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers).
It supports:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

Please open a new issue if you encountered one.
