### ISSUE TITLE
imports is important in angular-meteor?

### ISSUE THREAD

**Issue by laserus** [Urigo/angular-meteor#1492]
Hello,

I have tried to modify and organize code a more nicer way, and for some project there was path /client/imports/app/demo.component.ts

However it is quite long tree organization. I decided to remove imports from the path to make in more angular2 style (when you generate with ng cli a new project). 

However everything broke without /imports/, then I tried to fix it (and it seems that reflected-metadata is not added without this folder). I returned back the imports, but removed "app" folder and everything is fine.

Is it some kind of convention which is used by meteor-angular compiler? 

PS: it is fine for me to have /client and /server, on higher level, but for example /both I normally rename to /common (as it sound strange to me) and try to organize internally code and structure myself.

BR,
Andrey.

**Comment by Urigo** [comment]
Yes `imports` in a meaningful folder for Meteor, check out those resources:
https://guide.meteor.com/structure.html#javascript-structure
https://themeteorchef.com/snippets/understanding-the-imports-directory/
