### ISSUE TITLE
Using meteor-publish-composite with angular2

### ISSUE THREAD

**Issue by hsdhillon** [Urigo/angular-meteor#1499]
I am learning meteor along with angular2 and tutorial on angular-meteor.com has helped a lot.

I have extended the exercise in tutorial to use a new collection name Venues and using a reference in Parties collection to refer to document in Venues collection. I am trying to use meteor-publish-composite to publish the Parties and related Venue document along with it.

I am getting following error message when publishing Parties using publishComposite

```bash
server/imports/publications/parties.ts (11, 36): Argument of type '(options: Options, location?: string) => { find: () => ObservableCursor<Party>; children: { find:...' is not assignable to parameter of type '(...args: any[]) => PublishCompositeConfig<any> | PublishCompositeConfig<any>[]'.
  Type '{ find: () => ObservableCursor<Party>; children: { find: (party: any) => Cursor<Venue>; }[]; }' is not assignable to type 'PublishCompositeConfig<any> | PublishCompositeConfig<any>[]'.
    Type '{ find: () => ObservableCursor<Party>; children: { find: (party: any) => Cursor<Venue>; }[]; }' is not assignable to type 'PublishCompositeConfig<any>[]'.
      Property 'length' is missing in type '{ find: () => ObservableCursor<Party>; children: { find: (party: any) => Cursor<Venue>; }[]; }'.
```

Here is the code snippet from **server/imports/publications/parties.ts**

```javascript
Meteor.publishComposite('parties', function(options: Options, location?: string) {
    return {
        find: function() {
            const selector = buildQuery.call(this, null, location);

            Counts.publish(this, 'numberOfParties', Parties.collection.find(selector), { noReady: true });

            return Parties.find(selector, options);
        },
        children: [{
            find: function(party) {
                return Venues.collection.find(
                    {_id: party.venueId},
                    {limit: 1}
                );
            }
        }]
    }
});
```
Completed code is available at [https://github.com/hsdhillon/angular2-meteor-publish-composite](https://github.com/hsdhillon/angular2-meteor-publish-composite)

Also, I am not able to figure out as how I can access the related Venues from the template to render the parties-list.

I will really appreciate any help or pointers to solve this.

**Comment by dotansimha** [comment]
@hsdhillon, when using `publish-composite` you need to pass the actual `Mongo.Collection` object, and not the `ObservableCollection` that wrapped by `meteor-rxjs`. 
So instead using `Parties.find(selector, options);`, use `Parties.collection.find(selector, options);`.

**Comment by Urigo** [comment]
you can check out the usage of `meteor-publish-composite` in the new version of the tutorial - https://angular-meteor.com/tutorials/whatsapp2/ionic/privacy

**Comment by michaelb-01** [comment]
I'm trying to use the reywood:publish-composite package and i'm getting the following error:

`Property publishComposite does not exist on type 'typeof Meteor'`

I've followed the tutorial so i'm not sure where I went wrong.. 

My tsconfig.json is:

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2017"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es6",
    "skipLibCheck": true,
    "stripInternal": true,
    "noImplicitAny": false,
    "types": [
      "@types/meteor",
      "@types/meteor-publish-composite"
    ]
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}

```

and my meteor packages file:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.2.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.3.0                   # The database Meteor supports right now
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.5   # CSS minifier run for production mode
standard-minifier-js@2.2.0    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers
ecmascript@0.9.0              # Enable ECMAScript2015+ syntax in app code
shell-server@0.3.0            # Server-side component of the `meteor shell` command

insecure@1.0.7                # Allow all DB writes from clients (for prototyping)
angular-compilers
accounts-base
accounts-ui
accounts-password
anti:fake
jalik:ufs
jalik:ufs-gridfs
reywood:publish-composite

```

**Comment by impcyber** [comment]
@michaelb-01 Id ont know how to do this right, but this work for me:
`Meteor['publishComposite']('chats', function(): PublishCompositeConfig<Entity> {`

**Comment by ardatan** [comment]
Meteor.publishComposite is deprecated, you can see the current usage of publishComposite in the examples in README of the package
https://github.com/englue/meteor-publish-composite/blob/master/README.md
