### ISSUE TITLE
Task 'typescript' is not in your gulpfile

### ISSUE THREAD

**Issue by sunil85** [Urigo/angular-meteor#1503]
{
  "name": "lb",
  "version": "1.0.0",
  "description": "LB Node Dependencies",
  "main": "gulpfile.js",
  "dependencies": {
    "@angular/common": "2.1.0",
    "@angular/compiler": "2.1.0",
    "@angular/core": "2.1.0",
    "@angular/forms": "^2.1.0",
    "@angular/http": "2.1.0",
    "@angular/platform-browser": "2.1.0",
    "@angular/platform-browser-dynamic": "2.1.0",
    "@angular/platform-server": "2.1.0",
    "@angular/router": "3.0.0-rc.2",
    "@types/jquery": "^2.0.33",
    "@types/jquery.validation": "^1.13.31",
    "async": "^2.1.1",
    "autoprefixer": "^6.5.1",
    "babel-preset-es2015": "^6.16.0",
    "browser-sync": "^2.17.3",
    "browserify": "^13.1.0",
    "browserify-shim": "^3.8.12",
    "concurrently": "^3.1.0",
    "es6-promise": "^4.0.5",
    "glob": "^7.1.1",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.1",
    "gulp-babel": "^6.1.2",
    "gulp-clean": "^0.3.2",
    "gulp-concat": "^2.6.0",
    "gulp-debug": "^2.1.2",
    "gulp-exec": "^2.1.2",
    "gulp-foreach": "^0.1.0",
    "gulp-image": "^2.7.1",
    "gulp-imagemin": "^3.1.0",
    "gulp-install": "^0.6.0",
    "gulp-load-plugins": "^1.3.0",
    "gulp-minify-css": "^1.2.4",
    "gulp-minify-html": "^1.0.6",
    "gulp-msbuild": "^0.4.1",
    "gulp-newer": "^1.3.0",
    "gulp-postcss": "^6.2.0",
    "gulp-pug": "^3.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-rimraf": "^0.2.0",
    "gulp-sass": "^2.3.2",
    "gulp-sequence": "^0.4.6",
    "gulp-sourcemaps": "^2.1.1",
    "gulp-streamify": "^1.0.2",
    "gulp-typescript": "^3.0.2",
    "gulp-uglify": "^2.0.0",
    "gulp-util": "^3.0.7",
    "gulp-watch": "^4.3.10",
    "gulp-wrap": "^0.13.0",
    "gulpfile.ts": "0.0.2",
    "iis-reset": "^1.0.0",
    "merge-stream": "^1.0.0",
    "motion-ui": "^1.2.2",
    "node-bourbon": "^4.2.8",
    "pug": "^2.0.0-beta6",
    "rimraf": "^2.5.4",
    "run-sequence": "^1.2.2",
    "typescript": "^2.0.3",
    "typings": "^1.4.0",
    "vinyl": "^2.0.0",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^3.7.0",
    "xml2js": "^0.4.17",
    "xmlpoke": "^0.1.12"
  },
  "devDependencies": {
    "@types/jquery": "^2.0.33",
    "@types/uglify-js": "^2.0.27",
    "core-js": "^2.4.1",
    "foundation-sites": "^6.2.0",
    "gulp-imagemin": "^3.1.0",
    "gulp-nuget-restore": "^0.5.0",
    "jquery": "^2.1.4",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.11",
    "systemjs": "^0.19.39",
    "typescript": "^2.0.10",
    "zone.js": "^0.6.17"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://bitbucket.org/osfglobalservices/fr-lorfr-ifb-loreal-botanicals-sitecore.git"
  },
  "license": "UNLICENSED"
}

**Comment by Urigo** [comment]
@sunil85 can you please add more context about your problem?
code, reproduction, something..
