### ISSUE TITLE
Call function from another component

### ISSUE THREAD

**Issue by erperejildo** [Urigo/angular-meteor#1512]
Having 2 components, how can I call a function from another one?

I'm importing this component in my `plateEdit `component:
`import { name as Edition } from '../edition/edition';`
and I'ld like to call `update()` which is a function defined in `edition` from `plateEdit`.

I can call whatever I want inside of `<edition></edition>` but not from outside.
![sin titulo](https://cloud.githubusercontent.com/assets/5629919/21120274/66002256-c0be-11e6-91fd-c9b9b655bee2.jpg)

I'm using Angular 1 and it's a bit difficult to find info with Angular1 + TS about this.

Thanks in advance!

**Comment by dotansimha** [comment]
@erperejildo , it's an Angular questions and not directly related to `angular-meteor`, but we'll try to assist you. 
In Angular 1 there are multiple options for component's communication:
1. Move you function to a service and use this service in your component.
2. If there is a relation between the components (one inside each other), you can use bindings to pass the function from the parent component into the child component (just like any other attribute for component).

You can read more [here](https://docs.angularjs.org/guide/component).

**Comment by erperejildo** [comment]
Hi @dotansimha thanks for your support. I'll check that out.
