### ISSUE TITLE
return type Subscription instead of Observable - typescript

### ISSUE THREAD

**Issue by msio777** [Urigo/angular-meteor#1513]
Hi,
I'm using ionic 2 and in this example from [docs](https://angular-meteor.com/api/meteor-rxjs/latest/MeteorObservable#MeteorObservable.subscribe) is probably a mistake if one uses typescript. `this.meteorSubscription` returns `Subscription` type instead of `Observable`

```
  this.meteorSubscription = MeteorObservable.subscribe<any>("myData").subscribe(() => {
          // Subscription is ready!
       });
    }
```

**Comment by dotansimha** [comment]
@msio777 , can you please open an issue in https://github.com/Urigo/meteor-rxjs repository?

Thanks!

**Comment by dotansimha** [comment]
@msio777 
The return value of `MeteorObservable.subscribe` is `Observable`, and then you need to `subscribe` on the return value to get `Subscription`. 
The docs are correct.
