### ISSUE TITLE
alainning:roles importing issue!

### ISSUE THREAD

**Issue by habib786** [Urigo/angular-meteor#1530]
I have used **alanning:role** package by **Meteor**, the Roles are working fine but the problem is I am getting warnings that **"Cannot find name 'Roles"**. Kindly help me with this problem, I have searched it everywhere, some peoples import it like this **"import { Roles } from 'alanning:roles';"** I have also tried this but still getting errors on this... Please help me and please don't commit it as in **"asked issue"**. I am searching this issue from past two days, but I got no answer, please suggest me any help or please resolve this issue, thanks in advance.

**Comment by Urigo** [comment]
@habib786 check out this guide about how to import Atmosphere packages: https://guide.meteor.com/using-atmosphere-packages.html#using-atmosphere

**Comment by suhag007** [comment]
check this answer. http://stackoverflow.com/questions/41314579/alanningrole-importing-issue-in-angular2-meteor
