### ISSUE TITLE
Tutorial: update to latest Meteor

### ISSUE THREAD

**Issue by fiee** [Urigo/angular-meteor#1533]
If I download one of the ZIPs (e.g. `https://github.com/Urigo/meteor-angular2.0-socially/archive/step9.zip`), the project runs after calling `meteor npm install`.
If I follow the advice to `meteor update --patch` (to Meteor 1.4.2.3), the application is crashing due to missing `babel-runtime` and it complains about pure-JavaScript `bcrypt`. When I install both, it runs again.
It would be nice if you could include a hint about this to be expected behaviour - it’s a hurdle for beginners.

**Comment by Urigo** [comment]
The tutorial now uses the latest Meteor 1.6!
https://angular-meteor.com/tutorials/whatsapp2/ionic/privacy
