### ISSUE TITLE
Allow trailing slash in the website URL

### ISSUE THREAD

**Issue by tvvignesh** [Urigo/angular-meteor#1537]
There is an issue with angular-meteor website.
https://angular-meteor.com/ionic-tutorial works
but 
https://angular-meteor.com/ionic-tutorial/ does not

The trailing slash is the only difference which causes the problem. 

Maybe you have to fix your server to allow it.

In https://blog.ionic.io/ionic-and-meteor/ they have linked angular-meteor website with a trailing slash which leads to a 404 error.

**Comment by dotansimha** [comment]
Fixed! Thanks @tvvignesh
