### ISSUE TITLE
Socially step 19 code does not work

### ISSUE THREAD

**Issue by K69G4JRA725W** [Urigo/angular-meteor#1539]
I downloaded the code fromthe tutorial: 
https://angular-meteor.com/tutorials/socially/angular2/3rd-party-libraries

Step 18 code works fine. However step 19 code does not work. The Chrome browser only says "...loading". The console error messages are:
--------------------------------------------------------------------------------------------------------
Unable to resolve some modules:

  "@angular/http" in /D/home/angular/nineteen-meteor-angular2.0-socially/node_modules/@angular/material/material.umd.js (web.browser)

If you notice problems related to these missing modules, consider running:
  meteor npm install --save @angular
-------------------------------------------------------------------------------------------------------------
Then I ran "meteor npm install --save @angular". I got this error message.

npm ERR! addLocal Could not install D:\home\angular\nineteen-meteor-angular2.0-socially\@angular
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@angular"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! path D:\home\angular\nineteen-meteor-angular2.0-socially\@angular
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\home\angular\nineteen-meteor-angular2.0-socially\@angular'
npm ERR! enoent ENOENT: no such file or directory, open 'D:\home\angular\nineteen-meteor-angular2.0-socially\@angular'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

Please resolve this problem,. Thanks!

**Comment by K69G4JRA725W** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@angular' ]
2 info using npm@3.10.9
3 info using node@v4.6.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData @angular
8 silly fetchOtherPackageData @angular
9 silly cache add args [ '@angular', null ]
10 verbose cache add spec @angular
11 silly cache add parsed spec Result {
11 silly cache add   raw: '@angular',
11 silly cache add   scope: null,
11 silly cache add   escapedName: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: '@angular',
11 silly cache add   spec: 'D:\\home\\angular\\nineteen-meteor-angular2.0-socially\\@angular',
11 silly cache add   type: 'local' }
12 error addLocal Could not install D:\home\angular\nineteen-meteor-angular2.0-socially\@angular
13 silly fetchPackageMetaData Error: ENOENT: no such file or directory, open 'D:\home\angular\nineteen-meteor-angular2.0-socially\@angular'
13 silly fetchPackageMetaData     at Error (native)
13 silly fetchPackageMetaData  error for @angular { [Error: ENOENT: no such file or directory, open 'D:\home\angular\nineteen-meteor-angular2.0-socially\@angular']
13 silly fetchPackageMetaData   errno: -4058,
13 silly fetchPackageMetaData   code: 'ENOENT',
13 silly fetchPackageMetaData   syscall: 'open',
13 silly fetchPackageMetaData   path: 'D:\\home\\angular\\nineteen-meteor-angular2.0-socially\\@angular' }
14 silly rollbackFailedOptional Starting
15 silly rollbackFailedOptional Finishing
16 silly runTopLevelLifecycles Finishing
17 silly install printInstalled
18 verbose stack Error: ENOENT: no such file or directory, open 'D:\home\angular\nineteen-meteor-angular2.0-socially\@angular'
18 verbose stack     at Error (native)
19 verbose cwd D:\home\angular\nineteen-meteor-angular2.0-socially
20 error Windows_NT 6.1.7601
21 error argv "C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@angular"
22 error node v4.6.1
23 error npm  v3.10.9
24 error path D:\home\angular\nineteen-meteor-angular2.0-socially\@angular
25 error code ENOENT
26 error errno -4058
27 error syscall open
28 error enoent ENOENT: no such file or directory, open 'D:\home\angular\nineteen-meteor-angular2.0-socially\@angular'
29 error enoent ENOENT: no such file or directory, open 'D:\home\angular\nineteen-meteor-angular2.0-socially\@angular'
29 error enoent This is most likely not a problem with npm itself
29 error enoent and is related to npm not being able to find a file.
30 verbose exit [ -4058, true ]

**Comment by K69G4JRA725W** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@angular' ]
2 info using npm@3.10.9
3 info using node@v4.6.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData @angular
8 silly fetchOtherPackageData @angular
9 silly cache add args [ '@angular', null ]
10 verbose cache add spec @angular
11 silly cache add parsed spec Result {
11 silly cache add   raw: '@angular',
11 silly cache add   scope: null,
11 silly cache add   escapedName: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: '@angular',
11 silly cache add   spec: 'D:\\home\\angular\\nineteen-meteor-angular2.0-socially\\@angular',
11 silly cache add   type: 'local' }
12 error addLocal Could not install D:\home\angular\nineteen-meteor-angular2.0-socially\@angular
13 silly fetchPackageMetaData Error: ENOENT: no such file or directory, open 'D:\home\angular\nineteen-meteor-angular2.0-socially\@angular'
13 silly fetchPackageMetaData     at Error (native)
13 silly fetchPackageMetaData  error for @angular { [Error: ENOENT: no such file or directory, open 'D:\home\angular\nineteen-meteor-angular2.0-socially\@angular']
13 silly fetchPackageMetaData   errno: -4058,
13 silly fetchPackageMetaData   code: 'ENOENT',
13 silly fetchPackageMetaData   syscall: 'open',
13 silly fetchPackageMetaData   path: 'D:\\home\\angular\\nineteen-meteor-angular2.0-socially\\@angular' }
14 silly rollbackFailedOptional Starting
15 silly rollbackFailedOptional Finishing
16 silly runTopLevelLifecycles Finishing
17 silly install printInstalled
18 verbose stack Error: ENOENT: no such file or directory, open 'D:\home\angular\nineteen-meteor-angular2.0-socially\@angular'
18 verbose stack     at Error (native)
19 verbose cwd D:\home\angular\nineteen-meteor-angular2.0-socially
20 error Windows_NT 6.1.7601
21 error argv "C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Administrator.WIN-3D2SKEQRIB1\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@angular"
22 error node v4.6.1
23 error npm  v3.10.9
24 error path D:\home\angular\nineteen-meteor-angular2.0-socially\@angular
25 error code ENOENT
26 error errno -4058
27 error syscall open
28 error enoent ENOENT: no such file or directory, open 'D:\home\angular\nineteen-meteor-angular2.0-socially\@angular'
29 error enoent ENOENT: no such file or directory, open 'D:\home\angular\nineteen-meteor-angular2.0-socially\@angular'
29 error enoent This is most likely not a problem with npm itself
29 error enoent and is related to npm not being able to find a file.
30 verbose exit [ -4058, true ]

**Comment by superrandres** [comment]
Hello, And how did you solve it?

**Comment by K69G4JRA725W** [comment]
The problem is with mdl.  Remove all mdl related stuff, and use another UI framework.
