### ISSUE TITLE
Tutorial stuck on "loading" on android-device

### ISSUE THREAD

**Issue by darkbasic** [Urigo/angular-meteor#1550]
$ meteor run android-device

[...]

=> Started app on Android Device.             
I20170124-23:57:06.153(1)? 01-24 23:57:03.656 13588 13588 I chromium: [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
I20170124-23:57:06.189(1)? 01-24 23:57:04.476 13588 13588 I MeteorWebApp: Serving asset bundle with version: ab78fad63047c6b197998acc2eadd6a6e7e4a30c
I20170124-23:57:12.190(1)? 01-24 23:57:11.525 13588 13588 I chromium: [INFO:CONSOLE(22504)] "Unhandled Promise rejection:", source: http://localhost:12664/packages/modules.js?hash=0fd3175a396bf624c862bb6bfcf0a44a133ca642 (22504)
I20170124-23:57:12.192(1)? 01-24 23:57:11.525 13588 13588 I chromium: [INFO:CONSOLE(22506)] "Error: Uncaught (in promise): Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
I20170124-23:57:12.192(1)? 01-24 23:57:11.525 13588 13588 I chromium: Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
I20170124-23:57:12.192(1)? 01-24 23:57:11.525 13588 13588 I chromium:     at new PathLocationStrategy (http://localhost:12664/packages/modules.js?hash=0fd3175a396bf624c862bb6bfcf0a44a133ca642:54939:23)
I20170124-23:57:12.192(1)? 01-24 23:57:11.525 13588 13588 I chromium:     at provideLocationStrategy (http://localhost:12664/packages/modules.js?hash=0fd3175a396bf624c862bb6bfcf0a44a133ca642:65630:13)
I20170124-23:57:12.193(1)? 01-24 23:57:11.525 13588 13588 I chromium:     at NgModuleInjector.get (/AppModule/module.ngfactory.js:140:77)
I20170124-23:57:12.193(1)? 01-24 23:57:11.525 13588 13588 I chromium:     at NgModuleInjector.get (/AppModule/module.ngfactory.js:145:84)
I20170124-23:57:12.193(1)? 01-24 23:57:11.525 13588 13588 I chromium:     at NgModuleInjector.get (/AppModule/module.ngfactory.js:183:151)
I20170124-23:57:12.193(1)? 01-24 23:57:11.525 13588 13588 I chromium:     at NgModuleInjector.AppModuleInjector.createInternal (/AppModule/module.ngfactory.js:224:60)
I20170124-23:57:12.193(1)? 01-24 23:57:11.525 13588 13588 I chromium:     at NgModuleInjector.create (http://localhost:12664/packages/modules.js?hash=0fd3175a396bf624c862bb6bfcf0a44a133ca642:48938:80)
I20170124-23:57:12.193(1)? 01-24 23:57:11.525 13588 13588 I chromium:     at NgModuleFactory.create (http://localhost:12664/packages/modules.js?hash=0fd3175a396bf624c862bb6bfcf0a44a133ca642:48923:22)
I20170124-23:57:12.194(1)? 01-24 23:57:11.525 13588 13588 I chromium:     at http://localhost:12664/packages/modules.js?hash=0fd3175a396bf624c862bb6bfcf0a44a133ca642:48641:47
I20170124-23:57:12.194(1)? 01-24 23:57:11.525 13588 13588 I chromium:     at ZoneDelegate.invoke (http://localhost:12664/packages/modules.js?hash=0fd3175a396bf624c862bb6bfcf0a44a133ca642:22348:26)", source: http://localhost:12664/packages/modules.js?hash=0fd3175a396bf624c862bb6bfcf0a44a133ca642 (22506)
I20170124-23:57:12.197(1)? 01-24 23:57:11.533 13588 13588 I chromium: [INFO:CONSOLE(1185)] "deviceready has not fired after 5 seconds.", source: http://localhost:12664/cordova.js (1185)
I20170124-23:57:12.197(1)? 01-24 23:57:11.534 13588 13588 I chromium: [INFO:CONSOLE(1178)] "Channel not fired: onDOMContentLoaded", source: http://localhost:12664/cordova.js (1178)

**Comment by darkbasic** [comment]
![angular-meteor-android](https://cloud.githubusercontent.com/assets/1047358/22270755/5a9352b8-e291-11e6-8fb3-e2b4df662098.png)

**Comment by darkbasic** [comment]
I'm using meteor-angular2.0-socially-step11

**Comment by Richard-Hackman** [comment]
same here, 
while I found APP_PATH_HREF already defined in client\index.html, I've defined that again inside client\imports\app\app.module.ts then the error disappeared and got another error as follows:
modules.js?hash=7293439…:56187 EXCEPTION: Error in :0:0 caused by: The selector "app" did not match any elementsErrorHandler.handleError @ modules.js?hash=7293439…:56187......

**Comment by Richard-Hackman** [comment]
@darkbasic hello, have you found any solution for this problem?

**Comment by darkbasic** [comment]
Unfortunately not...

**Comment by Richard-Hackman** [comment]
@darkbasic I have just found one, you need to edit client\main.ts to be like:
```
import 'angular2-meteor-polyfills';

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { Meteor } from "meteor/meteor";
import { AppModule } from './imports/app/app.module';

Meteor.startup(() => {
   platformBrowserDynamic().bootstrapModule(AppModule);
});
```

In the solution I found in stackoverflow they have added the following lines as well which I omitted and the app worked without them as well:
```
import { enableProdMode } from '@angular/core';

enableProdMode();
```
you may take a look here:
http://stackoverflow.com/questions/40077102/app-from-socially-tutorial-with-angular2-stuck-in-loading-page-on-android

I hope that will help you

**Comment by Urigo** [comment]
thank you @darkbasic for solving your own issues for everyone!

please check out the new version of the tutorial
