### ISSUE TITLE
Lazy Loading & Routing

### ISSUE THREAD

**Issue by mragwa** [Urigo/angular-meteor#1553]
Dears, 
I'm trying to make my application some how modular and i don't need to inject all of my modules to app.module at the first start. 
Native angular2 have a great method "Lazy Loading" but when i tried to use, it  doesn't work. 
after a day of search i found that the problem is from meteor itself and it doesn't support angular2 lazy loading. 
I'm asking when we can use it or if any one have some hacks to work around it ? 
also what i can do to config meteor type script compiler so i can add some loaders like [angular-router-loader](https://github.com/brandonroberts/angular-router-loader)
Finally if you have any other logical solution for my app routing structure it will be helpful: 
My app structure:
![modules](https://cloud.githubusercontent.com/assets/5574454/22366099/88f40df2-e483-11e6-93ab-5666b08c0393.jpg)

Regards.

**Comment by sdarnell** [comment]
FYI There's an example of lazy loading of modules with Meteor 1.5 at: https://github.com/joerex/angular-meteor-lazy-load

**Comment by Urigo** [comment]
Check out the new examples for using lazy loading the dynamic imports here - 
https://github.com/Urigo/angular-meteor/tree/master/examples/MeteorCLI

https://github.com/Urigo/angular-meteor/tree/master/examples

we've also published new [angular-compilers  package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers).
It supports:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

Please open a new issue if you encountered one.
