### ISSUE TITLE
[tutorial] Cannot install angular2-google-maps

### ISSUE THREAD

**Issue by darkbasic** [Urigo/angular-meteor#1554]
meteor npm install angular2-google-maps --save
socially@ /home/niko/WebstormProjects/socially
├── UNMET PEER DEPENDENCY @angular/common@2.1.2
├── UNMET PEER DEPENDENCY @angular/core@2.1.2
└── angular2-google-maps@0.17.0 

npm WARN angular2-google-maps@0.17.0 requires a peer of @angular/common@^2.3.1 but none was installed.
npm WARN angular2-google-maps@0.17.0 requires a peer of @angular/core@^2.3.1 but none was installed.

**Comment by zee92** [comment]
meteor npm install angular2-google-maps --savesocially@ /home/niko/WebstormProjects/socially├── UNMET PEER DEPENDENCY @2.1.2├── UNMET PEER DEPENDENCY @2.1.2└── angular2-google-maps@0.17.0npm WARN angular2-google-maps@0.17.0 requires a peer of @^2.3.1 but none was installed.npm WARN angular2-google-maps@0.17.0 requires a peer of @^2.3.1 but none was installed
--

**Comment by Urigo** [comment]
@darkbasic made it work in the new tutorial!
