### ISSUE TITLE
Long initial loading times on Android

### ISSUE THREAD

**Issue by tseck** [Urigo/angular-meteor#1559]
Hi there,

I am experiencing long loading times of the tutorial apps on Android. Reading and trying out different posts on SO and github did not really solve the problem.
Specifically when I just take the ```meteor create test``` app and deploy it, it loads in about 2 seconds, adding just the necessary meteor- and npm-packages for angular-meteor from the socially tutorial (angular 1.5) will yield a loading time of 8-12 seconds on Android 5.
Also the ```meteor-angular2.0-socially``` app takes 8 seconds without the ```launch-screen```package that lengthens the loading time.
On an iPhone it seems to be more user friendly, only 4-7 seconds.
Also this probably leads to the ```deviceready has not fired after 5 seconds.``` log-output.
Is it because the packages (```angular``` and ```angular-meteor``` npm and ```pbastowski:angular-babel``` and ```urigo:static-templates```) need longer loading time or some initialization delay?

Can anyone help me with this issue?

Also other sources (e.g. https://forums.meteor.com/t/meteor-cordova-startup-time/6266/3 or https://forums.meteor.com/t/ridiculously-slow-startup-time-on-meteor-ios-cordova-application-localmarket/22718) could not help.

I posted here since the loading times slowed down when I added angular.

**Comment by kombadzomba** [comment]
Any words on this one? We have the same problem. Our angular2+meteor prokect load time on android os around 15s! It is impossible to use it.

**Comment by tseck** [comment]
There should be lazy loading and asynchronous Imports now in meteor 1.5 but
we switched to react native actually.
Eg oclazyload etc

Miloš Micić <notifications@github.com> schrieb am Sa. 6. Mai 2017 um 14:22:

**Comment by sephiroth56** [comment]
no solution ?? same boat

**Comment by Urigo** [comment]
Check out the new examples for using lazy loading the dynamic imports here - 
https://github.com/Urigo/angular-meteor/tree/master/examples/MeteorCLI

https://github.com/Urigo/angular-meteor/tree/master/examples

we've also published new [angular-compilers  package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers).
It supports:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

Please open a new issue if you encountered one.
