### ISSUE TITLE
 update failed: MongoError: not okForStorage

### ISSUE THREAD

**Issue by catsoft** [Urigo/angular-meteor#156]
Hi. When I add my html ng-repeat="order in customer.book.orders" get this error on browser console ' update failed: MongoError: not okForStorage' if I try to update something. Currently I solved this by adding a watch on 'customer.book.orders' and set a copy of values to scope with angular.copy. But it doesn't feel right. The dot notation should work but somehow it does not. push and slice also does not work properly in this situation. I have to write extra logic because I need update  and track the changes on this array.Do you know something about it ?

**Comment by Urigo** [comment]
I think I know what's the reason and where is the problem..

Can you create a repo that reproduces this so I can run, check and fix this?

**Comment by Urigo** [comment]
@catsoft any chances to get a reproduction?

**Comment by Urigo** [comment]
@catsoft just tested it with the new version and it works fine.
Let me know if it doesn't work for you
