### ISSUE TITLE
angular 2 meteor 'whatsapp' clone is not working at step '4. Realtime Meteor Server ' -- 404 error with http://localhost:3000/sockjs/info

### ISSUE THREAD

**Issue by TarunKala** [Urigo/angular-meteor#1566]
Hi,

i have fallowed the steps as in https://angular-meteor.com/tutorials/whatsapp2/ionic/meteor-server-side.

but after setting up realtime meteor server with mongo DB --  data is not loading and,
Console shows the following error(which is continuously hitting):

_

Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/sockjs/info?cb=8gic9r08wc
_

im running the ionic server on port 3000 which will be same for meteor(api)

Any idea whats the reason for this issue
![meteorbug](https://cloud.githubusercontent.com/assets/22730778/23105331/93803812-f703-11e6-87b6-57ec7ccf32e6.png)

**Comment by mordka** [comment]
I bet the same port (3000) can't be used simultaneously. Probably meteor server failed to start at port 3000.
Leave the Ionic port default (8100) and let meteor server run at default (3000). This is a good starting point.

**Comment by SebastienGarciaz** [comment]
Same problem

**Comment by bdeshaz** [comment]
Doesn't seem meteor is starting up. I believe meteor starts up via the meteor-client bundler, but this doesn't seem to be happening. The dev server will run  :8100 after ionic serve _i'm using ionic serve -l_ , but :3000 doesn't not seem to be starting @Urigo

**Comment by Urigo** [comment]
We've updated the tutorial and all looks ok.
Please open a new issue if that is not the case
