### ISSUE TITLE
Login with external services opens browser outside the app

### ISSUE THREAD

**Issue by ingleo** [Urigo/angular-meteor#1567]
Hi,

I'm trying to login with external services (facebook, twitter, google) from the ionic application client, but when I execute the methods Meteor.loginWith... the login form opens outside the app and the session becomes active in the browser but not in the app.

In my component i have this method:
```javascript
loginWithFacebook() {
        Meteor.loginWithFacebook({ requestPermissions: ['public_profile', 'email'], loginStyle: 'popup' }, (err) => {

            this.zone.run(() => {
                if (err) {
                    this.error = err;
                } else {
                    console.log('done');
                }
            });
        });
    }

loginWithTwitter() {
        Meteor.loginWithTwitter({ requestPermissions: [], loginStyle: 'popup'}, (err) => {
            this.zone.run(() => {
                if (err) {
                    this.error = err;
                } else {
                    console.log('done');
                }
            });
        });
    }
```

Here is my meteor-client.config.json
```
{
  "runtime": {
    "meteorEnv": {},
    "DDP_DEFAULT_CONNECTION_URL": "http://192.168.0.5:3000",
    "ROOT_URL": "http://192.168.0.5:3000"
  },
  "import": [
    "meteor-base@1.0.4",
    "accounts-base",
    "accounts-password",
    "accounts-facebook",
    "accounts-twitter",
    "accounts-google",
    "service-configuration",
    "underscore",
    "meteor",
    "modules-runtime",
    "modules",
    "promise",
    "babel-runtime",
    "ecmascript-runtime",
    "ecmascript",
    "base64",
    "ejson",
    "jquery",
    "check",
    "random",
    "tracker",
    "retry",
    "id-map",
    "ordered-dict",
    "geojson-utils",
    "diff-sequence",
    "mongo-id",
    "minimongo",
    "ddp-common",
    "ddp-client",
    "ddp",
    "allow-deny",
    "reactive-var",
    "mongo"
  ],
   "export": {
    "ddp": ["DDP"],
    "meteor": ["Meteor"],
    "mongo": ["Mongo"],
    "tracker": ["Tracker"],
    "underscore": ["_"],
    "accounts-base": ["Accounts"]
  }
}
```
I'm using these versions
```
Meteor 1.4.2.6 
Angular2 Version: 2.2.1
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
OS: Linux 4.4
Node Version: v6.9.5
```
I appreciate any help! 
Regards.

**Comment by jycouet** [comment]
Hi, did you try:
`loginStyle: 'redirect'`?

**Comment by ingleo** [comment]
Hi,
I tried with ```loginStyle: 'redirect'``` but it still opens the register form outside the browser.
Regards.

**Comment by ingleo** [comment]
Update: I'm still looking for a solution and found this:
To open the form to register with external services inside de app, in the file config.xml of ionic project, put this line to let the Webview can open URLs itself
```html
<allow-navigation href="http://*/*" />
```
Additionally, in ServiceConfiguration I added the loginStyle: 'redirect' suggested by @jycouet 

```javascript
ServiceConfiguration.configurations.insert({
    service: 'twitter',
    consumerKey: 'XYZ',
    secret: 'XYZ',
    loginStyle: "redirect"
});
```
It seems that the problem is in when the callback is done, the window redirects to the server's ip and the ionic app is not able to get the final response, the server console show the error:

```console
W20170222-15:34:45.409(-5) (oauth.js:431) Error in OAuth Server: redirectUrl (file:///android_asset/www/index.html) is not on the same host as the app (http://192.168.0.5:3000/)
```
Anybody have the solution?

Regards

**Comment by Eraldo** [comment]
Same problem here. :|
I get "Error: Must pass options.rootUrl or set ROOT_URL in the server environment" when trying to log in with google. The strange thing is that I do have set that variable in the server environment and it still does not seem to find it. Could it be that it is due to the meteor bundling process not taking it into account?

**Comment by Eraldo** [comment]
If I set the client ROOT_URL to `http://localhost:8100` and use:
```typescript
Meteor.loginWithGoogle({loginStyle: 'redirect', 'redirectUrl': 'http://localhost:8100'}, (e: Error) => {
```
=> I get: `Cannot GET /_oauth/google?close&state=eyJsb2dpblN...`
Which makes sense since ionic gets the redirect callback and does not know what to do with it.

If I set ROOT_URL client to `http://localhost:3000` and use:
```typescript
Meteor.loginWithGoogle({loginStyle: 'redirect', 'redirectUrl': 'http://localhost:3000'}, (e: Error) => {
```
=> I get a blank popup.

If I set ROOT_URL client to `http://localhost:3000` and use:
```typescript
Meteor.loginWithGoogle({loginStyle: 'popup', 'redirectUrl': 'http://localhost:3000/_oauth/google?close'}, (e: Error) => {
```
=> I get a popup page including the credential secret (server response).
```html

<!DOCTYPE html>
<html>
<body>
  <p id="completedText" style="display:none;">
    Login completed. <a href="#" id="loginCompleted">
      Click here</a> to close this window.
  </p>

  <div id="config" style="display:none;">{"setCredentialToken":true,"credentialToken":"Eh...","credentialSecret":"AH...","storagePrefix":"Meteor.oauth.credentialSecret-","isCordova":false}</div>
  <script type="text/javascript" src="/packages/oauth/end_of_popup_response.js"></script>
</body>
</html>
```
If I close that popup, I get:
```
errorClass {message: "No matching login attempt found", errorType: "Accounts.LoginCancelledError", stack: "Accounts.LoginCancelledError↵    at convertError (…e (http://localhost:8100/build/main.js:129107:12)"}
```

Conclusion:
I still don't know how to get it to work. :|

**Comment by Eraldo** [comment]
I tried moving the `Meteor.loginWithGoogle` method to the server and calling it via a meteor method. However, I get ...
```
I20170308-11:21:57.821(1)? Exception while invoking method 'loginGoogle' TypeError: Meteor.loginWithGoogle is not a function
I20170308-11:21:57.821(1)?     at [object Object].Meteor.methods.loginGoogle (server/methods.ts:12:12)
I20170308-11:21:57.822(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20170308-11:21:57.822(1)?     at packages/ddp-server/livedata_server.js:711:19
I20170308-11:21:57.822(1)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170308-11:21:57.822(1)?     at packages/ddp-server/livedata_server.js:709:40
I20170308-11:21:57.822(1)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170308-11:21:57.822(1)?     at packages/ddp-server/livedata_server.js:707:46
I20170308-11:21:57.823(1)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:681:23)
I20170308-11:21:57.823(1)?     at packages/ddp-server/livedata_server.js:551:43
```
So I guess that method is not available on the server? (stange)
Any ideas what is going on there or how to get the social login to work?

**Comment by ingleo** [comment]
I try putting the code on the server too, and did not work, I don't know what more i can do with this issue, pleas anybody have any idea about it? 
Really appreciate any idea or workaround.

**Comment by Eraldo** [comment]
I did some research and thought using the in-app browser might be an option.
Here is an article showing how it can be done: https://www.thepolyglotdeveloper.com/2014/07/using-oauth-2-0-service-ionicframework/

I still see some challenges however.

Please update if one of you managed to do it.

**Comment by fernandoarevalo** [comment]
Hi!

I have same problem... I tried to get the session in mobile app but wasn't possible, the ionic native facebook implementation "https://ionicframework.com/docs/native/facebook/" works fine but require create a different model or just adjust meteor model to insert an user and connect with it

Regards

**Comment by darkbasic** [comment]
Please have a look at my latest post here: https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/40

InAppBrowser works fine with Cordova, but it isn't compatible with Browser. See my post here: https://forum.ionicframework.com/t/issue-inappbrowser-invalid-event-target/88548/15

**Comment by ingleo** [comment]
I'm going to close this issue because it has been resolved, look this post Urigo/Ionic2CLI-Meteor-WhatsApp#92, clarifying that is only for facebook login.
