### ISSUE TITLE
Property 'default_connection' does not exist on type 'typeof Meteor'

### ISSUE THREAD

**Issue by atd** [Urigo/angular-meteor#1571]
Meteor.default_connection is not included in Meteor type

### When reporting a bug, please be sure to include the following:
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)

Just add Meteor.default_connection to any component

- [ ] What version of `angular-meteor` you're using, and the platform(s) you're running it on

angular2-compilers@0.6.6

- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior

Meteor shows the following message:

```
client/imports/frontpage/frontpage.component.ts (89, 44): Property 'default_connection' does not exist on type 'typeof Meteor'.
```

I would expect the method to exist in Meteor type

**Comment by sdarnell** [comment]
Presumably you're referring to the typings? Sadly they're a bit out of date.
But Meteor.default_connection is a REALLY old name that is only a legacy value, it was renamed Meteor.connection.

On the server, Meteor.connection is null, but on the client you could work around the problem using an any cast or using Meteor['connection'].

It may be best to raise the issue at: https://github.com/meteor-typings/meteor

**Comment by atd** [comment]
Thank you for the clarifications @sdarnell 

I am using `Meteor['connection']` for now and opened the issue at https://github.com/meteor-typings/meteor/issues/31
