### ISSUE TITLE
$scope.$apply doesn't work in reactively context 

### ISSUE THREAD

**Issue by nmarmon** [Urigo/angular-meteor#1575]
Hi there,
I am using $scope.$apply in reactively context, but the view is not refresh. I can use $scope.$apply in tthat kind of context?. And if it is possible, how I can refresh the DOM intentionaly? And if it is impossible, is there other thing that I can use instead of $scope.$apply? Regards

**Comment by nmarmon** [comment]
Hi again, I think I need to use $bindToContext, according to this thread: https://forums.meteor.com/t/scope-apply-in-meteor-angular/24388. Now I need more information about it because in the docs: https://angular-meteor.com/api/angular-meteor/1.3.6/reactive-context there is not much information. Can anyone expalin it in a more clear way? Thanks

**Comment by nmarmon** [comment]
I have the next code:

this.userPart = null;
$scope. $ On ('user-participate', function () {
    that._getParticipation (that. $bindToContext (that._getCurrentParticipation));
});

I have two functions: _getParticipation () to which I want (and pass) a callback, in this case _getCurrentParticipation ().

When I receive the onuserparticipe event (when the user is logged in), I execute _getparticipation() and collects the user participation data and if there is the _getcurrentparticipation() callback will be executed, for the purpose of changing this.userPart to undefined or 0 for show different elements.

The flow works fine and this.userPart changes its value but I can not update the view in any way.

1- I've tried removing the $reactive(this).attach ($scope); And use $scope.$apply () and it does not work.
2- I have tried as shown in the example to use this.$bindToContext () passing the callback that changes the value of this.userPart and also, although I do not understand the behavior of $bindToContext() and maybe I'm not using it well.

Can you help me with this, please?

Thank you!!

**Comment by ardatan** [comment]
`angularjs` example and use of new `angular-compilers` has been changed. You can check it out new example, and open a new issue if you still have these errors.
https://github.com/Urigo/angular-meteor/tree/master/examples/angularjs
