### ISSUE TITLE
npm packages support angular-meteor

### ISSUE THREAD

**Issue by jinzhiqiang** [Urigo/angular-meteor#1576]
hi all, I 'm finding a framework for my project. angular-meteor is very good, maybe it can help me. but I have a problem, how to setup a npm module support angular-meteor?

**Comment by Urigo** [comment]
If you are using the Meteor in a project that is compiled separately from Meteor, for example using the Angular CLI, you should use [meteor-rxjs](https://github.com/urigo/meteor-rxjs) and [meteor client bundler](https://github.com/Urigo/meteor-client-bundler).
Here is an example project: https://github.com/Urigo/angular-meteor/tree/master/examples/angularcli-meteor
