### ISSUE TITLE
'Unexpected token export' when angular2-compliers puts node_modules together

### ISSUE THREAD

**Issue by Slavrix** [Urigo/angular-meteor#1578]
I'm converting an old angular2 project over to use meteor to act as an admin panel style thing for a project that is based off the ionic2-meteor whatsapp tutorial.

So I'm building the website in the client folder inside api.

I'm pretty sure I've got things correct (based off the old socially tutorial) for the angular2 client.

I'm getting these as errors though.

```
modules.js:13538 Uncaught SyntaxError: Unexpected token export
es5-shim.js:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at es5-shim.js:17
    at es5-shim.js:2789
promise.js:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at promise.js:17
    at promise.js:582
ecmascript-runtime.js:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at ecmascript-runtime.js:17
    at ecmascript-runtime.js:4630
babel-runtime.js:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at babel-runtime.js:17
    at babel-runtime.js:160
random.js:18 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at random.js:18
    at random.js:368
```
I imagine that I have probably missed an import or something somewhere but can't work out where.

Any help would be awesome.

These are the packages I have installed.

```
meteor-base@1.0.4            
mobile-experience@1.0.4       
mongo@1.1.15                   
reactive-var@1.0.11            
jquery@1.11.10                 
tracker@1.1.2
standard-minifier-css@1.3.3
standard-minifier-js@1.2.2
es5-shim@4.6.15
ecmascript@0.6.3
shell-server@0.2.2
angular2-compilers
barbatus:typescript
accounts-base@1.2.14
npm-bcrypt@0.9.2
accounts-password@1.3.4
reywood:publish-composite
http@1.2.11
alanning:roles
check@1.2.4
dispatch:mocha-phantomjs
tmeasday:publish-counts
hwillson:stub-collections
practicalmeteor:mocha
xolvio:cleaner
```

~Edit

the error comes from @angular/http module, I'm going to try rolling it back to see if it helps.

```
export var QueryEncoder = (function () {//<---- this is the line causing the error
    function QueryEncoder() {
    }

    QueryEncoder.prototype.encodeKey = function (k) { return standardEncoding(k); };

    QueryEncoder.prototype.encodeValue = function (v) { return standardEncoding(v); };
    return QueryEncoder;
}());
```
rolling back and forward didn't help at all.

Wasn't sure if this could be a bug or not so I posted it here.

**Comment by c4wrd** [comment]
Check for any usages of Tracker or MeteorComponent in your files. I had an issue where if you used Tracker without importing I'd receive the same error, or any usage of MeteorComponent would result in the same error. For Tracker, just import it, or use the new MeteorReactive.
