### ISSUE TITLE
Javascript code rendered in view in 0.6.1

### ISSUE THREAD

**Issue by fredrikekelund** [Urigo/angular-meteor#158]
After updating to 0.6.1, I'm seeing JS code in my template. The code:

```js
(function(){angular.module('angular-meteor').run(['$templateCache', function($templateCache) {$templateCache.put('client/views/login.tpl', '');}]); })();
```

Screenshot:

![](https://owncloud.fredrik.computer/index.php/apps/files_sharing/ajax/publicpreview.php?x=1855&y=985&a=true&file=angular-meteor%2520error.png&t=632eece627ec6e2ee350ef94400b937f&scalingup=0)

**Comment by Urigo** [comment]
Is it because you haven't initialized your AngularJS app yet?

Like:

    angular.module('socially',['angular-meteor']);

**Comment by fredrikekelund** [comment]
I think this might have been a problem with my browser's template cache. Tried upgrading again and the problem went away :confused:

**Comment by fredrikekelund** [comment]
The problem just returned actually. And @Urigo no, I'm initializing the app like so:

```js
var app = angular.module("DataTool", [
	"ngAnimate",
	"angular-meteor",
	"ng-context-menu"
]);
```

```html
<body>
	<div class="u-fullWidth u-fullHeight" ng-app="DataTool">
	</div>
</body>
```

I tried manually bootstrapping the app as well, but that gives me the same result.

**Comment by fredrikekelund** [comment]
Okay, I found out what I think is the problem.

In my `index.html` (which ties together my tpl files), I use `ng-include` to render my Angular templates. I referenced the src to every tpl file as a URL relative to the path root (**meaning it starts with a "/"**), and it seems Meteor was unable to match this path to the path registered for the compiled tpl files. Removing the leading forward slash from the URL resolved the issue for me.

I might add a note in the README and docs about this. @Urigo, you think that's sufficient?

**Comment by Urigo** [comment]
Yes, where would you put it?
Do you want to PR it?

**Comment by netanelgilad** [comment]
I don't think this is a meteor issue. I think this is how angular resolved the templateUrls from the templateCache. It just matched the id of a template in the templateCache with the requested url as is. That means that you have to reference your templates exactly the way angular-meteor adds them (but I may be mistaken here about this whole issue..).
If this is indeed the case than the README needs to state that referencing templates is done by the full template url and starting from the base project folder (without a leading slash).

**Comment by Urigo** [comment]
Exactly

**Comment by Urigo** [comment]
Closing for now but @fredrikekelund would love your pull request on the readme file!
