### ISSUE TITLE
How can I update angular to the latest version (1.3.10) and is it safe?

### ISSUE THREAD

**Issue by smoke** [Urigo/angular-meteor#159]
I see that this package is installing angular 1.3.8 - how can I have the latest version e.g. via mquandalle:bower and is it safe?

**Comment by Urigo** [comment]
You can use the [meteor-bower package](https://github.com/mquandalle/meteor-bower) and just request the Angular 1.3.10.
This is totally safe.
Soon we are going to remove angular bower package from our package so that you will be able to easily use any angular version you want.

Please re-open if there is a problem

**Comment by smoke** [comment]
I just tested with the latest version - and currently it is not possible.

What I did:
* installed angular-meteor following the instructions
* setup bower - add .bowerc as recommended with { "directory" : ".meteor/local/bower" }
* bower init to create valid bower.json
* bower install angular --save

The result in the browser console is the following:
```
WARNING: Tried to load angular more than once.
angular.version
Object {full: "1.3.8", major: 1, minor: 3, dot: 8, codeName: "prophetic-narwhal"}
```

Apparently angular-meteor is installing and expecting angular.js in separate location and/or bower can not properly resolve the case.

What I did as a temporary workaround - I created a fork of angular-meteor, cloned it in packages/ and installed it. This way I am able to control the angular version via packages/angular-meteor/smart.json

So this is an issue.

As for the rest of the package - great job, thank you!

**Comment by Urigo** [comment]
Reopening.

will look on it later this week

**Comment by Tim-W** [comment]
Any update on this? Would love to be able to use 1.3.11.

**Comment by Urigo** [comment]
yes, @netanelgilad is working on a meteor-bower pull request that will help you do that very easily.
Will update in a couple of days

**Comment by Urigo** [comment]
Hi, don't think I forgot about it!

I've just added 1.3.12 and will release a new version today to tomorrow.

The reason I'm slow with this is that we found a lot of issues in meteor-bower and also in the why meteor itself chooses package versions.
I'm talking to Meteor core devs about it and hopefully soon there will be a much better solution for that.

**Comment by Urigo** [comment]
The new version has been released
