### ISSUE TITLE
Link to tutorial from README -> 404

### ISSUE THREAD

**Issue by atbe** [Urigo/angular-meteor#1591]
The link in the README http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping:

`If you are new to Angular2 and/or Meteor but want to learn them quickly, please check out our 23-steps Angular2-Meteor [tutorial](http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping)`

leads to a 404. 

Has the page been moved?

**Comment by Urigo** [comment]
fixed.
thank you for the feedback @atbe !
