### ISSUE TITLE
[barbatus:scss-compiler] simplify use of Ionic SCSS through fourseven:scss/PR244

### ISSUE THREAD

**Issue by ghybs** [Urigo/angular-meteor#1598]
### Feature request:
- [x] A descriptive title

- [x] An overview of the suggested solution

    Pull https://github.com/fourseven/meteor-scss/pull/244 into `barbatus:scss-compiler`.

- [x] A description of the problem you're trying to solve, including *why* you think this is a problem

    Currently [`fourseven:scss`](https://github.com/fourseven/meteor-scss) package as well as the angular2-meteor fork [`barbatus:scss-compiler`](https://github.com/barbatus/meteor-scss) only implement local path and explicit module path resolutions, typically for `{}/node_modules/`.

    Unfortunately, some 3rd party SCSS files expect a global `includePaths` set, typically through webpack config (e.g. Ionic and Bootstrap). This leads for example to the need to customize the SCSS files (see [section 1.10 "Ionic-2"](https://angular-meteor.com/tutorials/whatsapp2/meteor/setup#ionic-2) of step 1 of WhatsApp Clone with Ionic 2 and Meteor CLI), just to replace [these 2 lines](https://github.com/Urigo/Ionic2-MeteorCLI-WhatsApp/blob/da6ccca1224add19fb7491444c138574099a39f4/client/imports/theme/ionicons.scss#L8-L9):
    ```scss
    @import "ionicons-icons";
    @import "ionicons-variables";
    ```
    By:
    ```scss
    @import "{}/node_modules/ionicons/dist/scss/ionicons-icons";
    @import "{}/node_modules/ionicons/dist/scss/ionicons-variables";
    ```
    As usual, this duplication leads to maintenance burden (any modification in Ionic has to be reflected here), with some issues reported here just for that (e.g. https://github.com/Urigo/angular-meteor/issues/1593)

    However I recently pushed https://github.com/fourseven/meteor-scss/pull/244 that takes an `scss-config.json` file at the root of the Meteor project to specify such a global `includePaths` array. With this new functionality, there is no longer need to duplicate most of Ionic SCSS files, just to specify the `{}/node_modules/ionicons/dist/scss/` includePath in that config file.

    Therefore, by also pulling this functionality into `barbatus:scss-compiler`, we could highly simplify the tutorial, and obviously all angular2-meteor apps that use such libraries as Ionic.
- [x] If the feature changes current behavior, reasons why your solution is better

    Highly simplifying the tutorial and all angular2-meteor apps that use such libraries as Ionic.

=> Would you accept a PR on [`barbatus:scss-compiler`](https://github.com/barbatus/meteor-scss) repo to implement this functionality, then publish it on Atmosphere?

(note: filing a feature request on this repo, as issues seem to be disabled in `barbatus:scss-compiler` repo)

**Comment by Urigo** [comment]
we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6.

Please open a new issue if you encountered one.
