### ISSUE TITLE
Subscriptions not working for local mongo

### ISSUE THREAD

**Issue by jerradpatch** [Urigo/angular-meteor#1600]
The issue in summary is that the local meteor mongo instance is not returning data. I have connected to the data base with the CLI and seen that data was there. However, it seems the server is fetching nothing. I can connect to a remote DB and the exact same code works just find. Furthur described below. Thanks much. 

Currently using meteor RXJS I have had a similar issue before and it was due to packages being out of sync. So, I had thought that "meteor update" was supposed to handle package version management, but I sometimes notice this is not the case. Let me know whats up with this setup, if you would be so kind.

##Collection.ts
```typescript
init(){

if(!this.Model) {
            this.Model = new MongoObservable.Collection<ModelOuNeRe>('OuNeRe', {idGeneration: 'MONGO'});
            this.Model.allow({
                insert() {
                    return false;
                },
                update() {
                    return false;
                },
                remove() {
                    return false;
                }
            });
        }

    if(Meteor.isServer) {

            var model = this.Model;
            console.log("FETCHED ", this.Model.find({}).cursor.fetch());
            Meteor.publish('OuNeRe_subscribeTop20',
                function() {
                    CommonLogic.debug(this, "calling, OuNeRe:OuNeRe_subscribeTop20");
                    var found = model.find({ videoType: { $not: { $eq: 'featured' } } } , {
                        limit:100
                    });
                    CommonLogic.debug(this, "returning, OuNeRe:OuNeRe_subscribeTop20 found"+found.cursor.count());

                    return found;
                });
    }
}
```
This code returns no data in the console.log('FETCHED... when run with
```bash
npm run dev
```
##Package.json
```json
"scripts": {
    "dev": "meteor -p 3000 --settings settings-dev.json"
}
```
##setting-dev.json (modified Keys)
```json
{
	"public": {
		"mode" : "dev",
		"ga": {
			"account" : "UA-892efefwef2f1",
			"debug": true
		},
		"google":{
			"appId": "103674456-eid7pvjbvqm4nmv41nnvamjv8k048dg.apps.googleusercontent.com"
		},
		"facebook":{
			"appId": "176406924234240800"
		}
	},
	"private":{
		"google":{
			"appId": "10361123423235356-feid7pvjbvqm4nmv41nnvamjv8k048dg.apps.googleusercontent.com",
			"secret": "uVP7FmbA8J_1m_uZL3vDjxFS"
		},
		"facebook":{
			"appId": "1764069afwefa8012304800",
			"secret": "4cc23d67jjiuikkiiio7aff7eab88ii88if1c8"
		}
	}
}
```

Now when I run the exact same code with a remote mongoDB specifying mongo-url and oplog-url, console.log("FETCHED... Returns the full list for data.

```bash
"MONGO_URL=mongodb://xxxxx:yyyyy@coolness:user@collness.server:2345/someplace MONGO_OPLOG_URL=mongodb://xxxxx:yyyyy@coolness:user@collness.server:2345/local?authSource=AuthDatabase meteor --settings settings-prod.json",
```
As you can see I am running the meteor instance locally and specifying a remote DB. The settings-prod.json is just prod app keys (Almost the same as dev-settings)

#Versions of deps: Meteor Packages
accounts-base                 1.2.17* A user account system
accounts-facebook          1.1.1* Login service for Facebook accounts
accounts-google              1.1.2* Login service for Google accounts
accounts-twitter               1.2.1* Login service for Twitter accounts
angular2-compilers          0.6.6  Angular 2 Templates, HTML and TypeScript compilers for Meteor
ecmascript                       0.7.3  Compiler plugin that supports ES2015+ in all .js files
es5-shim                          4.6.15  Shims and polyfills to improve ECMAScript 5 support
fortawesome:fontawesome    4.7.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
meteor-base                    1.0.4  Packages that every Meteor app needs
mobile-experience           1.0.4  Packages for a great mobile user experience
mongo                             1.1.17  Adaptor for using MongoDB and Minimongo over DDP
reactive-var                     1.0.11  Reactive variable
reywood:publish-composite  1.5.2  Publish a set of related documents from multiple collections with a reactive join
service-configuration      1.0.11  Manage the configuration for third-party services
shell-server                     0.2.3  Server-side component of the `meteor shell` command.
standard-minifier-css      1.3.4  Standard css minifier used with Meteor apps by default.
standard-minifier-js         2.0.0  Standard javascript minifiers used with Meteor apps by default.
tracker                             1.1.3  Dependency tracker to allow reactive callbacks
vsivsi:file-collection         1.3.8  Collections that efficiently store files using MongoDB GridFS, with built-in HTTP support

#Versions of deps: Package.json
```json
{
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@angular/animations": "^4.1.1",
    "@angular/common": "^4.1.1",
    "@angular/compiler": "^4.1.1",
    "@angular/compiler-cli": "^4.1.1",
    "@angular/core": "^4.1.1",
    "@angular/forms": "^4.1.1",
    "@angular/http": "^4.1.1",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.1.1",
    "@angular/platform-browser-dynamic": "^4.1.1",
    "@angular/platform-server": "^4.1.1",
    "@angular/router": "^4.1.1",
    "@angular2-material/card": "^2.0.0-alpha.8-3",
    "@angular2-material/checkbox": "^2.0.0-alpha.8-3",
    "@angular2-material/core": "^2.0.0-alpha.8-3",
    "angular2-meteor": "^0.7.1",
    "angular2-meteor-accounts-ui": "^1.0.0",
    "angular2-meteor-auto-bootstrap": "^0.6.0",
    "angular2-meteor-polyfills": "^0.2.0",
    "babel-runtime": "^6.23.0",
    "bcrypt": "^1.0.2",
    "es6-promise": "^4.1.0",
    "meteor-node-stubs": "^0.2.6",
    "meteor-rxjs": "^0.4.7",
    "meteor-typings": "^1.3.1",
    "moment": "^2.18.1",
    "ng-lazyload-image": "^3.1.1",
    "ng2-material": "^0.8.1",
    "ngx-bootstrap": "^1.6.6",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.4.0",
    "validate.js": "^0.11.1",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "@types/meteor": "^1.4.1",
    "@types/meteor-accounts-phone": "0.0.5",
    "@types/meteor-publish-composite": "0.0.32",
    "@types/underscore": "^1.8.0",
    "meteor-typings": "^1.3.1"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by rrubio** [comment]
I had the same issue under development and also tried setting it up under "package.json/script", at the end i ran the following from the command line:

# MONGO_URL=mongodb://xxxxx:yyyyy@coolness:user@collness.server:2345/someplace meteor

The above works fine under dev, have not tried it under production yet.

**Comment by Urigo** [comment]
is this still an issue with the latest versions?

if so, could you open a new issue with a simple example repo or a failing test?  
we would get that fixed immediately!

thank you
