### ISSUE TITLE
Wrong types for .forEach()

### ISSUE THREAD

**Issue by Deadly0** [Urigo/angular-meteor#1605]
```
FlatCollection.find(query).forEach(flat => {
	if (type === 'flats') {
		flat.position = value;
	}
	else {
		flat.floorId = value;
	}
	delete flat._id;
	FlatCollection.insert(flat);
});
```
This code gives following errors:
```
Property 'position' does not exist on type 'Flat[]'.
Property 'floorId' does not exist on type 'Flat[]'.
Property '_id' does not exist on type 'Flat[]'.
Argument of type 'Flat[]' is not assignable to parameter of type 'Flat'.
```

Compiler expects type `Float[]` but variable `flat` have type `Flat`

**Comment by sdarnell** [comment]
Could it be a simple mistake?  Should find() be findOne()?

Here are the type definitions (from typings for meteor):
```
    find(selector?: Selector | ObjectID | string, options?: {
      sort?: SortSpecifier;
      skip?: number;
      limit?: number;
      fields?: FieldSpecifier;
      reactive?: boolean;
      transform?: Function;
    }): Cursor < T > ;
    findOne(selector?: Selector | ObjectID | string, options?: {
      sort?: SortSpecifier;
      skip?: number;
      fields?: FieldSpecifier;
      reactive?: boolean;
      transform?: Function;
    }): T;
```
Note that find() returns a Cursor<T> whereas findOne() returns a T.

**Comment by sdarnell** [comment]
The key question is which typing definitions are wrong for you, or whether tsc is just getting a bit confused and falling back to any.
I'd suggest breaking it up to be as simple as possible, e.g.:
```
let cursor = FlatCollection.find(query);
cursor.forEach(flat => { ... });
```
Then adding types as to see where it goes wrong.
```
let cursor: Mongo.Cursor<Flat> = FlatCollection.find(query);
cursor.forEach(flat => { ... });
```
and
```
let cursor: Mongo.Cursor<Flat> = FlatCollection.find(query);
cursor.forEach((flat: Flat) => { ... });
```

**Comment by Deadly0** [comment]
@sdarnell `.find()` returns `ObservableCursor<T>`. I'm about angular2-meteor, sorry, i have forgot to point on it.

**Comment by Urigo** [comment]
we've released a new and last version update to `angular2-meteor` to support the latest Angular.

But also the prefered data solution when working with Angular is to use the [meteor-rxjs](https://github.com/urigo/meteor-rxjs) package
