### ISSUE TITLE
*ngFor trackBy function not called starting from angular4.0.0-beta.8

### ISSUE THREAD

**Issue by activeperception** [Urigo/angular-meteor#1606]
Works well with angular4.0.0-beta.7.

It works well in this [plunker](https://plnkr.co/edit/XIQxq983z4QhVEVf3b2j?p=preview) (angular without meteor) but I cannot understand why it doesn't when meteor is used too. 

Any idea of how angular-meteor might interact with the changes introduced by [angular4.0.0-beta.8 ](https://github.com/angular/angular/blob/master/CHANGELOG.md#400-beta8-2017-02-18)?

Obviously I tried with the latest Angular4 stable version and it doesn't work either.

Thanks

**Comment by activeperception** [comment]
It works well when METEOR_PROVIDERS are not added to my module providers.

**Comment by Urigo** [comment]
we've released a new and last version update to `angular2-meteor` to support the latest Angular.

But also the prefered data solution when working with Angular is to use the [meteor-rxjs](https://github.com/urigo/meteor-rxjs) package
