### ISSUE TITLE
Error while importing Ionic 3's native library

### ISSUE THREAD

**Issue by ardatan** [Urigo/angular-meteor#1607]
I'm using Meteor 1.5, Angular 4 and Ionic 3 on my project by using Meteor CLI, but I cannot import Ionic's native library; it gives an error in browser because it cannot detect ES2015 import syntax in the ES2015 js files.

The code to import Ionic's SplashScreen plugin in TypeScript file:

`import { SplashScreen } from '@ionic-native/splash-screen';`
The error, which I get in browser;

`Uncaught SyntaxError: Unexpected token import modules.js:xxxxxx`

**Comment by Slavrix** [comment]
use typescript

**Comment by ardatan** [comment]
I am already using typescript (with barbatus:typescript). If you check the code of Ionic 3 native library, you can see ES2015 syntax there, and you can get that it is not related to "use typescript".

**Comment by amerzad** [comment]
This is happening to me also. I downgraded back to ionic-native@2.9.0 successfully.
I think the problem is, that after 2.9.0 they changed their compilation module to es2015.
Is there any way to make the barbatus:typescript compilers transpile @ionic-native@3.* files on meteor client?

**Comment by ardatan** [comment]
Unfortunately, I couldn't get help or any kind of answer about this situation, I think they don't care about MeteorCLI version.

**Comment by ardatan** [comment]
Closed w/ PR https://github.com/Urigo/angular-meteor/pull/1671
