### ISSUE TITLE
$bindToContext only updates current view, not parent

### ISSUE THREAD

**Issue by SimonSimCity** [Urigo/angular-meteor#1629]
I created a component that has a property, where an object get's passed in. The parent view also shows some of the content of this object.

When I now update this variable from another context and try to bind it back again using `this.$bindToContext(() => { /* some code ... */ })` it only updates the child's view, but not the parents one - leaving out the rest of the page, where data also might have to be re-rendered.

This is the same difference like calling `$scope.$apply()` or `$scope.$digest()` - see https://www.sitepoint.com/understanding-angulars-apply-digest/

Is this the correct behavior? If yes, the documentation should tell this more clearly. Currently it only says:

    This method binds the function to the reactive context. Any change in the function to the reactive context will be updated in the view accordingly.

Source: https://angular-meteor.com/api/angular-meteor/1.3.6/reactive-context#apply

If this is not the wanted behavior, please change it.

I know that this is a matter of performance, but it should be explained and stated clearly if you chose to go for a more performant way.

**Comment by ardatan** [comment]
`angularjs` example and use of new `angular-compilers` has been changed. You can check it out new example, and open a new issue if you still have these errors.
https://github.com/Urigo/angular-meteor/tree/master/examples/angularjs
