### ISSUE TITLE
Add ng-annotate compile step 

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#164]
Maybe use the plugin in a similar way that https://github.com/xaiki/metor-riotjs/blob/master/plugin/compile-riot.js uses it.

Compile to a Javascript file.

@netanelgilad thoughts?

**Comment by netanelgilad** [comment]
You mean by having a different extension for js files? That kinda sucks..

**Comment by Urigo** [comment]
as an option..

**Comment by leoetlino** [comment]
[This already exists.](https://github.com/JNissi/meteor-ng-annotate)

I do agree having a different extension is less than ideal, so we will probably have to wait on upstream…

**Comment by Urigo** [comment]
cool I haven't knew about that.

**Comment by leoetlino** [comment]
I didn't either, but Google did :)

Le Thu Feb 19 2015 at 21:07:00, Uri Goldshtein <notifications@github.com> a
écrit :
