### ISSUE TITLE
How to change $state?

### ISSUE THREAD

**Issue by abtx** [Urigo/angular-meteor#1646]
I've got a function outside the constructor and I'm trying to figure out the code to change the state, but so far no luck. I tried passing `$state` to the constructor and writing `this.state = $state` to use it in my function, but that doesn't work. 

What is a correct way for a function to trigger state change? 

PS: I want to change it when I create a new object, i.e. I'm adding an item to the collection, when it's added I'm returning its `_id`, the missing piece of the puzzle is to change the route.

**Comment by Urigo** [comment]
@abtx could you create a simple example repo?
it will be easier for me to respond on real code :)

thanks

**Comment by abtx** [comment]
Thanks, I solved this. Here I have a function with an insert statement that redirects the user when done:

>  insertTripAndGo() {
          var state = this.$state;
          // create new trip
          Meteor.call('trips.insert', this.selectedValue.description, this.selectedValue.description, 
          this.selectedValue.terms, function(error, result){
          if(error) {
              console.log(error)
          } else {
              state.go('detailsView', {'tripId': result});
          }
       });
    }
