### ISSUE TITLE
Slow rebuild times on old compilers

### ISSUE THREAD

**Issue by gooor** [Urigo/angular-meteor#1648]
Since upgrading to meteor 1.5.2.2 hot reload works like sh*** - after first error in TS file it stops reloading front - no matter what I do with this file. I have to restart meteor in order to get him reload this file *&%*()&. Funny part is that saving TS file triggers meteor to rebuild but Browser stays untouched throwing old error :(

**Comment by gooor** [comment]
And second thing - why  it doesn't show errors in TypeScript files? - I mean errors like `const something = ;`???? It just shows 'module 'x' not found'? It makes development of meteor-angular app a nightmare....

**Comment by ardatan** [comment]
You can try it with new compilers (angular-compilers) by changing template and style syntax. You can check MeteorCLI/bare example.

**Comment by Urigo** [comment]
closing as we haven't got new feedback.
Please reopen if you find a similar issue with the new compiler
