### ISSUE TITLE
Multiple clients, same backend

### ISSUE THREAD

**Issue by sebakerckhof** [Urigo/angular-meteor#167]
Hello,

I'm currently planning a collaborative application. Meteor seems to provide a lot of useful functionality, but I want to make my front-end in angularjs. I'd like to split this up in an admin and user client, but with a shared meteor backend. I could make this into one big client with routing, but really, the clients have not a lot in common, so I'd like to split this into two clients for maintainability (e.g. I could later upgrade one of two clients to angularjs 2 and still leave the other on angular 1).

I can see how this would be possible with asteroid, as the client is fully seperated. Yet I'd like to take advantage of some of the benefits from angular-meteor (mainly how meteorcollections behave as normal arrays and sync happens transparent for the developer. Don't care about blaze templates though). But is it possible to create multiple clients for the same backend using angular-meteor?

**Comment by Urigo** [comment]
Yes, you can just define 2 separate AngularJS applications.
Each AngularJS application is a module and you can load each one based on the current platform (Meteor.isCordova) or path (with a parent AngularJS application that initializes the right module).

Hope it helps
