### ISSUE TITLE
Template file names and Windows paths, same problem as #158

### ISSUE THREAD

**Issue by fredrikekelund** [Urigo/angular-meteor#169]
With Meteor soon to launch [official Windows support](https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows), the #158 problem with .tpl files and filenames resurfaces since Windows uses backslashes instead of forward slashes for paths.

![](https://owncloud.fredrik.computer/index.php/apps/files_sharing/publicpreview?file=%2F%2FMeteor%20error%20-%20windows%20paths.png&x=1680&y=949&a=true&t=09adb9ed58fab306306c7cccf6ccbffb&scalingup=0&forceIcon=0)

Probably the best way to solve this would be to, in the build step, replace any backward slashes in the path with forward slashes. As I understand it, the actual path doesn't mean anything much anyway since it's just stored as a key in `$templateCache`?

**Comment by netanelgilad** [comment]
You are right about the templateCache, it just uses keys and the key that we put in the templateCache is the sourcePath returned by meteor when compiling .tpl files.
Now this issue depends on how meteor will handle file paths when compiling resources. Seems logical to me that they would take care of the differences between platform for the sake of the developer not having to deal with himself, and that includes the backward slashes in windows.
So I would wait and see what happens with meteor windows support before actually implementing this.
But in the end we might actually need to...

**Comment by Urigo** [comment]
Hopefully solution is coming soon here:
https://github.com/meteor/windows-preview/issues/47#issuecomment-72130504

**Comment by Urigo** [comment]
If not, we can just add a simple function that backwards the slashes.......  (pull request encouraged)

**Comment by Urigo** [comment]
@fredrikekelund can we close this?

**Comment by fredrikekelund** [comment]
Yeah, I think we can. I'll keep an eye on https://github.com/meteor/windows-preview/issues/47 to see if there comes a standardized solution at a later point.

**Comment by Urigo** [comment]
Great (It would be great if you will add a link to that issue in a comment next to your code)
