### ISSUE TITLE
Tutorial: Encapsulating Meteor within AngularJS Services

### ISSUE THREAD

**Issue by rjsmith** [Urigo/angular-meteor#17]
Encapsulating interaction with Meteor collections / methods etc inside one or more Angular Services.

I prefer to keep my Angular controllers as simple as possible, focused only on defining the $scope models and UI - specific behaviour methods.  Any backend - specific work should be encapsulated in a Service layer.  This has several advantages, such as testing (mock out the Service when testing the Controller), and theoretical ability to swap out Meteor for another backend (hello, open-sourced Firebase in the future?!).  So, a tutorial to demonstrate ways of using the angular-meteor services ($collection, $users etc) wrapped in Angular services, rather than directly attaching to a controller $scope, would be very useful for more advanced front-end architectures.

**Comment by Urigo** [comment]
@rjsmith @paulvanbladel please take a look at the new version:
https://github.com/Urigo/angular-meteor/releases/tag/0.6.0-alpha

I think I've addressed this issue there

**Comment by Urigo** [comment]
Closing.
Please re-open if you think I haven't addressed everything here
