### ISSUE TITLE
Angular Material Latest Version Doesn't Work with angular-compilers@0.2.5

### ISSUE THREAD

**Issue by leonardoespinosa** [Urigo/angular-meteor#1722]
I try use angular material latest version (2.0.0-beta.12) in my project and angular-compilers can't  import the main theming Sass file from Angular Material and include the base styles like:

```
@import '../../node_modules/@angular/material/_theming.scss';
@include mat-core();
```

All Angular Material styles not listed. I see issue #1631 and update the angular-compiler to 0.2.5 version and meteor to 1.6 version and fails again. My project use:

Meteor packages:
```
meteor-base@1.2.0
mobile-experience@1.0.5
mongo@1.3.0
reactive-var@1.0.11
jquery@1.11.10
tracker@1.1.3
standard-minifier-css@1.3.5
standard-minifier-js@2.2.0
es5-shim@4.6.15
shell-server@0.3.0
accounts-password@1.5.0
msavin:mongol
jalik:ufs
jalik:ufs-gridfs
service-configuration@1.0.11
accounts-ui@1.2.0
accounts-twitter@1.4.0
accounts-google@1.3.0
mys:fonts
check@1.2.5
email@1.2.3
astrocoders:one-signal
vsivsi:job-collection
btafel:accounts-facebook-cordova
babel-compiler@6.24.7
ecmascript@0.9.0
localstorage@1.2.0
percolate:synced-cron
meteorhacks:ssr
dynamic-import@0.2.0
angular-compilers

```
Angular-meteor:
```
angular-compilers@0.2.5
angular-html-compiler@0.2.5
angular-scss-compiler@0.2.5
angular-typescript-compiler@0.2.7_1
```

Package.json
```
 {
  "name": "test",
  "private": true,
  "scripts": {
    "start": "meteor --settings settings.json"
  },
  "dependencies": {
    "@agm/core": "1.0.0-beta.1",
    "@angular/animations": "4.4.6",
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/compiler-cli": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/flex-layout": "2.0.0-beta.9",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/material": "2.0.0-beta.12",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "@angular/platform-server": "4.4.6",
    "@angular/router": "4.4.6",
    "@ngx-translate/core": "8.0.0",
    "@ngx-translate/http-loader": "2.0.0",
    "@types/node": "8.0.47",
    "angular-meteor": "1.3.12",
    "angular2-meteor-polyfills": "0.2.0",
    "angulartics2": "3.2.0",
    "babel-runtime": "6.26.0",
    "base-64": "0.1.0",
    "bcrypt": "^1.0.3",
    "core-js": "2.5.1",
    "font-awesome": "4.7.0",
    "gm": "1.23.0",
    "google-material-color": "1.3.1",
    "hammerjs": "2.0.8",
    "jquery": "3.2.1",
    "jspdf": "1.3.5",
    "md5": "2.2.1",
    "meteor-node-stubs": "0.3.2",
    "meteor-rxjs": "0.4.8",
    "meteor-typings": "1.4.1",
    "microtime": "2.1.6",
    "ng2-page-scroll": "4.0.0-beta.12",
    "prismjs": "1.8.3",
    "qrious": "4.0.2",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.5.2",
    "spawn-sync": "1.0.15",
    "thread-sleep": "2.0.0",
    "try-thread-sleep": "1.0.2",
    "ts-helpers": "1.1.2",
    "typescript": "2.5.3",
    "typescript-collections": "1.2.5",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@types/chai": "4.0.4",
    "@types/hammerjs": "2.0.35",
    "@types/highcharts": "5.0.9",
    "@types/jasmine": "2.6.2",
    "@types/meteor": "1.4.12",
    "@types/mocha": "2.2.44",
    "@types/prismjs": "1.6.5",
    "autoprefixer": "7.1.6",
    "awesome-typescript-loader": "3.2.3",
    "chai": "4.1.2",
    "chai-spies": "0.7.1",
    "codelyzer": "3.2.2",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "node-sass": "4.5.3",
    "protractor": "5.2.0",
    "ts-node": "3.3.0",
    "tslint": "5.8.0"
  }
}
```
I use Angular 4.4.6 version because is the last version compatible with Angular Material 2.0.0-beta.12. I try import the main theming like  `@import '~@angular/material/_theming.scss';` but node-sass in angular-compiler doesn't work and display error:

```
=> Errors prevented startup:
While processing files with angular-compilers (for target web.browser):
client/main.scss:1:1: File to import not found or unreadable: ~@angular/material/_theming.scss.
```

I try use fourseven:scss package referencing route like 
`@import '{}/node_modules/@angular/material/_theming.scss';` and creating scss-config.json file with the content:

```
{
  "includePaths": [
    "{}/node_modules/"
  ]
}
```
and doesn't work. Also, I try with other versions of Angular Material and same dependencies:
- Angular Material version 2.0.0-beta.11 with Angular 4.4.3, angular-compilers 0.2.5 => Same Problem
- Angular Material version 2.0.0-beta.10 with Angular 4.3.6, angular-compilers 0.2.5 => Same Problem

In Angular Material Changelog [https://github.com/angular/material2/blob/master/CHANGELOG.md#200-beta11-carapace-parapet-2017-09-21](url) i see the MaterialModule has been removed and each @angular/material component is now bundled into its own javascript file. Maybe that's problem, I don't know.

I appreciate the help. Regards!

**Comment by ardatan** [comment]
You shouldn’t need to use fourseven:scss, and it may conflict angular-compilers packages.
New compiler doesn’t work like old version of Angular Meteor Compilers.
- First, remove any other meteor scss package.
- Then, import 3rd party libraries without ‘~’ like below;
‘@import ‘@angular/material/theming’;’
- Underscore and file extension shouldn’t be added in import path in SCSS ( like every SCSS )
- Then, add it to your root component by using styleUrls.
- Do not forget to disable encapsulation as it is noted in Angular Material docs.
‘encapsulation: ViewEncapsulation.none’
- Unless you add stylesheets to any component, it won’t work, because new compiler doesn’t merge all stylesheets and add all of them into the page.

If you have more questions, please let me know.

**Comment by leonardoespinosa** [comment]
Thanks! It worked!

**Comment by pmcochrane** [comment]
The comment above from ardatan would be really useful documentation for the angular compilers and how to migrate your app to use the new compiler. I've just spent the last few hours trying to figure out why I had no css in my after upgrading to the new angular-compiler package.

**Comment by ardatan** [comment]
In the version of compiler, this feature will be changed a little bit. The scss files, not in imports folder, would be merged and added directly on the page (like before).
The basic documentation for all these features will be added in the following version.
Thanks for your feedback.

**Comment by pmcochrane** [comment]
Looking forward to the next update then. Any ETA at present?
