### ISSUE TITLE
(Windows) Error when starting clean all-in-one example

### ISSUE THREAD

**Issue by FriOne** [Urigo/angular-meteor#1739]
I get `Angular SSR Error: Error: Unknown asset: importsappapp.html` when run `npm run start`.
Meteor version is 1.6
I guess this issue related to windows platform, I have windows 7 64x.
Any help to make it work?

**Comment by ardatan** [comment]
Could you reproduce this?

**Comment by FriOne** [comment]
@ardatan What do you mean? You can download all-in-one examples repo part and run `start` command. Well, if you have the same OS.

**Comment by gjr-qm** [comment]
Same problem here (Windows 10 64bit) with the 'universal' and 'all-in-one' examples. After a clean install of Meteor 1.6 and cloning the angular-meteor repo both examples give the error:

```
Angular SSR Error: Error: Unknown asset: importsappapp.html
at getAsset (...\angular-meteor\examples\MeteorCLI\universal\.meteor\local\build\programs\server\boot.js:328:19)
```

The 'bare' and 'lazy-loading' don't have this problem, but won't run either. On the client i get the error:
```
clientimportsappapp.html:12 ERROR RangeError: Maximum call stack size exceeded
```

**Comment by ardatan** [comment]
Yes, we have to fix that path issue on Windows. The fix will be released in a few days.

**Comment by gjr-qm** [comment]
Cool! Great work!

**Comment by FriOne** [comment]
@ardatan any update on this? Do we have a way to fix it temporary somehow?

**Comment by ardatan** [comment]
We've updated angular-compilers and examples. This path issue on Windows has been fixed. You can update the packages:
meteor update --all-packages
And if you are still facing this problem, you can open a new issue.
