### ISSUE TITLE
Different subscribes on the same collection causes problems

### ISSUE THREAD

**Issue by clouchtibat** [Urigo/angular-meteor#174]
I have two different controllers whose scope contains a list that use different subscribes on the same collection : 
    
    $scope.tests = $meteorCollection(Tests, false).subscribe("tests");    

    $scope.filteredTests = $meteorCollection(Tests, false).subscribe("filteredTests", "n", false);

The second uses a filter, the first returns the complete collection.
- If I'm on the filtered tests page the filtered list is correctly filtered.
- If I navigate to the tests page and then go back to the filtered tests page the filtered list doesn't work anymore.

I put a simplified test application here :
https://github.com/clouchtibat/test

Am I doing it wrong?

**Comment by netanelgilad** [comment]
Different subscriptions on the same collection eventually end up merged within the collection. If you have different controllers and you want to clear the subscriptions you created once the scope is destroyed, then subscribe using the meteorSubscribe service and not through the collection and listen for the scope destroyed event and cancel the subscription. That should clear the collection from the subscribed data. 
Hope this helps...

**Comment by clouchtibat** [comment]
Thanks for your answer, I'll try the meteorSubscribe solution.

And is there a solution if we are on the same scope, or is this just a nonsense to have different subscriptions on the same collection in the same scope?

**Comment by Urigo** [comment]
@clouchtibat this is how Meteor works.
Here is a great source for learning about that:
https://www.discovermeteor.com/blog/understanding-meteor-publications-and-subscriptions/

For you current problem - it looks like you are trying to create a filter.
Filter shouldn't be done with subscriptions (for the reasons in the article).
So you should use AngularJS filters or Mongo selectors when defining the $meteorCollection:

    var config = {};
    config.name = new RegExp(".*"+filter+".*", "i");

    $scope.filteredTests = $meteorCollection(function(){
      return Tests.find(config, {sort: {title: reverseSort?-1:1}, limit: 100});
    }, false).subscribe("Tests");


Something like that.
Hope it helps thing to be clearer
