### ISSUE TITLE
(Windows) ERROR RangeError: Maximum call stack size exceeded     at callWithDebugContext (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26969)

### ISSUE THREAD

**Issue by indware** [Urigo/angular-meteor#1749]
Please help I am getting this error, I know about Angular 2 but I am new to Meteor. Just following the instructions, haven't changed anything in the source code.

Command running: meteor
Command Output:
[[[[[ ~\E\Works\Meteor\CabBooking ]]]]]

=> Started proxy.
Compiling ES2015 modules!: 1930.691ms        \
Compiling TS Files...: 20.148ms
Compiling ES2015 modules!: 30.895ms          -
Compiling TS Files...: 6.117ms
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

NPM: 5.5.1
Node: 9.0.1

Browser error stack:
ERROR RangeError: Maximum call stack size exceeded
    at callWithDebugContext (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26969)
    at Object.debugCreateComponentView [as createComponentView] (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26306)
    at createViewNodes (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:25652)
    at callViewAction (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26117)
    at execComponentViewsAction (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26026)
    at createViewNodes (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:25715)
    at callViewAction (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26117)
    at execComponentViewsAction (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26026)
    at createViewNodes (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:25715)
    at callViewAction (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26117)
View_AppComponent_0 @ clientimportsappapp.html:12
proxyClass @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:43752
DebugContext_.logError @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26902
ErrorHandler.handleError @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:14575
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:17904
ZoneDelegate.invoke @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1844
Zone.run @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1594
NgZone.runOutsideAngular @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:17339
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:17904
ZoneDelegate.invoke @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1844
onInvoke @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:17385
ZoneDelegate.invoke @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1843
Zone.run @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1594
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2325
ZoneDelegate.invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1877
onInvokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:17376
ZoneDelegate.invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1876
Zone.runTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1644
drainMicroTaskQueue @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2054
ZoneTask.invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1955
invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2992
globalZoneAwareCallback @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:3018
XMLHttpRequest.send (async)
scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:4385
ZoneDelegate.scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1863
Zone.scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1688
Zone.scheduleMacroTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1711
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:4418
proto.(anonymous function) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2818
ResourceLoaderImpl.get @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:28599
DirectiveNormalizer._fetch @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42846
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42968
DirectiveNormalizer._loadMissingExternalStylesheets @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42968
DirectiveNormalizer.normalizeExternalStylesheets @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42945
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42877
ZoneDelegate.invoke @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1844
Zone.run @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1594
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2325
ZoneDelegate.invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1877
Zone.runTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1644
drainMicroTaskQueue @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2054
ZoneTask.invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1955
invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2992
globalZoneAwareCallback @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:3018
XMLHttpRequest.send (async)
scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:4385
ZoneDelegate.scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1863
Zone.scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1688
Zone.scheduleMacroTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1711
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:4418
proto.(anonymous function) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2818
ResourceLoaderImpl.get @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:28599
DirectiveNormalizer._fetch @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42846
DirectiveNormalizer.normalizeTemplateOnly @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42893
DirectiveNormalizer.normalizeTemplate @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42877
CompileMetadataResolver.loadDirectiveMetadata @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:43906
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55600
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55599
JitCompiler._loadModules @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55596
JitCompiler._compileModuleAndComponents @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55566
JitCompiler.compileModuleAsync @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55495
PlatformRef_._bootstrapModuleWithZone @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:18031
PlatformRef_.bootstrapModule @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:18017
meteor_1.Meteor.startup @ main.ts:15
maybeReady @ meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:821
loadingCompleted @ meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:833
clientimportsappapp.html:12 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 13, nodeDef: {…}, elDef: {…}, elView: {…}}
View_AppComponent_0 @ clientimportsappapp.html:12
proxyClass @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:43752
DebugContext_.logError @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26902
ErrorHandler.handleError @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:14580
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:17904
ZoneDelegate.invoke @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1844
Zone.run @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1594
NgZone.runOutsideAngular @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:17339
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:17904
ZoneDelegate.invoke @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1844
onInvoke @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:17385
ZoneDelegate.invoke @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1843
Zone.run @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1594
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2325
ZoneDelegate.invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1877
onInvokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:17376
ZoneDelegate.invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1876
Zone.runTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1644
drainMicroTaskQueue @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2054
ZoneTask.invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1955
invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2992
globalZoneAwareCallback @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:3018
XMLHttpRequest.send (async)
scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:4385
ZoneDelegate.scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1863
Zone.scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1688
Zone.scheduleMacroTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1711
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:4418
proto.(anonymous function) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2818
ResourceLoaderImpl.get @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:28599
DirectiveNormalizer._fetch @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42846
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42968
DirectiveNormalizer._loadMissingExternalStylesheets @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42968
DirectiveNormalizer.normalizeExternalStylesheets @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42945
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42877
ZoneDelegate.invoke @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1844
Zone.run @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1594
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2325
ZoneDelegate.invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1877
Zone.runTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1644
drainMicroTaskQueue @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2054
ZoneTask.invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1955
invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2992
globalZoneAwareCallback @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:3018
XMLHttpRequest.send (async)
scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:4385
ZoneDelegate.scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1863
Zone.scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1688
Zone.scheduleMacroTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1711
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:4418
proto.(anonymous function) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2818
ResourceLoaderImpl.get @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:28599
DirectiveNormalizer._fetch @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42846
DirectiveNormalizer.normalizeTemplateOnly @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42893
DirectiveNormalizer.normalizeTemplate @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42877
CompileMetadataResolver.loadDirectiveMetadata @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:43906
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55600
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55599
JitCompiler._loadModules @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55596
JitCompiler._compileModuleAndComponents @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55566
JitCompiler.compileModuleAsync @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55495
PlatformRef_._bootstrapModuleWithZone @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:18031
PlatformRef_.bootstrapModule @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:18017
meteor_1.Meteor.startup @ main.ts:15
maybeReady @ meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:821
loadingCompleted @ meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:833
modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2142 Unhandled Promise rejection: Maximum call stack size exceeded ; Zone: <root> ; Task: Promise.then ; Value: RangeError: Maximum call stack size exceeded
    at callWithDebugContext (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26969)
    at Object.debugCreateComponentView [as createComponentView] (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26306)
    at createViewNodes (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:25652)
    at callViewAction (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26117)
    at execComponentViewsAction (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26026)
    at createViewNodes (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:25715)
    at callViewAction (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26117)
    at execComponentViewsAction (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26026)
    at createViewNodes (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:25715)
    at callViewAction (modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26117) RangeError: Maximum call stack size exceeded
    at callWithDebugContext (http://localhost:3000/packages/modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26969:13)
    at Object.debugCreateComponentView [as createComponentView] (http://localhost:3000/packages/modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26306:12)
    at createViewNodes (http://localhost:3000/packages/modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:25652:46)
    at callViewAction (http://localhost:3000/packages/modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26117:13)
    at execComponentViewsAction (http://localhost:3000/packages/modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26026:13)
    at createViewNodes (http://localhost:3000/packages/modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:25715:5)
    at callViewAction (http://localhost:3000/packages/modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26117:13)
    at execComponentViewsAction (http://localhost:3000/packages/modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26026:13)
    at createViewNodes (http://localhost:3000/packages/modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:25715:5)
    at callViewAction (http://localhost:3000/packages/modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:26117:13)
api.onUnhandledError @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2142
handleUnhandledRejection @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2169
_loop_1 @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2159
api.microtaskDrainDone @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2163
drainMicroTaskQueue @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2062
ZoneTask.invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1955
invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2992
globalZoneAwareCallback @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:3018
XMLHttpRequest.send (async)
scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:4385
ZoneDelegate.scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1863
Zone.scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1688
Zone.scheduleMacroTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1711
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:4418
proto.(anonymous function) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2818
ResourceLoaderImpl.get @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:28599
DirectiveNormalizer._fetch @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42846
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42968
DirectiveNormalizer._loadMissingExternalStylesheets @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42968
DirectiveNormalizer.normalizeExternalStylesheets @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42945
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42877
ZoneDelegate.invoke @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1844
Zone.run @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1594
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2325
ZoneDelegate.invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1877
Zone.runTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1644
drainMicroTaskQueue @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2054
ZoneTask.invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1955
invokeTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2992
globalZoneAwareCallback @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:3018
XMLHttpRequest.send (async)
scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:4385
ZoneDelegate.scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1863
Zone.scheduleTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1688
Zone.scheduleMacroTask @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:1711
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:4418
proto.(anonymous function) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:2818
ResourceLoaderImpl.get @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:28599
DirectiveNormalizer._fetch @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42846
DirectiveNormalizer.normalizeTemplateOnly @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42893
DirectiveNormalizer.normalizeTemplate @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:42877
CompileMetadataResolver.loadDirectiveMetadata @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:43906
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55600
(anonymous) @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55599
JitCompiler._loadModules @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55596
JitCompiler._compileModuleAndComponents @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55566
JitCompiler.compileModuleAsync @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:55495
PlatformRef_._bootstrapModuleWithZone @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:18031
PlatformRef_.bootstrapModule @ modules.js?hash=8a8351b9e77beb33f787e9e363cce3d94bb24c59:18017
meteor_1.Meteor.startup @ main.ts:15
maybeReady @ meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:821
loadingCompleted @ meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:833

**Comment by ardatan** [comment]
I think you are using the old version of compiler. Could you try to update it to make sure?
‘meteor update —all-packages —allow-incompatible-update’

**Comment by indware** [comment]
@ardatan I have used that command but I am still facing the same issue, I am on windows 10 64 bit. And in case I have install meteor just yesterday.

**Comment by ardatan** [comment]
Can you reproduce the issue?

**Comment by maxfriedmann** [comment]
@indware : Can you try to replace AppComponent with 

```
@Component({
    selector: "app",
    template: "<div>TEST</div>"
})
export class AppComponent { } 
```
... so no templateURL and instead an inner template? That solved the problem for me.

I get the feeling it might be related to https://github.com/Urigo/angular-meteor/issues/1770 since again changing the templateUrl fixed the problem?

**Comment by ardatan** [comment]
We've updated angular-compilers and examples. This path issue on Windows has been fixed. You can update the packages:
meteor update --all-packages
And if you are still facing this problem, you can open a new issue.
