### ISSUE TITLE
service-configuration doesn't seem to be working with angular-meteor/examples/angularcli-meteor

### ISSUE THREAD

**Issue by arproudlock** [Urigo/angular-meteor#1762]
Hi, have managed to get most things working well with angular 4 and meteor following the angularcli-meteor example.  However I've run into a problem with service-configuration.

from /api I do `meteor add service-configuration` (along with accounts-facebook etc)
then `meteor`
and re-run the client-bundler

At this point all seems to be fine and running.  But when I try to add ServiceConfiguration.configurations.upsert as per the docs I get the following in the editor:
`[ts] Property 'configurations' does not exist on type 'typeof ServiceConfiguration'.`
and in terminal running meteor from /api
`server/main.ts (6, 22): Property 'configurations' does not exist on type 'typeof ServiceConfiguration'.`

api/server/main.ts looks like this:
```
import { Meteor } from 'meteor/meteor';
import { ServiceConfiguration } from 'meteor/service-configuration';
import * as moment from 'moment';
import { Skills, SkilledUsers } from './collections/index';

Meteor.startup(() => {

  ServiceConfiguration.configurations.upsert(
    { service: 'facebook' },
    {
      $set: {
        loginStyle: "popup",
        appId: "1292962797",
        secret: "75a730b58f5691de5522789070c319bc"
      }
    }
  );
  // other code to run on server at startup
```

Any idea what could be going wrong here?

**Comment by darkbasic** [comment]
I think it's because of missing typings. Since ServiceConfigurations it's already in the global scope you simply use `declare const ServiceConfiguration: any;` instead of the import and it will work flawlessly.

**Comment by arproudlock** [comment]
@darkbasic you're a legend, thank you.
