### ISSUE TITLE
merged-stylesheets.css Not Found

### ISSUE THREAD

**Issue by ingleo** [Urigo/angular-meteor#1763]
Hi everyone, 

I'm getting this error when run ionic serve testing an ionic app calling the meteor-client.

![seleccion_096](https://user-images.githubusercontent.com/10843115/32851346-bd7c1d3e-ca02-11e7-888d-9cc5dc085c34.png)

It seems is related meteor css conflict with ionic css.

Any idea what could be going wrong?

**Comment by darkbasic** [comment]
Did you try to follow our tutorial?
https://angular-meteor.com/tutorials/whatsapp2/ionic/setup

**Comment by ardatan** [comment]
You can reopen the issue if the issue still continues.
Please tell us more about your configuration if it doesn’t work as expected in the same way.
Thank you!
