### ISSUE TITLE
$meteorObject.save() throws Error

### ISSUE THREAD

**Issue by tobias-f** [Urigo/angular-meteor#177]
Hello.

Again, I am going through the tutorial. At step 6 calling the $meteorObject.save() method throws an error:

 'WebSocket.URL' is deprecated. Please use 'WebSocket.url' instead. urigo_angular.js?
TypeError: Cannot convert undefined or null to object

I guess also a bug...

**Comment by pieperz** [comment]
I also got this bug yesterday. Did you get around it?

**Comment by tobias-f** [comment]
Hey.

Actually, not yet... although I did not start digging to far :-(

**Comment by Urigo** [comment]
Tomorrow morning I'm on it
