### ISSUE TITLE
"Bad character escape sequence" error on windows 

### ISSUE THREAD

**Issue by suresram** [Urigo/angular-meteor#1770]
All the components that has template url starting with letter "u" or if the template is under a folder whose name start with letter "u"  results in the compilation error ""Bad character escape sequence" error on windows"

Example - Folder "user" which has a component "user-account.component"

@Component({
    templateUrl: 'user-account.component.html'
})

**Comment by maxfriedmann** [comment]
How annoying is that bug 😄 

The workaround that helped me was to just save the relative template path as constant string. 

Change 
 ```
@Component({
    templateUrl: "./UsersBackoffice.html"
})
export class UsersBackoffice { }

```
to
```
const templateUrl: string = "./UsersBackoffice.html";

@Component({
    templateUrl
})
export class UsersBackoffice { }
```

**Comment by ardatan** [comment]
We've updated `angular-compilers` and examples. This path issue on Windows has been fixed. You can update the packages:
`meteor update --all-packages`
And if you are still facing this problem, you can open a new issue.

**Comment by smeijer** [comment]
I'm trying to find the commit that's responsible for fixing this issue. Can you guys help me? I'm hoping that it will help fix a similar issue in styled-jsx.

https://github.com/zeit/styled-jsx/issues/253
