### ISSUE TITLE
New base doesn't work and examples tutorials either

### ISSUE THREAD

**Issue by abcluis** [Urigo/angular-meteor#1777]
I have been working in a project with meteor but i want to create a new project with this base https://github.com/Urigo/angular-meteor-base but seem doesn't work 
![image](https://user-images.githubusercontent.com/17711741/33188339-60ac485e-d056-11e7-8511-ee6eb473eb5a.png)

Tested in windows 10 
This is the server console
![image](https://user-images.githubusercontent.com/17711741/33188374-9e9f7032-d056-11e7-9a7a-8ca354c36b51.png)

In Linux(Ubuntu) works perfectly but i don't know why not in windows, in the examples of all-in-one and lazy-loading i have the same issue

**Comment by ardatan** [comment]
It is the path problem on Windows. We've fixed it now, you can check the new examples. Also we've updated `angular-meteor-base`, please re-open if you still have this problem.
