### ISSUE TITLE
adding dynamic meta tags

### ISSUE THREAD

**Issue by catsoft** [Urigo/angular-meteor#178]
Before v0.6 I was using "yasinuslu:blaze-meta" package for adding meta tags. But unfortunately I can not after this release.Do you know how can I deal with this problem?

**Comment by Urigo** [comment]
Can you create a repo that demonstrate that so I will be able to clone and test this?
Thank you

**Comment by Urigo** [comment]
Just tested it and it works fine for me..
@catsoft Looks like your problem is not angular-meteor related
