### ISSUE TITLE
Release with angular 5 support

### ISSUE THREAD

**Issue by staeke** [Urigo/angular-meteor#1781]
### When reporting a bug, please be sure to include the following:
- [X] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `angular-meteor` you're using, and the platform(s) you're running it on
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior

See [here](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor) for more detail on what is expected of a bug report.

### When you open an issue for a feature request, please add as much detail as possible:
- [X] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

**Comment by Urigo** [comment]
Do you mean for the Angular CLI + Meteor client bundler or the Meteor CLI?

**Comment by ardatan** [comment]
Please open the issue if the problem is still continuing.
Thank you!
