### ISSUE TITLE
packages/angular-typescript-compiler/index.js:204:7: Cannot set property 'module'

### ISSUE THREAD

**Issue by maxfriedmann** [Urigo/angular-meteor#1789]
I updated angular-compilers from v0.2.8_1 v0.2.9 due to #1777 and #1749. I also added the new NPM dependencies as mentioned during rebuild (typescript + angular/compiler-cli).

Now meteor builds with the following error: 
```
 While processing files with angular-compilers (for target web.browser):
   packages/angular-typescript-compiler/index.js:204:7: Cannot set property 'module'
   of undefined (at AngularTsCompiler.processFilesForTarget)
``` 

Unsetting the environment variable `ROLLUP` solves the issue. Using the tsconfig.json from the bare example also solved the problem. 

Meteor 1.6, Windows 10 x64

**Comment by ardatan** [comment]
If rollup is activated, compiler tries to force module type to 'es2015'. When there is no module type definition, it fails.
Fixed in new version;
`meteor update --all-packages`
