### ISSUE TITLE
Tutorial: Unit testing angular-meteor applications

### ISSUE THREAD

**Issue by rjsmith** [Urigo/angular-meteor#18]
Guidance on writing Angular Karma unit tests using mocks of the angular-meteor services.

**Comment by mikepc** [comment]
I was just curious how that's coming along? I googled angular-meteor unit test and it brought me here.

**Comment by JefferE** [comment]
Why has this been closed - is it done and I just can't find it? Still struggling to find angular-meteor testing information.

**Comment by mikepc** [comment]
I gave up on this issue months ago, went with a standard MEAN solution
since I already know how to test that. It's obvious the community isn't too
keen on testing, which wouldn't be a good fit for my company's platform.

**Comment by dyaa** [comment]
@Urigo cam u just tell us the best tools for testing and i'll try to search and help u writing this chapter since its the most thing that the community is searching for... PLEASE

**Comment by wilcraig** [comment]
Yeah I'm struggling to find unit testing tools as well for angular meteor as a lot of tools seem to have been deprecated with meteor's new testing guidelines, but it's not easy to set up or test things on angular meteor. I would say Jasmine is pretty popular, and just getting some unit testing running with Jasmine and side-by-side test files within angular meteor would be huge.

**Comment by Tallyb** [comment]
Probably your best bet will be mocha, so you can test both client and server

**Comment by wilcraig** [comment]
Thanks @Tallyb. We've got mocha integrated now, and just working to get everything working. Some examples of how to test controllers and services using ng-mock and chai with mocha would be helpful and appreciated. If it doesn't get done by the time we figure it out we'll probably try to contribute to the project with some sort of tutorial

**Comment by GuofuHuang** [comment]
@wilcraig , do you get any tutorials for testing? I have searched lots of places, but no luck.
