### ISSUE TITLE
Wrong IS_AOT calculation

### ISSUE THREAD

**Issue by iperevozchikov** [Urigo/angular-meteor#1807]
Hi! Currently angular-compilers have a bug with wrong calculation of IS_AOT variable in angular-html-compiler and angular-scss-compiler packages:
```javascript
const IS_AOT = ((process.env.NODE_ENV == 'production') || process.env.AOT);
```
Its fail if we want build our app without needing of AOT compilation (AOT=0), because !!'0' === true.
So, please just add condition from angular-typescript-compiler, its seems as right:
```javascript
const IS_AOT = ((process.env.NODE_ENV == 'production') && process.env.AOT != '0');
```

**Comment by ardatan** [comment]
Thank you! We merged your fix in our release. Please let us know if everything works expected.
