### ISSUE TITLE
.ng.html  vs.  .tpl

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#182]
Quick servey for the community - would you prefer Angular template files to end with .tpl like they are today or the end with .ng.html ??

Thank you

**Comment by fredrikekelund** [comment]
.ngml?

Think I prefer .tpl actually, makes the distinction very clear between Meteor and Angular templates and encourages general separation of concerns. And the more best practices surround angular-meteor the better, IMO.

**Comment by ndevr** [comment]
.ng.html cause of IDE auto support and code completion.

**Comment by netanelgilad** [comment]
@Urigo Are you sure .ng.html won't get compiled by meteor cause it ends with .html?
Need to check that..

**Comment by Urigo** [comment]
@netanelgilad already did before posting this.
thanks :)

**Comment by leoetlino** [comment]
I would say .ng.html, so editors will immediately know it is HTML and enable correct syntax highlighting − some currently detect .tpl as being Smarty templates…

**Comment by fredrikekelund** [comment]
I think the argument for editors recognizing HTML syntax is really compelling. Sublime seems to recognize tpl files as HTML, so the thought didn't strike me, but with that in mind, I think .ng.html might be a better choice

**Comment by Urigo** [comment]
OK, looks like ng.html it is!

**Comment by leoetlino** [comment]
Just to know, how are you going to make the change? In the next major
release? (1.0?)

Le mer. 18 févr. 2015 00:43, Uri Goldshtein <notifications@github.com> a
écrit :

**Comment by Urigo** [comment]
Yes, but I think 0.7.0 will come first.
I'll a beta version for about a week first.
I want to release version 1.0 only after my talk in ng-conf

**Comment by scresawn** [comment]
Would you maybe consider having a "what's new" section in the README file? When I ran "meteor update" today I got an error from my .tpl files, and it took me a while to figure out that this was the cause. Thank you very much!

**Comment by leoetlino** [comment]
@scresawn There is the [releases page](https://github.com/Urigo/angular-meteor/releases); maybe the README should link to that page? This should make that page easier to find.

**Comment by scresawn** [comment]
Wow, I never knew that page existed.  Yes, I think a link might help other people too.

**Comment by Urigo** [comment]
Good point, Added a link into the readme
