### ISSUE TITLE
npm ERR! when installing angular2-compilers

### ISSUE THREAD

**Issue by mbtechnologyil** [Urigo/angular-meteor#1825]
i was following the tutrials
https://angular-meteor.com/tutorials/whatsapp2/meteor/setup

and when i tried to install angular2-compilers i got this error:

C:\Users\hersh\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit
(C:\Users\hersh\AppData\Local\Temp\mt-1bjvknx.h19sg\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command
"C:\\Users\\hersh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0_1\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\hersh\\AppData\\Local\\Temp\\mt-1bjvknx.h19sg\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd
C:\Users\hersh\AppData\Local\Temp\mt-1bjvknx.h19sg\npm\node_modules\.temp-9kk7w1.gmo9i\node_modules\node-sass
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hersh\AppData\Roaming\npm-cache\_logs\2017-12-10T21_50_43_040Z-debug.log

This is the full log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\hersh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0_1\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe',
1 verbose cli   'C:\\Users\\hersh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0_1\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'rebuild',
1 verbose cli   '--update-binary' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 info readInstalled object
5 verbose rebuild path, id [ 'C:\\Users\\hersh\\AppData\\Local\\Temp\\mt-1bjvknx.h19sg\\npm\\node_modules\\.temp-9kk7w1.gmo9i\\node_modules\\node-sass',
5 verbose rebuild   'node-sass@3.8.0' ]
6 silly rebuild set [ 'C:\\Users\\hersh\\AppData\\Local\\Temp\\mt-1bjvknx.h19sg\\npm\\node_modules\\.temp-9kk7w1.gmo9i\\node_modules\\node-sass' ]
7 info build C:\Users\hersh\AppData\Local\Temp\mt-1bjvknx.h19sg\npm\node_modules\.temp-9kk7w1.gmo9i\node_modules\node-sass
8 info lifecycle node-sass@3.8.0~preinstall: node-sass@3.8.0
9 info linkStuff node-sass@3.8.0
10 silly linkStuff node-sass@3.8.0 has C:\Users\hersh\AppData\Local\Temp\mt-1bjvknx.h19sg\npm\node_modules\.temp-9kk7w1.gmo9i\node_modules as its parent node_modules
11 verbose linkBins node-sass@3.8.0
12 verbose linkBins [ { 'node-sass': 'bin/node-sass' },
12 verbose linkBins   'C:\\Users\\hersh\\AppData\\Local\\Temp\\mt-1bjvknx.h19sg\\npm\\node_modules\\.temp-9kk7w1.gmo9i\\node_modules\\.bin',
12 verbose linkBins   false ]
13 verbose linkMans node-sass@3.8.0
14 verbose rebuildBundles node-sass@3.8.0
15 info lifecycle node-sass@3.8.0~install: node-sass@3.8.0
16 verbose lifecycle node-sass@3.8.0~install: unsafe-perm in lifecycle true
17 verbose lifecycle node-sass@3.8.0~install: PATH: C:\Users\hersh\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\bin\node-gyp-bin;C:\Users\hersh\AppData\Local\Temp\mt-1bjvknx.h19sg\npm\node_modules\.temp-9kk7w1.gmo9i\node_modules\node-sass\node_modules\.bin;C:\Users\hersh\AppData\Local\Temp\mt-1bjvknx.h19sg\npm\node_modules\.temp-9kk7w1.gmo9i\node_modules\.bin;C:\Users\hersh\AppData\Local\Temp\mt-1bjvknx.h19sg\npm\node_modules\.bin;C:\Users\hersh\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\bin;C:\Users\hersh\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Users\hersh\AppData\Local\Programs\Python\Python36-32;C:\Program Files\nodejs\;C:\Users\hersh\AppData\Local\Microsoft\WindowsApps;C:\Users\hersh\AppData\Local\.meteor;C:\Users\hersh\AppData\Roaming\npm
18 verbose lifecycle node-sass@3.8.0~install: CWD: C:\Users\hersh\AppData\Local\Temp\mt-1bjvknx.h19sg\npm\node_modules\.temp-9kk7w1.gmo9i\node_modules\node-sass
19 silly lifecycle node-sass@3.8.0~install: Args: [ '/d /s /c', 'node scripts/install.js' ]
20 silly lifecycle node-sass@3.8.0~install: Returned: code: 0  signal: null
21 info lifecycle node-sass@3.8.0~postinstall: node-sass@3.8.0
22 verbose lifecycle node-sass@3.8.0~postinstall: unsafe-perm in lifecycle true
23 verbose lifecycle node-sass@3.8.0~postinstall: PATH: C:\Users\hersh\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\bin\node-gyp-bin;C:\Users\hersh\AppData\Local\Temp\mt-1bjvknx.h19sg\npm\node_modules\.temp-9kk7w1.gmo9i\node_modules\node-sass\node_modules\.bin;C:\Users\hersh\AppData\Local\Temp\mt-1bjvknx.h19sg\npm\node_modules\.temp-9kk7w1.gmo9i\node_modules\.bin;C:\Users\hersh\AppData\Local\Temp\mt-1bjvknx.h19sg\npm\node_modules\.bin;C:\Users\hersh\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\bin;C:\Users\hersh\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Users\hersh\AppData\Local\Programs\Python\Python36-32;C:\Program Files\nodejs\;C:\Users\hersh\AppData\Local\Microsoft\WindowsApps;C:\Users\hersh\AppData\Local\.meteor;C:\Users\hersh\AppData\Roaming\npm
24 verbose lifecycle node-sass@3.8.0~postinstall: CWD: C:\Users\hersh\AppData\Local\Temp\mt-1bjvknx.h19sg\npm\node_modules\.temp-9kk7w1.gmo9i\node_modules\node-sass
25 silly lifecycle node-sass@3.8.0~postinstall: Args: [ '/d /s /c', 'node scripts/build.js' ]
26 silly lifecycle node-sass@3.8.0~postinstall: Returned: code: 1  signal: null
27 info lifecycle node-sass@3.8.0~postinstall: Failed to exec postinstall script
28 verbose stack Error: node-sass@3.8.0 postinstall: `node scripts/build.js`
28 verbose stack Exit status 1
28 verbose stack     at EventEmitter.<anonymous> (C:\Users\hersh\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
28 verbose stack     at emitTwo (events.js:126:13)
28 verbose stack     at EventEmitter.emit (events.js:214:7)
28 verbose stack     at ChildProcess.<anonymous> (C:\Users\hersh\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
28 verbose stack     at emitTwo (events.js:126:13)
28 verbose stack     at ChildProcess.emit (events.js:214:7)
28 verbose stack     at maybeClose (internal/child_process.js:925:16)
28 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
29 verbose pkgid node-sass@3.8.0
30 verbose cwd C:\Users\hersh\AppData\Local\Temp\mt-1bjvknx.h19sg\npm\node_modules\.temp-9kk7w1.gmo9i
31 verbose Windows_NT 10.0.16299
32 verbose argv "C:\\Users\\hersh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0_1\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe" "C:\\Users\\hersh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0_1\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--update-binary"
33 verbose node v8.9.3
34 verbose npm  v5.5.1
35 error code ELIFECYCLE
36 error errno 1
37 error node-sass@3.8.0 postinstall: `node scripts/build.js`
37 error Exit status 1
38 error Failed at the node-sass@3.8.0 postinstall script.
38 error This is probably not a problem with npm. There is likely additional logging output above.
39 verbose exit [ 1, true ]

**Comment by ardatan** [comment]
Please try angular-compilers
