### ISSUE TITLE
Uncaught Error: Cannot find module '/client/imports/app/app.module.ngfactory'

### ISSUE THREAD

**Issue by mbtechnologyil** [Urigo/angular-meteor#1827]
This is super frustrating, i am trying for a week already to make it work, i am getting this error in the browser after "meteor run":
Uncaught Error: Cannot find module '/client/imports/app/app.module.ngfactory'
my code is 1-1 same as in the example:
https://github.com/Urigo/angular-meteor/tree/master/examples/MeteorCLI
Any of them.. if wonder if anyone was able to make ANY of the examples work because i had no luck so far and i tried them all

**Comment by ardatan** [comment]
It is really interesting if you are getting this error in all-in-one and universal ones. Then, other weird thing is how you get this error in JIT mode.
Which example are you trying to run?

**Comment by mbtechnologyil** [comment]
in all of them actually, i didnt quite figured it out every time i  delete my project and doing clone again i get either this error or the browser get stuck with "javascript max stack exceed" error which blows up my pc
i am working on Windows 10

**Comment by hershko765** [comment]
also i forgot to mention that i am getting this error with --production flag only

**Comment by ardatan** [comment]
I wonder if you have ever tried to run it on other OS except Windows.
Could you please try ‘meteor update —all-packages’?

**Comment by hershko765** [comment]
ok it did updated lots of packages plus browser doesnt freeze anymore, but the main error still persists:
**Uncaught Error: Cannot find module '/client/imports/app/app.module.ngfactory'**

but now after running "meteor --production" it also says this:
C:/Users/hersh/projects/angular-meteor/imports/app/app.module.ngfactory.ts (77, 83): Property 'ɵ0' does not exist on type 'typeof "C:/Users/hersh/projects/angular-meteor/imports/app/app.module"'.

C:/Users/hersh/projects/angular-meteor/imports/app/app.module.ngfactory.ts (79, 33): Property 'ɵ1' does not exist on type 'typeof "C:/Users/hersh/projects/angular-meteor/imports/app/app.module"'.

C:/Users/hersh/projects/angular-meteor/imports/app/app.module.ngfactory.ts (80, 76): Property 'ɵ2' does not exist on type 'typeof "C:/Users/hersh/projects/angular-meteor/imports/app/app.module"'.

C:/Users/hersh/projects/angular-meteor/imports/app/server-app.module.ngfactory.ts (108, 84): Property 'ɵ0' does not exist on type 'typeof "C:/Users/hersh/projects/angular-meteor/imports/app/app.module"'.

C:/Users/hersh/projects/angular-meteor/imports/app/server-app.module.ngfactory.ts (110, 34): Property 'ɵ1' does not exist on type 'typeof "C:/Users/hersh/projects/angular-meteor/imports/app/app.module"'.

C:/Users/hersh/projects/angular-meteor/imports/app/server-app.module.ngfactory.ts (111, 77): Property 'ɵ2' does not exist on type 'typeof "C:/Users/hersh/projects/angular-meteor/imports/app/app.module"'.


**W20171212-00:44:39.262(2)? (STDERR) C:\Users\hersh\projects\angular-meteor\node_modules\zone.js\dist\zone-node.js:196
W20171212-00:44:39.268(2)? (STDERR)                         throw error;
W20171212-00:44:39.270(2)? (STDERR)                         ^
W20171212-00:44:39.270(2)? (STDERR)
W20171212-00:44:39.271(2)? (STDERR) Error: Cannot find module '../imports/app/server-app.module.ngfactory'
W20171212-00:44:39.272(2)? (STDERR)     at makeMissingError (packages\modules-runtime.js:231:12)
W20171212-00:44:39.272(2)? (STDERR)     at require (packages\modules-runtime.js:241:19)
W20171212-00:44:39.275(2)? (STDERR)     at main.js (server/main.ts:20:1)
W20171212-00:44:39.276(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20171212-00:44:39.277(2)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20171212-00:44:39.277(2)? (STDERR)     at server/main.ts:108:4
W20171212-00:44:39.278(2)? (STDERR)     at infos.forEach.info (C:\Users\hersh\projects\angular-meteor\.meteor\local\build\programs\server\boot.js:414:13)
W20171212-00:44:39.279(2)? (STDERR)     at Array.forEach (<anonymous>)
W20171212-00:44:39.279(2)? (STDERR)     at C:\Users\hersh\projects\angular-meteor\.meteor\local\build\programs\server\boot.js:413:9
W20171212-00:44:39.280(2)? (STDERR)     at C:\Users\hersh\projects\angular-meteor\.meteor\local\build\programs\server\boot.js:463:5**

**Comment by ardatan** [comment]
Could you please downgrade your typescript version ‘2.4.2’ by running?
‘meteor npm uninstall typescript —save-dev’
‘meteor npm install typescript@2.4.2 —save’

**Comment by hershko765** [comment]
didnt worked, thats my current package.json:

{
  "name": "angular-meteor-universal",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/router": "^5.0.0",
    "babel-runtime": "^6.20.0",
    "meteor-node-stubs": "~0.3.0",
    "meteor-rxjs": "^0.4.8",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "typescript": "^2.4.2",
    "@angular/compiler-cli": "5.1.0",
    "@types/meteor": "1.4.12",
    "@types/node": "8.0.57"
  }
}

**Comment by hershko765** [comment]
UPDATE:
i tried to set it up on ubuntu VM, took me 10 minutes to make it work + uploading to galaxy working version.

so not sure if it was obvious already but its windows issue, it wont matter to me much since i will work on docker linux container, but its still weird issue that i wish i could resolve

**Comment by nloeffler** [comment]
First, thanks for all the amazing work! 

I have the same windows problem.  When I do a normal compile (meteor run) on windows, I get the error : can't find module './app.html'.  Trying to use templateUrl throws the browser into a loop where it runs out of memory reloading the app component.  If I try to use the production flag, I get the error:

Uncaught Error: Cannot find module '/client/imports/app/app.module.ngfactory'

If I move the project into the windows linux subsystem, I can build the app (with or without the production flag) and it runs perfectly. I guess this is a windows related problem, but any thoughts on how to get it to work on windows?

Thanks again.

**Comment by ardatan** [comment]
Closed via #1889

**Comment by AirBorne04** [comment]
for me this issue still persists on windows, is there any fix that i have missed?
