### ISSUE TITLE
Deploy an angularcli-meteor project on Galaxy

### ISSUE THREAD

**Issue by kami97118** [Urigo/angular-meteor#1838]
Hi,
Would it be possible to have the guidelines to deploy an angularcli-meteor project on Galaxy?
(https://github.com/Urigo/angular-meteor/tree/master/examples/angularcli-meteor)
 The meteor project itself is inside the "api" folder, how to deploy the whole project using the conventional meteor deploy command?

**Comment by ardatan** [comment]
Galaxy can only host Meteor project that was created by MeteorCLI, so you can only deploy Meteor part of your project to Galaxy.
