### ISSUE TITLE
Custom typings not in an npm package

### ISSUE THREAD

**Issue by pmcochrane** [Urigo/angular-meteor#1840]
I'm having issues with typings using the latest compiler packages with the meteor cli. App is working correctly although compiler warnings are displayed on any change. Directly running tslint does not display any warnings.

It flatly refuses to include any typings that are not in an npm package. I've tried a million things but cannot get rid of the warnings. This worked without warnings in v0.2.8_1 although I did have to rewrite my tsconfig file to get it to work in that version.

However it is just throwing a million errors now with 0.2.9_2.

It just doesn't want to include any custom .d.ts files. These were in a typings folder as this is where they originally were placed way back when I started out with the app.

**How are we supposed  to declare custom typings for functions that are not in an npm file**? I cant seem to find a way to get the compiler to include them event though I have the following in my tsconfig file:
`"include": [
	  "index.d.ts",
	  "typings/**/*.d.ts",
	  ".e2e/specs/**/*.ts",
	  "lib/**/*.ts",
	  "both/**/*.ts",
	  "server/**/*.ts",
	  "client/**/*.ts",
	  "imports/**/*.ts"
  ],
  `

I'm sure that my .d.ts are correct otherwise they would have worked previously. They just seem to be being ignored by the compiler and throwing a warning.

For info here is one of my main .d.ts files:
`declare var consoledebug;
declare var consoleinfo;
declare var consolewarn;
declare var consolelog;
declare var consoleerror;
// declare var getAngularAnimationState;
declare var getEvergreenBrowserState;

declare var serverGlobals; // Server side global configuration variable
declare var globalsTest; 	// Global var for testing parameters

declare var SSR;		// This is for package meteorhacks:SSR
declare var UserStatus; // This is for package mizzao:meteor-user-status
declare var Soap;

// Adds Accounts.onlogout
declare module Accounts {
  function _checkPassword(user:Object, password:Object): any;
    function onLogout(func: Function): void;
}
declare module "meteor/accounts-base" {
    module Accounts {
        function onLogout(func: Function): void;
    }
}
declare module Accounts {
    function onLogout(func: (user: Meteor.User, connection: Meteor.Connection) => void): void;
}
declare module "meteor/accounts-base" {
    module Accounts {
        function onLogout(func: (user: Meteor.User, connection: Meteor.Connection) => void): void;
	}
}

// For Deanius:promise
declare module Meteor {
	function callPromise(name: string, ...args: any[]): any;	// PMC
}
declare module "meteor/meteor" {
	module Meteor {
		function callPromise(name: string, ...args: any[]): any;	// PMC
	}
}`

Example warnings:
`imports/server/publications/setupPublication.ts (113, 28): Cannot find name 'Match'. Did you mean 'Math'?
imports/server/publications/setupPublication.ts (117, 5): Cannot find name 'consoleerror'.
imports/server/publications/setupPublication.ts (118, 5): Cannot find name 'consoleerror'.
imports/server/publications/setupPublication.ts (126, 3): Cannot find name 'check'.
imports/server/publications/setupPublication.ts (126, 21): Cannot find name 'Match'.
imports/server/publications/setupPublication.ts (150, 4): Cannot find name 'Counts'.
imports/server/publications/setupPublication.ts (163, 5): Cannot find name 'consolewarn'.
imports/server/publications/setupPublication.ts (167, 5): Cannot find name 'consolelog'.
imports/server/publications/setupPublication.ts (171, 5): Cannot find name 'consolewarn'.
imports/server/publications/setupPublication.ts (174, 5): Cannot find name 'consolelog'.
imports/server/publications/setupPublication.ts (181, 2): Cannot find name 'consolelog'.
imports/server/server-main/server-main.ts (25, 3): Cannot find name 'consolelog'.
imports/server/server-main/server-main.ts (27, 3): Cannot find name 'consoleerror'.
imports/server/server-main/server-main.ts (29, 3): Cannot find name 'consolelog'.
imports/server/server-main/server-main.ts (34, 4): Cannot find name 'Roles'.
imports/server/server-main/server-main.ts (34, 45): Cannot find name 'Roles'.
imports/server/server-main/server-main.ts (38, 4): Cannot find name 'Roles'.
imports/server/server-main/server-main.ts (38, 45): Cannot find name 'Roles'.
imports/server/server-main/server-main.ts (42, 4): Cannot find name 'Roles'.
imports/server/server-main/server-main.ts (42, 45): Cannot find name 'Roles'.
imports/server/server-main/server-main.ts (46, 4): Cannot find name 'Roles'.
imports/server/server-main/server-main.ts (46, 45): Cannot find name 'Roles'.
imports/server/server-main/server-main.ts (51, 4): Cannot find name 'Roles'.
imports/server/server-main/server-main.ts (51, 45): Cannot find name 'Roles'.
imports/server/server-main/server-main.ts (88, 4): Cannot find name 'consoledebug'.
imports/server/server-main/server-main.ts (116, 3): Cannot find name 'consolelog'.
imports/server/server-main/server-main.ts (117, 3): Cannot find name 'consolelog'.
imports/server/server-main/server-main.ts (134, 4): Cannot find name 'consolelog'.
imports/server/server-main/server-main.ts (141, 4): Cannot find name 'consolelog'.
imports/server/server-main/server-main.ts (150, 6): Cannot find name 'consoledebug'.
imports/server/server-main/server-main.ts (167, 4): Cannot find name 'consoledebug'.
imports/server/server-main/server-main.ts (169, 5): Cannot find name 'consoledebug'.
imports/server/server-main/server-main.ts (189, 3): Cannot find name 'consolelog'.
imports/server/server-main/server-main.ts (207, 4): Cannot find name 'consolelog'.
imports/server/server-main/server-main.ts (213, 5): Cannot find name 'consolelog'.
node_modules/angular2-meteor-accounts-ui/src/annotations.ts (60, 41): Generic type 'Observer<T>' requires 1 type argument(s).
node_modules/angular2-meteor-accounts-ui/src/login-buttons.ts (2, 26): Cannot find module 'meteor/accounts-base'.
node_modules/protractor/exampleTypescript/spec.ts (18, 40): Argument of type '"Hello Julie!"' is not assignable to parameter of type 'Expected<Promise<string>>'.
node_modules/protractor/exampleTypescript/spec.ts (23, 38): Argument of type '2' is not assignable to parameter of type 'Expected<Promise<number>>'.
node_modules/protractor/exampleTypescript/spec.ts (24, 47): Argument of type '"build an angular app"' is not assignable to parameter of type 'Expected<Promise<string>>'.
both/collections/auditing.collection.ts (43, 13): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/batchProcessing.collection.ts (37, 20): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/crontab.collection.ts (31, 12): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/helpFiles.collection.ts (57, 14): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/options.collection.ts (24, 12): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/patientServiceNumbers.collection.ts (29, 26): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/patients.collection.ts (15, 13): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/ref_diagnosesCodes.collection.ts (31, 22): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/ref_isd_locations.collection.ts (42, 20): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/ref_isd_postcodes.collection.ts (54, 20): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/ref_retis_services.collection.ts (28, 21): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/ref_role_hierarchy.collection.ts (38, 21): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/referrals.collection.ts (36, 14): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/referrers.collection.ts (42, 14): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/sci_notifications.collection.ts (39, 21): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/searchIndex.collection.ts (50, 16): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/user_history.collection.ts (40, 16): Property 'attachSchema' does not exist on type 'Collection<{}>'.
both/collections/users.collection.ts (349, 10): Property 'attachSchema' does not exist on type 'Collection<User>'.
node_modules/karma/config.tpl.ts (13, 19): Cannot find name 'FRAMEWORKS'.
node_modules/karma/config.tpl.ts (17, 14): Cannot find name 'FILES'. Did you mean 'File'?
node_modules/karma/config.tpl.ts (22, 16): Cannot find name 'EXCLUDE'.
node_modules/karma/config.tpl.ts (28, 21): Cannot find name 'PREPROCESSORS'.
node_modules/karma/config.tpl.ts (51, 17): Cannot find name 'AUTO_WATCH'.
node_modules/karma/config.tpl.ts (56, 17): Cannot find name 'BROWSERS'.
both/_modules_shared.ts (70, 3): Cannot find name 'consoleerror'.
both/_modules_shared.ts (83, 4): Cannot find name 'consoledebug'.
both/_modules_shared.ts (87, 3): Cannot find name 'consoledebug'.
both/_modules_shared.ts (92, 4): Cannot find name 'consoleerror'.
both/_modules_shared.ts (100, 4): Cannot find name 'consoleerror'.
both/_modules_shared.ts (113, 4): Cannot find name 'consoleerror'.
both/_modules_shared.ts (114, 4): Cannot find name 'consoleerror'.
both/_modules_shared.ts (115, 4): Cannot find name 'consoleerror'.
both/_modules_shared.ts (137, 20): Cannot find name 'Roles'.
both/_modules_shared.ts (145, 21): Cannot find name 'Roles'.
both/_modules_shared.ts (877, 6): Cannot find name 'consolewarn'.
both/_modules_shared.ts (881, 6): Cannot find name 'consoleerror'.
both/_modules_shared.ts (887, 5): Cannot find name 'consolelog'.
both/_modules_shared.ts (892, 7): Cannot find name 'consoleerror'.
both/_modules_shared.ts (895, 6): Cannot find name 'consolelog'.
both/_modules_shared.ts (898, 5): Cannot find name 'consoledebug'.
both/_modules_shared.ts (929, 2): Cannot find name 'consoledebug'.
both/_modules_shared.ts (1238, 3): Cannot find name 'consolelog'.
both/_modules_shared.ts (1301, 3): Cannot find name 'consoleerror'.
both/_schema.functions.ts (37, 2): Cannot find name 'consolelog'.
both/_schema.functions.ts (39, 3): Cannot find name 'consolelog'.
both/_schema.functions.ts (49, 3): Cannot find name 'consolelog'.
imports/polyfills-ie.ts (2, 1): Cannot find name 'consolelog'.
imports/polyfills-ie.ts (18, 1): Cannot find name 'consolelog'.
imports/polyfills-ie.ts (22, 1): Cannot find name 'consolelog'.
imports/polyfills-ie.ts (25, 1): Cannot find name 'consolelog'.
imports/polyfills.client.ts (6, 2): Cannot find name 'consolelog'.
imports/polyfills.client.ts (11, 2): Cannot find name 'consolelog'.
server/main.ts (103, 3): Cannot find name 'consoledebug'.
server/main.ts (107, 4): Cannot find name 'consoledebug'.
`

**Comment by ardatan** [comment]
This is an issue, we will investigate this. Until bugfix, you can make this typings into your main.ts files, without using .d.ts.

**Comment by pmcochrane** [comment]
Thanks for your reply and help with the new compiler. It'll be worth it in the end but it's been a bit of a bug ridden upgrade so far for me. Hopefully there is light at the end of the tunnel for you and thanks for your efforts.

**Comment by pmcochrane** [comment]
Didn't realise I closed it by mistake Sorry

**Comment by bouchepat** [comment]
I'm having the same issue. App runs fine but the custom types are not picked up. 

**Kudo** on the new compiler, the app compiles and runs much faster. 

Looking forward to the fix for this issue.

**Comment by ardatan** [comment]
Could you try to remove .d extension from definition files?

**Comment by bouchepat** [comment]
Great, thank you, removing the .d extension fixed the issue. 
Will there be a fix in future releases, so we can re-add the .d extension?

**Comment by ardatan** [comment]
I hope so. We’re working on it. There is a lot of reason to have that restriction.
