### ISSUE TITLE
sass extention not supported

### ISSUE THREAD

**Issue by mattiLeBlanc** [Urigo/angular-meteor#1848]
I am using Angular Material with a custom theme.
File is in the .scss format, however, I like to write in SASS style.
However,
using the `angular2-compilers` `barbatus:typescript` ,I am getting issues when importing SCSS files into SASS files.

Then I tried `angular-compilers` instead of the other 2 and I notice I am getting typing errors of packages like 
```
node_modules/meteor-typings/1.3/test/test.ts (332, 18): Argument of type '<T>(post: { title: string; }) => void' is not assignable to parameter of type '<T>(doc: T, index: number, cursor: Cursor<T>) => void'.
  Types of parameters 'post' and 'doc' are incompatible.
    Type 'T' is not assignable to type '{ title: string; }'.
node_modules/meteor-typings/1.3/test/test.ts (729, 24): Type '(userId: string) => boolean' has no properties in common with type 'Matcher'.
```

Also, It does seem to ignore SASS files all together.
Being used to AngularCLI  now, I find the whole experience very rusty.

Are there any way around this?

**Comment by ardatan** [comment]
Importing sass files is described in here:
https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers

Could you try to use `@types/meteor` instead of meteor-typings?

**Comment by mattiLeBlanc** [comment]
Hi, first of all thanks for your help!

I apparently had @types/meteor (older version) and meteor-typings (which I removed).
It seems to compile pretty, good. However I a running into 2 issues:

1)
my imports of meteor packages can't be resolved, mainly `meteor/account-base` and `meteor/meteor`.
I guess since they are not NPM packages VSCODE doesn;t know where to look for them. Does thsi require a TSCONFIG change?


2) I am getting a `Uncaught ReferenceError: __decorate is not defined
    at app.component.ts:12`
![image](https://user-images.githubusercontent.com/5285035/34465348-4b7a83c8-eefc-11e7-8c8b-f9b8128b3f34.png)

**Comment by ardatan** [comment]
Could you install tslib by
‘meteor npm install tslib —save’ ?
31 Ara 2017 Paz, saat 22:02 tarihinde Matti LeBlanc <
notifications@github.com> şunu yazdı:

**Comment by ardatan** [comment]
Could you install tslib by ‘meteor npm install tslib —save’?

**Comment by mattiLeBlanc** [comment]
I am still getting the `decorate` issue after installing tslib.

**Comment by mattiLeBlanc** [comment]
okay, I created a new clean meteor app, adding angular5 to it and following the instructions on the angular-meteor page.
I am still getting the decorate error.
Checkout out:
https://github.com/mattiLeBlanc/angular5

Hope you can see what I am doing wrong.

**Comment by ardatan** [comment]
You have to use same settings with tsconfig in MeteorCLI examples.

**Comment by mattiLeBlanc** [comment]
@ardatan  can you point me to the example you are referring to?
That is one of my issues...I find so many conflicting examples if I start from the meteor site. The Whatsapp clone is a mix of old and new stuff, it's very confusing.
I am so used to Angular CLI now where the whole setup is taken care of and everything just works.
I hope to finally find out what would be a good boilerplate to start with NG5 and Meteor.

**Comment by mattiLeBlanc** [comment]
@ardatan  okay. I  assume you meant these: https://github.com/Urigo/angular-meteor/tree/master/examples/angularcli-meteor

Looks like this was a fine puzzle to get it to work :(

**Comment by mattiLeBlanc** [comment]
okay, I resolved it.
I added 
`importHelpers: true` to my tsconfig.

And then I added
`import 'zone.js/dist/zone';` to my main.ts.

Now it is working.

I have updated the repo.
