### ISSUE TITLE
Lazy loading: Unexpected token < 

### ISSUE THREAD

**Issue by bouchepat** [Urigo/angular-meteor#1851]
I updated all the lazy loading modules as per repo example:
```
...
children: [
            {
                path: '',
                loadChildren: '../web/home/home.module#HomeModule'
            },
...
```
 But I'm getting this error, when run locally:

```
Unexpected token <
  Evaluating http://localhost:3000/client/web/home/home.module
  Loading /client/web/home/home.module
```
--- 
Previously, I lazy loaded my modules with the arrow function, but it throws an error when building app for deployment to server (i believe this is related to AOT):
```
Error encountered resolving symbol values statically. 
Function calls are not supported. Consider replacing the function 
or lambda with a reference to an exported function
```
```
...
children: [
            {
                path: '',
                loadChildren: () => HomeModule
            },
...
```
Any ideas on how I could fix this?
Thanks.

**Comment by ardatan** [comment]
Could you try to use similar file structure with our examples, because MeteorCLI cannot detect source files in different variations somehow. I think it is not related to compiler, because it doesn’t work like webpack or other bundlers.

**Comment by bouchepat** [comment]
Changing the structure of the app at this stage is not yet an option.  I noticed the polyfills in the examples,
especially:

```
declare var module : any;
global['System'] = {
  import(path: string){
    return module.dynamicImport(path);
  }
}
```
Once I added this, the lazy loading start to work as expected as long as the path were defined relatively.
Maybe this should be added in the documentation somewhere...
