### ISSUE TITLE
Possible to add Stylus and Sass examples? 

### ISSUE THREAD

**Issue by mattiLeBlanc** [Urigo/angular-meteor#1857]
Hi,

Thanks for your effort so far in setting up this great package.

I was wondering if Stylus and or Sass can also be supported.
I tried adding 'stylus' npm myself and run the render function but it doesn't seem to return CSS but rather creates a CSS file.
If I add the styles package to meteor, I can't create component stylus files because I think everything ends up in merged_stylesheets.

Is this hard to do, are there any examples you can point at so that I can figure it out?

Much appreciated.

**Comment by hershko765** [comment]
Which xli are you using?
For angular cli, i created new app with ng new style=scss
Then i ejected it with bg eject and copy-paste diffs in the webpack xonfig file

If you use meteor cli, stop using it its fucking slow and usless

**Comment by mattiLeBlanc** [comment]
I am using Meteor CLI, yes. I saw that there is also a NG CLI version of Angular-Meteor.
You recommend using that one?

Urigo wrote down a whole set of instructions how to run Meteor only on the server side and have NG  CLI on the front. 
Is that the way to go?

I love NG CLI, I use it a lot and I just came back to rewrite an old Angular 1.6 Meteor app to Angular 5 so I started running into issues with Meteor. But I got it working now.
However, I would be interested in the NG CLI experience.

**Comment by hershko765** [comment]
Meteor is cool framework that does stuff that no one do, but that comes with price of marriage to them and there components which are super slow and doesnt work alot of tine, dont break your head on meteor cli, urigo did wonderfull think when he developed the meteor client bundler, you should try the angular cli its super fast at compiling with webpack.

**Comment by mattiLeBlanc** [comment]
@hershko765  okay. So just to be clear do you suggest using Urigo's solution (https://github.com/Urigo/angular-meteor/tree/master/examples/angularcli-meteor) or do you another template?

**Comment by mattiLeBlanc** [comment]
@hershko765 I followed the angularcli-meteor instructions. This is freakin amazing.
@darkbasic Great tutorial about using ng-cli and meteor. 
Can you add a section about how to host this maybe? Do we have to 'demeteorize' or can we just put the build within a nodejs server?
