### ISSUE TITLE
angular-templates not parsing html properly with Meteor 1.6.1, maybe due to babel-complier incompatibilities?

### ISSUE THREAD

**Issue by leosco** [Urigo/angular-meteor#1878]
After upgrading to Meteor 1.6.1 on `angular-templates` 1.0.3, I get the following error at startup.
```
=> Errors prevented startup:                  
   
   While processing files with angular-templates (for target web.browser):
   client/index.html:8: Parse error in tag
```
https://blog.meteor.com/announcing-meteor-1-6-1-50aad71da4e6
See the blog post above, it details a breaking change with `babel-compiler` that would break any Atmosphere package that didn't update it's version constraints for usage of the package. 

Not sure if that's the issue here, but everything was working fine before I updated.

**Comment by ardatan** [comment]
angular-templates was deprecated, you have to switch the old compilers to our new compilers for Meteor 1.6.x

https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers

**Comment by leosco** [comment]
Does this still support Angular 1.x? Or am I stuck on Meteor 1.6 until I completely rewrite to Angular?

**Comment by ardatan** [comment]
You have to switch `angular-compilers`, and remove html and scss imports in your source files and use `templateUrl` instead. You can see the example below;
https://github.com/Urigo/angular-meteor/tree/master/examples/angularjs

**Comment by leosco** [comment]
Awesome, thanks for the help!

**Comment by dohomi** [comment]
@ardatan I currently try to update my code to Meteor 1.6.1.1. and switch from angular-templates to angular-compiler.

I receive following error right now:
```
[client]: HTML Files Compilation: 176.508ms  -
[client]: ES2015 modules Compilation: 442.446ms
[client]: SCSS Files Compilation: 0.038ms    /
[server]: HTML Files Compilation: 4.891ms    -
[server]: ES2015 modules Compilation: 42.740ms
node_modules/parchment/src/blot/abstract/blot.ts (9, 12): Cannot find name 'Node'.
node_modules/parchment/src/blot/abstract/blot.ts (29, 21): Cannot find name 'MutationRecord'.
node_modules/parchment/src/blot/abstract/blot.ts (34, 12): Cannot find name 'HTMLElement'.
node_modules/parchment/src/blot/abstract/blot.ts (54, 15): Cannot find name 'Node'.
node_modules/parchment/src/blot/abstract/blot.ts (55, 49): Cannot find name 'Node'.
[server]: SCSS Files Compilation: 0.039ms    -
=> Errors prevented startup:                  
   
   While processing files with angular-compilers (for target web.browser):
   packages/angular-typescript-compiler/index.js:269:37: Cannot read property 'module' of undefined (at AngularTsCompiler.processFilesForTarget)

```

I haven't done the whole transition to change all .html file imports, is this maybe connected? 
How exactly is the behaviour of the angular-templates different to angular-compiler? This is an example component from my app:
```js
import WidgetFollowerController from './WidgetFollowerController';
import tmpl from './widgetFollower.html';
const widgetFollower = {
    templateUrl: tmpl,
    controller: WidgetFollowerController,
    bindings: {
        isFollowedBy: '<?'
    }
};
export default widgetFollower;
```
Do I need to walk through all files and remove the import statement and copy the relative path to
```
templateUlr: './widgetFollower.html'
```
Thanks for your help

**Comment by ardatan** [comment]
You have to do whole thing (removing imports, and using the relative path to the project). 
‘angular-templates’ gets the html content and injects it to the javascript
code directly. However, ‘angular-compilers’ doesn’t do this; it serves html files to be accessed via ‘templateUrl’ stuff. That’s why, it is faster.
Check this out.
https://github.com/Urigo/angular-meteor/tree/master/examples/angularjs

**Comment by dohomi** [comment]
Ok thanks for clarifying this, one more question though. On the atmosphere page https://atmospherejs.com/meteor/angular-templates you recommend the use of `urigo:static-templates`, what is this template for? Thanks again

**Comment by ardatan** [comment]
You don’t need any other packages than ‘angular-compilers’. Just install that package, and change your source files like the example I sent.

**Comment by dohomi** [comment]
@ardatan I removed all `import * .html` statements in all my js files. The error still persists:
```
   While processing files with angular-compilers (for target web.browser):
   packages/angular-typescript-compiler/index.js:269:37: Cannot read property 'module' of undefined (at AngularTsCompiler.processFilesForTarget)
```
One question: does for example `<ng-include src="somePath/to/file.html">` will still work with angular compiler? Do you have an idea how to track down the error?

**Comment by ardatan** [comment]
If you don’t have any ts files, typescript compiler shouldn’t be triggerred. Can you reproduce a repo? And the only supported way to use angularjs with this compiler is the way you can see in the example. Other methods are not supported. And other questions except issues please use stackoverflow.

**Comment by dohomi** [comment]
@ardatan I don't use typescript for my project. Is it possible that typescript compiler is triggered through npm package (I'm using quill for example which leads to warning like `node_modules/parchment/src/blot/abstract/blot.ts (9, 12): Cannot find name 'Node'.`
I've seen that you target this in a seperate issue. Thanks again for your help I'll try to isolate the issue
