### ISSUE TITLE
Cannot find module './app.component.scss' after meteor update 1.4 to 1.6.1

### ISSUE THREAD

**Issue by klynicol** [Urigo/angular-meteor#1880]
Just updated my meteor from 1.4 to 1.6.1

I fixed the issue I was getting with babel-runtim by running `meteor install --save @babel/runtime`
Now the server seems to start without a hitch, but there's only the "loading..." screen in my client with an error of `Cannot find module './app.component.scss'` 

Thought maybe my angular2 complilers needed to be updated, but they seem to be up to date.

Here's my versions

 >accounts-base@1.4.2
accounts-facebook@1.3.1
accounts-oauth@1.1.15
accounts-password@1.5.0
alanning:roles@1.2.16
allow-deny@1.1.0
angular2-compilers@0.5.7
angular2-html-templates@0.5.3
autoupdate@1.4.0
babel-compiler@7.0.2
babel-runtime@1.2.2
barbatus:typescript@0.6.12
barbatus:typescript-compiler@0.9.12
barbatus:typescript-runtime@1.0.2
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-tools@1.0.10
boilerplate-generator@1.4.0
caching-compiler@1.1.11
caching-html-compiler@1.0.7
callback-hook@1.1.0
check@1.3.0
coffeescript@1.0.17
ddp@1.4.0
ddp-client@2.3.1
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.1.2
deps@1.0.12
diff-sequence@1.1.0
dispatch:mocha-phantomjs@0.1.9
dispatch:phantomjs-tests@0.0.7
dynamic-import@0.3.0
ecmascript@0.10.2
ecmascript-runtime@0.5.0
ecmascript-runtime-client@0.6.1
ecmascript-runtime-server@0.5.0
ejson@1.1.0
email@1.2.3
es5-shim@4.7.3
facebook-config-ui@1.0.1
facebook-oauth@1.4.0
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.4.0
hwillson:stub-collections@1.0.6
id-map@1.1.0
jquery@1.11.11
launch-screen@1.1.1
livedata@1.0.18
localstorage@1.2.0
logging@1.1.19
meteor@1.8.2
meteor-base@1.3.0
minifier-css@1.3.0
minifier-js@2.3.1
minimongo@1.4.3
mobile-experience@1.0.5
mobile-status-bar@1.0.14
modules@0.11.3
modules-runtime@0.9.2
mongo@1.4.3
mongo-dev-server@1.1.0
mongo-id@1.0.6
npm-bcrypt@0.9.3
npm-mongo@2.2.34
oauth@1.2.1
oauth2@1.2.0
observe-sequence@1.0.16
ordered-dict@1.1.0
practicalmeteor:chai@2.1.0_1
practicalmeteor:loglevel@1.2.0_2
practicalmeteor:mocha@2.4.5_6
practicalmeteor:mocha-core@1.0.1
practicalmeteor:sinon@1.14.1_2
promise@0.10.1
random@1.1.0
rate-limit@1.0.8
reactive-dict@1.2.0
reactive-var@1.0.11
reload@1.2.0
retry@1.1.0
routepolicy@1.0.12
server-render@0.3.0
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.3.1
shim-common@0.1.0
socket-stream-client@0.1.0
softwarerero:accounts-t9n@1.3.11
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.10
standard-minifier-css@1.4.0
standard-minifier-js@2.3.1
templating@1.2.15
templating-compiler@1.2.15
templating-runtime@1.2.15
templating-tools@1.1.2
tmeasday:test-reporter-helpers@0.2.1
tracker@1.1.3
twbs:bootstrap@3.3.6
underscore@1.0.10
url@1.2.0
useraccounts:core@1.14.2
useraccounts:unstyled@1.14.2
vazco:universe-html-purifier@1.2.3
webapp@1.5.0
webapp-hashing@1.0.9
xolvio:cleaner@0.3.1

package.json

`     {
      "name": "angular2-meteor-base",
      "private": true,
      "scripts": {
    "start": "meteor run",
    "start:prod": "meteor run --production",
    "build": "meteor build ./build/",
    "clear": "meteor reset",
    "meteor:update": "meteor update --all-packages",
    "test": "meteor test --driver-package practicalmeteor:mocha",
    "test:ci": "meteor test --once --driver-package dispatch:mocha-phantomjs"
  },
  "devDependencies": {
    "@types/chai": "3.4.34",
    "@types/meteor": "^1.3.31",
    "@types/mocha": "2.2.34",
    "chai": "3.5.0",
    "chai-spies": "0.7.1",
    "meteor-node-stubs": "0.2.4"
  },
  "dependencies": {
    "@angular/common": "2.4.1",
    "@angular/compiler": "2.4.1",
    "@angular/core": "2.4.1",
    "@angular/forms": "2.4.1",
    "@angular/platform-browser": "2.4.1",
    "@angular/platform-browser-dynamic": "2.4.1",
    "@angular/router": "3.4.1",
    "@babel/runtime": "^7.0.0-beta.39",
    "@types/angular": "^1.6.39",
    "angular2-meteor": "0.7.1",
    "angular2-meteor-accounts-ui": "^1.0.0",
    "angular2-meteor-polyfills": "0.1.1",
    "angular2-meteor-tests-polyfills": "0.0.2",
    "angular2-modal": "^2.0.3",
    "babel-runtime": "^6.26.0",
    "bcrypt": "^1.0.3",
    "bootstrap": "^3.3.7",
    "meteor-rxjs": "0.4.7",
    "reflect-metadata": "0.1.9",
    "rxjs": "5.0.2",
    "zone.js": "0.7.4"
  }
}`

**Comment by pbureau** [comment]
I confirm I have the same problem, upgrading meteor to 1.6.1 from 1.6.0.1 for my angular/meteor app. I guess will keep using meteor 1.6.0.1 for the moment.

**Comment by pbureau** [comment]
is this related with #1855 ??

**Comment by impcyber** [comment]
@pbureau yes, related
At the moment there is a solution only downgrade:
`meteor update --release 1.6.0.1`

**Comment by lokiribeiro** [comment]
I am also encountering the same error with this, I am using 1.6.0.1 and followed all the steps on step 1 of angular2-meteor socially app tutorial and could not proceed further because of this error; I could only see Loading... on my page when i tried to run the app.

**Comment by impcyber** [comment]
@lokiribeiro Try `angular-compilers`
https://github.com/Urigo/angular-meteor/issues/1882

**Comment by ardatan** [comment]
Usage of sass files in Angular-Meteor was changed after `angular-compilers`. You can see the new method to use scss files in your components.
https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers
If you have any further issues still going on, please open a new issue, and let us know.
