### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by choudrio** [Urigo/angular-meteor#1886]
@Urigo @ardatan 
What is the status of this project? There have been no official replies to issues for quite some time.
Last commit 3 months ago.

Is this project dead?

**Comment by Urigo** [comment]
@choudrio sorry about that.  I am working on something else and was a bit away.
If you want, I would be happy to meet on video and help you with any issue you might have and get it merged and release a new version.
My email is public on my Github profile.  Google Hangouts is my prefered way of communications

**Comment by portah** [comment]
Hi @Urigo, I hope everything is ok and you just extremely busy. Ppl did some PRs on different yours projects: https://github.com/Urigo/meteor-client-bundler/pull/55

**Comment by Urigo** [comment]
today we've released new versions for `angular-compilers` and `meteor-client-bundler` as well with a few fixes and to support the latest Meteor 1.6.1, thanks to the great work of @ardatan and @afaur !
Let us now if everything works as expected.

In the future, issues that actually try to address an issue and give new information about the issue would be more helpful.
I hope to keep pushing and offer more and more solutions for angular-meteor developers
