### ISSUE TITLE
Error migrating from angular-templates to angular-compilers (Angular 1.5.3)

### ISSUE THREAD

**Issue by buymybm100** [Urigo/angular-meteor#1892]
I need to migrate out of **angular-templates** as it has been deprecated. I am still using Angular 1 and my Components are defined using **templateUrl** and **controllerAs** syntax.

I have replaced angular-templates with angular-compilers and now get an error that the HTML cannot be found.

> Uncaught Error: Cannot find module './guest.html'

Code snippet:
```
import './guest.html';
const name = 'guest';

export default angular.module(name, [
])
  .component(name, {
    templateUrl: `imports/ui/components/${name}/${name}.html`,
    controllerAs: name,
    controller: Guest
  })
  .config(config);

function config($stateProvider) {
  'ngInject';

  $stateProvider.state('guest', {
    url: '/guest',
    views: {
      'mainContent': {
        template: '<guest></guest>'
      }
    },
  });
}

```
**Environment**
Angular-meteor v1.3.11
Meteor v1.6.0

Can anyone help ? 

Many Thanks,
Beemer

**Comment by ardatan** [comment]
You don't need to import html template in JS file. Could you please remove that line and try again?

**Comment by buymybm100** [comment]
Thanks @ardatan , that moved it forward. Not getting the error now after removing all the HTML imports. 

Now, the pages display but there is no CSS styling.  My  CSS/SCSS  files are kept in **/clients/styles** folder.  Do I need to specify each one ? I think angular-templates used to pick everything up automatically.

**Comment by ardatan** [comment]
There are two types of process for SCSS compilation;
If the file is under any 'imports' subdirectory, it is not directly added to page.
If the file is NOT under any 'imports' subdirectory, it is directly added to page.

So you have import scss files in CSS files or directly-added SCSS files.

But CSS Compilation is different, all css files are directly added to page.

**Comment by buymybm100** [comment]
I have created a main.scss to import all the SCSS files the App needs.
When I go into  ~/local/build/programs/web.browser/app/client , I can see that **main.scss** has included all the SCSS files correctly.
However, the **merged-stylesheets.css** that is served, has none of the styles.

Do I need to bootstrap with platformBrowserDynamic().bootstrapModule(AppModule) ? 
At present, I am using  this : 

angular.bootstrap(document, [ MyApp ], {strictDi: true  });

**Comment by ardatan** [comment]
No, you are using AngularJS.
Could you use CSS extension instead of SCSS?

**Comment by ardatan** [comment]
We just added a new example for AngularJS;
https://github.com/Urigo/angular-meteor/tree/master/examples/angularjs
You can see the usage of HTML and SCSS files.

**Comment by buymybm100** [comment]
Many Thanks, @ardatan. As per the example,  I have updated to Angular 1.6.9 and Meteor 1.6.1
The SCSS styles are fine now.  I have also removed main.scss as there was no need to manually import the various scss files. Thanks again!

**Comment by ardatan** [comment]
Happy to hear you made it! Your welcome.
