### ISSUE TITLE
angular2-boilerplate infinite loop issues [meteor-tool@1.6.0]

### ISSUE THREAD

**Issue by imad-abdou** [Urigo/angular-meteor#1903]
hello, im trying to install angular meteor using these three commands:
$ git clone https://github.com/bsliran/angular2-meteor-base ngMeteor
$ npm install
$ meteor
but the terminal stuck in infinite loop of downloading after typing the last commands 
platform: Ubuntu 16.04 LTS
Meteor: 1.6.1
node: 9.8.0
npm: 5.6.0

**Comment by ardatan** [comment]
That example is deprecated you can checkout the new one;
https://github.com/Urigo/angular-meteor/tree/master/examples/MeteorCLI/bare
