### ISSUE TITLE
Property 'mergeMap' does not exist on type 'ObservableCursor<Chat>'

### ISSUE THREAD

**Issue by kenpachi-zaraki** [Urigo/angular-meteor#1904]
After completing chapter 4 (Realtime Meteor Server) : 
https://angular-meteor.com/tutorials/whatsapp2/ionic/meteor-server-side
then, running "meteor" command in "api" directory
and, running "ionic serve" command in "whatsapp" directory
I'm getting the error below:

$ ionic serve
Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 35729
--dev-logger-port 53703 --nobrowser - Ctrl+C to cancel
[15:31:35]  watch started ...
[15:31:35]  build dev started ...
[15:31:35]  clean started ...
[15:31:35]  clean finished in 44 ms
[15:31:35]  copy started ...
[15:31:36]  deeplinks started ...
[15:31:36]  deeplinks finished in 24 ms
[15:31:36]  transpile started ...
[15:31:42]  typescript: src/pages/chats/chats.ts, line: 18
            Property 'mergeMap' does not exist on type 'ObservableCursor<Chat>'.

      L17:  .find({})
      L18:  .mergeMap((chats: Chat[]) =>
      L19:      Observable.combineLatest(

[15:31:42]  typescript: src/pages/chats/chats.ts, line: 23
            Property 'startWith' does not exist on type 'ObservableCursor<Message>'.

      L22:  .find({chatId: chat._id})
      L23:  .startWith(null)
      L24:  .map(messages => {

[15:31:42]  dev server running: http://localhost:8100/

[OK] Development server running!
     Local: http://localhost:8100
     External: http://10.0.2.15:8100
     DevApp: whatsapp@8100 on debian

[15:31:42]  copy finished in 6.95 s
[15:31:42]  watch ready in 7.14 s

Can you please help?

**Comment by ardatan** [comment]
I think that example should be updated. For now, you can add
import 'rxjs/add/operator/mergeMap';

**Comment by kenpachi-zaraki** [comment]
Thanks @ardatan  . I already tried : 
import 'rxjs/add/operator/mergeMap';
but it did not work.

However, you're are right. The tutorial example needs to be updated.

The correction has already been made in file:
src/pages/chats/chats.ts
on the github repository:
https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp

**Comment by mikenetcode** [comment]
Just tried to complete the tutorial too and just completed chapter 8.
Actually I'm trying to migrate my own app from ionic 1 & angular 1 with meteor backend and I'm not into typescript so far. So I hope my explanations are correct.

If you install all packages now you actually use typescript 2.6, angular 5 and rxjs 5.5 and that seems to be the major problem.

First you need to pipe all operators and change the imports to lettabale operators, like mentioned here: https://medium.com/coding-snippets/rxjs-5-5-property-map-does-not-exist-on-type-observable-e825129c2068

Also you have to change the composite publication of chats on meteor side:
`Meteor.publishComposite('chats', function(): PublishCompositeConfig<Entity> {` to
`Meteor['publishComposite']('chats', function(): PublishCompositeConfig<Entity> {`
like mentioned here: https://github.com/Urigo/angular-meteor/issues/1499

After this you still get an errors like: Type 'Observable<Chat[]>' is not assignable to type 'Observable<Chat[]>'. This generally means you have two copies of RxJs installed, like mentioned here: 
https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/56,
https://github.com/ngrx/store/issues/338,
https://stackoverflow.com/questions/42917003/type-observableany-is-not-assignable-to-type-observableany

In our special case we do not really have 2 versions of RxJs installed, but typescript 2.4.2+ detects the symlink of the node_modules dir in the api dir (= meteor server) as a second version. To fix this just completely seperate client & server:

1. remove all symlinks from api dir and copy orginal files
(2. run the meteor-client bundler again (npm run meteor-client:bundle) and copy meteor-client.js to ionic's node_modules dir)
3. copy collections dir and models.ts (from api/server) to ionic's src dir
4. correct paths of all collections and model imports
3. remove api alias from webpack.config & tsconfig.json
4. move api dir out of ionic project dir
5. start meteor & ionic manually 

Things should work out again ;-)

**Comment by bronze15** [comment]
tengo ese  mismo problema HELP PLEASE

Typescript Error
Property 'zone' does not exist on type 'Observable<{}>'

this.message
--
  | ).zone().subscribe(() => {
  | // Zero the input field


`${location.lat},${location.lng},${location.zoom}`
--
  | ).zone().subscribe(() => {
  | // Zero the input field


picture.url
--
  | ).zone().subscribe();
  | });

**Comment by vicnala** [comment]
Please try to remove ".zone()" and see if it works (it does for me).

**Comment by bronze15** [comment]
I tried it anyway, apparently there is new tersuon brings that problem and causes that error, as I have seen it on the internet in other projects

Descarga Outlook para iOS<https://aka.ms/o0ukef>
________________________________
