### ISSUE TITLE
Watch changes files 

### ISSUE THREAD

**Issue by ffaouzif** [Urigo/angular-meteor#1905]
The app will automatically reload if you change any of the source files. as defined on instructions tuto.
 after runing npm run start it work fine, but when i change some files it not watching , so i have to re use the comande again ?

**Comment by ffaouzif** [comment]
Meteor CLI

**Comment by ffaouzif** [comment]
source file of ts

**Comment by ardatan** [comment]
Could you reproduce a repo?

**Comment by ardatan** [comment]
Closed due to inactivity.
