### ISSUE TITLE
angular-compiler issue

### ISSUE THREAD

**Issue by ab-ankhbayar** [Urigo/angular-meteor#1906]
I've updated meteor version from 1.6.0.1 to 1.6.1.1. So, I had to update compilers too. I've removed angular2-compilers and added angular-compilers. Since then there is 'exports is not defined' error. I think this is compiler related issue. Any help?

**Comment by dohomi** [comment]
Hi I also have upgrade issues at the moment (with AngularJS 1.5.x). In the atmosphere package you recommend to switch from https://atmospherejs.com/meteor/angular-templates to urigo:static-templates. What would be the best for Angular 1.x users?

**Comment by ardatan** [comment]
Closed due to the inactivity.
