### ISSUE TITLE
External DB URL for ionic2

### ISSUE THREAD

**Issue by dnyaneshwaruttarwar** [Urigo/angular-meteor#1908]
Hi,

I've developed an application in ionic2 and now I want to integrate the meteor for chat application I have gone through the below tutorial 
https://angular-meteor.com/tutorials/whatsapp2/ionic/3.0.0/setup

but I'm having the question 
1) Where to deploy the meteor server (I haven't seen in the tutorial)
2) How to set the external mongo database

please help

**Comment by ardatan** [comment]
You can see the documentation of Meteor;
https://guide.meteor.com/deployment.html#galaxy-mongo
https://guide.meteor.com/deployment.html
