### ISSUE TITLE
Angular 5 meteor not running

### ISSUE THREAD

**Issue by kmahalingpur** [Urigo/angular-meteor#1910]
Hi, I'm new to the meteor. I was searching for angular 5 with meteor I found this repo, I tried to clone the repo as mentioned in the quick start as 
   $ git clone https://github.com/Urigo/angular-meteor-base myApp
   $ cd myApp
   $ meteor npm install
But the first time I got heap full error and the second time when I ran npm start app started but when I access it in the browser but the page is not loading at all. I tried the examples/meterocli/bare same issue and is there any correct tutorial how to run angular 5 with the meteor. One more thing I'm not able to find the Mongo DB URL in repo may I know where it will be.
Or is it better to go with angular5 and meteor as separate service??

Please help thanks in advance.

**Comment by atao60** [comment]
With the previous issue #1909 a [working demo](https://github.com/atao60/meteor-angular-no-type-declaration) is provided based on [Angular Meteor bare MeteorCLI example](https://github.com/Urigo/angular-meteor/tree/master/examples/MeteorCLI/bare).
The warning messages about missing declaration files can be ignored.

**Comment by ardatan** [comment]
Closed due to inactivity.
