### ISSUE TITLE
Angular 5 migrating meteor 1.6 to 1.6.1.1: Can't resolve all parameters for (?, ?, ?).

### ISSUE THREAD

**Issue by onhate** [Urigo/angular-meteor#1917]
I have an application running on meteor 1.6 and after upgrading to 1.6.1.1 I get the following error on browser console:

As is possible to see in the code, I have emitDecoratorMetadata as true in tsconfig.json

`Uncaught Error: Can't resolve all parameters for TranslateService: (?, ?, ?).`

I have created a replica of my project with all other dependencies I have in the project and only a single set of files to reproduce the issue.

**Angular Version**: 5.2.11
**Meteor Version**: 1.6.1.1

Steps to reproduce:
```
git clone https://github.com/onhate/meteor-1.6.1.1-upgrade-issue
cd meteor-1.6.1.1-upgrade-issue
npm install
npm start
```

**Comment by ardatan** [comment]
It is not related to `angular-compilers`. Probably a library in your application module is not AOT-compatible.
https://github.com/ngx-translate/core/issues/137
