### ISSUE TITLE
Updating AngularCLI-Meteor Example Dependencies

### ISSUE THREAD

**Issue by InsaneNaman** [Urigo/angular-meteor#1919]
As Angular community has released its new version (Angular 6) and it depends on a newer version of RxJS. So, it would be great if one can update dependency of this example: [https://github.com/Urigo/angular-meteor/tree/master/examples/angularcli-meteor](https://github.com/Urigo/angular-meteor/tree/master/examples/angularcli-meteor ). It would be easy for everyone to get started. TIA

**Comment by InsaneNaman** [comment]
Sure, I will do as soon as I get some free time. :smile:

**Comment by mfechner** [comment]
That would really be very helpful!
I currently started to look into meteor. As I would use meteor together with angular I would like to stick the the angular cli.
Meteor should only be a "module" that is used in the angular project.

Currently I cannot get the example running with angular 6.

If an update version is available I would like to test it and see if the example is fine. The example should maybe also include `meteor/accounts-base` to have standard auth available.

Thanks a lot!

**Comment by ansaries** [comment]
I have only updated all-in-one Meteor CLI example with Meteor 1.7.0.3 and Angular 6 in PR #1928. 
Its working with --production and even with AOT=1

Others examples will follow once this PR will be approved.

**Comment by georgyberdyshev** [comment]
Hello everyone,
if you would like to test the changes in PR #1927 

Modification for Meteor 1.7.0.3 with Angular 6.0.6 are already included and should
make it easier to get started on the updates for Angular CLI updates.

Thanks, Georgy

**Comment by ardatan** [comment]
You can see the new version of AngularCLI-Meteor boilerplate. It is now simpler than before.
https://github.com/Urigo/angular-meteor/tree/master/examples/AngularCLI
