### ISSUE TITLE
MeteorCli-bare not working with agm-marker-cluster

### ISSUE THREAD

**Issue by cbodapati** [Urigo/angular-meteor#1920]
I tried get the [agm-marker-cluster](https://angular-maps.com/api-docs/js-marker-clusterer/directives/AgmMarkerCluster.html) functionality working but failed. I tried all the work-arounds suggested by other developers in various portals..

I created a repo to reproduce the problem - https://gitlab.com/cbodapati/agmClusterTest.git

I tried this functionality in a pure Angular6, it works as expected.

expected behaviour - [agm-marker-cluster](https://angular-maps.com/api-docs/js-marker-clusterer/directives/AgmMarkerCluster.html) should work with MeteorCLI.

**Comment by ardatan** [comment]
I think there is a problem with UMD bundle of `agm-marker-cluster`.

**Comment by cbodapati** [comment]
Thanks for looking into this...
I made a test build in angular6 and  agm-marker-cluster works as expected.

**Comment by cbodapati** [comment]
Please look into that again, its working fine in Angular6...

**Comment by ardatan** [comment]
If you mean Angular CLI, it uses ES2015 not CommonJS like Meteor. There is a problem with CommonJS/UMD bundle of this package which is completely unrelated with Meteor.

**Comment by cbodapati** [comment]
Thanks for you time and effort. I will check with the agm guys.
