### ISSUE TITLE
Angular 6 AOT compilation disabled

### ISSUE THREAD

**Issue by weini01** [Urigo/angular-meteor#1922]
Hi,

I just updated to Angular 6 and tried to run my app with AOT compilation but got the following error:
```
@angular/compiler and @angular/compiler-cli must be installed for AOT compilation!
AOT compilation disabled!
```
both packages are installed, I also tried to remove node_module and reinstall it. Is there a known issue with angular 6?

**Comment by ardatan** [comment]
No, there is not. You can see the code below. If you have installed those dependencies properly, that warning won't show up.
https://github.com/Urigo/angular-meteor/blob/433d772777a1a242db07605f77459547b9d63186/atmosphere-packages/angular-compilers/plugin/register.js#L24

**Comment by weini01** [comment]
Hi it now works! I had to reinstall the two packages separate. Simple removing node_modules and npm install did not do the job. @ardatan thanks for your engagement at the whole angular-meteor project.
