### ISSUE TITLE
Angular 1.x autorun bug

### ISSUE THREAD

**Issue by sebakerckhof** [Urigo/angular-meteor#1935]
At the end of an autorun there's a `throttledDigest`. However, this seems to be not sufficient.
Because sometimes it thinks it's not digestable, but not all watchers get updated.

Reproduction:
https://github.com/sebakerckhof/angular-meteor-bug

I don't know exactly why that is, but a workaround might be to wrap the whole autorun in an $evalAsync ?

**Comment by ardatan** [comment]
The old packages have been deprecated, you need to update your code using this example;
https://github.com/Urigo/angular-meteor/tree/master/examples/angularjs

**Comment by sebakerckhof** [comment]
@ardatan I am using the same code (the non-deprecated stuff).

What I mean is, that at the end of an autorun we do a $digest on the scope (well, if there's not one already ongoing). But I think this should be an apply or evalasync, since it might trigger stuff in parent components to change. But the $digest only checks current scope and down.

**Comment by ardatan** [comment]
Please let me know if it doesn't work after you change your code.
