### ISSUE TITLE
Core.js not found, but it's actually there in node modules.  Meteor client is fine. Ionic is broken.

### ISSUE THREAD

**Issue by dc165015** [Urigo/angular-meteor#1941]
The errors occurs when importing the meteor-client.js.  When loading ecmascript-runtime-client, it suggested: The core-js npm package could not  be found in your node_modules directory.  Please run the following command to install it: meteor npm install --save core-js. 
Actually, I did install it on both meteor's node_modules and ionic's node_modules.I launched the meteor client, it is fine. While in ionic, the compile process goes well, but with the error displayed in the browser.  I was stuck there for 3 days, I deep dived into src. I am still not sure whether it came from webpack or meteor-client-bundler or anything else.   I surfed and found no any answer in online resources. 

The error stack: 
Error: Cannot find module 'core-js/modules/es7.object.get-own-property-descriptors'
    at makeMissingError (http://localhost:8100/build/vendor.js:125256:14)
    at Module.require (http://localhost:8100/build/vendor.js:125275:19)
    at _require (http://localhost:8100/build/vendor.js:125291:25)
    at modern.js (http://localhost:8100/build/vendor.js:128255:15)
    at fileEvaluate (http://localhost:8100/build/vendor.js:125369:9)
    at Module.require (http://localhost:8100/build/vendor.js:125272:16)
    at _require (http://localhost:8100/build/vendor.js:125291:25)
    at http://localhost:8100/build/vendor.js:128275:18
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:128279:3)
    at Object.defineProperty.value (http://localhost:8100/build/vendor.js:214805:30)

**Comment by ardatan** [comment]
Could you reproduce a repo?

**Comment by dc165015** [comment]
I made this repo:  https://github.com/dc165015/issue
Thanks a lot!

**Comment by ardatan** [comment]
The repo looks empty, could you check?

**Comment by dc165015** [comment]
I tried either to make a node_modules dir for api or link the node_modules dir of project root folder. Both sucks.

**Comment by dc165015** [comment]
any idea? did you reproduce the error?

**Comment by ardatan** [comment]
You must have a node_modules symlink in your Meteor project folder. That's the problem.

**Comment by jimenezff** [comment]
@dc165015 I had the same issue. I'm using Ionic 4, Angular 6 and Meteor 1.7. I have a node_modules symlink and I installed core-js in it. That didn't work. 

I finally was able to fix it by adding `"npmPackages": [
  	"core-js",
  	"@babel/runtime@7.0.0-beta.55"
  ]` to meteor-client.config.json

After adding "core-js" I got another error which I fixed by adding "@babel/runtime@7.0.0-beta.55"

I also have this `"generateNodeModules": true` in case that makes a difference.

I don't know if this is the best way to fix it but it's working for me and it doesn't seem like a crazy hack workaround.

**Comment by dc165015** [comment]
@jimenezff  THANK YOU VERY MUCH! You saved my days ...

**Comment by jimenezff** [comment]
@dc165015 I'm glad I was able to help :)  
Now I have to figure out why my build fails when I add `"@types/meteor"` to tsconfig.json
I get a bunch of `[ng] node_modules/@types/meteor/mongo.d.ts(344,9): error TS1005: ',' expected.`

**Comment by dc165015** [comment]
I bumped into this error ever. This is caused by the mess when you mix " meteor npm install " and " npm install".
I found 1 difference is they have different version. I can tell the other differences for there is no detailed doc. 
You have to either use meteor npm install or use npm install  to avoid the inconsistence. 

To fix this, you may remove node_modules and package-lock.json, then try again.

**Comment by dc165015** [comment]
@KeithGillette  this meteor-client-bundler is a black-box, no detailed doc and very tricky. It did trap me days and days...

**Comment by theosp** [comment]
Please note, core-js v3.x is not compatible anymore with meteor here: https://github.com/meteor/meteor/blob/3051150f2f5ae953f391802e73682fba613b3d46/packages/ecmascript-runtime-client/modern.js

You need to install v2.6.5.

I updated my package.json to:

  "core-js": "~2.6.5"

All works after that.

**Comment by pubkey** [comment]
I had the same problem also with the proposed fixes.
I could solve it by upgrading the project to meteor 1.8

You can do this by running the following command in [this folder](https://github.com/Urigo/angular-meteor/tree/master/examples/AngularCLI/api):

```bash
meteor update --release 1.8
```
