### ISSUE TITLE
[examples/AngularCLI]: "cannot find" messages as building the api server but it runs fine

### ISSUE THREAD

**Issue by atao60** [Urigo/angular-meteor#1948]
- [x] A descriptive title
- [x] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [x] What version of `angular-meteor` you're using, and the platform(s) you're running it on
- [x] What packages or other dependencies you're using
- [x] The behavior you expect to see, and the actual behavior

See demo on github: https://github.com/atao60/angular-meteor-example-AngularCLI

The installation is described in detail in the file [HISTORY](https://github.com/atao60/angular-meteor-example-AngularCLI/blob/master/HISTORY.md)

Pre-condition, main points:
* cloning [angular-meteor/examples/AngularCLI](https://github.com/Urigo/angular-meteor/tree/master/examples/AngularCLI)
* using meteor@1.7.0.4 and @babel/runtime@7.0.0-beta.55, see [issue #1946](https://github.com/Urigo/angular-meteor/issues/1946) and [issue #10128](https://github.com/meteor/meteor/issues/10128)
 
During the build of the api server (Meteor), error messages are thrown for any node or meteor global reférences, eg:
```
server/fixtures/data.fixture.ts (1, 16): Cannot find module 'fs'.
server/fixtures/data.fixture.ts (2, 11): Cannot find name 'Assets'.
```
But everything runs fine...

I haven't find any workaround to avoid those messages.

**Comment by ardatan** [comment]
They are related to `@types/meteor` package, and probably fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28064
It is not directly related to `angular-meteor`.

**Comment by atao60** [comment]
> They are related to @types/meteor

Even for 'fs' and other modules provided by node?

**Comment by atao60** [comment]
Both packages @types/node and @types/meteor are referenced in package.json.

So it's quite strange that references to Meteor's Assets or any of the node's modules (fs, console, path, ...) will generate a message 'cannot find' during the Meteor phase "TypeScript Files Compilation".
