### ISSUE TITLE
Building Karma Unit tests for use in app using meteor-client.

### ISSUE THREAD

**Issue by Slavrix** [Urigo/angular-meteor#1952]
When building an ionic web app and connecting to meteor via the meteor-client package, How can we write standalone unit tests as `import {Meteor} from 'meteor/meteor'` does fails with undefined.

If I do `declare let Meteor` I can get past the import failing, but then the Meteor methods are still unavailable as it isn't imported it seems.

Is there an advised way to mock the default meteor behaviours?

**Comment by ardatan** [comment]
Try using generateNodeModules option for meteor client bundler. This will generate sub modules for Meteor packages, so this may solve your issue
