### ISSUE TITLE
Error after adding ui-router package

### ISSUE THREAD

**Issue by digioak** [Urigo/angular-meteor#196]
Following the tutorial and saw in console:

Uncaught Error: Unknown provider: $compileProvider from angular-meteor.template

Strange that ui-router package depends on an older version of angular:

angularjs:angular            added, version 1.0.8
angularui:angular-ui-router  added, version 0.2.13_3

Also a warning that angular is being loaded twice.

**Comment by Urigo** [comment]
Yes you are right, it is fixed in the new angular-meteor package which I haven't release yet.
Later today I will release the beta version and then it should work

**Comment by fmachucas** [comment]
Hi, if you can't wait, use angularui:angular-ui-router@=0.2.13_2, it work's for me.

**Comment by Urigo** [comment]
Fixed on the new 0.7.0 release
