### ISSUE TITLE
Using angular-meteor with Meteor 1.8.2

### ISSUE THREAD

**Issue by Slavrix** [Urigo/angular-meteor#1971]
when trying to use this package along side meteor 1.8.2 and its new official typescript package, a message comes up saying 

> => Errors prevented startup:
> 
>    While determining active plugins:
>    error: conflict: two packages included in the app (angular-compilers and typescript) are both trying to handle *.ts
>    error: conflict: two packages included in the app (angular-compilers and typescript) are both trying to handle *.tsx

If I remove the official typescript package, then it still seems to work fine.
But since there is now official handling for typescript, is that something that should be looked at?

**Comment by ardatan** [comment]
`angular-compilers` has typescript compiler with AOT Compilation of Angular, html compiler for Angular to be used in `templateUrl` and scss compiler to be used in `styleUrls`. 
Besides that, `typescript` package doesn't support Angular's DI due to the lack of decorators and metadata reflection support.

**Comment by bouchepat** [comment]
I've been able to upgrade our app to Meteor 1.8.2 (from 1.8.1) and Angular to latest 8.2.14 (from 5.0.2). It took me a little while to convert to rxjs v6 and new syntax for lazy loaded routes. (Meteor CLI).

App is running fine in development, but the build process flags the new lazy loaded routing syntax:
 `{
                path: 'tests',
                loadChildren: () => import('../app/tester/tests.module').then(m => m.TestsModule),
                canActivateChild: [MetaGuard]
}`

 An error is triggered for each lazy loaded routes:

`
C:/Users/xxx/Documents/Repositories/app/imports/client/init/app-routing.module.ngfactory.ts (100, 37): Property 
'ɵ43' does not exist on type 'typeof "C:/Users/xxx/Documents/Repositories/app/imports/client/init/app-routing.module"'.
`

e43 seems to be counter for the defined route, e.g.: a module with 46 lazy loaded routes then each route would have e0, ...., e45 with same type of error.

I'm assuming the `angular-compiler` need an upgrade? or any other ideas?

Thanks

**Comment by simontbates** [comment]
@bouchepat -  can you give some detail behind how you managed to upgrade to Meteor 1.8.2, whilst still keeping AOT compilation?
