### ISSUE TITLE
Service Api Interface

### ISSUE THREAD

**Issue by ndevr** [Urigo/angular-meteor#199]
Hey Uri,

would be great if we can attach our own services with an simple api interface to the meteor service.

Example 1:

attaching services: $meteorProvider.attach('collection', $collectionFS); // key, value
accessing: $meteor.collection('MyCollection');

Example2:
attaching services $meteor.collection = $collectionFSFactory;

What do you think?

**Comment by Urigo** [comment]
I don't understand it so much..
why override the current behaviour?  (you can do that anyway with Angular without the library support)

You can also add functions to a service (also in Angular without the library support)

**Comment by Urigo** [comment]
Closing for now, if you still think it's good let's continue talking about it
