### ISSUE TITLE
Namespace clash with angular-meteor '$' services and other Angular modules

### ISSUE THREAD

**Issue by rjsmith** [Urigo/angular-meteor#20]
I am concerned that the services provided by angular-meteor ($collections, $users, $methods) may name - clash with core Angular services, either now or in the future.

I think AngularJS core team [recommend that 3rd parties do not use $](https://docs.angularjs.org/tutorial/step_05) (see the $ Prefix Naming Convention section) ?

How about `$meteor` as an alternative prefix? (e.g. `$collections` becomes `$meteorCollections`) ?  That is how the AngularFire library handles this (`$firebase` and `$firebaseSimpleLogin`)

**Comment by Urigo** [comment]
Guys, I listen and now in the new version all of the services are prefixed to $meteor:
https://github.com/Urigo/angular-meteor/releases/tag/0.6.0-alpha

**Comment by rjsmith** [comment]
great - well done on the v0.6.0 release ... looks awesome
