### ISSUE TITLE
tutorial videos somewhat out of sync with API

### ISSUE THREAD

**Issue by okosokolovo** [Urigo/angular-meteor#201]
Thank You for the angular-meteor project. I am following the tutorial, which is very helpful, but apart of the latest improvements in the text version (e.g. templating, API modifications), it is somewhat confusing to watch the video content which is demonstrating deprecated API (e.g. $collection) and other templating technique. At least it should be noted in some way at appropriate places (by the videos on YT and/or in the tutorial).
Otherwise, thanks for inspiring efforts and congratulations in participating at the ng-conf, wish you good luck.

**Comment by Urigo** [comment]
@okosokolovo thank you so much.
This weekend I'm going to start updating the videos, at least the first ones so that we will have at least a few updated before ng-conf.

Thank you so much for the feedback
