### ISSUE TITLE
'Improve this doc' link on step 15 of tutorial points to wrong file

### ISSUE THREAD

**Issue by digioak** [Urigo/angular-meteor#203]
https://github.com/Urigo/angular-meteor/edit/master/.docs/angular-meteor/client/views/steps/tutorial.step_15.html

it's actually .tpl?

Sorry, not sure where to do a pull request for this one...

**Comment by Urigo** [comment]
Thanks!

For next time, the docs site in a angular-meteor application running from .docs/angular-meteor/
