### ISSUE TITLE
Template files are confusing

### ISSUE THREAD

**Issue by RichardLitt** [Urigo/angular-meteor#206]
Looking through them, there's a lot of html mixed in with js, and I don't really grok how you separate out text from formatting. Also, there are .html and .tpl templates, and I'm not sure why there's a difference. Is there a better way of doing this?

**Comment by Urigo** [comment]
You are talking about the website......

**Comment by RichardLitt** [comment]
I'm talking about this: https://github.com/Urigo/angular-meteor/tree/master/.docs/angular-meteor/client/views/steps

That's in this repo, no?

**Comment by Urigo** [comment]
that's the code for the http://angularjs.meteor.com/ site.
There stuff are a bit different because I need to use both Markdown and HTML for angular and Meteor.

I've also haven't updated the site to the new angular-meteor yet.

But it works...

**Comment by RichardLitt** [comment]
It works, but I think it might be a barrier to having people improve the docs.

**Comment by Urigo** [comment]
yes I have a task to update that.

But first - update videos...
