### ISSUE TITLE
browser-policy 'unsafe-eval'

### ISSUE THREAD

**Issue by srtucker22** [Urigo/angular-meteor#207]
As far as I can tell, unless you state in the server that you'll allow evals to run on the client -- 

<code>BrowserPolicy.content.allowEval()</code>

you'll get an error from angular-meteor like so:

Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'

But I don't want to allow evals on my client if I can help it! ng-csp didn't seem to make a difference. Maybe it's because it's not on the html tag? IDK. I'm pretty new to this XSS security stuff.

Any help appreciated!

**Comment by Urigo** [comment]
Can you share more information?
maybe a reproduction so it will be easier for me to understand?

thanks

**Comment by Urigo** [comment]
@srtucker22 are you trying maybe to add a <script> tag for some reason?  Meteor doesn't support that

**Comment by srtucker22** [comment]
So I'm using the <a href="https://atmospherejs.com/meteor/browser-policy">browser-policy</a> package.

I've created a barebones example app <a href="https://github.com/srtucker22/test-browser-policy-angular">here</a>

I'm guessing the error has to do with this default policy in the browser policy package -- <code>BrowserPolicy.content.disallowEval()</code>

As the documentation explains: "your app's client code will not be able to use functions such as eval() that convert strings to code. Users' browsers will only let your app be framed by web pages on the same origin as your app."

This makes sense because I wouldn't want a user to inject some malicious XSS in a post for example. It might look something like this: 
<code>a href="javascript: eval(String.fromCharCode(77, 101, ...))"> {{ username }}'s website</code>
when evaluated could do whatever the malicious user wanted like get a victim's local storage.

Emily Stark from the Core team talks about browser-policy <a href="https://www.youtube.com/watch?v=79uMp-S23MA">here</a> and the slides are <a href="http://www.slideshare.net/emilystark/meteor-meets-mallory">here</a>

Thanks for looking into this!

**Comment by Urigo** [comment]
@srtucker22 that's good point and should be documented.
As I understand, Meteor thinks Angular's evals are breaking the policy. 
Looking at your code, the error goes to an Angular.js internal code that checks if csp is active by actually running a code that breaks that and catches that:
![screen shot 2015-03-19 at 4 53 13 pm](https://cloud.githubusercontent.com/assets/1297448/6733106/a54d4196-ce58-11e4-9e18-ffc7be3dd15d.png)

You should let Angular handle the CSP now because it's your front end and Meteor doesn't know what Angular does.  so I think you should allow eval in Meteor and then use Angular to verify with [ngCsp](https://docs.angularjs.org/api/ng/directive/ngCsp).
adding @asafdav to the conversion to verify.

**Comment by Urigo** [comment]
Closing for now, but still waiting for your confirmation

**Comment by srtucker22** [comment]
Makes sense. Thanks for looking into this!

**Comment by asafdav** [comment]
Hi guys, I don't think Angular's $eval could be the reason for this specific error message. $eval doesn't evaluate js at all, but instead it evaluates AngularJS expressions, that's is exactly why $eval exists.

**Comment by Urigo** [comment]
Yes, we are not saying that is the cause, we are saying Angular's check if it's active is the cause.
and also we think letting Angular alone handling eval with ngCsp is enough and there is no need for Meteor to do that as well, do you agree?

**Comment by asafdav** [comment]
Hi, It might good enough to use Angular CSP but you need to compare Meteor's solution to Angular's in order to make sure. [mustache-security](https://code.google.com/p/mustache-security/wiki/AngularJS) is a great reference to start from. 

It could also be a smart idea to open an issue to Angular.

**Comment by Urigo** [comment]
@srtucker22 I think there is no reason we couldn't use both - as Asaf said, maybe you can open an issue in Angular so they will change the way they check if it's active to a different way and then there will be no problem to use both for extra security (in case Meteor covers things that Angular doesn't)

**Comment by tomachinz** [comment]
Potentially would using BrowserPolicy.content.allowEval('self'); be an improvement? Does that only allow me to do Eval()?
