### ISSUE TITLE
using mquandalle:bower with angular modules leads to WARNING: Tried to load angular more than once

### ISSUE THREAD

**Issue by srtucker22** [Urigo/angular-meteor#211]
Even after changing all .tpl to .ng.html, I was still getting 
WARNING: Tried to load angular more than once. 

I narrowed down the problem to using the bower package for meteor. Don't know if there's a good fix for this or if I'm missing something obvious. Seems like the modules (e.g. ui.boostrap) are loading the bower dependencies, including angular.

**Comment by Urigo** [comment]
Yes, meteor-bower is a problem and as a decision we are not supporting that anymore.

There are a few workaround that will fix your problem, but I think It is best to create a Meteor package of your desired library.
Here there is more information about both a workaround and both about creating a package:
https://github.com/Urigo/angular-meteor/issues/205#issuecomment-76543479
