### ISSUE TITLE
angular bootstrap issue

### ISSUE THREAD

**Issue by mlim1972** [Urigo/angular-meteor#213]
Starting looking at this project and find it very interesting...  I know angular and wanted to start with Meteor using the project.  Tried to follow both the video and the tutorial but I'm not able to pass the angular check with either the ng-include or the [[1+1]] after "meteor add urigo:angular".  The ng-include don't show neither the 1+1 result.  I see angular and the index.ng.html are getting added to the index.html when I see the page source.  Any help is appreciated.

**Comment by Urigo** [comment]
@mlim1972 sorry but the videos are out of date, planning to fix that this week.

Please follow the tutorial's text

**Comment by mlim1972** [comment]
I followed the text tutorial as well...   ng-include doesn't seem to be working either even though I see it in the page source.

**Comment by Urigo** [comment]
looks like a spelling mistake or something like that.

Check the source code and compare...

**Comment by mlim1972** [comment]
Things are ok once I add the app.js and the ng-app.  but the verification of angular from the tutorial doesn't seem to be correct.  Anyway, thanks I have it going after adding the ng-app and app.js...  Will wait for the new videos...  I like the project, keep it up!

**Comment by Urigo** [comment]
thanks!

Yes we changed that so that we can use regular delimiters.

I think the first step reflects that change:
http://angularjs.meteor.com/tutorial/step_00
