### ISSUE TITLE
Meteor.users instanceof Mongo.Collection === false

### ISSUE THREAD

**Issue by tehXor** [Urigo/angular-meteor#214]
We just updated our Meteor app to 1.0.3.2 and angular-meteor to 0.7.1 in our test environment. And it looks like Meteor changed some things with the Meteor.users collection. All our client side views where we added this collection to the scope (in one way or the other) fail with the exception

`TypeError: The first argument of $meteorCollection must be a function or a Mongo.Collection.`

From our first test it looks like something changed in Meteor (also it seems illogical and therefore we are not sure if we have some specific problem with our installation) as in our production environment (which isn't updated and still is running Meteor 1.0.3.1 and angular-meteor 0.6.7)
`Meteor.users instanceof Mongo.Collection` returns `true` as expected. However in the test environment the same statement returns `false` also the the Meteor.users object looks the same at first glance. 
Working with Meteor.users in the test environment outside of angular-meteor works like before and all other "custom" collections also work like before in and outside of angular-meteor (so `ourCustomCollection instanceof Mongo.Collection` still returns `true` for example).

Any ideas what could have happened?
Thanks for any tipps...

**Comment by Urigo** [comment]
Yes looks like the package we are using the get collection by name had this problem and solved it in a new release:
https://github.com/dburles/mongo-collection-instances/pull/14

Will update the dependency later today

**Comment by tehXor** [comment]
You are scaring me with such fast replys :P
But thanks a lot; for the reply and the incoming update!
