### ISSUE TITLE
WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by xiulunlin** [Urigo/angular-meteor#217]
I just update from 0.6 to 0.7 and I get this problem on console . What's going on ?

**Comment by artitw** [comment]
I also got the same problem. How did you solve it?

**Comment by xiulunlin** [comment]
@artitw I do not use bower.json to load ui-router any more , instead I use meteor add angularui:angular-ui-router . And check the ./.meteor/packages to make sure that you are actually using 0.7 .
