### ISSUE TITLE
Android scrolling problem

### ISSUE THREAD

**Issue by scresawn** [Urigo/angular-meteor#218]
Hi,

My app uses urigo:angular and urigo:ionic.  After running meteor update and getting updates to both these packages, I have a problem with scrolling on Android.  (Scrolling is fine on iOS and on desktop browsers.)

I have an &lt;ion-content scroll="true" overflow-scroll="true">

If I try to scroll, it doesn't work, and I get this in the terminal:

I20150303-21:30:53.988(-5) (android:http://meteor.local/packages/urigo_ionic.js:9863) Uncaught TypeError: Cannot call method 'freeze' of null

However, if I try to scroll on the far right edge of the screen (where the hidden scrollbar would be), the scrolling does work!  I have a temporary fix of using overflow-scroll="false" but this is really slow on Android.

I'm sorry if I posted this in the wrong place:  Maybe it's a meteor-ionic problem or just something wrong in Ionic itself?

Thank you!

**Comment by Urigo** [comment]
I don't know.
The way to check that is just running Ionic by itself without angular-meteor and see if it works there.
I'm closing it until you test that and will re-open if it does work there

Thanks
