### ISSUE TITLE
iron router problem

### ISSUE THREAD

**Issue by berkaey** [Urigo/angular-meteor#221]
```
Router.configure
	layoutTemplate: 'layout'
	loadingTemplate: 'loading'
	notFoundTemplate: 'notFound'

if Meteor.isClient
	Router.route '/', () ->
		this.render 'hello'	

```

```
template(name="layout")
	.viewport(ng-app="myapp" ng-controller="main")
		+yield
```
when I use like this angular won't bind at all, how can I solve this any idea?

btw  if I use as described like it works.

**Comment by berkaey** [comment]
```
	Router.onAfterAction (req, res, next) ->
		Tracker.afterFlush ->
			angular.element(document).ready () ->
				unless angular.element(document).injector()
					angular.bootstrap(document, [slug])
```
I fixed my own problem and leave it here so anyone can use.

Basically; onAfterAction event document won't be ready immediately if you decide to add app to your basic layout like above you need to add this code too. I don't know maybe this can be added to angular-meteor but Im not fully tested.

**Comment by Urigo** [comment]
@berkaey looks like a nice solution.
I've just merged this pull request - https://github.com/Urigo/angular-meteor/pull/220 , this it the code you need to edit.
