### ISSUE TITLE
collection refreshed when object is saved

### ISSUE THREAD

**Issue by epotvin** [Urigo/angular-meteor#222]
This is a controller I actually use in my application. I manage photos by categories. Each photo has a categoryId.

Within a category, each photo has an index allowing them to be sorted in the list. When I move down a photo, its index is replaced by the next one. This is done by a call to the moveDown method. I also have a moveUp method but I keep just necessary code for the post.

Actually, it works. The index are changed, saved to the database and the list is updated automatically (I use a sort filter on the ng-repeat directive). The thing is, when it's saved, the $scope.photos collection is refreshed, making the browser to scroll back to the top of the page when I have many photos.

I tried to reproduce it with a simpler application, but it always work fine... the problem is just with this app. Do you know what could causes that?

```javascript
angular.module("nicosim").controller("AdminCategoryController", ['$scope', '$stateParams', '$meteor',
    function ($scope, $stateParams, $meteor) {

        $meteor.subscribe("categories").then(function (subscriptionHandle) {
            var category = Categories.findOne({name: $stateParams.category});
            $scope.category = $meteor.object(Categories, category._id, false);
        });

        $scope.$watch('category', function(category) {
            if (category) {
                $scope.photos = $meteor.collection(function() {
                    return Photos.find({categoryId: category._id});
                }, false);
            }
        });

        $scope.moveDown = function (photo) {
            var index = photo.index;
            $scope.photos.forEach(function (photo) {
                if (photo.index == index + 1) {
                    photo.index = index;
                    $scope.photos.save(photo);
                }
            });
            photo.index = index + 1;
            $scope.photos.save(photo);
        };

    }]);
```

**Comment by netanelgilad** [comment]
Any chance you are using the autopublish package and publishing the whole photos collection that way? (since I don't see where you are subscribing to the photos..).
I have seen this issue happen when using autopublish so that would be my first guess.
If it's not that, try debugging or logging that watch on category function. Is it by any change getting called every time you move down a photo?

**Comment by epotvin** [comment]
No I'm not using autopublish, but I publish them all with :
```javascript
Meteor.publish('photos', function() {
    return Photos.find();
});
````
And I subscribe them in a run() function of my module with :
```javascript
        Meteor.subscribe('photos');
```
I already checked the category $watch function, and no it's not called. 

As my investigation goes, I can tell that an abnormal thing that is happening here is a call to the stop() function the AngularMeteorCollection object. I put a breakpoint in it and this is the stack I have :

AngularMeteorCollection.stop (angular-meteor-…lection.js:210)
(anonymous function) (angular-meteor-…lection.js:282)
(anonymous function) (tracker.js:234)
Tracker.nonreactive (tracker.js:480)
Tracker.Computation.invalidate (tracker.js:233)
Tracker.Dependency.changed (tracker.js:354)
(anonymous function) (minimongo.js:379)
_.extend.runTask (fiber_stubs_client.js:42)
_.extend.flush (fiber_stubs_client.js:70)
_.extend.drain (fiber_stubs_client.js:78)
LocalCollection.update (minimongo.js:737)
Mongo.Collection._defineMutationMethods._.each.m.(anonymous function) (collection.js:828)
(anonymous function) (livedata_connection.js:774)
_.extend.withValue (dynamics_browser.js:23)
_.extend.apply (livedata_connection.js:765)
_.each.Mongo.Collection.(anonymous function) (collection.js:563)
upsertObject (angular-meteor-…llection.js:52)
save (angular-meteor-…llection.js:81)
(anonymous function) (photos.js?e6612…7d24b636e35:76)

As you can see, it starts with the call to the save function in my controller (in photos.js) and reach the stop function through a path I'm still investigation, comparing it with a simple app which behave correctly. I didn't find anything so far...

Emmanuel

**Comment by epotvin** [comment]
Got it! I was just using an old version of meteor-angular... 0.7.0... Everything is fine now.

Thanks for the help!

Emmanuel

**Comment by Urigo** [comment]
Great, closing
