### ISSUE TITLE
WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by artitw** [Urigo/angular-meteor#223]
After updating I received the following error on the client. It looks like from `meteor list` that `angularjs:angular@1.3.14` was added. Does anyone know how to solve the problem? Thanks!

````
WARNING: Tried to load angular more than once.
angularjs_angular.js:11637 Error: [ng:btstrpd] App Already Bootstrapped with this Element 'document'
http://errors.angularjs.org/1.3.14/ng/btstrpd?p0=document
    at http://localhost:3000/packages/angularjs_angular.js?cd6b2d01f519ab80a987d88280d8bede8e8da8c1:93:14
    at doBootstrap (http://localhost:3000/packages/angularjs_angular.js?cd6b2d01f519ab80a987d88280d8bede8e8da8c1:1456:15)
    at Object.bootstrap (http://localhost:3000/packages/angularjs_angular.js?cd6b2d01f519ab80a987d88280d8bede8e8da8c1:1496:14)
    at HTMLDocument.onReady (eval at <anonymous> (http://localhost:3000/packages/jquery.js?dd8bac56f8fd3666d433d2285ae01e52597cc51a:372:22), <anonymous>:4:11)
    at fire (http://localhost:3000/packages/jquery.js?dd8bac56f8fd3666d433d2285ae01e52597cc51a:3176:30)
    at Object.self.add [as done] (http://localhost:3000/packages/jquery.js?dd8bac56f8fd3666d433d2285ae01e52597cc51a:3222:7)
    at jQuery.fn.ready (http://localhost:3000/packages/jquery.js?dd8bac56f8fd3666d433d2285ae01e52597cc51a:3456:25)
    at eval (eval at <anonymous> (http://localhost:3000/packages/jquery.js?dd8bac56f8fd3666d433d2285ae01e52597cc51a:372:22), <anonymous>:10:29)
    at eval (eval at <anonymous> (http://localhost:3000/packages/jquery.js?dd8bac56f8fd3666d433d2285ae01e52597cc51a:372:22), <anonymous>:12:3)
    at eval (native)angularjs_angular.js:11637 (anonymous function)
````

**Comment by Urigo** [comment]
1. Are you using meteor-bower?
2. Are all your template files ends with .ng.html instead of .tpl?

**Comment by andresberrios** [comment]
Hi! I'm having the same problem. I am using meteor-bower, and I changed my template files from .tpl to .ng.html except for my index.html file where I have the `ng-app="..."` attribute.
Any ideas to fix this?

**Comment by Urigo** [comment]
Yes, please look at this thread for the solution - https://github.com/Urigo/angular-meteor/issues/205
we decided not to support meteor-bower as the library is not solid enough and doesn't have to version solver the Meteor packing system has.

**Comment by artitw** [comment]
1. I'm not using bower, at least not that I can tell. In fact, it looks like updating from 0.6 to 0.7 removed bower.
2. I have renamed the files to .ng.html, but the error persists. 

With the above stated, should I be doing some sort of work around like your reference #205?

**Comment by Urigo** [comment]
@artitw can you share a reproduction?

**Comment by artitw** [comment]
Actually, I forgot to change to .ng.html in my router code. It's working
now. Thanks!

**Comment by Urigo** [comment]
Great!

**Comment by sclausen** [comment]
Had the same error with a different dumb thing I fogot. Would it be possible to make the error message a bit more helpful?

**Comment by JNissi** [comment]
It's super easy to trip on this with the most basic project: Start a new project, create `client/index.html`, `client/index.ng.html`, `client/main.ng.js`and try to include the index template: `<div ng-include="'index.ng.html'"></div>`. Kaboom! 

It seems you need to use the full path for ng-include: `<div ng-include="'client/index.ng.html'"></div>`

**Comment by sclausen** [comment]
JNissi, that's right, but I think the problem is not, that it needs the full path, but that the error message is so uninformative.

**Comment by castlefields** [comment]
@sclausen Agreed the error message is misleading as my error came on Part 07 of the Tutorial. 

Moving the routes.js I forgot to update the first route, as the template path had now changed from root to client/parties/views/... 

Changing this removed the unhelpful error of WARNING: Tried to load angular more than once.

**Comment by netanelgilad** [comment]
I agree with all of you here.
The first problem with needing the full path to the template file is because we put the templates into the templateCache with the full path, so it has to be referenced exactly like that to work. That is how templateCache works. I think that is documented somewhere in the site/tutorial as that issue came up in the past.
About the unhelpful message, that is the message that Angular writes when it sees that window.angular.bootstrap is already defined, and that happens because when you route to an incorrect path Meteor returns the index file which has angular in it again, causing the message.
What we could do, is add a check ourselves for the case that angular is defined twice and add more helpful messages about wrong routes and such. But i'm not sure if that is an overkill..
everybody, @Urigo thoughts?

**Comment by castlefields** [comment]
@netanelgilad On making the mistake and learning from it, hopefully in the future it will be on my radar to check the templateUrl. Also the error arose out of me cutting and pasting along with the Tutorial - I think if I was actually coding, then as @JNissi mentioned, I would of entered the correct path. 

My concern would be that noobs to angular-meteor, of which I am one, will dismiss this fantastic project out of hand due to the usual generic console messages. 

Adding to the tutorial:-

.state('parties', {
        url: '/parties',
        templateUrl: 'client/parties/views/parties-list.ng.html',
        controller: 'PartiesListCtrl'
      })

above the .state('partyDetails'... would be beneficial.

Maybe a section within the MD could detail 'Common Issues Solved' whereby we could all contribute - just an idea...

BTW: Angular-Meteor - Fantastic !!

**Comment by Urigo** [comment]
@castlefields that's a great idea.
Do you mind pull requesting and writing it yourself?
this way you will get the credit and also I believe as the one who encountered this, you will best explain this issue:
https://github.com/Urigo/angular-meteor/edit/master/.docs/angular-meteor/client/views/steps/tutorial.step_05.tpl

**Comment by richarddewit** [comment]
@JNissi - thanks that fixed it for me!

**Comment by scrapcupcake** [comment]
So, it sounds to me like this could most profitably be solved by just fixing the behavior of the server that meteor runs when you start it up; 404s should 404. Then angular will return the correct (or at least a much MORE correct) error when you've specified an incorrect templateUrl, rather than this very surprising (read: awful, very bad, no good user experience) behavior.

**Comment by abcd-ca** [comment]
saw in the official angular package changelog that we could now ditch `.ng.html` in favour of simply, `.html`. At first I was getting the error, "Tried to load angular more than once.". Like artitw, I had forgotten to rename my template paths to match the new name change. This fixed it, not obvious but might help someone so I'm mentioning it.

**Comment by Urigo** [comment]
http://info.meteor.com/blog/angular-meteor-1.2.0

**Comment by Tallyb** [comment]
I did not try it but .ng.html should be a valid file name for any build process, doesn't it?

**Comment by abcd-ca** [comment]
@Tallyb I didn't mean to confuse the issue but .ng.html should work fine, it's just no longer necessary to distinguish between angular and blaze templates.

**Comment by El4a** [comment]
We just searched for a solution for over an hour, in my situation :
1) it wasn't bower related
2) the route path was correct
3) I did not forget .html or had no typos
4) adding .ng didn't help

The issue was that the views weren't wrapped in a div. So changing : 
<p> My content </p>

to : 

<div>
<p>My content <:p>
</div>

completely solved everything. Is this Angular's intention or a bug? Afterall, using ui-.router, the views are already wrapped in  <div ui-view></div> .

Hope someone can offer an explanation for this behaviour! =)

**Comment by kunalkamble** [comment]
@Urigo I am having issue with angular meteor app, I am just following steps from your demo socially app.
`WARNING: Tried to load angular more than once.`
I am not sure whats going on, after adding `ui.router` it started happening.

**Comment by stevenlivz** [comment]
I also get this on a brand new Meteor + Meteor-Ionic app (using code that was working fine before). Tried upgrading an existing code base as well as creating a new one.

If I do not call my file .ng then it tries to load angular twice and also the message "only one instance of babel/polyfill is allowed" appears. Using .ng files fixes it immediately. Everything is at their latest versions and I have followed all the latest instructions.

**Comment by kunalkamble** [comment]
@stevenlivz I had same issue with my angular-meteor app,
could you please share `.meteor/packages` file content?
for me it was lodash library, it was injecting angular.

**Comment by stevenlivz** [comment]
@kunalkamble Yep. Here it is. I added bower as well but I was getting this issue before that. Still getting it but changing to x.ng.y makes it work ok.

# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.

autopublish             # Publish all data to the clients (for prototyping)
insecure                # Allow all DB writes from clients (for prototyping)
angular
driftyco:ionic
ground:localstorage
mquandalle:bower        # allow bower packages to be used (e.g. angular)

**Comment by jeff10278** [comment]
@El4a: You are correct, not wrapping in div is the cause of this error.. Anyone have a clue why that is?

**Comment by hazboun** [comment]
I faced the same and while debugging I noticed that the injection to $templateCache used old paths even after moving the files! 

***/.meteor/local/build/programs/web.browser/app/client/parties/views/template.parties-list.js***
```javascript
(function(){angular.module('angular-meteor').run(['$templateCache', function($templateCache) { $templateCache.put('client/parties-list.html',"<form> <label>Party name: </label> <input type=\"text\" ng-model=\"newParty.name\"> <button ng-click=\"Parties.save(newParty); newParty='';\">Add</button> </form> <ul> <li ng-repeat=\"party in Parties\"> <a href=\"/parties/{{party._id}}\">{{party.name}}</a> <button ng-click=\"remove(party)\">x</button> </li> </ul> <button ng-click=\"removeAll()\">Remove All</button>");}]);
}).call(this);
```

Isn't suppose to re-inject/re-build? am I missing something here?

**Comment by hazboun** [comment]
I see my issue also reported here [#888] (https://github.com/Urigo/angular-meteor/issues/888)

**Comment by wormyy** [comment]
I have just spent a good amount of time on this. Simple `meteor reset` solved the problem. Probably some cache issues.

**Comment by luisreyes** [comment]
I had a one character typo in the ng-include path... which after correcting fixed my issue.

**Comment by Urigo** [comment]
I think that in the new [1.3 release](http://info.meteor.com/blog/angular-meteor-1.3) you should get a better error message of typos in paths.
It it working for you?

**Comment by ftcosta** [comment]
Check the obvious scenarios first.

```html
<script src="bower_components/angular/angular.js"></script>
···
<script src="bower_components/angular/angular.js"></script>
```
If the angular script tag appears more than once you will get the error with or without bower.
```
WARNING: Tried to load angular more than once.
```

**Comment by mariohmol** [comment]
Having same issue.. dont know how to solve it.. looking at the scripts that meteor added in my code i have: 

```
  <script type="text/javascript" src="/packages/angular.js?hash=4eebeee12feebcf34ccec8b82a9d1bd83175a005"></script>
  <script type="text/javascript" src="/packages/angular_angular.js?hash=08f63d24a8b0f235c02f3671f0823c0b8715d45e"></script>
```
Is this angular_angular giving the error? but i dont know where it came from... my dependencies are:

```
"dependencies": {
    "angular": "^1.5.5",
    "angular-animate": "^1.5.5",
    "angular-aria": "^1.5.5",
    "angular-component": "^0.1.0",
    "angular-material": "^1.0.8",
    "angular-messages": "^1.5.5",
    "angular-meteor": "^1.3.10",
    "angular-mocks": "^1.5.5",
    "angular-sanitize": "^1.5.5",
    "angular-ui-router": "^0.3.0",
    "meteor-node-stubs": "~0.2.0"
  }
```

**Comment by abcd-ca** [comment]
@mariohmol I haven't gotten that error in a long time now but check if you have any duplicate service definitions – like if you have myService1.js and myService2.js but they both internally define myService1 by accident 'cause you duplicated myService1.js as a starter for myService2.js

**Comment by mariohmol** [comment]
That is a very tiny project.. there is just one service.. and the angular itself has not been included 2 times.. i gues that the error is this angular_angular , but i dont know where it came from.. 

this is the project, take a look https://github.com/Gambiologia/meteorapp

This repo is basicly a meteor for dummies.. where i explain step by step how to do the enviroment and i would like to have a CRUD.. but this erros is driven me crazy
