### ISSUE TITLE
Example of Angular-Meteor

### ISSUE THREAD

**Issue by elvenking** [Urigo/angular-meteor#230]
Hello, i just want to ask if there is somewhere a full source code example of non-trivial application made using Angular-Meteor.

Thanks

**Comment by Urigo** [comment]
That's a good request, maybe more people from the community will share their code...

I'm trying to extend the tutorial to be as non-trivial as possible by adding more chapters for more real life scenarios.
Here is the last chapter and you can look at the code in the button:
http://angularjs.meteor.com/tutorial/step_16

Can you give more non-trivial scenarios that we could add to the tutorial? (or add them yourself?)

**Comment by YonathanB** [comment]
Hi Uri,
I've read all your tutorial and I've decided to make a small app using your
framework.
I want to add an internationalisation package to make it multilingual.
Do you suggest me to choose a angular solution or meteor? why?
thanks a lot

2015-03-12 22:32 GMT+02:00 Uri Goldshtein <notifications@github.com>:

> Closed #230 <https://github.com/Urigo/angular-meteor/issues/230>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Urigo/angular-meteor/issues/230#event-251249868>.
>



-- 
*--------------------------------------------------------------------------------------------------------------*
*Yonathan Benitah ----- יונתן בניטה*
+(972) 54-7 440 645

*כל מאן דרחמנא עביד לטב עביד*
*Tout ce que fait le Seigneur , Il le fait pour le bien*

**Comment by elvenking** [comment]
Hi Uri,

I think that tutorial is great, but i would like to see the final source code at github. 
I cant contribute code because i did not write anything with angular-meteor. I investigating your framework because it seems damn cool ;)

**Comment by Urigo** [comment]
@YonathanB as internationalization is mostly on the client side I would suggest the Angular solution.
Here is a nice from the recent ng-conf about internationalization future in angular https://www.youtube.com/watch?v=iBBkCA1M-mc
I think the best solution now is Pascal's existing solution.

@elvenking all the code is in branches by the step name in this repository (the links leads you to the branch of step 16, the last one:
https://github.com/Urigo/meteor-angular-socially/tree/step_16
