### ISSUE TITLE
How to use Angular-Meteor and Ionic-Meteor together ?

### ISSUE THREAD

**Issue by elvenking** [Urigo/angular-meteor#232]
This is follow up of my previous question #230.

Can someone provide an example of running Angular-Meteor and Ionic-Meteor together ?

I mean one codebase for Web, Android and iOS. The goal is to share code as much as possible between web and mobile.

**Comment by Urigo** [comment]
Yes, so there is a package.
Start by using the tutorial about mobile:  http://angularjs.meteor.com/tutorial/step_11

Then you can use the official Ionic package:

    meteor add driftyco:ionic

and look at the example here:
https://github.com/netanelgilad/meteor-ionic-example

But it's not updated, I think you can use it still and it will help you and I hope to update it soon
