### ISSUE TITLE
404 with karma and velocity

### ISSUE THREAD

**Issue by epotvin** [Urigo/angular-meteor#234]
I'm trying to use velocity as my main testing platform but with Karma and my integration tests I have a weird issue. The karma runtime running in the other chrome instance can't reach ng.html files. I have this message in my console :

http://localhost:9876/client/views/navbar.ng.html 404 (Not Found)

This keeps even angular to start. 

Emmanuel

**Comment by Urigo** [comment]
@epotvin can you please share a reproduction so I can look at it and try to solve it?

**Comment by Sanjo** [comment]
@epotvin When you provide a reproduce I can also have a look if you use sanjo:jasmine.

**Comment by epotvin** [comment]
No problem, I'll do it as soon as I have a minute!

Thanks guys!

**Comment by epotvin** [comment]
Hello again,

Here is the example application I created to reproduce this issue and some others :+1: 

https://github.com/epotvin/thumbnail-example

I explain a little bit the problem in the readme... Hope it'll help

**Comment by netanelgilad** [comment]
Ok I got it.
What happens is that when we compile the .ng.html files and put them into the templateCache in a js file, we add the file with original path of the file, which ends with `.html`. That causes the file to be imported as an html import and not as a script (@Sanjo, that means sanjo:karma acts differently from meteor in that case, if I understood who adds the file to karma).
It is a small fix in the compile plugin to add a js extenstion...

**Comment by Urigo** [comment]
Fixed on 0.8.3
