### ISSUE TITLE
Does ng-include work inside a template?

### ISSUE THREAD

**Issue by tjmonsi** [Urigo/angular-meteor#237]
I was trying this out:
```html
<template name="header">
  <ng-include src="'client/templates/includes/header/header.ng.html'"></ng-include>
</template>
```

But nothing happens. It doesn't load the header.ng.html file... I am doing something wrong?

**Comment by tjmonsi** [comment]
Never mind. I got it working. It seems that I have to put the ng-app on the top most html file and not inside a template file.

**Comment by Urigo** [comment]
ok closing
