### ISSUE TITLE
can not add record

### ISSUE THREAD

**Issue by windmaomao** [Urigo/angular-meteor#241]
$scope.items = $meteor.collection(Projects);

this works for viewing items, but when I do $scope.items.push({ title: "123"}); nothing happens. No record added to database. But if i try meteor mongo, i can add data from server,

   db.projects.insert({title: "abc"});

please help. I don't know where I should look to address this issue.

**Comment by windmaomao** [comment]
this is very strange, 

    angular.module("Q6").controller("ProjectsListController", ['$scope', '$meteor', function($scope, $meteor){
        $scope.items = $meteor.collection(Projects);
        console.log($scope.items);
    }]);
    
    angular.module("Q6").controller("ProjectsUpdateController", ['$scope', '$meteor', '$state', function($scope, $meteor, $state){
    
        $scope.items = $meteor.collection(Projects, true);
        $scope.data = {};
    
        $scope.update = function() {
            if ("_id" in $scope.data) {
    
            } else {
                console.log($scope.data);
                $scope.items.push($scope.data);
                console.log($scope.items);
                $scope.items.save();
                console.log($scope.items);
                $state.go('projects-list');
            }
        }
    
        $scope.remove = function(item) {
            $scope.items.splice($scope.items.indexOf(item), 1);
        }
    }]);


list and update are two different routes, support i have three records, if i go to update page, save() will show one new record is added to $scope.items. But then it redirect to list page, and it'll still print three records. And if I refresh the page, it'll still show three records. 

From the tutorial, push() seems good enough to add new record. What have I been missing ?

**Comment by windmaomao** [comment]
i figure out the reason, I have to add the following to server. Is that because I have enable the secure module or something ? I first followed the tutorial on meteor, so my repo is a bit mixed with all codes.

Projects.allow({
   'insert': function(userId, doc) {
       return true;
   }
});

**Comment by Urigo** [comment]
Yes exactly, if you remove the insecure package you have to add those rules. you can read more in step 8:
http://angularjs.meteor.com/tutorial/step_08

**Comment by funkytaco** [comment]
The step_08 tutorial URL is now 

http://angular-meteor.com/tutorials/angular1/user-accounts-authentication-and-permissions
