### ISSUE TITLE
Use $meteor service in a "non-meteor-environment"?

### ISSUE THREAD

**Issue by platdesign** [Urigo/angular-meteor#242]
Hey,
first i would like to thank you for this nice work! =)

I would like to create a stand alone angular app which should use a meteor backend.
Found [asteroid](https://github.com/mondora/asteroid), a nice module to communicate over ddp with meteor. Is there a way, to create a module of your `$meteor` service which can be used outside of the meteor-environment?

**Comment by Urigo** [comment]
yes that is something on our backlog. should be to hard and would love pull requests.

But can you elaborate on why do you want to use asteroid and not plain Meteor?

**Comment by platdesign** [comment]
Im new to meteor and like the way it communicates over ddp. But i dont need the "frontend" component and bundling mechanisms on js and html files. I would love to use browserify for this on my angular app. It gives me a nice way to structure code and templates (e.g. using jade).

Maybe there is a better way and im doing it wrong?!

**Comment by Urigo** [comment]
there is no wrong or right but I would argue that it's easier with Meteor then with browserify.
With Meteor you don't need to do anything, it has it's own build process and you don't care about it.
You can structure your code and files anyway you want and meteor with gather everything for you automatically.
And you can also work with jade - https://github.com/civilframe/meteor-angular-jade

**Comment by platdesign** [comment]
the app is build like this:

```javascript
var angular = require('angular');

var app = angular.module('app', [
   require('ui-router').name
]);

app.service('myService', require('./services/myService.js');

app.config(function($stateProvider){
  $stateProvider.state('home', {
    url: '/',
    template: require('./states/home/template.jade')
  });
});
...
```

This gives me a nicer and much more flexible way to organize the components and files than meteors build process does.

The question is, is there a way to extract meteors frontend components (minimongo, ddpclient, etc) used in the Meteor lib to use it this way.

**Comment by Urigo** [comment]
Well, sorry but I still not convinced...

In Meteor, your first line can be gone:

    var angular = require('angular');

app initialization will be just a string:

    var app = angular.module('app', [
       'ui.router'
    ]);

The service will just be defined where it is and Meteor will just bring it, so there is no need for that as well:

    app.service('myService', require('./services/myService.js');

and the same with the template...

so you just write more code when Meteor already is doing the require for you...  no?
again, you can place your files anywhere.... no need to do any require.

About using the frontend components, I think it's possible and I would argue that this project will be better fit than asteroid, but I don't think anyone done that yet..
