### ISSUE TITLE
compile of html can hang meteor build without showing any error

### ISSUE THREAD

**Issue by dohomi** [Urigo/angular-meteor#243]
Hello,

I just playing around with angular meteor and think its very well done kickstart to use angular in combination with Meteor. I recently just crashed my app without any error message, the HTML compile was missing double quotes```""``` where I hat single```''```.
Took me couple of time to figure out why the application didn't start any more. Would be great if there would be a console error which HTML file failed to compile.

Anyways I love your approach combining angular with meteor :+1:

**Comment by Urigo** [comment]
@dohomi please provide and reproduction...

**Comment by dohomi** [comment]
@Urigo 
Its a very minor edge case I think. I copied some configuration and didn't used the quotes correctly:
```
<div class="myclass" medium-editor options='{somoption:"value"}'></div>
```
I will set up a repro soon but now all works as expected.

**Comment by Urigo** [comment]
cool, I just wanted to see that so maybe I could see how to handle a better error message
