### ISSUE TITLE
Using an AngularMeteorObject as argument for $meteor.call.

### ISSUE THREAD

**Issue by JNissi** [Urigo/angular-meteor#247]
I get an object from the database with `$meteor.object(Coll, id, false)` and set it to a $scope variable. I then try to save the object when a save button is clicked. I use a method call for saving, because I need to touch some users while saving. `$meteor.call('updateObj', $scope.obj.id, $scope.obj)`.

At this point the code fails miserably because the AngularMeteorObject has some circular references and makes EJSON fail. `Uncaught RangeError: Maximum call stack size exceeded`

Is there a way to use the AngularMeteorObject as an argument to a method call, other than hand-picking the properties from the object to a new plain object?

I can provide sample code later if needed.

**Comment by Urigo** [comment]
@JNissi yes a sample code will be great!

**Comment by netanelgilad** [comment]
@Urigo This probably happens because of internal properties that exist on the object (used to get the collection and such).
We need to add a function like `.raw` or something like that to get the raw object and it's properties for situations like this.

**Comment by Urigo** [comment]
@netanelgilad yes, but I still want to see a reproduction first, it might be a different thing

**Comment by JNissi** [comment]
@netanelgilad is on the right track. I was also thinking of some kind of raw object getter. Like Restangular has `Restangular.stripRestangular()`.

I created a small sample project: https://github.com/JNissi/meteor-ng-cat It's pretty much the minimal example I could think of. I didn't even use the method call in the example, because I noticed the problem is a bit broader in scope and breaks all `(E)JSON.stringify()` calls with an `AngularMeteorObject` as the parameter.

**Comment by Urigo** [comment]
@JNissi thanks for the reproduction!
Do you want to pull request that solution?  should be pretty simple and we can help you

**Comment by JNissi** [comment]
Is this sufficient? I feel a bit bad adding a method called 'raw' to the object, as the probability of collision with actual data seems quite possible.

**Comment by Urigo** [comment]
how about stripAngularMeteor?

**Comment by netanelgilad** [comment]
getRawObject?

**Comment by Urigo** [comment]
yes much better!
