### ISSUE TITLE
is it possible to remove the blaze dependency

### ISSUE THREAD

**Issue by mxab** [Urigo/angular-meteor#253]
Hi,
first of all thanks for the great work on this project.

I was wondering if it would be possible to remove the blaze dependency at all. Since my sample project setup has only the index.html and therefore the blaze.js, html.js, templating.js is loaded, especially the blaze.js is not the smallest of files.

**Comment by mxab** [comment]
I played bit arround and was able to get it to work, but I am not sure if this is really the way to go :)

Initially if the index.html has only the body tag with an ng-include=index.ng.html and the ng-app directive, the templating package generated js file that looks basically like this:
```
...
//some stuff
...

Meteor.startup(function() { $('body').attr({"ng-app":"app","ng-include":"'client/index.ng.html'"}); });
```
if I copy this part simple in my app.js, remove the packages templating/htmljs/blaze from the meteor-platform and add a global Template variable to prevent the ```angular-meteor.template``` from failing it seems to work without loading blaze.js and so on.

I put my example project here
https://github.com/mxab/angular-meteor-without-blaze

**Comment by mxab** [comment]
Would it be an idea to make the ```angular-meteor.template``` optional?

**Comment by mxab** [comment]
some more findings:
the google/facebook and I guess the other oauth packages as well depend on the templating package which than loads blaze and so on
I opened an issues here https://github.com/meteor/meteor/issues/4045 but I am not sure if that will be resolved, for know I guess a custom oauth packages would be neccessary

another thing which should be avoided is the
```Meteor.startup(function() { $('body').attr({"ng-app":"app","ng-include":"'client/index.ng.html'"}); });``` in terms of that if you use angular material some things may not work when using ng-include on the same element ng-app (see also this issue https://github.com/angular/material/issues/1192)

**Comment by Urigo** [comment]
@mxab very interesting ideas!
I was playing with that myself before starting this project and done very similar things to you.
I have a plan to pull request the templating package to make it Blaze agnostic (basically separate it into 2 separate packages).
I think that will be a first interesting step.
Then pull request to fix the issues you mentioned.
Question - why would you want not to load the angular-meteor.template? 
that obviously won't be hard, be I want to make it as easy as possible for regular usage so we need to think of a way to do that without adding steps for regular users

**Comment by mxab** [comment]
Hi @Urigo,
the idea behind making template optional was that it assumes the presence of meteor template package and fails if the global Template var is not available
https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-template.js#L5
another idea would be to move the service $meteor you define in
https://github.com/Urigo/angular-meteor/blob/master/angular-meteor.js#L63
to a submodule "angular-meteor.meteor" as it does not depend on template, so if someone would like to have an approach without blaze/template you can only depend on this module

From what I get from the templating package, it does 3 things, append stuff to
- head
- body
- add blaze views to the js

adding stuff from to head/body would be still useful I guess

**Comment by mxab** [comment]
If you think it makes sense, I would setup a "meteor-angluar-platform" package like the meteor-platform but without the blaze/templating dependency.
actually I think jQuery could also be just a weak dependency for that case

**Comment by Urigo** [comment]
@mxab yes definitely!  creating a "meteor-angluar-platform" will be amazing.

About the templates, if you don't want to change the API we can just check if the templating package exists before executing the code.
Its not so nice, but that means that regular users won't have to do anything in addition

**Comment by mxab** [comment]
@Urigo 
I setup some packages here:
- ```planettraining:angular-meteor-platform```
- ```planettraining:accounts-google``` same like meteor but depends on  ```planettraining:google-no-ui-conf``` which does not include templating
- ```planettraining:accounts-facebook``` / ```planettraining:facebook-no-ui-conf```

Regarding the templating, at the moment I have ```Template = {}``` in my code. The idea about moving the $meteor service into a custom module would not break anything for the regular user as you still would include all the submodules in the ```angular-meteor``` module, 
```
angular.module("myRegularApp", ['angular-meteor'])..
```
but if someone does not use the templating you could just 

```
angular.module("myAppWithoutTemplating", [
  'angular-meteor.meteor',  //assuming this is where the $meteor service is provided
  'angular-meteor.subscribe',
  'angular-meteor.collections',
  'angular-meteor.meteor-collection',
  'angular-meteor.object',
  'angular-meteor.user',
  'angular-meteor.methods',
  'angular-meteor.session',
  'angular-meteor.reactive-scope',
  'angular-meteor.utils',
  'angular-meteor.camera',
  'hashKeyCopier']
```

but I haven't looked at all the code, so maybe it wouldn't work :)

**Comment by Urigo** [comment]
so in that way it will work right now, no need to change anything no?

**Comment by mxab** [comment]
yes it works so far, here is a running example :)
https://github.com/mxab/angular-meteor-todos-no-blaze

There is nothing that is needed to be changed, the only thing that feels a bit awkward is that I need to "polyfill" the Template package that the ```angular-meteor.template``` works
Don't get me wrong I really do not want you to change anything for the regular use case. I only think that if someone does want the templating module there is at the moment no way to "pick" the modules you want as the $meteor service is defined in the top level.

On the other hand the $meteor is only a convenience service for functions from other modules and I actually could pick functions :)

**Comment by MilosStanic** [comment]
Hey, @mxab this is great! Can you, please, describe how did you include angular-material into your project? 
I'm coming from the Angular hemisphere here, so I'm trying to make myself as comfy as possible. 
@Urigo thanks for the whole thing. I love the roadmap. Btw, regarding the "angular on server" stuff, I think I saw someone on Twitter the other day mentioning they have managed to run Angular 2 on server. 
Sorry to barge in here with off topic stuff, but I don't see other place to rant. 
Are you guys considering opening a Gitter channel for angular-meteor?

Sorry again, love the stuff. Will keep on with the tutorial.

**Comment by mxab** [comment]
Hey @MilosStanic for the example I took a very lazy approach and included them via npm, I created a angular-material package in the packages folder
https://github.com/mxab/angular-meteor-todos-no-blaze/blob/master/packages/angular-material/package.js
and activated it via https://github.com/mxab/angular-meteor-todos-no-blaze/blob/master/.meteor/packages#L9

the correcter approach would be to publish a angular-material package via atmosphere

**Comment by MilosStanic** [comment]
Thank you very much, @mxab! I tried it and it works. So simple, as everything I saw in MeteorJS so far. 
Regarding the correct approach, why doesn't anyone make the angular-material package on the atmosphere? Is it a copyright issue? Would it need to be maintained, or it would automatically pull the latest master branch from angular-material?

**Comment by mxab** [comment]
@MilosStanic no issues that I'm aware of, I was planning to publish a package just hadn't time so far, but the material package discussion is a bit off-topic for this issue thread :)

**Comment by dohomi** [comment]
Hi @MilosStanic you'll find the package here: https://atmospherejs.com/planettraining/angular-material 

Sorry haven't done much documentation yet, but if you are used to Angular there isn't anything new for you. It's simply the wrapper with the necessary angular material files (currently .0.9.0-rc1) Cheers

**Comment by MilosStanic** [comment]
Thanks a lot @dohomi

**Comment by Urigo** [comment]
@mxab @dohomi it was great meeting you guys and I love your amazing work!
Please add docs on our website and in the readme file to reference all your work so people will know about it!
