### ISSUE TITLE
have problems with ng-include

### ISSUE THREAD

**Issue by skihappy** [Urigo/angular-meteor#256]
I'm following your tutorial on angular-meteor.  For some reason, the index.ng.html file does not get included into index.html after using the <div ng-include="'index.ng.html'"></div>. Any ideas?

**Comment by Urigo** [comment]
have you placed it in 'index.ng.html' inside " " ?
like

    "'index.ng.html'"

**Comment by skihappy** [comment]
I did. I tried every possible quote combo as well. I, also, tried to specify the absolute path as ~/meteor-dev/socially/index.ng.html. Thanks for responding, by the way.

                           Dmitry Shusterman

 


Date: Mon, 23 Mar 2015 16:12:50 -0700

**Comment by skihappy** [comment]
Here is what I got after adding angular-meteor package just to show version numbers:
dmitry@dmitry:~/meteor-dev/socially$ meteor add urigo:angular                                              Changes to your project's package version selections:                                              angularjs:angular                   added, version 1.3.15dburles:mongo-collection-instances  added, version 0.3.3lai:collection-extensions           added, version 0.1.3urigo:angular                       added, version 0.8.0
                                              urigo:angular: The simplest no-conflict way to use AngularJS with Meteor,Meteorite and Atmosphere Smart Packages.


                           Dmitry Shusterman

 


Date: Mon, 23 Mar 2015 16:12:50 -0700

**Comment by Urigo** [comment]
can you share your complete project?

**Comment by skihappy** [comment]
Do you need anything else? I did add bootstrap package to meteor.

                           Dmitry Shusterman

 


Date: Mon, 23 Mar 2015 16:46:19 -0700

**Comment by Urigo** [comment]
can you upload everything to Github and send me a link?

**Comment by Urigo** [comment]
The tutorial works for me..

**Comment by skihappy** [comment]
https://github.com/skihappy/meteor-angular-issue/tree/master/socially

                           Dmitry Shusterman

 


Date: Mon, 23 Mar 2015 19:18:26 -0700

**Comment by skihappy** [comment]
OK. Thanks for trying. I'll reinstall the whole thing and try again clean.
                           Dmitry Shusterman

 


Date: Mon, 23 Mar 2015 19:34:17 -0700

**Comment by Urigo** [comment]
I've looked at your code.
The problem is that you haven't initialized the app...  read a bit further in the step's page...

**Comment by skihappy** [comment]
Thanks.

                           Dmitry Shusterman

 


Date: Tue, 24 Mar 2015 09:35:38 -0700

**Comment by andrew-wharton** [comment]
+1 please make this clear in the tutorial. I spent an hour trying to figure out why the template wasn't being included before finding this issue... very frustrating and I was *this* close to throwing in the towel.

**Comment by Urigo** [comment]
@andrew-wharton , @simonv3 pulled requested the tutorial and added a note to the tutorial, can you look at it and say if it's clear enough?

**Comment by andrew-wharton** [comment]
Looks great! Thanks!

**Comment by SJKool** [comment]
facing similar issue... please checkout the link: https://github.com/SJKool/socially/tree/local

and screenshot with the issue -- https://raw.githubusercontent.com/SJKool/socially/local/screenshot.jpg

**Comment by skihappy** [comment]
I got my issue resolved. Thanks, though. It was just a matter of a simple mistake on my part.

                           Dmitry Shusterman

 


Date: Sun, 2 Aug 2015 06:47:04 -0700

**Comment by GustavoSaudade** [comment]
I'm trying to step 1 of the tutorial .... but the ng-include don't works for me.

Can you help me?

**Comment by Urigo** [comment]
@GustavoSaudade which tutorial are you referring to?

**Comment by nazarel** [comment]
@Urigo I cannot speak for @GustavoSaudade, but I am encountering the same issue for the Meteor-Angular1 tutorial. I am on Windows and it's only quite recently (within past 1 month)  that this became an issue.

**Comment by ansaries** [comment]
Hi Urigo I am from MEAN background, I also got stuck with the ng-include attribute on the step1 of the socially app... review my code:
https://github.com/ansaries/AngMet.git

note that if i use {{}} braces in the index.html instead of ng-include then it evaluates the expression. which means that angular is running. but ng-include src="'client/main.html'" is not working. I tried all possible quotes. please help.

**Comment by tehbmar** [comment]
@Urigo hello, similar to @ansaries I am experiencing the same issues.  I have tried all sorts of combinations but nothing seems to work.  I also can't seem to get the code base as of faf85b1d1b0593573bc268ee948ec4834d7fb7a to even run in meteor.  Should I just move onto the Angular 2 or should I just find a different tutorial?

**Comment by HectorRPL** [comment]
Hello, I'm in bootstraping Angular 1 tutorial and ng-include dont works for me. Next I will put my code:

**client/index.html**
```
<body ng-app="rhane">
  <div ng-include src="'client/main.html'"></div>
</body>
```
**client/main.html**
`<p>Nothing here {{ 'yet' + '!' }}</p>`
**client/main.js**
```
import angular 				from 'angular';
import angularMeteor 	from 'angular-meteor';

angular.module('rhane', [
  angularMeteor
]);
```

Note, seem that angular is loaded fine, but for some reason cant it work ng-include like a tutorial explained us
some ideas?

**Comment by ansaries** [comment]
Just follow the next few steps and it will start working.

**Comment by tehbmar** [comment]
@ansaries Actually in order to get this to work I actually had to copy all of the versions from the git repo then run 
`meteor npm update pbastowski:angular-babel`

I think there are some issues with the template system, meteor 1.4, and angular-babel...

Either way I don't know 100% why it works or the actual issue in the code base, but it worked for me after figuring this out.

**Comment by yuristsepaniuk** [comment]
same issue with meteor 1.4

**Comment by yuristsepaniuk** [comment]
solution:

keep tutorial code as it is, except main.js -->

import angular from 'angular';
import angularMeteor from 'angular-meteor';
**import templateUrl from './main.html';**
 
angular.module('socially', [
  angularMeteor
]);


So what is going on? When we import main.html, It will be embedded into app.js for the client. No import to concatenation for main.html for result bundle.
P.S. Angular is bad, meteor+angular is bigger devil. To many gotchas :)

**Comment by kamilkisiela** [comment]
@yuristsepaniuk If the `main.html` file contains `<head>` or `<body>` the compiler will use it as the main html file and not as a template so there's no point of importing it.

You can easily just remove `import templateUrl from './main.html'` statement.
