### ISSUE TITLE
Add compileStep.packageName to templateCache key

### ISSUE THREAD

**Issue by pward123** [Urigo/angular-meteor#258]
I like to organize my angular templates into meteor packages to make it easier to use tinytest, etc.

The angular-meteor plugin uses compileStep.inputPath when placing the compiled templates into $templateCache.  This causes templates with the same path (relative to their package) to register with the same key in $templateCache.

Any chance of fixing this? (it would be a breaking change)

**Comment by Urigo** [comment]
@pward123 that's interesting, can you share a scenario?
also, what other suggestion to you have for the naming source?  maybe we can add a package name prefix?
@netanelgilad other ideas?

**Comment by pward123** [comment]
I'm new to angular, so I've been playing around with building a sample application.  Here's the repo (the readme has a description of the problem):

https://github.com/pward123/angular-base

**Comment by pward123** [comment]
Meteor has to deal with a similar situation when assets are placed in a package.  Instead of dropping your_logo_here.png into the main application's /public tree, I'm calling api.addFiles from the ui-login/package.js file.

In order to keep packages from overwriting each other's assets, Meteor prepends the package name plus an underscore to create the path to the asset:

    <img src=/packages/angular-base_ui-login/client/assets/your_logo_here.gif">

**Comment by Urigo** [comment]
@pward123 that sounds legit.
Do you want to create a pull request for that and get the credit?

**Comment by pward123** [comment]
Done. PR #303
