### ISSUE TITLE
Build sample project that can be used for examples, quick references and also reproductions of issues via forks

### ISSUE THREAD

**Issue by smoke** [Urigo/angular-meteor#260]
angular-meteor is becoming more and more popular and in order to improve the collaboration between us all I think it would be extremely helpful if there is a sample project that we can use for the above reasons.

In a perfect world it would:
 - be in a separate repository that developers can fork and share
 - optionally be installable via `meteor create --example angular-meteor` (not sure if meteor allows such things out of the box)
 - it would utilize all the specific features of angular-meteor
 - it would utilize all the good practices for angular-meteor
 - it would have views/places usable for simple performance metrics

@Urigo please share your thoughts and also pull in the discussion whoever you think fits in this discussion.

**Comment by Urigo** [comment]
That is a very good idea.
I was aiming for the tutorial to be just that - an example, best practices, tests and more..
But I guess it's not super easy for people to change it.
What about creating a separate repo that always holds the last step on the tutorial.
Then people can work on that and if someone does something interesting I can take it from there back to the tutorial?

**Comment by revov** [comment]
I think this would be a great boost for beginners and will attract a lot of people hesitating about the technology. A skeleton application with a sample controller (or two) that demonstrates all the concepts of angular-meteor that can simply be forked and run can not only serve as the basis of angular-meteor projects, but can also be used to demonstrate(reproduce) new features, issues, etc.

The tutorial is great for learning the concepts of angular-meteor but I think that a skeleton app should go a step further. Not immediately, of course, but in the future it will naturally improve and build up on what the tutorial is now. It will incorporate best practeces, all angular-meteor features and will help eager users who are impatient to go through the tutorial before getting their hands dirty.

Wouldn't it be amazing if a newcommer can experience ALL the awesome features of angular-meteor by jumping right into the action with a couple of commands.

**Comment by Urigo** [comment]
Yes I totally agree.
What will this repo include that is different from the end of the tutorial?

**Comment by smoke** [comment]
@Urigo I have skimmed the tutorial again and I think the app from the end of the tutorial would be a good start and the community can take it from there.

So far it seems that the "tutorial app" is missing only the new features added recently like:
 - $meteor.waitForUser() and $meteor.requireUser()
 - <meteor-include> may be
 - $meteor.camera

**Comment by netanelgilad** [comment]
@Urigo I think the master branch of angular-meteor-socially should always be the same as the last step. That could make it easier to play around with full app by just cloning it and not switching branches.. 
Also we could reach out to MDG to add angular-meteor-socially as a meteor example even if they still don't have the feature to add examples by the community..

**Comment by Novashock** [comment]
@Urigo how are you? I am in agreement with both @smoke and @netanelgilad The master should be the final product if that is possible. Thanks again for your time and work. Did I tell you last time we talk you are awesome?

**Comment by Urigo** [comment]
Thank you guys for the great idea!
I've done that now, you can check out https://github.com/Urigo/meteor-angular-socially  and hopfully now people could add ideas and features to that app and expand the tutorial!
