### ISSUE TITLE
ios $http get, CORS 

### ISSUE THREAD

**Issue by hagata** [Urigo/angular-meteor#263]
I'm running into issues working with external api's with angulars $http requests. Working with the standard $http get works just fine in browsers when doing  
```javascript
$http.get('http://httpbin.org/get').success(function(data,status){
	console.log(data,status);
})
```
Im I've added the <code>App.accessRule('*');</code> to mobile-config.js

and I also have the following:
```javascript
.config(['$httpProvider', function($httpProvider) {
    $httpProvider.defaults.useXDomain = true;
    delete $httpProvider.defaults.headers.common['X-Requested-With'];
}]);
```

However, when running the app in iOS, I'm running into cross origin access issues. I haven't been able to solve this with anything yet.

I'm getting errors related to meteor.local.
This is the first time I'm working with meteor & angular like this, and I might be missing something simple?

```
[Error] Failed to load resource: Origin http://meteor.local is not allowed by Access-Control-Allow-Origin. (200, line 0)
[Error] XMLHttpRequest cannot load http://httpbin.org/status/200. Origin http://meteor.local is not allowed by Access-Control-Allow-Origin. (connectDev, line 0)
```

**Comment by Urigo** [comment]
Might it be related to this?
https://github.com/meteor/meteor/issues/3469

**Comment by hagata** [comment]
Yes, it's similar, but I don't have my app published anywhere.

**Comment by Urigo** [comment]
So do you think it's a Meteor or angular-meteor bug?
can you please send a reproduction?

**Comment by netanelgilad** [comment]
@hagata Is this an ios specific issue? does it work when you run in on android?

**Comment by Urigo** [comment]
@hagata please provide a reproduction

**Comment by Urigo** [comment]
Closing, in case you provide a reproduction please reopen

**Comment by adrianbj** [comment]
I was having a horrible time with getting an external API today and had no luck with angular's $http, but using meteor's HTTP package seems to have solved it - might be a useful tip for others.
