### ISSUE TITLE
limit or prevent reactivity for a view - {reactive:false} is not working

### ISSUE THREAD

**Issue by tgienger** [Urigo/angular-meteor#264]
Is it possible to limit the amount of reactivity within a view? For example in a message board I want the thread with the latest reply to be "bumped" to the top, but I don't want it to do that while a user is reading a page. It would be quite annoying to be reading a post only to have it disappear on you and be placed back at the top of the page.

**Comment by tgienger** [comment]
I just read reactive: false. Not even an angular issue at all sorry. closing.

**Comment by netanelgilad** [comment]
Looking through the issue you referenced it seems like this should not be an issue any more. Inside `$meteorCollection` we use `observe` and in the docs it says that if the cursor was created with `reactive: false` then it should only deliver the first set of documents.
Can you share the code where you create the cursor, to make sure that is not the issue?

**Comment by Urigo** [comment]
@tgienger as you haven't provided a reproduction or comment I'm closing this but please reopen if you find it is still a problem for you
