### ISSUE TITLE
Tutorial confusion

### ISSUE THREAD

**Issue by moof2k** [Urigo/angular-meteor#266]
The tutorial here (http://angularjs.meteor.com/tutorial/step_00) gives the impression that upon completion of the first ng-include modification

    <body>
      <div ng-include="'index.ng.html'"></div>
    </body>

..you'll be left with a working application. However nothing appears until you go to the next step and add

    <div ng-app="socially" ng-include="'index.ng.html'"></div>

and

    if (Meteor.isClient) {
      angular.module('socially',['angular-meteor']);
    }

**Comment by simonv3** [comment]
Heh, was just going through this myself and noticed it.

**Comment by Urigo** [comment]
Thanks guys!
