### ISSUE TITLE
Using `getReactively` with `controllerAs`

### ISSUE THREAD

**Issue by Geen-Henk** [Urigo/angular-meteor#268]
I've been following the tutorial, in my preferred Angular coding style (using `this.` instead of `$scope.`). 

``` javascript
var self = this;

$meteor.autorun(self, function () {
  $meteor.subscribe("parties", {
    limit: parseInt(self.getReactively("perPage")),
    skip:  parseInt((self.getReactively("page ") - 1) * self.getReactively("perPage")),
    sort:  self.getReactively("sort"),
  }).then(function () {
    self.partyCount = $meteor.object(Counts, "numberOfParties", false);
  });
});
```

Only to come to the conclusion that `getReactively` is undefined on my controller, but is [a method/functionality of `$scope`](http://angularjs.meteor.com/api/getReactively)... Is there a way to make it available to my controller, besides using it off `$scope`?

**Comment by jonnylynchy** [comment]
I think if you're using this vs $scope, you would lose the ability to
access the $scope hierarchy. You also lose the ability to $emit (upwards)
and $broadcast (downwards).

**Comment by smoke** [comment]
With controllerAs you must use $scope to access methods and properties from the scope e.g. $emit, $broadcast, $watch. 
Of course $scope.getReactively is no exception.

**Comment by smoke** [comment]
I had to mention that $scope is available from the Dependency Injector - so you should only request it as a parameter for your controller constructor.

**Comment by mxab** [comment]
As @smoke mentioned you could use to access the controller via the scope. So if you have ````controllerAs:"myCtrl"````
I think inside your controller you can do ````$scope.getReactively("myCtrl.perPage")````

**Comment by Urigo** [comment]
Thanks everyone for all the solutions.
@Geen-Henk I'm closing this, please reopen if it didn't work for you

**Comment by Geen-Henk** [comment]
@mxab @smoke - thank you, this works
