### ISSUE TITLE
Best way to use optional modules like ngSanitize?

### ISSUE THREAD

**Issue by nickjanssen** [Urigo/angular-meteor#270]
Could there be a way for end-users to specify which optional angular modules they would like to use in addition? There are many here: https://code.angularjs.org/1.3.13/

Currently I've manually included ngSanitize 1.3.13 because that's what angular-meteor is using. But when angular-meteor updates its angular version, I will have to make sure that my own version of angular-sanitize stays up to date as well, which could become a problem.

**Comment by Urigo** [comment]
I think that the best way is to let Meteor's version solver to handle that for you.

Right now I'm trying to publish all the submodules versions myself under the angularjs Meteor organization but it's very hard to keep up....

I've opened an issue in Angular here: https://github.com/angular/angular.js/issues/11291
but I would love support from the community to publish more of those versions

**Comment by Urigo** [comment]
I hope I gave a suitable answer

**Comment by nickjanssen** [comment]
Sorry for the delay, yes that makes sense. I'll take a look at that video you posted later about the constraint resolved, looks interesting. So for now we'd have to manually publish every angular module in atmosphere, and you're basically asking the angular team to do it automatically for us in the future?

**Comment by Urigo** [comment]
https://atmospherejs.com/angular

**Comment by nickjanssen** [comment]
Awesome, thanks for the update!
