### ISSUE TITLE
App Already Bootstrapped with this Element

### ISSUE THREAD

**Issue by Xample** [Urigo/angular-meteor#271]
Hi, I still have the problem of "App Already Bootstrapped with this Element" in my app.
The problem is if I call the bootstrap manually into the App.js I will get this error but at least it will work, if I do not, nothing is bootstrapped.
I created a very simple boilerplate for a proof of the issue: https://github.com/Xample/Meteor-Angular-Bootstrap-Boilerplate

```bash
git clone https://github.com/Xample/Meteor-Angular-Bootstrap-Boilerplate
cd Meteor-Angular-Bootstrap-Boilerplate
meteor
```

**Comment by mxab** [comment]
Hi
ng-app="appname" and angular.bootstrap(document, ['appname']); do both start the application hence the error message, if you do angular.bootstrap(...) you should not use ng-app="..."

**Comment by Xample** [comment]
Hi, @mxab yes you are right but what I am wondering is why the app is NOT bootstrapped using only ng-app.

**Comment by mxab** [comment]
meteor adds stuff inside the body elements via javascript so ng-app is not there on startup, see the initial response + the template.index.js

the easiest workarround is to put ng-app=... in the <body> tag

**Comment by Xample** [comment]
I knew about the body tag but it seems I cannot neither add an app controller and include its content in the same time
I therefore replaced
```html
<body>
    <div ng-app="wow" ng-include="'client/index.ng.html'"></div>
</body>
```

With (putting out the ng-app)

```html
<body>
    <div ng-app="wow">
        <div  ng-include="'client/index.ng.html'"></div>
    </div>
</body>
```
Then it is bootstrapped!
Thank you @mxab !
