### ISSUE TITLE
DDP.connect and angular-meteor

### ISSUE THREAD

**Issue by jamgold** [Urigo/angular-meteor#272]
I am trying to evaluate Angular for a meteor app so I can use native Ionic for mobile. The problem is that the mobile app is supposed to connect to an existing Meteor application using DDP.connect.

Granted I just started reading the tutorials and api, I was not able to find anything to tell $meteor to actually use a remote connection.

Is this possible at all?

**Comment by Urigo** [comment]
@jamgold right now your best option is to use https://github.com/mondora/asteroid but then you would lose a lot of the benefit of Meteor and angular-meteor.
Can you elaborate why do you need to change the remote connection and not serve the application from the Meteor server?

**Comment by jamgold** [comment]
I need to split a mobile app from its desktop counterpart, and for it to use the same data I want the mobile app to DDP.connect to the desktop backend.

**Comment by Urigo** [comment]
I'm a few of my apps I have 2 different front-end applications, one with desktop and one for mobile (usually also uses Ionic).
The easiest way I found that separated the Angular applications for me but also shares the backend and also makes use of Meteor's features on the client side (Minimongo, PhoneGap integration, etc...) is the just separate the Angular applications and bootstrap them according to the platform like that:


    function onReady(appToRun) {
      angular.bootstrap(document, [appToRun]);
    }

    if (Meteor.isCordova) 
      angular.element(document).on("deviceready", onReady('myMobileApp'));
    else 
      angular.element(document).ready(onReady('myWebApp'));

**Comment by jamgold** [comment]
@Urigo thank you, that approach looks interesting. It still means that most of the code/markup is being bundled into the mobile app, even though never used, correct? For example, if I were to use legacy Jquery libraries like flot, how can I prevent those from being sent to the mobile client? Not to mention assets in /public. Meteor doesn't provide a means to filter where stuff goes other than client,server,cordova AFAIK. The only sensible workaround I have found so far is to split out platforms (different code base with shared packages) and use DDP.connect

**Comment by Urigo** [comment]
You are right, but there is a way to do that separation with packages, some of them I load only per platform (like Ionic and Bootstrap)
It's a little more work to define those local packages but I know Meteor is working on a better solution for that.
In the meantime it works for me better than using Asteroid but it's a personal perspective thing and per project decision..

**Comment by jamgold** [comment]
Agreed. As much as I admire the solution of asteroid for non meteor apps to connect to meteor, I definitely prefer to stay within the meteor _universe_. It would still be nice for meteor-angular to support the connection like a standard meteor Blaze app.

**Comment by netanelgilad** [comment]
Actually wrapping DDP.connect in the angular $meteor object or something that acts like it, is pretty good idea. @Urigo I think we should implement it, and it doesn't seem that complicated..

**Comment by Urigo** [comment]
Throwing more thoughts here...

#### There are a few DDP clients in Javascript, here is a list:
1. Asteroid - this is a nice solution that wraps DDP but also adds Meteor functionality on top of it.
I'm not sure we need those as we wrap those already... 
also, the easier way for us to connect is with an Observe API and they are not supporting that yet:
https://github.com/mondora/asteroid/issues/23   
We can use [diffArray](https://github.com/Urigo/angular-meteor/blob/master/lib/diff-array.js) function from Meteor like we do now.

2. We can use Asteroid DDP client - https://github.com/mondora/ddp.js   
It looks like in that case we would also need to implement an Observe solution outselfs.  
Again we can use Meteor's [diffArray](https://github.com/Urigo/angular-meteor/blob/master/lib/diff-array.js)

3. Another Javascript DDP client - https://github.com/eddflrs/meteor-ddp

4. And the most preferable one on my opinion - Use Meteor's DDP package - 
https://atmospherejs.com/meteor/ddp
If this library can be used outside of Meteor, we know it's well tested and also works with other Meteor clientside packages in case users will want to use that...
I saw Meteor just separated their DDP clients into a few packages (client, server and common) but I'm not sure what are their plans for doing something like that.
It just looks stupid to me that there are a lot of DDP client Javascript clients out there when the Meteor platform itself wrote one.
@avital , any thoughts on that?

**Comment by Urigo** [comment]
@jamgold I think I misunderstood your question...
I wasn't sure you meant [this function](http://docs.meteor.com/#/full/ddp_connect).

Now that I understand, can you please describe the architecture you are trying to build?

We can support that function pretty easily, but I was to understand what are your requirements for collections and not just subscribe and methods.

Thanks

**Comment by jamgold** [comment]
I want to be able to write a stripped down *client* for an existing web application. Since Meteor does not (yet) provide a fine, granular approach which assets to bundle for which platform (other than client/server/cordova), or even for a specific route.
 
Example: the web browser based implementation of my application has back-office functions not needed on a mobile client. I do not want the logic or templates not used on mobile to be included in the distro. My solution would be to write a specific client that connects to the *main* application with DDP.connect.

**Comment by dbnoble** [comment]
@jamgold in my experience, you don't have to do anything special to achieve what you are wanting.

You can simply build a separate Meteor app with your desired client functionality (or clone and strip down your existing one) and set the ENV MONGO_URL to use the same mongoDB instance that your production desktop app is currently using. Reactivity will work as expected on both clients.

As a matter of fact, you wanting to 'stay inside the Meteor universe' is a great reason to avoid DDP connect altogether. Within Meteor, DDP connect is really intended for you to be able to access multiple backends using the SAME client, you are looking for the exact opposite.

This is exactly what I would suggest doing for the admin/subdomain use cases you mentioned. In addition, this is an excellent way to build backend microservices to decouple intensive, long running backend processes that are not initiated from your users and have a dedicated meteor app that caters only to the needs of the client. 

I already use this pattern and I have been extremely happy with the results. Everything is fast and seamless. I am also about to begin building a mobile application and plan to do it this way as well.

**Comment by jamgold** [comment]
@dbnoble you make a very good point. I shall experiment with that. 

What does concern me, however, is the reliance on OPLOG tailing, which I keep reading about being a real hammer on scalability. There are discussions to have node database operations propagated by node to subscribed clients, instead of relying on OPLOG. This is nowhere near implemented, but would certainly affect all applications writing to the DB *out of band*

**Comment by keyvanfatehi** [comment]
I'm in the same boat, currently using asteroid but it is failing me in a classic search pattern where you resubscribe to the same publication with a different query on keyup.

I spent a lot of time (couple weeks now? full time...) fudging around with the meteor cordova integration for this mobile app -- it's not great for trying to come up with something truly polished.

I tried meteoric, but I ran into more issues. I decided to split the mobile app out of meteor altogether and made an ionic app (hence why I am looking at angular tooling again).

Ionic by itself has been brilliant... I look forward to seeing this package made usable from a separate client like an ionic app. In the meanwhile I must debug asteroid.

**Comment by Urigo** [comment]
@keyvanfatehi what are your thoughts about this comment: https://github.com/Urigo/angular-meteor/issues/272#issuecomment-95709983
What is the perfect solution for you?
Do you want to help us work on that?

**Comment by keyvanfatehi** [comment]
Hey @Urigo, I saw that comment and agree with option 4, but option 1 may be more quickly achievable. I am realizing now that I can probably solve my own problem (search) by using asteroid's meteor method call feature.

The perfect intermediate solution would definitely be a proper DDP client (option 4?) with good docs about how to use it from external clients.

Once that exists, we get closer to perfection by writing nice wrappers (things like asteroid) that can provide the full flexibility of DDP (i.e. why does asteroid not have observe? would it have had it if the author didnt have to write the ddp lib himself as well?)

I find it comical that the best ddp clients I've found have been outside of javascript. I use this https://github.com/hharnisc/python-meteor and it has been awesome. The ddp client underneath (written by the same person) supports observe IIRC.

The most impressive one I've seen is https://github.com/martijnwalraven/meteor-ios but I've not had a chance to use it yet.

Yeah, I'm trying my best to help. I added native facebook-connect support to asteroid a few hours ago, but this is definitely more important.

**Comment by KaiBuskirk** [comment]
Danke!

**Comment by idanwe** [comment]
@keyvanfatehi @jamgold take a look at [idanwe/meteor-client-side](https://github.com/idanwe/meteor-client-side)

I exposed the client side of meteor-platform (without blaze) to bower

Give you the ability to use all Meteor API's and DDP protocol from the original implementation

**Comment by Urigo** [comment]
And don't forget of course that now you can get `angular-meteor` with Bower as well!  (https://github.com/Urigo/angular-meteor#meteor-client-side---with-bower)
So here are a few examples:
https://github.com/idanwe/angular-socially-client-side
https://github.com/idanwe/meetup-NY-meteor-ionic-chat

We are going to release a blog post about that to the Ionic blog and I'll link to it here soon.

I'm happy to announce that I'm closing the oldest issue of angular-meteor thanks to @idanwe !!

**Comment by idanwe** [comment]
Awesome!!! :)

**Comment by leizard** [comment]
Hi, @Urigo @idanwe , thank you for your awesome packages.
Can you explain to me what is superior when using  meteor-client-side and angular-meteor instead of Asteroid ? Could Asteroid resolve the reactive problem by on.("changed") event ?
Thank you.

**Comment by Urigo** [comment]
@leizard Asteroid uses it's own implementation of the whole client side with a different syntax.
That means you can't use any of the Meteor packages that works on the client.
