### ISSUE TITLE
Possible limitation of the $urlRouterProvider

### ISSUE THREAD

**Issue by Xample** [Urigo/angular-meteor#274]
Hi, I just found a possible issue with the urlRouteProvider, it is not directly related to the angular-meteor package but as everyone is now using the ng.html files pattern, I should not be the only one affected by this issue.

just run this little project
```bash
git clone https://github.com/Xample/Meteor-Angular-Bootstrap-Boilerplate.git
cd Meteor-Angular-Bootstrap-Boilerplate/
meteor
```

Then open the link : ```http://localhost:3000/tab1```
You will not see anything within the content, but if you click on Tab2 and then back to Tab1 it will work.

The router seems to be looking for the following tag [1] within the body.
```html
<div ui-view class="content"></div>
```

unfortunately it is not "yet" there. This tag [1] is added through the import of the index.ng.html file.
```html
<div ng-include="'client/index.ng.html'"></div>
```
 
Moving the tag [1] from index.ng.html to the ```index.html``` file solves the problem but it is half a solution.

Any idea on how to solve this in a clean way ? Some I had:
- Add a controller to the dependency and fire an event to the router when it is loaded
- Being able to make a synchronous ng-include

Something else I do think about, would the ```ui-view``` directive to itself notify the router once loaded (synchronously or not)

**Comment by netanelgilad** [comment]
I would like to attack the bigger issue here. I don't quite like that we make people use ng-include for their index.ng.html file.
What we could do, is set the index.ng.html file as the main file of the app, and append it to the document in a build plugin. That would mean no more ng-include, for whoever can use the index.ng.html standard (the option to use regular html files with ng-include will also stay available).
@Xample @Urigo what do you guys think?

**Comment by Xample** [comment]
So if no index.html then index.ng.html would be the default fallback ? If index.html people will still be able to mix in other templates engine. It sounds good to me in term of UX.

**Comment by Urigo** [comment]
@Xample it looks like this is related to this issue:
https://github.com/angular-ui/ui-router/issues/679

Can you try to reproduce that with a clean Angular app without Meteor to make sure it's the same problem?

I'm not sure i want to add a work around and push an explicit file automaticly to Meteor just for that.

**Comment by Xample** [comment]
@Urigo okay I took this project https://codeload.github.com/angular-ui/ui-router/zip/master I then ran the *sample* example after including the content view within 2 successive includes. And it works i.e. I have not been able to reproduce the problem.

**Comment by Urigo** [comment]
@Xample I've created a pull request that solves that problem:
https://github.com/Xample/Meteor-Angular-Bootstrap-Boilerplate/pull/1

It's a workaround but it looks like it's the current way to handle this situation:
https://github.com/angular/angular.js/issues/4957
https://github.com/angular-ui/ui-router/issues/679
http://stackoverflow.com/questions/25334652/stateprovider-in-angularjs-not-rendering-the-ui-view

I think the workaround is simple and not intrusive so I prefer this solution then the one @netanelgilad suggested as it's more inline with the current state of Angular.

I can maybe add this workaround to the tutorial, do you think I should?
