### ISSUE TITLE
showing loading/processing indicator for $meter.call() with before/after hooks

### ISSUE THREAD

**Issue by dohomi** [Urigo/angular-meteor#278]
Hi Guys,

would like to know if there is a convenient way to show a loading/processing indicator if any ```$meteor.call()```is being fired. Would be great if there would be a kind of ```onBefore```and ```onAfter```hook to set inside of a Provider on ```module.run```. Currently I resolve this with:
```
indicator.show();
$meteor.call().then(function(){ ... indicator.hide()},function(error){indicator.hide})
```

Cheers and thanks for this great package.

**Comment by netanelgilad** [comment]
Currently, there is no better way to this than what you described.
But adding a provider with hooks similar to the idea of $httpProvider, is pretty awesome.
$httpProvider uses interceptors which could be useful to for method calls but i'm not sure that's how we should implement it.
@dohomi do you want to show the indicator for every method call? no matter where is originated from? or do you to do that only for certain calls?

**Comment by dohomi** [comment]
@netanelgilad I would have one default loading indicator for all calls - its like a loading spinner over the whole page - similar like my success ```toast```message https://material.angularjs.org/#/demo/material.components.toast.

I think in most CRUD usecases the user-interface should be blocked as long as the database is being written, otherwise weird non-complete or non-validate states can happen. 

Additionally an option to disable the hook would be nice as well - for having a custom handling on specific method calls.

**Comment by Urigo** [comment]
Thanks really cool!
Would love a pull request that does something similar to Angular http interceptors.

**Comment by dohomi** [comment]
I'm very new to the Angular world, will try to check out the docs how the interceptors are done. Something similar would be great for subscriptions which are used in ui-states or inside of any controller.

**Comment by Urigo** [comment]
Maybe it's better to solve it on the Meteor level before creating an Angular specific code?
Then on top of that add some kind of wrapper for Angular....

Here are 2 related issues that if they will be solved, we can you those packages for that:
https://github.com/hitchcott/meteor-method-hooks/issues/3
https://github.com/Workpop/meteor-method-hooks/issues/1

**Comment by pbastowski** [comment]
Have a look at 

https://github.com/pbastowski/rest-call

And @MeteorMethod in

https://github.com/pbastowski/angular2-now/blob/master/README.md

Both @RestCall and @MeteorMethod annotations allow you to specify "spinner" and before/after hooks.

**Comment by Urigo** [comment]
@pbastowski don't you think a solution more similar to `Angular http interceptors` will be more general?

**Comment by pbastowski** [comment]
@Urigo More general, perhaps. But I don't think that makes it necessarily better or easier to use. I think we could expose a general "low-level" api, similar to `Angular's http interceptors`, and then add "sugar" around it to make it much nicer to use.

Since talk is cheap, let's have a look at an example of how one might configure angular's http interceptors to turn the spinner on and off for each $http call, versus the angular2-now way of doing it. Let's assume that `spinner` is defined somewhere already and that it exposes `show()` and `hide()` methods.

### Angular Interceptors
```javascript
app.config(function($httpProvider, $provide) {

  $provide.factory('myHttpInterceptor', function($q) {
    return {
      'request': function(config) {
        spinner.show();
        return config;
      },

      'requestError': function(rejection) {
        spinner.hide();
        return $q.reject(rejection);
      },

      'response': function(response) {
        spinner.hide();
        return response;
      },

      'responseError': function(rejection) {
        spinner.hide();
        return $q.reject(rejection);
      }
    };
  });

  $httpProvider.interceptors.push('myHttpInterceptor');
});

// Service
app.factory('greatService', function ($http) {
    return {
        getUser: function getUser(id) {
            return $http.get('http://jsonplaceholder.typicode.com/users/' + id);
        }
    }
});

// Call it somewhere 
greatService.getUser(1).then( function(data) { console.log(data.data) } );
```


### Now, using a @RestCall
```javascript
// Configure spinner
restConfig({ spinner: spinner })

// Service
@Service('greatService')
class greatService {
  @RestCall('http://jsonplaceholder.typicode.com/users/${id}')
  getUser() { }
}

// Call it somewhere 
greatService.getUser(1).then( data => console.log(data.data) );
```

**Comment by Urigo** [comment]
I think this feature should go in a separate package..
I would love to accept any pull requests that will provide that new package an easier API.
Closing for now
