### ISSUE TITLE
$meteor.requireUser() doesn't work at all

### ISSUE THREAD

**Issue by goooseman** [Urigo/angular-meteor#283]
In [the 8th step of tutorial](http://angularjs.meteor.com/tutorial/step_08) it is said, that I can use
```
resolve: {
    "currentUser": ["$meteor", function($meteor){
      return $meteor.requireUser();
    }]
  }
```
to restrict unauthorized users from any route. But in my application it doesn't work at all. The most interesting part, that in [angular meteor demo application](http://socially-step08.meteor.com/parties) it doesn't work too. I can get to any route, when I'm not logged in.

OK, I've tried to cope with this problem for myself. I've wrote the following code (coffeescript):

```
$stateProvider.state('signIn',
      url: '/sign-in'
      controller: 'signInCtrl'
      templateUrl: 'client/pages/users/views/signIn.html'
    ).state('home',
      url: '/'
      controller: 'indexCtrl'
      templateUrl: 'client/pages/index/views/index.html'
      resolve:
        currentUserExists: currentUserExists
    )

currentUserExists = ['$q', '$timeout', '$state', '$rootScope', '$log', ($q, $timeout, $state, $rootScope, $log) ->

      if $rootScope.currentUser
    # Resolve the promise successfully
        $q.when()
      else
    # The next bit of code is asynchronously tricky.
        $timeout ->
    # This code runs after the authentication promise has been rejected.
    # Go to the log-in page
          $state.go 'signIn'
          return
        # Reject the authentication promise to prevent the state from loading
        $q.reject()
    
]

```

It checks, if currentUser exists. If not, redirect to singIn page.
The problem is, that on site initial load (when I refresh a page or when I type address in address bar), ``` $rootScope.curentUser ``` returns ``` undefined ``` (not  ``` null ``` ), but when I navigate through site, everything is OK. So I've edited code to wait for one second, if is the first load. But this code is really ugly:
```

currentUserExists = ['$q', '$timeout', '$state', '$rootScope', '$log', ($q, $timeout, $state, $rootScope, $log) ->
  if window.notFirstTime == true
    $q.when()
  else
    $timeout ->
      window.notFirstTime = true
      if $rootScope.currentUser
    # Resolve the promise successfully
        $q.when()
      else
    # The next bit of code is asynchronously tricky.
        $timeout ->
    # This code runs after the authentication promise has been rejected.
    # Go to the log-in page
          $state.go 'signIn'
          return
        # Reject the authentication promise to prevent the state from loading
        $q.reject()
    , 1000
]

```

So the questions are:
* Why ``` $meteor.requireUser() ``` doesn't work as excepted?
* Why ``` $rootScope.currentUser ``` returns undefined on site load?

**Comment by Urigo** [comment]
@goooseman can you share your versions file?
Maybe you are using an older version?

**Comment by goooseman** [comment]
@Urigo, thank you for your answer. 
To represent this issue on blank project, I've created a blank project on latest meteor v1.1.0.2 with latest meteor-angular v0.8.3. And realized where the problem is.
It can be viewed [here](http://require-user-bug.meteor.com) or see source code [on GitHub](https://github.com/goooseman/meteor-angular-require-bug-error).
In this project I've created two simple views: '/allow-all' which is has to be accessible to everybody, and restrict, which can be viewed only by authenticated users. 
If we open '/allow-all' and then click '/restrict' link, everything works fine: we are restricted.
But when we directly pass [require-user-bug.meteor.com/restrict](http://require-user-bug.meteor.com/restrict) and press enter in our address bar, the page loads and doesn't redirect at all. 
And my versions file can be viewed [here](https://github.com/goooseman/meteor-angular-require-bug-error/blob/master/.meteor/versions).

Looking forward for your help.

**Comment by Urigo** [comment]
@goooseman that's very interesting, might be a ui-router thing..
can you test that without Meteor and just return a rejected promise and see if it also happens there?

**Comment by goooseman** [comment]
@Urigo it seems it is a ui-router bug
I've created one more [route](http://require-user-bug.meteor.com/check-without-meteor) in my demo app, which is restricted with this code:
```
justRestrict = ['$q', ($q) ->
  $q.reject()
]
```
When I click a link from main page, it is restricted, but if i type ``` http://require-user-bug.meteor.com/check-without-meteor ``` in browser it opens the link. The most interesting fact, that ``` ui-view ``` content is not shown, but there is no redirect.

**Comment by netanelgilad** [comment]
Hey @goooseman, I Pull Requested your repo with a fix. Check it out :)
https://github.com/goooseman/meteor-angular-require-bug-error/pull/1

**Comment by goooseman** [comment]
@netanelgilad wow, changing $location to $state really works. You are a lifesaver. I will update api reference's example to use $state instead of $location.

**Comment by netanelgilad** [comment]
The other issue was the arguments to the stateChangeError function which caused the error object to actaully be the fromState (cause it is the fourth argument that ui-router sends in the broadcast..). =]
