### ISSUE TITLE
Exception while simulating the effect of invoking '/todos/update' 

### ISSUE THREAD

**Issue by padsbanger** [Urigo/angular-meteor#286]
Hello, 

I am building a TODO application following the tutorial here: 
http://angularjs.meteor.com/tutorial/step_06

I have an error while I am trying to access a single todo item:

![screen shot 2015-04-11 at 14 51 48](https://cloud.githubusercontent.com/assets/471029/7101431/78d8cb8a-e05a-11e4-9b87-8c98e5e52b84.png)

Here is my app.js

```js

Todos = new Mongo.Collection('todos');

if (Meteor.isClient) {
  var todo = angular.module('todo', ['angular-meteor', 'ui.router']);

  todo.config(['$urlRouterProvider', '$stateProvider', '$locationProvider', function($urlRouterProvider, $stateProvider, $locationProvider) {
    $locationProvider.html5Mode(true);

    $stateProvider
      .state('todos', {
        url: '/todos',
        templateUrl: 'todos-list.ng.html',
        controller: 'todoListController'
      })
      .state('todoDetails', {
        url: '/todos/:todoId',
        templateUrl: 'todo-details.ng.html',
        controller: 'todoDetailsController'
      });

    $urlRouterProvider.otherwise("/todos");

  }]);

  todo.controller('todoListController', ['$scope', '$meteor', function($scope, $meteor) {
    $scope.todos = $meteor.collection(Todos);

    $scope.addTodo = function(todo) {
      todo.date = new Date();
      $scope.todos.save(todo);
    };

    $scope.remove = function(todo) {
      $scope.todos.remove(todo);
    };

    $scope.clear = function() {
      $scope.todos.remove();
    };

  }]);

  todo.controller('todoDetailsController', ['$scope', '$stateParams','$meteor', function($scope, $stateParams, $meteor) {
    $scope.todoId = $stateParams.todoId;
    $scope.todo = $meteor.object(Todos, $stateParams.todoId);
  }]);

}
```

My index.html:

```html
<head>
  <base href="/">
</head>

<body>
  <div ng-app="todo">
    <h1>
      <a href="/todos">Home</a>
    </h1>
    <div ui-view></div>
  </div>
</body>

```

My todo-list.ng.html

```html
<form>
  <label for="name">Name</label>
  <input type="text" id="name" ng-model="newTodo.name">
  <label for="priority">Priority</label>
  <input type="text" id="priority" ng-model="newTodo.priority">
  <button class="btn btn-primary" ng-click="addTodo(newTodo)">Add Todo</button>
</form>
<ul>
  <li ng-repeat="todo in todos track by $index">
    <a href="/todos/{{todo._id}}">{{todo.name}} {{todo.priority}} {{todo.date | date}}</a>
    <button class="btn btn-primary" ng-click="remove(todo)">Done</button>
  </li>
  <h4>Tasks to do: {{todos.length}}</h4>
</ul>
<button class="btn btn-primary" ng-click="clear()">Clear list</button>

```

And todo-details.ng.html

```html
<h1>Your to do</h1>
<input type="text" ng-model="todo.name">
<input type="text" ng-model="todo.priority">
```

I have no idea, what am I doing wrong, following the official tutorial step by step, just replace parties with todo, honestly.

Any ideas ?

**Comment by stromhalm** [comment]
Same here! Any help would be appreciated

**Comment by anchoo2kewl** [comment]
I have the same issue and I noticed that the downgrade to angular 0.8.2 fixes this. However, I also noticed that when I downloaded the code and ran meteor, it worked since the meteor version was 1.05. When I upgraded meteor to 1.1.0.2, I got the same issue for the update. Another interesting thing is when we add buttons for save and reset as the tutorial suggests, it still throws the error but actually saves the content.

**Comment by Urigo** [comment]
Thanks guys, I've seen the problem. working on a solution right now

**Comment by slopSurfer** [comment]
Thanks very much Uri.




Love your work.




I experienced this issue also after updating Meteor and angular-meteor yesterday but didn’t have time to investigated.








—

**Comment by eduardoRoth** [comment]
Meteor 1.1.0.2 update seems to have an effect on angular-meteor.
I was following the tutorial but, after the update, the code no longer worked. Even when I cloned the last step repo it was getting a couple of errors:

When I loaded the page:
![image](https://cloud.githubusercontent.com/assets/5419161/7106788/cadae7f6-e113-11e4-9a35-d76b65e50645.png)

And then when I tried to do anything:
![image](https://cloud.githubusercontent.com/assets/5419161/7106790/dc5bda6c-e113-11e4-8f5c-b1e30c456d65.png)

**Comment by netanelgilad** [comment]
hey @eduardoRoth, these are problems with the 0.8.3 version.
We are working on a fix right now, and we will release a new version..

**Comment by Urigo** [comment]
Solved in 0.8.4

**Comment by ambujpunn** [comment]
@Urigo I'm having some what of the same problem but seeing this as the error: ```Meteor.makeErrorType.errorClass {error: 409, reason: "MinimongoError: can't set field named $$hashKey", details: undefined, message: "MinimongoError: can't set field named $$hashKey [409]", errorType: "Meteor.Error"…}```

Do you know what can be causing this?

**Comment by ambujpunn** [comment]
Ahh, I updated it to 0.8.10 and it works! Out of curiosity, what was the problem @Urigo?

**Comment by Urigo** [comment]
@ambujpunn we used to clean $$hashkey only 2 levels down before saving to the server, now we are cleaning it all the way:
https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-meteorCollection.js#L32

**Comment by seanfcarroll** [comment]
I had the same issue, and fixed it by updating to 0.9.1

```
meteor update
.
.
urigo:angular                  upgraded from 0.8.5 to 0.9.1
```

I had forked the https://github.com/Urigo/meteor-angular-socially project, which had an older version of angular-meteor.

Excellent project, by the way!

**Comment by batjko** [comment]
I am getting this same error with the example app, and apparently I am on the latest version(s), though on Windows:
![image](https://cloud.githubusercontent.com/assets/7287076/9464000/697ab3a0-4b18-11e5-9d33-86906d55b0d2.png)
![image](https://cloud.githubusercontent.com/assets/7287076/9464020/8dc5de38-4b18-11e5-87fb-f52c3a901b27.png)

The insert of the new todo task seems to succeed, but the error gets thrown nonetheless.

**Comment by Urigo** [comment]
@batjko can you share your repo?

**Comment by batjko** [comment]
@Urigo I'm afraid it's not on Github. Let me know what you'd like to see.

**Comment by Urigo** [comment]
can you send it to my personal mail?

**Comment by batjko** [comment]
So I've tried it again, after a laptop reboot and restarting Meteor in the project... I no longer see this error. 
It's a bit strange that it turned up in the first place, since all the packages were on the latest version, but apparently it's all good now.
