### ISSUE TITLE
Meteor 1.1.0.2 Update seems to break angular-meteor

### ISSUE THREAD

**Issue by eduardoRoth** [Urigo/angular-meteor#290]
After I've updated Meteor to version 1.1.0.2 angular-meteor stopped working on my project (I was following the tutorial and had just finished step 13).

I cloned the last step repo, to check if it was somehow my project, but I got the same error when I tried to do anything on it.

On load the errors I got were:
![image](https://cloud.githubusercontent.com/assets/5419161/7106831/ab048080-e114-11e4-899d-4829f45d4821.png)

And after any click I kept getting this error:
![image](https://cloud.githubusercontent.com/assets/5419161/7106834/bb0a063a-e114-11e4-9e27-93d4d3b24752.png)

Hope this helps to find the error.

**Comment by eduardoRoth** [comment]
As netanelgilad replied in [issue #286](https://github.com/Urigo/angular-meteor/issues/286#issuecomment-92104837) this is caused by angular-meteor 0.8.3

**Comment by Urigo** [comment]
There is a new 0.8.4 version which solves that issue.
Thanks for the issue and please reopen in case it persists
