### ISSUE TITLE
$meteor.object helpers use in controller

### ISSUE THREAD

**Issue by goooseman** [Urigo/angular-meteor#292]
I have a model with a helper.
For example:
```
@Tests = new (Mongo.Collection)('tests')

Tests.helpers {
  helloWorld: ->
    "#{@hello} #{@world}"
}
```
And a controller with ``` $scope.test = $meteor.object(Tests, $stateParams.testId) ```.
When I call a ``` helloWorld() ``` helper from a view (``` {{test.helloWorld()}}```), everything works fine.

But when I call it from my controller (```$scope.hello = $scope.test.helloWorld()```), it breaks the whole page, but only when the page is accessed after a refresh.

I created an example in my previous demo app. ([Repo](https://github.com/goooseman/meteor-angular-require-bug-error)). If I open [this](http://require-user-bug.meteor.com/tests) page and click on any test's link, everything works fine. But if I refresh that page (or access it with [direct link](http://require-user-bug.meteor.com/tests/pNraLmFFexD4iZyJ2)), it throws me an error:
``` TypeError: e.test.helloWorld is not a function ```

This is beacuse ``` $meteor.object() ``` is propagating asynchronously and it doesn't have any helper functions on startup. 

The only workaround, I have found for the moment, is to use $timeout for one second, on using object's helper functions.

**Comment by netanelgilad** [comment]
hey @goooseman,
I checked the site you linked and I'm not getting any errors in the tests page, I actually get the list with the hello world. I tried refreshing multiple times.
Does it happen to you all the time or is this some kind of race condition? what browser are you using?

**Comment by goooseman** [comment]
@netanelgilad, thanks for your answer.
the problem is not on the tests page, but on the individual test page. Click on the any of hello world links and then refresh the page or just click [this](http://require-user-bug.meteor.com/tests/pNraLmFFexD4iZyJ2) link.

**Comment by netanelgilad** [comment]
The problem was that the subscription was only done on the tests page and when you access a test page directly, the subscription doesn't happen.
It is good practice to have your subscriptions in a resolve to make sure the data exists before the route is loaded. Check out my PR.
have fun :)

**Comment by goooseman** [comment]
@netanelgilad thanks, this really works. So maybe we have to mention that in docs or tutorial?
And as I can understand, it is a good practice to always (even if I don't use helpers) subscribe in route resolve, isn't it?

**Comment by netanelgilad** [comment]
Yep, it is always a good practice as I see it.
It is a good point about mentioning it in the tutorial. @Urigo ?

**Comment by Urigo** [comment]
@goooseman can you please look into step 9 and come up with the best place to put it?
https://github.com/Urigo/angular-meteor/edit/master/.docs/angular-meteor/client/views/steps/tutorial.step_09.tpl
I always believe the best explanations come from the person who encountered it :)
