### ISSUE TITLE
Including a Changelog.md file

### ISSUE THREAD

**Issue by dohomi** [Urigo/angular-meteor#294]
Hi Guys,

Thanks for this great package. Would be great if you could publish a ```Changelog.md``` file to track what changes are waiting in new versions. Cheers

**Comment by netanelgilad** [comment]
Awesome idea of course @dohomi.
@Urigo wanna start one?

**Comment by Urigo** [comment]
@dohomi @netanelgilad what's the difference between that and https://github.com/Urigo/angular-meteor/releases

**Comment by dohomi** [comment]
@Urigo thats a good one :) haven't found this link so far
