### ISSUE TITLE
Onsen UI

### ISSUE THREAD

**Issue by fullhdpixel** [Urigo/angular-meteor#295]
Referring to this issue I posted on stackoverflow:

http://stackoverflow.com/questions/29636191/meteor-angular-onsen-ui-jquery-loading-order

Could you help me resolving this issue?

Thanks for this awesome package!

**Comment by fullhdpixel** [comment]
Could you provide a quick and dirty workaround to avoid errors caused by Meteor's integrated jQuery library?

**Comment by Urigo** [comment]
isn't the solution I linked in your answer worked?

**Comment by Urigo** [comment]
@fullhdpixel looking deeper into that, this is an Onsen UI issue.
It is a clear problem if Jquery breaks your library and here is another example of that:
https://github.com/OnsenUI/OnsenUI/issues/529
