### ISSUE TITLE
Current user keep in the users collection search result.

### ISSUE THREAD

**Issue by keith3** [Urigo/angular-meteor#308]
There is a user manage module in my application, I added **account-base** package, search operation works well with others collection but not users collection, uses search result always contain the current user. (same code with your tutorial)

Meteor version: Meteor 1.1.0.2
Packages: 
- accounts-base                          --- 1.2.0        
- accounts-password                   --- 1.1.1         
- angularui:angular-ui-router       --- 0.2.13_3   
- meteor-platform                        --- 1.2.2        
- tmeasday:publish-counts          --- 0.3.7        
- twbs:bootstrap                           --- 3.3.4        
- urigo:angular                             --- 0.8.4        
- urigo:angular-utils-pagination    --- 1.0.5

**Comment by Urigo** [comment]
@keith3 can you share your code?

**Comment by Urigo** [comment]
Closing, please re-open if there is a reproduction
