### ISSUE TITLE
Tutorial with ControllerAs syntax

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/angular-meteor#309]
Hi Guys, 

I tried completing the tutorial with somewhat changed examples, using controllerAs syntax as proposed by John Papa's style guide. 
Everything went well until the step 12. I'm stuck implementing pagination with controllerAs syntax. 
The `urigo:angular-utils-pagination` doesn't seem to work well in that setup. 
The directive is rendered but the pagination itself doesn't seem to be working. 
Later on in the step 12, the getReactively method seems to require `$scope` as well. 
Here 
```
angular.module('socially').controller('PartiesListCtrl', 
  [ '$meteor', '$scope',
  function($meteor, $scope){
    var vm = this;

    vm.page = 1;
    vm.perPage = 3;
    vm.sort = { name: 1 };

    vm.parties = $meteor.collection(function() {
      return Parties.find({}, {
          sort : $scope.getReactively('sort')
        });
    });

/*    $meteor.subscribe('parties', {
      limit: parseInt(vm.perPage),
      skip: parseInt((vm.page - 1) * vm.perPage),
      sort: vm.sort
    }).then(function(){
      vm.partiesCount = $meteor.object(Counts ,'numberOfParties', false);
    });
*/
    $meteor.autorun($scope, function() {

  $meteor.subscribe('parties', {
    limit: parseInt($scope.getReactively('perPage')),
    skip: (parseInt($scope.getReactively('page')) - 1) * parseInt($scope.getReactively('perPage')),
    sort: $scope.getReactively('sort')
  }).then(function(){
    vm.partiesCount = $meteor.object(Counts ,'numberOfParties', false);
  });

});

    vm.pageChanged = function(newPage) {
      vm.page = newPage;
    };

    vm.remove = function(party){
      vm.parties.remove(party);
    };

    vm.removeAll = function(){
      vm.parties.remove();
    };
  }
]);
```
The commented out code with `vm.` in `$meteor.subscribe` seems to work, however, when I wrap in `$meteor.autorun` as it requires `$scope`, doesn't play well. 

Comments, please?

**Comment by MilosStanic** [comment]
For the sake of complete picture, here's the view: 

```
<form layout="row">
  <div flex="25" layout="column">
    <md-input-container>
      <label>Name</label>
      <input ng-model="plc.newParty.name">
    </md-input-container>
    <md-input-container>
      <label>Description</label>
      <input ng-model="plc.newParty.description">
    </md-input-container> 
    <md-checkbox ng-model="plc.newParty.public">
      Public      
    </md-checkbox>
    <md-button ng-click="plc.newParty.owner=$root.currentUser._id; plc.parties.push(plc.newParty)">Add</md-button>
  </div>
  <div flex="75">
  </div>
</form>
<md-content>
<md-list layout="column">
  <md-list-item dir-paginate="party in plc.parties | itemsPerPage: plc.perPage" total-items="plc.partiesCount.count">    
    <a href="/parties/{{party._id}}">{{party.name}}</a>
    {{party.description}}    
    <md-button ng-click="plc.remove(party)">X</md-button>
  </md-list-item>
</md-list>
<dir-pagination-controls on-page-change="plc.pageChanged(newPageNumber)"></dir-pagination-controls>
</md-content>
```

Note: I'm using angular-material, so I'm using `md-list` instead of `ul-li`

**Comment by Tallyb** [comment]
off topic - can we enahnce the tutorial with addign angular material?

**Comment by MilosStanic** [comment]
I would also like to know how to modify Meteor's login/register etc. templates to use angular material. Is it possible to override the default templates?

**Comment by Urigo** [comment]
@MilosStanic 
1. can you share a repo of your try?  it will be easier for me to look and solve
2. About changing templates, of course!  you have all the services here that you can use: http://angularjs.meteor.com/api/auth

@MilosStanic and @Tallyb actually it will be really cool to create accounts:ui with angular-material that gives you the forms out of the box!! 

Would love your help on that

**Comment by MilosStanic** [comment]
@Urigo sorry, I deleted the thing because it went totally berserk on me. The list and details views were displayed at the same time on the same page in browser, and nothing was working as it should. 
So I started the tutorial all over again without ControllerAs syntax and angular-material.

However, now at the step 12, I see another buggy behaviour: when I open up a party detail page, and click cancel button, when it returns to the list view, the pagination no longer works. I have to refresh browser page to make it work again. 

Regarding the angular-material templates, I would be glad to help. I am seriously planning in making an app using angular-meteor with angular-material, so I will need them anyway.

When I finish the tutorial, I will try reimplementing it with ControllerAs syntax and see what happens. Then I will upload it to github and we'll try to debug it, if you're up to it. 

After that I will redo the whole thing with angular-material. 

I see that $scope.getReactively relies on $watch, so I guess it can't fit to ControllerAs syntax. It would be an interesting excercise to make it all work.

**Comment by Tallyb** [comment]
@Urigo @MilosStanic I am opening a seperate issue for the material login ui

**Comment by Urigo** [comment]
@MilosStanic it looks like the subscription hasn't stopped...
have you got to the section of the chapter about 'Stopping a subscription'?

**Comment by MilosStanic** [comment]
@Urigo yes, thank you, that was it. Sorry.
