### ISSUE TITLE
angular.element() can not be called with a selector, because angular:angular does not depend and load jQuery like angularjs:angular did 

### ISSUE THREAD

**Issue by smoke** [Urigo/angular-meteor#314]
angular.element() uses jQuery if it is loaded prior angular itself, if jQuery is not loaded first it uses jqLite.
angularjs:angular did depend on jQuery and loaded it first, but with angular:angular this is not the case.

Change to angular:angular was introduced since v0.8.5 and this commit 8b0acbe.

So the issues is that ```angular.element()``` on its turn does not support arbitrary selectors and code like ```var backgroundColor = angular.element('body').css('background-color')``` would fail with:
```
Uncaught Error: [jqLite:nosel] Looking up elements via selectors is not supported by jqLite! See: http://docs.angularjs.org/api/angular.element
http://errors.angularjs.org/1.3.15/jqLite/nosel
```

A quick workaround would be to change ```angular.element('body').css('background-color')``` to ```angular.element(document).find('body').css('background-color')``` - this effectively uses the .find() method of a wrapped element, however this could be a problem for huge libraries.

As much as I like jQuery I would recommend not depending on it, since you have angular in place.

So the only problem here is - how to provide choice to people stuck with jQuery? In other words - how to effectively load jQuery prior angular, if this is required?

**Comment by Urigo** [comment]
With weak dependency.   we did that on angularjs:angular.

@dotansimha can you publish another version with that?

**Comment by dotansimha** [comment]
@smoke  @Urigo 
Done. published it under "1.3.15_1".

**Comment by smoke** [comment]
@Urigo Just a small thing to confirm -adding jQuery as weak dependency solves the case completely - in other words if there is jQuery it loads it prior angular and uses it, if not it just loads angular, right?

**Comment by Urigo** [comment]
exactly.
released 0.8.6 just for that

**Comment by smoke** [comment]
Great! 
One more thing - I am a bit confused with all the new packages around, so I would better ask - isn't angularjs:angular not needed any more and why is it in cc11ae0?
```
-angular:angular@1.3.15
+angular:angular@1.3.15_1
+angularjs:angular@1.3.15
```

**Comment by Urigo** [comment]
yes it is not need to be anymore, it is probably because you have another package that depends on that.
try meteor update and check which other package depend on that

**Comment by smoke** [comment]
Sorry, I have pointed wrong commit hash - the hash is 23533b9 where you have just added angularjs:angular@1.3.15 yourself in the new release 0.8.6 :)

**Comment by Urigo** [comment]
ohhh this is strange
but it's ok, it won't add it to your own app (I've checked with the tutorial but make sure as well)

**Comment by viniciusferreira** [comment]
call jquery library before angularjs
