### ISSUE TITLE
Material Login Buttons

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular-meteor#315]
Create account-ui login buttons in material design, based on angular-material. 
My initial issue is how to get the angular-material package to be included in meteor. 
@Urigo  can you suggest the best method? 
The following repository has material login partials that we might want to use: 
https://github.com/Tallyb/df-material
The relevant partials are under src/components/auth/partials

@Urigo do you have the material socially repo that you have showed in the last meetup?

**Comment by Urigo** [comment]
@Tallyb there is already a meteor-angular-material package:
https://github.com/planet-training/meteor-angular-material/

as for Login Buttons, I think this should be a community effort.
I would of course love to help but I don't think it should be an open issue....

**Comment by Urigo** [comment]
even though you just need to write regular angular-material after adding this package, here is an example to use:
https://github.com/madvas/meteor-angular-material-todomvc

**Comment by Tallyb** [comment]
Great news. This is brand new. I was looking to one couple of weeks ago. (so new - the readme does not even contain the package add...)
