### ISSUE TITLE
WARNING: Tried to load angular more than once

### ISSUE THREAD

**Issue by eeandrew** [Urigo/angular-meteor#336]
Here is my folder structrue
client
  ---app.js
  ---index.html
  ---index.ng.html
Their content is the same as in step__00.
I got this error in Chrome.

**Comment by Urigo** [comment]
can you share your meteor/.version file please?

**Comment by eeandrew** [comment]
angular:angular@1.3.15_1
autopublish@1.0.3
autoupdate@1.2.1
base64@1.0.3
binary-heap@1.0.3
blaze@2.1.2
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
check@1.0.5
dburles:mongo-collection-instances@0.3.3
ddp@1.1.0
deps@1.0.7
ejson@1.0.6
fastclick@1.0.3
geojson-utils@1.0.3
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
id-map@1.0.3
insecure@1.0.3
jquery@1.11.3_2
json@1.0.3
lai:collection-extensions@0.1.3
launch-screen@1.0.2
livedata@1.0.13
logging@1.0.7
meteor@1.1.6
meteor-platform@1.2.2
minifiers@1.1.5
minimongo@1.0.8
mobile-status-bar@1.0.3
mongo@1.1.0
observe-sequence@1.0.6
ordered-dict@1.0.3
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
routepolicy@1.0.5
session@1.1.0
spacebars@1.0.6
spacebars-compiler@1.0.6
templating@1.1.1
tracker@1.0.7
ui@1.0.6
underscore@1.0.3
urigo:angular@0.8.8
url@1.0.4
webapp@1.2.0
webapp-hashing@1.0.3

**Comment by Urigo** [comment]
You are good in terms of packaging..

Maybe your path is wrong?

can you share your index.html?

**Comment by Tallyb** [comment]
Is it needed to have both urigo:angular@0.8.8 and angular:angular@1.3.15_1 in project?

**Comment by Urigo** [comment]
urigo:angular@0.8.8 bring angular:angular@1.3.15_1 with it

**Comment by eeandrew** [comment]
app.js
```
angular.module('mainApp',['angular-meteor']);
```
index.html
```
<body>
	<div ng-app="mainApp" ng-include="'index.ng.html'"></div>
</body>
```
index.ng.html
```
<p>
	Hello World
</p>
```

**Comment by Urigo** [comment]
You need to place the full path:

    <div ng-app="mainApp" ng-include="'client/index.ng.html'"></div>

**Comment by eeandrew** [comment]
Wow. Thanks.

**Comment by Urigo** [comment]
np, good luck!
