### ISSUE TITLE
docs app

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular-meteor#337]
the docs app refer to a non existing package: urigo:angularmeteormarkdown

**Comment by Urigo** [comment]
it is a local package in the packages directory

I leave it there because it's not the best implementation...

**Comment by Tallyb** [comment]
I think I figured out the issue. Windows cannot create a folder with colon, hence "urigo:angularmeteormarkdown" is failing.

**Comment by Tallyb** [comment]
I embedded the markdown directive directly in directive and removed the package. Not that great. Let me know if I should make a PR for it.

**Comment by Urigo** [comment]
yes, if that make the site work on Windows then please do!

**Comment by Tallyb** [comment]
well, I fail to do it because of the above errors (and probably some lack of github knowledge). Either you can rename the directory to avoid the colon (if that is possible for packages, proabably is, as other packages did not have this issue), or just embed the markdown.js under the directives directory and remove the package from packages.

**Comment by cedric25** [comment]
To fix the problem when cloning the repo on Windows, I simply replaced "urigo:angularmeteormarkdown" with "urigo-angularmeteormarkdown".
Would that be ok? Should I make a PR?

**Comment by Urigo** [comment]
@cedric25 yes of course!

**Comment by Tallyb** [comment]
Thanks!
