### ISSUE TITLE
Performance problems on collection binding

### ISSUE THREAD

**Issue by rjbma** [Urigo/angular-meteor#339]
I', currently trying out `angular-meteor` (great job, by the way!), and I came across a performance  problem when binding to a collection. Searching for other issues here, I think the problem is almost fully explained in #208. 

In that issue, the solution is to disable autobind when using the collection binding mechanism. While that did solve the immediate problem, the thing is that (in my case, at least) the deprecated collection binding worked ok *with autobinding*.

I've set up a meteropad to demonstrate this: http://meteorpad.com/pad/Gis2QPghRgCaerAfo/Collections

Also, another weird problem (not referenced in #208) happens when using the new collection binding: when typing on one of the inputs, that input suddently loses focus, and we have to focus it again to continue typing. 

By the way, this doesn't seem to happen with every type of collection. Collections with simpler documents don't seem to be affected by this problem. That's actually why the JSON doc in my example is so convoluted...

**Comment by Urigo** [comment]
@rjbma the MeteorPad doesn't seem to be working, can you share a repo please?

**Comment by Urigo** [comment]
also with the inputs losing focus, I think I know the solution and want to make sure it works with your repo

**Comment by rjbma** [comment]
@Urigo I've created a repo at https://github.com/rjbma/collections-test with the test case.

However, testing it again, I can't really notice any perfomance differences between the two implementations. Maybe it was just some kind of problem with my local environment at the time..., so sorry about that!

Anyway, about the inputs losing focus - that still happen. It actually looks like some kind of reload; if you scroll down the page and edit one of the last inputs, not only that input will lose focus, the page will be scrolled back to the top.

**Comment by Urigo** [comment]
ok, I'm working on a nice solution for keeping the focus and not re-rendering elements. 
Will update soon

**Comment by Urigo** [comment]
@rjbma solved here: https://github.com/Urigo/angular-meteor/commit/159dca46c62dd8ebc3f29f3e02e73c126dab6231
Please check your code against master and let me know if you have problems
