### ISSUE TITLE
First change made to an item inside a meteorCollection after an update from server is not pushed to server

### ISSUE THREAD

**Issue by cnelson711** [Urigo/angular-meteor#345]
The first change to an array is only registered locally and not pushed to the server if I use a $meteor.collection and try to push to an array that is a member of an item in the collection (I'm NOT saving or removing a new party from the collection, but editing an array that is a member of a party), 

I've pasted my code below.

```
party.ng.js
============
angular.module('parties', ['angular-meteor', 'ui.router']);
angular.module('parties').controller('PartyController', function($scope, $meteor) {
    var ctrl = this;

    ctrl.newPartyName = "";
    ctrl.parties = $meteor.collection(Parties);

    ctrl.createParty = function() {
        ctrl.parties.save({
            name: ctrl.newPartyName,
            randomNumbers: []
        });
        ctrl.newLeagueName = '';
    };

    // Join a league (submit a request to join)
    ctrl.addToPartyArray = function(party) {
        party.randomNumbers.push(Math.random());
    };

    ctrl.removeFromPartyArray = function(party) {
        party.randomNumbers.splice(0, 1);
    };
});

index.ng.html
================
<div ng-controller="PartyController as partyCtrl">
    <ul>
        <li ng-repeat="party in partyCtrl.parties">{{party.name}}
            <p ng-repeat="num in party.randomNumbers">{{num}}</p>

            <button type="submit" ng-click="partyCtrl.addToPartyArray(party)">Add Random Num</button>
            <button type="submit" ng-click="partyCtrl.removeFromPartyArray(party)">Remove Random Num</button>
        </li>
    </ul>

    <form name="createPartyForm" ng-submit="createPartyForm.$valid && partyCtrl.createParty()" novalidate>
        <input ng-model="partyCtrl.newPartyName" type="text" placeholder="Party Name" required>
        <button type="submit" ng-class="{ disabled : !createLeagueForm.$valid }">Create Party</button>
    </form>
</div>
```

**Comment by cnelson711** [comment]
You can see the issue if you open two browser windows to http://issue345.meteor.com and click the Add/Remove Random Number buttons.

**Comment by lukavent** [comment]
Did you subscribed to the collection somewhere?
I don't see any kind of a subscription.

Please check the example in docs: http://angular-meteor.com/api/meteorCollection

In your case it should be something like

      // Bind without auto-save all todos to $scope.notAutoTodos
     ctrl.parties = $meteor.collection(Parties).subscribe("parties");

Did that helped?

**Comment by cnelson711** [comment]
I'm using the autopublish package in the example (there's no need for a subscribe method if my server publishes nothing, right?).  In anycase, I tried adding the subscribe to no avail.

The problem may be in angular.js itself, or in the way that angular-meteor uses angular.js to watch values.  If angular.js doesn't have the previous value set, than it calls the function registered with watch with the current value twice instead of the previous value and the current value (thus angular-meteor's arraydiff thinks there are no changes).

```
Line 14308 of angular.js
watch.fn(value, ((last === initWatchVal) ? value : last), current);
```

I can dig deeper.

**Comment by rgnevashev** [comment]
http://meteorpad.com/pad/22osq6YWY2poiu3KB/Copy%20of%20Collections

im confirm, The first change not pushed to the server... before hook not execute...

**Comment by Urigo** [comment]
@cnelson711 I think I understand to problem.
Hopefully tomorrow I will ship a fix

**Comment by cnelson711** [comment]
Sweet.  You probably know more than I do, but I think it has something to do with:

```
Line 256
angular-meteor-meteorCollection.js

if (oldItems == 'UPDATING_FROM_SERVER')
              oldItems = realOldItems;

if (newItems !== oldItems) {
              diffArray(oldItems, newItems, {
```

Stepping through when I add a new item, realOldItems looks exactly the same as newItems (though they don't pass the !== operator)... I feel like realOldItems is supposed to be equal to the previous value of the items, and it's not.

**Comment by Urigo** [comment]
@cnelson711 solved, please try with the latest code.
Also, it will be great if you can add a test for it!
