### ISSUE TITLE
meteor.collection update function?

### ISSUE THREAD

**Issue by ambujpunn** [Urigo/angular-meteor#348]
Meteor provides an update function for the Meteor Collection object. Is there an equivalent for the $meteor.collection service? I only see ```save()```, ```remove()```, ```subscribe()```, but no update.

What would be a good way to specifically update an existing doc? Just calling ```save()``` on it?

**Comment by Urigo** [comment]
Yes exactly, save() is the equivalent but simpler version of update.
If you want to use update, you can call it directly on the Meteor collection

**Comment by ambujpunn** [comment]
Awesome thanks Uri!
