### ISSUE TITLE
Help: Stuck while including lodash

### ISSUE THREAD

**Issue by Brasilikum** [Urigo/angular-meteor#353]
Hey there,

Following the [Step 19](http://angular-meteor.com/tutorial/step_19) from the Tutorial, I tried to add my first Third-Party-Library.

My Steps:
1. Add package: `meteor add stevezhu:lodash`
2. Declare dependency: ```angular.module('groupExpense',['angular-meteor', 'ui.router', 'lodash']);```
3. Use in controller:
```js
angular.module('groupExpense').controller('ExpenseDetailCtrl', ['$scope', '$stateParams', '$meteor', 'lodash',
  function($scope, $stateParams, $meteor, lodash){
....
```

But what I get in the console of the browser is:
```js
Error: [$injector:modulerr] Failed to instantiate module groupExpense due to:
[$injector:modulerr] Failed to instantiate module lodash due to:
[$injector:nomod] Module 'lodash' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

I already checked [lodashes packages.js](https://github.com/stevezhu/meteor-lodash/blob/master/package.js) and it declares lodash as api.export:
```js
Package.onUse(function(api) {
	api.addFiles(['lodash.js', 'client.js'], 'client');
	api.addFiles('server.js', 'server');
	api.export('lodash');
	api.export('_');
});
```

What have I missed? Why cant't I import it?

Other then that, maybe it would be a good IDEA to have some kind of FAQ, forum etc for meteor-angular?

Cheers!

**Comment by cnelson711** [comment]
This doesn't seem like an issue with angular-meteor... I don't think Lodash defines an Angular module or factory, so it can't be dependency injected (nor does it seem like it needs to be - you're not going to create a new instance of anything from the library).

If 'Lodash' is similar to 'Underscore' (which it seems to be), than you don't need to use Angular's dependency injection, as _ should just be available globally.

Good luck.

**Comment by Tallyb** [comment]
Not sure where I saw it, but worked for me to put 
    _ = lodash;
In model directory.

**Comment by Urigo** [comment]
@Brasilikum can you share the repository of your package?

**Comment by Urigo** [comment]
Closing until we will understand more about the library
please re-open with more info

**Comment by Brasilikum** [comment]
You have been right indeed, *lodash* was available globally so I assigned it to _!
