### ISSUE TITLE
return value from $meteor.call

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular-meteor#357]
In socially there is a call to rsvp : 
     $meteor.call('rsvp', partyId, rsvp).then(
        function(data){
          console.log('success responding', data);
        },
 
data, however is undefined. I tried to return a value in meteor.methods rsvp as follow: 
                Parties.update(partyId, modifier, function (err, data) {
                    if (!err) return (rsvpIndex);
                });
But that does not seem to work either. 
What am I missing here?

**Comment by smoke** [comment]
The function where you return (rsvpIndex) return for the callback it self and not for the defined method.

You can try something like: 
```
var ret;
Parties.update(partyId, modifier, function (err, data) {
  if (!err) ret = rsvpIndex;
});
return ret;
```

**Comment by Tallyb** [comment]
@smoke Thanks Rado. However, it still prints success responding undefined. 
Any other idea?

**Comment by netanelgilad** [comment]
@smoke @Tallyb, the problem here is that the code running in the callback is asynchronous. That means that the return statement of the method happens before the callback actually gets called.
@Tallyb you can either use the synchronous version of update (without sending a callback) and then just return whatever you want after that, or you can go with the bit harder solution and add fibers to make the method wait for the callback...

**Comment by Tallyb** [comment]
@netanelgilad so this brings me to a closed issue that is popping its ugly head again - get the ID of a newly created item. In our beloved socially, if we want to jump to the party page right after pressing the add button on a new party. What is the best way of doing it? 
(BTW sorry I missed your talk on ng-conf IL, heard it was really good!)

**Comment by smoke** [comment]
@Tallyb you should check the docs http://docs.meteor.com/#/full/insert - if you don't pass a callback to Collection.insert, update, remove - *on server side* - *they block* and return required information. Collection.insert returns the id of the newly created object, that you can use accordingly.

**Comment by Tallyb** [comment]
@smoke. Yay, Rado. That worked. Blagodryia mlogo.

**Comment by smoke** [comment]
You are welcome :)
