### ISSUE TITLE
changing context

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular-meteor#358]
Not quite an issue, and probably more meteor related, but I would love help from anyone who is willing too. 
Let's assume an app like Trello, where my users has few boards and each board has quite few cards. The user is mostly on a single board and rarely changes context. 
The user  has access to all cards of their Trello board. However, it is only reasonable for the client to have locally the cards of current board, and upon switching context update to the cards of the newly selected board. 
The boards are stored in one mongo collection ('boards' - creative name); and all cards in a seperate collection ('cards') with the ID of the board. [If anyone thinking I am "stuck" in RDBMS era, I actually saw such a recommendation for Mongo as well]. 
Q1) Does that make sense? 
Assuming yes, here is my confusion: 
Q2) do I need to publish on server the specific board cards, or do I need just to subscribe from the client to the current board? how? 
Q3) what should be defined in the collection Model?

Thanks for help. 
PS - would be useful to enhance Socially to support some parent-child relationships.  This will enforce its value comparing to firebase... 
PS2 - valuable information from this thread will be compiled into a blog post for the angular-meteor site...

**Comment by Urigo** [comment]
@Tallyb I think this discussion is a better fit to https://forums.meteor.com/

As for your question, if you want to implement this, why not just create a publish function that gets as a parameter the cards (or cards range or board number and then calculate the cards range) and publish only those cards?

Would love to see contributions for the tutorial with more cases

**Comment by Tallyb** [comment]
https://forums.meteor.com/t/few-to-many-relationships-context-change/4837
