### ISSUE TITLE
(docs): Missing parameter in API reference

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular-meteor#365]
http://angular-meteor.com/api/meteorCollection
The API usage is showing 2 params but there are 3 in the arguments list. 
Not sure how to resolve.

**Comment by Urigo** [comment]
The third parameter is for CollectionFS, maybe we should add an explanation and example

**Comment by Tallyb** [comment]
OK. You may want also to note that the collectionFS usage example is also showing just 2 params. 
$meteorCollection(Images, false);
If not sending a function as first param - then the 3rd one is not required?
