### ISSUE TITLE
watch specific attribute - advice pls

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular-meteor#366]
I will use Socially example: assume that I want to resend mail invites to all participants in case the name of the party was changed (their inviation says "good vibes" but the party is now named "free drinks"). 
What is the best way of doing this? Can I get previous value without destroying current (i.e. not party.reset())?

**Comment by Urigo** [comment]
The best practice will be to change the value in a Meteor methods and then do to logic of getting the current name, getting the new name and sending the mail there
