### ISSUE TITLE
Is there any way to implement a pure AngularJS UI using AngularJS {{ ... }} template expressions?

### ISSUE THREAD

**Issue by rjsmith** [Urigo/angular-meteor#37]
Hi,

I am experimenting with angular-meteor, and learning meteor + AngularJS frameworks at the same time.  I would really appreciate your guidance on how to incorporate existing AngularJS packages, all of which include templates with the standard AngularJS {{ ... }} expression syntax.

I wanted to see if I could use the [ui-grid](https://github.com/angular-ui/ng-grid/) AngularJS module in my angular-meteor application.  To cut to the chase I simply downloaded the pre-built ui-grid-unstable.js and ui-grid-unstable.min.css files and added them to the `client/lib` and `client/stylesheets` folder.  Meteor did its job and built them into my app's index.html, great.  

I added `ui.grid` as a dependent module into my app, great:

``` javascript
angular.module('myMeteorApp',[
    'angular-meteor',
    'ui.router',
    'ui.grid'
]);

// Bootstrap AngularJS framework
Meteor.startup(function () {
    // Add ui.grid module as a dependency
    // NB: 25-Oct-2014: I don't really know what this does, but does seem to stop Angular for complaining during dependency injection
    angularMeteor.requires.push('ui.grid');

    angular.bootstrap(document, ['myMeteorApp']);
});
```

I then added a ui-grid attribute into my app page:

``` html
                <div class="row">
                    <div class="col-xs-12 my-grid" ui-grid="{ data: myList }"></div>
                </div>
```

And got this:

![image](https://cloud.githubusercontent.com/assets/678653/4779417/cb8a908a-5c2e-11e4-83f5-fc52a6e5fd35.png)

Because ui-grid uses standard AngularJS template syntax, and because angular-meteor switches {{ ... }} to [[ ... ]](to avoid clashing with Meteor Template subsystem), none of the ui-grid templates render correctly.

So, what are my real options?  

I took a look at the [meteor-ng-grid](https://github.com/davidyaha/meteor-ng-grid) project to see how it was done there.  It appears it [replaces some of the templates](https://github.com/davidyaha/meteor-ng-grid/blob/master/options.js) with modified versions that use [[ ... ]].  The ui-grid project has many such templates.  It doesn't seem viable in a real-world project to maintain angular-meteor equivalent versions of all of the templates, and update them by hand every time ui-grid bumps up versions.

One option might be to say I want to _only_ use AngularJS for all of the front-end of my application ... understanding that I can;t use any Blaze - based templates (e.g. the useful loginButtons that comes with the accounts-ui packages).  The huge advantage is that I could then access all of the AngularJS UI module ecosystem without any modification, whilst taking advantage of Meteor's reactivity and backend integration.  If I could turn off the bit of code in angular-meteor that switches the Angular expression syntax (by a config setting?) , what would happen?  Or, maybe the app could remove the (Template?) (Blaze?) packages from its standard set, so it doesn't try and get in the way .

I am happy to try a few experiments along these lines, but would really appreciate anyone's guidance, as I think you have already thought about these issues.

Also I apologise if this question is not really suitable for the github issues list.  Is there a mailing list or similar for angular-meteor ?

Thanks,

Richard

**Comment by Urigo** [comment]
Now you can!
https://github.com/Urigo/angular-meteor/releases/tag/0.6.0-alpha

**Comment by dandv** [comment]
CC @pscanf
