### ISSUE TITLE
Conditional templates if cordova or client  

### ISSUE THREAD

**Issue by AhmadEl-Banna** [Urigo/angular-meteor#374]
Hi there , I'm trying to build a system with mobile client and web client,both have completely different look and feel and requirements,and different views , it will be nice to have a away to attach cordova views alone ,if Meteor.isCordova and not include the web , and the other way around 
thank you

**Comment by dohomi** [comment]
@AhmadEl-Banna Don't you want to solve this inside packages? There you can add specific files based on your architecture:

http://docs.meteor.com/#/full/pack_addFiles

**Comment by AhmadEl-Banna** [comment]
@dohomi  I don't want to solve it with packages I just want the handler https://github.com/Urigo/angular-meteor/blob/master/plugin/handler.js 
to add the views conditionally if it Cordova add it to $templateCache of ionic and if it browser add it to $templateCache of angular-meteor 
or may be allow the developer to configure how  the handler locate the views and what module to add the views into it's templateCache , for cordova and for browser

**Comment by AhmadEl-Banna** [comment]
I'm new to meteor so I just can download the repo and modify the handler to locate the ng.html and add it to  angular-meteor  and locate the ion.html and add it to ionic 
and I add ionic as cordova only package 
http://stackoverflow.com/questions/28172446/can-i-add-a-meteor-package-for-a-single-platform

**Comment by cleor41** [comment]
Did you find a solution to this yet?

I'm not sure I understand your issue exactly but maybe you could attach the Meteor property isCordova to the $rootScope. If you put all of your html inside of directives you could conditionally include the appropriate directive. 

An issue with this approach might be that you get all of the client code for each scenario when you don't need half of it.

**Comment by Urigo** [comment]
We added a full tutorial step to show how to do it:
http://angular-meteor.com/tutorials/angular1/mobile-support-and-packages-isolation
