### ISSUE TITLE
$rootScope.currentUser undefined

### ISSUE THREAD

**Issue by vacarsu** [Urigo/angular-meteor#376]
Trying to use the currentUser object, but it seems to be undefined. Also when trying to interpolate it within a template it appears empty.

**Comment by Brasilikum** [comment]
Please provide more details. Where are you trying to access the `currentUser`? You could post some code for us to better understand

**Comment by vacarsu** [comment]
Not much of any code to show console.log($rootScope.currentUser) logs undefined, and yes I am injecting $rootScope.

**Comment by vacarsu** [comment]
If I sign in and go to the page it logs the current user. However, if I refresh the page then undefined get logged to the console.

**Comment by vacarsu** [comment]
Having played with angular-meteor a bit more, I'm completely at a loss as to why $rootScope is undefined. All I am trying to do is set a key value equal to the $rootScope.currentUser, then insert the new object into the database, it all works fine but the $rootScope value.

```javascript
$scope.submitComment = function (newComment) {
      var comment = {
        creator: $rootScope.currentUser,
        msg: newComment,
        createdAt: new Date(),
        parent: $stateParams.issueid
      }
      Comments.insert(comment)
      $scope.newComment = '';
    }
```

In this code snippet the creator field always get entered blank. I am injecting $rootScope into the controller.

**Comment by Urigo** [comment]
@vacarsu 

1. $rootScope.currentUser is binded into [Meteor.user](http://docs.meteor.com/#/full/meteor_user) which is undefined if the Users collection subscription is not ready yet...
to make sure it's there, you should do something like:
 
        $scope.$meteorSubscribe("users-subscription").then(function(){
           // Now $rootScope.currentUser should be defined
        });

2. In the templates you should use $root.currentUser to get the user.

Let me know if that didn't work for you or if you want to add something to the docs to make it more clear

**Comment by vacarsu** [comment]
@Urigo The above had no effect. And $root.currentUser doesn't work. the way I'm currently interpolating {{currentUser.profile.displayName}} works fine, but sometimes the image doesn't show up. See image in previous post. I don't think it's that the user subscription isn't ready yet, as I have a resolve according to how the docs specify to wait for the current user.

```javascript
resolve: {
  "currentUser": ["$meteor", function($meteor){
     return $meteor.waitForUser();
  }]
}
```

Should I put up a repository demonstrating the issues?

**Comment by vacarsu** [comment]
Perhaps it is possible to set values in the insert method rather then trying to set the creator field in the controller?

**Comment by Urigo** [comment]
@vacarsu yes I guess I was out of context, can you share a repo?

**Comment by vacarsu** [comment]
Here is the repo. https://github.com/vacarsu/roles-example

**Comment by vacarsu** [comment]
@Urigo I have got it working now! It was a combination of my insert method not being quite right not subscribing to the "users-subscription", Although I wonder why my resolve block wasn't working as expected?

**Comment by vacarsu** [comment]
Never mind issue still exists, the creator field is getting entered into the db now that I fixed the insert issue. but it's just getting a blank object now.

![screen shot 2015-06-01 at 6 02 11 pm](https://cloud.githubusercontent.com/assets/11384972/7926510/8a871070-0888-11e5-8b41-7d5de6b0863b.png)
image from meteor mongo CLI
