### ISSUE TITLE
$meteor.call passing files as parameters returns Error: DataMan constructor received data that it doesn't support.

### ISSUE THREAD

**Issue by vantonio** [Urigo/angular-meteor#379]
Hi all,

I defined a meteor function as:
```
Meteor.methods({
    addPhotos: function (userId, files) {
        check(userId, String);
        if (files.length == 0) {
            throw new Meteor.Error(404, "No Photos specified")
        }
        var status = {
            successful : 0,
            failed : 0
        };
        console.log('files', files);

        for (var i = 0, len = files.length; i < len; i++) {
            var obj = Photos.insert(files[i]);
            if(obj !== undefined){
                User.update(userId, { $addToSet: {photos: obj}});
                status.successful ++;
            }else {
                status.failed ++;
                throw new Meteor.Error(404, "Error inserting portrait");
            }
        };
        console.log(status);
        return status;
    }
});
```
but when I called this function with:
```
$meteor.call('addPhotos', $scope.userId, files).then(
            function(data){
                ...
            },
            function(err){
                ...
            }
        );
```
Meteor throws this error:
```Exception while simulating the effect of invoking 'addPhotos' Error: DataMan constructor received data that it doesn't support.```

I can see from console logs that the ```files``` object has been turned into a ```[Object, Object]``` from ```[File, File]``` during passing.

Any thoughts on this?

**Comment by netanelgilad** [comment]
This seems like a Meteor issue. I think meteor does some kind of serializing of objects being passed to method calls. Are you expecting to get the files on the server by sending them as parameters to the method? I don't think that is going to work. You need to upload the files to the server and then do manipulation, 
Check out the CollectionFS package which makes uploading files really easy.

**Comment by vantonio** [comment]
Hi, sorry for the delay. The code was used on the client to insert files, until I realized that meteor and angular together just won't work.
Right now I have dropped the angular-meteor package all together, but I'm curious about the angular 2 version.
Thanks for the answer and apologies for the delay again.

**Comment by netanelgilad** [comment]
@vantonio Just cause I'm curious to see if there really is an angular-meteor issue here. Did calling the Meteor Method work for you using the regular Meteor.call?

**Comment by Urigo** [comment]
@vantonio can you share your code in a repo so we can see if indeed it is an angular-meteor issue and solve it?

**Comment by vantonio** [comment]
Hi there @netanelgilad @Urigo, to accomplish this upload function, I've tried a few angular modules, like https://github.com/danialfarid/ng-file-upload or https://github.com/flowjs/ng-flow.
If I'm not mistaken, they all add a directive, monitor an element(```<button>``` or ```<a>```), and return object or array of objects of type File(https://w3c.github.io/FileAPI/).

But the problem is when you pass File objects from Angular to Meteor(i.e. ``` $meteor.call('addPhotos', $scope.userId, files)```), somewhere in between the ```File objects``` are lost. Meteor receives only ```objects``` which CollectionFS  cannot handle, hence the error ```DataMan constructor received data that it doesn't support```.

If you need more information please do not hesitate to ask.

**Comment by vantonio** [comment]
Also I want to apologize for the comment ```meteor and angular together just won't work```, what I meant was it won't work for me on this project:-) --I had to finish the project in less then a month.
There are many other factors here, for example meteor can't access anything from current $scope. I've tried hacks like using the $rootScope but overall it felt like an overkill for the project I'm working on.

Apologies again for the stupid comment, hope to try the Angular 2 version soon.

**Comment by Urigo** [comment]
@vantonio because CollectionFS is a little different then the regular Meteor collection it needs some special care but we already support it.
We do plan to create a tutorial for that really soon, in the meantime you can find a few examples of how to accomplish what you want here:
https://trello.com/c/tLGobwdw/26-uploading-media-photos-videos-chapter

As for an Angular 2.0 version, we already support that as well, you can find more information here:
http://angular-meteor.com/angular2

I hope you won't give up on angular-meteor because of those reasons as it seams they are already solved.

Please keep us updated about your efforts and we would love to help
