### ISSUE TITLE
Step 19 - 3rdParty Libraries - missing line in code display

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#380]
The code displayed on the page needs to have to an line at the end to close the brackets i.e.
});  (would have saved me one hour trying to found out why if failed) - it is also required  the final package.js file example:

EXAMPLE OF CODE
// package metadata file for Meteor.js
var packageName = 'PACKAGE_NAME';
var where = 'client'; // where to install: 'client' or 'server'. For both, pass nothing.
var version = 'PACKAGE_VERSION';
var summary = 'PACKAGE_SUMMARY';
var gitLink = 'GIT_LINK';
var documentationFile = 'README.md';

// Meta-data
Package.describe({
  name: packageName,
  version: version,
  summary: summary,
  git: gitLink,
  documentation: documentationFile
});

Package.onUse(function(api) {
  api.versionsFrom(['METEOR@0.9.0', 'METEOR@1.0']); // Meteor versions

  api.use('DEPENDENCY_NAME', where); // Dependencies

  api.addFiles('FILE_NAME', where); // Files in use

**Comment by Urigo** [comment]
Fixed here:
https://github.com/Urigo/angular-meteor/pull/381
