### ISSUE TITLE
I think there is a conflict in dependencies between angular-ui-router and ui-select

### ISSUE THREAD

**Issue by oshai** [Urigo/angular-meteor#382]
I tried to install both packages and it ended up with 2 versions of angular:
angular:angular@1.3.15_1
angularjs:angular@1.3.15

looks like there are 2 organizations for the same purpose.
what I see in chrome console is:  
`WARNING: Tried to load angular more than once.`

**Comment by Urigo** [comment]
looks like this is ui-select issue, @dotansimha can you update the dependencies?

**Comment by dotansimha** [comment]
Hi,
@Urigo  - Fixed it, package: https://atmospherejs.com/angularui/ui-select - the new version is 0.12.0.
@oshai - Can you try and verify?

**Comment by oshai** [comment]
the package was removed but I still have the warning.
from looking at the versions file of meteor I see I still have 2 versions
of angular, although I am not sure that is a problem.

angular:angular@1.4.0

urigo:angular@0.8.12


searching the web I found that usually it happened because of a bad
template route. I was not able to spot one like that... yet...

**Comment by dotansimha** [comment]
@oshai , please try to debug and check for invalid files that are loaded (404), Meteor does not return "404" - instead he returns the homepage, that can cause angular to load again in some cases.

**Comment by oshai** [comment]
now its gone, without doing any additional thing, so it might be that it
did the trick. Thanks!

**Comment by oshai** [comment]
thanks, in my case I have "otherwise" route to 404.
