### ISSUE TITLE
Angular ui-grid

### ISSUE THREAD

**Issue by mgrivera** [Urigo/angular-meteor#386]
Hi, 

I don't know if I can use this forum to just make general questions about angular-meteor or only to submit bugs, etc. If I'm misusing this forum, please just tell me and I don't do it again :) 

That said, this is my question: 

I use angular a lot these days and have been using ui-grid lately and love it. When doing part 4 of angular-meteor tutorial I could see how you kind of integrated ui-router to angular-meteor. I think so because the way you installed the router using official meteor package: 

meteor add angularui:angular-ui-router

So, my real question is: Do we have to wait for "every" angular package, as is ui-grid, to be integrated to meteor package system? Or, every angular package, like ui-grid and ui-bootstrap and others, can be used in angular-meteor as is, I mean without waiting for you to add it to meteor package system?  

Many thanks for your answers and bye ...

**Comment by Tallyb** [comment]
You should search if package already exists, or check step 19 of the tutorial on how to create it yourself.

**Comment by mgrivera** [comment]
Many thanks for your answer Tallyb; it was very informative ...

**Comment by Tallyb** [comment]
sorry - was on mobile; 
I also found this https://atmospherejs.com/angularui/ng-grid . is that what you are looking for? 
Step 19 of the tutorial http://angular-meteor.com/tutorial/step_19 is explaining how to integrate 3rd party libraries. 
also, for those questions, you may join the gitter: https://gitter.im/Urigo/angular-meteor. 
I apologize if I am stating the obvious...

**Comment by mgrivera** [comment]
Well, ng-grid is version 2; there is ui-grid which is version 3.0. Version 2 was added to meteor, as I can see; I think version 3 should follow soon. 

I haven't read step 19 of tutorial yet but I will do it today. Gitter is fantastic and I will join. 

Thanks (again) for the info Tallyb ...

**Comment by Urigo** [comment]
Thanks @Tallyb !

**Comment by Urigo** [comment]
@mgrivera after you find a suitable ng-grid  (if you find or if you create one yourself) please post it here as well:
https://trello.com/c/EGCdgHAk/47-official-meteor-packages-to
