### ISSUE TITLE
Component Router delayed for 1.5, plans for updating to 1.4?

### ISSUE THREAD

**Issue by vacarsu** [Urigo/angular-meteor#387]
@Urigo  Since the new Component Router got delayed for angular 1.5, do you have plans to upgrade angular-meteor to 1.4 sooner?

**Comment by Urigo** [comment]
I've updated it today and will release a new version soon.
In the meantime if you want to update your project already you can just add a dependency in your packages file directly to angular:angular@1.4.0:

    meteor add angular:angular@1.4.0

**Comment by Urigo** [comment]
@vacarsu released in the new 0.8.14 version
