### ISSUE TITLE
MinimongoError: can't set field named $$hashKey

### ISSUE THREAD

**Issue by gpothier** [Urigo/angular-meteor#389]
There seems to be a regression in 0.8.12 (problem does not happen in 0.8.10). In some cases calling scope.$apply causes this error:

MinimongoError: can't set field named $$hashKey [409]

Full trace:

"Meteor.makeErrorType/errorClass@http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:532:15
@http://localhost:3000/packages/mongo.js?3cfe0c5981c197df33036a37574850f057e934a6:984:19
.apply/stubReturnValue<@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:4269:20
.withValue@http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:955:17
.apply@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:4260:31
Mongo.Collection.prototype[name]@http://localhost:3000/packages/mongo.js?3cfe0c5981c197df33036a37574850f057e934a6:656:1
upsertObject@http://localhost:3000/packages/urigo_angular.js?f39a58528c9912d9069bc87495d9781c9d7c3fec:1036:11
save@http://localhost:3000/packages/urigo_angular.js?f39a58528c9912d9069bc87495d9781c9d7c3fec:1064:25
updateCollection/<.changedAt@http://localhost:3000/packages/urigo_angular.js?f39a58528c9912d9069bc87495d9781c9d7c3fec:1318:9
diffArray/<@http://localhost:3000/packages/urigo_angular.js?f39a58528c9912d9069bc87495d9781c9d7c3fec:473:9
_.forEach@http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:164:13
diffArray@http://localhost:3000/packages/urigo_angular.js?f39a58528c9912d9069bc87495d9781c9d7c3fec:457:3
updateCollection@http://localhost:3000/packages/urigo_angular.js?f39a58528c9912d9069bc87495d9781c9d7c3fec:1306:1
setAutoBind/ngCollection.unregisterAutoBind<@http://localhost:3000/packages/urigo_angular.js?f39a58528c9912d9069bc87495d9781c9d7c3fec:1278:15
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:3000/packages/angular_angular.js?9db7e8edebe9ba02ab378f03d9a52d49148583ee:14338:23
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:3000/packages/angular_angular.js?9db7e8edebe9ba02ab378f03d9a52d49148583ee:14601:13
cleanup@http://localhost:3000/client/lib/pad.js?28277c20ced0c42fb697d3fe810cb506bd047d23:184:5
commit@http://localhost:3000/client/lib/pad.js?28277c20ced0c42fb697d3fe810cb506bd047d23:174:5
endDraw/strokeTimeout<@http://localhost:3000/client/lib/pad.js?28277c20ced0c42fb697d3fe810cb506bd047d23:164:7
timeout/timeoutId<@http://localhost:3000/packages/angular_angular.js?9db7e8edebe9ba02ab378f03d9a52d49148583ee:16329:28
completeOutstandingRequest@http://localhost:3000/packages/angular_angular.js?9db7e8edebe9ba02ab378f03d9a52d49148583ee:4954:7
Browser/self.defer/timeoutId<@http://localhost:3000/packages/angular_angular.js?9db7e8edebe9ba02ab378f03d9a52d49148583ee:5342:7

**Comment by netanelgilad** [comment]
Should be fixed in the last commits. Will be in the next version..
