### ISSUE TITLE
All fields are getting passed to the client

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#390]
I am sure this is due to being new to Meteor, but I cannot get the app to select only certain fields from the mongo collection to pass to the client.

in model: 
Labels = new Mongo.Collection("labels");

In server: 
Meteor.publish("labels", function() {
  return Labels.find({}, {gb:1, fr:1, key:1 });
});

in client: 
  $scope.labels = $meteor.collection(Labels, false).subscribe('labels');

However when Angular shows records from $scope.labels it includes all fields: i.e.
{"key":"listfail","gb":"Incomplete","us":"Incomplete","de":"Unvollständig","fr":"Incomplet","it":"Incompleto","es":"Incompleto","_id":"RecMGiGfLFjv3aZWi"}

I know the line return Labels.find({}, {gb:1, fr:1, key:1 });  works within mongo, so is it the Minimongo retaining old data (i have restarted computer to try and clear it!)
Version urigo:angular@0.9.0-alpha.5  used.

**Comment by barbatus** [comment]
@JohnAReid Docs says it should be
````
Labels.find({}, {fields: {gb:1, fr:1, key:1}})
````

**Comment by JohnAReid** [comment]
Thanks
