### ISSUE TITLE
is it possible to get an object resolved before starting the controller?

### ISSUE THREAD

**Issue by oshai** [Urigo/angular-meteor#391]
if you look at the example at the tutorial step 6 http://angular-meteor.com/tutorial/step_06 there is an example of binding to an object (party). from my checks trying to access the object properties immediately after retrieving (next line) it doesn't works. properties still not available. 
is there a way to get the object injected to the controller in a way that it will be available when the controller starts? iron-router has a similar solution, but it is only for meteor. I am using ui-router.

**Comment by Tallyb** [comment]
If you are using ui-router (angularui:angular-ui-router), it has a similar option under the resolve property. There is an example in step 9 of the tutorial (search for "good practice").

**Comment by oshai** [comment]
Thanks!
