### ISSUE TITLE
meteor-roles support?

### ISSUE THREAD

**Issue by harinanda** [Urigo/angular-meteor#394]
meteor-roles support?

**Comment by vacarsu** [comment]
I use meteor roles just fine with angular meteor.

**Comment by Urigo** [comment]
@harinanda is there any specific requirement you would like to add?

**Comment by harinanda** [comment]
thanks  @Urigo  and @vacarsu . i got it

**Comment by MilosStanic** [comment]
Any sample on how to manage roles in angular-meteor app?
I need to create an admin user, and restrict some routes only to admin. How do I do that? Do I have to install some of Meteor's router packages?

**Comment by vimes1984** [comment]
Hey @MilosStanic I tend to use the amazing https://github.com/alanning/meteor-roles package
to set up a Admin role
Then I use:
```
   
 $stateProvider
    .state('adminui', {
      url: '/adminui',
      templateUrl: 'client/templates/angular/adminui.ng.html',
      controller: 'AdminuiCtrl',
      resolve: {
        currentUser: ['$meteor', '$q', function($meteor, $q) {
          return $meteor.requireUser().then(function(user) {
            if(!_.contains(user.roles, 'super-admin')) {
              // fail the promise chain
              return $q.reject('FORBIDDEN');
            }
            // keep the success promise chain
            return user;
          });
        }]
      }
    });
```

**Comment by MilosStanic** [comment]
Thanks again @vimes1984 , got it on Gitter.
