### ISSUE TITLE
Multiple publications to the same collection

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular-meteor#398]
I am struggling with grasping this example from the $meteor.subscribe APIs: 
```
$meteor.subscribe('todos').then(function(subscriptionHandle){
// Bind all the todos to $scope.todos
$scope.todos = $meteor.collection(Todos);
```
All cool when you have a single subscription. Hwoever, assume I a single 'posts' collection but have 2 publication from my server: 
```  
Meteor.publish('recentPosts', function(){
    return Posts.find({/*code to return the last X posts*/});
  });
  Meteor.publish('topPosts', function(){
    return Posts.find({/*code to return the top ranked X posts*/});
  });
```

They are both shown on the same template, so I have 2 scope variables: 
$scope.recentPosts
$scope.topPosts

Do I just need to write something like: 
```
$meteor.subscribe('recentPosts').then(function(subscriptionHandle){
      // is this correct? 
      $scope.recentPosts = $meteor.collection(Posts).subscribe ('recentPosts');
}); 
$meteor.subscribe('topPosts').then(function(subscriptionHandle){
      // or is this one? 
      $scope.topPosts = $meteor.collection(Posts);
});
``` 
 or something else?

**Comment by vacarsu** [comment]
Not sure of your specific use case, but how I do this:

```javascript
  $scope.milestones = $scope.$meteorCollection(function () {
      return Milestones.find({ 'project': $stateParams.id });
    }, true).subscribe('milestones', $stateParams.id);

    $scope.issues = $scope.$meteorCollection(function () {
      return Issues.find({ 'project': $stateParams.id });
    }, true).subscribe('issues', $stateParams.id);
```
Both of the above publish methods look as follows
```javascript
  Meteor.publish('issues', function (projectId){
    return Issues.find({});
  });
```
```javascript
Meteor.publish('milestones', function (projectId){
  return Milestones.find({});
});
```

**Comment by vacarsu** [comment]
Ah I think I understand now, and I believe it would look like this:

You'd use one subscription and set your $scope variables inside of the callback.
```javascript
$scope.$meteorSubscribe('posts').then(function (handleSubscription) {
  $scope.recentPosts = $meteor.collection(Posts, optionsToGrabRecentPostsOnly)
  $scope.topPosts = $meteor.collection(Posts, optionsToGrabTopPostsOnly);
});

**Comment by Tallyb** [comment]
the $meteor.collection does not recieve options for calculate. The question is if there is a way to reuse the definition in the server of the top posts code, e.g. by subscribing directly to it. 
     $scope.recentPosts = $meteor.collection(Posts).subscribe ('recentPosts');

**Comment by vacarsu** [comment]
Yes there is I do this myself you can return a callback like this:
```javascript
$scope. recentPosts = $meteor.collection(Posts, function () {
  return \\ find your posts
}).subscribe('recentPosts');
```

**Comment by civilframe** [comment]
@vacarsu There are lots of reasons to have two publications for the same collection. Say you want to make a directive that shows a list of posts by a configurable scope variable.

**Comment by Tallyb** [comment]
Assume I have really lots of posts on my server. I do not want to sync all of them to the client. 
My client will show page with 2 sections: the top 10 posts and the recent 5 posts. This is why I need to subscriptions to the same collection - the first one to tell the server to bring the 10 top, and the other to tell the server to bring the 5 recent. So, basically my collection can have anything between 10 and  15 documents at any given time (this assumes the server has more than 10 of course).

**Comment by Tallyb** [comment]
I created this repository with multiple server subscriptions. https://github.com/Tallyb/ng-leaderboard-subs
I am wondering if there is a way on the client side to specify the query as is in the subscription without repeating it (sure, I could use config object instead).

**Comment by vacarsu** [comment]
I don't think doing this with two different subscriptions is possible, I cloned your repo and the only way I could get the desired results was to use one subscription and filter the results on the client. The angular-meteor tutorial even states that this is the proper way to do this. In each publication you were finding all players anyway and then just sorting them via selection. Seems best to just use one subscription.

The Publish method
```javascript
Meteor.publish('players', function () {
  return Players.find({});
})
```

The subscription
```javascript
$scope.$meteorSubscribe('players').then(function (handle) {

      $scope.topPlayers = $meteor.collection(function () {
        return Players.find ({}, {sort: {score: -1}, limit: 2});
      });

      $scope.firstPlayers = $meteor.collection(function (handle) {
        return Players.find ({}, {sort: {name: 1}, limit: 3});
      });

    });
```
this worked for me and seems much better the keeping a list of several different publications along with all the possible different queries you could be using for each one.

**Comment by civilframe** [comment]
There's nothing wrong with having multiple subscriptions. Meteor is built for this.

**Comment by vacarsu** [comment]
Yes, but there must be a bug in angular meteor then, because I tried using the repo to use the two publications, without repeating the query in controller and it just wouldn't work.

**Comment by Tallyb** [comment]
Apparently. you have to repeat the query in controller (or use an options object),as the client is taking from the collection. 
I have updated the readme to explain what is going on there. Check it out.

**Comment by vacarsu** [comment]
Ah, so there is no way around duplication. That is unfortunate. At least you got to the root of it.

**Comment by Tallyb** [comment]
The subscriptions says what it wants to be brought to the client. The query to the local $scope variable is totally differ. Pretty useful, as you can use the subscription to bring the "next bunch" but only display it later. 
If you do not want to repeat yourself, you can use function with parameters.

**Comment by vacarsu** [comment]
The way I see it is the publication is for security, like when you have a collection that users can only see a specific set of results in, then the controller query is where you further refine the view results. Personally, I would avoid mutliple subscriptions for a single collection, it seems you can do nearly anything with a single publication. Much like in the tutorial where you decide whether the user can see certain parties based on whether he owns the party or whether it is a public party.

**Comment by Tallyb** [comment]
But what if you work on millions of items, and there is no or little security (think Amazon items).  You cannot sync all of the db to the client. You have to pull only a portion. Search query results top 20 + other people Also bought.

**Comment by vacarsu** [comment]
Yes of course, but you would only have that one subscription to grab 20. you could reuse that pub as many times as you want to grab 20 of any items. you filter the 20 items you receive on client. that that make sense? And when I say avoid multiple publications I mean only when it's absolutely necessary because of data overload. so you could grab 20 items at a time and filter them on the client by "other people also bought.", "top items" etc.

**Comment by Tallyb** [comment]
If you run your code variation above and check the client local db, you will see all of the db locally. Worth a test.

**Comment by vacarsu** [comment]
I am aware because I didn't limit the number in that example. I'm saying you could, and then still query for 20 items of whatever you needed. I can create some example of what I mean if you want.

**Comment by vacarsu** [comment]
```javascript
Meteor.publish('players', function () {
  return Players.find({}, { limit: 3 });
})
```
like so works with the same subscription and you can lower the client side limit even further down if you wanted.

**Comment by vacarsu** [comment]
Here is another example showing the power of a flexible pub/sub
```javascript
var limit = 3;

    $scope.$meteorSubscribe('players', limit).then(function (handle) {

      $scope.topPlayers = $meteor.collection(function () {
        return Players.find ({}, {sort: {score: -1}, limit: 2});
      });

      $scope.firstPlayers = $meteor.collection(function (handle) {
        return Players.find ({}, {sort: {name: 1}, limit: 3});
      });

    });
```
```javascript
Meteor.publish('players', function (limit) {
  return Players.find({}, { limit: limit });
})
```

**Comment by civilframe** [comment]
@vacarsu The above example won't work 100% of the time. The subscription will only fetch the top three players, by id. What if the top three players by score are not also the top by id? And what if the top three players by name are also not the top by id. You need multiple subscriptions in this case.

**Comment by vacarsu** [comment]
@civilframe Ah! you are absolutely right, I didn't even think to take that into account. Certainly some tweaking could be done to shrink it into one sub? Having a hard time conceptualizing what that may look like at the moment.

**Comment by Tallyb** [comment]
I have updated the repository to start / stop any subscription, so you can inspect local database to see what is going on. 
Also published on http://ng-leaderboard-subs.meteor.com/

**Comment by mgrivera** [comment]
Wow, I can see how this is a very powerful mechanism, I mean stopping subscriptions, because when doing it the local data is cleared at the same time and automatically. Well, at least what corresponds to the particular subscription, because you have two of them in the sample and can have one active but the other stopped. 

Very interesting indeed .. thanks for the beautiful sample, at least for me that am very new to meteor and angular-meteor (not angular however).

**Comment by Tallyb** [comment]
For further reference, I add here the link to my blog post on the angular-meteor blog, if anyone finds it relevant: https://medium.com/angular-meteor/coll-pub-sub-with-angular-meteor-cb13fe48f570
