### ISSUE TITLE
How to stop mini mongo collections getting to big?

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#400]
Is there a way to clear the existing mini mongo collection before making a $meteor.subscribe call. 

I am finding that the code is getting slower (performing a find on the collection) as the client collection is getting larger each time a new $meteor.subscribe is made, and the client collection most likely contains data no longer required.

**Comment by civilframe** [comment]
@JohnAReid You may want to consider the architecture/layout of your app. $meteor.subscribe only keeps the subscription active as long as the current $scope is alive (it is $destroyed when you the component is no longer being rendered) This should, for the most part, help to control the size of your subscriptions. 

The other important piece is to limit your result set. For example, only show the user the first 100 records, sorted by their created date. Then load another 100 if they request more, etc. You can limit and sort result sets like so:

```javascript
//.. Controller code
var filter = {
	'some_property': 'a value'
};

var paging = {
	limit: 100
	sort: {'created_on': -1}
};

$meteor.subscribe('BlogPosts', filter, paging).then(function() {
	$scope.blogPosts = $meteor.collection(function() {
		return BlogPostsCollection.db.find(filter, paging);
	})
});

//.. Server code
Meteor.publish('BlogPosts', function(filter, paging) {
	return BlogPostsCollection.db.find(filter, paging);
}
```

**Comment by ccortezia** [comment]
@civilframe I think you were talking about $meteor.$meteorSubscribe right ? 
Take a look at http://angular-meteor.com/api/subscribe.

**Comment by civilframe** [comment]
@ccortezia Good catch! I mistakenly thought $meteor.subscribe does that all on it's own. Looks like that's not the case..

@Urigo would you confirm/clarify the above?

**Comment by JohnAReid** [comment]
This is something I have been working on and making sure my search is on the _id field whenever possible.

My concern is really with linking the collection to the $scope object, if the whole collection on the client is exposed to the $scope does this not create extra overheads.    Is it not possible to allocate the collection to a variable within the controller and then clear that variable by setting it to null?

**Comment by civilframe** [comment]
@JohnAReid Setting the collection to $scope variable doesn't add significant overhead (I believe), since it's just a reference. Also, setting the variable to null will not stop the meteor subscription, which is what copies a portion of the database from the server to the client, keeping it in sync.

Meteor subscriptions are a very different concept than what I was used to. If you are new to it as well, I recommend reading https://www.discovermeteor.com/blog/understanding-meteor-publications-and-subscriptions/ and  http://meteorpedia.com/read/Understanding_Meteor_Publish_and_Subscribe

**Comment by JohnAReid** [comment]
@civilframe Thanks if it not does add to the $scope overhead  too much then I do not have a problem with using it.  

The Meteor subscription system is difficult concept to get the hang off - call the subscription and then do the same thing again on the client -  it's a bit like BOGOF (buy one get one free) but more like CTFO (call twice get once).

**Comment by Tallyb** [comment]
@JohnAReid - we have discussed some of it in other issue: https://github.com/Urigo/angular-meteor/issues/398
Also check this repository to get some idea on how not to think all data. https://github.com/Tallyb/ng-leaderboard-subs

**Comment by Urigo** [comment]
@civilframe great answers, can't add any more to it and just confirming everything you said (including using `$scope.$meteorSubscribe` and not `$meteor.subscribe`

**Comment by Urigo** [comment]
@Tallyb that's a very nice example !

**Comment by JohnAReid** [comment]
OK I have had to re-open this due to the follow:

 I have three states on a ui router, home, list and list.detail, all with separate controllers.

In the list controller I call the following which is getting a list of statements from Mongo:
$scope.statements = $meteor.collection(Statements, false).subscribe('subscribeStatementsReq', detail.all).

In the detail controller I call the following: 
$scope.statements = $meteor.collection(Statements, false);

The detail.html display the list of statements loaded from Mongo and stored on the client.

So as more and more calls are made by the subscribe call the list of statements is getting larger and larger.

Now use the router to go back to home, wait a few seconds and click on list again and all the statements are still displayed.  So it looks as if the list scope is not getting destroyed.
