### ISSUE TITLE
(docs) - $meteor.collection API

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular-meteor#403]
The doc says: 
Calling $scope.$meteorCollection is exactly the same but additionally it will automatically **stop the collection** when the scope is destroyed. Therefor this is the recommended method.

What does "stopping the collection" means here? I understand stopping of subscription, but I am not clear what happens when the collection is stopped.

**Comment by Urigo** [comment]
You are right, the explanation is bad...

It's closing the:

* autobind if it's open
* Observe on the cursor
* Clearing the data from the array

Here is the code:
https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-meteorCollection.js#L222-L233

maybe you can suggest an edit to the docs?
thanks!!

**Comment by Tallyb** [comment]
OK, I understood what bothers me with the description. While on subscribe you get a manual way of doing the stop (namely .stop() on the handle), collection does not provide an "alternative" way. This why I do not like that it is the "recommended" method - it is all or nothing :). 
Having said that, I understand that the data will be cleared upon closing the subscription, and same goes for cursor observing. 
The autobind watching (if opted for) will be stopped when the $scope is destroyed anyway , which is the same as placing on $scope. 
Makes sense? Am I talking bullocks here?

**Comment by Urigo** [comment]
You can still call stop() , it's a public function on the array.

It is important to stop the query handle (cursor observe) as it will continue to watch even if there is no data.

**Comment by Tallyb** [comment]
So this is an undocumented method in addition to  save, remove and subscribe?

**Comment by Tallyb** [comment]
created a new PR for both $meteorCollection service and the object.
