### ISSUE TITLE
Problem with subscription and ng-controller directive.

### ISSUE THREAD

**Issue by vacarsu** [Urigo/angular-meteor#406]
Using the ng-controller directive does not allow for enough time for the subscription to finish, which means bindings do not appear. Is there anyway around this? I want to avoid putting it in a ui-router view as this causes the controller to be re-instantiated every time a route is hit with that view.

**Comment by Tallyb** [comment]
Can you provide additional details?

**Comment by vacarsu** [comment]
Sure, I have a navbar which needs to be on every page. So I put it in the index.html file with an ng-controller directive. Inside of the controller I have a Counts subscription which counts unread notifications and displays the number in the navbar. The problem is the binding does not appear when I use ng-controller. I put the navbar inside a ui-view and it works, however this causes the controller to be re-instantiated whenever a route with that view is hit. Within the navbar controller I am also observing changes in the subscription to display toast messages. If I put the navbar in a ui-view because the controller is re-instantiated toasts reappear every time. So I just want to put the navbar in the index file using the ng-controller directive.

Really angular-meteor shouldn't be so reliant on a router should it?

**Comment by Tallyb** [comment]
I am not answering your question, but suggesting some alternative. You may want to use named views. 
<div ui-view="navbar"><div> 
<ui-view>. 
In your top state you add a view section to the state object. https://github.com/angular-ui/ui-router/wiki/Quick-Reference#ui-view
ui router knows only to replace the chagied parts between states, so if your state does not explicitly referring to the navbar view, it will not be reinstantiated. 

also - do you use the $scope version of the subscribe, or the $meteor?

**Comment by vacarsu** [comment]
Thanks for your suggestion I tried using name views but I guess the only way is to have a root view and put the navbar on the root view? I'm using named views, which is where I put the navbar for a short time. However because I do not have a single root view I had to add the view name to each parent route which caused the controller re-instantiating. 

And to answer your question I am using the $scope version.

**Comment by Tallyb** [comment]
well, state diagram wise, you have a "root" view which is the screen having the navbar and some content. Everything else should inherit from it. your root view === you index. 
If you will use the $meteor version, you can control the establishment of the subscription, and it will not be started and stopped with every screen change. For example, if you will put it in module.run 
$meteor.subscripbe ('CountSubsciption') then reistantiating the controller will have no affect on it.

**Comment by vacarsu** [comment]
Ah, putting it in a run block is a great idea! Also, restructuring my routes as you suggested. Though I still think this issue should stay open. ng-controller should still work.

**Comment by Urigo** [comment]
I agree with @Tallyb about the structure, but as for your question, the problem shouldn't be on ng-controller.
If the subscription is not ready it's not s problem, think about it like the $http promise.
Let's say you bind your Counts like that:

    $scope.dogsCount = $scope.$meteorObject(Counts, "numberOfDogs", false);

and then later you subscribe to 

    $scope.$meteorSubscribe("dogsSubscriptions");

Then in the view you have

    <div>Number of dogs are {{ dogsCount }} </div>

Then it will just be empty until the subscription and the data will get there, no?

**Comment by vacarsu** [comment]
@Urigo The problem is the binding never got filled with the data. Not until I used a named view in ui-router. Angular-meteor works incredibly well with ui-router no problems at all. Problems arise when you are not using a router to handle controller bindings.

**Comment by Urigo** [comment]
@vacarsu can you please share a repo?

**Comment by MilosStanic** [comment]
@vacarsu if you're placing it in index.html it will not get parsed by Angular. It has to be in some .ng.html file.

**Comment by vacarsu** [comment]
@MilosStanic Ah, I see thanks. So it is a meteor thing.
