### ISSUE TITLE
Mongo database options

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#407]
Would it be possible to provide an example of the best way to do the following:

1 - To use two mongo databases (one for static data and the other for user info)

2 - To have two Meteor projects which uses the same mongo database.

**Comment by Tallyb** [comment]
It seems that this is a better place to search for an answer or submit your question: https://forums.meteor.com/
It is not directly related to angular-meteor

**Comment by Urigo** [comment]
@JohnAReid I agree with @Tallyb although I too would love to see a nice and good example of this.
Can you please open this on the Meteor forum and paste the link here for future usage?
thanks
