### ISSUE TITLE
How to stop mini mongo collections getting to big? -  re open of #400

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#408]
OK I have had to re-open this due to the follow:

I have three states on a ui router, home, list and list.detail, all with separate controllers.

In the list controller I call the following which is getting a list of statements from Mongo:
$scope.statements = $meteor.collection(Statements, false).subscribe('subscribeStatementsReq', detail.all).

In the detail controller I call the following: 
$scope.statements = $meteor.collection(Statements, false);

The detail.html display the list of statements loaded from Mongo and stored on the client.

So as more and more calls are made by the subscribe call the list of statements is getting larger and larger.

Now use the router to go back to home, wait a few seconds and click on list again and all the statements are still displayed. So it looks as if the list scope is not getting destroyed.

**Comment by smoke** [comment]
You are perfectly correct, unless subscriptionHandle is stopped by calling ```subscriptionHandle.stop()``` the documents are still kept and synced in Minimongo.

So what you will have to do for collection subscriptions is one of the following:
* Get the subscriptionHandle once the subscription completes and have a custom ```$scope.$on('$destroy', function() { subscriptionHandle.stop(); });```. This way you can optimize the code a bit
* Just use ```$scope.$meteorSubscribe('books')``` which binds on $destroy for each subscription and calls the subscriptionHandle.stop(); internally, as this is what it is intended for. Check #304 for more info.

The docs for both usages are on http://angular-meteor.com/api/subscribe, note that the above usage is not explicitly obvious through the docs.

Just a small note - for AngularMeteorObject the subscription is stopped through a method .stop() on the object, not through a subscriptionHandle http://angular-meteor.com/api/meteorObject

**Comment by Urigo** [comment]
@smoke thanks so much for the great answer.
how would you improve the docs to make it easier for more people to understand that concept?

also, @Tallyb has wrote a new blog post on this subject:
https://medium.com/angular-meteor/coll-pub-sub-with-angular-meteor-cb13fe48f570
