### ISSUE TITLE
is it possible to use getReactively on $rootScope variables?

### ISSUE THREAD

**Issue by oshai** [Urigo/angular-meteor#415]
I have a case that I want to update the ui based on the user so if a user was log-out and log-in ass different user, a score of the user in the ui is changed. The way I thought about doing it is by looking at `$rootScope.currentUser`.  

from my testing it seems like there is some kind of access to the $rootScope, but it is not getting updated on user change (unless I have a bug in my code). here is the relevant code:

    $meteor.autorun($scope, function() {
                if (null !== $rootScope.currentUser) {
                    $scope.userForScore = $scope.$meteorObject(Userinfo, {user_id: $scope.getReactively('currentUser')._id});//$rootScope.currentUser._id
                }
            });

        $scope.userScore = function(){
            if ($scope.userForScore === undefined || $scope.userForScore.score === undefined) {
                return 1;
            }
            return $scope.userForScore.score;
        };

Userinfo - is a collection I created in the server.

**Comment by oshai** [comment]
I post it also here: http://stackoverflow.com/questions/30693154/is-it-possible-to-use-getreactively-on-rootscope-variables

**Comment by Tallyb** [comment]
you can use Meteor.user() instead. this is a reactive var.

**Comment by oshai** [comment]
It is working, thanks!
Is it a bug? should it be documented somewhere?
the documentation <a href="http://angular-meteor.com/api/auth">here</a> says:
`$rootScope.currentUser — The current logged in user and it's data. it is null if the user is not logged in. A reactive data source.`

**Comment by Tallyb** [comment]
@oshai If you look at the code, you will see that $rootScope is reactively getting the value from Meteor.user(). I do not think it is  a bug, I believe more of "best practices". Since Meteor.user is already reactive, there is no point (and also from performence POV) to make $rootScope reactive on top of it. The purpose of $rootScope.User is to enable using the user in "pure" angular things, such as in templating, ui-router. (in "pure" agular i refer to everything which is not $meteor)

**Comment by oshai** [comment]
I am pretty sure there is a bug over there (angular-meteor-user.js:line 6)
    if (Meteor.user) {
should be
    if (Meteor.user()) {
not sure if this cause anything or it will fix anything, but probably a bug.

I can create a PR for that.
In addition, I don't understand what is the benefit of
`$rootScope.currentUser`.
is it only syntactic sugar?

**Comment by Urigo** [comment]
@oshai the reason it's `if (Meteor.user) {` and not `if (Meteor.user()) {` is because I want to return null even when that's what Meteor.user() return, but it keeps track of it and when it will change, it will return the new value.

`$rootScope.currentUser` is just a wrapper for http://docs.meteor.com/#/full/meteor_user   you can use it in a controller or in the HTML

**Comment by oshai** [comment]
@urigo I think I am missing something. from my chrome console:
the return value of the expression "Meteor.user" is always "function
Meteor.user()" whether the user logged in or not.
am I right? its like saying 'if(true)'

Ohad

**Comment by Urigo** [comment]
You are right, It's a function, but I'm talking about the return value..

**Comment by oshai** [comment]
I am sorry. But I still don't understand in what case this if expression
changes. The function is not called without the () right?

**Comment by Urigo** [comment]
ohh the reason for the if statement is to check if you have to accounts package.
If you don't have the accounts package, Meteor.user would be undefined

**Comment by oshai** [comment]
Got it, Thanks!
I still think there is a bug there, I will try to reproduce it.

**Comment by oshai** [comment]
I think I managed to reproduce it, although not exactly my code. if you can look here: http://reproduce_415.meteor.com I created 2 users:
a@a and b@b both with password 123456 and a random score (list below in that page).
when a user logged in / out - the score should be changed - based on the reactivity of 'currentUser'. but it doesnt happen: 

![image](https://cloud.githubusercontent.com/assets/2683969/8140875/8d053e56-1168-11e5-8ceb-d161d7def80a.png)


the sources are here:
https://github.com/oshai/rep_415

Let me know if that is clear.

**Comment by oshai** [comment]
from debugging I noticed that "autorun" method is called only once when page is loaded and not after a logout/login. I am not sure it is the same but in meteor's Tracker.autorun documentation: http://docs.meteor.com/#/basic/Tracker-autorun it is not clear that this function will run after login/logout.

**Comment by Urigo** [comment]
@oshai getReactively works on $rootScope variables.
You had other problems in your examples that aren't related to that, I've created a pull request to your repo to fix those issues so you can see that it does work:
https://github.com/oshai/rep_415/pull/1

I've also add more info to the docs about autorun, let me know if you think I should add more.

**Comment by oshai** [comment]
Thanks, I see my mistake.
about the documentation of autorun, I think an example can help there to
clarify it.

**Comment by Urigo** [comment]
@oshai do you care for submitting a pull request with an example?
best documentation comes from a fresh mind!

**Comment by oshai** [comment]
sure, I will take the one from this issue.

**Comment by oshai** [comment]
Another suggestion I have which is more general is to change the api
structure so that it will have a section about $meteor object with
subsections for specific methods. I thought about it because I don't see a
reason that autorun is in the $meteorUtils section.... I guess this is
related to older api.
So for example there will be a meteor section and under that autorun page
where the autorun method content will be (in a sub-section).
If you want I can help with that.

**Comment by Urigo** [comment]
@oshai yes I think we should get autorun out there into it's own page and also get more examples.

Care to try do that?

**Comment by oshai** [comment]
yes, I will try.
