### ISSUE TITLE
Huge performance down after rerun a subscription of 1500+ elements.

### ISSUE THREAD

**Issue by dagatsoin** [Urigo/angular-meteor#416]
I am making  an app with a map and a bunch of filters on the left side. I have a collection called `Traces` which are some geolocalised points. And a `Trackers` collection which are traces' categories.
When I subscribe to `Traces` I send an array of `trackersIds` to get what I need.

I got this autorun block which reruns each times the trackers ids array is changed.

```
$meteor.autorun($scope, function(){
	$meteor.subscribe('traces', {trackersIds:$scope.getReactively('trackersIds',true)}).then(function(){
		$scope.traces = $meteor.collection(Traces);
	});
});
```

My subscription is about 1500 elements. 

At the first run there is no problem, the app is smooth. But when I uncheck then recheck a tracker the subscription rerun and my application begin to slow down dramatically. Even if my subscription is still of 1500 elements.

How could I know where is the bottleneck? I tried to use the Chrome profiler but there is too much element and I don't know where to look.

I don't think my subscription is too big, because it runs smoothly at the first time. Could be there a memory leak somewhere? A non destroyed object stayed alive between the first and second subscription?

Thx for your help.

**Comment by Tallyb** [comment]
I am not sure it will solve your solution, but can you try replace $meteor.subscribe with $scope.$meteorSubscribe  and $meteor.collection with $scope.$meteorCollection? 
 one other thing which might give you an idea is this: 
place the code bellow as a bookmark item (the code is the url) 
click it on the page. You will see the number of angular watchers on the page. 

      javascript:(function() { var watchers, elementsWithScope, scope, i, _len; watchers = 0;   elementsWithScope = document.querySelectorAll('.ng-scope'); for (i = 0, _len = elementsWithScope.length; i < _len; i++) { scope = angular.element(elementsWithScope[i]).scope();       if (scope.$$watchers != null) { watchers += scope.$$watchers.length; } } alert('Watcher Count: ' + watchers); })()

**Comment by civilframe** [comment]
@dagatsoin You may also take advantage of Angular's single-binding feature, for example:

```html
<div class="traces" ng-repeat="trace in traces">
    <div class="trace-name" ng-bind="::trace.name"></div>
</div>
```

References:
https://docs.angularjs.org/api/ng/directive/ngBind
https://docs.angularjs.org/guide/expression

**Comment by dagatsoin** [comment]
@Tallyb I replace collection and subscribe. Did not notice any change but it is best-practice, so thx.

Concerning the watchers. Something strange here. Each time I uncheck and recheck a tracker layer - so at each autorun iteration - the total number of watchers increases by 2: 92, 94, 96, 98... instead of stay unchanged.
Is it a normal behavior ?

**Comment by smoke** [comment]
@dagatsoin Have you tried "stopping" the old collection as I believe it still hold some resources and execution cycles unless told so. 
Here is an example using your code, but you would just place the piece of code within your refactored variant.
```
      $meteor.autorun($scope, function(){
        $meteor.subscribe('traces', {trackersIds:$scope.getReactively('trackersIds',true)}).then(function(){
          if ($scope.traces && $scope.traces.stop) {
            // stop the old subscription - this unbinds watchers and cleans up memory
            $scope.traces.stop();
          }
          $scope.traces = $meteor.collection(Traces);
        });
      });
```

Please share with us if this works.

**Comment by auterium** [comment]
@Tallyb, @dagatsoin, @smoke there's no need to stop a subscription within the $meteor.autorun, as the method internally handles the subscriptions and stops them whenever the previous autorun gets invalidated, so using $scope.$meteorCollection (which internally binds to the $destroy signal of the scope) or checking if it can be stopped (as proposed by smoke) will have no effect other than some extra code lines and calls.

@dagatsoin are you loading all the traces on the first run? If so, the alternative is to keep them loaded in minimongo and then filtering at the collection level and not the subscription. I.E.
```javascript
$scope.$meteorSubscribe('traces');

$meteor.autorun($scope, function() {
  $scope.traces = $meteor.collection(function() {
    return Traces.find({trackerIds: $scope.getReactively('trackersIds', true)});
  }, false);
});
```

Your performance drop most likely is because on each computation of autorun, since the subscription is ended, all the data that was stored needs to be deleted before the new one arrives, so it will take extra time while removing the documents from minimongo.

**Comment by civilframe** [comment]
@auterium :+1: great suggestion

**Comment by dagatsoin** [comment]
@auterium In fact, @smoke 's solution has worked. I think the `$destroy` signal does not fire. But I don't understand why.

So manually stopping it does the job. And the number of watchers does not increase at each iteration any more.
So, is it the normal behavior? Would not be to the $meteorSubscribe to auto stop when the autorun iterate like @auterium says? Could it be a bug?

**Comment by auterium** [comment]
@dagatsoin the $destroy signal is at the $scope level, so when the $scope is destroyed, the signal gets send. $scope.$meteorObject, $scope.$meteorCollection, and $scope.$meteorSubscribe are stopped when the $destroy signal is fired.

Strange thing is that when I researched this it was properly stopping on each autorun computation. How are you checking the listeners?

**Comment by dagatsoin** [comment]
I don't check the listeners. It is just a deduction because I need to manually stop this. Do you have a snippet to check if $destroy is fired ?

I dis this but nothing logs:
```
$meteor.autorun($scope, function(){
  		$scope.getReactively('trackersIds',true);
		$scope.$meteorSubscribe('traces', {trackersIds:$scope.trackersIds}).then(function(){
			
			// I try to watch $destroy with this
	  		$scope.$on("$destroy", function() {console.log("destroy");});

			if ($scope.traces && $scope.traces.stop) {
				// stop the old subscription - this unbinds watchers and cleans up memory
				$scope.traces.stop();
			}
			$scope.traces = $scope.$meteorCollection(Traces);
		});
});
```

**Comment by auterium** [comment]
@dagatsoin man it took me almost 20 mins to figure out this...

Here's your problem: you should not call for $meteor.collection or $scope.$meteorCollection within the autorun. Each autorun's invalidation stops any subscription created inside it to replace it for the new one, but it doesn't do the same for collections or objects. You should be using $scope.$meteorCollection outside the autorun as it can be created only once and it will be reactive based on what the subscription gets.

Please try the following code:
```javascript
// This needs to be $scope.$meteorCollection so the collection will be destroyed when the user leaves the controller
$scope.traces = $scope.$meteorCollection(Traces);

$meteor.autorun($scope, function() {
  // This is better as it's lower level and the subscription will be stopped by Meteor on each autorun invalidation
  $meteor.subscribe('traces', {
    trackerIds: $scope.getReactively('trackersIds')
  });
});
```

Please let us know if it works as expected

**Comment by dagatsoin** [comment]
@auterium, it works like @smoke code but much proper! Your 20 minutes has been very useful indeed. You finally make me understand in which order collection/subscription work! It worse a beer or two if you come to britany :beers:

**Comment by smoke** [comment]
@auterium Great job - definitely seems more proper and cleaner with your solution!

**Comment by auterium** [comment]
Thanks guy, I'm glad it helped! And @dagatsoin, I'll be in Paris for 2 days in september if you want to pay for those beers lol
