### ISSUE TITLE
state templateUrls not working when using traceur compiler.

### ISSUE THREAD

**Issue by vacarsu** [Urigo/angular-meteor#420]
I'm having an issue where ui router isn't able to find my template when using es6. I have a repository up here https://github.com/vacarsu/angular-meteor-es6-issue

I checked all my template urls and they all seem to be correct.
No matter what I try I just keep getting:
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
2VM27550:26323 WARNING: Tried to load angular more than once.

**Comment by Urigo** [comment]
@vacarsu looks like you have 2 different ways to start the paths:

    /client/modules/navbar/views/navbar.ng.html
    client/modules/root/views/root.ng.html

as for ES6 examples, there is this one:
https://github.com/pbastowski/meteor-angular-socially/tree/feature/ng2now

which is also based on the great Angular2.0Now package:
https://github.com/pbastowski/angular2-now

let me know if that helped

**Comment by vacarsu** [comment]
Sorry about the two different paths, that's just me trying different ways. I'll check out the examples.

**Comment by vacarsu** [comment]
Is there anyway to get this working without using angular2now? I'm already using traceur to transpile to es5.

**Comment by vacarsu** [comment]
Small update, I do see my templates being loaded in chrome devtools. I wonder what is going wrong when displaying them.

![screen shot 2015-06-09 at 10 09 49 am](https://cloud.githubusercontent.com/assets/11384972/8064490/e38ce84a-0e8f-11e5-9b43-f95f08702840.png)

**Comment by vacarsu** [comment]
If I hardcode the template directly in the state declaration it works perfectly. Obviously this is something I want to avoid doing. I'm trying to port a large app from MEAN stack to angular-meteor, and I'm stopped at this point.

**Comment by Urigo** [comment]
@vacarsu what do you mean by hardcoding the state declaration?

from looking at the code and this issue:
http://stackoverflow.com/questions/27944011/angular-ui-router-traceur-controller-assignation

It looks like it might be a problem of loading order.

Can you try placing everything in one file in the right order, just to make sure that that's the problem?

**Comment by vacarsu** [comment]
@Urigo I mean if I copy the html from the .ng.html file and put it in the config state ```template: '<div></div>'```

it works perfectly. At any rate, I got fed up and implemented angular2-now and got everything working.

**Comment by Urigo** [comment]
@vacarsu the loading order in Meteor is different:
http://docs.meteor.com/#/full/structuringyourapp

This is why it's possible that even thought it worked for you in MEAN it won't work for you here.

Also, I think the library you used (harmony) is not well maintained.

If you don't like angular2Now, maybe you should try `Babel`?
https://github.com/grigio/meteor-babel

**Comment by vacarsu** [comment]
@Urigo  Now that you mention it, when implementing angular2-now I do remember needing to move my app folder outside of the modules folder. This must have been the problem. At any rate, using angular2-now has made the structure even stronger if anything so it's not that I don't like it. I was just trying to get the app working with as few changes as possible.

I got everything working with angular2-now and babel.

**Comment by Urigo** [comment]
@vacarsu very cool, I'm happy it worked for you.
I wonder what is the state of harmony and if they should warn people not to use it...

Also, if you want as little changes as possible, maybe using just Babel by itself is enough
