### ISSUE TITLE
angular-meteor requires "mquandalle:bower@0.1.11"(?) and causes some issues

### ISSUE THREAD

**Issue by RobinBuschmann** [Urigo/angular-meteor#426]
If i'm using "angular-meteor" in a custom package, meteor always installs the "mquandalle:bower@0.1.11" package for my test project. Which in turn causes that meteor resolves some dependencies defined in a bower.json file somewhere in the "angular-meteor"-package (?). I guess thats why meteor loads angular.js twice:
After running my project, i'm seeing this in chromes developer console under "Sources":

    /angular:angular/angular.js
    /...
    /urigo.angular/.meteor/local/bower/angular/angular.js

I'm definitely not using meteor-bower in my test project. What can I do to prevent meteor from installing mquandalle:bower or at least to prevent bower from resolving dependencies? Or am i completely wrong with my assumption?

thanks in advance

my test repo:
https://github.com/RobinBuschmann/meteor-example

**Comment by netanelgilad** [comment]
Hey @RobinBuschmann ,
It seems like your project is using a very old version of angular-meteor (0.3.6) which still used bower. Can you try updating to the latest version? `meteor update urigo:angular`

**Comment by RobinBuschmann** [comment]
hey, thank you. that fixed the issue. I'm new to meteor and just wondering why meteor installs an old version, when no explicit version is specified.

    api.use('urigo:angular', 'client');

**Comment by netanelgilad** [comment]
That is good question. Did you create the repository along time ago when it had angular-meteor already and then you did some changes?
Meteor saves package version in the `versions` file, so if you had angular-meteor on the project a long time ago and the removed it, and recently re-added it, it may save the version from the first time.
That is just my wild guess...

**Comment by RobinBuschmann** [comment]
No actually not. I've created the project and the repo yesterday and i've tested it again a few minutes ago with a new project (+ package, which integrates meteor-angular): again meteor installed version "0.3.6"

**Comment by ccortezia** [comment]
This happened to me too, and forced me to hard-bind all my packages to the current latest version. Couldn't figure out the reason yet.

**Comment by Urigo** [comment]
That's very strange and looks like it might be a bug in Meteor's version solver.
@RobinBuschmann , can you please open an issue in Meteor and reference it to here?
thanks

**Comment by Urigo** [comment]
@RobinBuschmann now that I saw the issue I realize you placed `urigo:angular` inside a package so that is Meteor's behaviour and you should specify the right minimum version your package is dependent upon.
