### ISSUE TITLE
Problems trying to publish ui-grid to Atmosphere

### ISSUE THREAD

**Issue by mgrivera** [Urigo/angular-meteor#427]
Hi all, I'm trying to publish ui-grid (not ng-grid, which has been published!) to Atmosphere. I'm trying to follow instructions in step 17 in tutorial, but have some problems. This is what I did: 

1) installed bower 
2) (using bower) installed ui-grid in a directory in my PC 
3) cloned meteor-package-publisher to the same directory 
4) created a json (package) file for ui-grid (ui-grid.json). I did this, following the sample file in tutorial 
5) run meteor-package-publisher: 
     node meteor-package-publisher ui-grid.json 
6) got this error: cannot find module 'minimist' 

Finally, this is the content of the "json" file (ui-grid.json): 

{
  "source": {
    "type": "bower",
    "name": "angular-ui-grid",
    "version": "3.0.0-rc.21"
  },
  "destination": {
    "atmospherePackageName": "angular-ui-grid",
    "atmosphereOrganizationName": "smrsoftware",
    "summary": "Angular ui-grid - version 3",
    "git": "https://github.com/angular-ui/ng-grid",
    "documentation": null,
    "versionsFrom": "METEOR@0.9.0.1",
    "filesToAdd": [
      {"name": "./bower_componets/angular-ui-grid/ui-grid.css", "platforms": ["client"]},
	  {"name": "./bower_componets/angular-ui-grid/ui-grid.eot", "platforms": ["client"]},
	  {"name": "./bower_componets/angular-ui-grid/ui-grid.js", "platforms": ["client"]},
	  {"name": "./bower_componets/angular-ui-grid/ui-grid.svg", "platforms": ["client"]},
	  {"name": "./bower_componets/angular-ui-grid/ui-grid.ttf", "platforms": ["client"]},
	  {"name": "./bower_componets/angular-ui-grid/ui-grid.woff", "platforms": ["client"]} 
    ],
    "use": [
      {"name": "angular:angular@1.2.16", "platforms": ["client"]}
    ]
  }
}

Thanks in advance for your help and bye ...

**Comment by Urigo** [comment]
@dotansimha

**Comment by dotansimha** [comment]
Hi @mgrivera, please follow these instructions:
1. clone meteor-package-publisher into a clean folder. 
2. run "npm install" in this folder
3. create a JSON file for you package (it looks like the one you created is a good one)
4. run "node ./meteor-package-publisher test.json" in this folder

Note: You need does not need to install ui-grid from bower, the publisher does this for you.

**Comment by mgrivera** [comment]
@dotansimha Thanks for ansewring! I will try this later and post results ...

**Comment by mgrivera** [comment]
Hi dotansimha, sorry for just wanting to check with you before running package-publisher: 

1) this is the bower site for ui-grid (it is *not* its github site, just the (github) bower site): 

https://github.com/angular-ui/bower-ui-grid 

2) this is the bower.json file in the bower site: 

{
  "name": "angular-ui-grid",
  "version": "3.0.0-rc.22",
  "main": [
    "./ui-grid.css",
    "./ui-grid.eot",
    "./ui-grid.js",
    "./ui-grid.svg",
    "./ui-grid.ttf",
    "./ui-grid.woff"
  ],
  "ignore": [],
  "dependencies": {
    "angular": ">=1.2.16 <=1.3.x"
  },
  "homepage": "http://ui-grid.info"
}

3) finally, this is my "test.json" file, describing "ui-grid" to meteor-package-publisher: 

{
  "source": {
    "type": "bower",
    "name": "angular-ui-grid",
    "version": "3.0.0-rc.22"
  },
  "destination": {
    "atmospherePackageName": "angular-ui-grid",
    "atmosphereOrganizationName": "smrsoftware",
    "summary": "Angular ui-grid - version 3",
    "git": "https://github.com/angular-ui/bower-ui-grid",     // note this is ui-grid bower site 
    "documentation": null,
    "versionsFrom": "METEOR@0.9.0.1",
    "filesToAdd": [
    {"name": "./ui-grid.css", "platforms": ["client"]},
	  {"name": "./ui-grid.eot", "platforms": ["client"]},
	  {"name": "./ui-grid.js", "platforms": ["client"]},
	  {"name": "./ui-grid.svg", "platforms": ["client"]},
	  {"name": "./ui-grid.ttf", "platforms": ["client"]},
	  {"name": "./ui-grid.woff", "platforms": ["client"]} 
    ],
    "use": [
      {"name": "angular:angular@1.2.16", "platforms": ["client"]}
    ]
  }
}

4) note the dependencies section in bower.json tells about a range of angular versions ("angular": ">=1.2.16 <=1.3.x"). Do I have to express that range in package-publisher test.json file; or telling just: angular:angular@1.2.16 is fine? If I have to tell the range of versions, how do I express that? Then same as in bower.json file? 

Many thanks again for your help and bye ...

**Comment by mgrivera** [comment]
Hi @dotansimha, I followed your instructions and think am closer, but errors keep showing up ... 

This is the error message: 

C:\angular-meteor\meteor-package-publisher>node ./meteor-package-publisher ui-grid.json
Hi, I am the Meteor packages publisher. All you have to do is sit back and let the evening go.
bowerParser initialized!
bowerParser cleaning bower_components

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: rimraf: options should be object
    at Function.rimrafSync [as sync] (C:\angular-meteor\meteor-package-publisher\node_modules\rimraf\rimraf.js:262:10)
    at BowerParser.clean (C:\angular-meteor\meteor-package-publisher\lib\parsers\bowerParser.js:14:12)
    at C:\angular-meteor\meteor-package-publisher\meteor-package-publisher.js:20:18
    at fs.js:271:14
    at C:\angular-meteor\meteor-package-publisher\node_modules\bower\node_modules\bower-config\node_modules\graceful-fs\graceful-fs.js:104:5
    at Object.oncomplete (fs.js:107:15)

C:\angular-meteor\meteor-package-publisher>

=========================================================================

Im my json file, I don't know if these are correct: 

1) git site is bower site (ie: not ui-grid site). I think this should be correct, because the grid js (an other) files are there
2) I'm using these to indicate Angular dependency: 
"use": [
			{"name": "angularjs:angular@1.3.15", "platforms": ["client"]}
		]

==========================================================================
This is the complete json file: 

{
	"source": {
	"type": "bower",
	"name": "angular-ui-grid",
	"version": "3.0.0-rc.22"
	},
	"destination": {
		"atmospherePackageName": "angular-ui-grid",
		"atmosphereOrganizationName": "smrsoftware",
		"summary": "Angular ui-grid - version 3",
		"git": "https://github.com/angular-ui/bower-ui-grid", 
		"documentation": null,
		"versionsFrom": "METEOR@0.9.0.1",
		"filesToAdd": [
			{"name": "./ui-grid.css", "platforms": ["client"]},
			{"name": "./ui-grid.eot", "platforms": ["client"]},
			{"name": "./ui-grid.js", "platforms": ["client"]},
			{"name": "./ui-grid.svg", "platforms": ["client"]},
			{"name": "./ui-grid.ttf", "platforms": ["client"]},
			{"name": "./ui-grid.woff", "platforms": ["client"]} 
		],
		"use": [
			{"name": "angularjs:angular@1.3.15", "platforms": ["client"]}
		]
	}
}

Many thanks for your help and bye ...

**Comment by dotansimha** [comment]
Looks like your rimraf version is incorrect. 
The package.json specify ^2.3.2 and you might got the newer version.
Please try to run this in the publisher's folder: 
npm install rimraf@2.3.2

**Comment by mgrivera** [comment]
Hi @dotansimha, 

Wow, I just keep having errors when running this tool. Now it seems it almost completed, but threw and error just before finishing (I suppose ...). 

This is a copy of the screen: 

![untitled](https://cloud.githubusercontent.com/assets/12546268/8337392/b5395f14-1a74-11e5-8dab-055628dff766.png)


It seems I have to have an account in Meteor, but I have one and is what I am giving in "json" file (smrsoftware). Any ideas how to continue with this? 

Many thanks for keeping with this issue and bye

**Comment by dotansimha** [comment]
Hi @mgrivera ,
Please try to make sure logged into into meteor by running `meteor login` command in any folder. after the login proccess is done, please try to publish again.

**Comment by mgrivera** [comment]
Hi @dotansimha, 

Wow, it seems, at last, the package was published successfully. I even went to Atmosphere and could see the package there (smrsoftware:angular-ui-grid (v3)). It is a little late for me to install (meteor create ...) it in an meteor application and test it to see if it function correctly. I'll try to do it tomorrow. 

Here is the screen of meteor-package-publisher in action: 

![untitled](https://cloud.githubusercontent.com/assets/12546268/8343540/3133c430-1aa0-11e5-86ee-9665326ea943.png)

I'll comment back soon after trying to use the grid in my meteor application. 

In the meantime, many thanks for all your help (and patience!). Bye ...

**Comment by dotansimha** [comment]
@mgrivera Great! 
@Urigo can we close this now?

**Comment by Urigo** [comment]
thanks guys!

**Comment by mgrivera** [comment]
Sorry for commenting once again ... 
Just to say that I added ui-grid to my app and tested it with some data from a collection. It seems it works correctly. 
Thanks and bye ...
