### ISSUE TITLE
Bug - Date javascript object convert to {} on $meteor.collection(..).save

### ISSUE THREAD

**Issue by rgnevashev** [Urigo/angular-meteor#428]
file angular-meteor-utils.js line 28
`if( !angular.isObject(data) || data instanceof File) { return data; }`
replace to
`if( !angular.isObject(data) || data instanceof File || data instanceof Date) { return data; }`

**Comment by Urigo** [comment]
Thanks @rgnevashev and thanks @cantoine , I've added tests to make sure we won't make the same mistake again
