### ISSUE TITLE
waiting for data loaded before handelling collection ?

### ISSUE THREAD

**Issue by dagatsoin** [Urigo/angular-meteor#429]
I need to wait the end of a subscription. I handle a subscription about 2000 items in a Leaflet heatmap. I want the heatmap displays after the subscription is complete.
I tried to use MeteorSubscribe.then() promise, but it fires before the end. So my heatmap is incomplete.

`Template.subscriptionsReady` is the perfect thing to handle that but how I use it in angular-meteor ?

**Comment by vacarsu** [comment]
Can you show how you're using MeteorSubscribe in the controller? The only time I've had issues with subscription data not binding to the template is when using ng-controller in index.html

**Comment by dagatsoin** [comment]
Sure, here it is.

  	$scope.traces = $scope.$meteorCollection(Traces);

	$meteor.autorun($scope, function(){
  		$scope.getReactively('trackersIds',true);
		$scope.$meteorSubscribe('traces', {trackersIds:$scope.trackersIds}).then(function(){			
		  	$scope.tracesCount = $scope.$meteorObject(Counts ,'numberOfTraces', false).count;
		});
  	});

 I found a work around comparing the total number of items `tracesCount` in a reactive loop at each `traces` change.

  	$meteor.autorun($scope, function() {
		$scope.getReactively('traces',true);
		if($scope.traces.length == $scope.tracesCount && heat != null){
			var promise = makeTraces(); // A function that extract lats longs 
									// from $scope.traces and put them in tracesCoords[]
			promise.then(function(finished) {
				heat.setLatLngs(tracesCoords);
				heat.redraw();
			});
		}
  	});

**Comment by vacarsu** [comment]
In your first example looksl ike your trying to get a collection without subscribing to it. 
```
$scope.traces = $scope.$meteorCollection(Traces);
```
should be
```
$scope.traces = $scope.$meteorCollection(Traces).subscribe('traces');
```
Or combine it in the counts object subscription.

**Comment by dagatsoin** [comment]
A trace has a trackerId property.
My first autorun re-subscribe to the traces when the list of trackersIds change. This works well.

The problem is that the subscribe promise doesn't wait the end of loading to resolve.
So my `then()` script start to handle an incomplete collection of traces.
It does:
- subscribe
- begin to load the collection
- resolve the promise and continue the script (so with incomplete collection)
- finish to load the collection

 And I want:
- subscribe
- wait the end of the datas loading
- handle my complete collection.

**Comment by netanelgilad** [comment]
Hey @dagatsoin,
That is an interesting issue that I encountered a while back as well but haven't resolved yet. I suspect that this may be a Meteor issue but I am not sure. Can you try just using `Meteor.subscribe` and add a callback as the last parameter for when the subscription is ready?
From my previous trials I think that the ready event of the publication gets to the client before all the items in the publication actually get to the client.
Try it and share with us what happens

**Comment by dagatsoin** [comment]
According to [this post](https://forums.meteor.com/t/this-ready-in-a-publication/1681/10) It seems that the `this.ready()` on the server is fired independently to the end of the data sending.
So client receive a "ready" event (which resolve the $meteorSubscribe promise) while documents are still loading.

So I have to do dome modification on my publish function on the server. I will do some test with `added` then this.ready() and share the result.

**Comment by dagatsoin** [comment]
So. I am back to my issue. For now I try to not use the $meteorSubscribe callback but orignial Meteor.subscribe callback. But this does not work
I have in my client:

	$meteor.autorun($scope, function(){
  		$scope.getReactively('trackersIds',true);
		Meteor.subscribe(
			'traces',
			{
				trackersIds:$scope.trackersIds
			},
			{
				onReady:function(){console.log("rezdy")}
			}
		);
	});

And on the server I use: 

	Traces.find({trackerId: { $in : trackersIds}}).forEach(function (trace) {
		self.added( "traces", trace._id);
	});
	self.ready();

But my client onReady callback never runs. I know the self.ready() is fired because it works when I use $meteorSubscribe callback. Does Meteor Angulart support takes clare of the onReady onStop callback ?

**Comment by dagatsoin** [comment]
I think I will close this issue. It is not a real Angular Meteor issue but more a Meteor behavior.
Finally my workaround with the autorun works well. Even if Template.subscriptionsReady implementation in Angular Meteor could be more elegant.

**Comment by Tallyb** [comment]
It made me think that if the subscription is an observable - does it really "finishes"?

**Comment by dagatsoin** [comment]
I would say yes. Because "dead" could be a state.
