### ISSUE TITLE
It is not clear/consistent where should users ask questions about angular-meteor when they face difficulties 

### ISSUE THREAD

**Issue by oshai** [Urigo/angular-meteor#432]
right now, if a user of angular-meteor has a problem of understanding the api or a bug in his code he can open an issue here or in stackoverflow or in meteor forum or in angular forum or maybe some other places (gitter chat?).
I think this consistency issue make it less transparent to community, and make communication harder. In addition, it is much harder to google for issues that are related to angular-meteor (it will direct you to issues either in angular or meteor)
I suggest to make it more clear where should questions be asked, I think the most reasonable place is stackoverflow with angular-meteor tag: http://stackoverflow.com/questions/tagged/angular-meteor
For bugs/suspected bugs, the best place is this repository in issues.
I suggest that it will be documented in the readme of this repository.
What do you think?

**Comment by Tallyb** [comment]
+1

**Comment by mgrivera** [comment]
Brilliant. I'm very new to all this stuff and things are just becoming easier for me, just a little bit. But I like the whole direction this angular-meteor stuff is taking. Organizing communication this way is a step forward. Thanks ...

**Comment by Urigo** [comment]
Very good point.
I've hope I've made it clear here:
https://github.com/Urigo/angular-meteor/commit/fe1484e8d6968a785d7eef5c3ee2f0a65da6b0b8

**Comment by oshai** [comment]
Thanks looks good.
