### ISSUE TITLE
reactive variable across controllers

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular-meteor#433]
please advise: 
I have a varialbe (actually 2) that I want to be reactive across controllers, as it impact the behaviour of multiple controllers & views. I have a top level controller which remains during all time, and the other controllers may change, although there are 2 views on the page (with 2 controllers) that both  reflect the reactive variable. 
My options: 
- Sharing data among controllers is typically done via angular services, but service variables can't be made reactive (right?). 
- Same goes for $rootscope variables (?) 
- so the only option is to use session variables  and bind them to local scope varialbes on every scope. 

Any thoughts and ideas?

**Comment by netanelgilad** [comment]
You can just add a variable on your scopes that points to the variable in
the service. Than use get reactively on the scope variable name (which is
just a reference to the service variable). Should probably work.

**Comment by Urigo** [comment]
This should work as we do something similar ourselves.
Also, it's not a good practice but because you mentioned it - getReactively does work on $rootScope variables

**Comment by danimbrogno** [comment]
I'm struggling with the same concept. An example of how to properly implement reactive variables within an angular service and then access them via a controller would be very helpful. I'm not quite following what you are suggesting @netanelgilad. Any help would be appreciated.
