### ISSUE TITLE
Collection's transform not work.

### ISSUE THREAD

**Issue by endows** [Urigo/angular-meteor#434]
I want to use transform like this.

```
Channels = new Mongo.Collection('channels')
Posts = new Mongo.Collection('posts',{transform:(doc)->
  doc.channel = Channels.findOne(doc.channel_id)
  doc
  })
・・・
$collection(Posts).bind($scope, 'posts');
```

but it is not work.angular-meteor is not support transform?

**Comment by netanelgilad** [comment]
Hey @endows,
Notice that you are using the deprecated api for collection. Try doing:
```js
$scope.posts = $meteorCollection(Posts);
```
`$meteorCollection` should work with Collection transforms. Try it and tell us how it goes.

**Comment by endows** [comment]
Hi @netanelgilad Thanks to reply. There is bad new and good news.
First bad news.I used ```$meteorCollection```,but same result.
Next is good news. I try this
```
Channels = new Mongo.Collection('channels')

Posts = new Mongo.Collection('posts')
Posts._transform = (doc)->
   #doc.channel = Channels.findOne(doc.channel_id)
    doc.channel = Channels.findOne()
    doc
```
If, ```findOne```'s query is empty,result inserted ```Channel``` object.

**Comment by endows** [comment]
I settled this program. This is so simple.
```_id``` must be ```STRING``` like this.
```
Channels._idGeneration = 'STRING'
```
