### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/angular-meteor#442]
I first thought it was due to #436 , but I removed that similar code where I call a function to resolve image url and I still get Maximum call stack exceeded on a diffObjectRemovals. I see it's a recursive function, so I guess the condition to break out of the recursion is not good. 

I don't know how to see what is calling this function and how it came to that.

**Comment by Tallyb** [comment]
I had a similar issue. Do you $watch a reactive car? Do you use transform function? 
Check any $meteor.autorun code as well.

**Comment by Urigo** [comment]
@MilosStanic can you please share what is different in your own code?

**Comment by MilosStanic** [comment]
I think #467 should solve this issue.

**Comment by Urigo** [comment]
great, new version coming soon
