### ISSUE TITLE
.subscribe send Array. How i can use meteor to find somethik?

### ISSUE THREAD

**Issue by michalmw** [Urigo/angular-meteor#445]
Hello,
i have array:
$scope.tablica = [];
When i push only one element to array all is ok. But if i splice or push another element have problem. Then Meteor/MongoDB callback all collecion.

My code:

      $meteor.autorun($scope, function() {

         $scope.wybrane = function(skladnik) {
            $scope.search = '';
            if ($scope.tablica.indexOf(skladnik) != -1){
                var idx = $scope.tablica.indexOf(skladnik);
                $scope.tablica.splice(idx, 1);
            }
            else
                $scope.tablica.push(skladnik);

            $scope.search = $scope.tablica;
       
            $meteor.subscribe('smoothie', {
                limit: parseInt($scope.getReactively('perPage')),
                skip: parseInt(($scope.getReactively('page') - 1) * parseInt($scope.getReactively('perPage'))),
                sort: $scope.getReactively('sort')
            }, $scope.tablica).then(function(eeee) {
                console.log('eeee',eeee)
                $scope.smoothieCount = $meteor.object(Counts,'numberOfParties', false);
            });
        }
    });

And smoothie.js
```
         Meteor.publish("smoothie", function (options, nazwa) {
                  if(nazwa.length < 1) {
                  console.log('here:',nazwa);
                  Counts.publish(this, 'numberOfParties', Smoothie.find({}), {noReady: true });
		return Smoothie.find({}, options); 
	}
	else {
		console.log('here...:', nazwa)
	 Counts.publish(this, 'numberOfParties', Smoothie.find({
	 	'skladniki' : {'$in': nazwa}
 }), {noReady: true });
	return Smoothie.find({
		'skladniki' : {'$in': nazwa}
	}, options); 
	}
                  });
```

smoothie.ng.html
```
 <li dir-paginate="smothie in smoothie | itemsPerPage: perPage" total-items="smoothieCount.count">
      <a href="/skladniki/{{skladnik._id}}">{{smothie.nazwa}}</a>
      <p>{{smothie.opis}}</p>
      <ul>
      	<li ng-repeat="skladnik in smothie.skladniki">
      		{{skladnik}}
      	</li>
      </ul>
      <button ng-click="remove(skladnik)">X</button>
    </li>
    <dir-pagination-controls on-page-change="pageChanged(newPageNumber)"></dir-pagination-controls>
```

**Comment by Tallyb** [comment]
The push and splice are reactive and do not need to be inside the autorun block.

**Comment by michalmw** [comment]
Ok, but this no solution for my problem ;/

**Comment by Urigo** [comment]
@michalmw can you share this code in an example repo so I can test and work on it?
or better then that, create a failing test in the tests folder

thanks

**Comment by michalmw** [comment]
Hello Urigo ;-) 

My code:
http://91.196.50.33/smoothie.tar.gz

Mongodb:
````
meteor:PRIMARY> db.smoothie.find({});
{ "_id" : "x82fzpNvfA74QMSXv", "nazwa" : "OOO", "opis" : "ooo", "skladniki" : [ "limonka" ], "owner" : "jRDNn3L2cCDefJdLP" }
{ "_id" : "MePRYSBTBzKS33ktn", "nazwa" : "wwww", "opis" : "wwww", "skladniki" : [ "Truskawka", "limonka" ], "owner" : "jRDNn3L2cCDefJdLP" }
{ "_id" : "aJ6Bhhhrfhv3S9Xxp", "nazwa" : "truskawka", "opis" : "truskawka", "skladniki" : [ "Truskawka" ], "owner" : "jRDNn3L2cCDefJdLP" }
`````
And next collection: 
````
meteor:PRIMARY> db.skladniki.find({});
{ "_id" : "Zxt34Hybce4zXcxe9", "nazwa" : "Truskawka", "wartosci" : "Jakieś wartości truskawek", "owner" : "jRDNn3L2cCDefJdLP" }
{ "_id" : "zLH72mSDBTqxQNPdg", "nazwa" : "limonka", "wartosci" : "Pyszna i zdrowa!", "owner" : "ZyrTMwiKhr74z7Yxk" }
````

How this working?
When you open in localhost/smoothie and You have 2 Icon'
'Truskawka', 'Limonka'. If you click in e.x. 'Limonka' mongo should callback only smoothie with 'limonka'. (this working)

If you click 'Truskawka' and 'Limonka', mongo should callback smoothie (first in limonka and truskawka) but should callback too only limonka and only truskawka. (working in 50%)

If you unclick product you should have smoothie with only 'selecy' product, or if you don't have select nothink you should have all smoothie.

PS. Uri im your fan ;). I watched you all video ;-). My girlfriend want throw away from home because i only speak about you :D and Meteor-Angular :D

**Comment by michalmw** [comment]
@Urigo or someone? Can help?

**Comment by Urigo** [comment]
@michalmw I can't access this file you sent...
can you try again or share a repo?

**Comment by michalmw** [comment]
@Urigo is now ok ;-)
http://91.196.50.33/smoothie.tar.gz

I wait for you answer ;-)

**Comment by Urigo** [comment]
@michalmw this is a very strange file, looks like a compiled version or something :)
can you please share a repo with the complete Meteor project?

**Comment by michalmw** [comment]
@Urigo Ohh sorry.
http://91.196.50.33/smot.tar.gz -- this is correct

**Comment by Urigo** [comment]
@michalmw no problem, but can you please also add the `.meteor` folder (without the `.meteor/local` folder)

thanks

**Comment by michalmw** [comment]
@Urigo 
Now is ok.
http://91.196.50.33/smot2.tar.gz

I try change somethink i code. but this still not working. In my 4 post in this topic you have instrution you instructions on how I wanted to make it work

Thx.

**Comment by Urigo** [comment]
@michalmw is it ok if I'll publish this in a repo or is it a private project?

**Comment by michalmw** [comment]
@Urigo 
This is portal for my girlfriend :woman: 
You can publish this ;D I just want to make it work.  ;-) She Too

**Comment by Urigo** [comment]
OK it's live here:
https://github.com/Urigo/issue-445

It looks like you have a Mongo error:


     Exception from sub smoothie id xgeXZWoKgta6TrpcC Error: Exception while polling query 
       {"collectionName":"smoothie","selector":{"skladniki":{"$in":[{"$regex":"sadfasdf"}]}},"options":
      {"transform":null,"limit":3,"skip":0,"sort":{"name":1}}}: Can't canonicalize query: BadValue cannot nest
       $ under $in

I have to leave now but now maybe someone from the community can help you while I'm away

**Comment by michalmw** [comment]
@Urigo i do this in another way.

1. Find all in my collecions.
2. Do filtr in angular: 
````
ng-repeat="smothie in smoothie | filter:wybraneSkladniki"
````
3. In controller do:
```` 
$scope.wybraneSkladniki = function(item) {
        var tak = 0;
        //sprawdza czy talica jest pusta 
        if($scope.tablica.length < 1)
            tak = 1;
        else {
            angular.forEach(item.skladniki, function(value, key) {
                 angular.forEach($scope.tablica, function(skladnik, keyy) {
                    if(value == skladnik) {
                        tak = 1;
                    }
                 });
            });
        }
        return tak == 1;
    };
`````
And working ;-)
Thx for you time and help ;-)
