### ISSUE TITLE
$http.get on local path

### ISSUE THREAD

**Issue by babakness** [Urigo/angular-meteor#447]
Hello. There is no way to do something like $http.get('/local/path') because of the way meteor works. Anything equivalent? A way to pull in a local template file and use $interpolate, for example. 

Regards.

**Comment by babakness** [comment]
Sample use case

http://onehungrymind.com/angularjs-dynamic-templates/

**Comment by netanelgilad** [comment]
Why should `$http.get` not work in meteor? Just make sure to put the template files in the public folder so that meteor serves them and then use $http on the path (after the public folder).

**Comment by Tallyb** [comment]
Might work, but then again, isn't it better to use $tempateCache directly instead? Also ui-router templateProvider can be used for dynamic templating.

**Comment by babakness** [comment]
Thanks for feedback.
