### ISSUE TITLE
Tutorial - Step 9 Question

### ISSUE THREAD

**Issue by jaypanares** [Urigo/angular-meteor#448]
Hi, currently going through the awesome tutorial.

I noticed that the guide says that `.subscribe('parties');` should be added to `$scope.party = $meteor.object(Parties, $stateParams.partyId, false)` in case the user "doesn't go through the parties router".

Why does clicking the link to the details page work, but changing the URL manually to the details page does not load `$scope.party` unless `.subscribe('parties)` is added?  Is this a quirk of angular-meteor?

Hoping someone can shed some light on this.

Thanks, and keep up the great work!

**Comment by mgrivera** [comment]
Hi jaypanares, 

Maybe what they are trying to say is that: 
1) if you *first* open parties route, this page (route) will load parties and those docs will be there when you open details page; 
2) if you don´t open parties page first, then parties wont be there, so it is "safe" to add ".subscribe('parties')" just to be sure that parties will be there in case you have not opened parties page before. 

Also note that you can do a: "$meteor.subscribe" ... and then an: "$scope.var = $meteor.collection()" (or $meteor.object()). Using $meteor.collection().subscribe() is just "syntactic sugar" to "$meteor.subscribe()" and then "$scope.var = $meteor.collection()". 

Just my thoughts about your doubts  ...

**Comment by netanelgilad** [comment]
@mgrivera explained it correctly. This is not an angular-meteor quirk or a quirk at all for that matter. The thing is the way we setup our states with ui-router. When the browser goes to a details page directly, the state of `partyDetails` is loaded and it's controller too but the controller of the state `parties` is not loaded so the `subscribe` inside that controller never happens. That is why the `PartyDetailsCtrl` has to subscribe by itself, to make sure the data it needs is there.
This could be addressed by having the `partyDetails` state be a child state of `parties`, which would make the `PartiesListCtrl` load and subscribe but I guess that is outside of the scope of the tutorial.

**Comment by Tallyb** [comment]
Disclosure: shameless self promotion!!! 
For subscriptions and collections, you may find this blog post useful: https://medium.com/angular-meteor/coll-pub-sub-with-angular-meteor-cb13fe48f570

**Comment by mgrivera** [comment]
Excellent blog post. I'll read it ... again ...

**Comment by jaypanares** [comment]
Thanks for the responses everyone!  I get it a bit better now.  Since there
is no `.subscribe('parties')` being called when going directly to the
details page, no collection data is being pushed to the client.  Is it safe
to say that once a `.subscribe()` has been called, the subscription
persists even though views and controllers change?

**Comment by Tallyb** [comment]
Yes, but...
Yes - when you call $meteor.subscribe you get a promise with a handler. Any time you want to stop the subscription it is done as handler.stop(). 
But - if you use the $scope.$meteorSubscribe variant - the subscription will be automatically stopped on destroy of the scope. 
not sure about calling twice...

**Comment by mgrivera** [comment]
1) Is it safe to say that once a `.subscribe()` has been called, the subscription
persists even though views and controllers change?

Yes! As I can see in my application, you load some data in one route; go to another route, the data is there. So, collections (in minimongo) persists among routes ... 

2) Also, does calling `.subscribe('parties')` twice have any effect on the app?

I was testing this case, just for curiosity. It seems something wrong happens and results are unexpected. In my opinion, calling subscription twice should have no effect on data and the program. The effect should be just to refresh the collection (with same data). However, this has have wrong results in my case. 

Of course you can stop a subscription and call it safely again ... but it shouldn't produce errors if calling twice without stopping it first.

**Comment by Tallyb** [comment]
As of twice, thrice or more: I tried this one: ng-leaderboard-subs3.meteor.com
No problem. As expected, the data will reside locally until all subscriptions are stopped.
