### ISSUE TITLE
angular-meteor and autoform

### ISSUE THREAD

**Issue by kwk** [Urigo/angular-meteor#450]
Hi there,

I'm not new to angular but to angular and meteor. I have a simple app running and I've defined a model that I successfully generated a form for using [aldeed:meteor-autoform](https://github.com/aldeed/meteor-autoform/). I can use this form to insert items into my collection. This all works perfectly fine.

BUT, I have no clue how I can show values that already exist in my collection inside an autoform. Here's an [example](http://autoform.meteor.com/updateaf) that works if you only have meteor.

In my simple application I've generated **list** and **details** page for books using the angular-meteor package. Therefore the object that I want to show inside of the autoform is available in my details controller like this:

```javascript
$scope.book = $meteor.object(Books, $stateParams.dockerhostId);
``` 

How can I get `$scope.book` inside an autoform template that looks like this:

```html
  {{#autoForm collection="Books" type="update" id="booksUpdateForm"}}
      {{> afFormGroup name="name" template="bootstrap3-horizontal" label-class="col-sm-3" input-col-class="col-sm-9"}}
  {{/autoForm}}
```

Thank you in advance!
-Konrad

**Comment by kwk** [comment]
Hi,

I've found this way, although it seems to fetch the document from MongoDB twice, doesn't it?. In my controller I use the `Template.MY_AUTOFORM_ID.helpers(MY_OBJECT)` function to register a variable that I can use in the `{{#autoForm}}` template:

**book-detail.controller.ng.js**:
```javascript
'use strict'

angular.module('myapp')
  .controller('BookDetailCtrl', function ($scope, $stateParams, $meteor) {
    $scope.book = $meteor.object(Books, $stateParams.booksId);
    $meteor.subscribe('books');

   Template.booksUpdateForm.helpers({
      selectedBookDoc: function () {
       // This fetches the object from MongoDB again.
        return Books.findOne({_id: $stateParams.dockerhostId});      }
    });

   $scope.save = function () {
      if ($scope.form.$valid) {
        $scope.book.save().then(
          function (numberOfDocs) {
            console.log('save successful, docs affected ', numberOfDocs);
          },
          function (error) {
            console.log('save error ', error);
          }
        )
      }
    };

    $scope.reset = function () {
      $scope.book.reset();
    };
  });
```

**book-detail.html** (Note new `doc=selectedBookDoc`):
```html
  {{#autoForm collection="Books" type="update" id="booksUpdateForm" doc=selectedBookDoc}}
      {{> afFormGroup name="name" template="bootstrap3-horizontal" label-class="col-sm-3" input-col-class="col-sm-9"}}
  {{/autoForm}}
```

I know it works but can this be improved somehow or is it bad practice in any sense?

Thanks in advance.

**Comment by Tallyb** [comment]
I quickly looked at the autoform package. To me it reads: form package for people who do not use angular. automatic insert and update and even advanced validations are so well supported in Angualr, that for me using this package with angular sounds like a reciepe for troubles. Just my 2c.

**Comment by kwk** [comment]
Hi Tally, thanks for replying. What would you recommend for validation?
Another package maybe or just plain angular? Autoform does this all based
on the model so it's pretty convenient to use.

2015-06-19 18:11 GMT+02:00 Tally Barak <notifications@github.com>:

**Comment by Tallyb** [comment]
Any specific use cases? 
Angular has really good mechanism on input + formatting + validation

**Comment by Urigo** [comment]
@kwk look at the example in `meteor-include` API:
http://angular-meteor.com/api/meteor-include#usingangularscopeinsidemeteortemplate

Let me know if getting the scope inside the template helps

**Comment by mgrivera** [comment]
Hi all,

Have you checked angular formly? If you are using angular, it seems
appropriate to use it. I see fomly as the autoform package but written for
angular.

For validation, I think collection2 (plus simple-schema) maybe an awesome
choice.

Bye ...

**Comment by kwk** [comment]
@Urigo thank you, your' example helped a lot.

@mgrivera thank you.

**Comment by funkytaco** [comment]
@kwk where should you put your collections in your app directory structure (for security)?

**Comment by funkytaco** [comment]
Also, I'm not sure how to convert the meteor code to AngularJS-Meteor compatible code:

For: 
>                            <template name="insertBookForm">
                              {{> quickForm collection="Books" id="insertBookForm" type="insert"}}
                            </template>

I tried: 
>                            <template name="insertBookForm">
                              <meteor-include src="quickForm" collection="Books" id="insertBookForm" type="insert"></meteor-include>
                            </template>

I have an idea that the template is probably not being parsed by Angular-Meteor (because the filename ends in .ng.html), but not sure of the syntax to use as the docs I've looked at don't cover an alternate syntax for Blaze templates https://www.meteor.com/tutorials/blaze/templates

**Comment by funkytaco** [comment]
One last question, is there any way I can pass the hook for the submitted form back to Angular's scope? I'd like to keep as much Blaze/Meteor out of the project as possible, outside of the stack.

I'm pro bono consulting for a non-profit and have a Meetup.com group that may be helping out on Tuesday. The hackathon will be only 2.5 hours, so I'd rather stick to Angular because I won't have time to ramp up people on the Meteor aspects.

**Comment by kwk** [comment]
I generally went with the directory structure generated by yeoman. You might want to give it a try and see how yeoman lays out the structure in a fresh project:

```bash
npm install -g yo
npm install -g generator-angular-meteor
yo angular-meteor appName
```

I've put the meteor template files right next to `*.ng.html` files.

I'm sorry but I cannot tell out of my mind how to pass the hook back to angular.

**Comment by funkytaco** [comment]
Great, thanks!

**Comment by funkytaco** [comment]
I thought about it for a bit and as far as the autoform speaking to angular, I think I could do a Meteor.call() and somehow get the data to Angular that way.

But on a side note, I'm starting to think this is a bit too much work, though. I don't see why Angular-Meteor is better than just using a MEAN stack. I need to be able to hand off this application to the non-profit, and I think they're going to keep coming back to me as there is compounding complexity here of talking between Meteor/Angular that's not covered in the tutorials.

For my personal tastes, it's pretty great, as I like both Meteor (so far) and AngularJS, but maybe not for this project. I've got alot to think about as I'm going to involve other devs who are volunteering their free time to join.

**Comment by cellulosa** [comment]
hey @kwk, how did you solve this at the end? I'm having the same issue whether I can only retrieve the working object to be updated using the helper (as you did in you original example). Any hint?

    /* book-detail.html */
    <template name="bookDetailTemplate">
        {{> quickForm collection="Books" id="updateBook" doc=book type="update"}}
    </template>

    /* book-detail.ng.html */
    <meteor-include src="bookDetailTemplate"></meteor-include>

    /* book-detail.ng.js */
    angular.module("myapp").controller("BookDetailCtrl",
        function($scope, $stateParams, $meteor){

            $scope.book = $meteor.object(Books, $stateParams.bookId);

            Template. bookDetailTemplate.helpers({
                book: function () {
                    return Books.findOne({_id: $stateParams.bookId});
                }
            });
        }
    );
