### ISSUE TITLE
Collection doesnt resolve on page reload

### ISSUE THREAD

**Issue by cleor41** [Urigo/angular-meteor#453]
```javascript
      .state('story',{
        abstract: true,
        templateUrl: 'client/story/story_layout.ng.html',
        controller: 'StoryLayoutCtrl',
        resolve: {
          currentUser: function($meteor){
            return $meteor.waitForUser();
          }
        }
      })
      .state('story.view',{
        url: '/story/:story_id',
        templateUrl: 'client/story/view/views/storyview.ng.html',
        controller: 'StoryViewCtrl',
        resolve: {
          story: function($meteor,$stateParams){
            return $meteor.object(Stories, $stateParams.story_id, false);
          },
          numbers: function($meteor,$stateParams){
            return $meteor.collection(function(){
              return Numbers.find({story_id: $stateParams.story_id});
            }, false);
          },
          author: function($meteor,$stateParams,story){
            debugger;
            console.log("story",story); //only contains _id property on refresh
            console.log("story._id",story._id) //undefined on refresh
            console.log("story.user_id",story.user_id); //undefined on refresh
            return $meteor.object(Meteor.users, story.user_id, false);
          }
        }
      })
```

When I enter the story.view state from a link, the story object fully resolves inside of the author object (I pass it through to do a nested resolve) but when I refresh the page, it only resolves the _id of the story object and so I can't get the user_id property. This messes up the author retrieval. Since the story object resolves albeit with no properties, I thought this might be a metor-angular issue and not a ui-router bug. I appreciate any help or guidance!

It should be noted that it appears to be a race condition of sorts since every 1 out of 10 tries or so, the properties on the story object exist and the code executes as it should.

**Comment by cleor41** [comment]
I'm not sure why this worked but if I pass in currentUser from the abstract state, story is resolved as expected.

```javascript
         story: function($meteor,$stateParams,currentUser){
            return $meteor.object(Stories, $stateParams.story_id, false);
          }
```

**Comment by netanelgilad** [comment]
Where are you subscribing for the data? It may be that where you are subscribing for the data in Stories collection sometimes happens after the resolve of the meteor object. Maybe adding the currentUser to the story resolve makes it wait just a bit longer (for the resolve of the user) which also makes the data available. Though this is a wild guess...
As a best practice (as I see it) you should resolve subscriptions in your resolves and set the $meteor.object and $meteor.collection on controller itself. That makes sure the data exists before the state loads (as the subscriptions return a promise) and then you can do whatever you need inside the controller.

**Comment by cleor41** [comment]
This is a new project (and my first meteor project) so I'm using autopublish still.

The tutorial said to put all of your subscriptions inside the resolve. I'm still playing around with different app structures so I tossed my models in there too although I like what you proposed. Its getting a little too cluttered.

**Comment by Urigo** [comment]
@cleor41 you should wait for the user also in `story.view`, maybe something like that:


      .state('story',{
        abstract: true,
        templateUrl: 'client/story/story_layout.ng.html',
        controller: 'StoryLayoutCtrl',
        resolve: {
          currentUser: function($meteor){
            return $meteor.waitForUser();
          }
        }
      })
      .state('story.view',{
        url: '/story/:story_id',
        templateUrl: 'client/story/view/views/storyview.ng.html',
        controller: 'StoryViewCtrl',
        resolve: {
          story: function($meteor,$stateParams){
            return $meteor.object(Stories, $stateParams.story_id, false);
          },
          numbers: function($meteor,$stateParams){
            return $meteor.collection(function(){
              return Numbers.find({story_id: $stateParams.story_id});
            }, false);
          },
          author: function($meteor,$stateParams,story){
            debugger;
            $meteor.waitForUser().then(function(){
              console.log("story",story); //only contains _id property on refresh
              console.log("story._id",story._id) //undefined on refresh
              console.log("story.user_id",story.user_id); //undefined on refresh
              return $meteor.object(Meteor.users, story.user_id, false);
            });
          }
        }
      })


But anyway I've changed the docs a bit because I don't think handling those inside the router is the best practice.
It's ok but handling inside the controller can be faster

**Comment by cleor41** [comment]
Thank you all for the responses! I moved all of my data queries to controllers and put
waitForUser/requireUser in each routes resolve. It works as expected.
