### ISSUE TITLE
How long should local host take to run?

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#459]
I have been convinced that the slow response of my system when running meteor was due to my computer and windows 8.1, but even with a new ssd the system is still slow (often it can take two or three minutes for the browser to update.

Note: I am talking about the build time so that I can run and test the app - the response on the server is very fast.
 
I have tried the sample meteor todo app and the response time is a lot faster ( a few seconds) so the question is what is the expected build time in terms of angular meteor?

**Comment by Urigo** [comment]
@JohnAReid this is strange, `urigo:angular` shouldn't take longer to compile..

**Comment by Urigo** [comment]
cab you share more info?

**Comment by JohnAReid** [comment]
@Urigo recorded starting and chrome loading to give your some idea  -  link sent to your gmail account. 

Theses are by far faster than I normally get (perhaps because the same command has been run three of four times in making the recordings.

**Comment by Urigo** [comment]
@JohnAReid I'm not sure I've got your email..

**Comment by JohnAReid** [comment]
@Urigo hi - sorry for the delay in replying: Instead of the video I have a summary of the time taken here:

0 seconds: Preparing project
1 seconds: Started Proxy. looking for packages
2 seconds: Started Proxy. Selecting package versions
6 seconds: Started MongoDB.  Selecting package versions
10 seconds: Building local packages
11 seconds: compileAngularTemlat....
13 seconds: compileTemlates ' fro....
14 seconds: building the application
18 seconds: Starting your app
21:seconds: app running at ... 

overall it takes 21 seconds to load.

**Comment by Urigo** [comment]
is anyone else experience the same numbers with a new project?

**Comment by JohnAReid** [comment]
I have switched from windows 8.1 to Ubunto, the initial start time is about the same BUT any changes made and saved are updated on the browser in less than 2 seconds. My only regret is in not changing from windows 8.1 earlier.

**Comment by Tallyb** [comment]
I am on windows 10 and loading time are totally insane... 


![image](https://cloud.githubusercontent.com/assets/7386255/9833280/8a0bcb24-5999-11e5-8453-ff6b1c22815e.png)

**Comment by JohnAReid** [comment]
I am so pleased I do not wait for Windows 10 - I also remember reading a post on the Meteor main forum that the start time on Windows 10 was slow.

**Comment by MilosStanic** [comment]
I can confirm slow loading and refresh times on Windows 10, about as much as @Tallyb said, even running in a virtual box with Ubuntu. But when I tried to install fresh ubuntu on my laptop, it died on me :(, so I'm still waiting for service to fix it.

**Comment by Urigo** [comment]
Now I'm focused on releasing version 1.0.0 with the current build process so it will support older versions of Meteor.
Right after that (waiting for a pull request in Meteor to be included and shipped) I will release version 1.2 which supports the new build process with caching and hopefully it will improve build times.

**Comment by Tallyb** [comment]
@MilosStanic Did you also encounter the phenomenon that when closing the dev tools - the app loads like charm?

**Comment by MilosStanic** [comment]
@Tallyb I'm not sure. I know that opening dev tools seems to generally slow things in the browser. Especially if you're low on RAM. I can't try as my laptop is still in service.

**Comment by Tallyb** [comment]
@MilosStanic It is embarrassing, but just in case anyone did the same thing: apparently I was throttling at some point and did not turn it off, so no wonder loading with dev tools open took ages...

**Comment by JohnAReid** [comment]
I am closing this issue as it is old and last comment last over a month ago!
