### ISSUE TITLE
error only on deployed app

### ISSUE THREAD

**Issue by ghost** [Urigo/angular-meteor#46]
I'm getting this error when I deploy my app to modulus server.

Uncaught Error: [$injector:unpr] Unknown provider: tProvider <- t
http://errors.angularjs.org/1.3.1/$injector/unpr?p0=tProvider%20%3C-%20t df443c28b894e8e6bbffa91b0330520825ad6b70.js:55

In my development machine everything works fine.Do you have any idea what about is this ?

**Comment by GuyAvraham** [comment]
Can u explain what it mean make sure minsafe? 
I have some deployment issues

**Comment by Urigo** [comment]
@GuyAvraham Use ng-strict-di to make sure your app is minsafe:
https://docs.angularjs.org/api/ng/directive/ngApp

**Comment by GuyAvraham** [comment]
thanks!

**Comment by oshai** [comment]
@Urigo  - I encounter the same problem. the tutorial says specifically it is not required to write explicit strings in the controller declaration (http://angular-meteor.com/tutorial/step_02), because it is using ng-annotate intenally. was that changed along the way?

**Comment by Tallyb** [comment]
Name you js files xxx.ng.js so they will be minifed.

**Comment by oshai** [comment]
thanks! my mistake...
