### ISSUE TITLE
Meteor-Angular upload files?

### ISSUE THREAD

**Issue by michalmw** [Urigo/angular-meteor#461]
Hello,

Have you good tutorial how i can upload file in angular.js and save path to mongodb?

**Comment by mxab** [comment]
Try https://github.com/CollectionFS/Meteor-CollectionFS you can use it in angular-meteor without using anything from angular-meteor. if you want to use the $meteorCollection see this http://angular-meteor.com/api/collectionfs

**Comment by michalmw** [comment]
Hello, this for you answer. 

Someone else can show somethink yet?

**Comment by pbastowski** [comment]
Have a look at this: https://github.com/pbastowski/meteor-upload-files

**Comment by dotansimha** [comment]
Hi @michalmw ,
The new step in the tutorial (20) covers the upload and managing filed with CollectionFS and $meteor.collectionFS.

**Comment by Urigo** [comment]
@michalmw the step is not yet completed and tested so please use cation.
Hopefully tomorrow it will be fully functional and tested

**Comment by Urigo** [comment]
Try this and let me know what you think:
http://angular-meteor.com/tutorial/step_20

**Comment by mikemorris46** [comment]
Hi,
Have been following the tutorial, which is great by the way, but hit some problems on Step 20. Any chance of adding the files for the completed app? Files only go as far as step 19.

**Comment by Anoop-Goudar** [comment]
@Urigo , http://angular-meteor.com/tutorial/step_20 this source is not available anymore.
Please suggest alternate source.

**Comment by Urigo** [comment]
https://angular-meteor.com/tutorials/whatsapp2/ionic/file-upload

**Comment by Anoop-Goudar** [comment]
Thanks @Urigo  for quick response.
I was to using ng-file-upload in the Angular client side and was trying to
figure out a way to create a api and make a post operation from Angular
