### ISSUE TITLE
How to tunnel result from asynchronous method call inside Meteor method into $scope?

### ISSUE THREAD

**Issue by kwk** [Urigo/angular-meteor#464]
Hi,

this is a question rather than a bug or an issue and it is best explained with a working and a non-working example. Maybe the anwer is trivial but I cannot see it right away.

# Working example

## Meteor method

Suppose I have a Meteor method lying under `server/methods/book-info.js`:

```javascript
'use strict'

Meteor.methods({
  'bookInfo': function() {
    // Assume we query book information here
    // ...
    var res = 42;
    return res;
  }
});
```

## Angular controller

When I call this method from my controller (`client/books/book-detail-ctrl.ng.js`) like this:

```javascript
'use strict'

angular.module('myApp')
  .controller('BookDetailCtrl', function ($scope, $stateParams, $meteor) {
    // This is the property I want to fill by calling a meteor method
    $scope.bookInfo = 0;

    $scope.fetchBookInfo = function() {
      $meteor.call('bookInfo').then(
        function (data) {
          console.log("success");
          console.log(data);
          $scope.bookInfo = data;
        },
        function (err) {
          console.log("error");
          console.log(err);
        }
      );
    }
  });
```

## Angular template

I can have a template `client/books/book-detail.view.ng.html` that looks like this:

```html
<input type="button" ng-click="fetchBookInfo()">Fetch Book Information</input>
<p>Book Info: {{ bookInfo }}</p>
```
When I click on the **Fetch Book Information** button it generates `<p>Book Info: 42</p>`.

We see that we can tunnel a simple value from a meteor method to our scope. 

But what if the book information is not directly available inside the meteor method?

In other words, what if we have to make an asynchronous call that yields the book information?

# Non-working example

Let's assume the book information (`42`) is not available right away in the Meteor method. Instead let's assume it will be queried by an asynchronous function call.

```javascript
'use strict'

Meteor.methods({
  'bookInfo': function() {
    var res = 0;
    // Library is an artificial name and represents any library you want
    Library.getInfo(function(data) {
         // the "data" that is available inside this function scope shall be returned by . But how?
         // I basically want to do this but it doesn't work because the "return res;" below is "faster".
         res = data;
    });
    return res;
  }
});
```

How can I restructure my app so that I can assign the `data` object available inside my anonymous callback function to `res`?

Thank you in advance!

**Comment by MilosStanic** [comment]
Hi,
This is typical asynchronous problem. So you should use promises. 

Here's an example of how to do it: 
http://stackoverflow.com/a/23777507/2727080

Please do tell if it works and maybe paste your corrected code.

**Comment by kwk** [comment]
Thank you @MilosStanic . The answer you gave me is one that I stumbled upon earlier. Do a I need a wrapper around `var Future = Npm.require("fibers/future");`? Shall I use [meteorhacks/npm](https://github.com/meteorhacks/npm) for this? Also what about [`Meteor.wrapAsync`](http://docs.meteor.com/#/full/meteor_wrapasync)?

**Comment by kwk** [comment]
Thank you @MilosStanic you've made my day. The solution was to install meteorhacks ([`meteor add meteorhacks:npm`](https://gentlenode.com/journal/meteor-17-using-npm-modules-in-your-application/36)) and then create a `package.json` like this:

```json
{
  "fibers": "1.0.5"
}
```

After that I've modified my Meteor method to look like this:

```javascript
'use strict'

var Future = Npm.require("fibers/future");

var syncInfoFunction = function() {
  var fut = new Future();
  var library = new Library(/*...*/):
  library.getInfo(function (err, data) {
    if (err) {
      console.log(err);
      fut["throw"](err);
    } else {
      fut["return"](data);
    }
  });
  return fut.wait();
};

Meteor.methods({
  'bookInfo': function() {
    return syncInfoFunction();
  }
});
```

Maybe I can make `syncInfoFunction()` less of a global function.

Again, thank you so much!

**Comment by MilosStanic** [comment]
Cool, 

What stops you to copy-paste `syncInfoFunction()` code into your `bookInfo` function?
This all should be somewhere in the docs.

**Comment by kwk** [comment]
@MilosStanic you're right. nothing stops me :)
