### ISSUE TITLE
possible to use publishComposite?

### ISSUE THREAD

**Issue by vacarsu** [Urigo/angular-meteor#468]
Hi, I was wondering if anyone has used the publishComposite package with angular-meteor. I'm trying to get it working, but all the examples are done in blaze.

**Comment by mxab** [comment]
we use publishComposite and angular meteor quite it works fine. Blaze should have nothing to do with it

**Comment by vacarsu** [comment]
what does the return object from publish Composite look like? I get the object I query returned but the fields are not populated within the object.

**Comment by kennyki** [comment]
You need to query the sub-objects in your client.

The publisher (server):
```
Meteor.publishComposite('topTenPosts', function() {
    return {
        find: function() {
            // return a cursor of the posts
        },
        children: [
            {
                find: function(post) {
                    // return a cursor, i.e. query of the post's author
                }
            }
        ]
    };
});
```

The controller (client):
```
$scope.posts = $scope.$meteorCollection(Posts, false);
$scope.authors = {};

$scope.$meteorSubscribe('topTenPosts').then(function() {
    $scope.posts.forEach(function(post) {
        // the related-authors data are published, but you still need to query and assign them
        $scope.authors[post._id] = Users.findOne(post.author);
    });
});
```

**Comment by vacarsu** [comment]
@kennyki thanks that makes sense.

**Comment by kennyki** [comment]
@vacarsu you're welcome.

**Comment by vacarsu** [comment]
@kennyki One last thing, for an object containing an array of ids would I just add a $in operator to the client and server queries?

**Comment by kennyki** [comment]
I supposed so. In such case I suggest to take a look at publishing a client-only collection like this: http://braindump.io/meteor/2014/09/20/publishing-to-an-alternative-clientside-collection-in-meteor.html
