### ISSUE TITLE
Problems setting nested object using AngularMeteorCollection.save

### ISSUE THREAD

**Issue by ccortezia** [Urigo/angular-meteor#469]
Suppose I have an object as simple as ```{brand: 1, value: {sub: 2}}```

After setting the field "value" to null through AngularMeteorCollection.save(data), the local collection no longer updates itself to any posterior non-null values on the "value" field (altough the subscription is properly receiving the changes). The field "brand" is normally update though.

PS: I detected this behavior when preparing a sandbox to debug another related problem. In the other scenario, I had a stack trace accusing TypeError inside the function ```diffObjectChanges``` on the [line](https://github.com/Urigo/angular-meteor/blob/master/lib/diff-array.js#L149) ```var diff = diffObjectChanges(oldItem[key], value);``` telling ```Exception in queued task: TypeError: Cannot read property 'blah' of null```. Unfortunately I couldn't reproduce this stacktrace on the sandbox, but the steps I used inside my bigger project are just the same.

The sandbox repo is linked [here](https://github.com/ccortezia/angular-meteor-sandbox/tree/bug-nested-diff)

**Comment by Urigo** [comment]
Thanks @ccortezia !
Do you think you can create failing tests for those scenarios?

Maybe here is meteor collection - https://github.com/Urigo/angular-meteor/blob/master/tests/integration/angular-meteor-collection-spec.js

and unit one in DiffArray - https://github.com/Urigo/angular-meteor/blob/master/tests/integration/angular-meteor-diff-array-spec.js

and maybe something like your example with e2e tests in here:
https://github.com/Urigo/angular-meteor/tree/master/examples

I will have a look on this anyway but those tests will be a great help!

**Comment by ccortezia** [comment]
> Do you think you can create failing tests for those scenarios?

Certainly. Just need to figure out angular-meteor devel environment first.

**Comment by Urigo** [comment]
Great!

Here are resources about that:
https://github.com/Urigo/angular-meteor/blob/master/README.md#contributor-developer-setup
