### ISSUE TITLE
$meteorObject stop() method (???) 

### ISSUE THREAD

**Issue by mgrivera** [Urigo/angular-meteor#477]
Hi all, 

in my application I have recently used more AngularMeteorCollection than AngularMeteorObject. I know there is an "stop()" method for AngularMeteorCollection to: 

"Stops watching the current collection for changes made in the scope variable or the meteor collection ..." 

I have used the same method in AngularMeteorObject. However, I can not see it in the documentation for AngularMeteorObject. Today I was using AngularMeteorObject in my program and could see the stop() method while debugging. 

Is it my fault or the method for AngularMeteorObject is not in the docs for this kind of object? 

Can somebody explain this to me? 

Many thanks and bye ...

**Comment by Tallyb** [comment]
Probably missing on the docs. I think I did the PR to update the collection documentation, but did not add It to object.

**Comment by mgrivera** [comment]
Hi @Tallyb, many thanks for this clarification ... I thought I was going crazy :) ...

**Comment by Urigo** [comment]
@mgrivera do you care maybe to update the docs with a PR to get the credit for your help?

**Comment by Tallyb** [comment]
stepped in with a PR

**Comment by Urigo** [comment]
Awesome @Tallyb !
