### ISSUE TITLE
Following your tutorial for creating meteor package, get publish: You're not in a Meteor package directory.

### ISSUE THREAD

**Issue by vacarsu** [Urigo/angular-meteor#481]
Hi, I'm trying to bring this package into meteor. https://github.com/andrewppace/vcard-json
but When I try to publish it I get the error in the title.

**Comment by Urigo** [comment]
@dotansimha

**Comment by MilosStanic** [comment]
@vacarsu where's your `.meteor` directory in the project? I think that is causing the error.

**Comment by vacarsu** [comment]
I decided to go with an npm package and use meteorhacks npm, rather than try to create a package for this.

**Comment by Urigo** [comment]
sounds like a good solution.
What do you do with npm dependencies?

Meteor for React added a solution that might be interesting here:
http://react-in-meteor.readthedocs.org/en/latest/client-npm/

I wonder what are your thought about that and if we can embrace this solution as well?
