### ISSUE TITLE
Collection2 errors will result in "$apply already in progress" error

### ISSUE THREAD

**Issue by shadysayed** [Urigo/angular-meteor#483]
In a project that uses collection2 for schema validation. saving an invalid document using

    $scope.collection.save(newDoument)

will result in "$apply already in progress" the reason seems to be that you call $rootScope.$apply without first checking $rootScope.$$phase inside AngularMeteorCollection.save function. And for some reason the callback for inserting an item in a collection is called inside a digest phase.

to avoid this I usually create a helper that goes like this

    $rootScope.applyIfNeeded = function(callback) {
      if (this.$$phase) {
        if (typeof callback === "function") {
          callback();
        }
      } else {
        this.$apply(callback);
      }
    };

Then whenever I need to call $apply I use

    $rootScope.applyIfNeeded(<callback if any>)

**Comment by shadysayed** [comment]
I've created a repo to reproduce this issue. Check out this commit shadysayed/meteor-issues-reproduction@1566e2e91ffbe17c3e13fda5925445978e2b7f74

**Comment by Urigo** [comment]
@shadysayed thanks for noticing!
do you care of creating a pull request with a fix and a failing (before) and success (after) tests?

**Comment by Urigo** [comment]
@shadysayed can you please test this issue against the latest master?

**Comment by cranesandcaff** [comment]
I'm on `0.9.3`, it's still throwing on incorrect docs.

**Comment by DAB0mB** [comment]
As for version `1.0.0` there isn't any digestion problem. Obviously the promise won't be resolved since it's being rejected by the schema, but the funny thing is that the promise is rejected with the bound result instead of the received error. I [fixed](https://github.com/DAB0mB/angular-meteor/commit/f0e6a71f5625f916b98bf92870a59bab48c0edf5) it, hopefully enough it will be merged soon :-D

**Comment by Urigo** [comment]
@shadysayed looks like it's fixed in `angular@1.0.0-rc.5`.
Please test and let me know if it works for you.

**Comment by markleusink** [comment]
Latest version fixed it for me!

(after updating the package name from urigo:angular to angular ;-)
