### ISSUE TITLE
Having an automatic 'updatedAt' field breaks $meteorObject with autoClientSave = true

### ISSUE THREAD

**Issue by shadysayed** [Urigo/angular-meteor#485]
In a collection where all saved items have an automatically updated 'updatedAt' field or similarly named one. The client will be stuck in an update loop if the following code is used
    
    $scope.item = $scope.$meteorObject(Items, item_id, true)

Once an item is saved the client will set 'updatedAt' to its clock and then the server will try to correct that with its 'updatedAt' clock and angular meteor will detect that the object is changed and will try to save it again which will result in updating 'updatedAt' and so on.

I had to do a simple monkey patching fix on my side but it only works for fields that are exactly named `updatedAt` I think something more robust should be implemented.

    angular.module('fix-updated-at', ['angular-meteor']).config([
      '$provide', function($provide) {
        $provide.decorator('AngularMeteorObject', [
          '$delegate', function($delegate) {
            return function() {
              var result;
              result = $delegate.apply(this, arguments);
              result.$$internalProps.push('updatedAt');
              return result;
            };
          }
        ]);
      }
    ]);

**Comment by ccortezia** [comment]
Hi @shadysayed , can you provide a repo with your problem isolated so we can reproduce your problem ?

**Comment by shadysayed** [comment]
Sure check out shadysayed/meteor-issues-reproduction@5c5b7217726cae78c1f195d92edb815f90323983 I simulated the user editing an object using a `$timeout` of 3 seconds. I've also added some code to log ddp messages to the console. Just do a `meteor run` and open the browser console and you'll see a flood of update messages.

**Comment by Urigo** [comment]
@shadysayed thanks for noticing!
do you care of creating a pull request with a fix and a failing (before) and success (after) tests?

* copied the response from your other issue but it's not automatic :)

**Comment by Urigo** [comment]
With the new [Angular Meteor 1.3 release](http://info.meteor.com/blog/angular-meteor-1.3), we do not recommend using $meteorObject but to use the new `helpers` syntax with the `findOne` function.
Please let me know if that works for you
