### ISSUE TITLE
Tutorial  - step 20  CollectionFS 

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#486]
Paragraph: 
So now we have the CollectionFS support and the storage adapter - we need to create a CollectionFS object to handle our files. Note that you will need to define the collection as shared resource because you will need to use the collection in noth client and server side.

should be: (5th word from end)
So now we have the CollectionFS support and the storage adapter - we need to create a CollectionFS object to handle our files. Note that you will need to define the collection as shared resource because you will need to use the collection in both client and server side.

**Comment by Urigo** [comment]
Thanks @JohnAReid 
I'm going to review that step again tomorrow and will take your notes into count!
