### ISSUE TITLE
untrusted code may only remove documents by ID

### ISSUE THREAD

**Issue by alecperkey** [Urigo/angular-meteor#487]
Hi--thanks for making this

From step 4, at the end of the video

I have a problem with not being able to remove a party added from from the front-end. says 'untrusted code may only remove documents by ID'

However, if i first remove one party which was from the server code, then I can remove the front-end created party

http://i.imgur.com/96Xqa5r.png

**Comment by alecperkey** [comment]
I just noticed I had my ng-app attribute on the body not on the container div within it. I think this might have been the issue.

**Comment by Urigo** [comment]
@alecperkey that sounds strange that this is the problem..

What version of Meteor are you using?

did you compared your code to the tutorial's one with `Code Diff` button?

**Comment by Tallyb** [comment]
It is probably some problem with the ID in the client code on the remove. Probably it is not set correctly (when the party is from the server) and when trying to run remove ({}) - it throws an error on the client. (blind debug is a new hobby - debug without seeing the code).

**Comment by Urigo** [comment]
@alecperkey closing for now. If you can provide more feedback please reopen
