### ISSUE TITLE
How to work package-based

### ISSUE THREAD

**Issue by sebakerckhof** [Urigo/angular-meteor#490]
I'm trying to put my code into packages, but I get a lot of errors.
To rule out problems with my code I now tried to restructure the socially tutorial code into a package, but this also gives me errors in the front-end.

This is the repo: https://github.com/sebakerckhof/meteor-angular-socially

Am I doing something wrong or is it currently not possible to use angular-meteor inside packages?

**Comment by sebakerckhof** [comment]
Ok, turns out I have to modify my template references from:
```
client/parties/views/parties-list.ng.html
```
to:
```
packagename_client/parties/views/parties-list.ng.html
```

**Comment by Urigo** [comment]
Exactly.
I'm mentioning this here in the tutorial:
http://angular-meteor.com/tutorial/step_05#routesdefinition

but do you think we can add it in another place for easier access?

**Comment by sebakerckhof** [comment]
I guess that location is fine, and it's just me not reading the documentation.
However, it might be better to have the tutorial already in a package-based structure, since that seems to be the best way to structure a Meteor application anyway.

If you agree, I can provide a PR. I've done it anyway and I also rewrote most of the angular code to comply (or at least comply more) with the [john papa style guide](https://github.com/johnpapa/angular-styleguide). However I've only done it for the final step. So maybe this can be added as a new step or I need to go back and do it for every step.

**Comment by dpdonohue** [comment]
I vote for @sebakerckhof adding more documentation on how to do Angular-Meteor in a package-based archtiecture!  I agree this is the best practice for Angular-Metero apps!

Having seen the documentation here
http://angular-meteor.com/tutorial/step_05#routesdefinition
I still am having problems getting this thing to work.  

I made an issue on StackOverflow: 
http://stackoverflow.com/questions/32209160/angular-meteor-how-can-i-include-ng-template-in-package-based-design

**Comment by dpdonohue** [comment]
I found a way to inject Angular into Meteor via packages, and documented it here
http://stackoverflow.com/questions/32209160/angular-meteor-how-can-i-include-ng-template-in-package-based-design/32250748#32250748

**Comment by Urigo** [comment]
Do one of you want to add a chapter to the tutorial on changing the structure to package based?

**Comment by sebakerckhof** [comment]
I'd be up for that, but currently a bit swamped with work...

**Comment by dpdonohue** [comment]
I could help but not sure if my approach is the best way to do it.  I described the details here
http://stackoverflow.com/questions/32209160/angular-meteor-how-can-i-include-ng-template-in-package-based-design/32250748#32250748

**Comment by alecperkey** [comment]
Hi, @dpdonohue, have you refined your approach at all? I am going to make a ui-accounts package to simplify and extend the angular-meteor auth functionality, but it is my first package so I am researching best patterns. 

@Urigo do you have any helpful links to existing packages, or pattern guidelines for packages extending angular-meteor?

Thanks

https://trello.com/c/3iLcMnaf/55-account-ui-angular-material

**Comment by Tallyb** [comment]
@alecperkey The blaze template directive is an extension of the angular-meteor package: https://github.com/Urigo/angular-blaze-template (was removed from core on angular-meteor 1.0 / meteor 1.2). 

Do you plan to build the UI using material design or bootstrap?

**Comment by alecperkey** [comment]
Good point-- that is definitely the package I should look at for understanding. I prefer angular material, though many people use bootstrap. So I will start with material. Might it be preferable to support both via options, or is it preferable to have separate packages for each to reduce file size? 

sort of unrelated I put this together in case its useful for anyone
https://docs.google.com/spreadsheets/d/1sKrU1L_qb_ivjpLjz0iSLjvUWHz78VriES3FEsc0cPM/edit#gid=2140873394

**Comment by dpdonohue** [comment]
Hi @alecperkey I have extended my method to support directives, services, controllers, and routes.  So a Meteor package can plug Angular directives, services, controllers, or routes using this approach.  I could not find a way that a package could contribute one of those things to the central Angular application without this approach.  The approach is basically for the package to add the info to a Meteor Session variable.  The central application reads all the directives or services or controllers from the corresponding session variable and declares them as Angular object.

Not an elegant solution but no matter what I tried, my Angular application failed to recognize my service or directive or controller when it was contributed form a package.

I can share more code if you like.  I cannot create a package to contribute this functionality of course you just have to add it to your core app code.

**Comment by Tallyb** [comment]
@alecperkey check out this one: https://github.com/Tallyb/angular-meteor-material. 
If you are using material - you may want to use some of the ui parts from it. 
Bootstrap is probably less critical as a blaze package exists for it.

**Comment by alecperkey** [comment]
@Tallyb, thanks. I tried to use your config and provider initially in the package, but thought that was causing me errors, so I just put the options config into each of the controllers which used it for experimenting purposes. 

@dpdonohue, it seems the controller of a package can be used with controller as syntax in ui router, but only if the routes are also defined in the package, rather than the parent apps routing config. I have been thinking about it and wonder if your approach to include the packages controllers, directives, services, and routes in the parent app (via the Session) for a package based approach is actually counter-productive to how a package based approach should work? I'm not sure, really...

Anyway, there is a new chapter (21) on the socially tutorial where the login controller is moved to a (well, 2) packages. I had some error recreating this approach with a package for all the login, register, and reset pieces. If you have time please check out my issue and repo (as well as step 21!). https://github.com/Urigo/meteor-angular-socially/issues/78

Thanks for your help so far +1:

**Comment by Urigo** [comment]
The issue @alecperkey mentioned is fixed and you can check out how to work package based in the new tutorial here: http://angular-meteor.com/tutorials/angular1/mobile-support-and-packages-isolation

Let me know if you want to add more stuff to the chapter (or just pull request)
