### ISSUE TITLE
UI router redirection after login?

### ISSUE THREAD

**Issue by dagatsoin** [Urigo/angular-meteor#491]
How could I make a redirection after a user has been logged in ? I am still using ui-account.

Thx :)

**Comment by markleusink** [comment]
I solved that by hooking into the onLogin event of the accounts-ui package:

    app.controller('AppController', ['$scope', '$state', '$timeout', function($scope, $state, $timeout) {

      //when a user signs in redirect to the overview page
      Accounts.onLogin( function() {
        $timeout(function(){
            $state.go('overview');
        }, 0);
      });

    }]);

**Comment by idanwe** [comment]
@markleusink why did you use $timeout?

**Comment by markleusink** [comment]
Because otherwise the redirect didn't work. Probably has to do with a resolve issue. A $timeout set to 0 fires just a little later.

**Comment by markleusink** [comment]
@idanwe I'll admit BTW that it's a hack. See http://stackoverflow.com/questions/20610450/angulajs-angularjs-timeout-without-delay-parameters-reason for more details. I'm always open to better solutions.

**Comment by MilosStanic** [comment]
you can also emit an event to root scope from your onLogin, and then catch event and route it to wherever you want.

**Comment by idanwe** [comment]
@markleusink I register to `Account.onLogin` in `run` function and it is working.

```javascript
angular
  .module('App')
  .run(run);

function run ($rootScope, $state) {
  $rootScope.$on('$stateChangeError', function(event, toState, toParams, fromState, fromParams, error) {
    // We can catch the error thrown when the $requireUser promise is rejected
    // and redirect the user back to the main page
    if (error === 'AUTH_REQUIRED') {
      $state.go('login');
    }
  });

  Accounts.onLogin(function () {
    if ($state.is('login')) {
      $state.go('main');
    }
  });

  Accounts.onLoginFailure(function () {
    $state.go('login');
  });
}
```

**Comment by Urigo** [comment]
Great answers.
Few questions:

1. Do you think we should add an example somewhere in the tutorial?
2. Do you think we should wrap `onLogin` and add it to the [auth API](http://angular-meteor.com/api/auth)?

**Comment by markleusink** [comment]
1. Yes: seems like a pretty common use case.
2. What would be the benefit of that? Only one I see now is that you could then make it work with a promise instead of a callback.

**Comment by cmddavid** [comment]
I'm not sure where i found this, but i use the following solution:

```
	var vm = this;

	vm.credentials = {
		email: $cookies.get('email')||''
	};

	vm.error = '';

	vm.login = function (){

		$meteor.loginWithPassword(vm.credentials.email, vm.credentials.password).then(
			function(){
				$state.go('main.dashboard');
			},
			function(err){
				vm.error = err;
			}
		);
	};

```

Afcourse this does require a angular form instead of standard Meteor login form.

**Comment by dagatsoin** [comment]
Back to earth. I love the @idanwe way !
@Urigo 
1 - Yes, could be a part of the new redesign part to serve a better UX.
2 - Use the force.

**Comment by sebakerckhof** [comment]
Sorry to post in a closed issue, but I think another common problem not tackled here is how to redirect to the route that the user requested. In case you use $meteor.requireUser() in the resolve object of a state.
