### ISSUE TITLE
Property absent from meteorCollection object

### ISSUE THREAD

**Issue by ccortezia** [Urigo/angular-meteor#494]
I am facing a strange behavior here. Objects retrieved using meteorCollection are missing a field (it is an array).  Data is properly published, and I can see the field if I do CollectionX.findOne() from the console. I then tried to bisect over angular-meteor commits to find a suspicious commit, but could only track down into 0.8.5 until my project started to break: problem still happened.

Since I was not able to isolate the problem on a clear repository, I could try to debug it if someone can provide me a hint on where I should start searching in the code.

**Comment by Urigo** [comment]
I can go through it with you in a Hangouts if you ilke

**Comment by ccortezia** [comment]
Mailing you privately now.
Em 03/07/2015 22:04, "Uri Goldshtein" <notifications@github.com> escreveu:

**Comment by ccortezia** [comment]
Bad news. The problem is not happening anymore (both on 0.9.2 and 0.9.1). I think my environment changed, and the issue was naturally masked, which resembles a nasty race condition. I will keep an eye as my project evolves to freeze the environment should the bug rise again.

**Comment by Urigo** [comment]
ok, hopefully you can reproduce it soon.
Closing for now.
Thanks

**Comment by ccortezia** [comment]
I did manage to reproduce a similar problem on a different part of my application. I will make a note here for future reference.

The variable behavior point can be noted on this [observer](https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-meteorCollection.js#L170) inside ```AngularMeteorCollection``` factory.

When loading data from publications, objects with nested branches may have its data fully loaded into the angular collection through addedAt callback, in which case everything worked fine. In other scenarios, with more data being received, these same objects would have a initial portion of data loaded through addedAt and the remaining data would be loaded through changedAt. When this second sceario happened, some bad behavior of some functions on lib/diff-array.js could leave this object crippled (the subject of this very issue) depending on the types involved.

I would like to understand the dynamics of data loading, since this non-deterministic fragmentation is a bit annoying. Would it be related to the format of publications. Anyway, applying the PR #506 seemed to avoid the cripple, even when with this partial data load happening.
