### ISSUE TITLE
Better design for the tutorial app

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#502]
Hi everyone,

So we have our tutorial app `socially` that uses `angular-material`.
It's very nice, but I think the design can be even better.

I would love some help for designing the app better and make it look more compelling.

Please have a look at [step 18](http://angular-meteor.com/tutorial/step_18) which @MilosStanic done a great job creating and think how to improve it so the app will look better and also the tutorial will still contain all the important information.

Would love to get pull requests for this branch: https://github.com/Urigo/meteor-angular-socially/tree/step_18

and even just designs as comments to this post.

Thanks everyone!

**Comment by JohnAReid** [comment]
@Urigo I would just like to say I like the current version of the tutorial  - it is easy to understand and to follow. I think you need to list what improvements you are looking for!

**Comment by Urigo** [comment]
Thanks @JohnAReid :)
I meant just the design of the app itself (colors, layouts)

**Comment by Urigo** [comment]
Ohh by the way, now that I'm officially MDG, I can promise shirts and stickers for the ones who will help me the most! ;)

**Comment by markleusink** [comment]
I agree with @JohnAReid : the tutorial is great and quickly gets you up to speed with `angular-meteor`. For the design of the steps < 18 I would stick with Bootstrap: that's a lot easier to understand for the vast majority of the users compared to `angular-material`.

That said, I do think that the tutorial could use some Bootstrap styling for most steps. Here's an idea for step 17:

<img width="1358" alt="screen shot 2015-07-10 at 08 30 59" src="https://cloud.githubusercontent.com/assets/1773707/8613449/96fb2cea-26df-11e5-8452-b8f35854c4aa.png">

**Comment by Tallyb** [comment]
The major change that needs to be done for a nice UX, wether bootstrap (as above) or material is to move the new party to the partyDetails page. 
In any case this is a good idea, as some code is repeated anyway between the create party section and the party details. 
The design above is nice but does not fit mobile...

**Comment by Urigo** [comment]
@Tallyb is right, mobile is important as well.

About Bootstrap - step 17 is what step 17 is all about.
So we can have two designs, one for Bootstrap and one for Material, but both should be better then now.

I think the new party button should show/hide the form, but still stay in the list page.
But in anyway, I hate having comments on design that is not in front of my eyes....

Does anyone knows a good tool to review designs (in public)?

**Comment by newswim** [comment]
Maybe try https://redpen.io/ ?

**Comment by Tallyb** [comment]
http://www.bounceapp.com/

**Comment by dispareil** [comment]
At least  can someone change the font-family and font-size of the tutorial ?

**Comment by Urigo** [comment]
I've added a Trello card for that:
https://trello.com/c/uWuI9jV1/56-new-visual-design

**Comment by funkytaco** [comment]
I like semantic UI http://semantic-ui.com/kitchen-sink.html

**Comment by Tallyb** [comment]
![image](https://cloud.githubusercontent.com/assets/7386255/8834286/f48cfc5e-30bb-11e5-81a5-6b1aefa3fd3f.png)
Starting to work it out...

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by alexanderzeillinger** [comment]
I like the draft of @markleusink :+1:

**Comment by Urigo** [comment]
We have new designs thanks to @hlandao and @dotansimha !!
Check out the Bootstrap version here: http://socially-step17.meteor.com/
and the `angular-material` version here: http://socially-step18.meteor.com/

More improvements and pull requests are welcomed.

Thanks everyone for the great help and suggestions
