### ISSUE TITLE
Problem when trying to $set object to nulled field

### ISSUE THREAD

**Issue by ccortezia** [Urigo/angular-meteor#503]
Suppose I have a record ```{nested: null}```. If I try to update it to ```{nested: {sub: 1}}```, I get an exception. The record is properly updated though.

The execution of this [deepCopyObjectChanges](https://github.com/Urigo/angular-meteor/blob/master/lib/diff-array.js#L246) raises the following exception: ```Exception in queued task: TypeError: Cannot set property 'sub' of null```

Isolated repo [here](https://github.com/ccortezia/angular-meteor-sandbox/tree/bug-nested-diff-2). 
Click on clear,save: bug appears. 
Click on drop,save: bug won't appear.

**Comment by Urigo** [comment]
@ccortezia it is closed by your pull request?

**Comment by ccortezia** [comment]
Yes, we can close it now.
