### ISSUE TITLE
Remove meteor-include tag after it's done loading

### ISSUE THREAD

**Issue by markoffk** [Urigo/angular-meteor#504]
Hi. I have a question: Is it possible to get rid of meteor-include html surrounding block just after rendering template inside of it? Having this block:
```
(<meteor-include ... >) 
```
still after rendering breaks bootstrap css styling in some cases (f.ex. bootstrap version of accounts-ui inside of bootstrap nav block). Or does removing this block after rendering will break reactivity then?

Thanks.

**Comment by Urigo** [comment]
@markoffk If it's still relevant, you should re-open that issue on this repository as we deprecated `meteor-include` in favor of `blaze-template`:
https://github.com/Urigo/angular-blaze-template
