### ISSUE TITLE
subscription gets the wrong dataset

### ISSUE THREAD

**Issue by thinkrapido** [Urigo/angular-meteor#507]
Hi, I'm building an Employee of the Month application.

I have two subscriptions as seen below. Unfortunately I get the same result set for both of the subscriptions. (e.g. the one of kvp-month)
When I comment out the kvp-month subscription the kvp-esotm collection is correct.
But nothing is seen for the kvp-month ng-repeat usage as it should be.

What's going wrong? Do I oversee something?

I have a dashboard in my app displayed by views and controllers assigned for those views. Maybe this is the problem? Or has it to do with Meteor itself.

```JavaScript
// server 
Meteor.publish('kvp-eotm', function (year, month) {
  var minDate = getMinDate(year, month),
      maxDate = getMaxDate(year, month);

  var out = KVP.find({
    $and: [{date: {$gte: minDate}}, {date: {$lt: maxDate}}, {isStarred: true}]
  }, {
    sort: {date: -1},
    limit: 1
  });

  return out;
});

Meteor.publish('kvp-month', function(year, month, first) {
  var minDate = getMinDate(year, month),
      maxDate = getMaxDate(year, month);

  first = _.isNumber(first) ? Math.max(parseInt(first), 0) : 0;

  var out = KVP.find({
    $and: [{date: {$gte: minDate}}, {date: {$lt: maxDate}}]
  }, {
    sort: {date: -1},
    limit: first
  });
  
  return out;
});

// cllient
// eotm controller
  $meteor.subscribe('kvp-eotm', year,  month).then(function() {
    $scope.esotm = $meteor.collection(KVP, false);
  });

// and list controller
  $meteor.subscribe('kvp-month', null, null, 5).then(function() {
    $scope.entries = $meteor.collection(KVP, false);
  });

```

**Comment by Tallyb** [comment]
Your subscriptions are different but your collection is the same, since both your subscriptions are based on the KVP meteor collection. 
So when you do $meteor.collection - you will see the combined results of both subscriptions. 
You will need to filter at your client collection, similar to your publish functions above. 
I have written about it here: https://medium.com/angular-meteor/coll-pub-sub-with-angular-meteor-cb13fe48f570
And the example at the end clarifies it.

**Comment by Urigo** [comment]
@Tallyb another example of needing your great post..
where do you should link to it in the tutorial?

**Comment by Tallyb** [comment]
@urigo (blushing)
Chapter 9 is a good place, I think. This is where you hit publications.

**Comment by Urigo** [comment]
@Tallyb can you pull request to suggest the best place in the chapter?
