### ISSUE TITLE
Tutorial - $meteor.collection(Parties) gives error - $scope.$meteorCollection(Parties) works

### ISSUE THREAD

**Issue by golgistudio** [Urigo/angular-meteor#509]
Really great tutorial!   Thank you!

In step 3 of the tutorial - " Binding to Angular" - http://angular-meteor.com/tutorial/step_03
There is a step to update the parties declaration. - $scope.parties = $meteor.collection(Parties);
That resulted in an error when i tried it (see screenshot below).   
Replacing $meteor.collection with $scope.$meteorCollection worked for me.

![image](https://cloud.githubusercontent.com/assets/5599690/8589004/e4b25a3c-25c5-11e5-9f60-007242159812.png)

~~~~~~~~~~~~~~~~~~~
The API recommends using $scope.$meteorCollection.

Not sure if I did something wrong.  If not, I recommend updating the tutorial.

~~~~~~~~~~~~~~~~~~~
running on windows w/ chrome and firefox browsers

**Comment by Tallyb** [comment]
It shows $meteor is not defined. Make sure you removed the foot. It is $meteorCollection, no dot.

**Comment by golgistudio** [comment]
Thanks Tally,

Not sure what you were saying about removing the foot and the dot, but I figured it out.

I had forgotten to pass in $meteor to the controller.
