### ISSUE TITLE
module not defined or not a function in integration test

### ISSUE THREAD

**Issue by marcusreese** [Urigo/angular-meteor#516]
It works in /tests/jasmine/client/unit/, but in /tests/jasmine/client/integration when I use
<code>beforeEach(module("swen"));</code>
then Velocity says: ReferenceError: module is not defined.
And when I use
<code>beforeEach(angular.mock.module("swen"));</code>
then Velocity says: TypeError: angular.mock.module is not a function.
Current project location: https://github.com/marcusreese/swen
Is this expected behavior? If so, can you guide me or suggest a resource regarding what to put into tests/jasmine/client/integration/?
Thanks for all you do with angular-meteor!

**Comment by Urigo** [comment]
@marcusreese sorry I haven't had a chance to look at your question, can you publish it again?

**Comment by marcusreese** [comment]
Okay thanks, I just put something up there. I'm not very familiar with the
conventions, so feel free to guide me.

**Comment by marcusreese** [comment]
I found one resource: https://github.com/meteor-velocity/velocity-examples/blob/master/leaderboard-jasmine/tests/jasmine/client/integration/LeaderboardSpec.js
Is that example appropriate for an angular-meteor project?

**Comment by quetzalcoatl** [comment]
@marcusreese: have you been using sanjo:jasmine when this problem occurred?

**Comment by marcusreese** [comment]
Yes, I have been using sanjo:jasmine, and it was loaded after angular-mocks.
As you suggested, I solved the "module not defined" problem by the following:
`meteor remove angular:angular-mocks`
`meteor add angular:angular-mocks`
I appreciate your disclaimer: "Meteor can in fact load them in any order, and this trick doesn't guarantee anything, it can change with different Meteor versions. It just happens to work today."
Hopefully someone will take your suggestion to heart and correct this in a better way.
In the meantime, thank you for your work!
(I'll let someone else decide whether or not this issue should be closed now.)

**Comment by Urigo** [comment]
@quetzalcoatl amazing answer!
As right now we are the ones publishing the `angular:`angular-mocks` package, we can add a `weak` dependency to `sanjo:jasmine`.  not the cleanest solution but might save a lots of headaches to people..

@dotansimha what do you think?

Closing as we have a solution for that but let's keep the conversation

**Comment by dotansimha** [comment]
@Urigo 
Sure it's not a problem to add the weak dependency and I think this is the right solution - it will not install `sanjo:jasmine`, but it will load after it. 

So, to add & publish?

**Comment by Urigo** [comment]
@dotansimha yes
