### ISSUE TITLE
HTTPS SSL Certificate of https://angular-meteor.com/tutorial is blocked out

### ISSUE THREAD

**Issue by lanshunfang** [Urigo/angular-meteor#519]
Hi there,

https://angular-meteor.com/tutorial is blocked out by Chrome default since it's using SSL certificate issued to *.meteor.com. So why not get a free signed SSL certificate from StartCom (https://www.startssl.com/?app=12)?

Cheers,
Paul

**Comment by leoetlino** [comment]
I wouldn't recommend StartSSL. While they offer free certificates, revocations aren't free, and this stays true even if [a widespread, critical security bug is affecting most sites and revoking is the only way to keep your HTTPS site secure](https://en.wikipedia.org/wiki/Heartbleed). [1] [2] [3] [4] [5]

[1] https://raim.codingfarm.de/blog/2014/04/12/distrusting-startssl/
[2] https://www.startssl.com/?app=43
[3] https://www.techdirt.com/articles/20140409/11442426859/shameful-security-startcom-charges-people-to-revoke-ssl-certs-vulnerable-to-heartbleed.shtml
[4] https://en.wikipedia.org/wiki/StartCom#Response_to_Heartbleed
[5] https://news.ycombinator.com/item?id=7557764

**Comment by leoetlino** [comment]
There are alternatives:
- [Let's Encrypt](https://letsencrypt.org/) (coming in Q4 2015)
- CloudFlare's free SSL service

But either they are not available yet (*Let's Encrypt* is coming in Q4 2015) or they do not support websockets (CF's free plan does not supports WS), so I would suggest GlobalSign's [free certificate for open source projects](https://www.globalsign.com/en/ssl/ssl-open-source/). Alternatively, paid certs typically cost less than $5 per year.

**Comment by jboothe** [comment]
Since it's been over 6 months, I proposed this [PR](https://github.com/Urigo/angular-meteor/pull/1062) to change the urls to use http until the cert is addressed.

**Comment by leoetlino** [comment]
Well, angular-meteor.com is now not available over port 443 anymore, so it doesn't really matter anymore.

Also, LE is now available for free and getting a cert is _really_ easy, so there's no reason (financially at least) this is not done. ;)

**Comment by jboothe** [comment]
@leoetlino, thanks for the [Let's Encrypt](https://letsencrypt.org) tip. The PR addresses several broken links on the Github home page - https://github.com/Urigo/angular-meteor.

**Comment by leoetlino** [comment]
My bad. I thought it was about the SSL cert errors (that were present a few months ago). Yeah, that should definitely be fixed until the site is accessible over SSL.

**Comment by Urigo** [comment]
will be added when Galaxy adds support for LetsEncrypt (Very soon)

**Comment by Urigo** [comment]
just fixed with the new Galaxy automated SSL!
http://info.meteor.com/blog/automated-ssl-reserved-pricing-galaxy-europe
