### ISSUE TITLE
include loginbuttons in ionic nav button area

### ISSUE THREAD

**Issue by phaggood** [Urigo/angular-meteor#525]
I'm using the ionic package with the tutorial - on step #8 where it says to add the login buttons include, is there a way to add this to the ionic nav?  I tried the following but it doesn't get displayed.  

      <ion-view view-title="Home">
          <ion-nav-buttons side="primary">
              <meteor-include src="loginButtons"></meteor-include>
          </ion-nav-buttons>

        <ion-content class="padding">
       . . .

**Comment by Urigo** [comment]
What is the output you get on the page's DOM?

**Comment by phaggood** [comment]
Sorry, me being an idiot - I restarted the project and didn't re-install the accounts and accounts-ui packages.
