### ISSUE TITLE
Support for IE8

### ISSUE THREAD

**Issue by TWKDreamState** [Urigo/angular-meteor#527]
I've been really impressed working through the tutorial of angular-meteor and it solves a lot of headaches I am having with the current mean stack I am using so I'm looking to port my app across.

I need to support IE8 at the moment which means the 1.2 branch of angular, although it's possible that most of my app will work with the latest version?

Is there anyway to drop back to a previous version of angular or will this cause issues with angular-meteor?

**Comment by Urigo** [comment]
Yes, you just need to:

    meteor add angular:angular@1.2.0

To you app as a hard dependency.
