### ISSUE TITLE
Can single field can be passed to $meteor.collection objects save function?

### ISSUE THREAD

**Issue by suman-mits** [Urigo/angular-meteor#532]
I have made 
`$scope.newObj = $meteor.collection(function() {
     return Users.find({_id:  Meteor.userId()})
})`

Can I just update single field instead of the entire document?

**Comment by ccortezia** [comment]
Take a look at #349 and #521

**Comment by suman-mits** [comment]
i know it can be done with $meteor.object, I wanted to know if it can be done with $meteor.collection as I need it for auto saving feature
