### ISSUE TITLE
Publish Meteor.users always return currentUser

### ISSUE THREAD

**Issue by cupideias** [Urigo/angular-meteor#536]
I'm trying to get a user by the username, when I use `Meteor.users.findOne`, it always return the current user. And if I user `Meteor.users.find`, it returns all current user document, and the `profile.firstName`and `profile.lastName` of the right matched username.

```javascript
Meteor.publish('userByUsername', function(username) {
    return Meteor.users.findOne({
        username: username
    }, {
        fields: {
            'profile.firstName': 1,
            'profile.lastName': 1,
        }
    });
});
```

How can I get only the user that match with the username?

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

**Comment by ccortezia** [comment]
@cupideias, I believe the publication ```userByUsername``` is raising a server-side error when a subscription takes place. Publications must return a cursor, or use lower level functions to control the publication behavior. Your function is returning a single record, or undefined in case no user record is found.

**Comment by cupideias** [comment]
Sorry about the post. I starting with Angular Meteor and was just a beginner mistake, what I needed was a method, not a publish. Thanks for the help.

**Comment by trajano** [comment]
Although this is a valid issue that should be re-openned.  Given a publish to a subscription 'all-user-list' with some paging information for example:

````
Meteor.publish('user-list-admin', function (selector, options) {
  if (!Roles.userIsInRole(this.userId, ['admin'])) {
    this.stop();
  }

  Counts.publish(this, 'user-list-admin-count', Meteor.users.find(selector), {noReady: true});
  return Meteor.users.find(selector, options);
});
````

The subscription and query against the Meteor.users table will always have the current user.  It might need some work, but I don't think the Meteor.users and the current user really should not be tied together otherwise this issue would arise.

**Comment by stubailo** [comment]
@trajano try this: https://atmospherejs.com/percolate/find-from-publication
