### ISSUE TITLE
Date object not being saved correctly using .save()

### ISSUE THREAD

**Issue by ambujpunn** [Urigo/angular-meteor#541]
I've noticed that if I create a document which has a date field and use the ```save()``` to save it to the collection, the date never ends up getting saved in Mongo. It comes out as empty in Mongo: ```date: ()```, but if I use the native Meteor ```insert()``` for the Collection, the date is saved correctly in Mongo. Is there a reason why this is happening?

```$scope.collection.save({date: new Date})``` (doesn't work)
```Collection.insert({date: new Date})``` (works)

**Comment by Urigo** [comment]
Thanks for the issue.
I have 2 requests:
1. Can you please create a failing test for that scenario?
2. Can you please test against the master branch and also against that pull request (#539) and let me know if it happens there as well?

**Comment by tgienger** [comment]
`$scope.collection.save({date: new Date()});`

**Comment by Urigo** [comment]
Fixed in `angular@1.0.0-rc.5`
