### ISSUE TITLE
$meteor.camera on Android 5.0 & Chrome not working properly

### ISSUE THREAD

**Issue by ppotoplyak** [Urigo/angular-meteor#544]
Hi,

On Android 5.0 & Chrome, the modal is auto taking the picture without giving the user the choice to take a snapshot at a desired time.  i.e. when the modal pops up, the snapshot is already taken and the modal is populated.

The same code base is working fine on Ubuntu Chrome.

``$ find . | grep mdg_camera
./.meteor/local/build/programs/server/packages/mdg_camera.js
./.meteor/local/build/programs/server/packages/mdg_camera.js.map
./.meteor/local/build/programs/server/assets/packages/mdg_camera
./.meteor/local/build/programs/server/assets/packages/mdg_camera/photo.html
./.meteor/local/build/programs/web.browser/packages/mdg_camera.js
./.meteor/local/build/programs/web.browser/packages/mdg_camera.js.map``

I tried to make sense of ./.meteor/local/build/programs/web.browser/packages/mdg_camera.js but the code is terse.  If you guys give me some pointers I can try to root cause.  My Meteor knowledge is minimal but I can try.

Thanks,
-pavel

**Comment by ppotoplyak** [comment]
After a little digging, my previous description is not quite right.  There is no auto taking of the picture, it just appears that way as the video stream is just a single frame as opposed to being a real video stream.
i.e. On my Galaxy S4, when the modal pops up, you see a single still frame as opposed to a live video stream.

It's as if the ``video.play();`` in mdg_camera.js is a nop on my Android device.  In fact, if I comment the ``video.play()`` out then I will see the same exact behavior on my desktop as I see in my broken Android case.

**Comment by ppotoplyak** [comment]
Adding autoplay, see last line, appears to be a workaround or a real fix in my situation:

.meteor/local/build/programs/web.browser/packages/mdg_camera.js:

Template["viewfinder"] = new Template("Template.viewfinder", (function() {                                      // 64
  var view = this;                                                                                              // 65
  return [ HTML.DIV({                                                                                           // 66
    "class": "viewfinder"                                                                                       // 67
  }, "\n    ", HTML.VIDEO({                                                                                     // 68
    id: "video",
    **autoplay: "true",// 69**

To be quite frank, I really don't know what I am doing :) 
It would be great if someone smarter than me can opine on whether this is a legitimate issue and deserves a PR.

thanks,
-pavel

**Comment by ppotoplyak** [comment]
This is an issue with the underlying mdg:camera package and not angular-meteor.  Sorry about the noise, closing bug.

**Comment by Urigo** [comment]
@ppotoplyak thanks for the persistence and the updates!
