### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#545]
Hi!
I want to add Internationalization support for the tutorial...
anyone wants to help in that?
also, I'm thinking about adding translations to the videos or even add voice overs for other languages...
thanks!

**Comment by simonv3** [comment]
@Urigo I can help with Dutch - do you have any idea how to do this with Angular / JS in general? I've only ever done it with Ruby / Python apps.

**Comment by shinrox** [comment]
I can help with brazilian portuguese

**Comment by Urigo** [comment]
I'm closing for now as providing the infrastructure is too expensive.. :(
Would love to get PR though...
