### ISSUE TITLE
/tutorial/step URL's do not work anymore

### ISSUE THREAD

**Issue by funkytaco** [Urigo/angular-meteor#546]
The tutorial URL's are still referenced, but don't point to anything anymore.

e.g.
http://angular-meteor.com/tutorial/step_06 - 404
http://angular-meteor.com/tutorial/step_08 - 404

If there's a referer, it seems to just redirect to the home page sometimes

**Comment by Urigo** [comment]
thanks, will redirect them now...
where are they referenced?

**Comment by Urigo** [comment]
fixed
