### ISSUE TITLE
Angular 2 meteor don't import template url in @View

### ISSUE THREAD

**Issue by lungkuteo** [Urigo/angular-meteor#550]
Hi! I'm using angular 2 with meteor. But when i use `templateUrl` to import file `list.ng.html`, it not working. Code in my file `main.ts`:
```
    import {Component, View, bootstrap} from 'angular2/angular2';
        @Component({
            selector: 'my-app'
        })
        @View({
            templateUrl: 'client/list.ng.html'
        })
        class AppComponent {}
        bootstrap(AppComponent);
```
But i use `template: '\<h1\>My app\</h1\>'`, it OK. Please help me, thank all!

**Comment by ShMcK** [comment]
Just a quick check:
- `list.ng.html` is definitely located in the client folder. Paths must be exact from the folder roor.

And what happens if your template targets: '<h1>My app</h1>` without escaping?

**Comment by lungkuteo** [comment]
I found error. Because chrome save cache, meteor get file from cache if file's name not change each reload. Try disabled cache of chrome, issue was resolved

**Comment by ShMcK** [comment]
I've also experienced the same frustrating error. I'll add a warning about it in the tutorial. Thanks!
