### ISSUE TITLE
Date object converted to {} on meteor collection auto save

### ISSUE THREAD

**Issue by sumanla13a** [Urigo/angular-meteor#551]
I am passing new Date() from controller to my collection that is set to auto. The date is being converted to {}. 
I saw the issue on collection.save function, could this be related?

**Comment by shankar-mits** [comment]
@Urigo +1

**Comment by Urigo** [comment]
Thanks for the issue.
I have 2 requests:
1. Can you please create a failing test for that scenario?
2. Can you please test against the master branch and also against that pull request (https://github.com/Urigo/angular-meteor/pull/539) and let me know if it happens there as well?

**Comment by Urigo** [comment]
Fixed in `angular@1.0.0-rc.5`
