### ISSUE TITLE
Potential performance problem on updateAngularCollection

### ISSUE THREAD

**Issue by ccortezia** [Urigo/angular-meteor#558]
An application with some collections, each holding a few thousand documents showed performance problems after some seemingly unrelated actions to those collections (calls to meteor methods targeting other collections). Looking at the profiler chart (attached) showed a bottleneck inside a Tracker computation.

![perf-problem](https://cloud.githubusercontent.com/assets/1430769/9011036/25991294-3781-11e5-83ff-a93a75f62f16.png)

This behavior was detected on a really old angular-meteor (0.5.9, old api), but since the code for updateAngularCollection looks the same as the (0.9.x), I believe the problem may still be there.

**Questions to be answered**
1) Any debug suggestion (besides testing on 0.9.x, which I will do next week) ?
2) Any chance my code, or document format is forcing a worst run scenario inside angular.each ?

**Comment by ccortezia** [comment]
Sorry for taking so long to return here.

1) The bottleneck is still there on 0.9.x
2) It is activated any time a underlying data change occur, and trigger the observer callbacks.
3) The bottleneck can be avoided when data is being added to an empty array instead of updating an already populated one.

Initially I went the worked around it by dropping every single element from the collection array (```$scope.collection.length = 0```) before doing any operation that would cause an immediate change initiated from inside. This is ugly, and don't cover the cases of changes initiated by other clients.

I believe the root problem is the level of generalization targeted by angularMeteorCollection (which results in complex code like diff-array.js and ultimately create these uncharted non-performant edge cases). Perhaps it could be refactored in such a way to allow some level of configuration-tuning for those willing to work with bigger collections.

After some struggling I decided to completely drop the usage of angularMeteorCollection from my application. Instead I wrote a sibbling lite version of it suited for my use cases, which allow the injection of a specialized callback to absorb observed changes on on a per-model way. I believe my code is not feature complete enough enough to go into the framework, but the approach is, and the result is incredibly faster (with a much simpler code).

@urigo, I won't close this issue just in case you want to discuss these ideas further. Otherwise you can go ahead and close it.

PS: congrats for the latest official MDG integration !

**Comment by Urigo** [comment]
@ccortezia thanks and very interesting points.

My guess is that the reasons are that we deep check when collection is updatedAt.
This is probably why when you remove everything it won't go through it and just do to addedAt.

I wonder if using a non nested diff makes your scenario better?
You can do it like we do in CollectionFS:
https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-collection.js#L326

Let me know if that's helping and if it's an interesting API to expose

**Comment by ccortezia** [comment]
> My guess is that the reasons are that we deep check when collection is updatedAt.

Well, actually in both cases my execution flow went through updateAt. The difference was in this conditional [check](https://github.com/Urigo/angular-meteor/blob/0.9.3/modules/angular-meteor-collections.js#L134)

This [gist](https://gist.github.com/ccortezia/387fafce1f8d14dd482c) shows the simplified meteor collection I was talking about. See that I didn't need to perform any deep comparison. Perhaps some ideas can be derived from this (much) less general implementation.

As for the flag-param API you mentioned, I didn't follow the discussions at the time, but I am not really fond of it: as if a workaround for a failed design somewhere was made permanent through the public API (no offense intended). Maybe it is good enough for collectionFS (as I said, I didn't follow up, can't measure the challenge there), but the more generic collection may require some more power. I am actually working with collections loaded with thousands of items at the same time, and my only concern now is browser rendering performance.

**Comment by DAB0mB** [comment]
@urigo @ccortezia As for version `1.0.0-rc4`, to test this issue I used the following piece of code:

```js
_.times(1000, function(i) {
  meteorArray.push({ index: i });        
});

console.profile('diff');
$rootScope.$apply();
console.profileEnd();
```

And this was my profiling result:

![image](https://cloud.githubusercontent.com/assets/7648874/9694746/2315c7ca-5364-11e5-8e7d-f6ef6da32e4c.png)

It seems that there are 2 bottlenecks:
- `Meteor._debug` - caused mostly by silly debug logs.
- `AngularMeteorCollection._upsertDoc` - which doesn't seem to make too much unnecessary calls besides Meteor's API.

Iv'e yet to test a collection with complex documents (more than 1 level deep), so I'll be sure to update you and give you my thoughts.
