### ISSUE TITLE
Folder Structure issue

### ISSUE THREAD

**Issue by sali1982** [Urigo/angular-meteor#559]
I put my collection in a file in Folder Model:

var Owners = new Mongo.Collection("Owners");

Since the controler JS code is  in client folder, and runs before it, it gives error that is not defined yet. Why it is happening to me?

**Comment by Tallyb** [comment]
Remove the var. The model should be global.

**Comment by sali1982** [comment]
Thanks. I removed it. It did not work. What I had to do is to remove it from a model folder, instead I repeat it once in Server file, once in client file. Is this okay to have it like that?

I do not understand why it happens. Please help.

**Comment by Urigo** [comment]
@sali1982 can you please share a repo?

**Comment by Brasilikum** [comment]
Had the same issue, the solution @Tallyb proposes totally works.

**Comment by Urigo** [comment]
Closing.
@sali1982 please reopen if @Tallyb solution doesn't work for you
