### ISSUE TITLE
http-call-client error

### ISSUE THREAD

**Issue by YooJaSung** [Urigo/angular-meteor#561]
i want to upload and download images using gridfs..

and now i an following tutorials step 20. compiles are not error but i get client 

error  http-client-call.js (The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType.) when save method.. 

i really didn't know why this error occur..

**Comment by Urigo** [comment]
@YooJaSung can you share your repo?

**Comment by vacarsu** [comment]
Same problem here.

**Comment by vacarsu** [comment]
I'm in a bit of a hurry to get this issue sorted out, any insight would be greatly appreciated.

**Comment by DAB0mB** [comment]
For me it is just showing the warning above, but it doesn't show any error. Infect the files seem to be saved properly. Anyways for me it doesn't seem like an angular-meteor issue but more like gridfs issue. Have you tried using the latest version of angular-meteor? Note that `urigo:angular` is now deprecated and you should add `angular` package instead.

**Comment by vacarsu** [comment]
Yes it's just a warning I managed to get everything working find. This is an issue with CollectionFS I think as I get this warning with the file system store as well.

**Comment by Urigo** [comment]
@vacarsu can we close this for now?

**Comment by Urigo** [comment]
@YooJaSung can we close this for now?
