### ISSUE TITLE
Current User missing profile properties after logging in

### ISSUE THREAD

**Issue by cleor41** [Urigo/angular-meteor#565]
Meteor Accounts is supposed to publish the entire profile object by default. After I log a user in, certain properties are missing from the profile object but if I refresh the page, the entire profile object is there.

I solved this issue by subscribing to a pub that exposed the profile object directly after a user logs in. Has anyone experienced this before?

```javascript
  $rootScope.$on('logged-in', function(){
    $meteor.subscribe("self").then(
      function(success){
        UserService.setupNotifications($rootScope.currentUser);
        $state.go('profile.library.follows',{username: Meteor.user().username});
      },
      function(error){
        $state.go('profile.library.follows',{username: Meteor.user().username});
      }
    );
  });
```

Specifically, the profile kept excluding an array called notifications on the profile object, as well as a couple of others.

**Comment by cranesandcaff** [comment]
Is that event one you set up yourself or is it included in this package?

**Comment by cleor41** [comment]
I set the event up myself. After the accounts-password login promise resolves I fire the 'logged-in' event above.

**Comment by cranesandcaff** [comment]
Are you using a standard Accounts UI package or a custom one?

**Comment by cleor41** [comment]
I'm using the standards one, this is what I have for logging in. Not optimal yet but it does the trick

```javascript
  	var AccountLogin = function(user,scope,rootScope){
      /* Redefine user to explicitly set the user attributes we want */
      var password = user.password;
      var user = {
        email: user.email.toLowerCase()
      }
      SpinLoaderService.showLoader(true);
  		Meteor.loginWithPassword(user,password,
  		function(err){
        if(err){
          SpinLoaderService.showLoader(false);
          scope.error = err.reason;
        }else{
          scope.error = "";
          rootScope.$broadcast('logged-in');
        }
  		});
  	};
```

**Comment by cleor41** [comment]
I think I should be using the $meteor implementation for consistency though, I just never changed it for this prototype

**Comment by cranesandcaff** [comment]
That might be your issue, try using the `$meteor` service and see if it fixes the required traits. It might be a `$scope` issue. I'm trying it now because I want to check if a user is set up on log in and the `requireValidUser` function doesn't seem to be working. If it works with `$meteor` I'll let you know.

**Comment by cleor41** [comment]
Yep that fixed it for me, thanks! You said requireValidUser wasn't working for you?

**Comment by cranesandcaff** [comment]
Yeah, I created an issue on here. It's undefined when logged and calling it in a state resolve method doesn't return or throw an error.
