### ISSUE TITLE
subscribe issues on angular-meteor

### ISSUE THREAD

**Issue by sali1982** [Urigo/angular-meteor#576]
I do see strange behaviours.

1. I removed the autopublish
2. added this in my server js file: 
Meteor.publish("assets", function () {
  return Assets.find({});
});

3. subscribed it in my js controller:
 $scope.assets =  $meteor.collection(Assets).subscribe('assets');

I do not see any assets! I am very very confused. What is the issue? Please help....

**Comment by sali1982** [comment]
I realized the reason it was not happening is my Server files runs before NEWing the Collection. So it gives error that Assets is undefined. 

When I moved my server code to the root js file, and added that inside: 
if(Meteor.isServer){}
and defining the Assets before, my list was populating...

Then my main issue is that Server file runs before the collection file. But why? it is not in the client folder. Why on the earth it says it is undefined? Please help this is so strange!!!!

**Comment by Urigo** [comment]
@sali1982 can you please share a repo with this problem, then I think I could more easily understand what's the problem.
In the meantime, have you read the Meteor file load order documentation here?
http://docs.meteor.com/#/full/structuringyourapp
