### ISSUE TITLE
requireValidUser undefined?

### ISSUE THREAD

**Issue by cranesandcaff** [Urigo/angular-meteor#578]
Below is an example state. I logged the method from the `$meteor` object but the log is undefined, it doesn't throw an `undefined is not a function` error though so not sure what's up with that. Possibly Angular eating exceptions as it is sometimes wont to do.

It doesn't redirect to anything or fire a `$stateChangeError` event.

    .state('main', {
        url: '/',
        templateUrl: 'client/main/index.ng.html',
        controller: 'MainVM',
        resolve: {
          currentUser($meteor){
          console.log($meteor.requireValidUser)
          return $meteor.requireValidUser(function(user){
            if(user.profile.isSetup){
              return true
            }
            return 'NOT_SETUP'
          })
        }
      }
    })

Should I check what version I'm using or is there some other debugging I should look into? I just started the project using it so I should have the latest versions.

**Comment by cleor41** [comment]
I don't think you can log requireValidUser it just returns a promise. Let me check something real quick

**Comment by cranesandcaff** [comment]
I wasn't logging the return value, just `console.log($meteor.requireValidUser)` which should log the function itself.

It was throwing the not a function error but I wasn't logging the error in the state change event watcher.

**Comment by cleor41** [comment]
Ahh I see, I overlooked that

**Comment by cleor41** [comment]
Can you use resolve like that? I thought you could only use key value pairs

**Comment by cranesandcaff** [comment]
I'm using Babel for ES6, it's the same as `currentUser: function($meteor)` but shorter.

![Imgur](http://i.imgur.com/QkximKf.png)

This is the `console.log()` of `$meteor`. I don't seem to have that method, maybe it's a version issue. I have to figure out how to check the version of angular meteor being used. Probably just that. I did just start this repo though so I don't know why it wouldn't have the right version...

**Comment by cranesandcaff** [comment]
Yep. For some reason I was on `0.8.4`.  Fixed and closed.

**Comment by cleor41** [comment]
Glad you found your issue, I'll check out babel

**Comment by cleor41** [comment]
Looks like I'm late to the party 8000+ stars hahaha

**Comment by cranesandcaff** [comment]
I really love ES6 and Babel makes it super easy. There is an Angular Babel package for running both Babel and Ng-min(or whatever it's called...). Super cool.
