### ISSUE TITLE
$rootScope change on auth change?

### ISSUE THREAD

**Issue by cranesandcaff** [Urigo/angular-meteor#579]
When a user logs in or out there isn't an event fired for that, so their state doesn't change. If they were on a page for unauthed users they stay there instead of being redirected. Is there a way to listen to changes to auth?

**Comment by phaggood** [comment]
perhaps $rootScope.loggingIn or $meteor.waitForUser() ?

http://angular-meteor.com/api/auth

**Comment by Urigo** [comment]
There are a few ways to do that.
I think the most common way to do that with Meteor and Blaze is to use Tracker.autorun, so in our case, maybe the best option will be to `$watch` the currentUser and respond to it
