### ISSUE TITLE
angular-meteor app fails on startup with "unknown provider $$asyncCallbackProvider"

### ISSUE THREAD

**Issue by phaggood** [Urigo/angular-meteor#585]
I haven't changed any app code but I did do 'meteor update' after which my app ceased to startup.  

Here's the browser console output:

app.ng.js?e999ad7257a2d60cd9fc4de2b25e2b6e9dfe322a:13 non-cordova init
app.ng.js?e999ad7257a2d60cd9fc4de2b25e2b6e9dfe322a:4 initalizing angular
angular.js:68 Uncaught Error: [$injector:unpr] Unknown provider: $$asyncCallbackProvider <- $$asyncCallback <- $animate <- $compile
http://errors.angularjs.org/1.4.4/$injector/unpr?p0=%24%24asyncCallbackProvider%20%3C-%20%24%24asyncCallback%20%3C-%20%24animate%20%3C-%20%24compile

This is my entire app.ng.js file (located in client/lib per the tutorial)

     angular.module('ionicApp', ['angular-meteor', 'ui.router','ionic'])

     function onReady() {
       console.log("initalizing angular");
       angular.bootstrap(document, ['ionicApp']);
       console.log("initalized");
     }
     if (Meteor.isCordova) {
       console.log("cordova init");
       angular.element(document).on("deviceready", onReady);
     }
     else {
       console.log("non-cordova init");
       angular.element(document).ready(onReady);
     }

And my index.ng.html (note - no ngApp per the tutorial)

     <head>
       <title>makerActive</title>
     </head>

     <body>

     <ion-nav-bar class="bar-positive">
       <ion-nav-back-button>
       </ion-nav-back-button>

     </ion-nav-bar>

       <ion-nav-view>

       </ion-nav-view>
     </body>

These are all the packages I've got loaded:

$ meteor list
accounts-password            1.1.1  Password support for accounts
accounts-ui                  1.1.5  Simple templates to add login widgets to an app
aldeed:collection2           2.3.3  Automatic validation of insert and update operations on the client and server.
angularui:angular-ui-router  0.2.15  angular-ui-router (official): Flexible routing with nested views in AngularJS
autopublish                  1.0.3  Publish the entire database to all clients
insecure                     1.0.3  Allow all database writes by default
lepozepo:s3                  5.1.1  Upload files to S3. Allows use of Knox Server-Side.
meteor-platform              1.2.2  Include a standard set of Meteor packages in your app
urigo:angular                0.9.3  The simplest no-conflict way to use AngularJS with Meteor, Meteorite and Atmosphere Smart Packages.
urigo:ionic                  0.4.0* Ionic framework packaged for Meteor.

**Comment by DAB0mB** [comment]
The latest angular:angular-mocks package does not work with angular:angular@1.4.1. I fixed it in pull request #587 by specifying  angular:angular-mocks version.

**Comment by sean-stanley** [comment]
I had a very similar error with angular@1.4.4 after adding angular-animate@1.4.4

I also got the familiar 'You've tried to launch Angular twice' error. It resolved after removing angular-animate.

I guess I'll wait until angular-animate is supported to fancy up my project with some animations.

**Comment by Urigo** [comment]
@dotansimha I think it might be that not all of our dependencies are updated to the latest Angular version?  (angular-mocks)?

**Comment by phaggood** [comment]
So, should I attempt to merge #587 locally or assume it's going to be merged into mainline soon?

**Comment by Urigo** [comment]
No, please try to current master branch

**Comment by phaggood** [comment]
sorry, I'm really confused here.  So I should check out angular-meteor master, merge PR 587, build my own package locally, uninstall the angular-meteor package from atmosphere then install my local package so I can have the correct angular version to run my angular meteor app?

**Comment by Urigo** [comment]
no no, just take the current master and run it locally.  without PR 587.
You can see instruction here: https://github.com/urigo/angular-meteor#user-content-run-local-urigoangular-in-your-project

**Comment by phaggood** [comment]
Followed instructions in the link to fork and use local package; on startup I'm still getting the same problem - Uncaught Error: [$injector:unpr] Unknown provider: $$asyncCallbackProvider <- $$asyncCallback <- $animate <- $compile

**Comment by phaggood** [comment]
I'm at wits end - I rolled back to a previous version and angular launches with no problem; the angular launcher in app.js is *exactly* the same between this version and my old vesion.  Uri, if you're interested I've added you as a collaborator, the app in question is called 'makerActive'.

**Comment by mirstan** [comment]
+1

**Comment by Urigo** [comment]
Fixed in `angular@1.0.0-rc.5`
Please let me know if that's not the case
