### ISSUE TITLE
Helpers and Templates for collection-helpers

### ISSUE THREAD

**Issue by murid** [Urigo/angular-meteor#589]
Doesn't seem to work with https://github.com/dburles/meteor-collection-helpers

```
$scope.books = $meteor.collection(function(){
    return Books.find({})
});

$scope.authors = $meteor.collection(function(){
    return Authors.find({})
});

$scope.author = $meteor.collection(function(){
    return Authors.findOne(this.authorId);
});
```

    <li ng-repeat="book in books">{{book.name}} by {{author.name}}</li>

What's missing?

**Comment by Urigo** [comment]
I think that collection helpers expose functions...
so:

     author.name()

no?

**Comment by murid** [comment]
This worked for me:

    $scope.author = function (book) {
        return $meteor.object(Authors, book.authorId, false);
    }

and the view:

    <li ng-repeat="book in books">{{book.name}} by: {{author(this.book).name}}</li>

**Comment by Urigo** [comment]
@murid do you think you can add a test for this scenario with a pull request?
it would be great to make sure it will always keep working...
thanks!
