### ISSUE TITLE
What admin to user

### ISSUE THREAD

**Issue by vimes1984** [Urigo/angular-meteor#590]
Hello there, 
I've been reseaching admin interfaces, but all seem to use Iron router do you  have any suggestions uising UI router?

**Comment by Urigo** [comment]
There are many Angular Bootstrap Admin themes out there, much more then there are Blaze and Iron Router ones...
Here is an example of one which suppose to have angular-meteor integration as well:
https://wrapbootstrap.com/theme/angle-bootstrap-admin-app-angularjs-WB04HF123

**Comment by vimes1984** [comment]
Thank you for taking the time to find one, I hadn't thought about going done that route I was search atomosphere and couldn't stumble across one... 
Sorry for opening an issue, regarding just this...

**Comment by Urigo** [comment]
thanks for opening and feel free to open any issue you want

**Comment by vimes1984** [comment]
I'm goign to roll my own :D
https://github.com/vimes1984/foundation-angular-admin

**Comment by vimes1984** [comment]
and since I'm building it... 
I've run into a small issue when inlcuding a ng.html file in the package.js file it doesn't include in the front end: 
https://github.com/vimes1984/foundation-angular-admin/blob/master/package.js
Line 22..
Called here https://github.com/vimes1984/foundation-angular-admin/blob/master/public/js/routes.js
including the template as raw html works template: '<h2>Admin view</h2>'; Works...

**Comment by vimes1984** [comment]
anddd I fixed it... 
      templateUrl: 'vimes1984_foundation-angular-admin_client/templates/admin.ng.html',
is the correct syntax... 
Sorry and thanks for listening!
