### ISSUE TITLE
Using typescript.

### ISSUE THREAD

**Issue by dagatsoin** [Urigo/angular-meteor#592]
Hello,

I plan to use typescript for a new project. Both to prepare Angular 2 and meteor 1.2 and because I prefer to use typed (even super set) language.

Question: is their any known issues/requirements with typescript + meteor + angular-meteor?

**Comment by Urigo** [comment]
I don't know, I only tried TypeScript with Angular 2.0 but I think it's a good direction.
Let me know how it works for you.
Also, you should probably check out this library (based on Babel):
https://github.com/pbastowski/angular2-now

**Comment by tgienger** [comment]
Typescript compiles to plain javascript, so there should be zero issues. I've been using it with vscode and love it. I'm really loving intellisense.

**Comment by Urigo** [comment]
@tgienger are you using it with `angular-meteor`?

I would love to see an example and maybe even add it to the tutorial!

**Comment by tgienger** [comment]
Sure thing. I can just re-write a tutorial in typescript if you like.

**Comment by Urigo** [comment]
that can be cool!

**Comment by Rian0702** [comment]
Would love to see that too

**Comment by adriangordon1231** [comment]
+1

**Comment by Urigo** [comment]
we are now using a great Typescript package in the Angular 2.0 tutorial.
Would love it if someone will create a version of socially with that package

**Comment by jacobdr** [comment]
I think I may actually take up the task of doing this given my increasing comfort with Typescript.

This is slightly outside the scope of this particular issue, but what is now considered the canonical Meteor typescript compiler? (@netanelgilad @pbastowski) 

I have been using the ([popular](https://atmospherejs.com/?q=typescript)) [meteortypescript package](https://github.com/meteor-typescript/meteor-typescript-compiler/) package, but has that been replaced by y'all?

**Comment by pbastowski** [comment]
@jacobdr I have a TS version here https://github.com/pbastowski/meteor-angular-socially/tree/feature/step-17-ng2now-ts.

This version just uses the TS compiler (and SystemJS) instead of Babel, without any regard to type annotations. So, if you are after a full TS refactor then this is not it. Have a look. Let me know what you think.

**Comment by Urigo** [comment]
@pbastowski amazing
