### ISSUE TITLE
Socially 2 app reloads when an exception happens - obscuring the exception

### ISSUE THREAD

**Issue by IgorMinar** [Urigo/angular-meteor#608]
*steps to repro*:
1. follow http://angular-meteor.com/tutorials/angular2/adding-removing-objects-and-angular-event-handling
2. make a typo (e.g. instead of `this.partiesForm.controls.name.updateValue('');` type `this.partyForm.controls.name.updateValue('');`
3. open the app and add a new item

*expected result*: the app breaks and exception is visible in the console (or better yet a compile time error is displayed in the meteor console)

*actual result*: after submitting the new item via the form the app reloads just after posting the data to the server, which means that after the reload the app now contains the new item.

This makes it look like the app works (albeit with a reload) and makes it hard to find the cause for this reload.

**Comment by ShMcK** [comment]
Meteor-Angular2 needs an improved typescript compiler. 

Currently, `sclausen:angular2-typescript` is a better fit, but only runs on the client and throws errors for any server side `.ts` files. I've posted [this question](https://github.com/Microsoft/TypeScript/issues/4269) to the Typescript community to try to address this problem.

**Comment by Urigo** [comment]
Fixed thanks to the great work of @barbatus who created a new [Typescript package for Meteor](https://github.com/barbatus/typescript) , updated the [Angular2.0-Meteor package](https://github.com/Urigo/Meteor-Angular2) and the [tutorial](http://angular-meteor.com/tutorials/angular2/bootstrapping).
