### ISSUE TITLE
Can helpers create AngularMeteorObjects? 

### ISSUE THREAD

**Issue by mpkorstanje** [Urigo/angular-meteor#629]
I have an object model with helper functions from `dburles:collection-helpers` to get and set related objects.

```javascript
Authors = new Mongo.Collection('authors');
Books = new Mongo.Collection('books');

Books.helpers({
  author: function(author) {
    // Gettter/Setter
    return arguments.length ? 
            (this.authorId = author._id) : Authors.findOne(this.authorId);
  },
});
```

The authors and books are put into scope by the controller.

```javascript
angular.module('app')
	.controller('MainController', function ($scope, $meteor) {
		$scope.books = $meteor.collection(function () {
			return Books.find({});
		});
		
		$scope.authors = $meteor.collection(function () {
			return Authors.find({});
		});
});
```
And looping over the books, the `book.author()` function is used to fetch the author of the book. The author is then used as the model of an drop down which lets us pick from all the available authors.

```HTML
<div ng-repeat="book in books">
	{{book.name}} by: {{this.book.author().name}}
	<form class="form">
		<div class="input-group">
			<ui-select ng-model="book.author" 
				ng-model-options="{ getterSetter: true }" 
				ng-disabled="disabled" required="true">
				<ui-select-match placeholder="Select an author">
					{{$select.selected.name}}
				</ui-select-match>
				<ui-select-choices repeat="author in authors">
					<span ng-bind-html="author.name"></span>
				</ui-select-choices>
			</ui-select>
		</div>
	</form>
</div>
```

This will result in a `Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!`. Because `book.author()` returns a new instance of the author is created each time the function is called, the digest cycle doesn't recognize that the object is unchanged. Which is a bit of a bummer because being able to walk data structures is a nice feature.

Is there a way to create helper functions that produce stable AngularMeteorObjects and -Collections?

edit: Still working on minimal example.

**Comment by sean-stanley** [comment]
+1

**Comment by mpkorstanje** [comment]
Created [minimal example of problem](https://github.com/mpkorstanje/angular-meteor-helpers-issue). Example is somewhat different from the code above. That way I could avoid using ui-select. The example breaks at `ng-repeat="book in selected.author().books()` which returns a new array each time `author.books()` is invoked.

**Comment by mpkorstanje** [comment]
Looked into the problem some more but I don't think it can be properly solved right now.

1. To look up meteor documents  we need to go through $meteorCollection or $meteorObject. This is the easy part. The helper functions can be declared as factories that produce the actual function with $meteorCollection and $meteorObject in their scope. E.g. something like this:

```javascript
angular.module('app').config(
	function ($meteorHelpers) {
		$meteorHelpers
			.helper(Books,'author', function($meteorCollection, $meteorObject){
				return function(){
					if(!this.$$reactiveAuthor){
						this.$$reactiveAuthor = $meteorObject(Author,this.authorId)
					}

					return this.$$reactiveAuthor;
				}
			})
			.helper(Author,'books', function($meteorCollection, $meteorObject){
				return function(){
					if(!this.$$reactiveBooks){
						this.$$reactiveBooks = $meteorCollection(Books,{authorId:this._id})
					}

					return this.$$reactiveBooks;
				}
			})
	}
);
```

And with some additional factories the most common use case could probably be simplified somewhat.

```javascript
angular.module('app').config(
	function ($meteorHelpers, $findOne, $find) {
		$meteorHelpers
			.helper(Books, 'author', $findOne(Author, 'authorId'))
			.helper(Author, 'books', $find(Books, {authorId: '_id'});
	}
);
```

2. Each individual document or all documents in a collection would need to be extended with helper functions that can do the look up. It can't be prototyped because of the context.

3. The helper functions factory would need to be constructed with $meteorCollection and $meteorObject in in scope. Specifically, when the meteor collection was created through $scope.$meteorCollection, the helper functions would need to use $scope.$meteorCollection to ensure the meteor collections created by the helper functions are also stopped up when the original object goes out of scope.

I can't figure out how to access $scope.$meteorCollection while inside AngularMeteorCollection.

Hope this makes sense.
