### ISSUE TITLE
Can't use expression {{...}} at the index.html

### ISSUE THREAD

**Issue by marioaleogolsat** [Urigo/angular-meteor#630]
Hey, I've been playing around with meteor-angular for a while and I've got something wierd: I can use expressions like {{ text }} at any TEMPLATE.ng.html. "Well, maybe the angular.js is not loading...", that's what I thought, but if I use something like <p ng-bind="{{ text }}"></p> it works like a charm.
Even simple expressions like {{ 1 + 2 }} doesn't work, it trows "Indentifier Expected" .

Is there something that maybe I'm missing here?

**Comment by simonv3** [comment]
Hey @marioaleogolsat, if you're following the tutorial you'll see this disclaimer: 

> We are using the .ng.html file extension so that Blaze - Meteor's templating system won't compile and override our AngularJS expressions.

Which might be what's going on in your case.

To get around it, from the tutorial:

> To start simple, create a new file called index.ng.html under the main folder, this will be our main HTML template page.

And add

```
<body>
  <div ng-include="'index.ng.html'"></div>
</body>
```

to `index.html`.

Let me know if that fixes your problem!

**Comment by marioaleogolsat** [comment]
Thanks, works perfectly for me!
