### ISSUE TITLE
Bump Version #?

### ISSUE THREAD

**Issue by jonmc12** [Urigo/angular-meteor#631]
I ran into some issues related to issue #349 and wanted to test if some of the recent commits fixed the problem.  However, running a 'meteor update' failed to get the latest version of "urigo:angular" package.  I noticed that while several updates were made to the package, the version # in package.js was not updated, so I don't think there is any way I can download that latest via meteor package system.

I ended up cloning the git repo locally so I could test the fixes (and it did indeed fix my problem!), however, I thought it might be an oversight that the version # in package.js was not bumped so that the latest can be downloaded through the meteor package system?

**Comment by JohnAReid** [comment]
The following might explain it (atken from https://github.com/Zodiase/meteor-mdl/issues/17#issuecomment-135857184)

That might be the issue with meteor package manager. I follow the package versioning instruction and use mainVersion-revision format but somehow meteor package manager considers 1.0.1 more up-to-date than 1.0.1-1 for example. I tested and found even with 1.0.2-1 released, using meteor update always gets me 1.0.2 instead. I had to do meteor add zodiac:mdl@=1.0.2-1 to work around.

**Comment by jonmc12** [comment]
Thx @JohnAReid, but in this case it does not look like the version # has been bumped since [July 20](https://github.com/Urigo/angular-meteor/commit/6b837e621f03c3aab2289f90764449d91cde02d3), and atmosphere lists latest version as [August 13](https://atmospherejs.com/urigo/angular), even though there have been dozens of commits since that date.  As far as I understand, there is know way to get the latest version of code repo via meteor package manager even when explicitly stating the version #.

**Comment by Urigo** [comment]
Hi guys,  sorry that it took a while, I had many things I wanted to push in the next version and I just kept postponing it!
Right now I'm testing the current master against my own apps and tutorials (even though we have great test coverage) and will release a new version in a few days.
Also, the next version will be the last one on `urigo:angular` and from then on we will move to the new and official `angular` package!!!!!!
You can actually use the release candidate of the new `angular` package already now:
https://atmospherejs.com/meteor/angular

I've released it yesterday so it's based on the current `master` branch.

**Comment by jonmc12** [comment]
@Urigo - very cool!  congrats on the official package.  Personally I have found the project very empowering between docs, support, tutorials and quality of library - so I'm not surprised it was adopted by Meteor.

I didn't realize you used master branch to keep unreleased commits - all makes sense.  I'm using the release candidate and seems to be working great.

**Comment by Urigo** [comment]
Just released `angular@1.0.0-rc.5`.
Let me know if everything works for you!

**Comment by jonmc12** [comment]
@Urigo I've been on ```angular@1.0.0-rc.5```, generally working well, but I'm actually seeing the #349 type problem again.  

I have a form where the user updates 3 fields on a model - which then reveals a 4th field.  I do a batch update on the 3 fields, and it works.  But then when I try to update the value of the 4th field, and it does not update to the DB.  Its reproducible that it seems to lose its binding for auto-save after the first update.

Please let me know if more specific report of the bug would be helpful..
