### ISSUE TITLE
Meteor 1.2 - Official support for React and Angular as view layer alternatives to Blaze

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#635]
The documentation for Meteor has the following regarding version 1.2:

Official support for React and Angular as view layer alternatives to Blaze.

Would you care to explain what this means!

**Comment by leoetlino** [comment]
That means that Meteor now officially supports Angular as another client frontend in addition to their homegrown Blaze. This in turn means that `urigo:angular` will become `meteor:angular` (or simply `angular`) in the future.

As far as I am aware, the official support shouldn't bring any breaking changes.

**Comment by JohnAReid** [comment]
@leoetlino Many thanks

**Comment by Chidan** [comment]
This is awesome, thanks
