### ISSUE TITLE
$meteor.collection(Posts).subscribe('posts') or $scope.$meteorSubscribe('posts') ?

### ISSUE THREAD

**Issue by hojas** [Urigo/angular-meteor#643]
What is the difference between

```
$scope.posts = $meteor.collection(Posts).subscribe('posts');
```

and

```
$scope.$meteorSubscribe('posts').then(function(handle) {
    $scope.posts = $meteor.collection(Posts);
});
```

?

**Comment by batjko** [comment]
Well, according to the [API reference](http://angular-meteor.com/api/subscribe):
> Calling $scope.$meteorSubscribe will automatically stop the subscription when the scope is destroyed.

...which indicates this will not be the case, if you use the other version.

**Comment by Tallyb** [comment]
The latter allows you to use a function to fetch only part of the data in the local minimongo. 

Take a look here: https://medium.com/angular-meteor/coll-pub-sub-with-angular-meteor-cb13fe48f570
(and forgive the self promoting, but I think you may find it useful)
