### ISSUE TITLE
angular-meteor conflicts with meteor-job-collection when included after

### ISSUE THREAD

**Issue by mxab** [Urigo/angular-meteor#644]
Hi,

I just noticed that the angular-meteor package in combination with the meteor job collection throws an error if included in the wrong order
```
'The global definition of Mongo.Collection has changed since the job-collection package was loaded. Please ensure that any packages that redefine Mongo.Collection are loaded before job-collection.'
```

I guess this is a related issue
https://github.com/vsivsi/meteor-job-collection/issues/58

I cannot really see where some Mongo.Collection shadowing is happening, maybe in one of the dependencies does it

Not sure if there is anything that can be done, but I thought I mention it

**Comment by mxab** [comment]
A very simple workaround for now is to make sure that the angular packages is listed before the job collection in the _packages_ file

```
angular
...
vsivsi:job-collection
```

**Comment by Urigo** [comment]
@mxab can you check if that happens by one of the package dependencies?

**Comment by Urigo** [comment]
I think I had the same thing with his files package..
I'm closing unless someone would like to investigate this package

**Comment by lekev** [comment]
Hi I have the same issue, It seems that angular package use [dburles:mongo-collection-instances](https://github.com/dburles/mongo-collection-instances) as depency
`api.use('dburles:mongo-collection-instances@0.3.4', 'client'); // For getCollectionByName `
[PackageFile](https://github.com/Urigo/angular-meteor/blob/7febfed399a360fd906999044b775262eb1b2c9c/package.js#L45)

the workaround to list angular before the job collection in the packages file and to add 'Mongo.Collection.prototype.constructor = Mongo.Collection;' before the new new JobCollection( ... ) doesn't fix the issue

**Comment by ozsay** [comment]
@Urigo The new API doesn't use this package. It's just for legacy code. Should we do something?

**Comment by DrDanRyan** [comment]
FYI, this also causes issues with `vsivsi:file-collection` which is a very nice package for people wanting to use gridFS and not take on CollectionFS. It is also a very well maintained package compared with CollectionFS.
