### ISSUE TITLE
Adding to array deletes all others

### ISSUE THREAD

**Issue by jdmswong** [Urigo/angular-meteor#649]
Stackoverflow synopsis here:
http://stackoverflow.com/questions/32409003/modifying-a-collections-objects-attribute-removes-all-other-attributes

I submitted it as a question, but I think I may have found a bug.

**Comment by Urigo** [comment]
@jdmswong that looks like an interesting `autobind` problem.
My first response would be to recommend not to use `autobind` because it's not best practice, but in anyway we need to solve it.
Do you think that you can provide a failing test that I could look into?

**Comment by jdmswong** [comment]
Hi @Urigo I'll see if I can whip one up for you.  Can you elaborate on ```autobind```? I don't see it explicitly used here.

**Comment by Urigo** [comment]
`autobind` (http://angular-meteor.com/api/meteorObject) means that every change you made to the object, it will automatically be saved. like 3 way data binding.
The when you `push` to an array, we `$watch` that, find out what changed and then save it to Meteor.

The best practice is to not use that, pass `false` in the third parameter and use the `save` function to save your changes.

**Comment by jdmswong** [comment]
Is it best practice because using save makes one call to the server, instead of many smaller ones?

**Comment by Urigo** [comment]
No, it's because it's better to use 1 way data binding then 2 way data binding.
It's better for performance and less error prone.
React, Blaze and Angular 2.0 work in that way

**Comment by Urigo** [comment]
@jdmswong in the new 1.0.5 version does it still happening for you?

**Comment by jdmswong** [comment]
Hi @Urigo I took your advice and used 1 way data binding.  I can't speak into whether this issue still occurs, but it is no longer a problem for me!

**Comment by Urigo** [comment]
ohh I'm happy it's working for you.
In version 1.3 I'm going to loose 3 way data binding from the code as it's not a good practice

**Comment by jdmswong** [comment]
since you're here @urigo I was wondering if you're committed to developing Angular Meteor in the long term, or does the project have an expiry date? thanks!

**Comment by Urigo** [comment]
I'm committed for the long term.
It is obvious to me that the relevance and popularity of this solution is growing each day both for Angular 1.x and Angular 2.0

**Comment by Tallyb** [comment]
@urigo what does loosing 3 way days binding means in practice?

**Comment by Urigo** [comment]
that it will be the same as sending `false` in the autobind flag always
