### ISSUE TITLE
Can't use <div ng-controller="MyCtrl"> outside <div ui-view>

### ISSUE THREAD

**Issue by maximedubois** [Urigo/angular-meteor#650]
If I use 
`<div ng-controller="TestController">{{test}}</div>` in index.html beside `<div ui-view></div>` and I declare my scope variable in my controller the value is never shown on the page.

**Comment by maximedubois** [comment]
it seems like there's a conflict between angular and meteor using {{}}. If I use <span ng-bind="test"></span> it's working well..

**Comment by Urigo** [comment]
yes, as of today, `html` files are rendered by `Blaze` and not `Angular` and only `ng.html` files are rendered by `Angular`.
Soon this will be changed in the new Meteor 1.2 release where there is a better separation, my plans are to make `angular@1.0.0` support all `html` files by Angular.
In the meantime you can keep using `.ng.html` or use this `angular-meteor-platform` package:
https://github.com/planet-training/angular-meteor-platform
