### ISSUE TITLE
Stopping a subscription

### ISSUE THREAD

**Issue by Unavi** [Urigo/angular-meteor#652]
I just completed [Angular Tutorial Step 12](http://angular-meteor.com/tutorials/angular1/search-sort-pagination-and-reactive-vars) and it seems like the last part, Stopping a subscription, isn't working.

It says I have to use 
`$scope.$meteorSubscribe(name, publisherArguments)` instead of 
`$meteor.subscribe(name, publisherArguments)`, 
but even with the change it is not reacting to any search or pagination input after going to the details page.

I don't know if this is a isolated problem, so I uploaded it to a repository: 
[Unavi/AngularMeteorTutorial](https://github.com/Unavi/AngularMeteorTutorial)

Would be nice if one of you could take a look. :smile:

**Comment by Urigo** [comment]
Have you tried comparing your code to the current state of the tutorial?
https://github.com/Urigo/meteor-angular-socially/tree/step_12

**Comment by Unavi** [comment]
Yes no difference. In step 16 the subscription section changes suddenly to:

    var subscriptionHandle;
    $meteor.subscribe('parties').then(function (handle) {
        subscriptionHandle = handle;
    });
    $scope.$on('$destroy', function () {
        subscriptionHandle.stop();
    });
but even with that change no improvement.

**Comment by vacarsu** [comment]
if you can't get $meteor.subscribe you can try $scope.$meteorSubscribe() this will stop the subscription when the scope is destroyed.

**Comment by Unavi** [comment]
@vacarsu that's what I it was original but doesn't work.

**Comment by Unavi** [comment]
Finally figured out why it is not subscribing anymore...
![picture](http://i.imgur.com/J3Ki78L.jpg)
Removed this part in `routes.ng.js` and now it's working.

Why should I subscribe with `$meteor.subscribe` bzw why do we start with this in the tutorial?
Is there any advantage?

**Comment by Urigo** [comment]
@Unavi Ohh I see now!
Maybe we should rephrase it...
Can you maybe suggest a pull request to the docs that will make it more understandable?

**Comment by Unavi** [comment]
Made a pull request ... hopefully^^ :smile:
So why use `$meteor.subscribe`  and not `$scope.$meteorSubscribe` in the first place?

**Comment by Urigo** [comment]
Just because I think that in the routes you can't get access to the `$scope` but maybe I'm wrong?
