### ISSUE TITLE
Angular 2 tutorial, step 5 (Routing) not loading

### ISSUE THREAD

**Issue by vsheyanov** [Urigo/angular-meteor#664]
http://angular-meteor.com/tutorials/angular2/routing-and-multiple-views

From console:
```Uncaught Error: Multiple files in patch. Must specify filename which is one of: client/app.ts, client/parties-list/parties-list.ts```

**Comment by Urigo** [comment]
not again :(
@vsheyanov thanks for that.
@ShMcK could you have a pick?
thank you both!

**Comment by ShMcK** [comment]
I've made [a pull request with a patch update](https://github.com/Urigo/angular-meteor/pull/672).
Sorry for the trouble.

**Comment by Urigo** [comment]
Fixed
