### ISSUE TITLE
ENOENT error when trying to build docs locally 

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular-meteor#671]
When running meteor / meteor update  I get ENOENT on both of those packages: 

mdg:tutorial-diff-box 
mdg:tutorial-step-diff-compiler

Error: ENOENT, mkdir 'D:\dev\angular-meteor\.docs\angular-meteor\packages\tutorial-step-diff-compiler\.npm\plugin\mdg:tutorial-step-diffs-plugin-new-8fezek'

On windows 10.

**Comment by Urigo** [comment]
@Tallyb can you see if it's a problem with the tutorial plugin?
If so, it's better to open it as in issue in the package itself:
http://info.meteor.com/blog/step-by-step-tutorials-with-git

**Comment by Tallyb** [comment]
https://github.com/meteor/tutorial-tools/issues/7
