### ISSUE TITLE
collection not seems to bind with template

### ISSUE THREAD

**Issue by raza2022** [Urigo/angular-meteor#679]
i have a collections named Mails. now i trying to bind single mail (let's suppose currentMail) with template but it doe's working within scope. am tried both methods by following examples given@ http://angular-meteor.com/api/meteorObject and here is my code in controller
```
$scope.currentMail = $scope.$meteorObject(Mails, $stateParams.id)
```
i also tried 
```
$scope.currentMail = $meteor.object(Mails, $stateParams.id)
```
the Question is that, is necessary to subscribe the $scope with collection to retrieve one collection from mails collections ? (because with subscribing mails within scope fulfill my need)

**Comment by jacobdr** [comment]
@raza2022 You do need to subscribe to the collection -- either in a parent scope or in the current scope -- before you try to query the MiniMongo database using a $meteor.object or $meteor.collection call.

Terrible analogy that might be helpful: 
Think of `subscribing` as filling the well with water, and Angular-Meteor's `.collection` and `.object` methods as tools to draw buckets of water from the well. Read another way: `subscribe` fills the client-side MiniMongo database with a whole slew of documents, and  Angular-Meteor is the tool that you use to fetch a subset of those documents and place them on the scope in a reactive way. 

Anyway, I thinkyou would want code that looks something like this:

```javascript
/// Client-side code
$scope.$meteorSubscribe('Mails').then(function(subscriptionHandle){
    // Alternatively you may want to bind the $scope.idToSearch = $stateParmams.id
    // and then use a $scope.getReactively('idToSearch') inside the funciton call below
    $scope.currentMail = $scope.$meteorObject(Mails, {"_id":$stateParams.id})
})
```

Make sure that you have [published the documents](http://docs.meteor.com/#/basic/Meteor-publish) first -- I assume in my above solution that you publish the collection under the name "Mails")

**Comment by Urigo** [comment]
thanks @jacobdr for the great answer
