### ISSUE TITLE
Creating packages with angular

### ISSUE THREAD

**Issue by suhail-ansari-apconic** [Urigo/angular-meteor#680]
I would like to create some packages with angular the same way we can do with blaze. I am unable to find any documentation as to create packages that provide a functionality like blaze with angular. I would like to create a full user management module with angular and include in my various applications.

With blaze it was quite easy. I would create a template and can include my templates with include directive. But with angular it is not able to find the view template uri.

Please let me know if there are standard ways to create packages with angular,

Thanks

**Comment by suhail-ansari-apconic** [comment]
I was able to solve the problem by reading your route tutorial portion correctly. What is needed though for tutorial is how to write a package using angular instead of blaze. 

The whole angular thing is working nicely for now but some more tutorials and few package from angular universe will make this whole angular-meteor a great success story.

Thanks

**Comment by Urigo** [comment]
@suhail-ansari-apconic thanks for the feedback!
What would you add to this chapter? 
http://angular-meteor.com/tutorials/angular1/3rd-party-libraries

**Comment by Urigo** [comment]
@suhail-ansari-apconic 
Waiting for your feedback

**Comment by suhail-ansari-apconic** [comment]
I think a better way would be to have a tutorial to write a package like accounts fully in angular.  Since most people use accounts-UI they already have the familiarity. This would show how to write end to end functionality in angular using meteor package.

**Comment by Urigo** [comment]
Ohh I understand, so like a full package with logic and everything.
Why would that be different then a tutorial on regular Meteor package?

**Comment by suhail-ansari-apconic** [comment]
The thing is that there are developers with various skill set. As a manager when i have to tell them to use angular instead of blaze some of them have no clue how to create a package with controllers, view template and service using angular. After a while with lack of documentation they just abandon the whole thing altogether and stick with blaze. That is why i think a package written with angular controllers, services and view template would be a great addition to the tutorial. (Something like a full accounts UI package and how to use it in your application).

**Comment by Urigo** [comment]
I think @simonv3 is working on something like that.
Maybe he can also create a tutorial out of it

**Comment by simonv3** [comment]
I am! @suhail-ansari-apconic have a look at https://github.com/simonv3/meteor-running/

The *basic* functionality is all there. Once you install it you get log in / registration / password reset and an admin panel (and a setup for creating an admin account with any email address). There's also an admin panel which lists users, groups, and the site details. No editing yet though (that's next step). It's being used in https://github.com/simonv3/quick-survey/

It's still early stages, and over the next two weeks I'm pre-occupied with client work, but I'm happy for pull requests.

**Comment by Urigo** [comment]
@Tallyb also look at this package

**Comment by dennishu001** [comment]
I think it will be sufficient if you can point out the way angular-meteor looks up template files in a package in your existing tutorials. By looking at the meteor-running package, I just found out you need to use 'author_package-name_client/templates' to properly point to 'client/templates' in your package. Other than that, I didn't find anything peculiar using angular-meteor in a local package. Thanks for the wonderful work!

**Comment by simonv3** [comment]
Yeah, there's absolutely nothing special about Angular Meteor packages in regards to meteor packages - you just have to include them in the angular app as well if they're an angular library.
