### ISSUE TITLE
Unable to redirect to intended page after login

### ISSUE THREAD

**Issue by nutanlade** [Urigo/angular-meteor#684]
Hi All,

I'm trying to redirect to messages page after FB login. Somehow it is not working. Please correct or provide any other alternative.

angular.module("jaarvis").run(["$rootScope", "$state", "$meteor", function($rootScope, $state, $meteor) {

   $meteor.autorun($rootScope, function(){
      if (! Meteor.user()) {
        console.log('user');
        if (Meteor.loggingIn()) {
          console.log('loggingIn ' + Meteor.user()); -- returning null
          if(Meteor.user()) {
            $state.go('onlineusers');
          } else {
            //On login
            $state.go("messages");
          }
        }
        else{
          console.log('login');
          $state.go('login');
        }
      }
     });
}]);

**Comment by jacobdr** [comment]
This is a re-post from a [StackOverflow issue](http://stackoverflow.com/questions/32552029/redirect-after-login-angularjs-meteor/32556900#32556900) that I already resolved. 

@Urigo Please close

**Comment by Urigo** [comment]
Great!  thank you!
