### ISSUE TITLE
Textangular issues

### ISSUE THREAD

**Issue by lanmower** [Urigo/angular-meteor#685]
I have no idea where else to post this, looks like fraywing:text-anuglar on github is the original project and its not clear who maintains it on meteor.

http://meteorpad.com/pad/eedqTbamxnyHKcAK6/Textangular

Textangular gives the following error when included.

WARNING: Tried to load angular more than once.

**Comment by shinrox** [comment]
yeah, I didn't find a good package too.. you can try creating your own package following this steps http://angular-meteor.com/tutorials/angular1/3rd-party-libraries

**Comment by lanmower** [comment]
Thanks Shinrox, looks like I have some learning to do :)

**Comment by Urigo** [comment]
@netanelgilad I think you have created one as well right?

**Comment by netanelgilad** [comment]
yes I think you can also use my package here: https://github.com/netanelgilad/meteor-textAngular.
If you have problems with it, don't hesitate to open an issue
