### ISSUE TITLE
 Untrusted code may only update documents by ID. 

### ISSUE THREAD

**Issue by dtruel** [Urigo/angular-meteor#688]
The following code fails with the following error:` Error: Not permitted. Untrusted code may only update documents by ID. [403]`.

```javascript
$scope.settings = $scope.$meteorObject(Settings, {profileQuestions:{$exists:true}}, false);
$scope.settings.bob = "hello!";
$scope.settings.save();
```

I read up on the docs, and it looks like the update must use the _id property to update only.  I tried to debug the code and I think that when angular-meteor does the update, it tries to use the original selector.  To fix it, I think we would need to write code that grabs the _id from the initial result and uses that to update the document from there on out.  Are there plans to make this happen, or am I just misusing it?

**Comment by Kreeg** [comment]
hi! That's the solution @dtruel

**Comment by canac** [comment]
I am running to this issue as well. Is there any chance of the change suggested by @dtruel getting implemented?

**Comment by Urigo** [comment]
Using `Meteor Object` and `save` is not a best practice anymore.
Please read the [1.3 release docs]()http://info.meteor.com/blog/angular-meteor-1.3 and use the native Meteor API for that
