### ISSUE TITLE
save() would empty $meteor.object / $scope.$meteorObject, when called with no field changed

### ISSUE THREAD

**Issue by aguegu** [Urigo/angular-meteor#692]
I was going through the official tutorials. In step 6: http://angular-meteor.com/tutorials/angular1/bind-one-object

After implement the code fragment 6.5/6.6, 

If I click the save button without any modification, the name/description fields would be emptied. these fields are gone from the object or scope. 

If I click the save button with a little modification, it works fine.

But in either case, the success promise supplies `Object {action: "updated"}`, not the number of successful docs changed. 

angular@1.0.0-rc.6

**Comment by jeje87** [comment]
Hello, I have the same problem. When I return to an earlier version (urigo:angular), it works again...

**Comment by cranesandcaff** [comment]
Same issue here. @jeje87 what version were you on?

**Comment by Urigo** [comment]
yes I can confirm that, looking at it now

**Comment by jeje87** [comment]
thanks !!
