### ISSUE TITLE
how can i use two different accounts at a time?

### ISSUE THREAD

**Issue by liekkas** [Urigo/angular-meteor#693]
in tutorial step-9,it says 
```Log in with 2 different users in 2 different browsers.```
so I did, but when I logined with one account,the another client also logined automatically,how can i use two different account at a time?

**Comment by Tallyb** [comment]
a. Use another browser (e.g. Chrome and firefox)
b. open an anonymous browser - e.g. incognito mode in Chrome.

**Comment by liekkas** [comment]
thank u
