### ISSUE TITLE
Add ability to get Meteor.currentDate()

### ISSUE THREAD

**Issue by gonengar** [Urigo/angular-meteor#698]
Currently, in order to work with dates synchronized among all the clients - there is a need to create a simple function called 'date' which returns new Date(); on the server and this method should be called by the clients using meteor methods.
Maybe there might be a more elegant solution.

**Comment by jacobdr** [comment]
@Urigo Not sure that this has anything to do with Anguar-Meteor, can we close?

**Comment by Urigo** [comment]
@gonengar that seems like a nice idea.
I'm trying to make `angular-meteor` is agnostic as possible to Meteor and adding minimum APIs on top of the Meteor API.
That way it will be easier to switch between frontend frameworks and also the whole Meteor community will benefit from your suggestion.
I advise you to open a feature request on Meteor issues
thank you for the suggestion
