### ISSUE TITLE
simple-todos-angular doesn't work

### ISSUE THREAD

**Issue by sclausen** [Urigo/angular-meteor#702]
I initally filed this issue at meteor/meteor/issues/5250, but now I think the last problem could be a angular-meteor specific error.
The first Problem is, that ng-include in the body tag leads to:
```javascript
Meteor.startup(function() {
  document.body.setAttribute('ng-include', ''todos-list.ng.html'');
  document.body.setAttribute('ng-controller', 'TodosListCtrl');
});
```
which throws an error, because of the two singlequotes around todos-list.ng.html. @gjr-qm filed it here [here](meteor/meteor/issues/5232).
In the current meteor release, this can be fixed with moving it from an attribute-directive to an element directive in the body like:
``` html
<body ng-controller="TodosListCtrl">
  <ng-include src="'todos-list.ng.html'"></ng-include>
</body>
```
or as @gjr-qm mentioned in the meteor issue, you could also escape the src like this
```html
<body ng-controller="TodosListCtrl" ng-include="\'todos-list.ng.html\'"></body>
```
this hack let my atom syntax-highlighting going crazy :grin: 

After all, `<meteor-include src="loginButtons"></meteor-include>` doesn't render anything.

**Comment by gjr-qm** [comment]
I think you have to:
- meteor remove urigo:angular
- meteor add angular

And then change:
`<meteor-include src="loginButtons"></meteor-include>`
into:
`<blaze-template name="loginButtons"></blaze-template>`
in todos.list.ng.html

At least those steps worked for me :-)

**Comment by sclausen** [comment]
I didn't added `urigo:angular`, it was the new `angular` package, but neither using `blaze-html-templates` nor `static-html` together with `<blaze-template name="loginButtons"></blaze-template>` fixed it for me. Sorry, that I have been too lazy to create an example repository, I will catch up on this!

**Comment by gjr-qm** [comment]
Ooops, forgot to mention that you also have to include urigo:angular-blaze-template. That together with the steps mentioned above did the trick for me

**Comment by sclausen** [comment]
Aaaaaah! With `blaze-html-templates` and `urigo:angular-blaze-template` and `<blaze-template name="loginButtons"></blaze-template>` it finally works!
Maybe someone should make a pull request for the simple-todos-angular example accordingly to your suggestions. Do you wan't to do it, or am I allowed to make a pull request with your fix?

**Comment by gjr-qm** [comment]
Be my guest with the pull request. You already forked and fixed it

**Comment by sclausen** [comment]
Sorry I have been faster than your approval, that was very rude.
