### ISSUE TITLE
Step 20: Bootstrap, angular-material and handling files

### ISSUE THREAD

**Issue by aleksander351** [Urigo/angular-meteor#704]
I went through the tutorials and skipped step 18. - angular-material, because I like the Bootstrap version better.

Now at step 20, there are instructions only for angular with material. For example:
20.4  Add usage of file uploader - seems to be dependent on material specific tags (<md-dialog>, md-dialog-content)

More general instructions would be appreciated.

**Comment by veekungx** [comment]
[ng-file-upload](https://github.com/danialfarid/ng-file-upload) just a directive (but very cool)
You can learn about it from the link

if you love bootstrap version here a little example


HTML
```
 <div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <div ng-model="avatar"
          class="drop-box"
          ngf-drop
          ngf-select
          ngf-change="addImages($files)"
          ngf-drag-over-class="{accept:'dragover', reject:'dragover-err', delay:100}"
          ngf-multiple="false"
          ngf-allow-dir="false"
          ngf-pattern="'image/*'"
          accept = "image/*">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
```

CSS
```
.drop-box {
    background: #F8F8F8;
    border: 5px dashed #DDD;
    width: 100%;
    height: 200px;
    text-align: center;
    padding-top : 60px;
}

.drop-box.dragover {
    border: 5px dashed blue;
}
```

**Comment by Urigo** [comment]
I'm not sure I want to make a different example for each CSS Framework.
@veekungx thanks for the example

**Comment by aleksander351** [comment]
Not different for every css framework, but one that is more general and
works for all frameworks would be best.

Thank you veekungx!

V tor., 29. sep. 2015 05:18 je oseba Uri Goldshtein <
notifications@github.com> napisala:

**Comment by aleksander351** [comment]
"A more general example." With that I mean, at least for the file upload
tutorial.

V tor., 29. sep. 2015 05:18 je oseba Uri Goldshtein <
notifications@github.com> napisala:
