### ISSUE TITLE
UI not updating when removing item from a collection

### ISSUE THREAD

**Issue by damirkusar** [Urigo/angular-meteor#706]
In your Tutorial (http://angular-meteor.com/tutorials/angular1/adding-removing-objects-and-angular-event-handling) under point 4.7, when we introduce the `$scope.parties.remove(party);`, the UI is not getting updated. But the item is removed from the collection when checking the DB. When refreshing the page manually, the item is gone. Also tested to use urigo:angular instead and with it, it works fine, UI gets updated as expected. Here is the error when calling the remove method:

Exception in queued task: ReferenceError: EJSON is not defined
    at http://localhost:3000/packages/angular.js?bd3f456b6f161aa79dc09843803fa57faf2cb20b:948:14
    at http://localhost:3000/packages/underscore.js?46eaedbdeb6e71c82af1b16f51c7da4127d6f285:228:20
    at Array.some (native)
    at _.some._.any (http://localhost:3000/packages/underscore.js?46eaedbdeb6e71c82af1b16f51c7da4127d6f285:277:59)
    at Function._.find._.detect (http://localhost:3000/packages/underscore.js?46eaedbdeb6e71c82af1b16f51c7da4127d6f285:227:5)
    at Object.collectionUtils.findIndexById (http://localhost:3000/packages/angular.js?bd3f456b6f161aa79dc09843803fa57faf2cb20b:946:22)
    at Object._hObserve.cursor.observe.removedAt (http://localhost:3000/packages/angular.js?bd3f456b6f161aa79dc09843803fa57faf2cb20b:775:46)
    at observeChangesCallbacks.removed (http://localhost:3000/packages/minimongo.js?ddeb2f3d695025f8a898acc13d2fe121f9728127:3669:28)
    at Object.self.applyChange.removed (http://localhost:3000/packages/minimongo.js?ddeb2f3d695025f8a898acc13d2fe121f9728127:3598:44)
    at http://localhost:3000/packages/minimongo.js?ddeb2f3d695025f8a898acc13d2fe121f9728127:407:13

**Comment by fxckdead** [comment]
I was facing the same error, but it's simple, you need to add the EJSON package to your meteor project

``meteor add ejson``

Maybe it must be added to the list of dependencies @Urigo  ? 

Duplicated in #705

**Comment by shantanubhadoria** [comment]
yeah i face the same issue on update to 1.2.0 perhaps ejson can be added as a dependency?

**Comment by Urigo** [comment]
Fixed in `1.0.0-rc.10`

**Comment by damirkusar** [comment]
Hi Guys, 

thanks for the fast replies. @fxckdead, your tip did the job. Thanks.

**Comment by Urigo** [comment]
@damirkusar just using `angular@1.0.0-rc.10` wasn't enough?

**Comment by damirkusar** [comment]
@Urigo actually no, still had to add ejson. Maybe I did something wrong, its late :) i removed the package and added it again with 'meteor add angular@1.0.0-rc.10'. And also checked in '.meteor/packages' and found this entry: 'angular@1.0.0-rc.10'. 

Working on Mac 10.9.5, do you need more infos?

**Comment by Urigo** [comment]
@damirkusar sorry, I think I've missed something, can you please try again with `angular@1.0.0-rc.11`?

**Comment by damirkusar** [comment]
@Urigo yep, your latest changes solved the problem. Great work. 
Must say, meteor with angular makes fun, and with such a support its much more awesome :)
Thank you very much

**Comment by Urigo** [comment]
A missing dependency.......
happy you are happy!  keep the feedback coming
