### ISSUE TITLE
Add blaze-html-templates package to deps, since it can now be removed

### ISSUE THREAD

**Issue by uriva** [Urigo/angular-meteor#710]

**Comment by Urigo** [comment]
@uriva in the Meteor 1.2 branch of angular-meteor I'm working on a new build process that will replace that package and it could be removed.
First step is that I'm releasing `angular@1.0.0` right after `meteor 1.2.0.2` with the current build process to support all versions of Meteor and right after I'll release a new `angular@1.2.0` that will support the new build process and then `blaze-html-templates` could be removed.
In any way, I don't want to add it as a dependency as there are alternatives in case you remove it
