### ISSUE TITLE
$stateChangeError : 6 parameters instead of 4

### ISSUE THREAD

**Issue by jeje87** [Urigo/angular-meteor#713]
Hello,

I would point out to you that the $stateChangeError event have six callback parameters (instead of 4).

$rootScope.$on("$stateChangeError", function(event, toState, toParams, fromState, fromParams, error) {

}

Step 8 need to be updated.

Thanks for this great job !

**Comment by Urigo** [comment]
Thanks!  will update shortly, now focused on releasing 1.0.0 (waiting for a Meteor pull request to be shipped...)

**Comment by Urigo** [comment]
thanks @jeje87 for the great feedback, fixed and deployed. 
Sorry for the delay
