### ISSUE TITLE
Problem with collection transform

### ISSUE THREAD

**Issue by Deadly0** [Urigo/angular-meteor#720]
I have 2 collections: Sports and Leagues. It's convenient to use transformations to get all leagues belong to sport: `sport.getLeages()` 

```javascript
var methods = {
	getLeagues: function() {
		Leagues.find({sportId: this._id}).fetch()
	}
};

Sports = new Mongo.Collection('sports', {
	transform: function(entry) {
		_.extend(entry, methods)
		return entry
	}
});
```

It's works well when I use Blaze as template engine. But after migrating to angular I have lost reactivity for `Leagues` collection in this case. I think it's because I use `Leagues.find()` instead of `$meteor.Collection()`. But `$meteor` variable doesn't exist in this context and on server too. 

There is any solution to use `transform` in such case?

**Comment by netanelgilad** [comment]
Hey @Deadly0 ,
Where are you calling sport.getLeagues? Without seeing the code, I can assume that when blaze was used it was called inside a template helper or something of the like, which are run inside a reactive context, so blaze keeps your templates reactive in that way. In angular-meteor if you want to keep the reactivity that the `find` method of a collection offers, then you need to make sure you run that code in a reactive context as well, which could be a $meteor.autorun function.
If further explanation is needed, don't hesitate :smile:

**Comment by Urigo** [comment]
With the new [Angular Meteor 1.3 release](http://info.meteor.com/blog/angular-meteor-1.3) and the `helpers` syntax, we don't wrap the regular Mongo Collections anymore so any Meteor package should work like you were using Blaze.
Let me know if that is not the case
