### ISSUE TITLE
add-platfrom doesn't work on windows?

### ISSUE THREAD

**Issue by muliyul** [Urigo/angular-meteor#722]
![image](https://cloud.githubusercontent.com/assets/8338082/10147725/7f48d820-6638-11e5-8b37-93bfc52322b2.png)

version 1.2.0.1

**Comment by Urigo** [comment]
@muliyul I think this issue should go on the Meteor repo: https://github.com/meteor/meteor/issues
Also add more info about your project like packages you are using etc..
