### ISSUE TITLE
ES2015 features not transpiled in ng.js files

### ISSUE THREAD

**Issue by klenis** [Urigo/angular-meteor#724]
Hi!

The transparent functionality of transpiling `.js` files with the `ecmascript` package in Meteor 1.2 works with `.js` files but it doesn't work with `.ng.js` files.

It would be awesome if this functionality would work for `.ng.js` files seamlessly without adding other babel packages or additional configuration.

```
meteor@1.2.0.2
angular@1.0.1
```

Thanks!

**Comment by Urigo** [comment]
Will be coming soon in `angular@1.2`

**Comment by Urigo** [comment]
In the meantime, use can use this package:
https://github.com/pbastowski/angular-meteor-babel/

**Comment by klenis** [comment]
Cool, thank you!

**Comment by Urigo** [comment]
`angular@1.2.0` has been released
