### ISSUE TITLE
Document rollback when insert directly in Mongo CLI

### ISSUE THREAD

**Issue by firdausramlan** [Urigo/angular-meteor#73]
When inserting first data directly in Mongo CLI for the first time, the view get updated with new data.

```
db.parties.insert({name: 'Party Name', description: 'Party Desc'});
```

But after inserting second data using Mongo CLI or browser, the first data just gone.

I'm testing the socially-step04

**Comment by jakobloekke** [comment]
Hi,


Just wanted to say hello and wish you a good  day!  By the way,  have you seen that  <http://favor.thechampconsulting.com/e4kobq>

Sent from a prehistoric stone tablet, jakob@jakobloekkemadsen.com
