### ISSUE TITLE
Aligning login buttons

### ISSUE THREAD

**Issue by jalapagos** [Urigo/angular-meteor#730]
Hi,

From looking through the issues, I have found out that 
    
    <meteor-include src="loginButtons"></meteor-include>
 
has been depreciated for :					

    <blaze-template
 	   name="loginButtons">
    </blaze-template>

This works, however, the default dropdown is to the right. I wish to make it dropdown to the left. 
I attempted using :   
     
    align="left"

Didn't work so I thought I'd ask here if there is any specific way to make it dropdown to the left. 

Thanks

**Comment by Urigo** [comment]
Good question, you can read how here:
http://angular-meteor.com/api/blaze-template#passingargumentstoblazetemplate
