### ISSUE TITLE
$meteor.call causing ReferenceError on server

### ISSUE THREAD

**Issue by jonmc12** [Urigo/angular-meteor#734]
I've been using angular@1.0.1, and today received an error when using ```$meteor.call```.  This error does not appear when calling ```Meteor.call``` from either the client or the server.

```
Exception while invoking method 'createSpreadSheet' ReferenceError: path is not defined
   at [object Object].Meteor.methods.createSpreadSheet (server/tools.js:147:1)
   at maybeAuditArgumentChecks (livedata_server.js:1692:12)
   at livedata_server.js:708:19
   at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
   at livedata_server.js:706:40
   at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
   at livedata_server.js:704:46
   at tryCallTwo (/Users/jonmc12/.meteor/packages/promise/.0.5.0.h2jsml++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
at doResolve (/Users/jonmc12/.meteor/packages/promise/.0.5.0.h2jsml++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
at new Promise (/Users/jonmc12/.meteor/packages/promise/.0.5.0.h2jsml++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
```

I have resolved the error locally by changing API usage in [package.js](https://github.com/Urigo/angular-meteor/blob/master/package.js#L33).  It works when I change

```
api.use('check');
```
to
```
api.use('check', 'client');
```

**Comment by Urigo** [comment]
Are you using the `check` package or function somewhere?

**Comment by Urigo** [comment]
In anyway we use `check` in the code just on the client side so I'm pushing a fix.

**Comment by jonmc12** [comment]
Thank for fix!  I wasn't sure if needed on server or would have provided pull request

**Comment by jonmc12** [comment]
@Urigo I'm really having trouble with this bug.  I've tried various things, and every time it is fixed for a short period of time and then re-appears.

Yesterday, I fixed by removing the use of the check method in the angular-meteor method and other places in my code.  However, this morning the error reappeared.

Today, the error seems to have temporarily disappeared as I ran ```meteor remove check```.  However, this fix is not working on my colleague's machine.

While I only see this bug when using ```$meteor.call```, the error actually originates from the [DDP server](https://github.com/meteor/meteor/blob/devel/packages/ddp-server/livedata_server.js), would it be better filed in the issues for Meteor repo?

**Comment by jonmc12** [comment]
Update: I believe I have found a way to work around this issue permanently by finding an alternative to the ```path``` command.  My apologies for all the 'issue spam', but I believe this issue will come up for other users as time goes on and it is changing the way I need to write code within my Meteor Methods.

**Comment by Urigo** [comment]
@jonmc12 can you elaborate on this issue and your code?

**Comment by jonmc12** [comment]
@Urigo I've attempted to show a reproduction of the underlying cause of this issue [in a fork meteor-angular-socially](https://github.com/jonmc12/meteor-angular-socially).  At this point, I believe its a Meteor issue, and not necessarily an Angular Meteor specific bug.

```
git clone https://github.com/jonmc12/meteor-angular-socially.git
cd meteor-angular-socially
meteor
```

from client:  ```Meteor.call('testPath')``` and ```$meteor.call('testPath')``` - both will trigger the error above:

```
Exception while invoking method 'testPath' ReferenceError: path is not defined
   at [object Object].Meteor.methods.testPath (server/users.js:7:17)
   at maybeAuditArgumentChecks (livedata_server.js:1692:12)
   at livedata_server.js:708:19
   at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
   at livedata_server.js:706:40
   at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
   at livedata_server.js:704:46
   at tryCallTwo (/Users/jonmc12/.meteor/packages/promise/.0.4.8.1cke04u++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/domains/core.js:45:5)
   at doResolve (/Users/jonmc12/.meteor/packages/promise/.0.4.8.1cke04u++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/domains/core.js:171:13)
   at new Promise (/Users/jonmc12/.meteor/packages/promise/.0.4.8.1cke04u++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/domains/core.js:65:3)
```

Next,  open ```meteor shell``` and from the shell ```Meteor.call('testPath')``` - you will see this works.  It seems strange to me that the method works differently on the client than the server.

Now, go back into your browser and issue ```Meteor.call('testPath')``` and ```$meteor.call('testPath')```.  Both of these commands will no longer trigger an error.

In my own code repo, there seems to be a set of package dependencies that is exacerbating this issue in a way that the appears intermittently and non-deterministically.  Some of the things I've observed that will cause the error to come and go:

1.  Change ```api.use('check', 'client')``` in package.js in angular-meteor
2.  Change version of ```check``` in versions.json in angular-meteor
3.  ```meteor add check``` and ```meteor remove check```
4.  Reseting server via ```meteor run ios-device```
5.  Waiting several hours (I should note I have a few cron jobs running)
6.  ```meteor add ongoworks:google-spreadsheets``` and ```meteor remove ongoworks:google-spreadsheets``` - note: this package uses ```Npm.require('path');``` and also the ```check``` method
7.  ```meteor remove angular``` and ```meteor add angular```

At this point, I've changed the code in my repo to work around this error, so I hope it will no longer affect my methods.  I'm thinking I should file this as an issue on the Meteor project as a next step to help examine the underlying packaging issues.

**Comment by Urigo** [comment]
@jonmc12 please try to create a reproduction of this error without the `angular` package and open it as in issue in Meteor.
I'm not merging your pull request as I think the new version of `check` came after Meteor 1.2 and I don't want version 1.0 to be dependent on that.
What do you think?

**Comment by jonmc12** [comment]
@Urigo all sounds good to me.. I filed a [meteor issue](https://github.com/meteor/meteor/issues/5415) today using the todos example
