### ISSUE TITLE
Reactive parameters to subscription

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular-meteor#735]
This relates to https://github.com/Urigo/angular-meteor/issues/732

I think there is actually a problem here, but I am not quite sure what it is. 
I created a sample app running here http://ng-leaderboard-3.meteor.com. 

Click on top / first players. There is an initial limit value. If you go above it the subscription updates correctly. If you go bellow the original number - it remains with the original number of players. 

Code is here: https://github.com/Tallyb/ng-leaderboard-3

At first I thought it is calling for $scope.$meteorCollection().Subscribe() with subscription name and parameters (which BTW is not correctly documented - I will issue a PR), as in the leaderboard-first. But the same happens when I call $scope.$meteorCollection and $scope.$meteorSubscribe separately, as I did in leaderboard-top. 
Any ideas?

**Comment by mgrivera** [comment]
> At first I thought it is calling for $scope.$meteorCollection().Subscribe() with subscription name *and parameters* (which BTW is not correctly documented - I will issue a PR) ... 

Wow, this is fantastic! I never do subscribe using *$meteorCollection().Subscribe()* because I can't use parameters to limit the subscription. Now you are saying it is, indeed, possible. Could you please elaborate? 

Thanks ....

**Comment by Tallyb** [comment]
Apparently it is calling the $subscribe with all parameters: https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-collection.js line 57.

**Comment by netanelgilad** [comment]
Hey @Tallyb,
This is quite a simple mistake :smile:.
You create the controller twice, once by using ng-controller, and once by using it on the state with ui-router. So what happens is you always have another subscription in the background running for the default limit. Try removing the ng-controller from the templates and see the magic happens :wink:

**Comment by Tallyb** [comment]
Hola @netanelgilad  - back from your travels? 
You mean - a really stupid mistake... well spotted. Surely does the magic. 
Anyway - is it true that we can use $scope.$meteorCollection().Subscribe() with parameters?

**Comment by netanelgilad** [comment]
Yes, I'm back to business :)
And yep, $meteorCollection.subscribe is just a shortcut for the regular subscribe function, so all arguments are passed through.

**Comment by mgrivera** [comment]
> And yep, $meteorCollection.subscribe is just a shortcut for the regular subscribe function, so all 
>  arguments are passed through.

Now this are *really* fantastic news ...
