### ISSUE TITLE
Tutorial / example app should run with strict dependency injection mode

### ISSUE THREAD

**Issue by uriva** [Urigo/angular-meteor#737]
Like so:
`angular.bootstrap(document, ['myApp'], {strictDi: true});`

Otherwise one might encounter very hard to debug error messages on production which do not replicate locally.

**Comment by Urigo** [comment]
Good point, will update soon!

**Comment by dotansimha** [comment]
@Urigo @uriva 
Done!

**Comment by Urigo** [comment]
@dotansimha are you sure?   I did changed it to use `ng-annotate` with `.ng.js` but I think you haven't added `, {strictDi: true}`

**Comment by dotansimha** [comment]
@urigo 
In the beginning I use ng-strict-di and only when we change the ng-app to angular.bootstrap,  I changed it to strictDi: true

**Comment by Urigo** [comment]
ohhhhh  ok cool!
thanks
