### ISSUE TITLE
Angular-Meteor + Ionic + Typescript

### ISSUE THREAD

**Issue by jacobdr** [Urigo/angular-meteor#738]
I am hesitant to post this as a bug -- rather its more of a call out to the community to see where we stand when we combine these three bleeding-edge frameworks (Angular-Meteor + Ionic + Typescript).

I was successfully able to clone @netanelgilad's [meteor-ionic-example](https://github.com/netanelgilad/meteor-ionic-example), update it to Meteor 1.2, swap out `urigo:angular` for the now-standard namespace `angular` package, and move all the code into a client subdirectory. All was good in the world. I owe @netanelgilad a PR to update the example.. but I digress. 

Then I tried to add `meteortypescript:compiler` and the whole world blew up. I was getting failure in the browser related to bootstrapping order, and the white screen of death on my ios emulator. The worst part is that even reverting the filename to just .js (and .ng.js) didn't fix the state of the world -- even after clearing out the ".meteor/local" directory. 

I've now written a full, multi-thousand line Angular-Meteor project in Typescript and really came to appreciate the type safety and schema-checking on collections that it provides. I would love to bring that along as I now try to experiment with the beautiful Ionic framework. 

Does anyone have a working example of an app that uses Angular-Meteor + Ionic + Typescript? And if they aren't all playing nice together now, I would be interested in converting this ticket to a feature request, as the marriage of those three I feel would put this project at Mars 3000 awesome future status.

**Comment by adriangordon1231** [comment]
+1

**Comment by netanelgilad** [comment]
Hey @jacobdr ,
do you have a repository setup where I can take a look on what's going on when all of these packages are used together?
I would have assumed that using angular-meteor with typescript would be the problem (because of file extension problems) and adding ionic should not affect anything, but that does not seem to be the case by what you're expressing. I would be interested in knowing what goes down there...

**Comment by Urigo** [comment]
also, I think the new typescript compiler used in the Angular 2.0 Meteor package might be better

**Comment by pbastowski** [comment]
@jacobdr @Urigo have a look at this https://github.com/pbastowski/meteor-ionic-example/tree/feature/typescript. Clone it. Run it.

This shows how to use my typescript package without SystemJS, as a replacement for Babel / ecmascript.

Although, I'd recommend using it with SystemJS, as shown in this example https://github.com/pbastowski/meteor-angular-socially/tree/feature/step-17-ng2now-ts.

Let me know what you think.

**Comment by Urigo** [comment]
@pbastowski awesome!
