### ISSUE TITLE
How to display Loading

### ISSUE THREAD

**Issue by Rian0702** [Urigo/angular-meteor#741]
Could you please provide a best practice how to display a loading bar if a collection is loaded from the server ?

**Comment by adriangordon1231** [comment]
I don't know if this is standard, but this is how I would do it: 

Controller.js
```
this.showPreloader = false; 
var self = this;

$meteor.subscribe("publishedCollection").then(function(){

    self.showPreloader = true;
});
```

Then you simply display a gif in your template only when showPreloader == true.


Template.ng.html
```
<div ng-controller = "Controller as ctrl ">
    <div ng-show="ctrl.showPreloader">
        <img ng-src="mygif.gif" />
    </div>
</div>
```

**Comment by Rian0702** [comment]
thank you but i think this shows the loading if the collection is loaded because you set it true in the "then" promise. am i right or do i understand something wrong here?

**Comment by mxab** [comment]
to ensure that it stops spinning incase an error occurs, I use it in the finally method of the promise

```
$meteor.subscribe("publishedCollection").finally(function(){
    self.showPreloader = false;
});
```

**Comment by Tallyb** [comment]
@Rian0702 from the documentation: $meteor.subscribe() 
returns: promise(subscriptionHandle)	
The promise solved successfully when subscription is ready. The success promise holds the subscription handle.

**Comment by mgrivera** [comment]
@Rian0702 ... well, you should set it true *before* calling the subscription, then, as @mxab suggests turn it off in finally method ... that way the spinner will be off whatever is the result of the promise (success or failure) ...

**Comment by adriangordon1231** [comment]
@RichardLitt Yes. that was an error on my part.It should be the other way around

**Comment by RichardLitt** [comment]
Pretty sure you mean @Rian0702...?

**Comment by netanelgilad** [comment]
@Rian0702 Did the answers resolve your issue?

**Comment by Rian0702** [comment]
Yes, sorry for my late response:)
