### ISSUE TITLE
$rootScope.currentUser is not acting like a Reactive Data Source

### ISSUE THREAD

**Issue by Svenskunganka** [Urigo/angular-meteor#742]
Hey!

I've got this code:

```Javascript
$scope.$meteorAutorun(function() {
    if ($rootScope.currentUser.completedGuides &&
        $rootScope.currentUser.completedGuides.indexOf($scope.guide._id) > -1) {
      $scope.isChecked = true;
    } else {
      $scope.isChecked = false;
    }
  });
```

But the `$rootScope.currentUser` variable is not re-running the function when it updates as I have this code in Meteor:

```Javascript
Meteor.publish('userData', function() {
  if (this.userId) {
    return Meteor.users.find({ _id: this.userId }, { fields: { completedGuides: 1 } });
  } else {
    this.ready();
  }
});
```
and this code in a `.run` function in my app:
```Javascript
angular.module('myApp')
.run(['$meteor', function($meteor) {
  $meteor.subscribe('userData');
}]);
```

If I create a never ending loop with a 1 second wait, I can see that after one second or so the `completedGuides` property shows up in the `$rootScope.currentUser` object, but the `$scope.$meteorAutorun` function is not being re-run.

Looking at [angular-meteor-user.js#L79](https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-user.js#L79) I can see that the `$rootScope.currentUser` is simply a replicate of `Meteor.user()`, and above that line I can also see that the autorun function is bound to the `$rootScope` scope. I've tried replacing my `$scope.meteorAutorun(fn)` with `$meteor.autorun($rootScope, fn)` without success.

Any clues why this is happening or do I have some code issues?

**Comment by mxab** [comment]
You should use Meteor.user() for your use case.
```
$scope.$meteorAutorun(function() {
var currentUser = Meteor.user();
    if (currentUser.completedGuides &&
        currentUser.completedGuides.indexOf($scope.guide._id) > -1) {
      $scope.isChecked = true;
    } else {
      $scope.isChecked = false;
    }
  });
```

There is no way the autorun could detect that you are accessing a property.

**Comment by Svenskunganka** [comment]
Ah that worked like a charm! Thanks a bunch!

**Comment by Urigo** [comment]
I wonder if we could make $rootScope.currentUser reactive...

**Comment by Svenskunganka** [comment]
How about making `$rootScope.currentUser` a method instead that simply calls `Meteor.user()` and return its value? Don't know if that works reactively as it's another layer that the Tracker has to monitor.

An example:

```
$rootScope.currentUser = function() {
    return Meteor.user();
  }

$scope.$meteorAutorun(function() {
  if ($rootScope.currentUser().completedGuides &&
        $rootScope.currentUser().completedGuides.indexOf($scope.guide._id) > -1) {
      $scope.isChecked = true;
    } else {
      $scope.isChecked = false;
    }
});
```

**Comment by mxab** [comment]
I think you simply should stick to using Meteor.user() in the autorun. As far as I see it the currentUser is more supposed to be used in the templates, not functions

```
<button ng-if="$root.currentUser">Logout</button>
```

You wouldn't gain anything by adding the currentUser as a function to the rootScope.

I guess you could play around with Object.defineProperty to make it reactive, but still you wouldn't have gained anything besides having a reactive property on the rootScope.

If you want to have a reactive currentUser call on something angularish, I guess it would be better to extend the $meteor service with the currentUser() call
