### ISSUE TITLE
Strange Max Call Error when saving $scope item

### ISSUE THREAD

**Issue by justingrayston** [Urigo/angular-meteor#744]
Firstly, meteor and in particular Angular Meteor is brilliant. I stumbled across it researching for a project.
I went through the tutorial and then to embed some of the concepts and understanding I created my own little test app.

It is a simple CRUD app. However when editing and updating an item more than once, I was getting the following error.

```
RangeError: Maximum call stack size exceeded
    at Object (native)
    at isArrayLike (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:299:28)
    at Object.forEach (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:355:32)
    at angularMeteorUtils.service.$timeout.stripDollarPrefixedKeys (http://localhost:3000/packages/angular.js?79d598e7209fc684674dfb4e34a62c9c0e619f58:1509:15)
    at http://localhost:3000/packages/angular.js?79d598e7209fc684674dfb4e34a62c9c0e619f58:1511:25
    at Object.forEach (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:373:20)
    at angularMeteorUtils.service.$timeout.stripDollarPrefixedKeys (http://localhost:3000/packages/angular.js?79d598e7209fc684674dfb4e34a62c9c0e619f58:1509:15)
    at http://localhost:3000/packages/angular.js?79d598e7209fc684674dfb4e34a62c9c0e619f58:1511:25
    at Object.forEach (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:373:20)
    at angularMeteorUtils.service.$timeout.stripDollarPrefixedKeys (http://localhost:3000/packages/angular.js?79d598e7209fc684674dfb4e34a62c9c0e619f58:1509:15)
```

Now, it is highly likely it is something so obvious that someone who uses this a lot may know what I am doing wrong, but I have revisited with (sort of) fresh eyes, and I can't see what I am doing wrong. The tutorial I don't think covers this exactly, because this isn't just autobinding the changes. You make the changes in the form and then use the collection save method to update the item.

The problem seems to be all the extra properties that get added to the object. This then gets saved out to the DB and when subsequently loaded and re-saved we get nasty recursion. 

I resolved it by saving a new object and assigning the properties I actually wanted to it. This worked fine, but seems hacky (hence I think I must be missing something obvious).

The working app is here: [bookish-123.meteor.com](http://bookish-123.meteor.com)

I have deployed the failing app with the original code saving the $scope.book directly here:
[bookish-666.meteor.com](http://bookish-666.meteor.com) so you can see it in action. Steps to replicate are:
 * Create Item
 * Edit Item Save - It works fine
 * Open item again to edit and save
 * Error thrown (See below)

I have started an actual project prototype and created a modelUtils service with a clean up script that removes all _xxx and $xxxx properties except for _id.

It uses lodash though, but could easilly be done with out (I was just being lazy ;) )

```js
cleanProperties: function(model) {
      return lodash.omit(model, function(v, k){
        return (lodash.startsWith(k, '$') || lodash.startsWith(k, '_')) && k !== '_id';
      });
    }
```

If this isn't me being dumb, I would be happy to update the existing clean up script (which removes $ properties), and submit a pull (with supporting tests).

The code for the test app is here https://github.com/justingrayston/meteorjs-bookish if you want to see in detail what I am doing. The controller in question is https://github.com/justingrayston/meteorjs-bookish/blob/master/client/books/controllers/editBook.js

Thanks!

**Comment by jacobdr** [comment]
@Urigo Maybe a problem with the base case in the recursive [stripDollarPrefixedKeys](https://github.com/Urigo/angular-meteor/blob/3e0dc78a0178e1b58f842b6e1e119a1a39a16d27/modules/angular-meteor-utils.js#L28)?

If I have some time later I'll try to transpose @justingrayston's code into a test case

**Comment by justingrayston** [comment]
Thanks @jacobdr 

I figured thats where the problem is, I just didn't want to dive in if I was missing something obvious.

On initial scan I thought the cause could be the _serverBackup property. It isn't a string value and it doesn't start with $ and looking at the object (in console it logs the object being sent to the save method) the _serverBackUp object seems to recurse, which would lead to this error. This is why I thought there must me something I am missing. Removing those _ properties (except for _id) prevents this from happening. 

Would be good to see if you get the recursive _serverBackup too!

**Comment by netanelgilad** [comment]
Hey @justingrayston,
I'm trying to run your code and get the error but it doesn't seem to happen to me.
I have cloned your repo and run the code, no error. I went to the saveBook method and changed it to:
`$scope.book.save().then(...)` but that also doesn't get me the error. What am I missing here?

**Comment by justingrayston** [comment]
Hi @netanelgilad 

You should be able to replicate at http://bookish-666.meteor.com/

Apologies I should have put the breaking code in a branch.

Change the save function to this...

```
  $scope.saveBook = function() {

    $scope.book.owner = $rootScope.currentUser._id;

    books.save($scope.book).then(saveSuccess, saveError);
  };
```

It is saving the object with the _collection_ rather than the loaded _object_ itself that causes the error. I can confirm that $scope.book.save() works without issue. The function above replicates locally for me.

I realised just now, that in a real project that I have started I am testing in the save function if the object object is new or not and using the appropriate method. Then I don't have the problem because I am either saving a new Object into the collection or using the Meteor Object save method.

However, it should probably not fall over if you just use the collection save method with a Meteor Object.

Let me know how you get on and if you still can't replicate.

**Comment by Urigo** [comment]
This issue shouldn't happen with the new [Angular Meteor 1.3 release](http://info.meteor.com/blog/angular-meteor-1.3) and the `helpers` syntax.
Let me know if that is not the case

**Comment by suryaiiit** [comment]
I still see this issue.

**Comment by Urigo** [comment]
@justingrayston @suryaiiit I've tested it now and it works for me.
Can you please share a reproduction?

**Comment by justingrayston** [comment]
I will update the original example app later tonight. My take on Uri's
comment was that as this API will be deprecated as of 1.4 the issue can be
closed as the core problem won't be an issue is you use helpers. I'll
branch a version using the helpers API, which should highlight any issues.

**Comment by justingrayston** [comment]
I modified the failing code to the 1.3 helpers API. 

https://github.com/justingrayston/meteorjs-bookish/tree/max-call-stack-1.3

It is rough and ready, but it clearly doesn't have the max call stack error. It may exist in the old API still, but as that is under deprecation warning and people should move to the helpers API as per @Urigo stated. I would no longer class this a bug in this version of the code (1.3)
