### ISSUE TITLE
Tutorial  - ng-annotate and .ng.js

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#747]
To save confusion and make it easier to read; would it not be better to show all the examples of the controllers using the ng.js method as in  section 2 .

Also I would suggest making ng-annotate part of the Meteor Angular package as Meteor will perform minification when deployed.

**Comment by Urigo** [comment]
@JohnAReid Agree with your first point.
will update soon.
about the second point - it already is...

**Comment by JohnAReid** [comment]
thanks

**Comment by dotansimha** [comment]
@JohnAReid 
Done!

**Comment by Urigo** [comment]
Awesome @dotansimha !
