### ISSUE TITLE
API blaze-template and project structure issues

### ISSUE THREAD

**Issue by mbeaudru** [Urigo/angular-meteor#750]
Hi,

Following instructions of this page, http://angular-meteor.com/api/blaze-template , i've been able to use a blaze-template inside my project, which is already great. 

But now, i'd like to move my templates definitions which are below the body tag for lisibility purposes. In fact, the only way for me to make templates working well has been to define them below the body tag and nowhere else and I don't know why.

I've tried to ng-include templates definitions below the body tag but it raises a "Expected one of: body, head, template" error which seems legitimate.

So do you have a solution or a best practice in order to have a better project structure with blazer-template API ?

Thank's

**Comment by Urigo** [comment]
@mbeaudru can you please share a reproduction of your problem?

**Comment by mbeaudru** [comment]
Sure, thank you for your fast reply !

Here is my actual structure (truncated) :
```
-client
    -index.html
    -app.ng.js
    -actualities
        -views
            -actualities-list.ng.html
```
The blaze-template integration works when it is defined below the body tag like this :
index.html
```html
<head>
    <base href="/">
</head>
<body>
<div ng-app="pulse">
    <div ui-view></div>
</div>
</body>

<template name="addActuality">
[...]
</template>
```

I would like to have a more readable code in storing this template definition somewhere else. Or, if not possible, just store it in addActuality.ng.html located here for instance :

```
-client
    -index.html
    -app.ng.js
    -actualities
        -views
            -actualities-list.ng.html
        -templates
            -addActuality.ng.html
```
And then call this file with an ng-include directive for instance, below the body tag (which is not working as said in the first post).

But, if you have a better solution to manage templates I'm listening.

**Comment by Urigo** [comment]
@mbeaudru is `addActuality.ng.html` contains Blaze templates?
If so, it has to be named `addActuality.html`

**Comment by mbeaudru** [comment]
Of course ! This was so easy, thank you very much ! 

By the way, I really appreciate your work you've done an amazing job.
