### ISSUE TITLE
Why concatenate first directory inside package with underscore instead of slash?

### ISSUE THREAD

**Issue by sebakerckhof** [Urigo/angular-meteor#752]
Referencing to this line: https://github.com/Urigo/angular-meteor/blob/master/plugin/handler.js#L20

Why are templates cached like: 'author_packagename_path/to/file.js' instead of 'author_packagename/path/to/file.js' which IMO makes more sense?

**Comment by Urigo** [comment]
@sebakerckhof I agree.
Can you make a pull request that will make that consistent with the new build process of Meteor and the way we bring package assets?
thank you for the great suggestion

**Comment by sebakerckhof** [comment]
@Urigo Should I way till PR #719 lands? Also, this will break current packages. So maybe we should think about backwards compatability and support both cases but print a deprecation message?

**Comment by Urigo** [comment]
You don't need to wait for #719 but I know it will create a breaking change.
This is why I will release it only as part on version 1.2 that will break things anyway...

**Comment by netanelgilad** [comment]
In the new build process for templates it now uses forward slash: https://github.com/Urigo/angular-meteor/blob/feature/meteor1.2/plugin/ng-caching-html-compiler.js#L7

**Comment by Urigo** [comment]
@sebakerckhof I've just released `angular@1.2.0` with the new build process.
Let me know if that works for you

**Comment by sebakerckhof** [comment]
Yeah, I was already using rc2 and no problems so far.
