### ISSUE TITLE
Undefined when i refresh the navigator

### ISSUE THREAD

**Issue by isibz** [Urigo/angular-meteor#753]
Hi,

When i refresh the navigator i print into the console $scope.web._id and prints UNDEFINED but when i print $scope.web prints the Object.
Any solution to print the value?

CODE:

angular.module('App')
.controller('WebDetailCtrl', function($scope, $stateParams, $meteor , $location) {
  
  $scope.web = $meteor.object(Webs, $stateParams.webId,false);
    var subscriptionHandle;
    $meteor.subscribe('webs').then(function(handle) {
    subscriptionHandle = handle;
    });

  $scope.$on('$destroy', function() {
      subscriptionHandle.stop();
    });
  
  $scope.save = function() {
    if($scope.form.$valid) {
      Meteor.call('actualizarWeb', $scope.web.getRawObject());
      $location.path('/main/webs');      
    }
  };   
 
  //ISSUE
  console.log ($scope.web); //On navigator refresh SubObject (...)
  console.log ($scope.web._id); //On navigator refresh UNDEFINED

});

**Comment by Urigo** [comment]
@isibz that's probably because the subscription has not finished yet.

You can try to change your code to this:

    var subscriptionHandle;
    $meteor.subscribe('webs').then(function(handle) {
      subscriptionHandle = handle;
      $scope.web = $meteor.object(Webs, $stateParams.webId,false);

      console.log ($scope.web); //On navigator refresh SubObject (...)
      console.log ($scope.web._id); //On navigator refresh UNDEFINED
    });
