### ISSUE TITLE
Maximum Callstack exceeded  - Meteor transform

### ISSUE THREAD

**Issue by Rian0702** [Urigo/angular-meteor#757]
Hello, 
everytime i try to use transform i get the "Maximum Callstack Exceeded Errror" 

member is just an array of userIds

My Code: 
```javascript
Relations = new Mongo.Collection("relations",
    {
        transform: function (doc) {
            doc.MembersObject = Meteor.users.find({
                _id: { $in: doc.member }
            });
            return doc;
        }
    });
```

**Comment by mxab** [comment]
Don't add a MongoCursor to your object this will result in strange things if you try to serialize that

you could add a .fetch() at the end after your find

**Comment by Rian0702** [comment]
okay. Sorry i am completely new to Mongo and just tried something like a join. Could you provide a small example or a link ?

**Comment by mxab** [comment]
maybe something like this
```
Relations = new Mongo.Collection("relations",
    {
        transform: function (doc) {
            doc.members = Meteor.users.find({
                _id: { $in: doc.member }
            }).fetch()
            return doc;
        }
    })
```

Depending what you want to do you could also have a look at this
https://github.com/englue/meteor-publish-composite/

**Comment by Rian0702** [comment]
Thank you very much! This works. :+1: 

Really dont understand why but i will have a look at your link and at the fetch function soon :)
