### ISSUE TITLE
Need to update version of angularjs:angular-animate

### ISSUE THREAD

**Issue by Furqankhanzada** [Urigo/angular-meteor#758]
@Urigo i don't know where i need to request fro this :)

[angularjs](https://atmospherejs.com/angularjs) packages have updated version ```1.3.15``` except ```angularjs:angular-animate```. it has ```1.3.13``` thats why its giving me error with latest angularjs version.

**Comment by Urigo** [comment]
@dotansimha

**Comment by mxab** [comment]
@Furqankhanzada I think you are using the wrong namespace
angular:angular should be very up to date
https://atmospherejs.com/angular/angular

**Comment by Urigo** [comment]
ohh that's right, haven't noticed that in your issue.
thanks @mxab

**Comment by Furqankhanzada** [comment]
Thanks @Urigo and @mxab :)
