### ISSUE TITLE
Update scope first and meteor on background.

### ISSUE THREAD

**Issue by simonbonjean** [Urigo/angular-meteor#761]
My angular app create controls on a canvas and we can move it with keyboard arrow.

I create link between my angular model and meteor. After that, moving is very slow.
I think view is update after meteor mongo server. 

There is a bouncing  solution ? 

**Before meteor**
![motion quick](https://cloud.githubusercontent.com/assets/708696/10512756/1f00b8d0-7343-11e5-8fcf-e2528e7f6f04.gif)
**After meteor**
![motion slow](https://cloud.githubusercontent.com/assets/708696/10512981/b2788ac4-7344-11e5-8313-ca66396f7db0.gif)
```html

<div ng-style="{
        'left': 'calc(' + (control.x - control.width / 2) + '% - ' + control.strokeWidth + 'px)',
        'top': 'calc(' + (control.y - control.height / 2) + '% - ' + control.strokeWidth + 'px)'}"></div>

```

**Comment by simonbonjean** [comment]
GroundDB I thought could help me, but it changes nothing.

**Comment by netanelgilad** [comment]
This seems like an interesting case @simonbonjean.
What do you mean by creating a link between angular model and meteor? Have you used $meteorObject? What parameters have you given it?
If you can share your code, that would be great.

**Comment by Urigo** [comment]
closing as there wasn't a response.
Also, we significantly changed our API in [Angular Meteor 1.3](http://info.meteor.com/blog/angular-meteor-1.3) so it won't be an Angular specific problem
