### ISSUE TITLE
Cannot get $scope to work ngMaterial directives

### ISSUE THREAD

**Issue by zenonn37** [Urigo/angular-meteor#762]
Good Morning,
I cannot use $scope from a parent or child controller, with ngMaterial. For example, if I try to use a toolbar directive with $scope.title = "Title" for the brand it will not render. This example failed in the angular-meteor.com tutorial as well. This example works fine out of meteor, with all angular and ngMat versions. Thanks for your help in advance.

Chris

**Comment by Tallyb** [comment]
Well, it is probably something very specific to your repo. Material works really well with angular-meteor . here is a demo http://angular-meteor-material.meteor.com/ and the repo is here https://github.com/Tallyb/angular-meteor-material

**Comment by Urigo** [comment]
@zenonn37 please let us know if you found the bug
