### ISSUE TITLE
Windows-incompatible filenames in docs

### ISSUE THREAD

**Issue by nickbenes** [Urigo/angular-meteor#765]
I recently had to switch to a Windows machine and bumped into an annoying quirk yesterday that prevented me from cloning angular-meteor in Windows.

Windows file/folder names are not allowed to have colons (`:`) in them, since they reserve that for drive names. Right now, angular-meteor has a folder called
```
angular-meteor/.docs/angular-meteor/packages/tutorial-step-diff-compiler/.npm/plugin/mdg:tutorial-step-diffs-plugin/
```
Looks like this is a dev version of the standard [mdg:tutorial-step-diff-compiler](https://atmospherejs.com/mdg/tutorial-step-diff-compiler) used by [mdg:tutorial-diff-box](https://atmospherejs.com/mdg/tutorial-diff-box). The standard version is also included in `angular-meteor/.docs/angular-meteor/.meteor/packages`, so I was able to remove the dev version and haven't seen any issues.

Before I do a PR for my [win-compat](https://github.com/nickbenes/angular-meteor/tree/win-compat) changes, though, I want to see if there's a need to keep the dev version. @barbatus made some recent changes to its [plugin.js](https://github.com/Urigo/angular-meteor/blame/master/.docs/angular-meteor/packages/tutorial-step-diff-compiler/plugin.js) file, and @dotansimha has done some work with the dev version as well.

Is there a need to keep the dev version of `tutorial-step-diff-compiler` or can we stick with the official version? Should I incorporate the changes from @barbatus somewhere else and if so, how?

**Comment by Urigo** [comment]
@Tallyb I think you opened an issue on the tutorial tool repo on that no?

**Comment by Tallyb** [comment]
I thought I did, but I cannot find it. 
This issue exists on this repository: https://github.com/Urigo/angular-meteor/issues/708

**Comment by nickbenes** [comment]
Great -- thanks!

**Comment by Urigo** [comment]
@Tallyb I was referring to this - https://github.com/meteor/tutorial-tools/issues/7

**Comment by Urigo** [comment]
fixed now.
