### ISSUE TITLE
Current getUpdate spec reporting incorrect errors

### ISSUE THREAD

**Issue by nickbenes** [Urigo/angular-meteor#770]
I just ran the test suite and got two errors that aren't really errors: "getUpdates module functionality should get updates when null-field is assigned a array-object" and "... when null-subfield is assigned a array-object".

The spec was expecting `{$set: {'a.0': 1, 'a.1': 2, 'a.2': 3}}`, but updating with that when `a` is null results in the error 
```
"writeError" : {
		"code" : 16837,
		"errmsg" : "cannot use the part (a of a.0) to traverse the element ({a: null})"
	}
```
I'm submitting a PR that fixes the spec. Thanks for taking a look!

**Comment by netanelgilad** [comment]
You are totally right. 
@Urigo this is due to my change in the way arrays are saved to mongo when first created, in my PR I didn't fix the expectations of these specs. :wink:

**Comment by Urigo** [comment]
@netanelgilad I wonder why the Travis tests still pass

**Comment by Urigo** [comment]
Merged, but still thinking about the travis tests
