### ISSUE TITLE
$meteor.loginWithPassword not working with Ionic

### ISSUE THREAD

**Issue by suryaiiit** [Urigo/angular-meteor#781]
Hi,

I'm trying my hands on Ionic Meteor using this: http://angular-meteor.com/ionic-tutorial
I'm not able to get $meteor.loginWithPassword working, I tried this at the 4th Step (http://angular-meteor.com/tutorials/ionic/authentication).

Anything missing for that to work.

Thanks.

**Comment by suryaiiit** [comment]
Looks like there is another library not added in Step-3 but there in Step-4 (may be the documentation is missed is Step-3). 
<script src="lib/accounts-base-client-side/dist/accounts-base-client-side.bundle.min.js"></script>

But then I get a different error:
TypeError: Cannot read property 'apply' of undefined
    at null.loginWithPassword (http://localhost:8100/lib/angular-meteor/dist/angular-meteor.bundle.js:2124:20)

not sure why is the null.loginWithPassword, below is my code:

$meteor.loginWithPassword($scope.loginData.username, $scope.loginData.password).then(function(data) {
                console.log('Login Success: ', data);
            }, function(error) {
                console.log('Login Error: ', error);
            })

Regards

**Comment by phaggood** [comment]
what does your 'meteor list' say?  I use the same syntax for
meteor.loginwithpassword and have the following when i list packages:

accounts-password   1.1.1* Password support for accounts

aldeed:collection2  2.5.0  Automatic validation of insert and update
operations on the client and server.

driftyco:ionic      1.1.0_2  Ionic Framework official Meteor package

insecure            1.0.3* Allow all database writes by default

lepozepo:s3         5.1.1* Upload files to S3. Allows use of Knox
Server-Side.

meteor-platform     1.2.2* Include a standard set of Meteor packages in
your app

urigo:angular       0.9.3* The simplest no-conflict way to use AngularJS
with Meteor, Meteorite and Atmosphere Smart Packa...

**Comment by suryaiiit** [comment]
As I wrote, I'm trying to do this using Ionic CLI .. as I already have a web application with Meteor.
hence meteor list is not valid, I think. But if you are asking me about the meteor list in my web app below is the list (loginWithPassword is working fine on the web app):

accounts-password                          1.1.3  Password support for accounts
alanning:roles                             1.2.14  Authorization package for Meteor
aldeed:collection2                         2.5.0  Automatic validation of insert and update operations on the client and server.
aldeed:simple-schema                       1.3.3  A simple schema validation object with reactivity. Used by collection2 and autoform.
alexk111:ng-img-crop                       0.3.2  Image Crop directive for AngularJS.
angular:angular-material                   0.11.1* Google Material design written for AngularJs (official repo)
angular:angular-messages                   1.4.6* AngularJS (official) release. For full solution: http://angular-meteor.com/
angularui:angular-google-maps              2.2.1  angular-google-maps (official)
angularui:angular-ui-router                0.2.15  angular-ui-router (official): Flexible routing with nested views in AngularJS
angularutils:pagination                    0.7.0* Magical automatic pagination for anything in AngularJS
blaze-html-templates                       1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
cfs:graphicsmagick                         0.0.18  Adds `gm` to scope with the ability to perform GraphicsMagick or ImageMagick manipulation
cfs:gridfs                                 0.0.33  GridFS storage adapter for CollectionFS
cfs:standard-packages                      0.5.9  Filesystem for Meteor, collectionFS
check                                      1.0.6  Check whether a value matches a pattern
civilframe:angular-jade-manually-modified  0.0.3+ Jade templating for Meteor-Angular
danialfarid:ng-file-upload                 5.0.9  An AngularJS directive for file upload using HTML5 with FileAPI polyfill for unsupported browsers
ecmascript                                 0.1.5  Compiler plugin that supports ES2015+ in all .js files
email                                      1.0.7  Send email messages
es5-shim                                   4.1.13  Shims and polyfills to improve ECMAScript 5 support
froala:editor                              1.2.8  A beautiful jQuery WYSIWYG HTML rich text editor.
jquery                                     1.11.4  Manipulate the DOM using CSS selectors
less                                       2.5.0_3  Leaner CSS language
meteor-base                                1.0.1  Packages that every Meteor app needs
mobile-experience                          1.0.1  Packages for a great mobile user experience
momentjs:moment                            2.10.6  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mongo                                      1.1.2  Adaptor for using MongoDB and Minimongo over DDP
netanelgilad:angular-sortable-view         0.0.13_1  Fully declarative (multi)sortable for AngularJS
okland:accounts-phone                      0.0.21  A login service based on mobile phone number, For Meteor.
session                                    1.1.1  Session variable
standard-minifiers                         1.0.1  Standard minifiers used with Meteor apps by default.
suryaiiit:meteor-angular-froala            0.0.1  Angular Froala for Meteor
tmeasday:publish-counts                    0.7.2  Publish the count of a cursor, in real time
tracker                                    1.0.9  Dependency tracker to allow reactive callbacks
urigo:angular                              1.0.1* Deprecated: use the official `angular` package instead!
vitalets:angular-xeditable                 0.1.9  Edit in place for AngularJS.

**Comment by suryaiiit** [comment]
Got it, I should add 'accounts-password-client-side'

Thanks.
