### ISSUE TITLE
New projects - this is not an issue - more of an request

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#787]
Having to create a test version on another issue, I created a new meter project, added angular, deleted the sample files and added new client server and model folders, then added app.ng.js, main and index files.

Would it not be possible to have a meteor createAngular call which would all this for us?

**Comment by Tallyb** [comment]
@JohnAReid 
If you are fond of material (I am!) - here is an opinionated  boiler plate with material account (login, logout, register) windows you can copy.
It has a todos app to point where to start. 

https://github.com/Tallyb/angular-meteor-material

[if you like it - please star...]

**Comment by JohnAReid** [comment]
Thank @Tallyb the boiler plate looks good but if I read it correctly the user would still have to create meteor then add the pakages for Angular and other items - I am suggesting this could be done in the Meteor create stage.

**Comment by Tallyb** [comment]
right...

**Comment by JohnAReid** [comment]
I beleive this would make Angular easier to work with Meteor - but as no one else is interested I have closed this issue.
