### ISSUE TITLE
Problem with fonts - base64 

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#790]
This problem which I have had for a few weeks (possibly after upgrading to 1.2) is driving me round the bend: Below is the error message I am getting in the chrome console window.

![image](https://cloud.githubusercontent.com/assets/7714810/10712311/53909a54-7a8f-11e5-83e0-d6be14593bd0.png)

The problem is that I cannot isolate the error - I have started a new project, added the packages one by one and then added the files used one by one. The problem seems to have gone then all of a sudden it returns - so I then delete the files one by one and the issue still exists - I am then back to a clean project with just an index page  - and still the issue occurs.

Then a brain wave - run the app in Chrome incognito window and low and behold - the app runs without any errors. So the same app running at the same time on the same pc produces no error in incognito - but with errors in normal chrome.

By the way I do not think it has anything to do the files reported - the error appears at any point in the source code within the console window - I get the js code with a red line below it:

![image](https://cloud.githubusercontent.com/assets/7714810/10712433/1f1dfd30-7a93-11e5-9fcf-458dbfeecdce.png)

The problem is that when these occur it stops the js code from running - and so it returns the wrong result.

I have put a post on the Meteor forum last week asking if anyone else has seen this problem - but I guess I am the only one!

I have spent most of the day trying to solve problem - have you any ideas what to do next?

**Comment by Tallyb** [comment]
Disable chrome extensions to eliminate the criminal.

**Comment by JohnAReid** [comment]
@Tallyb Thanks - you have stoppped me going round in circles!

**Comment by Tallyb** [comment]
@JohnAReid  share if you found anything...

**Comment by JohnAReid** [comment]
To be honest I started the computer this morning and I was going to clear the extensions one by one to see what was causing the error. The only problem is bizarrly the error did not come up again. I have no doubt it will come back again at some point which is why I haven't closed this issue.

**Comment by JohnAReid** [comment]
It makes less and less sense - problem came back with error reported in Chrome console window - opened a new window (not incognito) linked to the local host and the problem does not appear! Two normal chrome windows opened - one reports the error - the other does not!

**Comment by Urigo** [comment]
@JohnAReid are you sure it's an angular-meteor issue?

**Comment by JohnAReid** [comment]
I am totally not sure - as I cannot pin point the source of the error. 
The error only appears with Meteor apps local host - and only when the app gets more complex - i.e. create a new meteor app and it is OK.

As I seem to be the only one to have reported this problem I will close this issue - it is most likey due to one of the packages I am using.
