### ISSUE TITLE
"Cannot read property 'apply' of undefined" when clicking on a button with $meteor.loginWithFacebook()

### ISSUE THREAD

**Issue by maxfriedmann** [Urigo/angular-meteor#791]
Hi there,
since a couple of days the promise behind $meteor.loginWithFacebook and $meteor.loginWithGoogle don't work anymore in one of my project and I don't know why. 

Simple Button with a simple ng-clicked controller call that does $meteor.loginWithFacebook() produces this error message : 

```
TypeError: Cannot read property 'apply' of undefined
    at null.loginWithFacebook (http://localhost:3000/packages/angular.js?d2db9bfa9c7bfe58b5c47cd57d99ed5e3c86f7de:1558:20)
    at Scope.$scope.loginWithFacebook (http://localhost:3000/app/client/views/login/login.controller.js?d5174ac68dde8434571098a376bd3b5c7f2ca741:61:21)
    at fn (eval at <anonymous> (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:13345:15), <anonymous>:4:242)
    at callback (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:23572:17)
    at Scope.$eval (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:16012:28)
    at Scope.$apply (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:16112:25)
    at HTMLButtonElement.<anonymous> (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:23577:23)
    at HTMLButtonElement.jQuery.event.dispatch (http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:4691:9)
    at HTMLButtonElement.elemData.handle (http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:4359:28)(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246Scope.$apply @ angular.js:16094(anonymous function) @ angular.js:23554jQuery.event.dispatch @ jquery.js:4665elemData.handle @ jquery.js:4333
```

I am using v.1.0.3.

**Comment by piotrraczynski** [comment]
I got the same error for loginWithPassword function, v.1.0.3

**Comment by piotrraczynski** [comment]
I got this resolved. @maxfriedmann, install accounts-password-client-side then include accounts-password-client-side.bundle.js and accounts-pase-client-side.bundle.js

**Comment by Urigo** [comment]
Thanks @piotrraczynski

**Comment by vasanthns** [comment]
Hi,

I am getting the exact same error while trying $meteor.loginWithFacebook()

```TypeError: Cannot read property 'apply' of undefined
    at null.loginWithFacebook```

I am using all latest versions as well as included the package/JS files mentioned.

regards,
Vasanth

**Comment by dinesh36** [comment]
+1 @piotrraczynski

**Comment by Urigo** [comment]
With the new [Angular Meteor 1.3 release](http://info.meteor.com/blog/angular-meteor-1.3) the way we work with Meteor accounts has improved a lot.
No need for Angular wrappers anymore.
Check it out and let me know how did it worked for you here or in the post's comments

**Comment by neosekar** [comment]
Hi,
 I am getting the same error  **TypeError: Cannot read property 'apply' of undefined at null.loginWithFacebook** ,  i am using angular-meteor 1.3.6 version..

**Comment by ozsay** [comment]
@neosekar You don't need to use `$meteor` anymore.

You can just use `Meteor.loginWithFacebook` as described in the [official meteor docs](http://docs.meteor.com/#/full/meteor_loginwithexternalservice).

If you need to send a callback to the function use `$bindToContext` to be able to update your data reactively. Check the usage example in `ReactiveContext` [docs](http://www.angular-meteor.com/api/1.3.6/reactive-context).

**Comment by neosekar** [comment]
If i use Meteor method like this

** Meteor.loginWithFacebook({},
			function (error) {
				if (error) {
					return console.log(error);
				}
			});**

	 i am getting error like this,  **TypeError: Meteor.loginWithFacebook is not a function**.
Can you post any working sample code of loginWIthFacebook in angular-meteor.

**Comment by Urigo** [comment]
@neosekar have you add the `accounts-facebook` package?

**Comment by neosekar** [comment]
I already added the list of packages 

**accounts-base          1.2.2  A user account system
accounts-facebook      1.0.6  Login service for Facebook accounts
accounts-password      1.1.4  Password support for accounts
autopublish            1.0.4  (For prototyping only) Publish the entire ...
blaze-html-templates   1.0.1  Compile HTML templates into reactive UI wi...
ecmascript             0.1.6* Compiler plugin that supports ES2015+ in a...
es5-shim               4.1.14  Shims and polyfills to improve ECMAScript...
insecure               1.0.4  (For prototyping only) Allow all database ...
jquery                 1.11.4  Manipulate the DOM using CSS selectors
meteor-base            1.0.1  Packages that every Meteor app needs
mobile-experience      1.0.1  Packages for a great mobile user experience
mongo                  1.1.3  Adaptor for using MongoDB and Minimongo ov...
service-configuration  1.0.5  Manage the configuration for third-party s...
session                1.1.1  Session variable
standard-minifiers     1.0.2  Standard minifiers used with Meteor apps b...
tracker                1.0.9  Dependency tracker to allow reactive callb...**

But nothing works. Can you post any working example of loginWithFacebook  ?

**Comment by Urigo** [comment]
@neosekar let's do the opposite, can you please provide an non working example I can look at?
in a separate repo.
Thanks

**Comment by neosekar** [comment]
Here i attached the repository url  [](https://github.com/neosekar/meteorIonic2).

**Comment by neosekar** [comment]
Hey, anyone have the working example of loginwithfacebook(); pls post it..

**Comment by neosekar** [comment]
Hey, loginwithfacebook();  still not working..

**Comment by Urigo** [comment]
@neosekar there's a need to publish accounts-facebook in the same way that @idanwe as done with accounts-password here:
https://github.com/idanwe/accounts-base-client-side
https://github.com/idanwe/accounts-password-client-side

@neosekar do you want to try to publish this one yourself?  we can help

**Comment by idanwe** [comment]
@neosekar take a look at https://github.com/idanwe/accounts-password-client-side/issues/2#issuecomment-162036663

**Comment by asafper** [comment]
Hi,
I'm also getting this exception did any one resolve this ?
