### ISSUE TITLE
An issue in angular2 tutorial step3

### ISSUE THREAD

**Issue by dai-shi** [Urigo/angular-meteor#806]
http://angular-meteor.com/tutorials/angular2/3-way-data-binding

The example does not work until we add the `main.ts` file because the server side collection is not loaded, probably.

**Comment by barbatus** [comment]
I guess the example means downloaded zip archive?
If yes then each link at the top point to the beginning of the current state, so doesn't contain code below.
If you want complete code go to the next step and download.

**Comment by dai-shi** [comment]
No, I meant the tutorial itself. Sorry for the confusion.

I went through the tutorial carefully from the beginning without downloading the archive,
and at step 3 it didn't work as explained, specifically when inserting data from the console.

Has anyone experienced this before?

**Comment by barbatus** [comment]
Ok, now I see. You are saying that it didn't work at Inserting Parties from the Console.
Yeah, i guess paragraph says to create main.ts and import collection should go before.

**Comment by dai-shi** [comment]
Yeah, thanks for helping the clarification. At first, I tried to "improve the doc", and found out that it was not trivial. I would like someone to take part in it.

**Comment by aaronksaunders** [comment]
I still cannot get this code to work... even after downloading the code from the tutorial page... any guidance would be appreciated

**Comment by Urigo** [comment]
I've just deployed @barbatus recent changes, please let me know if it's working for you now

**Comment by dai-shi** [comment]
Cool. Thanks! @barbatus @Urigo
