### ISSUE TITLE
controller as vm syntax

### ISSUE THREAD

**Issue by paulvanbladel** [Urigo/angular-meteor#81]
Is the controller as vm syntax possible with angular-meteor?
thanks
paul.

**Comment by Urigo** [comment]
@paulvanbladel @thaiat just released the new version and there is no need to send the scope anymore.
Please check again and see if the controller as vm is working now:
https://github.com/Urigo/angular-meteor/releases/tag/0.6.0-alpha

**Comment by Urigo** [comment]
Just checked it on the tutorial and changed everything to the controller as vm syntax and everything worked great!
Please enjoy the new version (soon the beta is coming) and please re-open if there are more issues.
