### ISSUE TITLE
Angular2 Documentation Errata - as of angular@2.0.0-alpha.45

### ISSUE THREAD

**Issue by evanplaice** [Urigo/angular-meteor#811]
**Angular2 step .05** 
 - `routerInjectables` has been changed to `ROUTER_PROVIDERS`
 - `routerDirectives` has been changed to `ROUTER_DIRECTIVES`
 - `bind` has been changed to `provide`
 - `@inject` is no longer used. The new `RouteData` and `RouteParams` were introduced
 - `HTML5LocationStrategy` has been changed to `PathLocationStrategy`

**Angular2 step .06**

- `@inject` is no longer used. The new `RouteData` and `RouteParams` were introduced
- `HTML5LocationStrategy` has been changed to `PathLocationStrategy`

**Angular2 step .07**
- `@inject` is no longer used. The new `RouteData` and `RouteParams` were introduced

**Angular2 step .09**
- `routerDirectives` has been changed to `ROUTER_DIRECTIVES`

I would have forked and updated the documents myself but couldn't figure out where the code samples are being injected from.

*Sources:*

 - `ROUTER_PROVIDERS` - [angular@2.0.0-alpha.41/CHANGELOG.md][1]
 - `ROUTER_DIRECTIVES` - [angular@2.0.0-alpha.36/ccfadb9b474][2]
 - `provide` - [angular@2.0.0-alpha.41/CHANGELOG.md][3]
 - `RouteData`/`RouteParams` - [angular@2.0.0-alpha.45/b87da8][4]
 - `PathLocatationStrategy` - [angular@2.0.0-alpha.36/3963e0ab3][5]

[1]: https://github.com/angular/angular/blob/master/CHANGELOG.md#200-alpha41-2015-10-13
[2]: https://github.com/angular/angular/commit/ccfadb9b4747d5fd7a3c32f7a8e92b23b07f7fd0
[3]: https://github.com/angular/angular/blob/master/CHANGELOG.md#200-alpha41-2015-10-13
[4]: https://github.com/angular/angular/commit/b87da8f47c340e0539213709c4a3407db6e12a45
[5]: https://github.com/angular/angular/commit/3963e0ab3902af89450d8e90a340086f18504800

**Comment by Urigo** [comment]
Please check out the new updated tutorial with @barbatus and let me know if it's working for you

**Comment by evanplaice** [comment]
@Urigo @barbatus Did a read-through of the changes and everything looks good to me.

If I get some time, maybe I can try creating the sample app following the updated directions.

**Comment by Urigo** [comment]
great, closing
