### ISSUE TITLE
I18n Broken @ angular.meteorhub.org?

### ISSUE THREAD

**Issue by evanplaice** [Urigo/angular-meteor#812]
For some reason, the first 5 Angular1 tutorials are rendering as Chinese.

![angular-meteor-chinese1](https://cloud.githubusercontent.com/assets/303159/10869236/0f17f7bc-805e-11e5-9d2d-ec09182fd6eb.png)

![angular-meteor-chinese2](https://cloud.githubusercontent.com/assets/303159/10869235/08ffff14-805e-11e5-9083-0ee125bf72ca.png)

I doubt this has anything to do with it but here's the Chrome console output after a refresh with disabled cache:

```
GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILED
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
GET chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js net::ERR_FAILED
```

**Comment by Urigo** [comment]
haha, does anybody else gets that?

**Comment by evanplaice** [comment]
It's really bizarre. If I use Google Translate it's perfectly valid English.

It reminds me of:
http://www.theonion.com/article/china-unable-recruit-hackers-fast-enough-keep-vuln-51719

**Comment by evanplaice** [comment]
Wait, is angular.meteorhub.org associated with angular-meteor.com? If not, I think I stumble on a half-assed clone of the official site.

Looks like it came from: https://github.com/MeteorHub/meteor-doc-cn

**Comment by Urigo** [comment]
ok, closing here, if you want you can reopen there
