### ISSUE TITLE
Double curly braces never rendered, ng-bind always working 

### ISSUE THREAD

**Issue by jargot** [Urigo/angular-meteor#813]
I'm actually not sure if this is a straight up Angular problem or an Angular-Meteor one, but extensive Google-ing didn't help me at all, so I'm assuming it might be caused by this combination...

My problem is simple:

I want to use Angular expression rendering to generate URLs within an ng-repeat like so:

    <li ng-repeat="category in myCategories" class="nav-header">
        <a ng-href="/categories/{{category.slugged_name}}">
            <span ng-bind="category.slugged_name"></span>
        </a>
    </li>

The ng-bind gets rendered perfectly, but the url gets rendered as "localhost:3000/categories/".
I unfortunately cannot use ng-bind in the anchor tag, so I need to get the curly braces working...

I get the data for myCategories in my controller, like so:

    $scope.myCategories = $scope.$meteorCollection(Categories, true).subscribe('myCategories');

I should also mention that I already had encountered the problem with the double curly braces not working in a few other places in the project, but I circumvented it using the ng-bind approach when it was possible. 

Any ideas ?

**Comment by Urigo** [comment]
Are you using an `html` file instead of `.ng.html` file by chance?

**Comment by jargot** [comment]
Yup. That nailed it.

Thank you very much :)
