### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated + WARNING: Tried to load angular more than once

### ISSUE THREAD

**Issue by scrapcupcake** [Urigo/angular-meteor#818]
Tried to create a super simple application but getting this issue. I've uploaded a repo here, which exhibits the issue:
https://github.com/scrapcupcake/angular-meteor-routing-issue

**Comment by vimes1984** [comment]
I just ran into this same issue: 
you need to remove the .ng from the html file and the refernce to it then empyt your template cache :D

**Comment by Urigo** [comment]
You should remove `blaze-html-templates` and `ecmascript` and change all `.ng.html` to `html`.
or instead, if you want to keep using `.ng.html` and keep using Blaze as the HTML parser, just replace the `angular` package with the `angular-with-blaze` package.
