### ISSUE TITLE
Step 8 not working

### ISSUE THREAD

**Issue by aceymer** [Urigo/angular-meteor#822]
I have followed your guide step by step and its awesome.
But at step 8 I do not get a dropdown on the login.
I cannot login/create account or anything.
I copied all your code and ran it but its still not working. I am not getting errors or anything.

Package list:
accounts-password             1.1.4  Password support for accounts
accounts-ui                   1.1.6  Simple templates to add login widgets to an app
angular                       1.0.4  Everything you need to use AngularJS in your Meteor app
angularui:angular-ui-router   0.2.15  angular-ui-router (official): Flexible routing with...
autopublish                   1.0.4  (For prototyping only) Publish the entire database t...
blaze-html-templates          1.0.1  Compile HTML templates into reactive UI with Meteor ...
ecmascript                    0.1.6  Compiler plugin that supports ES2015+ in all .js files
es5-shim                      4.1.14  Shims and polyfills to improve ECMAScript 5 support
jquery                        1.11.4  Manipulate the DOM using CSS selectors
meteor-base                   1.0.1  Packages that every Meteor app needs
mobile-experience             1.0.1  Packages for a great mobile user experience
mongo                         1.1.3  Adaptor for using MongoDB and Minimongo over DDP
session                       1.1.1  Session variable
standard-minifiers            1.0.2  Standard minifiers used with Meteor apps by default.
tracker                       1.0.9  Dependency tracker to allow reactive callbacks
urigo:angular-blaze-template  0.1.0  Include Blaze templates in your angular-meteor appli...

Please let me know if you need more information.

**Comment by Urigo** [comment]
there is a problem with the new `urigo:angular-blaze-template` version, can you try downgrading it to version `0.0.1` ?

**Comment by aceymer** [comment]
Yes.. Will try it first thing tomorrow..

**Comment by aceymer** [comment]
Yeah version 0.0.1 seems to work! Will test some more!

**Comment by dotansimha** [comment]
@aceymer you are right, 0.1.0 had a small bug that unattach the jquery element from it's data.
Fixed in 0.1.1, https://github.com/Urigo/angular-blaze-template/pull/3

**Comment by Urigo** [comment]
I've released the new version, @aceymer let me know if the problem persists.
