### ISSUE TITLE
Failed to instantiate module angular-meteor

### ISSUE THREAD

**Issue by CoreTea-Solution** [Urigo/angular-meteor#829]
I was trying to follow the tutorial and build app using ionic cli, but it does not work for me. I'm getting following errors:

```
angular-meteor.bundle.js:1142
Uncaught TypeError: Cannot read property 'ECMAScript' of undefined

ionic.bundle.js:13212 
Uncaught Error: [$injector:modulerr] Failed to instantiate module whatsapp due to:
Error: [$injector:modulerr] Failed to instantiate module angular-meteor due to:
Error: [$injector:nomod] Module 'angular-meteor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

I guess the 2nd error is result of 1st one, but I cannot figure out how to include ecmascript into the project

**Comment by Urigo** [comment]
yes we need to send a new bower version with those dependencies, @idanwe is already on it

**Comment by CoreTea-Solution** [comment]
Ok thanks, i'm waiting for a new bower, i have look his repo but nonew update about that...

Thanks....

**Comment by triniwiz** [comment]
I'm getting the same error :( just started using meteor

**Comment by rosswaycaster** [comment]
Any update on this?

**Comment by rosswaycaster** [comment]
Until this is fixed, I have a temporary solution at https://gist.github.com/rosswaycaster/9585844e03f99625507e

**Comment by idanwe** [comment]
@rosswaycaster I work on a solution will be available soon when @Urigo will release 1.2

**Comment by Urigo** [comment]
angular 1.2.0 has been released, let me know of that fixed your problem. thanks @idanwe

**Comment by triniwiz** [comment]
works great on my end :)

**Comment by CoreTea-Solution** [comment]
thanks, works great bro... ;)

but why data not save on server meteor,

i have create server meteor outside ionic project folder, works great but data not saved to my meteor server... :(

**Comment by Urigo** [comment]
@CoreTea-Solution can you share a repo with your problem?

**Comment by CoreTea-Solution** [comment]
I did not change anything from your repository, I just run and build android application, before I build, I change the ip and port that I use for the file meteor meteor-runtime.confige.js


```
__meteor_runtime_config__ = {};
__meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL = 'http://10.192.0.92:3000';
```

this my local ip address

when I want to start a new chat with the user who previously had done a chat, a new chat that does not fit into the same chat room but create a new chat room with the same user name,
I attach a screen shoot.
then I want to check the data chat, user and message mongodb database on the server meteor,
why no data is only stored in local storage (each device) is not the meteor server (the main server)

```
https://goo.gl/photos/yBfRK5PWctLHE5PG7
```
Thanks

**Comment by trajano** [comment]
Seems to have failed for me on angular 1.3.9 + Meteor 1.3 just checking if I may be missing something  else.
