### ISSUE TITLE
autopublish is not working correctly with angular@1.0.5

### ISSUE THREAD

**Issue by wapacz** [Urigo/angular-meteor#830]
I was going through the tutorial: http://angular-meteor.com/tutorials/angular1/folder-structure
And noticed problem with Mongo and Collection - after adding document to database directly (CLI, RoboMongo) or with web app all document data are cleared - only _id lefts.

Somehow I was able to add angular@1.0.5 with: 'meteor add angular' command.
I've found that when I downgrade to angular to 1.0.4 version it start working again, so there must be some bug with it in 1.0.5.

**Comment by Urigo** [comment]
can you please try updating to `1.0.6`?

**Comment by wapacz** [comment]
thanks, it's working fine with 1.0.6.
what causing problem?

**Comment by Urigo** [comment]
I've added release notes to show the changes
