### ISSUE TITLE
Object $hashKey

### ISSUE THREAD

**Issue by ThomsC** [Urigo/angular-meteor#831]
Hi,

I think I found a bug quite same as #299, if the object has an Object instead of an array this time it will give this error.

Exception while invoking method 'OperationAdd' Error: key $$hashKey must not start with '$'.

**Comment by Urigo** [comment]
can you please share you code in a repo?

**Comment by Urigo** [comment]
With the new [Angular Meteor 1.3](http://info.meteor.com/blog/angular-meteor-1.3) we don't use hashkeys anymore.
Please try to new `helpers` syntax and let me know what you think about it

**Comment by MilosStanic** [comment]
I just had this error with v1.3
```
details: undefined
error: 409
errorType: "Meteor.Error"
message: "MongoError: The dollar ($) prefixed field '$$hashKey' in 'profile.avatars.0.$$hashKey' is not valid for storage. [409]"
reason: "MongoError: The dollar ($) prefixed field '$$hashKey' in 'profile.avatars.0.$$hashKey' is not valid for storage."
stack: "Error: MongoError: The dollar ($) prefixed field '$$hashKey' in 'profile.avatars.0.$$hashKey' is not valid for storage. [409]
    at _.extend._livedata_result (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:4625:23)
    at onMessage (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:3365:12)
    at http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:2734:11
    at Array.forEach (native)↵    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?46eaedbdeb6e71c82af1b16f51c7da4127d6f285:149:11)
    at self.socket.onmessage (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:2733:11)
    at REventTarget.dispatchEvent (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:173:22)
    at SockJS._dispatchMessage (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:1158:10)
    at SockJS._didMessage (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:1216:18)
    at WebSocket.that.ws.onmessage (http://localhost:3000/packages/ddp-client.js?250b63e6c919c5383a0511ee4efbf42bb70a650f:1363:17)"
```
Here's how I make it happen: 

```javascript
this.saveUserData = function (){
		Meteor.users.update(
			{_id: this.thisUser._id },
			{ $set: { profile: this.thisUser.profile }},
			(error) => {
				if (error) {
					$mdToast.show(
						$mdToast.simple()
							.textContent('There was an error saving profile data!')
							.position('bottom right')
							.hideDelay(3000)
					);
					console.log('error saving profile data', error);
				} else {
					$mdToast.show(
						$mdToast.simple()
							.textContent('User profile successfully saved.')
							.position('bottom right')
							.hideDelay(3000)
					);
				}
			}
		);
	};	
```

Interestingly, when I press save again (i.e. call this method again), immediately after calling it the first time, it saves without error.

**Comment by ThomsC** [comment]
I didn't have $$hashKey anymore. But when I use angular material I got $$mdSelectId but maybe there is nothing to do with angular-meteor.
I juste remove it by doing : delete object.$$mdSelectId;

**Comment by bartvanremortele** [comment]
I just ran into this issue on 1.3.5 and by using `track by $index` in my ng-repeat I can work around this.

**Comment by Hadarg1** [comment]
I just ran into the same problem
I'm using Angular Meteor 1.3
I'm trying to write an object to MongoDB which one of it's propreties is an array.
Doing a console.log just before the insert, I can see that a $$hashkey field was added as a last field to each entry in the array.
I manage to solve the problem with angular.copy
I don't like this solution and I'm looking for a better way to solve it
The insert code:

  vm.addCampaign = () => {
        console.log(vm.newCampaign)**;//Only for testing purposes**
        vm.newCampaign.skills= angular.copy(vm.newCampaign.skills);**//The problem solution**
        Campaigns.insert(vm.newCampaign);**//the MongoDB meteor insert**
        vm.newCampaign = {};
        vm.newCampaign.skills = [
            {type:'-- Select Skill --',weight:0,audition:'--Select Audition --'}
            ];
        };

**Comment by devntd** [comment]
Ok, thanks for clarifying! 
:+1:
