### ISSUE TITLE
How to add other Angular package to work with Meteor?

### ISSUE THREAD

**Issue by johnsonqu** [Urigo/angular-meteor#84]
It's great tool to combine Meteor and Angular together. But I'm wondering how to add other Angular package workting with Angular-meteor? such as https://github.com/danielstern/ngAudio

**Comment by Urigo** [comment]
@johnsonqu now you can simply add them with bower, I've added a description to the readme file:

https://github.com/Urigo/angular-meteor/commit/24e69b73bd4026089a38cace88dbb554d86d80bf

**Comment by johnsonqu** [comment]
Thanks. Great work.
