### ISSUE TITLE
Feature: Progressive saving (such as Angular Breeze)

### ISSUE THREAD

**Issue by cyrus-za** [Urigo/angular-meteor#840]
If you check out this video (https://youtu.be/JLij19xbefI) at ng-conf 2014 where John Papa talks about Angular-Breeze and progressive saving, you will see why this is a great feature to add to the angular-meteor stack. Breeze traditionally works with C# .NET entities and has plugins for visual studio to directly talk between the server and the client, as opposed to using angular's $http or $resource directly. This is a similar approach to angular-meteor's $meteor handling the DDP communication to the server for you, but it does not have the feature of WIP (work in progress) or progressive saving. 

Just including the breeze package into this will obviously not work out of the box, but maybe the $meteor service can be extended. Right now the collections are reactive by default, and adding a 2nd parameter of `false` in there makes it non-reactive and lets you save it like a traditional angular form, as opposed to 3-way binding (or like @Urigo says, Full stack reactivity). 

What if we have a form that needs to save as a whole and will be invalid if it saves reactively? Stopping the Full stack reactivity will work, but what if the user closes the browser or wants to navigate to another view quickly to copy paste some value or to read something before getting back to the form. Would it not be great if the view could save the work in progress to localstorage (or some storage into mini mongo which uses html5 localstorage underneath)?

**Comment by Urigo** [comment]
Interesting.
I wonder if [GroundDB](https://github.com/GroundMeteor/db) can help you create something like that?

**Comment by quanganh206** [comment]
A day with it. I think that would help.

https://github.com/quanganh206/anguar-meteor-offline-contacts

**Comment by Urigo** [comment]
I also think it shouldn't be related to Angular Meteor alone but as a Meteor feature.
Definitely with the new [angular Meteor 1.3 syntax](http://info.meteor.com/blog/angular-meteor-1.3)

**Comment by cyrus-za** [comment]
I agree with you, but it is mainly a UI component. Yes, there is a lot of services to bind the UI and bakcend in breeze, but the actual progressive saving is mainly on the UI, with the backend just fovusing on storing the progressive saving, either in session or in the DB. 

Although Blaze could have some solution for it, I don't think it would ever be a package that just works for both angular and blaze without any tweaks. So unless we have the option to include blaze templates, like in previous versions, this will need to be a package specific to angular meteor, with part of it maybe split to meteor in general and a angular specific package for the UI which can later be written for blaze as well.
