### ISSUE TITLE
Tutorial  - all in one page

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#846]
Would it be posible to add an extra link on the tutorial page which would show all the 23 pages of the tutorial in one mega page - it is just that I find it a pain in a neck when I am trying to locate some details and keep jumpng  back and forward  between pages. If all the pages were combined into one I could then use the find facitily to jump to the required section.

**Comment by Urigo** [comment]
That's a nice idea, maybe you can pull request the site to create something like that?
shouldn't be too hard

**Comment by JohnAReid** [comment]
I have no idea what a pull request is.

**Comment by Urigo** [comment]
It's a very important concept - it let's you help the community and suggest your changes to code. it's the heart of open source:
https://help.github.com/articles/using-pull-requests/

**Comment by wsjwong** [comment]
Will try on this today.

**Comment by Urigo** [comment]
codemill$50

**Comment by Urigo** [comment]
@andela-osogunle has been assigned to this task.

**Comment by mariohmol** [comment]
Hi there.. where is the repo for tutorial?

**Comment by Tallyb** [comment]
docs: https://github.com/Urigo/angular-meteor-docs
socially repo: https://github.com/Urigo/meteor-angular2.0-socially

**Comment by mariohmol** [comment]
i couldnt find a repo for this page.. http://www.angular-meteor.com/tutorials/socially/angular2/bind-one-object

is that on github?

**Comment by Tallyb** [comment]
see my links above

**Comment by Urigo** [comment]
will be part of the next major version of https://github.com/Urigo/tortilla
