### ISSUE TITLE
Unable to load Angular templates in routes.

### ISSUE THREAD

**Issue by vimes1984** [Urigo/angular-meteor#849]
Ok I've just created a new meteor 1.2 app. 
And I'm using a set up that worked before.. 
I've included my routes and templates like so : 
```

MainApp.config(['$urlRouterProvider', '$stateProvider', '$locationProvider',
  function($urlRouterProvider, $stateProvider, $locationProvider){

    $locationProvider.html5Mode(true);
    $urlRouterProvider.otherwise('/');

    $stateProvider
    .state('home', {
      url: '/',
      templateUrl: 'app/client/templates/angular/template.home.ng.html', /*Doesn't work */
      templateUrl: 'app/client/templates/angular/template.home.ng', /*Doesn't work */
      templateUrl: '/app/client/templates/angular/home.ng.html', /*clutching at straws  */
      controller: 'HomeCtrl'
    })
    .state('contact', {
      url: '/contact',
      templateUrl: '/client/templates/angular/contact.ng.html',
      controller: 'ContactCtrl'
    });

}]);
```
But Iv'e noticed meteor is now loading my templates from /app and it's now ripping out the .html  and repfxing it with template. 
this is a comparison between a older version and a newer version : 
```
<script type="text/javascript" src="/client/templates/angular/home.ng.html.js?53594b2ab24052babc7795483fa7354b49b024ce"></script>
<script type="text/javascript" src="/app/client/templates/angular/template.home.ng.js?9463703b83741c520ab4bb93d7049e7fad3ad783"></script>
```
I can't seem to get the template to load in the route.... 

### Packages: 
```

# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mongo                   # The database Meteor supports right now
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.

autopublish             # Publish all data to the clients (for prototyping)
insecure                # Allow all DB writes from clients (for prototyping)
meteorhacks:npm


npm-container
usefulio:sync-methods

angular
matthew:foundation5-sass
fortawesome:fontawesome
angularui:angular-ui-router
urigo:angular-blaze-template
urigo:angular-ui-router
```
I've allready had to remove: 
#### mobile-experience
due to the conflicts by babel I think... 
If someone can point me in the right direction I'd be happy to patch what i can. 
Chris

**Comment by blntylmn** [comment]
same here just updated my project with meteor update command and getting this errors :

 While determining active plugins:
   error: conflict: two packages included in the app (pbastowski:angular-babel and ecmascript) are both trying to handle *.js
   error: conflict: two packages included in the app (templating and angular-templates) are both trying to handle *.html

**Comment by vimes1984** [comment]
yeah I got that aswell had to remove blaze html templates to get around it  :D

**Comment by blntylmn** [comment]
if I remove ecmascript and blaze-html-templates everything works

**Comment by vimes1984** [comment]
yup same as me well bar the html template issue...

**Comment by blntylmn** [comment]
blaze-template not working after update. Do you have this issue ?

**Comment by vimes1984** [comment]
we dont' need it : https://github.com/Urigo/angular-meteor/releases

**Comment by vimes1984** [comment]
Ok I think my template issue was from a template cache :dancer:

**Comment by vimes1984** [comment]
I have just run into the blaze-template issue .... It's not rendering my templates..

**Comment by Urigo** [comment]
no need for `.ng.html` anymore, just regular `.html` will do the work

**Comment by blntylmn** [comment]
But we have to use blaze-template for meteor native templates ?

**Comment by vimes1984** [comment]
yup just read the release and figured it out :D 
I think both me and @bintylmn are running into the same <blaze-template > issue which doesn't seem to want to work...

**Comment by blntylmn** [comment]
It gives me an error starting with these lines :
ReferenceError: Template is not defined
    at link (http://localhost:3000/packages/urigo_angular-blaze-template.js?73310390455b784def963671fb677b5eaa30ee4d:34:11)
    at invokeLinkFn

**Comment by vimes1984** [comment]
I'm gettting: 
Errors prevented startup:

While determining active plugins:
error: conflict: two packages included in the app (angular-templates and templating) are both trying to handle *.html

While determining active plugins:
error: conflict: two packages included in the app (angular-templates and templating) are both trying to handle *.html

Your application has errors. Waiting for file change.

when including blaze-html-templates  in my packages which is kind of needed since a lot of other packages expect it to be there.

**Comment by Urigo** [comment]
what packages use `templating` ?

**Comment by vimes1984** [comment]
blaze-html-templates 
which comes bundled with the latest release of meteor when you run meteor create.

**Comment by vimes1984** [comment]
and: 
https://github.com/Urigo/angular-meteor/blob/master/packages/angular-templates/package.js

**Comment by Urigo** [comment]
yes, with the new version you should remove both `blaze-html-templates ` and `ecmascript` : http://angular-meteor.com/tutorials/angular1/bootstrapping

**Comment by vimes1984** [comment]
the problem is if I remove that my blaze templates don't work...

**Comment by Urigo** [comment]
ohh so you work with Blaze and Angular?

**Comment by Urigo** [comment]
why?

**Comment by vimes1984** [comment]
yeah I do usually it's nice to have both...

**Comment by vimes1984** [comment]
some packages I use such as matthew:foundation5-sass use blaze templates generated by the package to initiate js in the files... 
I also use Aldeed's autoforms which uses blaze templates to work aswell....

**Comment by vimes1984** [comment]
https://github.com/aldeed/meteor-autoform

**Comment by Urigo** [comment]
we can acttually take the old build process and create a package out of it (for `.ng.js` and `.ng.html`)
it means to copy the same come and include the `angular-meteor-data` package.
want to give it a shot?

**Comment by vimes1984** [comment]
I'd love to take shoot, would that mean putting .ng back on all the angular files? 
Would that allow us to use the <blaze-template name="top"></blaze-template> tag again?

**Comment by Urigo** [comment]
you need to decide which engine you want to compile `html`

**Comment by Urigo** [comment]
if you want that to be Blaze then yes, it will be exactly like previous versions

**Comment by vimes1984** [comment]
ok say I'd want to use a package like autoforms which requires blaze would I have to go down the .ng route?

**Comment by Urigo** [comment]
yes

**Comment by Urigo** [comment]
there is also this route - https://github.com/dotansimha/accounts-ui-angular  by @dotansimha 
which is interesting to make it a general one

**Comment by vimes1984** [comment]
uuuu doesn't that render the new angular meteor version a little un compatible with a lot of the other meteor packages? 
Isn't that forcing a splintering of the community the ones that use angular/meteor the ones that use blaze/meteor?

**Comment by vimes1984** [comment]
isn't dotansimha's approach what we had with < blaze-templates >

**Comment by Urigo** [comment]
it's a bit different because it's rendering Blaze templates without adding the dependency on `templating`

**Comment by vimes1984** [comment]
I don't mind building a package using the old build process to use .ng and .html so people can choose. 
Ahhhh but it uses blaze-html-templates which does depend on templating: 
https://github.com/dotansimha/accounts-ui-angular/blob/master/package.js

**Comment by Urigo** [comment]
I think it doesn't add the build process to it, can you test it?

**Comment by vimes1984** [comment]
sure

**Comment by vimes1984** [comment]
that doesn't add the templating to the buidl propcess...

**Comment by vimes1984** [comment]
I assume it's becuase it add's blaze-html-templates on the client only is that right?

**Comment by blntylmn** [comment]
Ok I just renamed all file extensions to .ng.html to .html.
Over 600 files (dont do this me again :)
meteor update
meteor reset
everything works but blaze-template. it still says :

ReferenceError: Template is not defined
    at link (http://localhost:3000/packages/urigo_angular-blaze-template.js?73310390455b784def963671fb677b5eaa30ee4d:34:11)
    at invokeLinkFn (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:8812:9)
    at nodeLinkFn (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:8312:11)
    at compositeLinkFn (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:7703:13)
    at compositeLinkFn (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:7707:13)
    at compositeLinkFn (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:7707:13)
    at publicLinkFn (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:7578:30)
    at link (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:24407:38)
    at invokeLinkFn (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:8812:9)
    at nodeLinkFn (http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:8312:11) <blaze-template name="ReactiveFullcalendar">

**Comment by vimes1984** [comment]
See the discussion above blaze-template is no longer supported in angular-meteor...

**Comment by blntylmn** [comment]
So we have to leave the community packages advantage if we the decide go further :(

**Comment by vimes1984** [comment]
not to sure what you mean..

**Comment by blntylmn** [comment]
I mean with blaze-template ---> urigo:angular-blaze-template directive not native blaze template of meteor

**Comment by vimes1984** [comment]
from what I've been reading and after talking to Urigo it seems like there has been a decision to move away from blaze so it's now blaze OR angular's templating (@urigo please correct me if I'm wrong) which renders quite a few atmosphere packages useless... 
urigo:angular-blaze-template requires blaze to be installed something that the latest 1.2 release of meteor angular doesn't support...

**Comment by blntylmn** [comment]
Ok if I not misunderstand we need to make our own packages for angular meteor if we need some third party packages which is renders with blaze.  So if I want to use fullcalendar what is the correct way ?

**Comment by Urigo** [comment]
I will make sure to add a package that support the old build process very soon.
In the meantime, you can keep using `1.0.7`.
that way you can choose what way you want to use.

About choosing, if you need Blaze templates just because of login buttons, you can use `dotansimha:accounts-ui-angular` instead - https://github.com/dotansimha/accounts-ui-angular

**Comment by vimes1984** [comment]
for anybody finding this uirgo is suggesting to do this: 
meteor remove angular 
meteor add angular@=1.07 
then changing the files back to ng.html/ng.js

**Comment by vimes1984** [comment]
@urigo I'll take a crack at the package to support the old build version tomorrow if thats ok with you?

**Comment by Urigo** [comment]
sounds good

**Comment by Urigo** [comment]
thank you for that

**Comment by Urigo** [comment]
OK, I've released `angular-with-blaze@1.2.0` that replace `angular` in case you want to use the old build process like before and use blaze templates like before.
I've updated the `<blaze-template>` example so you can see (just updated the packages, the code stayed the same:
https://github.com/Urigo/angular-meteor/tree/master/examples/blaze-template

Thanks @dotansimha for the help

**Comment by vimes1984** [comment]
christ that was quick....

**Comment by vimes1984** [comment]
didn't have a chance to take a a crack at iit maybe next time :D

**Comment by Acostan** [comment]
Thanks for this.... I've been stuck trying to get a template to render from a package.  Whats the correct way to reference the ng.html file in the package based on this is my file structure.
```
/app
        /.meteor
        /client
                 /routes.ng.js
       /packages (symlink to package folder)

/packages
       /meteor-package
                /views
                         -index.ng.html
```

Here's the contents to routes.ng.js:
```
.state('index', {
            url: '/index',
            templateUrl: '/packages/meteor-package/views/index.ng.html',
```
     
Currently, its not finding this path '/packages/meteor-package/views/index.ng.html', which yields this error:

"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

Error: [ng:btstrpd] App Already Bootstrapped with this Element 'document'
"

**Comment by Urigo** [comment]
what packages and versions are you using?

**Comment by Acostan** [comment]
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code
angular-with-blaze@1.2.0
angularui:angular-ui-router
urigo:angular-blaze-template
less
urigo:angular-ui-router

**Comment by Urigo** [comment]
ohh now I see what you are trying to do.
First, you don't need to include the packages in your client folder as well.
second, the paths links are like so: 'author_packagename_path/to/file.js'  (in the old build process which you are using because of `angular-with-data`
Here is a related issue for more information: https://github.com/Urigo/angular-meteor/issues/752
it can be nice if someone can pull request the compiler to do the same: https://github.com/Urigo/angular-meteor/tree/master/packages/angular-blaze-templates-compiler/plugin

Please make sure that what I'm saying is actually true, I haven't tested the old build in a while

**Comment by Acostan** [comment]
Hey @Urigo I've posted the project files here:

[https://github.com/Acostan/test-angular-meteor] (https://github.com/Acostan/test-angular-meteor)

I tried to change the path to 'test_package_packages/test-package/lib/index.ng.html', but no success. I'm sure I'm doing something wrong. Please advise. Thanks in advance!

**Comment by lance-anderson** [comment]
> OK, I've released angular-with-blaze@1.2.0 that replace angular in case you want to use the old build process like before and use blaze templates like before.
I've updated the <blaze-template> example so you can see (just updated the packages, the code stayed the same:
https://github.com/Urigo/angular-meteor/tree/master/examples/blaze-template

@Urigo THANK YOU. This is wonderful. It seems like the crutch I need to transition from Blaze to Angular (wanting to leverage angular-ionic... love the WhatsApp demo!).

I'm wondering if there are any drawbacks or gotchas that I should be aware of before committing to ```angular-with-blaze``` over ```angular``` for a production project.

**Comment by dotansimha** [comment]
Hi @vimes1984 ,
Just answer a question related to this, please read my comment here:
https://forums.meteor.com/t/meteor-angular-tutorial-step-9-2-adding-user-accounts/10260/16?u=dotansimha

**Comment by Acostan** [comment]
I got it working finally using this path:
templateUrl: '/packages/test_package/lib/index.ng.html'
Apparently, "-" dashes get replaces with "_" underscores!

**Comment by Urigo** [comment]
@Acostan can you have a look at the docs and pull request the best place to add documentation about that?

**Comment by Acostan** [comment]
Sure @Urigo what branch should I compare it to? Are you referring to these docs (https://github.com/Urigo/angular-meteor)?

**Comment by Urigo** [comment]
Yes, on the `docs` directory there is the source code for the angular-meteor.com site

**Comment by marcianosr** [comment]
Hmm still could not get it to work... I installed `angular-with-blaze@1.2.0` and tried the example from the angular docs, but still no succes. Getting the error `Uncaught ReferenceError: Template is not defined`. Running the newest meteo version. Have I missed something?

**Comment by gentunian** [comment]
Having the same issue, `Template is not defined`

**Comment by gentunian** [comment]
having the same issue, `Template is not defined`

```
$ meteor list | grep blaze
angular-blaze-templates-compiler  0.0.1  Compile angular templates into the t...
angular-with-blaze                1.2.1  Everything you need to use both Angu...
urigo:angular-blaze-template      0.2.0  Include Blaze templates in your angu...
```

**Comment by lance-anderson** [comment]
@gentunian @marcianosr I had a bit of trouble resolving that issue myself. I found the [blaze-template](https://github.com/Urigo/angular-meteor/tree/master/examples/blaze-template) example in this repo _very_ helpful. I recommend cloning this repo, navigating to the ```examples/blaze-template``` folder and run ```meteor run```. It's likely a working example of what you're looking for. From there you can tweak the  example as needed to replicate the setup you're going for.

**Comment by gentunian** [comment]
@lance-anderson thanks for the reply and hints. Anyway, shouldn't the object `Template` be availble at global scope despite that all html files?

**Comment by jacobdr** [comment]
I also had some difficulties here, but by installing all of the below
packages I got things to work well together:


   - angular-with-blaze
   - blaze-html-templates
   - urigo:angular-blaze-template

**Comment by gentunian** [comment]
@jacobdr  so you don't have angular installed and your are using blaze for parsing .html files.

`blaze-html-templates` (because of `templating` conflicts with `angular` as far as I know.

**Comment by gentunian** [comment]
Ok to avoid confusion and to be helpful to anyone that was as confused as I was.

My confusion: have `angular`, `angular-with-blaze` and `urigo:angular-blaze-templates` installed and `blaze-html-template` removed (as the first post)

It turns out that I needed to remove `angular` and have `urigo:angular-blaze-template`, `blaze-html-templates` and `angular-with-blaze` installed as @jacobdr says.

After that, my angular templates (`.ng.html` files) and code (just `.js` files) are working ok.

**Comment by gentunian** [comment]
Interesting... maybe this is not the place but I will share what leads me to use blaze templates with angular.

Performance. Using blaze `{{#each item}}` to populated an `ion-list` is way faster that using `ng-repeat="item in collection"`. I guess that is because the binding between angular and `$meteorCollection`.

When I said way faster I meant: There's no apparent difference while using a web browser on your PC. But using a mobile phone (Moto E 2nd Gen android 5 and Samsung Galaxy Grand Prime android 4) the low performance is indeed notorious. Two seconds against one, that is measured repeated times just with a cronometer :)

**Comment by jacobdr** [comment]
Interesting to hear. Are you emulating or is that a native build running on
device?

@urigo do we have any benchmarks of angular vs angular2 vs blaze
performance?

**Comment by gentunian** [comment]
In the web app only. Accesing the web app vía mobile browser (e.g. opening chrome to `http://myip:3000`)

I've tried to reproduce this in a simple repo: https://github.com/gentunian/gevo-angular which is basically the tool I'm just playing with.

I used 180 items in a collection to note the difference in the browser from PC. It's notorious at sight with that quantity. The quantity is just for testing, in real life this should be loaded on demand.

**Comment by gentunian** [comment]
I would like to hear about the performance too. Are those test wrong in their essence? Has anyone tried that using a smartphone? How can I measure the real time spent, at least in the PC browser?

Cheers.

**Comment by carlosbaraza** [comment]
I am facing the issue that inside a package and using `angular-with-blaze` and `.ng.js` files, the code is not transpiled using Babel. I have tried adding `ecmascript` package, but it does not seem to work. If I remove the `.ng`, then `ng-annotate` does not work properly.

Anyone faced a similar issue?

**Comment by carlosbaraza** [comment]
I am doing some tests and it seems that even just using `angular` without anything relating to blaze, it still does not transpile without `ecmascript`. With `ecmascript` it does transpile but the ng-annotate does not work.

**Comment by carlosbaraza** [comment]
Ok, my fault, after installing the latest version of `angular`, both transpiling and ng-annotate work. However, now I am in the same situation than people were commenting before. If I want to use one of the multiple Meteor packages using Blaze, I can not do so without porting them.

In my case, one of the packages I am using with Blaze is: https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/

**Comment by carlosbaraza** [comment]
Just in case this would be useful for someone, I have created an Angular wrapper without the need for Blaze of `ian:accounts-ui-bootstrap-3`. https://github.com/carlosbaraza/accounts-ui-bootstrap-3-angular

**Comment by jacobdr** [comment]
Don't you use angular with blaze in your package.json dependencies? And I see calls to blaze and spaceship in source, which I'm not fully familiar with, but don't feel angular "native". 




So pleased to have someone finally release a package like yours! But am curious to hear more about its implementation... Learning from its development could inform development of material design wrapper, and other ui toolkit styling packages. 



—

**Comment by carlosbaraza** [comment]
No, I don't use `angular-with-blaze`. The idea is to use Blaze templates within the package to do the rendering and then link the angular scope to the rendered DOM. This way in the project/package importing the package, it is not required to have blaze-html-templates and the extension html can be freed to be handled by angular-templates in the parent package.

About SpacebarsCompiler, it was an attempt to be able to set custom templates without using templating in the parent project/package. However, I changed the behavior two hours ago because it was very ugly using Session to configure the package, and now I recommend now creating a second package using templating and so be able to set up the custom templates. This make unnecessary the compilation step I set up yesterday. I detailed the how to use in the readme.

Glad to know it helps.

**Comment by Urigo** [comment]
Short note, after [1.3 release](http://info.meteor.com/blog/angular-meteor-1.3) , the blaze-template example moved here: https://github.com/Urigo/angular-meteor/tree/master/examples/1.2/blaze-template

**Comment by buitregool** [comment]
I copied/paste this code from angular 1.3 (angular-meteor.js). I used to have all my templates with '.ng.html' extension, now I renamed them to '.html' and I get the below exception for each path. I wonder if the ' if (templatesFileExtension.indexOf(fileExtension) > -1)' is right? Cheers!

```
angularMeteor.config([
  '$provide',
  function ($provide) {
    var templatesFileExtension = ['html', 'tpl', 'tmpl', 'template', 'view'];

    $provide.decorator('$templateCache', ['$delegate', function($delegate) {
      var originalGet = $delegate.get;

      $delegate.get = function(templatePath) {
        var originalResult = originalGet(templatePath);

        if (angular.isUndefined(originalResult)) {
          var fileExtension = ((templatePath.split('.') || []).pop() || '').toLowerCase();

         if (templatesFileExtension.indexOf(fileExtension) > -1) {
            throw new Error('[angular-meteor][err][404] ' + templatePath + ' - HTML template does not exists!');
          }
        }

        return originalResult;
      };

      return $delegate;
    }]);
  }
]);
```

**Comment by Urigo** [comment]
@buitregool can you share your code?

**Comment by buitregool** [comment]
Yes sure. I opened an issue #958.

**Comment by Urigo** [comment]
thanks @buitregool , waiting for your code

**Comment by dtruel** [comment]
Just my vote- I'd put blaze template support back into the regular angular-meteor package.  

I think this feature needs to be supported by default because almost everybody is going to need to use some packages that require blaze-templates.
