### ISSUE TITLE
Serverside routes with angular-ui-router

### ISSUE THREAD

**Issue by stlouisweb** [Urigo/angular-meteor#85]
Using the angular-ui-router package is it possible to create server side routes like:

```
 Router.route('/getPDF', function() {
 var doc = new PDFDocument({size: 'A4', margin: 50});
 doc.fontSize(12);
 doc.text('PDFKit is simple', 10, 30, {align: 'center', width: 200});
 this.response.writeHead(200, {
 'Content-type': 'application/pdf',
 'Content-Disposition': "attachment; filename=test.pdf"
 });
 this.response.end( doc.outputSync() );
 }, {where: 'server'});
```

Alternatively how would one create a link to download a static asset such as:

```
<a href="/public/downloadable-file.pdf">Download File</a>
```

**Comment by danielflippance** [comment]
"This is currently impossible with angular-ui-router" - Is this still the case? Is there any way to configure angular-u-router to pass on unhandled routes to the server?

**Comment by danielflippance** [comment]
I discovered that you *can* have angular-meteor on the client and IronRouter on the server at the same time with this little trick.

Add IronRouter.
On the client, add a global route for IronRouter that does nothing:

    if (Meteor.isClient) {
    	//We do not use IronRouter on the client 
    	//but we need to have this route to prevent an iron router message being added to our page
    	Router.route('(.*)', function(){
    		this.stop();
    	});
    }

On the client, now add your angular-meteor routes.

On the server, add your IronRouter routing:

    Router.route('/my/server/path', { where: 'server' }).get(...)
