### ISSUE TITLE
Meteor template on angular-meteor@1.2.0?

### ISSUE THREAD

**Issue by thuanmaster** [Urigo/angular-meteor#851]
After upgrade angular to 1.2.0 i can't use `{{> sAlert}}` in `index.html`. I tried write directive like `dotansimha:accounts-ui-angular` but `Blade is not defined`. How can i use template from package `https://github.com/juliancwirko/meteor-s-alert` in `index.html`?

**Comment by Urigo** [comment]
If you want to use Blaze templates, replace the `angular` package with the `angular-with-blaze` package:
https://github.com/Urigo/angular-meteor/issues/849#issuecomment-155218952
