### ISSUE TITLE
How to use collectionFS in a no Meteor app's frontend?

### ISSUE THREAD

**Issue by triniwiz** [Urigo/angular-meteor#852]
Trying to set up an ionic app using the ionic cli method and I noticed i can setup a regular collection in any of the js files and it would work 
```js
Beers = new Mongo.Collection('beers');
```
then from anywhere in the app use the collection 
```js
$meteor.collection(Beers);
```
If i try using collectionFS like in most of the examples
```js
Images = new FS.Collection("images", {
    stores: [
        new FS.Store.GridFS("original")
    ],
    filter: {
        allow: {
            contentTypes: ['image/*']
        }
    }
});


$scope.images = $meteor.collectionFS(Images, false);
```
I'm getting this error

FS is not defined

**Comment by Deadly0** [comment]
@triniwiz, did you install CoffectionFS package? https://atmospherejs.com/cfs/standard-packages

**Comment by triniwiz** [comment]
yes it installed on the server but i'm trying to access it from a non meteor app

**Comment by Urigo** [comment]
With the new [Angular Meteor 1.3 release](http://info.meteor.com/blog/angular-meteor-1.3), there is no need to wrap CollectionFS anymore.
So there is nothing Angular specific about that.
Please try to migrate to the new `helpers` syntax and let me know what you think

**Comment by triniwiz** [comment]
@Deadly0  everything was installed on the server but wasnt able to access FS but the 1.3 looks like it might work
