### ISSUE TITLE
Conflict: two packages included in the app (pbastowski:angular-babel    and ecmascript) 

### ISSUE THREAD

**Issue by burock** [Urigo/angular-meteor#853]
Hi,
After upgrading recently to 2.1 i now have the below error ( I also tried removing ecmascript with angular@1.2.0-rc.5 but did not help):
[[[[[ ~/Meteor/super ]]]]]                    

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While determining active plugins:
   error: conflict: two packages included in the app (pbastowski:angular-babel
   and ecmascript) are both trying to handle *.js
   
   While determining active plugins:
   error: conflict: two packages included in the app (pbastowski:angular-babel
   and ecmascript) are both trying to handle *.js
   
=> Your application has errors. Waiting for file change.

My packages list as below:
accounts-password                                     1.1.4  Password support...
accounts-ui                                           1.1.6  Simple templates...
angular                                               1.2.0  Everything you n...
angular:angular-material                              0.11.4  Google Material...
angularui:angular-google-maps                         2.2.1  angular-google-m...
angularui:angular-ui-router                           0.2.15  angular-ui-rout...
ecmascript                                            0.1.6  Compiler plugin ...
es5-shim                                              4.1.14  Shims and polyf...
insecure                                              1.0.4  (For prototyping...
jquery                                                1.11.4  Manipulate the ...
meteor-base                                           1.0.1  Packages that ev...
mobile-experience                                     1.0.1  Packages for a g...
mongo                                                 1.1.3  Adaptor for usin...
planettraining:angular-translate                      2.8.1  Angular Translate
planettraining:angular-translate-loader-static-files  2.8.1  Angular Translate
planettraining:material-design-icons                  2.0.0  Material design ...
session                                               1.1.1  Session variable
standard-minifiers                                    1.0.2  Standard minifie...
tracker                                               1.0.9  Dependency track...

Thanks and regards,
Burak

**Comment by davidfsmith** [comment]
Updated meteor yesterday and I'm getting the same issue (with an added in HTML fail for good measure)

This was after completing Step 7 - Folder Structure.

````
[[[[[ ~/Documents/Development/JavaScript/meteor-socially ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While determining active plugins:
   error: conflict: two packages included in the app (angular-templates and templating) are both trying to handle
   *.html
   error: conflict: two packages included in the app (pbastowski:angular-babel and ecmascript) are both trying to
   handle *.js

   While determining active plugins:
   error: conflict: two packages included in the app (angular-templates and templating) are both trying to handle
   *.html
   error: conflict: two packages included in the app (pbastowski:angular-babel and ecmascript) are both trying to
   handle *.js

=> Your application has errors. Waiting for file change.
````

So I ran the following which appears to have resolved the issue

````
meteor remove blaze-html-templates
meteor remove ecmascript
````

Running ````meteor list```` now outputs the following:

````
angular                      1.2.0  Everything you need to use AngularJS in your Meteor app
angularui:angular-ui-router  0.2.15  angular-ui-router (official): Flexible routing with nested views in AngularJS
autopublish                  1.0.4  (For prototyping only) Publish the entire database to all clients
es5-shim                     4.1.14  Shims and polyfills to improve ECMAScript 5 support
insecure                     1.0.4  (For prototyping only) Allow all database writes from the client
jquery                       1.11.4  Manipulate the DOM using CSS selectors
meteor-base                  1.0.1  Packages that every Meteor app needs
mobile-experience            1.0.1  Packages for a great mobile user experience
mongo                        1.1.3  Adaptor for using MongoDB and Minimongo over DDP
session                      1.1.1  Session variable
standard-minifiers           1.0.2  Standard minifiers used with Meteor apps by default.
tracker                      1.0.9  Dependency tracker to allow reactive callbacks
````

Hope this helps.

**Comment by burock** [comment]
I tried that, too.  Unfortunately then it crashes with below errors:

====
Babel compiling files:
  server/publishers.js
W20151110-10:37:35.649(2)? (STDERR)           
W20151110-10:37:35.650(2)? (STDERR) /home/burak/.meteor/packages/meteor-tool/.1.1.10.pax6pr++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151110-10:37:35.650(2)? (STDERR) 						throw(ex);
W20151110-10:37:35.650(2)? (STDERR) 						      ^
W20151110-10:37:35.650(2)? (STDERR) ReferenceError: angular is not defined
=> Exited with code: 8
================

publisher.js simply has a couple of collections like 

Meteor.publish("buildings", function (options) {
  return Buildings.find(
    {
    $and:[
        {owner: this.userId},
        {owner: {$exists: true}}
    ]
    }, options);
});

Thanks
b

**Comment by burock** [comment]
Interesting.. After a couple of hours of tries I moved my "super/lib/app.ng.js" file from there to under "super/client/app.ng.js" it started to work. 
for all that bumps into.. why, though, i dunno..
cheers,
b

**Comment by burock** [comment]
I somehow changed my app.js module initiator location from "super/lib/app.js" to under "super/client/lib/app.js" and it worked...
I dunno why though..

**Comment by doronsever** [comment]
I still have this issue even though my app.js is sitting under client/lib/app.js

**Comment by doronsever** [comment]
Ok, i had to remove and it worked

`meteor remove blaze-html-templates
meteor remove ecmascript`

But `meteor remove blaze-html-templates` is important and should not be removed... any way to workaround this?

**Comment by Urigo** [comment]
In case you want to work with `Blaze` you should use `angular-with-blaze` package instead of `angular`.
check out the example here: https://github.com/Urigo/angular-meteor/tree/master/examples/1.2/blaze-template

**Comment by abj27** [comment]
@Urigo can we use angular-with-blaze with the ionic meteor package?

**Comment by saanplus** [comment]
Hi @Urigo , this might not be the right place to ask this but i am trying to follow your tutorial http://www.angular-meteor.com/tutorials/socially/angular1/bootstrapping. But somehow `<div ng-include src="'client/main.html'"></div>` is not linking to the angular template file. But if i write the markup directly into the index.html it runs perfectly. Is this a angular-templates pbastowski:angular-babel issue. Are you sure that that the exact steps defined in the bootstrapping step are tested?

**Comment by Urigo** [comment]
@saanplus it's not the place for this, but thanks for pointing that out.
We are aware about this issue and hoping to solve it this week
