### ISSUE TITLE
Information about release 1.2

### ISSUE THREAD

**Issue by Deadly0** [Urigo/angular-meteor#856]
Hi, where can I find information about 1.2 release?

**Comment by Urigo** [comment]
Good question.
I'm planning to release a blog post in Meteor very soon.
until then, I think the main changes are in the first chapter of the tutorial and in chapter 8

**Comment by Urigo** [comment]
Here it is: http://info.meteor.com/blog/angular-meteor-1.2.0

**Comment by Urigo** [comment]
And here is about the [1.3 release](http://info.meteor.com/blog/angular-meteor-1.3)
