### ISSUE TITLE
Angular 2.0 tutorial step 5.7 missing code

### ISSUE THREAD

**Issue by edoardo849** [Urigo/angular-meteor#860]
Hello, just noticed that in this step

http://angular-meteor.com/tutorials/angular2/routing-and-multiple-views 

at the point 5.7

instead of 
```
@View({
    template: '',
    directives: [ROUTER_DIRECTIVES]
})
```

should be

```
@View({
    template: '<router-outlet></router-outlet>',
    directives: [ROUTER_DIRECTIVES]
})
```

I think it's an error because later on you mention "Notice also that we've added one line template:".

Ciao

**Comment by Urigo** [comment]
@barbatus I think it's fixed now right?

**Comment by barbatus** [comment]
@Urigo yes
