### ISSUE TITLE
Tutorial angular2 step 7 is missing

### ISSUE THREAD

**Issue by edoardo849** [Urigo/angular-meteor#861]
Cannot find the seventh step "Folder Structure": the page has the text of the previously visited page:

http://angular-meteor.com/tutorials/angular2/folder-structure

**Comment by cesargalindo** [comment]
You can select if from the Tutorials drop-down menu at 
http://angular-meteor.com/tutorials/angular2

for now...

**Comment by Urigo** [comment]
Both links for now
