### ISSUE TITLE
Reactive function in $meteor.object

### ISSUE THREAD

**Issue by canac** [Urigo/angular-meteor#867]
Is there a technical reason why `$meteor.object` does not support a reactive function as the first parameter? If not, it would be useful in my application if it did, and it would make `$meteor.object` consistent with `$meteor.collection`. Right now I am having to do something like this:

```javascript
$scope.items = $scope.$meteorCollection(() => {
  const currentUser = $rootScope.getReactively('currentUser');
  return MyCollection.find({ userId: currentUser ? currentUser._id : null });
});
Object.defineProperty($scope, 'item', {
  get() {
    return $scope.items[0];
  },
});
```

It would be a lot cleaner if I could simply do this:

```javascript
$scope.item = $scope.$meteorObject(() => {
  const currentUser = $rootScope.getReactively('currentUser');
  return MyCollection.findOne({ userId: currentUser ? currentUser._id : null });
});
```

Thanks for all the time and effort you have put into making this such an awesome package! :+1:

**Comment by Urigo** [comment]
With the new [Angular Meteor 1.3 release](http://info.meteor.com/blog/angular-meteor-1.3) the way we work with objects has improved a lot.
No need for Angular wrappers anymore and you can simply use `findOne`.
Check it out and let me know how did it worked for you here or in the post's comments

**Comment by canac** [comment]
@Urigo Yes, it worked great! Thanks for addressing this use-case in the 1.3 release.
