### ISSUE TITLE
renamed all files to .html but templateUrl still requires .ng.html suffix

### ISSUE THREAD

**Issue by maartenbusstra** [Urigo/angular-meteor#868]
Updated to the new way of naming the files for the build system to pick up on the templates. But, whenever I try to rename the `templateUrl`s it doesn't work. (Angular tried to load more than once, etc.) :(

**Comment by maartenbusstra** [comment]
Oh, I just edited one of those renamed files and now it works. I guess it's a caching issue.

**Comment by dotansimha** [comment]
@maartenbusstra 
Next time you can also try to `meteor reset` in your project root.

**Comment by maartenbusstra** [comment]
@dotansimha I ended up just removing the build files, but the shortcut is nice.

**Comment by Urigo** [comment]
I think that in the new [1.3 release](http://info.meteor.com/blog/angular-meteor-1.3) we do caching validations better so there should be less of those problems happening
