### ISSUE TITLE
AngularMeteor Tutorial

### ISSUE THREAD

**Issue by steltz** [Urigo/angular-meteor#872]
I'm interested in AngularMeteor and was going through the tutorial and I keep getting this error when I install the Angular package:

>While determining active plugins:
>error: conflict: two packages included in the app (angular-templates and templating) are both trying to >handle *.html
>error: conflict: two packages included in the app (pbastowski:angular-babel and ecmascript) are both >trying to handle *.js

It appears the packages are fighting with each other. Did I do something wrong? I followed all the instructions in the tutorial.

Thanks

--Nic

**Comment by steltz** [comment]
Found this...

https://github.com/Urigo/angular-meteor/issues/849

It appears the tutorial is out of date.

**Comment by dotansimha** [comment]
It's in the tutorial - step 0, in the "Adding Angular 1" step:
http://angular-meteor.com/tutorials/angular1/bootstrapping

**Comment by abhaykumar1415** [comment]
1. meteor remove blaze-html-templates
2. meteor remove ecmascript

Run the following commands to remove meteor's  default ecmascript package  .
Now the app should run fine .
