### ISSUE TITLE
Extending LoginServices

### ISSUE THREAD

**Issue by benlegault** [Urigo/angular-meteor#873]
Hi, I'm new to meteor and...angular-meteor.  I have a package that was created to use a login service others that the default ones.  It's working fine under Meteor, using blaze and default features of Meteor but...how would I go about making this working with angular-meteor?  Let's say that I wish to login with a third party? Is there a way to extend the default ones?  Thank you people for your great work!!!

**Comment by p3r4f089** [comment]
check this http://angular-meteor.com/tutorials/angular1/user-accounts-authentication-and-permissions

**Comment by Urigo** [comment]
Great question! :)
With the new [Angular Meteor 1.3 release](http://info.meteor.com/blog/angular-meteor-1.3) the way we work with Meteor account is much better. No need for Angular wrappers anymore.
Check it out and let me know how did it worked for you here or in the post's comments
