### ISSUE TITLE
Tutorial is broken

### ISSUE THREAD

**Issue by master-7** [Urigo/angular-meteor#877]
Page not work http://angular-meteor.com/tutorials/angular1/mobile-support-and-packages-isolation

**Comment by cesargalindo** [comment]
You can access it from the Tutorial drop-down menu at  
 http://angular-meteor.com/tutorials/angular1

for now...

**Comment by Urigo** [comment]
It should work now, please let me know if it doesn't

**Comment by master-7** [comment]
Now tutorial is works. Thanks
