### ISSUE TITLE
Step 5, Router not routing properly

### ISSUE THREAD

**Issue by batjko** [Urigo/angular-meteor#879]
Hi there,
I have updated my Meteor project to 1.2.1, and started yesterday with this tutorial.
Everything seems to be fine, until Step 5 where I am getting our good old friend the "Tried to load Angular more than once" error, which I understand often happens if the router can't find the template:
![image](https://cloud.githubusercontent.com/assets/7287076/11189044/c57888ae-8c85-11e5-8a37-7c95c8b9593c.png)

But I am 100% sure I am using the right absolute path:
![image](https://cloud.githubusercontent.com/assets/7287076/11189056/de293448-8c85-11e5-8540-b2c799cab813.png)

```javascript
angular.module('socially')
  .config( ($urlRouterProvider, $stateProvider, $locationProvider) => {
    $locationProvider.html5Mode(true);

    $stateProvider
      .state('walks', {
        url: '/walks',
        templateUrl: 'client/views/walk-list.html',
        controller: 'WalkListCtrl'
      })
      .state('walkDetails', {
        url: '/walks/:walkId',
        templateUrl: 'client/views/walk-details.html',
        controller: 'WalkDetailsCtrl'
      });

    $urlRouterProvider.otherwise('/walks');
  });
```
Don't ask about the "walks", long story. Just imagine it says "parties" instead.

Any idea?

**Comment by batjko** [comment]
(sorry, I referred to the wrong step. I meant step 5 in the tutorial. That's corrected above now.)

**Comment by batjko** [comment]
I tried to change my controllers to use the old array notation for DI (I hadn't before):
i.e.:
```javascript
angular.module('socially')
  .controller('WalkListCtrl', ['$scope', '$meteor', ($scope, $meteor) => {
```

But that just complains even louder:
![image](https://cloud.githubusercontent.com/assets/7287076/11206960/351c0d28-8d0a-11e5-9702-fa9576d305f2.png)

**Comment by Urigo** [comment]
can you share your repo?

**Comment by batjko** [comment]
Ok, I'll put it on Github tomorrow if I can.

**Comment by HasanKeyf** [comment]
Yep, after upgrading to newest meteor-angular, in my app routing is not working anymore,  to make sure I also download and extract the zip files from your tutorial and found same issue(I did not change anything in it  but just did not work too). I tried newngrouter , it seems fine so far  . but ui-router  has some issue , could not get templates. I also tried to include templates in directives that is also not working , 
angular.module('siparisClient')
    .directive('anaSayfa', function () {
        return {
            scope: {
                bar: '='
            },
            templateUrl: 'client/ana/ana.html',
            controller: function($scope) {
                $scope.foo = 'bar';
            }
        };
});

the absolute path is definitely correct (client/ana/ana.html)

**Comment by batjko** [comment]
> , to make sure I also download and extract the zip files from your tutorial and found same issue(I did not change anything in it but just did not work too). I tried newngrouter , it seems fine so far . but ui-router has some issue

Yea that does sound like there's a genuine issue here, rather than something with our own projects/repos.

**Comment by Mklueh** [comment]
Same problem. No routing anymore, and no errors

**Comment by Urigo** [comment]
Can please try with the new tutorial and [version 1.3](https://github.com/Urigo/angular-meteor/issues/878)?

**Comment by Urigo** [comment]
I've tested it and it works.... please re-open of it's not working for you

**Comment by TylerL-uxai** [comment]
+1 for meteor 1.5
