### ISSUE TITLE
Subscription doesn't update when changing view

### ISSUE THREAD

**Issue by brenthmiras** [Urigo/angular-meteor#88]
I have my publish code in server as follows:

Meteor.publish("cars", function (returnAll) { 
    check(returnAll, Boolean);
    var query = returnAll?{}:{
        $and:[
                {ownerId: this.userId},//count only his own properties
                {ownerId: {$exists: true}}//sellerId field exists
            ]
    };
    Counts.publish(this, 'numberOfCars', Cars.find(query));
    return Cars.find(query);
});

I have two views of which one displays only the cars owned by the user and the other displays all cars.
In the former, i define my subscription like this:

$subscribe
    .subscribe('cars',false)//return only owned cars
    .then(
        function(){
            $collection(Cars)
                .bind($scope,'cars');
        },
        function(error){
            console.log(error);
            alert("Cannot subscribe to cars");
        }
    );

The owned are fetched without problems. The problem is when I go to all cars (which is a larger subset of the collection) and go back to owned cars, the list still shows all cars when it should only be showing the cars you own.

My subscription in all cars controller looks like this:

$subscribe
    .subscribe('allCars')
    .then(
        function(){
            $collection(Cars)
                .bind(
                    $scope,         //the scope to bind
                    'cars'  //the scope variable to bind
                );
        },
        function(error){
            console.log(error);
            alert("Cannot subscribe to allCars");
        }
    );

**Comment by jakobloekke** [comment]
Greetings, 

I've read spmething worthy  on the  web and I think this  is a  very good idea for your business, take a look <http://spoxophuse.edschneider.com/e4fja>

Hugs, jakob
