### ISSUE TITLE
Directive 'vm' conflict

### ISSUE THREAD

**Issue by brendanscarano** [Urigo/angular-meteor#890]
I'm working on a single page application in Meteor/Angular where I have two directives in my index.html on my global scope. I am using controllerAs: 'vm' for both directives and it seems that they are overwriting one another.

```javascript
(function() {
  'use strict';
  function dateTime() {

    function dateTimeCtrl() {
        this.foo = 'testing date time component';
    }

    return {
      restrict: 'EA',
      controller: dateTimeCtrl,
      controllerAs: 'vm',
      template: '<div>{{vm.foo}}</div>'
    };
  }

  angular
    .module('DateTimeDirective', [])
    .directive('dateTime', dateTime);
})();
```

```javascript
(function() {
  'use strict';
  function weatherForecast() {

    function weatherForecastCtrl() {
        this.bar = 'testing weather forecast component';
    }

    return {
      restrict: 'EA',
      controller: weatherForecastCtrl,
      controllerAs: 'vm',
      template: '<div>{{vm.bar}}</div>'
    };
  }

  angular
    .module('WeatherForecastDirective', [])
    .directive('weatherForecast', weatherForecast);
})();
```

I am placing both directives within my index.html
```html
<head>
  <base href="/">
</head>
<body>
  <div ng-app="morningApp">

    <date-time></date-time>

    <weather-forecast></weather-forecast>

  </div>
</body>
```

When I run meteor and open my localhost I expect to see:
testing date time component
testing weather forecast component

However I am only seeing:
testing weather forecast component

When I inspect the 'vm' scope in my dev tools I am only seeing bar attached to 'vm', and not foo.

If I change the controllerAs to anything else in either directive the output works fine.

**Comment by MilosStanic** [comment]
You shouldn't name controller aliases the same for both controllers, or any two controllers for that matter. As you properly concluded, now you have one single `vm` variable in the global scope, and whichever is declared last overwrites the `vm` variable.  

You may have been confused by following instructions on page http://www.angular-meteor.com/api/getReactively

Where it gives example of naming the controller as `vm`. 
However, the practice as per John Papa's guide is to alias `this` of the controller internally as `vm` and in routers, or other controllerAs declarations, use some more meaningful names. In your case:

```javascript
 (function() {
  'use strict';
  function dateTime() {

    function dateTimeCtrl() {
        var vm = this; // or var self = this;
        vm.foo = 'testing date time compnent';

        vm.fooFn = function (){
            ....
            vm.foo = 'you have a typo - it's compOnent';
        };
    }

    return {
      restrict: 'EA',
      controller: dateTimeCtrl,
      controllerAs: 'dtc',
      template: '<div>{{dtc.foo}}</div>'
    };
  }

  angular
    .module('DateTimeDirective', [])
    .directive('dateTime', dateTime);
})();
```
and

```javascript
(function() {
  'use strict';
  function weatherForecast() {

    function weatherForecastCtrl() {
        var vm = this;
        vm.bar = 'testing weather forecast component';
    }

    return {
      restrict: 'EA',
      controller: weatherForecastCtrl,
      controllerAs: 'wfc',
      template: '<div>{{wfc.bar}}</div>'
    };
  }

  angular
    .module('WeatherForecastDirective', [])
    .directive('weatherForecast', weatherForecast);
})();
```
I hope that's clear now.

**Comment by brendanscarano** [comment]
This makes sense - Thank you for the help. I'm going to refactor my controllers taking this into consideration.

**Comment by mxab** [comment]
I assume you don't want to access the global controller from inside your directive, therefore you should isolate the scope of your directive so you can also both name 'vm'.

To isolate use
```
  return {
      restrict: 'EA',
      controller: weatherForecastCtrl,
      controllerAs: 'vm',
      template: '<div>{{vm.bar}}</div>',
     scope : {}

    };
```
if you don't put the scope attribute there it will have access to outer scope which usually is more dangerous then helpful

**Comment by MilosStanic** [comment]
@mxab true, I totally overlooked that.

**Comment by mxab** [comment]
@brendanscarano can you close this issue? I think it is really unrelated to the meteor angular project

**Comment by brendanscarano** [comment]
@mxab sure, I'll close it! Thank you guys for the help

**Comment by brendanscarano** [comment]
Hey Max,

I'm having some trouble closing the issue in GitHub. I've never done this
before and from my understanding I need to make a commit such as, "Close
#890", or a pull request to close the issue. I'm confused because I can't
seem to push any commits from my terminal, and I'm not sure what branch to
compare to master to make a pull request in.

I would appreciate any information!

Thanks,
Brendan

**Comment by mxab** [comment]
Don't you see a close button at the end of this issue?

**Comment by brendanscarano** [comment]
Well I was certainly making that much more complicated that it had to be!
Thanks for the help - it's closed now

**Comment by Urigo** [comment]
by the way, the updated tutorial is written in controllerAs syntax for helping people use best practices
