### ISSUE TITLE
since minimongo is in-memory data store.It has limitations on mobile device.solution?

### ISSUE THREAD

**Issue by faraazc** [Urigo/angular-meteor#892]
is there any way to make minimongo or any alternate solution to make it persistent. 
Something like websql?

Actually my datasets are very huge possibly it may more than 10GB..how to handle?

**Comment by sebakerckhof** [comment]
Some thinks to consider:
-Even webSQL doesn't allow very large databases (and it's deprecated). 
-Other local storage solutions are also limited to a couple of tens of megs.
-Do you really need all of that data on the client at all time?
-Minimongo doesn't support indexes, so queries would be unacceptable slow anyway.
-Even on desktop, sending 10GB to the client will crash the browser.

So there's really no option without having a cordova build an querying a database through a native db plugin. And even then you'll likely run into problems with a 10GB database.

**Comment by Urigo** [comment]
I think it's a good question but it should be posted on the Meteor forums as it's not Angular-Meteor specific - forums.meteor.com
