### ISSUE TITLE
Browser hangs with loading spinner infinitely spinning

### ISSUE THREAD

**Issue by pavanputhra** [Urigo/angular-meteor#895]
This issue is specific to version 1.2.2 of angular-meteor release.

When I try to open the app in browser (chrome) whole app freezes and chrome loading icon will be infinitely loading.

As chrome loading icon was shown, I thought chrome may be trying to load some resource without success. When I checked network tab, I saw chrome was unable to load following resource. 

```
http://localhost:3001/packages/driftyco_ionic/release/fonts/ionicons.ttf?v=2.0.1
```
Only way I could able to solve the issue is by installing previous version of angular package.

Image: Chrome infinitely loads and freezes.

![infinate-loading](https://cloud.githubusercontent.com/assets/6524792/11359070/a78387ee-929e-11e5-957c-c133aa1a4fd5.png)

Image: Network tab: Trying to load driftyco_ionic

![loading_network_tab](https://cloud.githubusercontent.com/assets/6524792/11359075/b06764de-929e-11e5-819d-15b67144f5bf.png)

**Comment by mxab** [comment]
What happens if you open the url in a seperate tab?

**Comment by pavanputhra** [comment]
@mxab I reinstalled angular 1.2.2, so that I can test as you specified. Surprisingly it's working now! It's strange! I will close this bug for now.
