### ISSUE TITLE
Windows OS - Folder Restructuring - pops WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by ajblk** [Urigo/angular-meteor#896]
In [step 7 - angular-meteor Tutorial (Folder structure)](http://www.angular-meteor.com/tutorials/socially/angular1/folder-structure) 

When using Windows 7 machine to build, i get error in Javascript Console

`Error: only one instance of babel/polyfill is allowed
[2]</<@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357 line 365 > eval:2963:1
[2]<@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357 line 365 > eval:2955:1
s@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357 line 365 > eval:2861:246
e@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357 line 365 > eval:2861:425
@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357 line 365 > eval:2861:1
@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357 line 365 > eval:2853:1
@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357 line 365 > eval:11:2
.globalEval/<@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:365:5
.globalEval@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:364:1
.converters["text script"]@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:9792:4
ajaxConvert@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:8864:18
done@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:9285:15
.send/callback@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:9739:8
.send@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:9745:7
.ajax@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:9236:5
jQuery._evalUrl@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:9394:1
.domManip@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:6003:10
.append@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:5779:1
.html/<@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:5905:5
jQuery.access@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:4178:5
.html@http://localhost:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:5869:1
$ViewDirectiveFill/<.compile/<@http://localhost:3000/packages/angularui_angular-ui-router.js?0610fee435d288074016c06fc17724677ff22649:4042:9
invokeLinkFn@http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:8812:9
nodeLinkFn@http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:8312:1
compositeLinkFn@http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:7703:13
publicLinkFn@http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:7578:30
updateView@http://localhost:3000/packages/angularui_angular-ui-router.js?0610fee435d288074016c06fc17724677ff22649:3990:23
$ViewDirective/directive.compile/</<@http://localhost:3000/packages/angularui_angular-ui-router.js?0610fee435d288074016c06fc17724677ff22649:3952:11
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:16334:15
$StateProvider/$get/transitionTo/$state.transition<@http://localhost:3000/packages/angularui_angular-ui-router.js?0610fee435d288074016c06fc17724677ff22649:3342:11
processQueue@http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:14768:28
qFactory/scheduleProcessQueue/<@http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:14784:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:16012:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:15823:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:16120:13
done@http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:10569:36
completeRequest@http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:10767:7
requestLoaded@http://localhost:3000/packages/angular_angular.js?0a328c602667881bb749eae26bbfccca25285a42:10708:1
 <div class="ng-scope" ui-view="">
`

My versions 
`angular@1.2.2
angular-meteor-data@0.0.6
angular-templates@0.0.1
angular:angular@1.4.7
angularui:angular-ui-router@0.2.15
autopublish@1.0.4
autoupdate@1.2.4
babel-compiler@5.8.24_1
babel-runtime@0.1.4`

**Comment by ajblk** [comment]
Initial build won't give me any ouput but if i make some tiny html changes to the templates in views folder then it builds and output correctly

**Comment by MilosStanic** [comment]
It's a template caching problem, see #886 and #888

**Comment by Urigo** [comment]
The caching issue was fixed with the new [1.3 release](http://info.meteor.com/blog/angular-meteor-1.3)
