### ISSUE TITLE
Data not loading reactively from backedn

### ISSUE THREAD

**Issue by jessonjoy** [Urigo/angular-meteor#897]
Hi,

I am not able to reactively see my collections changed whenever the data in the backend mongo remote server is modified. It works one way - from device to server but not the other way. What could be wrong?

```
//Controller
$scope.$meteorSubscribe('MyList') 
            .then(function () {  
                $scope.aList = $meteor.collection(List);             
});

```

```
//Server
Meteor.publish("MyList", function () {
    if(this.userId) {
        return List.find({'user' : this.userId}, {sort: {createdDt: -1}, limit: 25});
    }
});

```

Thanks

JJ

**Comment by Tallyb** [comment]
A wild guess will be that user is moved or not properly updated hence the record is not going to the client. Is the data updated locally and just not displayed, or not returning to the client at all? 
[tip: I have learned about this development time `msavin:mongol` package for viewing local client data, but did not try it myself yet.]

**Comment by mxab** [comment]
What exactly do you mean by see that is reactively modified, can you maybe explain "how you look at the data" and how you modify it?

**Comment by jessonjoy** [comment]
@mxab : So if i modify an item in the list, it updates that document on my local mini mongo and on my remote mongo server - which is what i mean by reactive updates. However, the reverse doesn't work; whenever the data in the backend mongo remote server is modified, I cannot see the change happening on the client without refreshing or resubscribing. I imagined that this 3 way binding should work without the insecure package

**Comment by mxab** [comment]
Hmm strange as far as I know this should work, do you stop the subscription by any chance? Can you show how you modify the document front/back and how you display it?

**Comment by Urigo** [comment]
@jessonjoy Please try to use the new API introduced in the [1.3 release](http://info.meteor.com/blog/angular-meteor-1.3) and re-open if that won't work for you.
