### ISSUE TITLE
Edit String inside Array makes a refres on view using autoClientSave

### ISSUE THREAD

**Issue by mrtruko** [Urigo/angular-meteor#899]
Im having a problem with arrays and autoClientSave, everytime someone edits something inside an array there is a refresh in the table and you lose focus of the input you were editing and its almost imposible to write with autoClientSave on true, with autoClientSave on false everything works fine.
i have something like this, In this case its imposible to edit description with autoClientSave on true cuz the ng-repeat rerenders everything and input loose the focus on every change.
{
    "examenName" : "Name Of The exam",
    "items" : [ 
        {
            "score" : 1,
            "order" : true,
            "description" : "rthrthjj"
        }, 
        {
            "score" : 1,
            "order" : true,
            "description" : "jrthrthj"
        }
    ]
}

**Comment by jacobdr** [comment]
You probably should provide way more context if you are expecting a thoughtful and helpful response. 




With that said, it sounds like you should probably denounce the input (i.e. Don't update on every key press but after a certain amount of time after the initial input focus) or use a package that has an intermediate edit box that has a submit function, and only update the meteor collection of interest when that value gets changed. 




I'm on my phone so can't provide links right now, but a search for angular denounce input should give you some insight. Additionally, you could turn off auto save and make a manual call to the meteorCollection.save method. 




Good luck -- and share more code if you would like additional community support. 



—

**Comment by mrtruko** [comment]
Well im working on a school proyect and tried to make an online quiz app where more than 1 teacher could add questions and edit a quiz at the same time but every time someone makes an small change to an element inside an object array on the exam all the elements inside the ng-repeat rerenders for all teachers connected to the same quiz so its imposible to write a full sentence since it will rerender on every keypress. Here is a picture of the thing im trying to do.
and my github link for the exam if anyone wanna take a look at it. https://github.com/mrtruko/AlphaQuiz

![exam](https://cloud.githubusercontent.com/assets/12106310/11449872/cb69e644-956e-11e5-9012-e1c875dbcb85.png)

**Comment by Urigo** [comment]
@mrtruko we are moving away from `autobind` with the new [1.3 release](http://info.meteor.com/blog/angular-meteor-1.3) as it is not a best practice. more details inside the article.
Please try to move to the new `helpers` syntax and let me know if that works for you.
Uri
