### ISSUE TITLE
at startup :  Uncaught Error: [ng:btstrpd] App Already Bootstrapped with this Element 'document'

### ISSUE THREAD

**Issue by dabielf** [Urigo/angular-meteor#90]
while i'm perfectly (i think) following the tutorial, at Step 2, after i included

Meteor.startup(function () {
      angular.bootstrap(document, ['socially']);
    });

hints ?

**Comment by funkytaco** [comment]
FYI, I got this error when the path to my `templateURL` for a route in one of my $stateProvider.state() calls was wrong.

**Comment by blogui91** [comment]
I got the same error, finally i realized templateURL route was wrong. that's why.

**Comment by danimbrogno** [comment]
Yeah, I think what happens is if the templateUrl is wrong then the request for the template returns the entire meteor page again (aka the 404 response). This means your index file gets injected into your inject file. Hence the double bootstrap problem.

**Comment by leoetlino** [comment]
This is not actually what caused the issue for the OP and me, but yes, an invalid templateUrl can cause the app to bootstrap more than once.

**Comment by jakobloekke** [comment]
Hey,

If  you were looking for something  really fantastic  and cool, than you found  it! Just  take a look   <http://follow.nmwconsultant.com/e4pvd>

Warmest regards, jakob@jakobloekkemadsen.com

**Comment by jakobloekke** [comment]
Hello,

I've recently came accross that amazing  stuff, it looks nice I think, ytake a look <http://expert.mumineenfoundation.org/e4rbtsd>

Hugs, jakob@jakobloekkemadsen.com
