### ISSUE TITLE
Step 8 - Folder Structure Fix

### ISSUE THREAD

**Issue by braginteractive** [Urigo/angular-meteor#900]
Step 3 & 4 should be server.js instead of app.js if you are following the tutorials. 

Also at the end of the tutorial you should probably have people run 'meteor rebuild', I was getting the following error: Error: only one instance of babel/polyfill is allowed

I found the solution here: https://github.com/Urigo/angular-meteor/issues/870

**Comment by carlosbaraza** [comment]
:+1: 

Indeed, this have cause me an hour headache!

Thank you @braginteractive !

**Comment by Urigo** [comment]
Both (file names and caching problem) should be fixed with the new [1.3 release](http://info.meteor.com/blog/angular-meteor-1.3).
Please re-open if it's not the case
