### ISSUE TITLE
modularize an app cause [$injector:nomod] errors due to folder strcture

### ISSUE THREAD

**Issue by dagatsoin** [Urigo/angular-meteor#902]
My main app uses two modules: core and dashboard. Here are the declaration: 

**client/lib/app.js**:
```
angular
	.module('app',[
		/* Shared modules */
		'app.core',

		/* Feature areas */
		'app.dashboard',
	]);
```
**client/shared/core.module.js**
```
angular
	.module('app.core', [
		'angular-meteor',
		'ui.router',
		'accounts.ui',
		'nemLogging',
		'ui-leaflet',
		'rzModule',
		'angular.filter',
		'checklist-model',
	]);
```
**client/dashboard/dashboard.module.js**
```
angular
	.module('app.dashboard', [
		'app.map',
		'app.widgets'
	]);
```
**client/map/map.module.js**
```
angular
	.module('app.map', []);
```
**client/widgets/widgets.module.js**
```
angular
	.module('app.widgets',[]);
```

At loading I have errors:

```
Uncaught Error: [$injector:nomod] Module 'app.map' is not available! 
Uncaught Error: [$injector:nomod] Module 'app.core' is not available!
Uncaught Error: [$injector:nomod] Module 'app.widgets' is not available!
```

I think it is due to the load order of Meteor. It seems to not fit at all with Angular requirements. What folder structure is required for modularization in meteor angular?

**Comment by dagatsoin** [comment]
I managed to load the app.map module by renaming it 0-map.module.js
Is there an other way, it is a bit crappy.

**Comment by MilosStanic** [comment]
Why do you have two `app.dashboard` modules declared in two files `client/map/map.module.js` and `client/dashboard/dashboard.module.js` ?

**Comment by dagatsoin** [comment]
@MilosStanic  Typo. Edited.

**Comment by Urigo** [comment]
@dagatsoin here is the way Meteor depends the load order: http://docs.meteor.com/#/full/structuringyourapp
You can use naming or a certain folder structure.
But the best thing is, that with the new version of Meteor (1.3, a first beta should be out today or tomorrow) you can use ES2015 modules and they will determine the load order
