### ISSUE TITLE
Can't insert using collection2

### ISSUE THREAD

**Issue by matthieuh** [Urigo/angular-meteor#904]
When using aldeed:collection2 i got this error: "When the modifier option is true, validation object must have at least one operator" when i try to add object.

```
Events = new Mongo.Collection("events");

var EventSchema = new SimpleSchema({
  "name": {
    type: String,
    label: "Name"
  },
  "description": {
    type: String,
    label: "Description"
  }
});

Events.attachSchema(EventSchema);

```

```
$scope.events = $meteor.collection(Events, false);
      $scope.events.save(newEvent)
      .then(function() {
        $state.go('events');
      }, function(err) {
        if (err && err.message)
          console.log('err', err.message);
      });
```

This is a angular-meteor problem or mine ?

Thanks for help

**Comment by DAB0mB** [comment]
Can you please show how does 'newEvent' object looks like? Maybe it has to do something with the data you are trying to save.

**Comment by Urigo** [comment]
The `save` syntax will be depracated in favor of the new `helpers` syntax in [Angular Meteor 1.3](http://info.meteor.com/blog/angular-meteor-1.3).
Please try to migrate and tell me if it worked for you
