### ISSUE TITLE
CollectionFS doesn't resolve object fully after saving to collection

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/angular-meteor#905]
Additionally to problems with saving files to CollectionFS firing $digest on url() calls, as described in other issues, it appears it is so, because the saved object doesn't fully resolve upon saving to CollectionFS. 

Namely, immediately after saving like so: 

```javascript

$scope.images.save().then (function(data){
  console.log(data[0]._id.url({store: 'original'}));
});
```
returns `null` or `undefined`. If I log the whole object to the console, it collects everything needed, including the `url` function, yet, calling it returns empty result. When called afterwards, a few seconds later the `url` function returns a proper url of the saved object. 

So, my conclusion is that the object is not fully resolved after saving. And that's why it creates infinite digest loops when `url` is called from the view.

**Comment by shantanubhadoria** [comment]
I see you have a long list of issues, and to avoid duplication I will put my issue here as well since its possibly a duplicate. 
I am not able to retrieve a file saved using gridFS example in angular-meteor tutorial.

i.e. when I use image.url() in my angular template to get the url for the uploaded image and it gives me a file not found error. 
I can see a record for the file that I upload when I do 

     db.cfs.images.filerecord.find(); 

so I suspect that the error is not in upload but in loading the image itself.

**Comment by MilosStanic** [comment]
@shantanubhadoria  
Using `image.url()` in your template in ng-repeat will give you a digest loop, until `image.url()` resolves, and only then it will display the image after successfully retrieving the image's url. If you use only one `image.url()` it will probably try and fail on first digest, and you will not get the image. At least I suspect so. 
To fix that, try assigning a scope variable to your html element like so: 
```html
<img ng-src="imageurlvar">
```
and in your controller do something like 
```javascript
  $scope.imageurlvar = image.url();
```
It should then resolve properly and give you the url to be put into html view. 

Please let me know if this worked.

**Comment by shantanubhadoria** [comment]
@MilosStanic
Thanks for the suggestion.
How do you resolve the situation if its a array of images in a ng-repeat loop?

**Comment by MilosStanic** [comment]
@shantanubhadoria 
let's assume you have your documents in a collection `$scope.imgDocuments` then, you would do in your controller: 
```javascript
for (var i=0; i<$scope.imgDocuments.length; i++) {
   $scope.imgDocuments[i].imgUrl = $scope.imgDocuments[i].url();
}
```
and in your html view: 

```html
<div ng-repeat="imgdoc in imgDocuments">
   <img ng-src="imgdoc.url">
</div>
```

**Comment by MilosStanic** [comment]
Dear all, especially @dotansimha @netanelgilad , to demonstrate the issue, 
I have created a clone of the simple collectionfs-thumbnail example here: 
https://github.com/MilosStanic/angular-meteor-collectionfs

It only prints to console the returned object after saving image to collection, and demonstrates that the `url()` function returns `null`. However, in the template, the very same function is called in `ng-repeat` and it produces the url.

Thank you very much for your time.

**Comment by MilosStanic** [comment]
Can anybody please spare some time to take a look at this?
@Urigo, this is very important thing to make work. Uploading files without being able to immediately fetch their URL is really a problem. I don't want to subscribe to files collection on each controller where I need to view images. I want to store image urls in other collections, so I don't have to load images collection, too. 
Thank you very much.

**Comment by MilosStanic** [comment]
It appears this is a problem with CollectionFS. 
Described here https://github.com/CollectionFS/Meteor-CollectionFS/issues/323
I will investigate alternatives, since this is shameful and debilitating lack of feature.

**Comment by Urigo** [comment]
In anyway, with the new [Angular Meteor 1.3 release](http://info.meteor.com/blog/angular-meteor-1.3) the way we work with CollectionFS has improved a lot.
No need for Angular wrappers anymore.
Check it out and let me know how did it worked for you here or in the post's comments

**Comment by shantanubhadoria** [comment]
Hi @Urigo ,
I am using the new release now. I just finished rewriting my code base in the new Meteor like spec as suggested in the release blog post. I used FileSystem() storage for CollectionFS and can confirm that the file is uploading properly. However for some reason I am still not able to download the file from the url when I call document.url() on my image object.

In my Model: 

    documents = new FS.Collection('documents',{
      stores: [
        new FS.Store.FileSystem("original", {path: "~/uploads"})
      ]
    });

controller:

    controller: function($scope, $stateParams, $reactive, toastr) {
      $reactive(this).attach($scope);

      this.documentById = (documentId) => {
        return documents.findOne(documentId);

      // Helpers
      this.helpers({
        documentList: () => {
          return documentList.findOne({_id: documentId});
        }
      };

Then in my template

    <li ng-repeat="documentId in documentList.documents">
      <a download="{{ controllerAsLabel.documentById(document).original.name }}" ng-href="{{ controllerAsLabel.documentById(document).url() }}"
    </li>


Any ideas where I am going wrong?
Thanks

**Comment by MilosStanic** [comment]
@shantanubhadoria no, definitely, it's a CollectionFS problem, and it's been described in several issues on their repo. So there's only hacks that you can use to try to solve this problem. 
In your case, if you're storing to filesystem, it should be fairly easy to reconstruct the URL yourself?
Personally, I'm using GridFS, and I have two server methods to check file upload progress and if the upload is complete. 
Like this, on server: 

```javascript
Meteor.methods({
    'getUploadProgress': function(collectionName, imgId) {			
			var collection = FS._collections[collectionName];			
			var image = collection.findOne({_id: imgId});		
			return image.uploadProgress();
		},
    'isItOver': function(collectionName, imgId) {
			var collection = FS._collections[collectionName];
			var image = collection.findOne({ _id: imgId});		
			return image.isUploaded();
		}
});
```
And on the client I have the upload method in my FileStorage service: 
```javascript
FileStorageClass.prototype.uploadImg = function(dest) {
		var self = this;
		var d = $q.defer();
		self.currentFile = null;
		$('<input type="file">').bind("change", function (event) {
			if(dest==='avatars') {					
				self.currentFile = Avatars.insert(event.target.files[0], (err, fileObj) => {
					if(err) console.log(err);					
				});
			}	else if(dest==='backgrounds') {
				self.currentFile = Backgrounds.insert(event.target.files[0], (err, fileObj) => {
					if(err) console.log(err);					
				});
			}
			d.resolve(self.currentFile);
		}).click();
		return d.promise;
	};
```

So, finally in my controller I call this upload in my FileStorage service, and check each 1000ms whether the upload has completed, and I manually reconstruct the file's url, but I'm not sure that's a good solution in my case, which was proven when I deployed my app and this simply didn't work, there was 404 reply on my uploaded files: 

```javascript
vm.upload  = 	FileStorage.uploadImg;
...
this.uploadStart = function(dest){		
		vm.upload(dest).then(function(data){			
			vm.curFileId = data._id;
		  vm.started = true; // show progress bar						
			var repeater = $interval(function(){
				Meteor.call('getUploadProgress', dest, vm.curFileId, function(err, retval){					
					vm.fileProgress = retval; // update progress bar
					if(retval == 100) {				
						$interval.cancel(repeater); // cancel repeater I		
						var rptr = $interval(function(){ 
							Meteor.call('isItOver', dest, vm.curFileId, function(err, over){								
								if(over) {
									$interval.cancel(rptr);	// cancel repeater II							
									vm.started = false; // hide progress bar
									if(dest === 'avatars') {
										if(!angular.isDefined(vm.thisUser.profile.avatars)){ vm.thisUser.profile.avatars = Array();}
										let newAvatar = {
											file_id: data._id, 
											full_url: '/cfs/files/avatars/'+data._id+'/'+data.original.name+'?store=original',
											thumb_url: '/cfs/files/avatars/'+data._id+'/'+data.original.name+'?store=thumbnail'
										};
										vm.thisUser.profile.avatars.push(newAvatar);
										vm.setCurrentAvatar(data._id);
										Meteor.users.update({_id: vm.thisUser._id}, { 
												$set: { 'profile': vm.thisUser.profile }
											}, function(err, numberOfDocs){
												if (err) console.log(err);															
											}
										);											
									} else if (dest === 'backgrounds') {
										let newBackground = {
											file_id: data._id, 
											full_url: '/cfs/files/backgrounds/'+data._id+'/'+data.original.name+'?store=background'								
										};
										vm.thisUser.profile.background = newBackground;
										Meteor.users.update({_id: vm.thisUser._id}, { 
												$set: { 'profile.background': newBackground }
											}, function(err, numberOfDocs){
												if (err) console.log(err);																
										  }
										);
									}
									
								}
							});
						}, 1000);
					}
				});					
			}, 1000);						
		});
	};
```
I'm sure this is not a proper way to do things, but it's the only way I can think of at the moment, until the people at CollectionFS decide to implement `onUploaded` and `onStored` events that we can hook to. And the issue about this has been open for more than a year at CollectionFS.

**Comment by Urigo** [comment]
@MilosStanic thanks for the answer, can you also add a link to the existing issues on CollectionFS so that people will know where to refer to?

**Comment by MilosStanic** [comment]
@Urigo 
Yes, the issue at CollectionFS is best described here: https://github.com/CollectionFS/Meteor-CollectionFS/issues/323
