### ISSUE TITLE
Broken "Socially > Angular 1 > Ionic" route

### ISSUE THREAD

**Issue by carlosbaraza** [Urigo/angular-meteor#908]
Hi @Urigo,

Just let you know that the Angular 1 route for Ionic is broken: `http://www.angular-meteor.com/tutorials/socially/angular1/ionic`.

Cheers,
Carlos.

**Comment by jboothe** [comment]
I noticed the same but selecting "22. Ionic" would display the Ionic title on the page but the body was the content from "21. Mobile Support & Packages Isolation". 

There also seems to be an issue with the router. I've found selecting a tutorial from the megamenu at the top of angular-meteor.com pulls up a blank page although the url is correct. Hitting the browser refresh is needed to then load the page. 

Thank you Urigo, for the tutorials. It's apparent that you put a lot of time into them. It's also apparent that there were several maintenance revisions. As I went thru the Angular 1 tutorial, I found several typos, incorrect code and areas where some clarification would benefit. However, when clicking the "Improve this Doc" it goes to a Github 404 page. I wouldn't mind helping cleanup the docs if you provide a path. 

Let me know, and I'll pitch in.

**Comment by Urigo** [comment]
I believe it is fixed now
Thanks!

**Comment by carlosbaraza** [comment]
Awesome! :)

**Comment by jboothe** [comment]
Thanks for your incredible effort. From here it doesn't look like you slept this week. ;)

**Comment by Urigo** [comment]
Lucky for me @dotansimha @netanelgilad @idanwe @DAB0mB also haven't been sleeping this week so I've got a lot of help :)
