### ISSUE TITLE
Can I still use .ng.js for java script files?

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#910]
I know that version 1.2 did away with the need to the .ng. requirement in the java script files - but I was just wondering if I could still use this - as I find it a very quick way of knowing if I am working on a server or client java script file.

**Comment by kamilkisiela** [comment]
Yes, of course. You can name your files whatever you want. 

"ng.[extension]" suffix was the way to identify which files needed to be compiled.

**Comment by JohnAReid** [comment]
@kamilkisiela thanks!
