### ISSUE TITLE
Angular-material package out of date

### ISSUE THREAD

**Issue by sebakerckhof** [Urigo/angular-meteor#911]
The official meteor package for angular material ( angular:angular-material, https://atmospherejs.com/angular/angular-material ) is faulty.
Version 1.0.0-rc6 exists, but if you inspect the code in the package it's actually the code of 1.0.0-rc4

**Comment by sebakerckhof** [comment]
Same for 1.0.0-rc5!

**Comment by mxab** [comment]
I have a look

**Comment by dohomi** [comment]
@sebakerckhof just updated the source, its now published and version number is ```1.0.6-rc6_1```. Thanks for reporting

**Comment by sebakerckhof** [comment]
Great, thanks for the fast solution

**Comment by MilosStanic** [comment]
someone, please update package to rc7.
Rc6 had an ugly bug that rendered md-menu totally unusable.
Thanks!

**Comment by mxab** [comment]
@MilosStanic done

**Comment by MilosStanic** [comment]
@mxab wow, fast, thanks :beers:
