### ISSUE TITLE
Push.send({}) not working in meteor + angularJS + raix:push

### ISSUE THREAD

**Issue by mitiaptest** [Urigo/angular-meteor#912]
Meteor + AngularJS with raix:push not working.

We are facing issue in following method:

Push.send({
from: 'Test',
title: 'Hello',
text: 'World',
badge: 12,
query: {}
});

This method not working throws 'Error: Match error: Expected g in field badge'.

We have tested this with meteor simple example only added
raix:push
angular

If we ran APP without angular package raix:push works but not sure why not working with angularJS.

This is working fine on browser but not in iOS and Android App.

If I remove badge from Push.send() then that work in iOS and Android App but not with badge.

Guys can you please help me on this ?

@Urigo  Attached is my test app code.

[push_demo_with_angular_meteor_raix_push_issue.zip](https://github.com/Urigo/angular-meteor/files/52282/push_demo_with_angular_meteor_raix_push_issue.zip)

**Comment by mitiaptest** [comment]
@Urigo Can you please help me on this?

**Comment by mitiaptest** [comment]
Facing this issue after updating angular@1.0.7 to angular@1.2.2

**Comment by dyaa** [comment]
@mitiaptest I Think i can help. Can you post the code there and tell us how you're implementing `Push` ?

**Comment by Urigo** [comment]
@mitiaptest Please try updating to the new [1.3 release](http://info.meteor.com/blog/angular-meteor-1.3).
It uses a `helper` syntax with pure Meteor API so Angular shouldn't be in your way when using regular Meteor packages.
Let me know if that helped and if it is still related to the Angular package please re-open

**Comment by mitiaptest** [comment]
@dyaa Please find attached code. In this code I have added raix:push and angular package after that added "config.push.json" with GCM apiKey and projectNumber (Please add yours in attached code config.push.json file) after that on click of button called function i.e sendMessage inside of this added following code:

 var pushId = Push.send({
            from: 'Test',
            title: 'Hello',
            text: 'World',
            badge: 12,
            query: {}
          });
          console.log('Push id : ' + pushId);

This is working on browser but not working on Android devices.Throwing Error "Match error: Expected Number in field badge".

I am not sure which package make conflict.
@Urigo  I have tested this with 1.3 but its not resolved the issue.

But if I remove badge field from Push.send({}) then its seems to working on both browser and Android but not with badge field. 

[simple-todos-angular-raix-push.zip](https://github.com/Urigo/angular-meteor/files/57754/simple-todos-angular-raix-push.zip)

Please help me on this.

**Comment by mitiaptest** [comment]
@dyaa 
Error: Match error: Expected Number in field badge
Error
    at check (http://meteor.local/packages/check.js?9c4972d3f4fe56cd455d3022e70b5195e642fc41:61:15)
    at _validateDocument (http://meteor.local/packages/raix_push.js?27a49e0d3cdc02231f5d60989aea2035cbffffed:249:3)
    at PushHandle.Push.send (http://meteor.local/packages/raix_push.js?27a49e0d3cdc02231f5d60989aea2035cbffffed:329:3)
    at Scope.$scope.sendMessage (http://meteor.local/app/simple-todos-angular.js?1b1f1b7bd2439383516821d80268e033a2a401a6:6:25)
    at fn (eval at <anonymous> (http://meteor.local/packages/angular_angular.js?6d4ee2c049f945acd899d01d101da60606fc5cc8:13388:15), <anonymous>:4:224)
    at callback (http://meteor.local/packages/angular_angular.js?6d4ee2c049f945acd899d01d101da60606fc5cc8:23636:17)
    at Scope.$eval (http://meteor.local/packages/angular_angular.js?6d4ee2c049f945acd899d01d101da60606fc5cc8:16075:28)
    at Scope.$apply (http://meteor.local/packages/angular_angular.js?6d4ee2c049f945acd899d01d101da60606fc5cc8:16175:25)
    at HTMLButtonElement.<anonymous> (http://meteor.local/packages/angular_angular.js?6d4ee2c049f945acd899d01d101da60606fc5cc8:23641:23)
    at HTMLButtonElement.jQuery.event.dispatch (http://meteor.local/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:4691:9) angular_angular.js?6d4ee2c049f945acd899d01d101da60606fc5cc8:12543

**Comment by Urigo** [comment]
@mitiaptest can it be a `raix:push` problem?
how does Angular relates to your code?

**Comment by mitiaptest** [comment]
@Urigo If I remove angular package and use raix:push only then its works.

**Comment by phund** [comment]
I have a same issue. Any idea here. Thank you!

**Comment by mitiaptest** [comment]
@phund I am able to help you.can you please explain what exactly you are doing ?

**Comment by phund** [comment]
@mitiaptest 
I use meteor 1.2.1, angular 1.2.2,  raix:push@3.0.2. 
config.push.json:
{
  "gcm": {
    "apiKey": "xxxxxxxxxxxxxxxxxxxx",
    "projectNumber": xxxxxxxxxxx
  },
  "production": true
}
Push.send({
from: 'Test',
title: 'Hello',
text: 'World',
badge: 12,
query: {}
});
When I run in android simulator, it work properly. But when i build a .apk file and install on my phone, It doesn't work. No any error is raised  
Logs:
      Push: Sent message "Hello" to 0 ios apps 2 android apps
      Push, GUIDE: The "Push.appCollection" - No APN clients have  registred on the server yet...
      ANDROID: Result of sender:  {"multicast_id":7885496412699648000,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1450320921160305%fcc793840027b8b2"}]}
      ANDROID: Result of sender: {"multicast_id":6256537619202375000,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1450320921161893%fcc793840027b8b2"}]}

Thanks,

**Comment by mitiaptest** [comment]
@phund Get raix push git clone and include it into local packages folder I have resolved that issue and raix merged it into git but not published that changes yet.

**Comment by phund** [comment]
@mitiaptest I will do it. Thank you very much :+1:
