### ISSUE TITLE
Prevent Sync After Save

### ISSUE THREAD

**Issue by dtruel** [Urigo/angular-meteor#917]
Hello,

I'm building an application that has a contact info page.  On the page, you can input emails.  Instead of an "add new email" button, I'm pushing an empty object to the end of the emails list so that people don't have to click an 'add new' button, just like in gmail contacts.  Before saving, I quickly check if the last email item is empty - if it is, I delete it, then save, then add it again, before any $digest or $apply takes place.  Unfortunately, once the save takes place, the object is once again synced with the server's copy, and the new field I added is deleted.  To fix this, I could always add the field again after the save function returns.  However, that is not optimal, as the new input box disappears for the duration of the save.

My question is this: is there a way to prevent the sync from happening after save? I know real time is a big part of Meteor, however in this case I'm not sure the best way to handle it.

Thanks!

**Comment by MilosStanic** [comment]
Yes, you have to remove the `autopublish` package from your app by typing: 
`meteor remove autopublish`

Also when binding a collection to AngularJS, you should use `false` as the second argument, to prevent autosaving. 

Please read on here: http://www.angular-meteor.com/api/meteorCollection

**Comment by dtruel** [comment]
Hi Milos,

Thank you for responding.  Unfortunately I already have removed the autopublish package, and am using false as the second argument to prevent autosaving.  I'm actually publishing the object on page load (for an edit, not a new object), and subscribing like this:

``` javascript
$scope.$meteorSubscribe(singleItemSubscriptionName,itemId).then(function(handle) {
   item.emails.push({});
   //handle.stop()  //I tried adding this line, and it would no longer load data.
});
```

This is how I get the original data onto the page.  However once I get it on the page, I no longer need it. Unfortunately, stopping the subscription prevents the data from loading.

I don't see how I can get this data on the page without a publish and subscribe of some sort, short of using a meteor method.  However, I'd like to use the angular-meteor object if at all possible, and not have to resort to a meteor method for manually trasferring the data.

**Comment by dtruel** [comment]
Closing this issue because I resolved my problem by updating how the client-side logic runs.  If anybody else has this issue and can't find a workaround, it may be worth looking into.
