### ISSUE TITLE
problem when updating to 1.2.3 - Uncaught Error: use "new" to construct a Mongo.Collection

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#919]
I finally got round to updating (from 1.0.5 to 1.2.3 - a moderate size app with 176+ files) - however having taking the plunge - I am having a problem with Ground.DB - I am using the same version of ground.DB as in the old app but in the new updated app the following code:

(function(){var GroundLabels = new Ground.Collection('labels', { connection: null });
var GroundSimpleStatements = new Ground.Collection('simplestatement', { connection: null });
var GroundActivity = new Ground.Collection('activity', { connection: null });
var GroundPractice = new Ground.Collection('practice', { connection: null });
var GroundAllStatement = new Ground.Collection('allstatement', { connection: null });
var GroundMasterWords = new Ground.Collection('masterwords', { connection: null });
}).call(this);

is producing the following error: "Uncaught Error: use "new" to construct a Mongo.Collection" linking to the code above.  Ground.DB works in the old version so it must be something with the new Angular format - perhaps angular-meteor-data@0.0.6.

Any suggestions as I am really stuck!

**Comment by Urigo** [comment]
We released [Angular Meteor 1.3](http://info.meteor.com/blog/angular-meteor-1.3) because it is much easier to work with 3rd party Meteor packages. 
No need for any special wrappers anymore.
Please check it out and let me know if that worked for you.

**Comment by JohnAReid** [comment]
I have checked and it still does not work with version 1.3!

**Comment by Urigo** [comment]
@JohnAReid can you share your code?
It might sound like it's a GroundDB problem and not an Angular problem

**Comment by JohnAReid** [comment]
@Urigo GroundDB works fine in the normal version of Meteor - it is because Angular Meteor is no longer sitting on top of Meteor but is now a different version of Meteor.

**Comment by Urigo** [comment]
@JohnAReid can you share a reproduction? maybe in a separate repo?

**Comment by JohnAReid** [comment]
@Urigo I am closing this as  have decided not to use Meteor anymore!
I do not need 3 way data binding, and my app builds times was getting painfully long (10 - 15 seconds) - I have switched back to node with express and the build times are almost instant.

The most deciding factor has been the on going discussioins about Galaxy and hosting sites - I am using Bluemix and the procedure is so easy with no hoops to go through (such as mup).

I would however like to thank you personally for all your support and the first rate tutorials.

**Comment by Urigo** [comment]
@JohnAReid I'm very sorry to hear that.
I've forward your message inside the Meteor team.
It looks like in Meteor 1.3 there are going be improvements to build process performance and build process time is on the weekly agenda so I hope we will have more to share soon.

Besides that, does anyone experience the issue above with GroundDB as well?

**Comment by LucNaterop** [comment]
I am experience this error with Meteor 1.3 and ground:db

**Comment by Urigo** [comment]
@LucNaterop do you think it's grounddb related or angular-meteor related?
can you post a reproduction?

**Comment by LucNaterop** [comment]
The error just magically disappeared. I have no idea what was going on and I cannot reproduce it at this point.
