### ISSUE TITLE
Version 1.3 replacement for $meteor.waitForUser() 

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#922]
The $meteor.waitForUser() is deprecated in versin 1.3 -  but I cannot find a Meteor’s API for this method.

If I use Meteor.user() it returns undefined, but if I wrap within a $meteor.waitForUser() it returns the users details.

**Comment by Urigo** [comment]
If you look at the implementation you can see that this is because it's wrapped in an autorun.
There are 2 choices:
1. Simply copy that logic into your app
2. Create a package that does that and publish it for everyone to enjoy

If you choose option number 2, think if that package should be Angular Meteor specific or you create create something that the whole Meteor community can benefit from

**Comment by JohnAReid** [comment]
@Urigo - this leaves me speechless - I am faced with hours and hours  of work changing and checking that my codes works in 1.3. To make major changes and to not provide complete documentation on how to make the changes is not right - 

to reply "with look at the implementation"  is no help at at all - what are you taking about - where is the implementation?

It is bad enough having to makes these changes (I do not see any benefit I get from them) without having to hunt around to figure what to replace them with!

**Comment by Urigo** [comment]
@JohnAReid I'm sorry, I mean, in 1.3 your old code still works so I can improve the docs and help you out.
What I meant in look at the implementation is this:
https://github.com/Urigo/angular-meteor/blob/master/packages/angular-meteor-data/modules/angular-meteor-user.js#L17-L28

As you can see, it's a reasonable code to write in your app without using a package.
I do get the benefit of using it as a prepared method, I just think it might be in a separate package.
I can create one and I probably will if no one will do that before me, I just think it's an easy opportunity for community people to contribute and get recognized.
Tomorrow I will add more docs on that matter, I would love to hear feedback on where and how would you want that to be

**Comment by triniwiz** [comment]
@JohnAReid from taking a quick look at the code  you can create it 


```js
this.waitForUser = function () {
var deferred = $q.defer();
if (!Meteor.loggingIn())
deferred.resolve(Meteor.user());
return deferred.promise;
};
```


```js
this.waitForUser = function(){
      console.warn('[angular-meteor.waitForUser] Please note that this method is deprecated since 1.3.0 and will be removed in 1.4.0!');

      var deferred = $q.defer();

      $meteorUtils.autorun($rootScope, function(){
        if ( !Meteor.loggingIn() )
          deferred.resolve( Meteor.user() );
      });

      return deferred.promise;
    };
```

**Comment by JohnAReid** [comment]
Thanks all - I think my real grip is documentation -  I expected waitForUser to be documented in the Meteor  documentation page and it was not!

**Comment by Urigo** [comment]
I'm re-opening as I would love to think about a prepared solution, whether Angular specific or a general Meteor one

**Comment by Urigo** [comment]
Added to the 1.3.1 milestone where we will bring back the functions from before, just in a separate package

**Comment by sebakerckhof** [comment]
@Urigo I could provide a PR for this, but what should happen with $meteorUtils?

**Comment by jacobdr** [comment]
+1 




Love the leaner angular core but maintenance of old APIs through additional packages. 




The 1.2 upgrade threatened to break my code but the angular-with-blaze saved me. This resolution of this issue similarly helps me to maintain my legacy code bases. 




Break work @coreCommiters



—

**Comment by sebakerckhof** [comment]
@Urigo what about:
-Split of `meteorUtils` to a separate package (e.g. `angular-meteor-utils`), remove deprecated messages
-Split of `meteorCollection/meteorObject` to a separate package which depends on the `angular-meteor-utils` package (e.g. `angular-meteor-data-legacy`), leave deprecated messages
-Split of `meteorAccounts` to a separate package which depends on the `angular-meteor-utils` package (e.g. `angular-meteor-accounts`), remove deprecated messages
-Create an umbrella package to imply 3 packages above (e.g. `angular-meteor-legacy`)
-Have `angular-meteor-data` depend on `angular-meteor-legacy` until 1.4

That way nothing changes for current 1.3 users, and for 1.4 people can choose which legacy parts to include.

**Comment by Urigo** [comment]
@sebakerckhof that a good idea.
Hopefully by the end of the day we will have a separate accounts package and the rest later this week.
I will also love some help in that and maybe you can create the rest of the packages and pull request the `angular` to direct to that?

**Comment by sebakerckhof** [comment]
Okay, i'll look into that.

**Comment by justinweinberg** [comment]
This worked for me until something official comes out.  Inject MeteorUserService and change $meteor to MeteorUserService for the promise returning methods.  Aside from these three the regular Meteor methods sufficed.  

No warranty expressed or implied...

```JavaScript
(function() {
    "use strict";

    angular.module('app').factory('MeteorUserService', ['$q', MeteorUserService]);

    function MeteorUserService($q) {

        return {
            requireValidUser: requireValidUser,
            waitForUser: waitForUser,
            requireUser: requireUser
        };

        function requireUser() {
            var deferred = $q.defer();

            Meteor.autorun(function(stoppable) {
                if (!Meteor.loggingIn()) {
                    if (Meteor.user() === null) {
                        stoppable.stop();
                        deferred.reject("AUTH_REQUIRED");
                    } else {
                        stoppable.stop();
                        deferred.resolve(Meteor.user());
                    }
                }
            });

            return deferred.promise;
        }

        function requireValidUser(validatorFn) {
            return requireUser().then(function(user) {
                var valid = validatorFn(user);

                if (valid === true)
                    return user;
                else if (typeof valid === "string")
                    return $q.reject(valid);
                else
                    return $q.reject("FORBIDDEN");
            });
        }

        //I see trouble... there is no timeout 
        function waitForUser() {
            var deferred = $q.defer();

            Meteor.autorun(function(stoppable) {
                if (!Meteor.loggingIn()) {
                    console.log("stopping");
                    stoppable.stop();
                    deferred.resolve(Meteor.user());
                }
            });

            return deferred.promise;
        }


    }
})();
```

**Comment by Urigo** [comment]
With the new `1.3.2` release you can use the new `angular-meteor-auth` package.
Add it to your project, here are the docs: http://www.angular-meteor.com/api/1.3.2/auth
