### ISSUE TITLE
Missing ReactiveComponent used in tutorial blog post

### ISSUE THREAD

**Issue by kamilkisiela** [Urigo/angular-meteor#926]
**ReactiveComponent** from *dotansimha:angular-reactive-component* is missing.

Mentioned here:

https://github.com/Urigo/angular-meteor/blob/master/docs/angular-meteor/client/content/api-reference/1.3.0/api.reactive.html

and here:

http://info.meteor.com/blog/angular-meteor-1.3

**Comment by dotansimha** [comment]
Hi @kamilkisiela , you are right, I will deploy it ASAP.

**Comment by dotansimha** [comment]
@kamilkisiela Done!
You can now install it using `meteor add dotansimha:angular-reactive-component`
