### ISSUE TITLE
Errors after changing to new helpers

### ISSUE THREAD

**Issue by triniwiz** [Urigo/angular-meteor#928]
After i changed my code to use the helpers i'm getting errors all over :disappointed: 

TypeError: Cannot read property 'preventDefault' of undefined

```js
.controller('AddCompanyCtrl', function ($scope, $mdDialog) {

		$scope.helpers({
			save: function (event, data) {
				if (data != undefined && data.length > 0) {
					$mdDialog.hide(data)
				} else {
					event.preventDefault();
				}
			}, close: function () {
				$mdDialog.cancel()
			}
		})


	})
```
 
I was wondering is it still possible to use a controller by setting it in the config ?
```js
.config(function ($urlRouterProvider, $stateProvider) {
		$urlRouterProvider.otherwise('login')
		$stateProvider
			.state('login', {
				url: '/login',
				templateUrl: 'client/app/login/login.html',
				controller: 'LoginCtrl'
			})
})
```

or like in the examples
```js
.directive('login', function () {
    return {
      restrict: 'E',
      templateUrl: 'client/app/login/login.html',
      controllerAs: 'loginCtrl',
      controller: function () {}
}
})
```

I prefer the 1st one :tongue:

**Comment by Urigo** [comment]
@triniwiz maybe I should have explained `helpers` better.
`helpers` are only for functions that return a value to the view.
Your `helper` functions don't return anything to the view so there is no reason to place them inside a helpers but you should just place them inside a regular scope function like before

**Comment by Urigo** [comment]
about routing, there shouldn't be change

**Comment by triniwiz** [comment]
Changed the code so only functions which return value are in the helpers.

Thanks :smile:
