### ISSUE TITLE
$scope.subscribe doesn't support arguments w/ callbacks

### ISSUE THREAD

**Issue by bmanturner** [Urigo/angular-meteor#929]
Or if it does it is unclear how. I can get _only_ arguments to work and I can get _only_ callbacks to work, but not both.

I'm looking for the new equivalent of:
```
$scope.$meteorSubscribe('data', $scope.arg).then((sub) => {
// callback
});
```

**Comment by netanelgilad** [comment]
Check out my answer here:
https://forums.meteor.com/t/angular-meteor-1-3-now-closer-to-the-standard-meteor-api/14588/21?u=netanelgilad

Hope it clarifies..

**Comment by bmanturner** [comment]
It does. Thank you very much. Maybe I'm just a dullard, but I think an example should be added to the documents.

**Comment by netanelgilad** [comment]
You tottaly correct. @Urigo let's add an example.
