### ISSUE TITLE
Issues are getting closed to early

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#930]
I have posted two issues over the last few days - both have been closed by Urigo without a chance for me to reply!

The issues I raised are important to me and perhaps to other as well - I expect to be taken seriously!

**Comment by dagatsoin** [comment]
![image](https://49.media.tumblr.com/tumblr_m4j0lzgA8i1qio4rko1_400.gif)
You need to reopen it if the proposed solution does not work for you.

**Comment by JohnAReid** [comment]
Can't find any option to reopen a closed issue

**Comment by Urigo** [comment]
Hi @JohnAReid please link those issues here and I'll re-open them.
I'm sorry, it was like a spring cleaning after the new version and I might have gone to fast...
