### ISSUE TITLE
Tutorial - angular 1 - Step 14 missing Information

### ISSUE THREAD

**Issue by westor21** [Urigo/angular-meteor#932]
In Step 14 you promised:

In this step we will learn how to use Meteor methods and how angular-meteor enhances them with the support of promises.

But I do not find information about using $meteor.call and using of promises, especially how to handle errors.

**Comment by dotansimha** [comment]
Hi,
Changed the description in https://github.com/Urigo/angular-meteor/pull/935
Note that in the new API of angular-meteor (1.3), we removed the `$meteor` service, in order to use the original Meteor API for thing like that.

**Comment by Urigo** [comment]
Merged and deployed, thanks @westor21 and @dotansimha

**Comment by westor21** [comment]
Thank you for your fix and you advice of removing the meteor service. That is a pity, I liked the idea of using promises here. And it seems I have to rewrite some of my code to replace all the $meteor.subscribe stuff - I'm not so happy with this.
Could you consider to drop a deprecation note to the console as early as you know, the API will change? That would be great and helpful, especially if you could include a hint (may be with a link) on how to rewrite the code to be compatible with the new API.

**Comment by Urigo** [comment]
@westor21 I've added your suggestions to the docs, will be published after 1.3.1 will be released (hopefully tomorrow)
