### ISSUE TITLE
Tutorial - angular 1 - Step 15 does not load

### ISSUE THREAD

**Issue by westor21** [Urigo/angular-meteor#933]
I cannot load Step 15. The headline changes, but the content stays the same like the referring page.

**Comment by dotansimha** [comment]
@westor21 
Can your provide your `.meteor/versions`? 
Also, does this works for you? http://socially-step15.meteor.com/parties 
Thanks

**Comment by dotansimha** [comment]
Fixed in https://github.com/Urigo/angular-meteor/pull/935
@Urigo  please merge

**Comment by Urigo** [comment]
Merged and deployed, thanks @westor21 and @dotansimha
