### ISSUE TITLE
(v1.3) Failing to get object from collection, double this.helper runs, etc.

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/angular-meteor#934]
Hi @Urigo, 

Again, with my problems :)

I have a controller that looks like this: 
```javascript
angular.module('chatapp.admin').controller('AdminUserDetailsCtrl', function($scope, $meteor, $reactive, $stateParams, storage, $mdToast, $q, $interval){
	
	$reactive(this).attach($scope);
	console.log('PRINT 0: User Details controller instantiated');
	
	this.helpers({
		currentUser: () => {			
			console.log('PRINT1: ', $stateParams.userId);
			let result = Meteor.users.findOne({_id: $stateParams.userId});			
			console.log('PRINT2:', result);			
			return result;
		}
	});
	
	this.subscribe('users', () => {
		console.log('PRINT3: subscribing');		
	});
	
	console.log('PRINT4: currentUser helper', this.currentUser);

...
};
```
So, when I have the subscription block, the browser console looks like this: 

![WithSubscription](http://s11.postimg.org/mm5upjwir/Log_With_Subscribe.png)

As you can see, `this.helpers` is invoked twice. And only after the second call the model is ready.

On the other hand, when I comment out the block: 
```javascript
this.subscribe('users', () => {
	console.log('PRINT3: subscribing');		
});
```
Then the browser console looks like this: 
![WithoutSubscription](http://s11.postimg.org/9gqcjg2n7/Log_Without_Subscribe.png)

And you can see that `this.helpers` is called only once, but Meteor doesn't return user data from query. So model is empty.

Do you have any idea why is this so?

**Comment by MilosStanic** [comment]
Furthermore, when I navigate to the users list (which is one page back), I see `this.helpers` from the user details called two more times, although the user detiails controller should have been destroyed. 
Then, navigating between users list and user details multiple times, there seems to be a buffer of user id's of previously visited user details. 
So, on the 3rd visit to random user's details page, `this.helpers` gets called several times with userId's of all previously visited users in reverse order. 

Look at console now: 
![MultipleHelpersCalls](http://s18.postimg.org/3tl2rmw2h/Multiple_Helpers.png)

The first three calls to `this.helpers` are with the id of the current user I want to see, then `this.helpers` is called with id's of previously visited users. Yet, the model is populated with the data of the users I'm currently seeing.

This is totally bizarre :)

**Comment by Deadly0** [comment]
@MilosStanic what wrong with it? `currentUser` called first time when no users data loaded, and second time, when meteor loaded users data from server.

**Comment by MilosStanic** [comment]
@Deadly0 Okay, I understand, seems logical. But I shouldn't need to subscribe to `users` at all. Should I? 
`Meteor.users.findOne()` should return a non-empty object, even without subscription.

Also why is `currentUser` called repeatedly when I leave the page, as shown in my second post? And not only that, it calls it several times in reverse order of my previous visit to user details page.

**Comment by Deadly0** [comment]
Of course you should subscribe to users . If you not subscribed `Meteor.users.findOne` will return `undefined` every time. Remember, data about current logged in user loading automatically without subscription.

About second post. It's hard to say certainly, but when you navigate through pages it's changes some reactive sources, subscriptions, or destroy controller and `currentUser` method needs to be recalculated.

**Comment by MilosStanic** [comment]
@Deadly0 this fact that you stated that data about current logged in user is loading automatically without subscription may be the resolution to my problem that I stated in #887 

**Please** take a look at that issue (never mind the first few posts, start from the end). It appears that I have current logged in user data mixed into my `users` subscription no matter what I do. This reflects on the fact that the data about current user is always loaded into my paginated list of users (it used to be on every page, but after switching to 1.3 it's only on some). 

This effectively means that it's impossible to do a paginated list of users correctly in Meteor. 

Please correct me if I'm wrong. And if I'm right, do you have any idea how to make a paginated list of users that works properly?

**Thank you very much**. I think you've shed a lot of light on my knowledge about Meteor.

**Comment by Deadly0** [comment]
@MilosStanic is your problem current logged in user appears everywhere? I know the solution for the problem.

**Comment by MilosStanic** [comment]
@Deadly0 Yes, that's my problem. Thanks.

**Comment by sebakerckhof** [comment]
@MilosStanic pagination in Meteor is non-trivial because results from multiple publications are combined. This is not only a problem for user pagination. More in depth article: https://www.discovermeteor.com/blog/pagination-problems-meteor/

One solution is to use this package: https://atmospherejs.com/percolate/find-from-publication

**Comment by MilosStanic** [comment]
I think I'll close this as I got my answer from @Deadly0 in #887 about pagination, and thank you too, @sebakerckhof . 

Regarding the original issue, @Deadly0 says this is okay, and I should subscribe to collection, even though I need only one object. Even though, I think I remember I didn't really need subscription for $meteor.object(). But I'm not sure. 

@Urigo please reopen if you think this is an issue.

**Comment by Deadly0** [comment]
@MilosStanic you need to be subscribed to use `$meteor.object()`. The exception is **current logged in user** because accounts-base package already have this subscription.

**Comment by MilosStanic** [comment]
@Deadly0 thanks again, it may very well be that I don't remember correctly, or have simply overlooked the fact.
