### ISSUE TITLE
add extra info to returned list

### ISSUE THREAD

**Issue by leizard** [Urigo/angular-meteor#938]
Hi,
Normally I could return a reactive meteor collection like this : 

```
               $scope.chats = $scope.$meteorCollection(function () {
                    var chatCollection = Chats.find();
                    return chatCollection;
                }, false);
```

But what if I want to add some extra info to my returned chat list, something like this : 

```
                $scope.chats = $scope.$meteorCollection(function () {
                    var chatCollection = Chats.find().fetch();
                    _.each(chatCollection, function(chat) {
                        chat.imgUrl = generateUrl(chat._id);
                    });
                    return chatCollection;
                }, false);
```

which will return issue : 
```
TypeError: Cannot read property 'name' of undefined
    at new AngularMeteorCollection (angular-meteor.bundle.min.js:4)
    at Scope.$meteorCollection (angular-meteor.bundle.min.js:4)
    at Scope.$meteorCollection (angular-meteor.bundle.min.js:4)
    at chat-list.controller.js:10
    at processQueue (ionic.bundle.js:21888)
    at ionic.bundle.js:21904
    at Scope.$eval (ionic.bundle.js:23100)
    at Scope.$digest (ionic.bundle.js:22916)
    at ionic.bundle.js:23139
    at completeOutstandingRequest (ionic.bundle.js:13604)
```

seem like it can only return Collection cursor, not array.

How could I resolve this ? 
Thank you.

**Comment by MilosStanic** [comment]
There is not enough code quoted. 
What is in line 10 of your chat-list-controller.js ?

**Comment by leizard** [comment]
sorry. I just copy the the error from another version of the code. the point is if I convert Collection cursor to array like this:

```
               $scope.chats = $scope.$meteorCollection(function () {
                    var chatCollection = Chats.find().fetch();
                    return chatCollection;
                }, false);
```

it would return the same error:

```
TypeError: Cannot read property 'name' of undefined
    at new AngularMeteorCollection (angular-meteor.bundle.min.js:4)
    at Scope.$meteorCollection (angular-meteor.bundle.min.js:4)
    at Scope.$meteorCollection (angular-meteor.bundle.min.js:4)
    at chat-list.controller.js:10
    at processQueue (ionic.bundle.js:21888)
    at ionic.bundle.js:21904
    at Scope.$eval (ionic.bundle.js:23100)
    at Scope.$digest (ionic.bundle.js:22916)
    at ionic.bundle.js:23139
    at completeOutstandingRequest (ionic.bundle.js:13604)
```

line 10 is : 

```
$scope. chats = $scope.$meteorCollection(function () {
```

**Comment by MilosStanic** [comment]
@leizard sorry, but I can't see the line where you call `name` which is undefined.

**Comment by leizard** [comment]
yeah I don't either. it seems like a variable in some package file, which happened because I returned an array.
Thank you for spending your time.

**Comment by Deadly0** [comment]
@leizard this is not the core of your problem, but you can use transform http://docs.meteor.com/#/full/mongo_collection
```
var Chats = new Mongo.Collection('chats', {
  transform: function(chat) {    
    chat.imgUrl = generateUrl(chat._id);
    return chat;
  }
});
```

**Comment by leizard** [comment]
@Deadly0 thank you, that looks great. I really don't know Meteor supports a transform inside Mongo.Collection.
@Urigo with angular-meteor 1.3.1 and new helper support, could I do something like this (like I usually do in Blaze) : 

```
$scope.helpers({
  party() { 
    var chatList = Chats.find().fetch();
    _.each(chatCollection, function(chat) {
          chat.imgUrl = generateUrl(chat._id);
     });
     return chatList;
  }  
})
```

and chatList would be still reactive ?

**Comment by netanelgilad** [comment]
@leizard The code you wrote for 1.3 would work and would keep your helper reactive. We will release angular-meteor to bower with 1.3.1 version (which should be coming soon). Have fun!

**Comment by leizard** [comment]
@netanelgilad thanh you very much for the great works :)

**Comment by leizard** [comment]
I reopen it for anyone with similar issue could see. For now, I am using angular directives with $meteorAutorun to transform my returned list and keep it reactive. Looking forward 1.3.1 with new helper support and make my life easier :)

**Comment by Urigo** [comment]
I've released the new [1.3.1 version](https://github.com/Urigo/angular-meteor/releases), I will publish it to Bower in about 2 days

**Comment by leizard** [comment]
Wow. Such a good news on a Sunday morning. Cheers!

**Comment by Urigo** [comment]
@idanwe

**Comment by Urigo** [comment]
@leizard it's live in Bower as `1.3.2`

**Comment by leizard** [comment]
yeah! I saw it on the early morning and have been working on migration till now. I also posted an issue here: https://github.com/Urigo/angular-meteor/issues/1021
Beside that, everything works like a charm!
