### ISSUE TITLE
Execution order problems

### ISSUE THREAD

**Issue by sebakerckhof** [Urigo/angular-meteor#942]
Here's some pseudo code:
```js
function myController($scope,$reactive,userId) {
  var self = this;
  let $meteorData = $reactive(this).attach($scope);
  $meteorData.helpers({
    user() {
      console.log(Users.findOne(userId));
      return Users.findOne(userId);
    }
  });

  $meteorData.subscribe('userDetails', () => [
    userId,
    {onReady: () => {console.log("ready");}}
  ]);
};
```

Subscribing to userDetails results in some fields of that user being published to the client.

The problem is that if I execute the code above I get:
`undefined` (from `console.log(Users.findOne(userId));`)
`ready` (from `console.log("ready");`)
`{...userobject...}` (from `console.log(Users.findOne(userId));`)

Is this correct behavior? I would expect the order to be:
`undefined` (from `console.log(Users.findOne(userId));`)
`{...userobject...}` (from `console.log(Users.findOne(userId));`)
`ready` (from `console.log("ready");`)

That is because the ddp protocol works in this order (first the user details are published, then a ready message) and one would expect the data to be there in the onReady call...

**Comment by netanelgilad** [comment]
To me it makes sense. I think what happens is that the data arrives from
the subscription and the onReady gets called in one execution frame and the
findOne gets invalidated. But the autorun of the helper runs in the next
execution frame because that is when the Tracker flushes.
If you'll try to access the subscription data on the onReady callback, I
believe it will be there..

**Comment by sebakerckhof** [comment]
Well, I have never used Blaze, I always used angular-meteor, so I should read up on how tracker works.

Thing is I have a lot of code that looks like:
```html
<div ng-if="vm.loaded"> ... will give errors when parts of data is not available ...</div>
```

```js
this.data = $meteor.object(...);
$meteor.subscribe('subscription').then(()=>{this.loaded = true;});
```

In 1.2, when the promise was resolved, this.data was already updated. Using the onReady function in 1.3 it's not (I guess for the reason you mentioned). But that's a problem in the code above.
Now I just wrap the onReady function in a 0ms timeout, but that's probably not the best way to do it.

**Comment by eugenious** [comment]
I suppose that you shouldn't be relying on execution order at this fine level of detail.

The intention of "on ready" is to indicate that the subscription is initialized, it doesn't (necessarily) indicate that all reactive variables have finished reacting (if that makes sense).

Perhaps something like this could work for you:
```js
<div ng-if="vm.user">show user</div>
```

Basically, only show if there's a valid user object.

**Comment by Urigo** [comment]
I agree with @eugenious on this.
@sebakerckhof what do you think?

**Comment by sebakerckhof** [comment]
@eugenious Yeah, I've thought of that, but the problem is that there are already some fields of vm.user available from another subscription. So then I'd have to start looking for specific fields being present which gets ugly.

@Urigo Yeah, it surely isn't a bug if the system was designed like this. It's just that in my use cases it made sense that onReady was called after the reactive vars have updated. But I can imagine other use cases where it's the other way around. I can take other approaches for my usecases.

**Comment by Urigo** [comment]
@sebakerckhof how would a Meteor developer who use Blaze would handle your use case?
Maybe we can add back something?
