### ISSUE TITLE
(v 1.3) Error in Meteor.user() in helpers

### ISSUE THREAD

**Issue by cranesandcaff** [Urigo/angular-meteor#944]
$scope.helpers({
      currentUser(){
        return Meteor.user()
      }
    })

Inside of a controller throws error `TypeError: Cannot read property 'changed' of undefined'`

Returning other reactive stuff like `return Meteor.users.find()` seems to work though.

**Comment by Deadly0** [comment]
@cranesandcaff not familiar with new js syntax, but helper should looks something like this:
```
$scope.helpers({
  currentUser: () => {
    return Meteor.user()
  }
})
```
or in old js
```
$scope.helpers({
  currentUser: function() {
    return Meteor.user()
  }
})
```

Last example work in my app.

**Comment by cranesandcaff** [comment]
I'll give the second a try but the new syntax should have it compile to the same thing.

**Comment by Deadly0** [comment]
@cranesandcaff ok, got it. But your example work for me. Are you sure the problem in this helper?

**Comment by cranesandcaff** [comment]
Removing it removes the error, I'm reworking the auth to comply with the updated API. I'll update if I have further info.

**Comment by cranesandcaff** [comment]
It's possible I had the old version when I tested that...did the previous version have `$scope.helpers`? It's working now either way.

**Comment by Deadly0** [comment]
@cranesandcaff no, it's 1.3 new feature.

**Comment by cranesandcaff** [comment]
Interesting. I had

    app.controller('AppVM', function($scope){
      $scope.helpers({
        profiles(){
          return Profiles.find()
       },
      currentUser(){
        return Meteor.user()
      }
    }

Profiles worked fine, but if I left `currentUser` in it threw that error, took currentUser out no more error. Weird but working now.
