### ISSUE TITLE
Redundant warnings in v1.3

### ISSUE THREAD

**Issue by orangeRat** [Urigo/angular-meteor#945]
Guys, can I switch off the 'deprecated' warnings in settings? I rewrote my code to compatibility with new version, but I still see the warnings in JS console and it's annoying, because I should to find important messages between this messages after each page reload

**Comment by dotansimha** [comment]
Hi @orangeRat ,
Actually @Urigo  just fixed that in this commit https://github.com/Urigo/angular-meteor/commit/a83c26b377767d3265043074ea547f82f102e8c1
I think he will publish it in the next version (1.3.1) with several fixes.

**Comment by orangeRat** [comment]
Great! Problem is solved. Thank you :)
12 дек. 2015 г. 17:18 пользователь "Dotan Simha" <notifications@github.com>
написал:
