### ISSUE TITLE
Waffle.io

### ISSUE THREAD

**Issue by Tallyb** [Urigo/angular-meteor#946]
Am I the only one who does not know this tool? 
@Urigo  Feel like adding it to angular-meteor? 
check out the sample...
https://waffle.io/urigo/angular-meteor

**Comment by MilosStanic** [comment]
looks very nice.

**Comment by Urigo** [comment]
cool, I've create a milestone for 1.3.1 so probably you can look at it there as well:
https://waffle.io/urigo/angular-meteor?milestone=1.3.1
I'm not sure what's the benefit though...

**Comment by Tallyb** [comment]
It adds visibility, and because you can see this: 
[![Throughput Graph](https://graphs.waffle.io/urigo/angular-meteor/throughput.svg)](https://waffle.io/urigo/angular-meteor/metrics)

**Comment by Urigo** [comment]
Graphs, number one cause of doing nothing....
