### ISSUE TITLE
Docs say almost everything is deprecated and will be removed in v1.4

### ISSUE THREAD

**Issue by lukovnikov** [Urigo/angular-meteor#953]
Every page in the angular-meteor docs except $reactive and ReactiveContext are saying they are deprecated since v1.3 and will be removed in v1.4. However, I could not find any docs or plans for v1.4.

Could someone please elaborate on the future or is this a bug in the docs?

**Comment by Deadly0** [comment]
@lukovnikov ReactiveContext is oll you need now. Read the article about new realease http://info.meteor.com/blog/angular-meteor-1.3

**Comment by lukovnikov** [comment]
Thanks for the link, I was thinking 1.3 was still the old version and was looking for 1.4 docs.

**Comment by Urigo** [comment]
I've updated the messages and the docs on 1.3.1, hopefully will be out this weekend
