### ISSUE TITLE
angular-templates v0.0.2 / templates-handler.js-L15 / Error: [angular-meteor][err][404] ... 'HTML template does not exists!'

### ISSUE THREAD

**Issue by buitregool** [Urigo/angular-meteor#958]
I review the file 'templates-handler.js' and I have the impression that the 'if' in L15 it's wrong. It should be the opposite case. Would be nice if someone could confirm it. Thank you!

```
  var templatesFileExtension = ['html', 'tpl', 'tmpl', 'template', 'view'];
  ...
  ...
  if (templatesFileExtension.indexOf(fileExtension) > -1) {
    throw new Error('[angular-meteor][err][404] ' + templatePath + ' - HTML template does not exists!');
  }
```

**Comment by Urigo** [comment]
@buitregool any news or reproduction?

**Comment by rizqevo** [comment]
+1 for issue, my case was load html using ui-router
```javascript
templateUrl:function($stateParams){
                return  'client/module/'+$stateParams.appid+'/views/'+$stateParams.pagename+'.html';
            },      
```
@Urigo 1.3.1 still have this, updates 
```javascript
if (templatesFileExtension.indexOf(fileExtension) > -1) {
```
to
```javascript
if (templatesFileExtension.indexOf(fileExtension) < -1) {
```
it fixes me

**Comment by buitregool** [comment]
HI @urigo. Sorry for my delay. I did the same amend that @rizqevo and works perfectly. I'm also using ui-router but my templates are inside packages. Anyway, this is my environment:

**Packages:**
accounts-password               1.1.4  Password support for accounts
angular                         1.3.0+ Everything you need to use AngularJS in your Meteor app
angular:angular-material        1.0.0  Google Material design written for AngularJs (official repo)
bb                              0.0.1+ BB root package
bbcontacts                      0.0.1+ BB Contacts package
check                           1.1.0  Check whether a value matches a pattern
dotansimha:accounts-ui-angular  0.0.2  AngularJS wrapper for Meteor's Account-UI package
driftyco:ionic                  1.1.0_2  Ionic Framework official Meteor package
email                           1.0.8  Send email messages
es5-shim                        4.1.14  Shims and polyfills to improve ECMAScript 5 support
jquery                          1.11.4  Manipulate the DOM using CSS selectors
meteor-base                     1.0.1  Packages that every Meteor app needs
mobile-experience               1.0.1  Packages for a great mobile user experience
mongo                           1.1.3  Adaptor for using MongoDB and Minimongo over DDP
session                         1.1.1  Session variable
standard-minifiers              1.0.2  Standard minifiers used with Meteor apps by default.
tracker                         1.0.9  Dependency tracker to allow reactive callbacks

**router code sample**
```
    .state('login', {
      url: '/login',
      templateUrl: '/packages/bb/client/views/login.ng.html',
      controller: 'LoginCtrl',
      resolve: {
        ValidSubdomain: function(SubdomainFac, AccountsSrv, $q) {

          var deferred = $q.defer();

          $q.all([
            AccountsSrv.isSubdomainValid(SubdomainFac)
          ])
          .then(function(results) {
              if(!results[0]) deferred.reject(new Error('INVALID_SUBDOMAIN'));
              console.log(results);

              return deferred.resolve(results);
          });

          return deferred.promise;
        }
      }
    })
```
**Chome console error**
Error: [angular-meteor][err][404] /packages/bb/client/views/login.ng.html - HTML template does not exists!
    at Object.$delegate.get (templates-handler.js:16)
    at sendReq (angular.js:10528)
    at serverRequest (angular.js:10268)
    at processQueue (angular.js:14792)
    at angular.js:14808
    at Scope.$eval (angular.js:16052)
    at Scope.$digest (angular.js:15870)
    at Scope.$apply (angular.js:16160)
    at bootstrapApply (angular.js:1679)
    at Object.invoke (angular.js:4523)

**Comment by rizqevo** [comment]
-1 for issue, my folder structure needs rearrange. running 1.3.1 as default. Thanks @Urigo and team

**Comment by Urigo** [comment]
@buitregool looks like you are using the `angular` library but the templates are `ng.html`.
and if you want to use `ng.html` instead of `html` you need to use the `angular-with-blaze` package instead..

**Comment by buitregool** [comment]
I just left the extension '.ng.html' because it's an old project. If you rename all the file extensions to '.html' you will have the same issue. There is no blaze code inside. And if you look at the code L13 in 'templates-handler.js', you would realize that it doesn't matter because the code pops the last element from the split witch is 'html':
```
var fileExtension = ((templatePath.split('.') || []).pop() || '').toLowerCase();
```
I hope this helps. Cheers.

**Comment by dotansimha** [comment]
Hi @buitregool ,
Just a quick brief about `templates-handler.js`:
Angular-Meteor takes all the `.html` files and put them in `$templateCache`, which means that every `.html` that you'll try to load (via $http, `template:`, or `templateUrl:`) should come from the `$templateCache`, so this means that if a template does not exists in the `$templateCache` - it does not exists in your project. 
By default, when you try to load `.html` file using AngularJS, it try to find it inside the `$templateCache`, and if it does not exists, it tries to load it from your server.
The `templates-handler.js` overrides this behavior and try to fetch the template from the `$templateCache`, and it the file you tried to load does not exists and SHOULD exists (because every `.html` goes to the `$templateCache` when using Angular-Meteor), it throws an error, and it the file is not a common template file, it just runs the regular `$templateCache.get` logic. 

So in this point, I suggest you to check with your `$templateCache` if you have every `.html` that loaded to your project. You can do it by debugging AngularJS code, in about line #6061 (the `$templateCache.get` method), and check for the `data` variable, it should contain an object with all the keys of the existing templates.

You can also debug the actual process of adding the `.html` files to the $templateCache and check which files are included, by adding a `console.log(id)` here:
https://github.com/Urigo/angular-meteor/blob/master/packages/angular-templates/plugin/ng-template-compiler.js#L112
And check for the build's log (the output of Meteor CLI). 

Also, if you try to load `.html` file from a package, I think you need to include `angular` package using `api.use` in order to make sure that Angular-Meteor will compile the templates inside your package. 

Please let me know how its going, thanks!

**Comment by dotansimha** [comment]
@buitregool ?

**Comment by buitregool** [comment]
Hi @dotansimha. Thank u for taking the time for your detailed explanation. I tried what you suggested but it didn't work out. The reason is because the exception above is been thrown even before the lines you are talking about (i.e: ng-template-compiler.js#L112).  Again, ```templates-handler.js``` works fine. Only the validation/exception is wrong to my criteria.
```
  var templatesFileExtension = ['html', 'tpl', 'tmpl', 'template', 'view'];
  ...
  if (templatesFileExtension.indexOf(fileExtension) > -1) {
    throw new Error('[angular-meteor][err][404] ' + templatePath + ' - HTML template does not exists!');
  }
```
I may be to naive, I apologize. But think about it: If the array is design to come out with positive indexes from the different types of path files extensions, there is no way this last line can be right. 
Sorry can't do better. Cheers.

**Comment by dotansimha** [comment]
@buitregool 
The logic is as follow:
If the template **does not exists** in the `$templateCache` (the return value is not defined), the check if the extension is included in the `templatesFileExtension` (index is bigger than -1) - which means the template **should** exists, but it **does not exists** - then throw the exception... 

And in simple words: If there is no template in the `$templateCache`, and it's an HTML file - throw an error, because something went wrong during the compile time.

You problem seems to be that the template exists as HTML file, but the template compiler did not save it in the `$templateCache` - which is not the behavior that `angular-meteor` expects, because it does save all `.html` files into the `$templateCache`.

Can you please provide your project (or example the demonstrate the problem) so I can run it in my localhost? 

Thanks

**Comment by a-vasyliev** [comment]
Hi, guys. 

I've same issue. I'm building modular application, so each part of the system is in local package.
I'm trying to create parent route /admin where app will have admin interface.
I want to have single Angular application with nested views. So, layouts will be changed for /, /account and /admin parts of the system and "content" will be rendered into each of the "layouts".

./index.html:
```
<head>
    <base href="/">
</head>
<body ng-app="app-name">
    <div ui-view=""></div>
</body>
```

./packages/module-name/package.js:
```
api.addFiles([ 'client/admin.html']);
api.addFiles(['client/theme.js'], 'client');
```

Here I want to define admin template which will be common for all /admin/* routes. Ng-view should allow me to change "content" of pages.
./packages/module-name/client/admin.html
```
<div>
    Test!
    <div ng-view=""></div>
</div>
```

./packages/module-name/client/theme.js:
```
var module = angular.module('app-name', ['angular-meteor', 'ngMaterial', 'ui.router']);

module.config(function ($urlRouterProvider, $stateProvider, $locationProvider) {
    $locationProvider.html5Mode(true);

    // it should do nothing, other modules will add "sub-routes" to it.
    $stateProvider.state('admin', {url: '/', 'template': '<admin></admin>'});
});

angular.module('app-name').directive('admin', function () {
    return {
        templateUrl: 'admin.html',
        controllerAs: 'admin'
    }
});
```

I'm really sorry if it is wrong place to ask about this issue. Perhaps there is some my mistake. I'm new to NodeJs, Meteor, Angular...

**Comment by simonv3** [comment]
I'm returning to a project written in an earlier version of Angular-Meteor that uses packages and am stumbling across the same issue. 

package.js:
```
Package.on_use(function (api) {
  api.versionsFrom('1.1.0.3');

  api.use('accounts-password@1.1.1');
  api.use('email@1.0.6', 'server');
  api.use('mongo@1.1.0', ['client', 'server']);

  api.use('angular@1.3.2', 'client');

  api.addFiles('meteor-running.js', 'client');

  var clientFiles = [
    'client/js/directives/account-buttons.directive.js',
    'client/js/directives/account-buttons.html',
  ];
  api.addFiles(clientFiles, 'client');
});
```

`client/js/directives/account-buttons.directive.js`
```
angular.module('meteor-running')
  .directive('mrAccountButtons', function ($state, $rootScope) {
    return {
      restrict: 'A',
      scope: true,
      link: function ($scope) {
        $scope.state = $state;
      },
      templateUrl: 'simonv3_meteor-running_client/js/directives/account-buttons.html',
    };
  });
```

`clients/js/directives/account-buttons.html`
```
<div class="registration"
  ng-if="state.current.name !== 'setup'">
  <a class="button"
    ng-href="/login"
    ng-hide="$root.currentUser">Log in</a>
  <a class="button"
    ng-href="/register"
    ng-show="!$root.currentUser && activeSurvey.require_sign_in">Register</a>
  <div class="username"
    ng-show="$root.currentUser">
    Hello <span ng-bind="$root.currentUser | displayName"></span>
  </div>
  <a class="button"
    ng-href="/logout"
    ng-show="$root.currentUser">Log out</a>
</div>

```

I've just pushed these test versions to the package here: https://github.com/simonv3/meteor-running

**Comment by austingayler** [comment]
@a-vasyliev try `templateUrl: "'admin.html'"`, instead of `templateUrl: 'admin.html'`

**Comment by a-vasyliev** [comment]
@austingayler Thanks, I've found solution. It is required to provide template url with package name:
```
templateUrl:"/packages/your_package_name_here/client/template.html"
```

It is not obvious and there is not so much information about Meteor packages, AngularJS integration and modular apps...

**Comment by Urigo** [comment]
@a-vasyliev where do you think we can update the docs to reflect this?
Would love want to create a pull request to update the docs to make them better?

**Comment by jonmc12** [comment]
@simonv3 thank you - very helpful to look up the template location using ```$templateCache.put()``` in compiled package js.

**Comment by patrickdevivo** [comment]
Anyone have the status of this issue? Seeing the same error as initially posted.

**Comment by simonv3** [comment]
Hey @patrickdevivo have you tried what I went through?

**Comment by patrickdevivo** [comment]
@simonv3 it seems like that's for code that's been included as a package though, no? I have my templates directly in client/templates of my app. Unless I'm misunderstanding?

**Comment by simonv3** [comment]
@patrickdevivo hmm, you're right, though I suspect it's the same error. Can you investigate your compiled templates file? You can do this by looking in the `<head>` of your local instance and I think (though I don't have an instance running right now to check) it'll probably be in your-app.js name, and then do a find for templateCache.

**Comment by patrickdevivo** [comment]
@simonv3 thanks for the tip, I checked all the places where `$templateCache.put` is called, and the keys match all the places I use `templateUrl`. This could be a problem with Ionic? https://github.com/driftyco/ionic/issues/4766 which I'm using as well.

**Comment by patrickdevivo** [comment]
I just fixed it...and I feel very foolish. Just needed to include `angular-meteor` before `ionic` in the app dependencies!

**Comment by Urigo** [comment]
OK just to summarize the solution.
If adding a template from a package, use:

    templateUrl: "/packages/your_package_name_here/client/template.html"

Also look at the detailed answer here: https://github.com/Urigo/angular-meteor/issues/958#issuecomment-166897834

**Comment by cubitworx** [comment]
Just to add to the post about the templateUrl being:

    templateUrl: "/packages/your_package_name_here/client/template.html"

If your package has a prefix then you need to include the prefix before the package name with a semicolon as a separator within the url as follows:

    templateUrl: "/packages/your_prefix_here:your_package_name_here/client/template.html"

I seem to remember somewhere that the prefix and package name should be concatenated with an underscore but this might either have changed or be different for angular-meteor.

Thanks for the great work, Urigo!

**Comment by Urigo** [comment]
@cubitworx do you think the current docs are enough?
would you add/change something about this?

**Comment by cubitworx** [comment]
@Urigo If you are referring to the [Meteor-Angular Socially App Tutorial](http://www.angular-meteor.com/tutorials/socially/) then I think the more information the better :)

My preferred suggestion (but more work) would be to change the tutorial to include a prefix; since I am a firm believer that all apps & packages should always be prefixed in order to future proof them against namespace conflicts.

An easier fix would probably be to add something to step 21. You could probably just add the following note after code snippet `21.13  Implement the actual browser login component`:

> **A note on package name prefixing**
It is important to note that if you include a prefix in the declaration of your package name (as seen in `21.11  Create socially-browser package`) then you should remember to include this prefix in absolute path references elsewhere. E.g. if package name is declared as
`name: 'my-prefix:socially-browser'`
then the templateUrl in the above code snippet would need to read
`templateUrl: '/packages/my-prefix:socially-browser/client/auth/login/login.html'`

Or something like that. It is a bit verbose but I can't think of how to make it succinct without loosing the meaning.

**Comment by a-vasyliev** [comment]
My suggestion is to add tutorial which explains how to build modular apps with Meteor. This topic is much bigger than it appears: how to create packages, recommendations, best practices, examples how to use it with other packages, etc. I think it is necessary to create such tutorial. It took hours from me to understand how to build the same tutorial app, but using packages... (originally I'm PHP developer so Javascript/NodeJs world appear to me very big, interesting, but it is not so easy to understand it).

**Comment by cubitworx** [comment]
@a-vasyliev Although I do agree that would be useful. However, I don't think it is limited to the angular-meteor package and so would be a tutorial applicable to the meteor community as a whole. It is a methodology that is starting to gain a lot of traction in the meteor community but I can see this being reversed if meteor decides to implement some ability to define load order to files in the root application.

**Comment by Urigo** [comment]
great ideas.
Would love some PRs as well :)

**Comment by cubitworx** [comment]
@Urigo I'm not sure this warrants a feature request so I'll just make a comment here in case you think there is something to it...

One thing I was surprised about is that you chose to stick with absolute path references considering that meteor is geared around finding templates in files regardless of where they are located. Is there nothing we can do to declare templates inside files instead of by absolute file names?

Using a named template instead of an absolute path to a file would allow package authors to move files around in the package without breaking backwards compatibility. So templateUrl could instead be defined as follows:

    templateUrl: 'my-prefix:socially-browser/auth/login.html'

blaze template syntax in package 'my-prefix:socially-browser':

    <template name="auth/login.html">
    </template>

or angular template syntax in package 'my-prefix:socially-browser':

    <script type="text/ng-template" id="/auth/login.html">
    </script>

This is probably an argument that the angular purists will argue against :)

**Comment by a-vasyliev** [comment]
@cubitworx +1 :)

**Comment by Urigo** [comment]
@cubitworx interesting.
Best way is to open it as a PR and start discussing it there.

**Comment by kokokenada** [comment]
I've run into this problem running in Cordova only (works fine with web). (Everything is in packages.) I am loading the dependencies and packages differently, so I'm not sure if that's the reason.  Oddly, just changing the code to not throw the exception works around the problem.

Change:

    throw new Error('[angular-meteor][err][404] ' + templatePath + ' - HTML template does not exists!');

to

    console.log('[angular-meteor][err][404] ' + templatePath + ' - HTML template does not exists!');


Or just avoid loading angular-templates.js.

**Comment by Urigo** [comment]
@kokokenada please read this comment carefully - https://github.com/Urigo/angular-meteor/issues/958#issuecomment-166897834
If it's still not working for you, can you create a reproduction in a repo and send it here?
thanks

**Comment by eric-2d** [comment]
Hello,
I have the same issue and completely unable to resolve it.
I created a demo app with the problem here: https://github.com/eric-2d/meteor-angular-broken-templates

The app was created using a yeoman generator angular-meteor as follow:
````
/spare/tmp
↳ yo angular-meteor testApp
? What would you like to write scripts with? JavaScript
? What would you like to write markup with? HTML
? What would you like to write stylesheets with? CSS
? Would you like pagination, sorting and searching support? No
? Select a CSS framework Bootstrap
? Would you like to use user authentication? No
Created a new Meteor app in 'testApp'.        

To run your new app:                          
  cd testApp                                  
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn                
                                              
                                              
Changes to your project's package version selections:
                                              
blaze-html-templates   removed from your project
caching-compiler       removed from your project
caching-html-compiler  removed from your project
templating             removed from your project
templating-tools       removed from your project

blaze-html-templates: removed dependency      
ecmascript: removed dependency                
                                              
Changes to your project's package version selections:
                                              
angular                             added, version 1.3.11
angular-meteor-data                 added, version 1.3.11
angular-templates                   added, version 1.0.3
angular-templates-runtime           added, version 0.0.1
angular:angular                     added, version 1.4.8
angularui:angular-ui-bootstrap      added, version 0.13.0
angularui:angular-ui-router         added, version 0.2.15
benjamine:jsondiffpatch             added, version 0.1.38_1
caching-compiler                    added, version 1.0.6
caching-html-compiler               added, version 1.0.6
dburles:mongo-collection-instances  added, version 0.3.4
lai:collection-extensions           added, version 0.1.4
pbastowski:angular-babel            added, version 1.0.9
reactive-dict                       added, version 1.1.8
session                             added, version 1.1.6
templating-tools                    added, version 1.0.4
twbs:bootstrap                      added, version 3.3.6

                                              
angular: Everything you need to use AngularJS in your Meteor app
angularui:angular-ui-router: angular-ui-router (official): Flexible routing with nested views in AngularJS
twbs:bootstrap: The most popular front-end framework for developing responsive, mobile first projects on the web.
angularui:angular-ui-bootstrap: Native AngularJS (Angular) directives for Bootstrap.
                                              
Changes to your project's package version selections from updating package versions:
                                              
angular:angular                     upgraded from 1.4.8 to 1.5.3_1
dburles:mongo-collection-instances  upgraded from 0.3.4 to 0.3.5
lai:collection-extensions           upgraded from 0.1.4 to 0.2.1_1
pbastowski:angular-babel            upgraded from 1.0.9 to 1.3.6

````

At this point everything runs just fine with the latest version of meteor, all is well.

Now I run
````
/spare/tmp
↳ cd testApp
/spare/tmp/testApp
↳ meteor update
This project is already at Meteor 1.3.5.1, the latest release.
                                              
Changes to your project's package version selections from updating package versions:
                                              
angular-templates           upgraded from 1.0.3 to 1.0.5
angular-templates-runtime   removed from your project
caching-html-compiler       removed from your project
templating-tools            removed from your project
urigo:static-html-compiler  added, version 0.1.4

````
Then I get the message about template not found

So I proceed to turn the error off as described here:  http://www.angular-meteor.com/api/1.3.11/templates

But then a cascade of errors then follows:
````
[angular-meteor][err][404] client/components/toolbar/toolbar.view.ng.html - HTML template does not exists! You can disable this warning by following this guide http://www.angular-meteor.com/api/1.3.11/templates
templates-handler.js:35[angular-meteor][err][404] client/components/toolbar/toolbar.view.ng.html - HTML template does not exists! You can disable this warning by following this guide http://www.angular-meteor.com/api/1.3.11/templates
templates-handler.js:35[angular-meteor][err][404] client/main/main.view.ng.html - HTML template does not exists! You can disable this warning by following this guide http://www.angular-meteor.com/api/1.3.11/templates
angular_angular.js?hash=08f63d2…:13439 Error: [$compile:tplrt] Template for directive 'toolbar' must have exactly one root element. client/components/toolbar/toolbar.view.ng.html
http://errors.angularjs.org/1.5.3/$compile/tplrt?p0=toolbar&p1=client%2Fcomponents%2Ftoolbar%2Ftoolbar.view.ng.html
    at angular_angular.js?hash=08f63d2…:83
    at angular_angular.js?hash=08f63d2…:9317
    at processQueue (angular_angular.js?hash=08f63d2…:15772)
    at angular_angular.js?hash=08f63d2…:15788
    at Scope.$eval (angular_angular.js?hash=08f63d2…:17040)
    at Scope.$digest (angular_angular.js?hash=08f63d2…:16856)
    at Scope.$apply (angular_angular.js?hash=08f63d2…:17148)
    at done (angular_angular.js?hash=08f63d2…:11469)
    at completeRequest (angular_angular.js?hash=08f63d2…:11667)
    at XMLHttpRequest.requestLoaded (angular_angular.js?hash=08f63d2…:11608)
**jquery.js:9620 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.**
**VM2813:30569 WARNING: Tried to load angular more than once.**
angular_angular.js?hash=08f63d2…:13439 Error: only one instance of babel/polyfill is allowed
    at Object.eval (eval at <anonymous> (http://localhost:3000/packages/jquery.js?hash=22a0055f59bd150c435c5aba34c7c59076b8bcd9:397:22), <anonymous>:2872:9)
    at Object.1.180 (eval at <anonymous> (http://localhost:3000/packages/jquery.js?hash=22a0055f59bd150c435c5aba34c7c59076b8bcd9:397:22), <anonymous>:2875:4)
    at s (eval at <anonymous> (http://localhost:3000/packages/jquery.js?hash=22a0055f59bd150c435c5aba34c7c59076b8bcd9:397:22), <anonymous>:2863:254)
    at e (eval at <anonymous> (http://localhost:3000/packages/jquery.js?hash=22a0055f59bd150c435c5aba34c7c59076b8bcd9:397:22), <anonymous>:2863:425)
    at eval (eval at <anonymous> (http://localhost:3000/packages/jquery.js?hash=22a0055f59bd150c435c5aba34c7c59076b8bcd9:397:22), <anonymous>:2863:443)
    at eval (eval at <anonymous> (http://localhost:3000/packages/jquery.js?hash=22a0055f59bd150c435c5aba34c7c59076b8bcd9:397:22), <anonymous>:7043:4)
    at eval (eval at <anonymous> (http://localhost:3000/packages/jquery.js?hash=22a0055f59bd150c435c5aba34c7c59076b8bcd9:397:22), <anonymous>:7050:3)
    at http://localhost:3000/packages/jquery.js?hash=22a0055f59bd150c435c5aba34c7c59076b8bcd9:397:22
    at Function.globalEval (http://localhost:3000/packages/jquery.js?hash=22a0055f59bd150c435c5aba34c7c59076b8bcd9:398:7)
    at text script (http://localhost:3000/packages/jquery.js?hash=22a0055f59bd150c435c5aba34c7c59076b8bcd9:9824:11) <div ui-view="" class="ng-scope">
````

I don't know how to inspect the compiled templates nor anything about packages or prefixes.
Any help appreciated!
