### ISSUE TITLE
Helpers not logging correct values in production (minifaction?)

### ISSUE THREAD

**Issue by vacarsu** [Urigo/angular-meteor#960]
``` javascript
class app extends ReactiveComponent {
  constructor () {
    super(arguments);
    this.helpers({
      currentUser() { return Meteor.user() },
      isAdmin() { return Permissions.hasPermission(Meteor.userId(), 'admin') },
    })

    console.log(this.currentUser);
    console.log(this.isAdmin);
  }
}
```
On localhost the two values log the user object, and true respectively. However on the production host I'm getting undefined for the user object, and false for isAdmin.

**Comment by Deadly0** [comment]
@vacarsu data may be not loaded when you try to log it. Use $watch/autorun to be sure that data was loaded.

**Comment by Urigo** [comment]
Probably related to #968

**Comment by Urigo** [comment]
@vacarsu have you tried changing `currentUser` to `currentUser1` ?
Did it help?

**Comment by Urigo** [comment]
@vacarsu please use the new `angular-with-auth` package - http://www.angular-meteor.com/api/1.3.2/auth
Reopen if that doesn't work for you
