### ISSUE TITLE
No such template '_resetPasswordDialog' when running my app in another machine

### ISSUE THREAD

**Issue by mgrivera** [Urigo/angular-meteor#961]
Hi all, 

I copied my project to another PC. I moved everything, except the directory *local* in *.meteor*. I saw that this was the only file (ie: dir) in *.gitignore*, so I ignored it when copying files from one PC to another. 

Then I did a 'meteor run' in the other PC and everything worked fine. I run my app in the browser and everything worked. However, I got this message in debugger whenever my code tried to open a modal: 

>Error: No such template '_resetPasswordDialog'

Now, everything works fine in the original PC. Evidently, meteor downloaded and installed every needed packpage in the second PC; and everything works fine *but* this error when trying to open a modal. I open my modals using *angular-ui*. 

Any ideas why this may be happening? 

Thanks and bye ...

**Comment by mgrivera** [comment]
Hi, just to say that this issue was fixed when I upgraded angular meteor package to the new version. 
Thanks and bye ...

**Comment by Urigo** [comment]
thanks for updating
