### ISSUE TITLE
(v1.3) TypeError: Cannot read property 'changed' of undefined

### ISSUE THREAD

**Issue by eugenious** [Urigo/angular-meteor#968]
I'd like to report a subtle bug which I tracked down to this point:

In my ui-router state definition I have:
```js
    controller: function($scope) {
      $scope.helpers({
        currentUser() {
          return Meteor.user();
        }
      });
    }
```

When there is no logged in user:

**Expected**
currentUser to be undefined

**Actual**
I got a console error:
TypeError: Cannot read property 'changed' of undefined
    at ReactiveContext._propertyChanged (http://localhost:3000/packages/angular-meteor-data.js?

It is a subtle bug because other combinations work without a problem:

**This is ok: (the variable has changed to currentUser1)**
```js
    controller: function($scope) {
      $scope.helpers({
        currentUser1() {
          return Meteor.user();
        }
      });
    }
```

**This is ok: (using controllerAs syntax)**
```js
    controllerAs: 'myctrl',
    controller: function($scope, $reactive) {
      $reactive(this).attach($scope);
    
      this.helpers({
        currentUser() {
          return Meteor.user();
        }
      });
    }
```

As far as I can tell, it seems that the problem is with the variable $scope.currentUser, which is *already* defined, and so my controller in fact was trying to redefine it. It is already defined for backwards compatibility reasons pre 1.3.

Even though currentUser is already defined, I would like to define it myself again, because $scope.currentUser is deprecated and [going away in 1.4](http://www.angular-meteor.com/api/1.3.0/auth)

So to repeat this is only a bug for those NOT using controllerAs syntax, and redefining variables that already exist. (other variables may have this problem too).

This is closely related to #944, and in fact might be the same issue (that issue couldn't be reliably reproduced).

**Comment by atoftegaard** [comment]
I receive the same error, however in a slightly different scenario. If I refresh my browser on the faulty page, and it does a full page refresh, there is no error. If I reload the browser on a different page, and then navigate to the faulty page, I get the error. It seems related to Meteor.user(), but it happens even though I am logged in. My directive looks like this:

    .controller('TeamDetailsCtrl', function($scope, $reactive, $uibModal) {

	    	// attach the reactive context to angular scope
	    	$reactive(this).attach($scope);
	    	let reactiveContext = $reactive(this).attach($scope);
	    	var self = this;

    		// subscribe to any changes
    		reactiveContext.subscribe('teams');
    		reactiveContext.subscribe('teamInvitees');

	    	// fetch models reactively
	    	this.helpers({
	    		team: () => getTeam(Meteor.userId()),
	    		invitees: () => getTeamInvitees(Meteor.userId()),
	    		teamInvites: () => Teams.find({ _id: { $in: Meteor.user().profile.invites || [] } })
	    	});
    	}
    })

I use the controllerAs style, if thats of any concern.

**Comment by eugenious** [comment]
There's too much code here, try and see if you can narrow it down to one line. I can guess that maybe it's the Meteor.user().profile.invites which is giving the error. Maybe when everything starts up, Meteor.user() *starts* by being undefined and you should handle that case in your code?

Just guessing.

**Comment by Urigo** [comment]
@eugenious please use the new `angular-with-auth` package - http://www.angular-meteor.com/api/1.3.2/auth
Reopen if that doesn't work for you

**Comment by eugenious** [comment]
Thanks for the great work. I think this is heading in the right direction.

If I understand correctly, I should be able to use the $auth service to replace the Meteor global variable. That sounds like a good approach, so here's what I did:

This is what I had previously (it works fine):
```js
    controller: function($scope) {
      $scope.helpers({
        isLoggedIn() {
          return Meteor.userId() !== null;
        }
      });
    }
```

Using the new $auth service:
```js
    controller: function($scope, $auth) {
      $scope.helpers({
        isLoggedIn() {
          return angular.isDefined($auth.currentUser);
        }
      });
    }
```

I must be missing something, because I can't get this to work:

* isLoggedIn always returns `false`, regardless if a user is logged in or not
* doesn't seem to be reactive either

By the way, and this might not be related to the issue, I noticed that $scope.$auth.currentUser is returning the correct user (reactively), however I didn't even expected $scope.$auth to be defined at all since I hadn't defined it.

What am I doing wrong?

Sorry, this isn't even the same bug anymore, and may not even be a bug, but I was asked to reopen the issue.

**Comment by eugenious** [comment]
Actually, I don't have enough permission to reopen the issue.

@Urigo perhaps you could advise how to proceed, either reopen this bug, create a new bug, or if you could tell me what I'm doing wrong it would be appreciated!

**Comment by Urigo** [comment]
opened, will look on it soon

**Comment by eugenious** [comment]
#1064 describes the current situation better, so I'm closing this one

**Comment by justingrayston** [comment]
Just to state, I am getting the "TypeError: Cannot read property 'changed' of undefined" error. At the moment I am not convinced it is to do with Meteor.user at all, or #1064 (although I have seem $auth.currentUser not populated, but that was on a different view completely).

Interestingly, this is a controller for a directive not a view, and it is loaded as part of the parent page. I have a $auth.waitForUser which works fine. 

I am going to pull it apart a little before going any further, and will report back when/if I find what is causing for me.

**Comment by justingrayston** [comment]
Argh. For me it was literally timing and the fact at the top of the controller I had old code that set a default value for the $scope property. I didn't see the 'will be overwritten' warning in the console, because the error happened before that was caused.
```js
_propertyChanged(k) {
      if (this.scope && !this.scope.$$destroyed && !$rootScope.$$phase) {
        this.scope.$digest();
      }

      this.propertiesTrackerDeps[k].changed();
    }
```

So k must be undefined but it also must know it should be tracking it.

Just removing the declaration at the top of the controller made the problem go away, because the helper set the property on $scope.

BAD:
```js
$scope.myLovelyThings = [];

$scope.helpers({
  myLovelyThings: ...
});

```
