### ISSUE TITLE
Tutorial - Angular 1 - Step 3 shows no parties

### ISSUE THREAD

**Issue by gjr-qm** [Urigo/angular-meteor#979]
On my local machine it runs ok, but http://socially-step03.meteor.com/ shows no parties...

Developertools in Chrome show the parties are in the partiesList, but somehow angular is not aware of that.

**Comment by Urigo** [comment]
I think the deployed version is not updated yet, will try top update it tomorrow

**Comment by gjr-qm** [comment]
On my local machine with 1.3.1. it's ok!

**Comment by dotansimha** [comment]
@gjr-qm , 1.3.1 fixes that, just deployed the latest version of step 3 to http://socially-step03.meteor.com. 

Thanks!
