### ISSUE TITLE
Clean up subscriptions after scope destruction

### ISSUE THREAD

**Issue by hyperborea** [Urigo/angular-meteor#98]
The $subscribe service (and similarly the publisher argument in $collection.bind) currently only subscribes to the publication and returns a promise, but won't perform any clean up when the scope has been destroyed. This leads to over subscription when used in ui-router. How are you dealing with that problem?

I'm currently doing the following within the route controller:
```javascript
var sub = Meteor.subscribe('foo');
$scope.$on('$destroy', sub.stop);
```

Note that I'm not using $subscribe as that's not returning the subscription. Should we perhaps implement support for that in $collection.bind and $subscribe? Is there a better way?

**Comment by Urigo** [comment]
@hyperborea haha, we we're just talking about both of those issue and how we want to see them in the new 0.6 API !!
Will be solved very soon with the new API.
watch for the release (probably in the middle of next week)

**Comment by Urigo** [comment]
Probably the first solution will be to return the subscription and let you handle the cleaning yourself, that's because it is not obvious that you would want to stop the subscription when the scope is being destroyed as the subscription, like the collection, is global.
Unless you think differently - please share your thoughts

**Comment by hyperborea** [comment]
Awesome, looking forward to the new release! :)

Thinking about it again you're absolutely right in regards to the subscribe service, that one really shouldn't be opinionated. $collection.bind on the other hand is binding directly to the scope, so perhaps it would make sense for the publisher argument there to handle scope destruction?

**Comment by Urigo** [comment]
Fixed in the new version:
https://github.com/Urigo/angular-meteor/releases/tag/0.6.0-alpha

Please check yourself and re-open in case of a problem.

Thank you so much for reporting and suggesting this!
