### ISSUE TITLE
Tutorial - Angular 1 - Step 4 database updates have to be triggered to get on screen 

### ISSUE THREAD

**Issue by gjr-qm** [Urigo/angular-meteor#980]
Same as Step 3: Initially parties are not loaded and updates from other clients are not visible until you trigger them with a digest cycle (typing a character in one of the inputs for example).

I didn't try this on my machine, but http://socially-step04.meteor.com/ shows the issue.

**Comment by Urigo** [comment]
Might be that the deployed version in not updated.
Can you please try to run locally?

**Comment by gjr-qm** [comment]
A local run (with 1.3.1) doesn't have this problem.

**Comment by dotansimha** [comment]
Thanks @gjr-qm! deployed a new version of step 4 with 1.3.1.
