### ISSUE TITLE
(v1.3.1)Data change not be saved to MongoDB when using ui-grid!

### ISSUE THREAD

**Issue by michaelszt** [Urigo/angular-meteor#981]
After I moved my code from v1.2.3 to v1.3.1 , I always can not make my ui-grid work correctly. Here is my code:

    angular
        .module('Aries')
        .controller('TPSCtrl', TPSCtrl);
    TPSCtrl.$inject = ['$scope', '$reactive'];
    function TPSCtrl($scope, $reactive){
        $reactive(this).attach($scope);
        $scope.subscribe('termparams');
        $scope.helpers({
            tps: function()  {
                return TermParams.find({});
            }
        });
        $scope.gridTPS = {
            columnDefs: [
                { name:'name', field: 'name', displayName:'Name', enableCellEdit:false },
                { name:'tag', field: 'tag', width:100, enableCellEdit:false },
                { name:'len', field: 'len',  displayName:'Length', width:100, enableCellEdit:false },
                { name:'val', field: 'val', displayName:'Value', enableCellEdit:true}
            ]
        };
        $scope.gridTPS.data = $scope.tps;
    }

When I edit the value in the grid, change cannot be saved to MongoDB.

**Comment by Urigo** [comment]
First thing is that if you are in a regular $scope syntax, you don't need to add `$reactive(this).attach($scope);` but I'm not sure if that's your problem.
Can you please share a full repo I can play with?

**Comment by michaelszt** [comment]
@Urigo ,I create a demo repo, https://github.com/michaelszt/demo
In file "client/term/controllers/termParams.js", the current code can not work correctlly, and the commented code below is my original code based on v1.2.3, which can save data change to MongoDB after edit ui-grid.

**Comment by activeperception** [comment]
+1 same problem

**Comment by dotansimha** [comment]
Hi @michaelszt, do you mean the you used the auto-bind feature in 1.2.x? because it does not available in 1.3...

**Comment by michaelszt** [comment]
@dotansimha ,thank you for your help, do you know how to use ui-grid in 1.3.1?

**Comment by michaelszt** [comment]
@Urigo , do you have any solution for using ui-grid in 1.3.1?

**Comment by dotansimha** [comment]
@michaelszt , you need to create a server side method that will update your data in the MongoDB.
Start by using `Meteor.methods` in the server side, and the call your function using `Meteor.call` in the client side. 
You can use ui-grid's API to know when the user changes the data, I think this feature called `afterCellEdit`. 
Please re-open if you have any further questions.
