### ISSUE TITLE
1.3.1 reactive-context override reactive-scope

### ISSUE THREAD

**Issue by hlehmann** [Urigo/angular-meteor#983]
`$scope.getReactively` and `$scope.helpers` are defined by reactive-context causing unexpected results only after 1.3.1

**Comment by Urigo** [comment]
The goal is to make both `$scope.getReactively` and `this.getReactively` work.
Can you please share what is that a problem you are experiencing?

**Comment by hlehmann** [comment]
I reuse your example but with `$scope`
```javascript
myModule.controller('MyCtrl', ['$scope', function($scope) {
  $scope.myUser: {
    id: 10
  };

  $scope.helpers({
    myData: () => {
      return Data.find({_id: $scope.getReactively('myUser.id')});
    }
  });

  $scope.myUser.id = 29;
}]);
```
Problem: `$scope.getReactively('myUser.id')` return undefined.

I find that `$scope.getReactively` is pointing to the method defined in reactive-context and not in reactive-scope.

**Comment by hlehmann** [comment]
By the way, I have no issue with the `this` version

**Comment by Urigo** [comment]
Ohhh, you need to change 

    $scope.myUser: {
        id: 10
    };

to 

    $scope.myUser = {
        id: 10
    };

Where is the example so I can update it as well?

**Comment by hlehmann** [comment]
Well unfortunately no...
Here a little repo that show what looks like an issue, it's the same example but the result is `10` and not `29`.
https://github.com/hlehmann/angular-meteor-demo/blob/master/client/hello.js#L10

**Comment by hlehmann** [comment]
After a timeout it seems to work
```
angular.module('app').controller('MyCtrl', ['$scope', '$timeout', function ($scope, $timeout) {
    $scope.myUser = {
        id: 10
    };

    $scope.helpers({
        myData() {
            return $scope.getReactively('myUser.id');
        }
    });
    console.log(1, $scope.myData);

    $scope.myUser.id = 29;
    console.log(2, $scope.myData);

    $timeout(()=> {
        $scope.myUser.id = 53;
        console.log(3, $scope.myData);
    }, 100);

    $timeout(()=> {
        console.log(4, $scope.myData);
    }, 200);
}]);
```
console:
```
1 10 hello.js:13:5
2 10 hello.js:16:5
3 10 hello.js:20:9
4 53 hello.js:24:9
```

**Comment by dotansimha** [comment]
@hlehmann , fixed in https://github.com/Urigo/angular-meteor/commit/d42a1853807c1604b4391f030115bf9ab7679ee6

@netanelgilad @Urigo, please review it

**Comment by torayeff** [comment]
@Urigo What does this mean:
```[angular-meteor][helpers] Your tried to create helper for primitive 'searchText', please note that this feature will be deprecated in 1.4 in favor of using 'getReactively' - http://www.angular-meteor.com/api/1.3.1/get-reactively```

Do we need to use again:
``` this.getReactively('searchText') ```
instead of defining in helpers?
