### ISSUE TITLE
Cannot handle 404 

### ISSUE THREAD

**Issue by dyaa** [Urigo/angular-meteor#986]
Hey All,

I'm using Angular-meteor using the AngularUI Router and i cannot handle the `404` errors, I'm wondering if anybody had to deal with that specially it's `ABC` for SEO.

Currently i'm redirecting any not found entities to the route `/404` but with status code is `200`.

For more information i'm also using Meteor's `spiderable` package for rendering the page.

Also i found [Prerender.io][1] has their own solution using this metatag : 

```html
<meta name="prerender-status-code" content="404">
```

Will [Prerender][1] be my solution or there's another way without dealing with other services !

[1]: https://prerender.io

**Comment by dotansimha** [comment]
Hi @dyaa , 
The 404 issue is a Meteor's issue, and not Angular-Meteor. 
Also, we recommend using AngularJS routers (such as `ngRouter` or `angular-ui-router`) which eliminates the need to handle routes on the server side. 

You can also try to use `iron-router` inside a package, load it only in the server side, and create a route for 404 with the correct header. 
For more information about Meteor and 404, please follow https://github.com/iron-meteor/iron-router/issues/1055
