### ISSUE TITLE
Match.check(1, Number) throws an exception in iOS Chrome or desktop Safari

### ISSUE THREAD

**Issue by super5354** [Urigo/angular-meteor#988]
Match.check(1, Number) throws an exception in iOS Chrome or desktop Safari causing operations like below fails to run
```
AnyCollection.find({}, { limit:1 })
```
because it fails to validate the type of the limit argument as Number

I suspect that the pbastowski:angular-babel package, which angular-meteor depends on, is doing something funny with the Number constructor

Any idea how to get this working please?

**Comment by dotansimha** [comment]
Hi @super5354,
Can you provide a running example? 

Also, did you try to check `pbastowski:angular-babel`, for known issues? 

Thanks.

**Comment by super5354** [comment]
The problem can be reproduced using the simple-todo example (https://www.meteor.com/tutorials/blaze/creating-an-app) with below modifications.

simple-todos.html
```
<head>
  <title>simple-todos</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}
</body>

<template name="hello">
  <p>Check Number = {{test}}</p>
</template>

```
simple-todos.js
```
if (Meteor.isClient) {
  // counter starts at 0

  Template.hello.helpers({
    test: function () {
      return Match.test(1, Number);
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    // code to run on server at startup
  });
}
```
packages
```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.

autopublish             # Publish all data to the clients (for prototyping)
insecure                # Allow all DB writes from clients (for prototyping)
check
templating
pbastowski:angular-babel
```

The left screen is desktop safari with the wrong result. You will find the same if you view the page with iOS chrome with iPhone.
![screenshots](https://cloud.githubusercontent.com/assets/16398829/11968691/e475d9c4-a949-11e5-8b18-364ca91e3e73.jpg)

I checked the github of angular-babel (https://github.com/pbastowski/angular-meteor-babel/). There is no outstanding issue.

**Comment by Urigo** [comment]
@pbastowski

**Comment by pbastowski** [comment]
Guys, I will look into this in a few hours.

**Comment by pbastowski** [comment]
@super5354 

Could you please post your `.meteor/versions` file here?

I just tried `Match.test(1, Number) ` in my Chrome 47.0.2526.80 console and it works fine, see below. Yes, I know you mentioned Chrome on IOS, but I needed a baseline :)

![image](https://cloud.githubusercontent.com/assets/5649024/11982655/644a10f8-a9ad-11e5-9258-878fdca36def.png)

In Safari 9.0.2 on OS X it also works fine

![image](https://cloud.githubusercontent.com/assets/5649024/11982688/a6156014-a9ad-11e5-8b0a-a7e3d6fbf08b.png)

**Comment by pbastowski** [comment]
@super5354 

It would help if you could upload a repo to github that reproduces the issue. Then, I can examine the exact same code and configuration as you are experiencing problems with.

**Comment by super5354** [comment]
@pbastowski here you go https://github.com/super5354/check-number.git

Sorry, I should be more specific. Chrome Windows works fine for me too; while Safari Windows 5.1.7, iOS Chrome and iOS Safari do not work. I am using angular-meteor for web/mobile app development. I found this issue when testing it with iPhone using browsers.

**Comment by pbastowski** [comment]
Windows Safari 5.1.7 is not supported, sorry. 

What IOS version are you testing with?

**Comment by super5354** [comment]
iOS: 8.3 (12F70)
iOS Chrome: 47.0.2526.107

**Comment by mxab** [comment]
this maybe related to this one: https://github.com/pbastowski/angular-meteor-babel

**Comment by mxab** [comment]
@super5354 can you check if the error disappears if you add the pbastowski:angular-babel package before the other packages (put it on top of the packages file)

**Comment by pbastowski** [comment]
@super5354 I confirm that on IOS 8.4 the test fails. On IOS 9, however, it works just fine.

@mxab Moving angular-babel to the top of the packages file does indeed fix the problem. Thanks for the workaround. Now, how do we fix it?

**Comment by super5354** [comment]
@mxab Thanks! The workaround does work. As long as the angular-babel package is placed before the mongo package, it starts to work probably because it is where the check package gets first reference and forces the check package to use the overridden Number function.

**Comment by zloirock** [comment]
https://github.com/zloirock/core-js/issues/38#issuecomment-76114855

**Comment by pbastowski** [comment]
@super5354 I have published v1.0.10 of `pbastowski:angular-babel`, which should fix this problem for you. Could you try it and let me know if it does? Thanks.

**Comment by super5354** [comment]
@pbastowski It seems that the latest version is v1.0.9 not v1.0.10 but it still works like a charm. Thanks very much!

$ meteor update pbastowski:angular-babel

Changes to your project's package version selections from updating package
versions:

pbastowski:angular-babel  upgraded from 1.0.7 to 1.0.9

**Comment by pbastowski** [comment]
@super5354 you are correct. Apparently 1.0.10 is not published on Atmospherejs yet. I'll do that on Tuesday when I get back home.

**Comment by Urigo** [comment]
Hi Paul, I want to release a new version and update the dependency, is the new version of angular-babel out?  thanks!

**Comment by Urigo** [comment]
@pbastowski

**Comment by pbastowski** [comment]
@Urigo I have checked and 1.0.9 is indeed the latest version for Meteor 1.2+. I got confused with 0.1.10, which is for Meteor 1.1 :)
