### ISSUE TITLE
Reactive function breaks after upgrading to 1.3.1

### ISSUE THREAD

**Issue by tvgrieken** [Urigo/angular-meteor#991]
Although below example is something you could achieve with a filter too, this used to work. I use this in a setting where I join collections in combination with the publish composite package.

Controller:
````
vm.helpers({
    doSomethingWithPartyId: () => {
        return someFunction
    }
});
function someFunction(partyId) {
    return 'Do something with partyId:' + partyId
}

```
Then in view:
```
{{vm.doSomethingWithPartyId(party._id)}}
```
This breaks for me after upgrading to 1.3.1

**Comment by dotansimha** [comment]
Hi @tvgrieken , can you provide the actual repository so I try it on my local meteor? 

Also, what is your purpose with returning the method inside the helper? It looks like nothing in your code needs to be reactive.. am I wrong? 

Please provide more information. Thanks!

**Comment by tvgrieken** [comment]
Hi @dotansimha !

I implemented the suggestions here to achieve reactive joins: https://github.com/Urigo/angular-meteor/issues/749

This part specific:

 ```
function DashboardController($meteor) {
    var vm = this;
    vm.posts = $meteor.collection(Posts).subscribe('postsWithComments')
    vm.comments = $meteor.collection(Comments).subscribe('postsWithComments')

    vm.postComments = function(postId) {
        return vm.comments.filter(function(comment) {
            return comment.postId == postId
        })
    }
}
```
Modified to 1.3 API and working as expected, achieving reactivity:

````
function DashboardController($meteor) {
    var vm = this;
    $reactive(vm).attach($scope);
    vm.subscribe('postsWithComments')
    vm.helpers({
        posts: () => {
            return Posts.find()
        },
        comments: () => {
            return Comments.find()
        },
        postsComments: () => {
            return postComments
        }
    });

    function postComments(postId) {
        return vm.comments.filter(function(comment) {
            return comment.postId == postId
        })
    }
}
```
This fails in 1.3.1:
```
TypeError: v4.postComments is not a function
```
Not sure which package is causing this. I hope you can reproduce this and / or have advice for an alternative implementation of the publish composite package.

**Comment by Urigo** [comment]
@tvgrieken why do you need `postsComments` helper if you already have the function?

**Comment by tvgrieken** [comment]
@Urigo I see. I was under the assumption that only the helper methods were reactive. 

So, I have some problems understanding the helper concept.
Could you elaborate on the difference between vars defined in the helper function vs. outside?

Thanks a lot

P.s. This did the trick:
```
function DashboardController($scope, $reactive) {
    var vm = this;
    $reactive(vm).attach($scope);
    vm.subscribe('postsWithComments')
    vm.helpers({
        posts: () => {
            return Posts.find()
        },
        comments: () => {
            return Comments.find()
        }
    });

    vm.postComments = postComments;

    function postComments(postId) {
        return vm.comments.filter(function(comment) {
            return comment.postId == postId
        })
    }
}
```

**Comment by Urigo** [comment]
Vars defined inside a helper are Meteor data sources that you want to connect to the view and update everytime they reactively change.
Any vars that are not from Meteor should stay pure Angular
