### ISSUE TITLE
blaze template

### ISSUE THREAD

**Issue by ThomsCass** [Urigo/angular-meteor#999]
I try to use this package with angular-meteor : 255kb:meteor-status

It has a template to import called meteorStatus

So what I did is this :

`meteor add urigo:angular-blaze-template`

`<blaze-template name="meteorStatus"></blaze-template>`

Here is the error I got : 

`ReferenceError: Template is not defined
    at link (http://localhost:3000/packages/urigo_angular-blaze-template.js?e5e45916605fdaac59a14f9b3c10470a66e725ca:36:13)`

**Comment by Urigo** [comment]
You should use `angular-with-blaze` package instead of the `angular` package in case you want to work also with Blaze templates

**Comment by ThomsC** [comment]
Ok but then you can't use angular template. I thought it was possible sometimes to combine both..

**Comment by Urigo** [comment]
It is possible, that's why it's called `angular-with-blaze`...

**Comment by ozsay** [comment]
@ThomsC you can.

All you need to do is save angular templates with `.ng.html` and blaze templates with `.html`.

This way angular and blaze won't collide.

**Comment by ThomsC** [comment]
But that what I did. And I got the problem above

**Comment by Urigo** [comment]
@ThomsC can you share your repo?

**Comment by ThomsC** [comment]
Ok not sure how to do that yet but I will

**Comment by Urigo** [comment]
https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/

**Comment by Urigo** [comment]
Closing until you will provide a reproduction

**Comment by ThomsC** [comment]
Here is the repo : https://github.com/ThomsC/angular-with-blaze.git,

the template with blaze is in client/index.ng.html

**Comment by kamilkisiela** [comment]
@ThomsCass You should update packages. It's working with latest releases

**Comment by Urigo** [comment]
great.
@ThomsCass feel free to re-open is that's not the case
